hibernate/hibernate-orm

hibernate-infinispan/src/main/java/org/hibernate/cache/infinispan/util/Caches.java
This fixes compatibility with Infinispan 8.0 (scheduled for inclusion in WildFly 10).
https://hibernate.atlassian.net/browse/HHH-9999
=> HHH-9999 Fix use of deprecated API in hibernate-infinispan

documentation/src/main/asciidoc/userguide/chapters/batch/Batching.adoc
While experimenting with StatelessSession I discovered that it does not
support lasy loading. I think this isn't imediately obvious and worth to
be included in the documentation.
See also http://stackoverflow.com/questions/34800788/does-statelesssession-support-lazy-loading
=> Document that StatelessSession does not support lazy loading

hibernate-core/src/main/java/org/hibernate/boot/archive/internal/StandardArchiveDescriptorFactory.java
Switch to an OS-independent  way of checking absolute paths
=> HHH-4161 - persistence.xml <jar-file> not following JSR220 spec

build.gradle, databases.gradle, hibernate-core/src/main/java/org/hibernate/id/IdentifierGeneratorHelper.java, hibernate-core/src/test/java/org/hibernate/id/QuotedIdentifierTest.java, hibernate-core/src/test/java/org/hibernate/test/event/entity/MergeListPreAndPostPersistTest.java, libraries.gradle
Fix for [HHH-9271](https://hibernate.atlassian.net/browse/HHH-9271)
=> HHH-9271 - IdentityGenerator broken with quoted identifiers

hibernate-core/src/main/java/org/hibernate/annotations/Immutable.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/JavaTypeDescriptorRegistry.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/SerializableTypeDescriptor.java, hibernate-core/src/test/java/org/hibernate/test/annotations/immutable/Caption.java, hibernate-core/src/test/java/org/hibernate/test/annotations/immutable/CaptionConverter.java, hibernate-core/src/test/java/org/hibernate/test/annotations/immutable/Exif.java, hibernate-core/src/test/java/org/hibernate/test/annotations/immutable/ExifConverter.java, hibernate-core/src/test/java/org/hibernate/test/annotations/immutable/ImmutableTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/immutable/Photo.java
This PR replaces the [original PR](https://github.com/hibernate/hibernate-orm/pull/1189) since it underwent the following changes:
- the commits were squashed so we can better apply it on other branches
- the commit is rebased on master
- license headers were added, 
- code formatting for test logic
- some minor JavaDoc change indicating this is an attribute type, and not meant to be used directly on fields
=> HHH-10714 - Add support for @Immutable attribute types

databases.gradle, hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java, hibernate-core/src/main/java/org/hibernate/dialect/AbstractTransactSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Oracle10gDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQL81Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQL95Dialect.java, hibernate-core/src/test/java/org/hibernate/test/dialect/unit/lockhint/AbstractLockHintTest.java, hibernate-core/src/test/java/org/hibernate/test/dialect/unit/lockhint/SQLServer2005LockHintsTest.java, hibernate-core/src/test/java/org/hibernate/test/dialect/unit/locktimeout/HANALockTimeoutTest.java, hibernate-core/src/test/java/org/hibernate/test/dialect/unit/locktimeout/OracleLockTimeoutTest.java, hibernate-core/src/test/java/org/hibernate/test/dialect/unit/locktimeout/PostgreSQLLockTimeoutTest.java, hibernate-core/src/test/java/org/hibernate/test/locking/PessimisticWriteLockTimeoutTest.java, hibernate-core/src/test/java/org/hibernate/test/util/ReflectionUtil.java, hibernate-core/src/test/java/org/hibernate/test/util/SQLStatementInterceptor.java
This PR aims to fix all the following JIRA issues which are all related to handling the lock timeout info when it comes to acquiring a shared or an exclusive lock:
- HHH-10797 - PostgreSQL81Dialect does not honor the lock timeout settings
- HHH-10799 - Add PostgreSQL 9.5 Dialect which supports the SKIP LOCKED clause
- HHH-10816 - SQLServer2005Dialect does not use NOWAIT for aliases
- HHH-10817 - AbstractHANADialect should support the NOWAIT directive in the FOR UPDATE clause
=> Fix for HHH-10797, HHH-10799, HHH-10816, HHH-10817

hibernate-core/src/main/java/org/hibernate/LockOptions.java, hibernate-core/src/main/java/org/hibernate/annotations/QueryHints.java, hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/QueryHintDefinition.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Oracle8iDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Teradata14Dialect.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CascadingActions.java, hibernate-core/src/main/java/org/hibernate/jpa/QueryHints.java, hibernate-core/src/main/java/org/hibernate/loader/Loader.java, hibernate-core/src/main/java/org/hibernate/loader/criteria/CriteriaLoader.java, hibernate-core/src/main/java/org/hibernate/query/internal/AbstractProducedQuery.java, hibernate-core/src/test/java/org/hibernate/test/dialect/functional/OracleFollowOnLockingTest.java, hibernate-testing/src/main/java/org/hibernate/testing/DialectChecks.java
Improve Oracle follow-on-locking mechanism so that we only apply it according to the restricted usage examples. `LockOptions` allows overriding the default dialect verification if the user knows that in certain situations the `FOR UPDATE` clause can be applied without any issue.
=> HHH-9486: Use follow-on locking when paging only

README.md
Hibernate EntityManager was merged into Core and no longer exists as a sub-project.
=> Remove reference to EntityManager in README.md

hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java, hibernate-core/src/main/java/org/hibernate/sql/SimpleSelect.java, hibernate-core/src/test/java/org/hibernate/test/extralazy/Championship.java, hibernate-core/src/test/java/org/hibernate/test/extralazy/ExtraLazyTest.java, hibernate-core/src/test/java/org/hibernate/test/extralazy/School.java, hibernate-core/src/test/java/org/hibernate/test/extralazy/Student.java
For bidirectional collections, the  where clause is now considered when calculating the size() of the LazyCollectionOption.EXTRA annotated collections
=> HHH-10874 - @Where annotation is not processed with "Extra-lazy" loading

hibernate-entitymanager/src/main/java/org/hibernate/jpa/internal/metamodel/MetadataContext.java, hibernate-entitymanager/src/test/java/org/hibernate/jpa/test/xml/metamodel/AbstractMetamodelPopulateTest.java, hibernate-entitymanager/src/test/java/org/hibernate/jpa/test/xml/metamodel/DisabledPopulationTest.java, hibernate-entitymanager/src/test/java/org/hibernate/jpa/test/xml/metamodel/EnabledPopulationTest.java, hibernate-entitymanager/src/test/java/org/hibernate/jpa/test/xml/metamodel/IgnoreUnsupportedPopulationTest.java, hibernate-entitymanager/src/test/resources/org/hibernate/jpa/test/xml/Person.hbm.xml
https://hibernate.atlassian.net/browse/HHH-10968
=> [5.1]: HHH-10968 - Skip EntityMode.MAP metadata when JpaMetaModelPopulationSetting is IGNORE_UNSUPPORTED

hibernate-core/src/test/java/org/hibernate/test/wf/ddl/SFSBHibernateSessionFactory.java, hibernate-core/src/test/java/org/hibernate/test/wf/ddl/WildFlyHibernateDdlTest.java
https://hibernate.atlassian.net/browse/HHH-11024
Added a test failing with javax.ejb.EJBException: org.hibernate.exception.GenericJDBCException: Unable to set JDBC Connection into auto-commit mode in preparation for DDL execution
I have noticed that the test passess if the SFSBHibernateSessionFactory#cleanup() method is annotated with @TransactionAttribute(TransactionAttributeType.NEVER)
=> HHH-11024 - Add test for issue

hibernate-core/src/main/java/org/hibernate/SessionBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsState.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java, hibernate-core/src/main/java/org/hibernate/engine/spi/AbstractDelegatingSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/SessionCreationOptions.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/WrapperOptions.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/TimeTypeDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/TimestampTypeDescriptor.java, hibernate-core/src/test/java/org/hibernate/test/timestamp/JdbcTimeCustomTimeZoneTest.java, hibernate-core/src/test/java/org/hibernate/test/timestamp/JdbcTimeDefaultTimeZoneTest.java, hibernate-core/src/test/java/org/hibernate/test/timestamp/JdbcTimestampCustomSessionLevelTimeZoneTest.java, hibernate-core/src/test/java/org/hibernate/test/timestamp/JdbcTimestampCustomTimeZoneTest.java, hibernate-core/src/test/java/org/hibernate/test/timestamp/JdbcTimestampDefaultTimeZoneTest.java, hibernate-core/src/test/java/org/hibernate/test/timestamp/JdbcTimestampUTCTimeZoneTest.java, hibernate-core/src/test/java/org/hibernate/test/timestamp/JdbcTimestampWithoutUTCTimeZoneTest.java, hibernate-core/src/test/java/org/hibernate/test/timestamp/TimestampTest.java, hibernate-core/src/test/java/org/hibernate/test/type/descriptor/sql/StringValueMappingTest.java, hibernate-core/src/test/java/org/hibernate/test/util/ReflectionUtil.java, hibernate-core/src/test/java/org/hibernate/test/util/jdbc/TimeZoneConnectionProvider.java, hibernate-testing/src/main/java/org/hibernate/testing/transaction/TransactionUtil.java
I added a SF/Session-level configuration which is passed through the JDBC `PreparaedStatement`/`ResultSet`
=> HHH-10399 - Add support for specifying TimeZone for ZonedDateTime type

hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jdbc/internal/JdbcResourceLocalTransactionCoordinatorImpl.java, hibernate-core/src/test/java/org/hibernate/jpa/test/transaction/TransactionRollbackTest.java
https://hibernate.atlassian.net/browse/HHH-11407
the ExceptionConverterImpl cause the call of JdbcResourceLocalTransactionCoordinatorImpl#markRollbackOnly
then when a second call to JdbcResourceLocalTransactionCoordinatorImpl#rollback is execute 
rollbackOnly = true cause a second execution of dbcResourceTransaction.rollback();
=> HHH-11407 - JPA + JDBC transaction - when a commit fails rollback is executed twice

hibernate-core/src/main/java/org/hibernate/mapping/Table.java
Use JDBC Environment to get the qualified name of the table, instead of directly appending schema name when it is defined explicitly.
=> HHH-11455 - Do not use schema name when underlying database doesn't support It

hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java, hibernate-core/src/main/java/org/hibernate/event/internal/FlushVisitor.java, hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/EnhancerTest.java, hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/LazyCollectionDeletedTestTask.java, hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/merge/MergeEnhancedEntityTestTask.java, hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/merge/RefreshEnhancedEntityTestTask.java
This supersedes https://github.com/hibernate/hibernate-orm/pull/1854 with a small change and added comments.
It also avoids cascading the entity field value (e.g, null or some other value initialized by entity constructor) from the enhanced entity when `CascadingAction#performOnLazyProperty` returns `false`.
=> HHH-11576 and HHH-11459

hibernate-core/hibernate-core.gradle, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Oracle10gDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQL95Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServer2005Dialect.java, hibernate-core/src/test/java/org/hibernate/dialect/SQLServer2005DialectTestCase.java, hibernate-core/src/test/java/org/hibernate/jpa/test/lock/LockTest.java, hibernate-core/src/test/java/org/hibernate/test/dialect/unit/lockhint/SQLServer2005LockHintsTest.java, hibernate-core/src/test/java/org/hibernate/test/locking/A.java, hibernate-core/src/test/java/org/hibernate/test/locking/AbstractSkipLockedTest.java, hibernate-core/src/test/java/org/hibernate/test/locking/LockModeTest.java, hibernate-core/src/test/java/org/hibernate/test/locking/PessimisticReadSkipLockedTest.java, hibernate-core/src/test/java/org/hibernate/test/locking/PessimisticWriteSkipLockedTest.java, hibernate-core/src/test/java/org/hibernate/test/locking/UpgradeSkipLockedTest.java, hibernate-testing/src/main/java/org/hibernate/testing/DialectChecks.java, hibernate-testing/src/main/java/org/hibernate/testing/junit4/BaseUnitTestCase.java
https://hibernate.atlassian.net/browse/HHH-10654
=> HHH-10654 - LockOptions.SKIP_LOCKED semantics implementation on MSSQL

libraries.gradle
- https://hibernate.atlassian.net/browse/HHH-11698
=> HHH-11698 Upgrade to Byte Buddy 1.6.14 for improved JDK9 compatibility

hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQL81Dialect.java, hibernate-core/src/test/java/org/hibernate/test/id/sequence/NegativeValueSequenceTest.java
https://hibernate.atlassian.net/browse/HHH-11712
=> HHH-11712 - PostgreSQL does not support negative initial sequence values for ascending sequences unless MINVALUE is defined as well

hibernate-core/src/main/java/org/hibernate/dialect/pagination/SQLServer2012LimitHandler.java
https://hibernate.atlassian.net/browse/HHH-11929
HHH-11929 removed excessive toLowerCase() and substring() from SQLServer2012LimitHandler.hasOrderBy(). Also reversed the direction for scanning the sql string for "order by " to start at the end of the string
=> HHH-11929 Improve Performance of SQLServer2012LimitHandler.hasOrderBy()

hibernate-core/src/test/java/org/hibernate/jpa/test/graphs/Student.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/ClassWriter.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaAttribute.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaMap.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/model/MetaAttribute.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/StringUtil.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/xml/XmlMetaAttribute.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/xml/XmlMetaMap.java, tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/StringUtilTest.java
Fix for https://hibernate.atlassian.net/browse/HHH-10294
Replaces https://github.com/hibernate/hibernate-orm/pull/1152.
Attributes are not interweaved anymore.
A use case has been added to `Student.java`
=> HHH-10294 EntityGraph improvement: For each jpa attribute, generate also a String constant holding the attribute field name

hibernate-core/src/main/java/org/hibernate/internal/util/BytesHelper.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/UUIDTypeDescriptor.java, hibernate-core/src/test/java/org/hibernate/test/util/BytesHelperTest.java
Avoid creating unneeded temporary byte array in org.hibernate.type.descriptor.java.UUIDTypeDescriptor.ToBytesTransformer
=> HHH-12131 Avoid allocating unneeded byte array when parsing or transforming UUID.

hibernate-core/src/main/java/org/hibernate/dialect/HANAColumnStoreDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/TeradataDialect.java, hibernate-core/src/main/java/org/hibernate/hql/spi/id/IdTableSupport.java, hibernate-core/src/main/java/org/hibernate/hql/spi/id/IdTableSupportStandardImpl.java, hibernate-core/src/main/java/org/hibernate/hql/spi/id/global/GlobalTemporaryTableBulkIdStrategy.java
I've added `org.hibernate.hql.spi.id.IdTableSupport#getTruncateIdTableCommand`, implemented it in `org.hibernate.hql.spi.id.IdTableSupportStandardImpl` and `org.hibernate.dialect.TeradataDialect`, and added a call to it to `org.hibernate.hql.spi.id.global.GlobalTemporaryTableBulkIdStrategy#cleanUpRows`.
=> HHH-11798: Provide method for overriding delete statement in GlobalTemporaryTableBulkIdStrategy

build.gradle, documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsState.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java, hibernate-core/src/main/java/org/hibernate/hql/internal/ast/QueryTranslatorImpl.java, hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/JavaConstantNode.java, hibernate-core/src/main/java/org/hibernate/hql/internal/ast/util/LiteralProcessor.java, hibernate-core/src/main/java/org/hibernate/hql/internal/classic/WhereParser.java, hibernate-core/src/main/java/org/hibernate/internal/util/ReflectHelper.java, hibernate-core/src/test/java/org/hibernate/internal/util/ReflectHelperTest.java, hibernate-core/src/test/java/org/hibernate/internal/util/hib3rnat3/C0nst4nts३.java, hibernate-core/src/test/java/org/hibernate/test/queryconstant/NonConventionalJavaConstantAllowedTest.java, hibernate-core/src/test/java/org/hibernate/test/queryconstant/NonConventionalJavaConstantDefaultTest.java, hibernate-core/src/test/java/org/hibernate/test/queryconstant/NonConventionalJavaConstantDisallowedTest.java
https://hibernate.atlassian.net/browse/HHH-4959 (5.1)
https://hibernate.atlassian.net/browse/HHH-11377 (5.1)
=> HHH-4959 and HHH-11377 (5.1)

hibernate-core/src/main/java/org/hibernate/hql/internal/ast/ParameterTranslationsImpl.java
HHH-12116 and HHH-12101 introduced a regression when in a query a named parameter is used twice and the first reference does not permit to determine the expected type of the parameter.
This on PostgresSQL causes the failure of org.hibernate.test.hql.ASTParserLoadingTest#testMultipleRefsToSameParam() test.
=> HHH-12116 - Positional parameters report position as name HHH-12101 - Remove support for legacy HQL-style positional parameters

hibernate-infinispan/hibernate-infinispan.gradle
@sebersole , not sure if you want this, but the PR adds to the relocation POM of the infinispan project the info JBoss Nexus is checking for
=> HHH-12190 - General tidying of Gradle scripts

hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java, hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingDuplicateTest.java, hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithCascadeOnPersist.java, hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithMultipleManyToOne.java, hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithSecondaryTable.java, hibernate-core/src/test/java/org/hibernate/test/util/jdbc/PreparedStatementProxyConnectionProvider.java, hibernate-entitymanager/src/test/java/org/hibernate/jpa/test/insertordering/InsertOrderingWithSecondaryTable.java
PR includes fixes for the following issues:
https://hibernate.atlassian.net/browse/HHH-11634 
https://hibernate.atlassian.net/browse/HHH-11768 
https://hibernate.atlassian.net/browse/HHH-11714 
https://hibernate.atlassian.net/browse/HHH-11996
=> Bugfixes related to hibernate.order_inserts=true (5.1)

hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/test/java/org/hibernate/test/stateless/StatelessSessionTest.java
https://hibernate.atlassian.net/browse/HHH-12141
=> HHH-12141 - SQL insert in stateless session causes javax.persistence.TransactionRequiredException

hibernate-core/src/main/java/org/hibernate/engine/transaction/internal/TransactionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/test/java/org/hibernate/jpa/test/transaction/CloseEntityManagerWithActiveTransactionTest.java, hibernate-core/src/test/java/org/hibernate/jpa/test/transaction/ClosedEntityManagerWithJpaTransactionComplianceTest.java, hibernate-core/src/test/java/org/hibernate/jpa/test/transaction/ClosedEntityManagerWithoutJpaTransactionComplianceTest.java, hibernate-core/src/test/java/org/hibernate/jpa/test/transaction/GetTransactionTest.java, hibernate-core/src/test/java/org/hibernate/jpa/test/transaction/JtaGetTransactionThrowsExceptionTest.java
https://hibernate.atlassian.net/browse/HHH-12487
trying to create the `TransactionDriverControl` in the `TransactionImpl` constructor when 
the `EntityManager` is closed causes an Exception to be thrown because the `LogicalConnection` is closed.
=> HHH-12487 - Calling getTransaction() on a closed Session

hibernate-core/src/main/java/org/hibernate/loader/entity/plan/AbstractLoadPlanBasedEntityLoader.java, hibernate-core/src/main/java/org/hibernate/loader/entity/plan/EntityLoader.java, hibernate-core/src/main/java/org/hibernate/loader/entity/plan/LegacyBatchingEntityLoaderBuilder.java, hibernate-core/src/main/java/org/hibernate/loader/plan/exec/internal/AbstractLoadQueryDetails.java, hibernate-core/src/main/java/org/hibernate/loader/plan/exec/internal/BatchingLoadQueryDetailsFactory.java, hibernate-core/src/main/java/org/hibernate/loader/plan/exec/internal/EntityLoadQueryDetails.java
* https://hibernate.atlassian.net/browse/HHH-12556
This is part of a series of patch to improve our memory consumption when dealing with legacy batch fetch style.
With the OpenConcerto test case contributed by the OP, this change alone brings the memory used from **1002 MB** to **461 MB**.
I think this change is pretty safe API wise, that's why I isolated it.
=> HHH-12556 Share data structures between similar LoadPlan based EntityLoaders

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BasicProxyFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java, hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/ByteBuddyProxyFactory.java
* https://hibernate.atlassian.net/browse/HHH-12614
This one is rather safe: it's all about keeping the protection domain when proxying classes.
* https://hibernate.atlassian.net/browse/HHH-12618
This one is open to discussion: the idea is to use `MethodHandle` lookups when available. We have to be extra careful because the generated class has to end up in the original class package, which was not always the case before to the second commit added in this PR.
Especially, when dealing with an interface, the subclass was `Object` and thus the classes ended up in a `net.bytebuddy.renamed` package.
=> ByteBuddy enhancement assorted fixes/improvements

hibernate-core/src/main/java/org/hibernate/engine/transaction/jta/platform/internal/JBossStandAloneJtaPlatform.java, hibernate-core/src/main/java/org/hibernate/engine/transaction/jta/platform/internal/StandardJtaPlatformResolver.java, hibernate-core/src/main/java/org/hibernate/engine/transaction/jta/platform/internal/WildFlyStandAloneJtaPlatform.java
First attempt setup of WildFlyStandAloneJtaPlatform using org.wildfly.transaction.client.ContextTransactionManager + org.wildfly.transaction.client.LocalUserTransaction, if those classes are not found, then try JBossStandAloneJtaPlatform using com.arjuna.ats.jta.TransactionManager + com.arjuna.ats.jta.UserTransaction.
=> HHH-12640: Update to JBossStandAloneJtaPlatform should be backward compatible attempting old names as well and revert HHH-12620

documentation/src/main/asciidoc/userguide/chapters/caching/Caching.adoc, hibernate-jcache/src/main/java/org/hibernate/cache/jcache/MissingCacheStrategy.java, hibernate-jcache/src/test/java/org/hibernate/jcache/test/MissingCacheStrategyTest.java
https://hibernate.atlassian.net//browse/HHH-12649
Follows up on #2369. Changes the default behavior for the JCache region factory on missing caches, to be consistent with the Ehcache region factory, following our discussion on the mailing list.
=> HHH-12649 Auto-register entity and collection caches based on the Hibernate @Cache annotation (XML mapping) settings

build.gradle, documentation/documentation.gradle, gradle/libraries.gradle, gradle/published-java-module.gradle, hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java, hibernate-core/src/test/java/org/hibernate/boot/spi/metadatabuildercontributor/SqlFunctionMetadataBuilderContributorIllegalClassArgumentTest.java, hibernate-core/src/test/java/org/hibernate/cfg/annotations/CollectionBinderTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/tuplizer/bytebuddysubclass/MyEntityInstantiator.java, hibernate-orm-modules/hibernate-orm-modules.gradle
With this PR, the build passes with `-Dhibernate.bytecode.provider=javassist`.
* https://hibernate.atlassian.net/browse/HHH-12800
* https://hibernate.atlassian.net/browse/HHH-12801
* https://hibernate.atlassian.net/browse/HHH-12803
* https://hibernate.atlassian.net/browse/HHH-12804
* https://hibernate.atlassian.net/browse/HHH-12805
* https://hibernate.atlassian.net/browse/HHH-12807
* https://hibernate.atlassian.net/browse/HHH-12808
* https://hibernate.atlassian.net/browse/HHH-12809
* https://hibernate.atlassian.net/browse/HHH-12813
**Important, the last commit still has to be confirmed (mail sent on the hibernate-dev mailing list).**
=> Assorted JDK 11 adjustments

hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java, hibernate-core/src/test/java/org/hibernate/test/annotations/override/mappedsuperclass/MappedSuperClassBasicPropertyIdAttributeOverrideTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/override/mappedsuperclass/MappedSuperClassIdPropertyBasicAttributeOverrideTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/override/mappedsuperclass/MappedSuperClassWithUuidAsBasic.java, hibernate-core/src/test/java/org/hibernate/test/annotations/override/mappedsuperclass/SubclassWithUuidAsId.java
Based on [this PR](https://github.com/hibernate/hibernate-orm/pull/2513), I think we should just throw an exception since the standard does not say we should override a basic property from a base class and promote it as an `@Id`.
=> HHH-11771 - @Id annotation ignored with @MappedSuperclass inheritance

hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/ByteBuddyProxyFactory.java, hibernate-core/src/main/java/org/hibernate/proxy/pojo/javassist/JavassistProxyFactory.java, hibernate-core/src/test/java/org/hibernate/jpa/test/callbacks/PrivateConstructorTest.java, hibernate-core/src/test/java/org/hibernate/jpa/test/callbacks/ProtectedConstructorTest.java
https://hibernate.atlassian.net/browse/HHH-13020
=> HHH-13020 - When proxying an entity having a private default constructor, the log message is not very clear about the problem

libraries.gradle
https://hibernate.atlassian.net/browse/HHH-12964
(cherry picked from commit e66da8af0076c2fbca9c190e8e708441be5bfcd3)
=> HHH-12964 - Upgrade to dom4j 2.1.1 - 5.2

hibernate-core/src/main/java/org/hibernate/query/criteria/internal/CriteriaSubqueryImpl.java, hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/subquery/AbstractSubqueryInSelectClauseTest.java, hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/subquery/SubqueryInSelectClauseJpaComplianceTest.java, hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/subquery/SubqueryInSelectClauseTest.java
When the JPA query compliance mode is disabled (the default), it should
be possible to include subqueries in select clauses of a criteria query.
This was previously accepted due to a bug. After having fixed HHH-13001, we
started to throw an IllegalStateException.
* https://hibernate.atlassian.net/browse/HHH-13111
=> HHH-13111 Restore support of criteria subqueries in select clauses

migration-guide.adoc
Migration guide for Hibernate v5.4 incorrectly specified that depends on JTS 1.6, in fact the correct JTS version is 1.16 as included in actual maven dependency.
This PR corrects the JTS version information.
=> Corrects JTS version information in Hibernate 5.4 migration guide

hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/test/annotations/onetoone/OneToOneMapsIdChangeParentTest.java
https://hibernate.atlassian.net/browse/HHH-13228
=> HHH-13228 - The modification of a @OneToOne with @MapsId property is silently ignored during a merge operation

hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/AbstractProducedQuery.java, hibernate-core/src/test/java/org/hibernate/test/flush/NonTransactionalDataAccessTest.java
https://hibernate.atlassian.net/browse/HHH-13262 (5.3)
=> HHH-13262 (5.3)

hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/test/java/org/hibernate/test/inheritance/MappedSuperclassInheritanceTest.java
Make sure the @Inheritance annotation is ignored when used along with @MappedSuperclass
=> HHH-13217 - Don't throw exception if both @MappedSuperclass and @Inheritance are used

hibernate-core/src/main/java/org/hibernate/jpa/event/spi/jpa/ExtendedBeanManager.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/CdiBeanContainerBuilder.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/CdiBeanContainerExtendedAccessImpl.java, hibernate-core/src/test/java/org/hibernate/test/cdi/testsupport/TestingExtendedBeanManager.java, hibernate-core/src/test/java/org/hibernate/test/cdi/testsupport/TestingExtendedBeanManagerImpl.java, hibernate-core/src/test/java/org/hibernate/test/cdi/testsupport/TestingLegacyExtendedBeanManagerImpl.java, hibernate-core/src/test2/java/org/hibernate/test/cdi/events/extended/InvalidExtendedCdiSupportTest.java, hibernate-core/src/test2/java/org/hibernate/test/cdi/events/extended/ValidExtendedCdiSupportTest.java, hibernate-core/src/test2/java/org/hibernate/test/cdi/general/mixed/ExtendedMixedAccessTest.java, hibernate-core/src/test2/java/org/hibernate/test/cdi/general/mixed/Helper.java, hibernate-core/src/test2/java/org/hibernate/test/cdi/general/nonregistrymanaged/extended/NonRegistryManagedExtendedCdiSupportTest.java
Port of #2809 to branch wip/6.0.
Ticket: https://hibernate.atlassian.net/browse/HHH-13309
Waiting for CI; I didn't run tests locally. But there wasn't any conflict.
=> Port HHH-13309 to 6.0 - Extended bean managers implementing the new interface are not correctly detected 

hibernate-core/src/main/java/org/hibernate/type/descriptor/java/InstantJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/LocalDateJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/LocalDateTimeJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/OffsetDateTimeJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ZonedDateTimeJavaDescriptor.java, hibernate-core/src/test/java/org/hibernate/test/type/AbstractJavaTimeTypeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/InstantTest.java, hibernate-core/src/test/java/org/hibernate/test/type/LocalDateTest.java, hibernate-core/src/test/java/org/hibernate/test/type/LocalDateTimeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/LocalTimeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/OffsetDateTimeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/OffsetTimeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/ZonedDateTimeTest.java
https://hibernate.atlassian.net//browse/HHH-13266
Adding Gail because I think we should backport this to 5.3.
I added a comment to the ticket: https://hibernate.atlassian.net/browse/HHH-13266?focusedCommentId=104778&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-104778
In short, there's a bug in the java.util classes that leads to "drifts" when converting between year/month/day/hours/etc. to milliseconds since the epoch, and back. This only happens before a certain point in time around 1900 (different depending on the timezone).
Generally the bug is rather innocuous because we happen to run two conversions, and the two conversions fortunately drift in a way that compensate each other.
However, near 1900, there's a chance that the first conversion make the …
=> HHH-13266 LocalDateTime values are wrong around 1900 (caused by JDK-8061577)

hibernate-core/src/test/java/org/hibernate/test/type/AbstractJavaTimeTypeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/InstantTest.java, hibernate-core/src/test/java/org/hibernate/test/type/LocalDateTest.java, hibernate-core/src/test/java/org/hibernate/test/type/LocalDateTimeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/LocalTimeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/OffsetDateTimeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/OffsetTimeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/ZonedDateTimeTest.java
Follow-up on #2813 
Some tests failed for Oracle, Mariadb and HANA. This disable the tests, because the cause of the failures seems to be limitations of the databases.
I checked this works fine for MariaDB. I couldn't get Oracle Express or HANA to run on my machine, so this will have to be checked by the CI.
=> HHH-13266 Oracle, Mariadb and HANA test fixes

gradle/libraries.gradle
Update c3p0 dependency to addresses the XXE vulnerability (CVE-2018-20433)
=> HHH-13332 Update c3p0 to 0.9.5.3

hibernate-core/src/main/java/org/hibernate/action/internal/AbstractEntityInsertAction.java, hibernate-core/src/main/java/org/hibernate/engine/internal/ForeignKeys.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDeleteEventListener.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/jpa/test/BaseEntityManagerFunctionalTestCase.java, hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/BidirectionalLazyTest.java, hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/group/BidirectionalLazyGroupsInEmbeddableTest.java, hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/group/BidirectionalLazyGroupsTest.java, hibernate-testing/src/main/java/org/hibernate/testing/bytecode/enhancement/BytecodeEnhancerRunner.java
https://hibernate.atlassian.net/browse/HHH-13241
https://hibernate.atlassian.net/browse/HHH-13138
The fix for HHH-13138 is included here because it is required in order for all the HHH-13241 tests to pass.
=> HHH-13241 HHH-13138 (5.3)

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java, hibernate-core/src/test/java/org/hibernate/bytecode/internal/bytebuddy/EnhanceByteCodeNotInProvidedClassLoaderTest.java
https://hibernate.atlassian.net/browse/HHH-13343
=> HHH-13343 : Bytecode enhancement using ByteBuddy fails when the class is not available from the provided ClassLoader

hibernate-core/src/main/java/org/hibernate/query/internal/AbstractProducedQuery.java, hibernate-core/src/test/java/org/hibernate/jpa/test/lock/Lock.java, hibernate-core/src/test/java/org/hibernate/jpa/test/lock/LockTest.java
https://hibernate.atlassian.net/browse/HHH-13364
=> HHH-13364 Query.getSingleResult and getResultList() throw PessimisticLockException when pessimistic lock fails with timeout

hibernate-core/src/main/java/org/hibernate/type/descriptor/java/InstantJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/LocalDateJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/LocalDateTimeJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/OffsetDateTimeJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ZonedDateTimeJavaDescriptor.java, hibernate-core/src/test/java/org/hibernate/test/type/AbstractJavaTimeTypeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/InstantTest.java, hibernate-core/src/test/java/org/hibernate/test/type/LocalDateTest.java, hibernate-core/src/test/java/org/hibernate/test/type/LocalDateTimeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/LocalTimeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/OffsetDateTimeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/OffsetTimeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/ZonedDateTimeTest.java
https://hibernate.atlassian.net//browse/HHH-13266
@gbadner I think we should backport this to 5.3?
=> Backport HHH-13266 to branch 5.3 - LocalDateTime values are wrong around 1900 (caused by JDK-8061577)

hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java, hibernate-core/src/main/java/org/hibernate/cache/internal/QueryResultsCacheImpl.java, hibernate-core/src/main/java/org/hibernate/cache/internal/TimestampsCacheEnabledImpl.java, hibernate-core/src/main/java/org/hibernate/cache/spi/support/AbstractReadWriteAccess.java, hibernate-core/src/main/java/org/hibernate/cfg/CollectionSecondPass.java, hibernate-core/src/main/java/org/hibernate/cfg/Settings.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/engine/internal/ParameterBinder.java, hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/internal/TwoPhaseLoad.java, hibernate-core/src/main/java/org/hibernate/engine/loading/internal/CollectionLoadContext.java, hibernate-core/src/main/java/org/hibernate/engine/query/spi/HQLQueryPlan.java, hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultInitializeCollectionEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultReplicateEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultResolveNaturalIdEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultSaveOrUpdateEventListener.java, hibernate-core/src/main/java/org/hibernate/id/IncrementGenerator.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/jpa/event/internal/CallbackBuilderLegacyImpl.java, hibernate-core/src/main/java/org/hibernate/loader/Loader.java, hibernate-core/src/main/java/org/hibernate/loader/entity/CacheEntityLoaderHelper.java, hibernate-core/src/main/java/org/hibernate/loader/plan/exec/internal/AbstractLoadPlanBasedLoader.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/BasicBinder.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/BasicExtractor.java
Historically some classes have cached the logger level in static fields to prevent calls to the logging framework to reolve logging levels at run time.
Caching the log level at build time can cause a race condition in log levels at runtime, especially when the build system is multi-tiered. This is evident in a Quarkus native binary, as an incorrect log level at runtime;
https://github.com/quarkusio/quarkus/issues/2223
Optimisations in logging frameworks now mean that there is not a performance penalty for checking log level defined in the logging framework, removing the need to cache the log level.
=> HHH-13418 : Revert log level caching

.travis.yml, documentation/documentation.gradle, gradle/published-java-module.gradle, hibernate-osgi/hibernate-osgi.gradle
https://hibernate.atlassian.net//browse/HHH-13415
Necessary to work on [HHH-13409](https://hibernate.atlassian.net//browse/HHH-13409) in particular.
=> HHH-13415 Restore build compatibility with JDK11.0.3

.travis.yml, gradle/java-module.gradle
... so that we get actionable logs when something fails.
Builds on master generally last about 26 minutes, which is well below the limit of 50 minutes: https://docs.travis-ci.com/user/customizing-the-build#build-timeouts
So we only need to comply with the requirement of not waiting more than 10 minutes between two outputs, which is mainly a problem with tests. I added some configuration so that Gradle logs one line per executed test.
It worked just fine for this execution: https://travis-ci.org/yrodiere/hibernate-orm/builds/537749346?utm_medium=notification&utm_source=email
The log is big (1.6MB), but still below the [4MB limit](https://docs.travis-ci.com/user/common-build-problems/#log-length-exceeded): https://api.travis-ci.org/v3/job/537749347/log.txt
=> Get rid of travis_wait in .travis.yml

.travis.yml, gradle/java-module.gradle
So that the build isn't too verbose when running it locally.
=> Do not log test progress by default, but provide a build option and enable it for Travis

.travis.yml
If we don't force it, Travis will pick a release at random,
either Trusty or Xenial at the moment.
Using Oracle JDK 8 on Xenial is not easy, for some reason.
See:
* https://travis-ci.community/t/oracle-jdk-11-and-10-are-pre-installed-not-the-openjdk-builds/785/15
* https://github.com/travis-ci/travis-ci/issues/10289
=> Force the use of Ubuntu Trusty in the Travis build

hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/SetIdentifierOnAEnhancedProxyTest.java
calling setId() of an enhanced proxy causes
java.lang.NullPointerException
at org.hibernate.tuple.entity.AbstractEntityTuplizer.getPropertyValue(AbstractEntityTuplizer.java:593)
at org.hibernate.bytecode.enhance.spi.interceptor.EnhancementAsProxyLazinessInterceptor.lambda$handleWrite$2(EnhancementAsProxyLazinessInterceptor.java:222)
at org.hibernate.bytecode.enhance.spi.interceptor.EnhancementHelper.performWork(EnhancementHelper.java:130)
at org.hibernate.bytecode.enhance.spi.interceptor.EnhancementAsProxyLazinessInterceptor.handleWrite(EnhancementAsProxyLazinessInterceptor.java:216)
at org.hibernate.bytecode.enhance.spi.interceptor.AbstractInterceptor.writeObject(AbstractInterceptor.java:158)
at org.hibernate.test.bytecode.enhancement.lazy.proxy.SetIdentifierOnAEnhancedProxyTest$Child.$$_ …
=> HHH-11147 - Add failing test (based on master) 

hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/query/QueryProducer.java, hibernate-core/src/main/java/org/hibernate/query/criteria/internal/AbstractManipulationCriteriaQuery.java, hibernate-core/src/main/java/org/hibernate/query/criteria/internal/CriteriaQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/criteria/internal/compile/CriteriaCompiler.java, hibernate-core/src/main/java/org/hibernate/query/criteria/internal/compile/CriteriaInterpretation.java, hibernate-core/src/main/java/org/hibernate/query/criteria/internal/compile/CriteriaQueryTypeQueryAdapter.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/BasicCriteriaExecutionTests.java
https://hibernate.atlassian.net//browse/HHH-13154
This is necessary to allow users to prepare for ORM 6 where we will remove Hibernate Criteria in favor of JPA criteria.
I don't think it introduces any binary incompatibility. Adding @gbadner just in case you want to double-check.
This merely pulls up the `createQuery(criteria)` method declarations from `Session` to `QueryProducer` (to also expose it in `StatelessSession`) and implementations from `SessionImpl` to `AbstractSharedSessionContract` (to also implement it in `StatelessSessionImpl`).
I had to leave the method declarations in `Session` in order to resolve the conflict between signatures from `QueryProducer` and from `EntityManager`.
The tests are rather light, but there's no point in re-testing all the different criteria …
=> HHH-13154 Add support for JPA criteria on stateless sessions

hibernate-core/src/main/java/org/hibernate/engine/loading/internal/LoadContexts.java, hibernate-core/src/main/java/org/hibernate/type/CollectionType.java
https://hibernate.atlassian.net/browse/HHH-13442
inside the `CollectionType#getCollection()` the `CollectionKey` is created twice, the first time inside the `LoadContext#locateLoadingCollection`.
=> HHH-13442 - CollectionType#getCollection() method improvements

hibernate-integrationtest-java-modules/src/main/java/module-info.java
Works when executing the tests locally with JDK11 with this command:
```
./gradlew :hibernate-integrationtest-java-modules:test --stacktrace --info -Dhibernate.bytecode.provider=javassist
```
=> Fix JavaModulePathIT when testing with javassist

hibernate-core/src/main/java/org/hibernate/bytecode/spi/BytecodeEnhancementMetadata.java, hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/spi/BatchFetchQueue.java, hibernate-core/src/main/java/org/hibernate/engine/spi/PersistenceContext.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/main/java/org/hibernate/tuple/entity/BytecodeEnhancementMetadataNonPojoImpl.java, hibernate-core/src/main/java/org/hibernate/tuple/entity/BytecodeEnhancementMetadataPojoImpl.java, hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/BatchFetchProxyTest.java
Proposal for alternative approach to Gail and Andrea's work on this - so intended as an alternative to https://github.com/hibernate/hibernate-orm/pull/2931
At a high-level it centers on the addition of 2 methods - 
- org.hibernate.engine.spi.PersistenceContext#addEnhancedProxy
- org.hibernate.bytecode.spi.BytecodeEnhancementMetadata#createEnhancedProxy
=> Batch fetching support for bytecode proxies on top of HHH-11147

hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentBag.java
https://hibernate.atlassian.net/browse/HHH-11032
I added a commit to @nnguyenfilip and @barreiro's [commit](https://github.com/barreiro/hibernate-orm/commit/43c5f2ddbf7110fa4ca2326b657b663776ce7e64) that may improve performance:
* reduces the number of hashCode calculations;
* reduces the number of ```Map``` lookups;
* adds a check to return ```false``` early, if number of instances with the same hash is different.
I also made some variables final, and renamed some variables for readability.
Supersedes https://github.com/hibernate/hibernate-orm/pull/1521
=> HHH-11032 : performance improvements of PersistentBag.equalsSnapshot

hibernate-core/src/main/java/org/hibernate/action/internal/EntityIncrementVersionProcess.java, hibernate-core/src/main/java/org/hibernate/action/internal/EntityVerifyVersionProcess.java, hibernate-core/src/main/java/org/hibernate/dialect/lock/OptimisticForceIncrementLockingStrategy.java, hibernate-core/src/main/java/org/hibernate/dialect/lock/OptimisticLockingStrategy.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultPostLoadEventListener.java, hibernate-core/src/test/java/org/hibernate/test/locking/LockRefreshTest.java
https://hibernate.atlassian.net/browse/HHH-13492
The problem here is that an ```EntityVerifyVersionProcess``` is registered with the ```EntityEntry``` associated with the entity at the time that the entity is locked.
Later, when the entity is refreshed, that ```EntityEntry``` is replaced by a new one in the ```PersistenceContext```. This makes the ```EntityEntry``` registered with the ```EntityVerifyVersionProcess``` stale.
After the updated entity is pushed to the database by ```EntityUpdateAction#execute```, which calls ```EntityEntry#postUpdate``` to update the version in the entity and the current ```EntityEntry```.
Later, when ```EntityVerifyVersionProcess#doBeforeTransactionCompletion``` executes using the stale ```EntityEntry```, ```OptimisticLockException``` is thrown because the …
=> HHH-13492 : OptimisticLockException after locking, refreshing, and updating an entity

hibernate-core/src/main/java/org/hibernate/type/descriptor/java/OffsetTimeJavaDescriptor.java, hibernate-core/src/test/java/org/hibernate/test/type/AbstractJavaTimeTypeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/OffsetTimeTest.java
https://hibernate.atlassian.net/browse/HHH-13357
=> HHH-13357 (5.3)

hibernate-core/src/main/java/org/hibernate/action/internal/EntityIncrementVersionProcess.java, hibernate-core/src/main/java/org/hibernate/action/internal/EntityVerifyVersionProcess.java, hibernate-core/src/main/java/org/hibernate/dialect/lock/OptimisticForceIncrementLockingStrategy.java, hibernate-core/src/main/java/org/hibernate/dialect/lock/OptimisticLockingStrategy.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultPostLoadEventListener.java, hibernate-core/src/test/java/org/hibernate/test/locking/LockRefreshTest.java
https://hibernate.atlassian.net/browse/HHH-13492
=> Hhh 13492 5.3

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java, hibernate-core/src/test/java/org/hibernate/test/cascade/CascadeMergeToProxyEntityCopyAllowedTest.java, hibernate-core/src/test/java/org/hibernate/test/cascade/CascadeMergeToProxySimpleTest.java
https://hibernate.atlassian.net/browse/HHH-13590
The test case is fairly complicated and requires ```hibernate.event.merge.entity_copy_observer=allow```.
I'm pretty sure this bug applies more generally. I'll work on adding a simpler test case that does not require ```hibernate.event.merge.entity_copy_observer=allow```.
=> HHH-13590 : TransientObjectException merging a non-proxy association to a proxy

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultAutoFlushEventListener.java, hibernate-core/src/test/java/org/hibernate/test/events/AutoFlushEventListenerTest.java
https://hibernate.atlassian.net/browse/HHH-13592?oldIssueView=true
=> HHH-13592 (5.3)

hibernate-core/src/main/java/org/hibernate/id/AbstractPostInsertGenerator.java, hibernate-core/src/main/java/org/hibernate/id/IdentifierGenerator.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/test/joinedsubclassbatch/SequenceJoinedSubclassBatchingTest.java
https://hibernate.atlassian.net/browse/HHH-12968
=> HHH-12968 (5.3)

gradle/libraries.gradle, hibernate-core/src/test/java/org/hibernate/test/annotations/EntityTest.java, hibernate-core/src/test/java/org/hibernate/test/resource/transaction/jdbc/autocommit/MySQLSkipAutoCommitTest.java, hibernate-core/src/test/java/org/hibernate/test/temporal/TimePropertyTest.java, hibernate-core/src/test/java/org/hibernate/test/type/AbstractJavaTimeTypeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/LocalDateTest.java, hibernate-core/src/test/java/org/hibernate/test/type/LocalTimeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/OffsetTimeTest.java, hibernate-spatial/databases/mysql56/matrix.gradle, hibernate-spatial/databases/mysql8/matrix.gradle
* [HHH-13580](https://hibernate.atlassian.net/browse/HHH-13580): LocalTimeTest#writeThenNativeRead* and OffsetTimeTest#writeThenNativeRead* failing on MySQL
* [HHH-13582](https://hibernate.atlassian.net/browse/HHH-13582): LocalDateTest failures on MySQL
See commit messages for details.
To be backported to 5.3, but you already know that :)
=> HHH-13580 + HHH-13582 MySQL test failures

gradle/libraries.gradle, hibernate-core/src/test/java/org/hibernate/test/annotations/EntityTest.java, hibernate-core/src/test/java/org/hibernate/test/resource/transaction/jdbc/autocommit/MySQLSkipAutoCommitTest.java, hibernate-core/src/test/java/org/hibernate/test/temporal/TimePropertyTest.java, hibernate-core/src/test/java/org/hibernate/test/type/AbstractJavaTimeTypeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/LocalDateTest.java, hibernate-core/src/test/java/org/hibernate/test/type/LocalTimeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/OffsetTimeTest.java, hibernate-spatial/databases/mysql56/matrix.gradle
https://hibernate.atlassian.net/browse/HHH-13580
https://hibernate.atlassian.net/browse/HHH-13582
=> HHH-13580 HHH-13582 MySQL test failures (5.3)

databases/mariadb/matrix.gradle, hibernate-core/src/test/java/org/hibernate/test/type/LocalTimeTest.java, hibernate-core/src/test/java/org/hibernate/test/type/OffsetTimeTest.java
https://hibernate.atlassian.net/browse/HHH-13581
https://hibernate.atlassian.net/browse/HHH-13605
As mentioned in [HHH-13581](https://hibernate.atlassian.net/browse/HHH-13581), the problem is in the JDBC driver.
To be backported to 5.3.
=> HHH-13581 + HHH-13605 MariaDB test failures

databases/hana/matrix.gradle
https://hibernate.atlassian.net/browse/HHH-13606
Turns out this was simply a bug in the HANA JDBC driver that has been fixed since.
Note that we already updated to version 2.4.59 of the driver in `libraries.gradle`, so we probably just forgot to update `hana/matrix.gradle`.
=> HHH-13606 LocalDateTimeTest fails for HANA on CI

README.md
**Changes:**
1. Inserted "," before "and"
2. "quite unique" creates a tautology.
3. "features" -> "feature", The sentence was about a single feature.
4. The phrases "in order to" maybe wordy. Consider changing the wording.
5. The phrases "a number of" maybe wordy. Consider changing the wording.
6.  "Note :" -> "Note:", Unnessacary space between "Note" and ":"
=> Grammatical and syntax mistake in README.md

hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
https://hibernate.atlassian.net/browse/HHH-13698 (5.3)
=> HHH-13698 (5.3)

hibernate-core/src/main/java/org/hibernate/dialect/pagination/SQLServer2005LimitHandler.java
Fixes [HHH-13758](https://hibernate.atlassian.net/browse/HHH-13758)
=> HHH-13758 - Limit Handler for SQL server doesn't work with CTE queries with strings literals

README.md
Both Oracle and DB2 JDBC drivers are now available in MC so the statement is no longer accurate
=> Remove mention of Oracle and DB2 not being in MC

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/CodeTemplates.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/InlineDirtyCheckingHandler.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/PersistentAttributeTransformer.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/javassist/PersistentAttributesEnhancer.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/DirtyCheckingWithEmbeddableAndMappedSuperclassTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/DirtyCheckingWithMappedsuperclassTest.java, hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/MappedSuperclassWithEmbeddableTest.java
For issue [HHH-13759](https://hibernate.atlassian.net/browse/HHH-13759)
These are some additional commits to add on top of https://github.com/hibernate/hibernate-orm/pull/3138
This PR adds:
* test cases to check that the classes have the additional fields created during enhancements
* a simple refactoring of the existing code to make it clearer that we skip some logic when dealing with `@MappedSuperclass`.
* a comment in InlineDirtyCheckingHandler
I guess they are all optional but I would like to have them included
=> HHH-13759 Error on enhanced field with embedded and @MappedSuperclass

hibernate-core/src/main/java/org/hibernate/engine/spi/LoadQueryInfluencers.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java, hibernate-core/src/main/java/org/hibernate/event/spi/LoadEvent.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/loader/Loader.java, hibernate-core/src/main/java/org/hibernate/loader/entity/AbstractEntityLoader.java, hibernate-core/src/main/java/org/hibernate/loader/entity/BatchingEntityLoader.java, hibernate-core/src/main/java/org/hibernate/loader/entity/DynamicBatchingEntityLoaderBuilder.java, hibernate-core/src/main/java/org/hibernate/loader/entity/EntityLoader.java, hibernate-core/src/main/java/org/hibernate/loader/entity/LegacyBatchingEntityLoaderBuilder.java, hibernate-core/src/main/java/org/hibernate/loader/entity/PaddedBatchingEntityLoaderBuilder.java, hibernate-core/src/main/java/org/hibernate/loader/entity/UniqueEntityLoader.java, hibernate-core/src/main/java/org/hibernate/loader/entity/plan/AbstractLoadPlanBasedEntityLoader.java, hibernate-core/src/main/java/org/hibernate/loader/entity/plan/BatchingEntityLoader.java, hibernate-core/src/main/java/org/hibernate/loader/entity/plan/LegacyBatchingEntityLoaderBuilder.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/NamedQueryLoader.java, hibernate-core/src/test/java/org/hibernate/jpa/test/EntityManagerTest.java, hibernate-core/src/test/java/org/hibernate/jpa/test/ejb3configuration/PersisterClassProviderTest.java
https://hibernate.atlassian.net/browse/HHH-11958
Lots of refactoring code, but the implementation is still straightforward. 
The gist is to rely on `loadQueryInfluencers` to pass the hint, from LoadEvent all the way down to `QueryParameters`.
Testing case added.
=> HHH-11958 Make EntityManager.find() support QueryHints.HINT_READONLY

hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/test/java/org/hibernate/test/exceptionhandling/NonActiveTransactionSessionFindJdbcExceptionHandlingTest.java
https://hibernate.atlassian.net/browse/HHH-13433
https://hibernate.atlassian.net/browse/HHH-13737
Once approved, the same test case and logging will get pushed to master.
=> HHH-13433 HHH-13737 (5.3)

hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentBag.java, hibernate-core/src/test/java/org/hibernate/test/collection/bag/BagElementNullBasicTest.java
https://hibernate.atlassian.net/browse/HHH-13675
https://hibernate.atlassian.net/browse/HHH-13651
=> HHH-13675 HHH-13651 (5.3)

build.gradle
One of the build tasks, publish, had a typo in the description. It has been corrected in this commit.
=> Fixing a typo in the build task #HHH-13830

tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/ClassWriter.java, tooling/metamodel-generator/src/main/resources/META-INF/gradle/incremental.annotation.processors
Upgrade JPA MetaModel Generator (jpamodelgen) to support Gradle Incremental Compile
According to https://docs.gradle.org/current/userguide/java_plugin.html#sec:incremental_annotation_processing there are basically two requirements:
- Register your annotation processor in gradle specific meta-inf file
- For an _Isolating_ processor exactly one originating element must be specified with the Filer API.
=> HHH-13390 - Upgrade JPA MetaModel Generator (jpamodelgen) to support Gradle Incremental Compile

documentation/src/main/asciidoc/userguide/chapters/fetching/Fetching.adoc, hibernate-core/src/main/java/org/hibernate/engine/internal/TwoPhaseLoad.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java, hibernate-core/src/main/java/org/hibernate/graph/GraphSemantic.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/AbstractProducedQuery.java, hibernate-core/src/test/java/org/hibernate/graph/EntityGraphFunctionalTests.java, hibernate-core/src/test/java/org/hibernate/jpa/test/graphs/CompanyWithFetchProfile.java, hibernate-core/src/test/java/org/hibernate/jpa/test/graphs/mapped_by_id/FetchGraphFindByIdTest.java, hibernate-core/src/test/java/org/hibernate/jpa/test/graphs/mapped_by_id/LoadGraphFindByIdTest.java, hibernate-core/src/test/java/org/hibernate/jpa/test/graphs/queryhint/QueryHintEntityGraphTest.java
I found our 'fetch graph' implementation is almost perfect (e.g. load plan, SQL generation are perfectly in line with 'fetch graph' JPA spec), the only missing part is in TwoPhaseLoad. We have added 'fetch profile' overwriting (w.r.t meta model) logic there. Seems we are missing the 'fetch graph' overwriting counterpart there.
Testing code for both 'find' and 'query' are added.
=> HHH-8776 Fix 'fetch graph' implementation

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/FirebirdDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/IngresDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SAPDBDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/TeradataDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/TimesTenDialect.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/idtable/IdTable.java
This method threw lots of `NotImplementedFor6Exception`s on this branch, so I've tried to figure out what the right implementations are, going by what was there in the other branches. But I'm not at all sure that I got everything here right, so please review this @sebersole @dreab8.
This commit also gives `TeradataDialect` back its `IndexExporter`.
=> Dialect.getFallbackSqmMutationStrategy()

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/internal/log/DeprecationLogger.java
The database-version-specific dialects are now `@Deprecated`. So produce a log message to this effect.
=> Log usage of deprecated Dialect classes

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultSaveOrUpdateEventListener.java
This is an issue I've found long time ago. I risked exposing my ignorance to create a PR targeting v6 to have it fixed. Seems it is not noticed simply because it is not used often.
=> Wip/6.0 Remove an unnoticed negation operator in DefaultSaveOrUpdateEventListener

hibernate-core/src/main/java/org/hibernate/dialect/unique/DB2UniqueDelegate.java, hibernate-core/src/main/java/org/hibernate/dialect/unique/DefaultUniqueDelegate.java, hibernate-core/src/main/java/org/hibernate/mapping/Constraint.java, hibernate-core/src/main/java/org/hibernate/mapping/Table.java, hibernate-core/src/test/java/org/hibernate/test/annotations/any/AnyTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/bytecode/ProxyBreakingTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/idclass/xml/IdClassXmlTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/loader/LoaderTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/onetoone/OptionalOneToOnePKJCTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/query/QueryAndSQLTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/reflection/ElementCollectionConverterTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/xml/ejb3/Ejb3XmlTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/xml/ejb3/OrmVersion1SupportedTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/xml/hbm/HbmTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/xml/hbm/HbmWithIdentityTest.java, hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/AuditMetadataGenerator.java, hibernate-testing/src/main/java/org/hibernate/testing/junit4/BaseCoreFunctionalTestCase.java
1. TODO: Remove duplicate method from ConstraintConstaint.java currently has two duplicate methods. 1. getColumnIterator()2. columnIterator()
Both the methods return the same value i.e. column.iterator().
One of them needs to be removed in order to reduce and clean the duplication. 
2. TODO: Change method name for getXmlFiles in BaseCoreFunctionalTestCaseCurrently, in BaseCoreFunctionalTestCase a method named getXmlFiles()has a TODO placed that suggests the method name to be changed to getOrmXmlFiles().
Since the method has a protected scope, there is a possibility it is being used by other clients. Hence, changing the method name in minor versions might break the code for clients.
=> HHH-13856 - Long-awaited TODOs done as an improvement

hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java
a followup of https://github.com/hibernate/hibernate-orm/pull/3227.
Fixing an issue that if 'integrationSettings' is null (will be assigned Collections.emptyMap(), which is immutable) and new properties is added to it, exception will be thrown.
=> HHH-13853 fix minor issue

hibernate-core/src/main/java/org/hibernate/mapping/Constraint.java, hibernate-testing/src/main/java/org/hibernate/testing/junit4/BaseCoreFunctionalTestCase.java
Two methods that are dropped in v6.0 are now marked as deprecated in this commit.
As discussed in the removal PR https://github.com/hibernate/hibernate-orm/pull/3229
=> HHH-13874 - Deprecating methods that will be removed soon

hibernate-spatial/databases/db2/resources/hibernate.properties, hibernate-spatial/databases/sqlserver2012_spatial/resources/hibernate.properties, hibernate-spatial/matrix-test.sh, hibernate-spatial/src/main/java/org/hibernate/spatial/SpatialFunction.java, hibernate-spatial/src/main/java/org/hibernate/spatial/SpatialPredicates.java, hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/WithCustomJPAFilter.java, hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/h2geodb/GeoDBDialect.java, hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/hana/HANASpatialDialect.java, hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/mysql/MySQL5SpatialFunctions.java, hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/mysql/MySQL8SpatialFunctions.java, hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/oracle/OracleSDOSupport.java, hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/oracle/OracleSpatial10gDialect.java, hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/oracle/OracleSpatialFunctions.java, hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/oracle/OracleSpatialSDO10gDialect.java, hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/postgis/PostgisFunctions.java, hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/sqlserver/SqlServerFunctions.java, hibernate-spatial/src/main/java/org/hibernate/spatial/predicate/FilterPredicate.java, hibernate-spatial/src/main/java/org/hibernate/spatial/predicate/SpatialPredicates.java, hibernate-spatial/src/test/java/org/hibernate/spatial/integration/TestSpatialPredicates.java, hibernate-spatial/src/test/java/org/hibernate/spatial/testing/TestSupportFactories.java, hibernate-spatial/src/test/java/org/hibernate/spatial/testing/dialects/postgis/PostgisTestSupport.java
Currently, Hibernate Spatial functions can be called via Hibernate Criteria API (which is deprecated) or JPQL. To use them in the JPA Criteria API, they have to be manually mapped using `CriteriaBuilder#function(String, Class, Expression...)`, which is tedious and error prone.
This PR provides a wrapper to provide a convenient way to use Hibernate Spatial functions from the JPA Criteria API.
=> HHH-13799 : Criteria API support for Hibernate Spatial

hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/DotNode.java, hibernate-core/src/test/java/org/hibernate/test/annotations/onetoone/OptionalOneToOneMapsIdQueryTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/onetoone/OptionalOneToOnePKJCQueryTest.java
https://hibernate.atlassian.net/browse/HHH-13875
@jwgmeligmeyling, could you please take a look at this? It is related to https://hibernate.atlassian.net/browse/HHH-12775.
=> HHH-13875 : Optional one-to-one does not always join the associated entity table when querying

hibernate-jipijapa/src/main/java/org/jboss/as/jpa/hibernate5/HibernatePersistenceProviderAdaptor.java
In the HibernatePersistenceProviderAdaptor, there is an unnecessary declaration of JtaManager. The sole purpose of having this variable is only to use in the overridden method named InjectJtaManager.
This was be improved by removing the JtaManager as there is no use of the variable, as of now at least.
=> HHH-13855 - Remove unnecessary delared variable JtaManager in HibernatePersistenceProviderAdaptor

hibernate-core/src/test/java/org/hibernate/orm/test/manytomany/ManyToManyBidirectionalTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/onetomany/OneToManyBidirectionalTest.java
https://trello.com/c/bxDr9p96/66-check-circular-bi-directional-references-detection-for-collections
Tested both 'OneToMany' and 'ManyToMany' cases. Seems both are working fine as expected.
As discussed with Andrea, existing testing cases I worked on top of was enriched by SQL inspecting.
=> Wip/6.0 Verify bidirectional collection circular reference detection

hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/CollectionSizeNode.java
- Fix to work on Oracle by removing "as" between table name and alias
@sebersole or @dreab8, this works for Oracle. I thought there was some `Dialect` method that indicates if "as" is needed between table name and alias, but I don't see it.
Is there one that I missed?
Do you know if this will break for any dialects?
=> HHH-13619 - Support for JPA's `size` function as a select expression

hibernate-core/src/main/java/org/hibernate/resource/jdbc/internal/ResourceRegistryStandardImpl.java
A simple removal of 'todo'. Found during code review of Vlad's https://github.com/hibernate/hibernate-orm/pull/3292
=> Wip/6.0 Implement ResourceRegistryStandardImpl#convert to avoid NPE

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddedCollectionPart.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/results/graph/embeddable/internal/EmbeddableFetchImplTests.java
Seems an overlooking. In all other cases the created 'tableJoinFetch' is added to 'lhsTableGroup', except this one.
=> wip/6.0 Fix bug in EmbeddedCollectionPart#createTableGroupJoin

hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
Since H2 1.4.200, drop constraints should be enabled (see details and demo [here](https://hibernate.atlassian.net/projects/HHH/issues/HHH-13711)).
When the demo is run with the submitted change, no error is produced anymore.
This change is also compatible with earlier H2 versions (the demo was successfully tested with 1.4.197, 1.4.198 and 1.4.199; the older versions, not listed [here](https://www.h2database.com/html/changelog.html), have not been tested).
=> HHH-13711: drop constraints enabled for H2

hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
Double checked locking is subtle and error-prone. There is some imperfection as per https://en.wikipedia.org/wiki/Double-checked_locking. See code review self-comment for details.
=> Wip/6.0 Fix a double-checked locking implementation imperfection

hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/mapping/collections/MapOperationTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/mapping/collections/PluralAttributeMappingTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/mapping/collections/SetOperationTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/mapping/collections/SortNaturalByDefaultTests.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/domain/gambit/EntityOfMaps.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/domain/gambit/EntityOfSets.java
https://trello.com/c/up8I5oIi/58-support-for-sorted-set-and-sorted-map-without-sortnatural-or-sortcomparator
https://hibernate.atlassian.net/browse/HHH-13877
testing case added
=> Wip/6.0 HHH-13877 Make`@SortNatural` default for SortedSet and SortedMap

build.gradle, buildSrc/build.gradle, gradle.properties, gradle/published-java-module.gradle, gradle/publishing-repos.gradle, gradle/wrapper/gradle-wrapper.properties, hibernate-core/hibernate-core.gradle, hibernate-infinispan/hibernate-infinispan.gradle, hibernate-orm-modules/hibernate-orm-modules.gradle, hibernate-osgi/hibernate-osgi.gradle, settings.gradle, shared/config/checkstyle/checkstyle-non-fatal.xml, shared/config/checkstyle/checkstyle.xml, tooling/hibernate-gradle-plugin/src/test/groovy/org/hibernate/orm/tooling/gradle/HibernatePluginTest.groovy
https://hibernate.atlassian.net/browse/HHH-13685
Before we merge this, we need to upgrade and release three Gradle plugins:
* ~https://github.com/sebersole/gradle-maven-publish-auth/pull/20~ => Done
* ~https://github.com/hibernate/hibernate-matrix-testing/pull/9~ => Done
* ~https://github.com/sebersole/gradle-xjc-plugin/pull/3~ => Done
I checked:
* publishing to the local Maven repository
* publishing snapshots to nexus
* running the matrix plugin
I'd like to run tests on CI before we merge, but we need to release the Gradle plugins first.
=> HHH-13685 Upgrade to Gradle 5

build.gradle, gradle/java-module.gradle, gradle/published-java-module.gradle, hibernate-core/hibernate-core.gradle, hibernate-entitymanager/hibernate-entitymanager.gradle, hibernate-envers/hibernate-envers.gradle, hibernate-java8/hibernate-java8.gradle, hibernate-osgi/hibernate-osgi.gradle
https://hibernate.atlassian.net/browse/HHH-13689
**DO NOT MERGE**: This pull request is based on #3078 (upgrade to Gradle 5), which should be merged first. This means the first few commits are those from #3078 , but they will disappear once #3078 is merged and I rebase the PR on master.
The OSGi plugin [is deprecated](https://docs.gradle.org/5.0-milestone-1/release-notes.html#deprecated-osgi-plugin) in Gradle 5, meaning we will have to switch to its replacement before we can think about upgrading to Gradle 6. And we will have to upgrade to Gradle 6 at some point, for JDK13+ support.
This PR addresses two points:
* Switching to the recommended replacement for the OSGi plugin, the [BND Gradle plugin](https://github.com/bndtools/bnd/tree/master/biz.aQute.bnd.gradle), and adapting the …
=> HHH-13689 Replace uses of the deprecated osgi plugin with the biz.aQute.bnd plugin

documentation/src/main/asciidoc/userguide/chapters/domain/collections.adoc
follow up for https://trello.com/c/up8I5oIi/58-support-for-sorted-set-and-sorted-map-without-sortnatural-or-sortcomparator
Forgot to update the user guide for this new feature in v6.
=> wip/6.0 Update user guide regarding @SortNatural by default

build.gradle, documentation/documentation.gradle, gradle/base-information.gradle, gradle/java-module.gradle, gradle/published-java-module.gradle, hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/NaturalIdInUninitializedAssociationTest.java, hibernate-integrationtest-java-modules/hibernate-integrationtest-java-modules.gradle, settings.gradle
https://hibernate.atlassian.net/browse/HHH-13682
~This PR is based on #3328 (HHH-13925 - upgrade to Gradle 6.3) . #3328 should be merged first. This PR includes commits from #3328, so it should be rebased after #3328 has been merged.~ => Done
The goal here is simply to compile tests to Java 11/13/14 when we build with JDK 11/13/14. That way, not only do we check that Hibernate ORM can be run within JDK 11/13/14, but we also check that it will correctly interact with Java 11/13/14 bytecode, which is especially important for bytecode enhancement.
Hopefully this will allow us to avoid the kind of problems we've had before, where bytebuddy needed an update and we didn't notice it because we were only ever manipulating Java 8 bytecode in our tests.
Build against JDK13: …
=> HHH-13682 Generate Java 11/13/14 bytecode for tests when building with JDK11/13/14

gradle/java-module.gradle
Follow-up on #3329 ([HHH-13682](https://hibernate.atlassian.net/browse/HHH-13682))
Couldn't test for now,  because Gradle 6.3 doesn't work with JDK15+ (a problem with Groovy reflection, apparently). But @Sanne suggested this, and I think he's right: we will need to set the system property.
=> HHH-13682 Follow-up: restore the "net.bytebuddy.experimental" system property for JDK15+

documentation/src/test/java/org/hibernate/userguide/mapping/basic/SubselectTest.java, gradle/databases.gradle, hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Database.java, hibernate-core/src/main/java/org/hibernate/dialect/HANACloudColumnStoreDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HANARowStoreDialect.java, hibernate-core/src/test/java/org/hibernate/test/converter/AttributeConverterTest.java, hibernate-core/src/test/java/org/hibernate/test/dialect/functional/HANASearchTest.java, hibernate-core/src/test/java/org/hibernate/test/ops/HANANoColumnInsertTest.java, hibernate-core/src/test/java/org/hibernate/test/queryhint/QueryHintHANATest.java, hibernate-core/src/test/java/org/hibernate/test/schemaupdate/HANASchemaMigrationTargetScriptCreationTest.java
- Add new HANA Cloud dialect
- Adapt Databases enum
- Adapt failing tests
=> HHH-13917: Add support for HANA Cloud

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderDynamicBatch.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderProvidedQueryImpl.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderStandardImpl.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdLoadPlan.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleUniqueKeyEntityLoaderStandard.java, hibernate-core/src/main/java/org/hibernate/loader/ast/spi/CollectionLoader.java, hibernate-core/src/main/java/org/hibernate/loader/ast/spi/SingleEntityLoader.java, hibernate-core/src/main/java/org/hibernate/loader/ast/spi/SingleIdEntityLoader.java, hibernate-core/src/main/java/org/hibernate/loader/ast/spi/SingleUniqueKeyEntityLoader.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/query/internal/ScrollableResultsIterator.java, hibernate-core/src/main/java/org/hibernate/query/spi/QueryOptions.java, hibernate-core/src/main/java/org/hibernate/query/spi/QueryOptionsAdapter.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcSelectExecutorStandardImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/ReadonlyHintTest.java
The motivation of this PR is the fact that https://hibernate.atlassian.net/browse/HHH-11958 is not working in v6 because of code refactoring.
However, it is not difficult to fix it in v6. This PR doesn't include CollectionLoader into the scope, however.
A testing case is included.
=> wip/6.0 Loader 'readOnly' support

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmTreePrinter.java, hibernate-core/src/main/java/org/hibernate/sql/ast/SqlTreePrinter.java
Given that Hibernate supports SqlServer on Windows OS, I assume it is desirable to ensure the logging statement should output lines in OS agnostic way. However, currently the two AST tree logger's output on Windows is screwed up because `\n` is hardcoded in code.
Not a big deal for sure. But imagine a new Java developer working on Windows OS to turn on the AST tree logging statements...
=> wip/6.0 AST tree logging line separator OS agnostic

documentation/src/test/java/org/hibernate/userguide/pc/FilterJoinTableTest.java, documentation/src/test/java/org/hibernate/userguide/pc/FilterTest.java, hibernate-core/src/main/java/org/hibernate/internal/FilterHelper.java, hibernate-core/src/main/java/org/hibernate/internal/FilterJdbcParameter.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderBatchKey.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderSingleKey.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdLoadPlan.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmInterpretationsKey.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/StandardSqmSelectTranslator.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstWalker.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/StandardSqlAstSelectTranslator.java, hibernate-core/src/main/java/org/hibernate/sql/ast/tree/predicate/FilterPredicate.java, hibernate-core/src/main/java/org/hibernate/sql/ast/tree/select/QuerySpec.java, hibernate-core/src/main/java/org/hibernate/sql/exec/spi/JdbcSelect.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/filter/FilterBasicsTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/filter/FilterJoinTableTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/filter/FilterOnJoinFetchedCollectionTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/filter/FilterWithSqlFragmentAliasTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/filter/FilterBasicsTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/filter/FilterJoinTableTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/filter/FilterOnJoinFetchedCollectionTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/filter/FilterWithSqlFragmentAliasTests.java
https://trello.com/c/KLZjWiX0/118-filter-support-for-hql-criteria
Also a followup for https://trello.com/c/RQxAqQaT/104-loaderselectbuilder-implement-use-of-loadqueryinfluencer, which was mainly focused on `loader` filter implementation.
The idiosyncrasy of `@Filter` and `@FilterJointable` feature is that they bring about additional JDBC parameter bindings. In last PR I registered these filter parameter bindings via `QuerySpec` which is tightly coupled with `loader` and not workable for `HQL/Criteria`. To support both `loader` and `HQL/Criteria`, this PR refactored previous implementation to store filter parameter to `JdbcSelect` instead, which accommodates both scenarios well. However, better idea is more than welcome!
As in last PR, extensive testing cases were added.
=> wip/6.0 Implement filter for HQL/Criteria

hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlLexer.g4, hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
The following SQL syntax is useful in reporting:
select avg(price), store, item, cust from sales group by rollup(store, item, cust)
This syntax is supported on at least DB2, Oracle, SQL Server, and Postgres. It's not supported on MySQL.
Note that the ANSI SQL standard syntax for this is, apparently, the following:
select avg(price), store, item, cust from sales group by store, item, cust with rollup
However, I don't find this to be better. MySQL has partial support for this syntax.
This patch adds support for `rollup()` and `cube()` to HQL.
Note that this is just a proposal and has not been tested, since the query parser does not yet support `group by`.
=> Add rollup() and cube() for use in group by clause

hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/internal/FilterHelper.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java, hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java, hibernate-core/src/main/java/org/hibernate/persister/collection/CollectionPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/Joinable.java, hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/UnionSubclassEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/filter/WhereJoinTableTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/filter/WhereTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/filter/FilterBasicsTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/filter/WhereJoinTableTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/filter/WhereTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/filter/FilterBasicsTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/filter/WhereJoinTableTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/filter/WhereTests.java, hibernate-core/src/test/java/org/hibernate/test/cfg/persister/GoofyPersisterClassProvider.java
https://trello.com/c/lF9R13J3/115-where-and-wherejointable
So `@Where` and `@WhereJoinTable` belongs to the same `filter` umbrella, together with `@Filter` and `@FilterJoinTable`. We simply generalize existing implementation to accommodate it easily.
=> wip/6.0 implement @Where and @WhereJoinTable

hibernate-core/src/main/java/org/hibernate/action/internal/DelayedPostInsertIdentifier.java, hibernate-core/src/main/java/org/hibernate/boot/model/relational/AbstractAuxiliaryDatabaseObject.java, hibernate-core/src/main/java/org/hibernate/cfg/CopyIdentifierComponentSecondPass.java, hibernate-core/src/main/java/org/hibernate/event/spi/EventType.java, hibernate-core/src/main/java/org/hibernate/internal/util/MutableLong.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/Bindable.java, hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/UnionSubclassEntityPersister.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/MatchingIdSelectionHelper.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/idtable/ExecuteWithIdTableHelper.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/idtable/RestrictedDeleteExecutionDelegate.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/idtable/UnrestrictedDeleteExecutionDelegate.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableForeignKeyResultImpl.java
There seems to be an established pattern to use `AtomicInteger` as a convenient class of `mutable integer container`, regardless of whether it is used in single thread scenario (e.g. within method as a temporary variable without being exposed externally) or not. That is a misuse or sloppiness for we have to pay the performance cost of concurrency safety unnecessarily.
Luckily, in some recent PR by Andrea, a more appropriate substitute has been committed: `MutableInteger`.
Below is the **jmh** benchmark result between `AtomicInteger` and `MutableInteger` when it comes to increasing by 1:
```
Benchmark                Mode  Cnt   Score     Error    Units
benchmarkAtomicInteger   avgt   5       13.143 ± 6.360  ns/op
benchmarkMutableInteger  avgt   5       0.399 ± 0.045   ns/op
```
It is a …
=> wip/6.0 Replace 'AtomicInteger' with 'MutableInteger' in single thread scenario

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectClause.java
Just encountered the obvious bug. Guess the original intention is to go about optimization when the collection is singleton.
Did some jmh experimenting as following:
```
@Benchmark
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
public void iterateSingletonList() {
List<String> list = Arrays.asList("xxx");
for (String val : list) {
}
}
@Benchmark
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
public void getByIndexSingletonList() {
List<String> list = Arrays.asList("xxx");
list.get( 0 );
}
```
The jmh result goes as below:
```
Benchmark                   Mode  Cnt   Score   Error  Units
getByIndexSingletonList  avgt    5   5.200 ± 2.040  ns/op
iterateSingletonList    avgt    5  10.598 ± 1.498  ns/op
```
Not sure it is worthwhile, though. Now …
=> wip/6.0 Fix an obvious bug in SqmSelectClause

hibernate-spatial/src/main/java/org/hibernate/spatial/predicate/GeolatteFilterPredicate.java, hibernate-spatial/src/main/java/org/hibernate/spatial/predicate/GeolatteSpatialPredicates.java, hibernate-spatial/src/main/java/org/hibernate/spatial/predicate/JTSFilterPredicate.java, hibernate-spatial/src/main/java/org/hibernate/spatial/predicate/JTSSpatialPredicates.java, hibernate-spatial/src/main/java/org/hibernate/spatial/predicate/SpatialPredicates.java, hibernate-spatial/src/test/java/org/hibernate/spatial/integration/TestGeolatteSpatialPredicates.java, hibernate-spatial/src/test/java/org/hibernate/spatial/integration/TestJTSSpatialPredicates.java, hibernate-spatial/src/test/java/org/hibernate/spatial/testing/dialects/postgis/PostgisTestSupport.java
This enhances `SpatialPredicates` (added in version `5.4.13`, see #3159 for the original PR) to support `geolatte-geom` (in addition to `JTS`).
To clearly distinguish the classes, I've renamed `SpatialPredicates` to `JTSSpatialPredicates`, and added a new class `GeolatteSpatialPredicates` for `geolatte-geom`. ~~This unfortunately, is a minor breaking change~~.
Please review by commit, else the file renaming will mess with the Diffs.
=> HHH-13975 : geolatte-geom support for SpatialPredicates

hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java, hibernate-core/src/test/java/org/hibernate/test/cache/hhh13179/DiscriminatorSubclassNonUIPerson.java, hibernate-core/src/test/java/org/hibernate/test/cache/hhh13179/DiscriminatorSubclassPerson.java, hibernate-core/src/test/java/org/hibernate/test/cache/hhh13179/DiscriminatorSubclassUIPerson.java, hibernate-core/src/test/java/org/hibernate/test/cache/hhh13179/HHH13179Test.java, hibernate-core/src/test/java/org/hibernate/test/cache/hhh13179/JoinedSubclassNonUIPerson.java, hibernate-core/src/test/java/org/hibernate/test/cache/hhh13179/JoinedSubclassPerson.java, hibernate-core/src/test/java/org/hibernate/test/cache/hhh13179/JoinedSubclassUIPerson.java, hibernate-core/src/test/java/org/hibernate/test/cache/hhh13179/UnionSubclassNonUIPerson.java, hibernate-core/src/test/java/org/hibernate/test/cache/hhh13179/UnionSubclassPerson.java, hibernate-core/src/test/java/org/hibernate/test/cache/hhh13179/UnionSubclassUIPerson.java, hibernate-core/src/test/resources/org/hibernate/test/cache/hhh13179/DiscriminatorSubclassPerson.hbm.xml, hibernate-core/src/test/resources/org/hibernate/test/cache/hhh13179/JoinedSubclassPerson.hbm.xml, hibernate-core/src/test/resources/org/hibernate/test/cache/hhh13179/UnionSubclassPerson.hbm.xml
Fixes HHH-13179 and HHH-13173, regressions in 5.3 and forward.
Possibly originates from HHH-12146 - Support enabling caching at any level within a mapped hierarchy.
=> HHH-13179 Subclass 2nd level caching now works for XML mappings

hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/test/java/org/hibernate/test/flush/TestFlushJoinTransaction.java
https://hibernate.atlassian.net/browse/HHH-13936
=> HHH-13936 (5.3)

documentation/src/test/java/org/hibernate/userguide/fetching/GraphParsingTest.java, hibernate-core/src/main/antlr/org/hibernate/grammars/graph/GraphLanguageLexer.g4, hibernate-core/src/main/antlr/org/hibernate/grammars/graph/GraphLanguageParser.g4, hibernate-core/src/main/java/org/hibernate/graph/internal/parse/GraphParser.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractManagedType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/DomainModelHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/entitygraph/parser/AbstractEntityGraphTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/entitygraph/parser/EntityGraphParserTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/entitygraph/parser/EntityGraphsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/entitygraph/parser/GraphParsingTestEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/entitygraph/parser/GraphParsingTestSubEntity.java
The first step to entity graph verification. The following bugs were fixed:
1. ANTLR rule errors
2. entity graph subtype verification error
=> wip/6.0 Enable entity graph parser test cases

hibernate-testing/src/main/java/org/hibernate/testing/junit5/DialectFilterExtension.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/RequiresDialectFeature.java
We all encounter such common scenario. There has been a `DialectFeatureCheck` implementation names `Supportsxxxx` in `DialectFeatureChecks` class. Then we need to cover the dialects which fail to be validated by it. Previously we have to create another one (`DoesNotSupportsxxxx`) manually which is tedious and not elegant.
This PR aims to streamline such common scenario by simply specifying a new `reverse` property of `@RequiresDialectFeature` to true.
=> wip/6.0 add 'reverse' property to @RequiresDialectFeature annotation

documentation/src/main/asciidoc/userguide/chapters/fetching/Fetching.adoc, hibernate-core/src/main/java/org/hibernate/engine/internal/TwoPhaseLoad.java, hibernate-core/src/test/java/org/hibernate/jpa/test/graphs/LoadAndFetchGraphTest.java
https://hibernate.atlassian.net/browse/HHH-14097
The root cause is we lack fetch entity graph validation. For the initial multiple hydrated objects, only the first one is applicable to root entity graph.
Imported andrea's testing code from https://github.com/hibernate/hibernate-orm/pull/3452. Tons of thanks to him!
Remember only the testing case is needed to be merged into v6 for entity graph implementation is incompatible between v5 and v6 and the code changes except the testing case are not needed in v6 (actually I've carefully deleted the v5 implementation in v6 previously).
=> HHH-14097 Fix redundant SQLs issue for fetch entity graph

hibernate-core/src/main/java/org/hibernate/loader/entity/plan/AbstractLoadPlanBasedEntityLoader.java, hibernate-core/src/main/java/org/hibernate/loader/plan/exec/process/internal/AbstractRowReader.java, hibernate-core/src/main/java/org/hibernate/loader/plan/exec/process/internal/EntityReferenceInitializerImpl.java, hibernate-core/src/test/java/org/hibernate/test/batchfetch/BatchFetchRefreshTest.java
https://hibernate.atlassian.net/browse/HHH-12268
@Sanne, this was approved and pushed to master:
https://github.com/hibernate/hibernate-orm/pull/3461
This is needed for 5.3, because it fixes a regression that got introduced in 4.3 when we moved to load plans.
5.3 PR is:
https://github.com/hibernate/hibernate-orm/pull/3462
=> HHH-12268 (5.4)

hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/BatchingBatch.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/NonBatchingBatch.java, hibernate-core/src/main/java/org/hibernate/jdbc/Expectation.java, hibernate-core/src/main/java/org/hibernate/jdbc/Expectations.java, hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java, hibernate-core/src/main/java/org/hibernate/persister/collection/BasicCollectionPersister.java, hibernate-core/src/main/java/org/hibernate/persister/collection/OneToManyPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/test/batch/BatchOptimisticLockingTest.java
- https://hibernate.atlassian.net/browse/HHH-11082
I've been wondering if we should still give an option to log the parameters, but considering that this log message was just recently introduced: seems users have been happy enough without any log at all for many years. So I'm proposing to keep it simple.
=> Avoid logging parameters when logging statements

hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
https://hibernate.atlassian.net/browse/HHH-14041
The problem is that h2 does not directly substitute the constraint name but wraps it in a description: https://github.com/h2database/h2database/blob/9e2e212cf806fa75cd42437a13a33cb3185f5fb1/h2/src/main/org/h2/constraint/ConstraintReferential.java#L312
=> HHH-14041 - H2Dialect: fix referential integrity constraint constraint name extraction

hibernate-core/src/main/java/org/hibernate/loader/Loader.java, hibernate-core/src/test/java/org/hibernate/jpa/test/graphs/LoadAndFetchGraphTest.java
https://hibernate.atlassian.net/browse/HHH-14124
Essentially, the current implementation of sub-graph handling relies on side-effects in the session: when it loads an entity with an entity graph, it will replace the entity graph in the session with the subgraph, and hope that the next loaded entity needs this subgraph.
This will sort of work, though it's probably riddled with bugs (what if there are multiple subgraphs? what if entities are not processed in the expected order?). These bugs are not what HHH-14124 is about, however, so I won't try to address them.
The real problem that caused HHH-14124 is that this implementation of sub-graph handling doesn't take care of restoring the "root" entity graph after we're done processing one row in the result set. It may leave an incorrect graph, …
=> HHH-14124 Entity graph (fetch graph) is incorrectly applied to query results beyond the first one

hibernate-core/src/main/java/org/hibernate/metamodel/internal/StandardManagedTypeRepresentationResolver.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/StandardPojoEntityRepresentationStrategy.java
https://trello.com/c/CgVHHg3A/85-fix-problem-building-model-for-final-classes
The root cause is the following code snippet from `EntityMetamodel`:
Its usage was dropped during new code logic refactoring.
=> wip/6.0 Fix final entity class creating ProxyFactory issue

hibernate-core/src/main/java/org/hibernate/collection/internal/StandardOrderedMapSemantics.java, hibernate-core/src/main/java/org/hibernate/collection/internal/StandardOrderedSetSemantics.java, hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java, hibernate-core/src/main/java/org/hibernate/engine/spi/BatchFetchQueue.java, hibernate-core/src/main/java/org/hibernate/internal/util/collections/CollectionHelper.java, hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java, hibernate-core/src/main/java/org/hibernate/type/OrderedMapType.java, hibernate-core/src/main/java/org/hibernate/type/OrderedSetType.java, hibernate-core/src/main/java/org/hibernate/type/SetType.java
This is the follow up of https://github.com/hibernate/hibernate-orm/pull/3279. In recent code review, it seems we need to tackle the common confusion in case of `LinkedHashMap` and `LinkedHashSet` counterparts.
=> wip/6.0 Enrich CollectionHelper by adding LinkedHashMap and LinkedHashSet processing

documentation/src/test/java/org/hibernate/userguide/caching/SecondLevelCacheTest.java
https://hibernate.atlassian.net/browse/HHH-14133
Simple error of including empty char at the end of hint property key. Should be intolerable for example code in user guide.
=> HHH-14133 fix obvious example caching code error in user guide

hibernate-core/src/main/antlr/sql-script.g, hibernate-core/src/test/java/org/hibernate/test/fileimport/MultiLineImportExtractorTest.java, hibernate-core/src/test/resources/org/hibernate/test/fileimport/multi-line-statements.sql
https://hibernate.atlassian.net/browse/HHH-14152
So the original implementation of `MultipleLinesSqlCommandExtractor` striped off end-of-line chars. However, end-of-line chars could be a meaningful delimiter as other white space chars. For instance, the following common SQL script
```
INSERT INTO ISSUERS
VALUES (1, 1, 'BIPlatform', NULL, NULL);
```
would be erroneously transformed to
```
INSERT INTO ISSUERSVALUES (1, 1, 'BIPlatform', NULL, NULL);
```
This PR tries to reserve such end-of-line chars.
Another strongly related minor issue is the trailing end-of-line chars given that they are reserved rather than skipped. I changed the parser rule to allow trailing white spaces to make the paring more robust (and less confusing. User would get misled and confused when they get `statement must …
=> HHH-14152 reserve end-of-line chars in MultiLineImportExtractor

hibernate-core/src/main/java/org/hibernate/hql/internal/ast/SqlGenerator.java, hibernate-core/src/test/java/org/hibernate/query/hhh14154/HHH14154Test.java
https://hibernate.atlassian.net/browse/HHH-14154
The root cause is some sloppiness of code logic in `org.hibernate.hql.internal.ast.SqlGenerator` for the scenario wherein `FunctionNode`'s `sqlFunction` is null (e.g., the `FORMATDATETIME` function in the testing case of this PR).
=> HHH-14154 Incorrect SQL generated when concat() and function() methods are used together

documentation/src/main/asciidoc/userguide/appendices/Annotations.adoc, documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc, documentation/src/main/asciidoc/userguide/chapters/caching/Caching.adoc
https://hibernate.atlassian.net/browse/HHH-14159
Simply updating the 'hibernate.cache.query_cache_factory' related content to latest status quo. Seems the key name per se might be outdated as well, but it is not changed in this PR to maintain backward compatibility.
=> HHH-14159 Update 'hibernate.cache.query_cache_factory' config

hibernate-core/src/main/java/org/hibernate/type/descriptor/java/LocalTimeJavaDescriptor.java
This code is obviously wrong, though perhaps it doesn't actually produce any real bug.
=> fix an obvious mistake in LocalTimeJavaDescriptor (H6)

hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/test/java/org/hibernate/query/criteria/internal/hhh13908/Foo.java, hibernate-core/src/test/java/org/hibernate/query/criteria/internal/hhh13908/HHH13908Test.java
https://hibernate.atlassian.net/browse/HHH-13908
The root cause is we specified wrong return type for the 'time' function in MySQLDialect.
=> HHH-13908 fix MySQL's 'time' function return type issue

hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentCollection.java, hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java, hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java, hibernate-core/src/test/java/org/hibernate/event/service/internal/NewlyInstantiatdCollectionSkipDeleteOrphanTest.java
https://hibernate.atlassian.net/browse/HHH-14178
The root cause of the unexpected exception reported is our failure to detect whether some collection is newly instantiated. 
So below is the original code snippet:
```
final boolean deleteOrphans = style.hasOrphanDelete()
&& action.deleteOrphans()
&& elemType.isEntityType()
// a newly instantiated collection can't have orphans
&& child instanceof PersistentCollection;
if ( deleteOrphans ) {
```
Notice the comment for the last condition to decide whether deleteOrphan should be done. However, `child` is always of `PersistentCollection` type (we have collection field substitution logic before reaching here), so it boils down to the fact that we have no safety net against running 'delete-orphan' for new collection field.
How to detect whether …
=> HHH-14178 Make new collection skip delete-orphan 

hibernate-core/src/main/java/org/hibernate/query/criteria/internal/predicate/CompoundPredicate.java, hibernate-core/src/test/java/org/hibernate/query/criteria/internal/hhh11877/Foo.java, hibernate-core/src/test/java/org/hibernate/query/criteria/internal/hhh11877/HHH111877Test.java
https://hibernate.atlassian.net/browse/HHH-11877
The issue can be summarized as following:
Suppose we have an entity class `Foo` that contains a boolean field `bar`, the following criteria building will produce invalid SQL:
```
cq.select( foo ).where( cb.and( cb.and(), foo.get( Foo_.bar ) ) );
```
whereas the following is working fine:
```
cq.select( foo ).where( foo.get( Foo_.bar ) );
```
The root cause is internally in `CriteriaBuilderImpl#wrap()` method we fixed boolean type Path to ensure creating SQL snippet like `Foo_.bar = 1` rather than `Foo_.bar` (which will trigger invalid SQL). But we didn't go deeper than root level and this PR fixed the loophole to fix non-root level boolean type Path as well.
=> HHH-11877 Wrap CompoundPredicate's expression list

hibernate-core/src/main/java/org/hibernate/engine/query/spi/EntityGraphQueryHint.java, hibernate-core/src/test/java/org/hibernate/jpa/test/graphs/EntityGraphAttributeResolutionTest.java
https://hibernate.atlassian.net/browse/HHH-14113
I added a warning logging to remind the user that entity graph is not applicable to the root entity, as per Benjamin M.'s suggestion.
Note: this PR should not be merged into v6 for entity graph implementation in v6 has changed.
=> HHH-14113 Entity Graph attribute resolution not based on selected entity

hibernate-core/src/main/java/org/hibernate/query/criteria/internal/FromImplementor.java, hibernate-core/src/main/java/org/hibernate/query/criteria/internal/QueryStructure.java, hibernate-core/src/main/java/org/hibernate/query/criteria/internal/path/AbstractFromImpl.java, hibernate-core/src/test/java/org/hibernate/query/criteria/internal/hhh13058/HHH13058Test.java, hibernate-core/src/test/java/org/hibernate/query/criteria/internal/hhh13058/Patient.java, hibernate-core/src/test/java/org/hibernate/query/criteria/internal/hhh13058/Site.java, hibernate-core/src/test/java/org/hibernate/query/criteria/internal/hhh13058/Task.java
https://hibernate.atlassian.net/browse/HHH-13058
The current correlated subquery ignores the first left join and ends up with 'inner join' instead invariably. So suppose for the below entities:
```
@Entity(name = "Task")
public class Task {
@Id
Long id;
@ManyToOne
Patient patient;
}
@Entity(name = "Patient")
public class Patient {
@Id
Long id;
@ManyToOne
Site site;
}
@Entity(name = "Site")
public class Site {
@Id
Long id;
}
```
Note that `@ManyToOne`'s `optional` is `true` by default.
the following Criteria would skip the `Task` without `Patient`:
```
final Subquery<Task> subquery = outerQuery.subquery( Task.class );
final Root<Task> subtask = subquery.correlate( outerTask );
final From<Task, Patient> patient = subtask.join( Task_.patient, JoinType.LEFT );
final From<Patient, Site> site = …
```
=> HHH-13058 Fix issue left join root cannot be replaced by correlated parent in subquery

hibernate-core/src/main/java/org/hibernate/metamodel/internal/AttributeFactory.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EmbeddableTypeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/spi/EmbeddedTypeDescriptor.java, hibernate-core/src/test/java/org/hibernate/test/cut/CompositeUserTypeTest.java
Composite User Types work like regular Composite Types (like Embeddable) in HQL. However, because they cannot be represented in the JPA metamodel, libraries like [GraphQL for JPA](https://github.com/jcrygier/graphql-jpa) or [Blaze-Persistence](https://persistence.blazebit.com/) cannot fully utilize them. In order to make the composite property names available to these libraries, it would be nice to optionally expose these attributes as embedded attributes. This pull request aims to make that change and makes it configurable through a custom setting.
Composite User Types are a common solution for mapping composite interfaces. A common example is for example `Money` from the Java Money API (JSR-354), for which composite user types are implemented in …
=> HHH-14198 - Expose CompositeUserTypes through JPA Metamodel

hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/IngresDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/RDMSOS2200Dialect.java, hibernate-core/src/test/java/org/hibernate/test/dialect/unit/locktimeout/DB2LockTimeoutTest.java
Contains the following changes:
- support for `skip locked data` on DB2
- support for `use and keep share locks` on DB2
- removal of support for `for update` in `IngresDialect` and RDMS, since those databases only support `for update` in cursors, AFAICS
- fixed documentation of `Dialect.forUpdateOfColumns()`, which was completely wrong about its semantics
Fixes HHH-14210
=> HHH-14210 locking and DB2 (H6)

hibernate-core/src/main/java/org/hibernate/hql/internal/ast/util/LiteralProcessor.java, hibernate-core/src/test/java/org/hibernate/query/IntegerRepresentationLiteralParsingExceptionTest.java
https://hibernate.atlassian.net/browse/HHH-14213
The root cause is the string literal long value exceeds the Long value range. However, the exception message is misleading if Long string literal is provided. This PR changes the scope of the ticket to fix the exception message, which is confusing and misleading.
See the ticket comments for further details.
=> HHH-14213 Fix query numeric literal of integer representation parsing exception message

hibernate-core/src/main/antlr/sql-gen.g, hibernate-core/src/test/java/org/hibernate/test/annotations/onetomany/OrderByTest.java
https://hibernate.atlassian.net/browse/HHH-14148
The issue is invalid SQL like `... order by ... nulls last nulls last` would be generated for the combination of `@OrderBy on collection field` + `entity graph dictating the collection field to be fetched eagerly`.
So it turns out that the root cause is the following ANTLR2 snippet in sql-gen.g:
```
orderExprs { String ordExp = null; String ordDir = null; String ordNul = null; }
// TODO: remove goofy space before the comma when we don't have to regression test anymore.
// Dialect is provided a hook to render each ORDER BY element, so the expression is being captured instead of
// printing to the SQL output directly. See Dialect#renderOrderByElement(String, String, String, NullPrecedence).
: { captureExpressionStart(); } ( expr ) { …
```
=> HHH-14148 fix issue mapping-based order fragment might lead to incorrect SQL

hibernate-core/src/main/antlr/sql-gen.g, hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/FromClause.java, hibernate-core/src/test/java/org/hibernate/query/JoinOrderTest.java
https://hibernate.atlassian.net/browse/HHH-14201
Sometimes we generated SQL with wrong JOIN order. The root cause is we always reserve all the `EntityJoinFromElement`s without inserting them into AST tree,  until the last moment when we simply append them to the root level. However, it seems `EntityJoinFromElement` could show up anywhere and our special treatment of `EntityJoinFromElement` ends up with wrong SQL (some dbs could optimize by reverting back join order; whereas others simply accept it as it is and end up with error).
The solution is to insert all `EntityJoinFromElement`s back into the AST tree to ensure their original position or depth-first traversal order.
=> HHH-14201 Fix EntityJoinFromElement JOIN order issue

hibernate-core/src/main/java/org/hibernate/engine/internal/TwoPhaseLoad.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/loader/Loader.java, hibernate-core/src/main/java/org/hibernate/query/internal/AbstractProducedQuery.java, hibernate-core/src/test/java/org/hibernate/jpa/test/graphs/FetchGraphTest.java, hibernate-core/src/test/java/org/hibernate/jpa/test/graphs/LoadAndFetchGraphTest.java
https://hibernate.atlassian.net/browse/HHH-14212
This ticket exposes another regression issue and it forced me to re-consider the previous Fetch Graph implementation I initiated previously. It is becoming more and more difficult to maintain and obviously it is full of bugs and terribly fragile.
Finally I figured out we have a much simpler way to implement Fetch Graph we overlooked previously:
- revert back all the previous PRs related to Fetch Graph implementation and bug fixing (HHH-8776, HHH-14097, HHH-14124);
- simply add a logic in `TwoPhaseLoad` class to check whether Fetch Graph is in effective for now; return false if so in the internal `getOverridingEager()` method in `TwoPhaseLoad` class.
The reason is our HQL to SQL step has added all the JOINs already and we simply keep from …
=> HHH-14212 Ultimate Fetch Graph fix

hibernate-core/src/main/java/org/hibernate/query/criteria/internal/OrderImpl.java, hibernate-core/src/test/java/org/hibernate/query/criteria/internal/HHH13884Test.java
https://hibernate.atlassian.net/browse/HHH-13884
backport for #3272
[javax.persistence.criteria.Order.reverse()](https://docs.jboss.org/hibernate/jpa/2.2/api/javax/persistence/criteria/Order.html#reverse--) method javadoc explicitly declares that `reverse()` should return new instance.
=> HHH-13884 Order.reverse() contract

hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/inlinedirtychecking/DirtyCheckPrivateUnMappedCollectionTest.java
This PR skip the execution of the test when the bytecode provides is Javassist, the fix for https://hibernate.atlassian.net/browse/HHH-14220 was implemented only for ByteBuddy.
Not sure this is the best way to skip the test, any suggestion is more than welcome.
=> HHH-14220 Skip test when bytecode provider is Javassist

hibernate-core/src/test/java/org/hibernate/internal/ScrollableResultsObjectArrayCastingTest.java
Oracle stores null value when Lob field contains empty content, which happens to be the case for the original testing case.
=> HHH-14227 fix testing failure on Oracle

hibernate-core/src/main/java/org/hibernate/mapping/DenormalizedTable.java, hibernate-core/src/test/java/org/hibernate/test/inheritance/DenormalizedTablePhysicalIncludedTableConstraintTest.java
https://hibernate.atlassian.net/browse/HHH-14234
In denormalized table (child table with `TABLE_PER_CLASS` inheritance strategy is the only case in Hibernate), it shares many columns with its parent table, but it should stop duplicating any further. Among others, no need to duplicate unique constraint from parent table to child table or denormalized table.
=> HHH-14234 Fix issue denormalized table inherits unique constraints from parent table

hibernate-core/src/test/java/org/hibernate/test/inheritance/DenormalizedTablePhysicalIncludedTableConstraintTest.java
HANA dialect has special requirement regarding table name in terms of case sensibility. Renaming table names to UPPERCASE should solve the issue (another option is to put quotation marks around table names). See https://stackoverflow.com/questions/29974507/sap-hana-invalid-table-name
=> HHH-14234 Fix CI building error on HANA dialect

hibernate-core/src/test/java/org/hibernate/test/inheritance/DenormalizedTablePhysicalIncludedTableConstraintTest.java
Restricted testing on h2 dialect alone for the following two reasons:
* only H2 is tested fully;
* avoid irrelevant dialect features to break the testing case, so we can focus on the constraint issue in the test.
=> HHH-14234 fix CI building error on non-H2 dialect

hibernate-agroal/src/main/java/org/hibernate/agroal/internal/AgroalConnectionProvider.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DriverManagerConnectionProviderImpl.java
No rocket science here, when something is wrong in the setup (typically we cannot connect to the database), these variables can be null and we shouldn't end up with a NPE.
Noted while debugging a bug report in Quarkus.
https://hibernate.atlassian.net/browse/HHH-14316
https://hibernate.atlassian.net/browse/HHH-14317
Should be backported to 5.4.
=> HHH-14316 HHH-14317 Avoid accessing potentially null variables

hibernate-core/src/main/java/org/hibernate/query/internal/AbstractProducedQuery.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingsImpl.java, hibernate-core/src/main/java/org/hibernate/query/spi/QueryParameterBindings.java, hibernate-core/src/test/java/org/hibernate/test/hql/ParameterTest.java, hibernate-core/src/test/java/org/hibernate/test/jpa/compliance/tck2_2/StoredProcedureApiTests.java
https://hibernate.atlassian.net/browse/HHH-13310
I tried to avoid any change to API/SPIs, but I ended up adding the ` isAParameterList` to `org.hibernate.query.spi.QueryParameterBindings`, having this method a default should make the PR backportable also to 5.4 and 5.3.
=> HHH-13310 getParameterValue() not working for collections

.gitignore
https://hibernate.atlassian.net/browse/HHH-14324
The file isn't checked into the repository for this branch, but adding it to .gitignore just in case.
=> Backport HHH-14324 to branch 5.3 - Add .gradletasknamecache to .gitignore

hibernate-core/src/main/java/org/hibernate/type/CollectionType.java, hibernate-core/src/test/java/org/hibernate/test/annotations/selectbeforeupdate/UpdateDetachedTest.java
https://hibernate.atlassian.net/browse/HHH-14319
Hi @gbadner, I'm not 100% happy with the "fix" as it seems to me that the PersistentCollection entry shouldn't be replaced in the first place during flushing. Even if the replacing is intended, it should at least not wrap the collection that comes from the entity model, but create a copy instead. I think that the additional check in `CollectionType.replace` for `isWrapper` is a good one though and should be kept.
=> HHH-14319 Test and fix for CollectionType.replaceElements accidently clearing original collection

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/dirty/DirtyTrackingPersistTest.java
https://hibernate.atlassian.net/browse/HHH-14360
=> HHH-14360 Test a fix for NPE due to non-existing previous state in bytecode enhanced dirty attribute resolving

gradle.properties, gradle/java-module.gradle, gradle/libraries.gradle, hibernate-core/hibernate-core.gradle, hibernate-core/src/test/java/org/hibernate/test/bytecode/ReflectionOptimizerTest.java, hibernate-core/src/testJavassist/java/org/hibernate/test/bytecode/javassist/Bean.java, hibernate-core/src/testJavassist/java/org/hibernate/test/bytecode/javassist/BeanReflectionHelper.java, hibernate-core/src/testJavassist/java/org/hibernate/test/bytecode/javassist/BulkAccessorTest.java, hibernate-proxool/hibernate-proxool.gradle, tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
https://hibernate.atlassian.net/browse/HHH-14370
https://hibernate.atlassian.net/browse/HHH-14371
https://hibernate.atlassian.net/browse/HHH-14372
Workaround for https://github.com/gradle/gradle/issues/15538 , and a few more `--add-opens` to make tests work when illegal access is disabled. Strangely, we weren't using `--illegal-access=deny`? Anyway, JDK16-ea28 makes that the default.
This should fix compilation and tests on JDK16-ea28.
See https://ci.hibernate.org/view/Personal%20jobs/job/hibernate-orm-personal-yoann-jdk16/20/
Please do not backport to 5.4 yet: we need to backport the upgrade to toochains first.
=> HHH-14370 + HHH-14371 + HHH-14372 - Add required --add-opens options for Gradle, Weld, Javassist

hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/AbstractPluralAttributeSourceImpl.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/CodeTemplates.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/tracker/SimpleCollectionTracker.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/tracker/SimpleFieldTracker.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/tracker/SortedFieldTracker.java, hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BasicProxyFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/bytecode/spi/ByteCodeHelper.java, hibernate-core/src/main/java/org/hibernate/cache/internal/DisabledCaching.java, hibernate-core/src/main/java/org/hibernate/dialect/SpannerDialect.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/LobCreatorBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/LobCreatorBuilder.java, hibernate-core/src/main/java/org/hibernate/id/ExportableColumn.java, hibernate-core/src/main/java/org/hibernate/internal/EmptyScrollableResults.java, hibernate-core/src/main/java/org/hibernate/internal/util/Cloneable.java, hibernate-core/src/main/java/org/hibernate/internal/util/ReflectHelper.java, hibernate-core/src/main/java/org/hibernate/internal/util/StringHelper.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderProvidedQueryImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappingMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractPropertyMapping.java, hibernate-core/src/main/java/org/hibernate/persister/entity/UnionSubclassEntityPersister.java, hibernate-core/src/main/java/org/hibernate/sql/results/internal/StandardRowReader.java, hibernate-core/src/main/java/org/hibernate/tool/schema/spi/Exporter.java, hibernate-core/src/main/java/org/hibernate/type/MetaType.java, hibernate-core/src/main/java/org/hibernate/type/internal/StandardBasicTypeImpl.java
We have the following empty array constants in `org.hibernate.internal.util.collections.ArrayHelper`:
```
public static final String[] EMPTY_STRING_ARRAY = {};
public static final int[] EMPTY_INT_ARRAY = {};
public static final boolean[] EMPTY_BOOLEAN_ARRAY = {};
public static final Class[] EMPTY_CLASS_ARRAY = {};
public static final Object[] EMPTY_OBJECT_ARRAY = {};
public static final Type[] EMPTY_TYPE_ARRAY = {};
public static final byte[] EMPTY_BYTE_ARRAY = {};
```
This PR aims to reuse these constant in lieu of empty array creation to both boost performance and decrease memory footprint. Given the array is empty, it seems the replacement is hassle-free (unlike `Collections.emptyList()` which is immutable and adding element triggers exception).
As per …
=> wip/6.0 Reuse ArrayHelper's empty array constants to avoid unnecessary array creation

hibernate-core/src/main/java/org/hibernate/hql/spi/id/AbstractMultiTableBulkIdStrategyImpl.java, hibernate-core/src/main/java/org/hibernate/hql/spi/id/persistent/PersistentTableBulkIdStrategy.java, hibernate-core/src/test/java/org/hibernate/id/hhh14407/ChildEntity.java, hibernate-core/src/test/java/org/hibernate/id/hhh14407/ParentEntity.java, hibernate-core/src/test/java/org/hibernate/id/hhh14407/PersistentTableBulkIdStrategyNPETest.java
https://hibernate.atlassian.net/browse/HHH-14407
The NPE was introduced by https://github.com/hibernate/hibernate-orm/pull/3498. Specifically, the following new line introduced in that PR didn't take into consideration that some Column has null value (like the '**hib_sess_id**' column in **PersistentTableBulkIdStrategy**) so it would trigger NPE:
The fix is simple as the following two steps:
1. set the sql code type of the '**hib_sess_id**' to **Types.VARCHAR**;
2. in the above highlighted line, the **Column#getSqlTypeCode(Mapping mapping)** method is only invoked when **Column#getSqlTypeCode()** returns null; otherwise simply return the internal sqlTypeCode value directly, which is in line with the Javadoc of the method:
=> HHH-14407 NPE in AbstractMultiTableBulkIdStrategyImpl for column 'hib_sess_id' of PersistentTableBulkIdStrategy

hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java, hibernate-core/src/main/java/org/hibernate/dialect/function/ExtractFunction.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/StandardFunctionReturnTypeResolvers.java
`floor` and `ceiling` should not return `int` or `long` as that could lead to precision loss when extracting that value. Imagine if one of the two functions used `int`, then a query like this `select ceiling(2147483647.1)` (note that 2147483647 is the maximum integer value) would lead to an overflow error or precision loss as the correct return value is 2147483648.
On top of that, this PR enables "implicit casting" between numerics for the purpose of extraction from a JDBC result set. It should be possible to extract an `int` out of e.g. `double` if known to be compatible with `int` like it would be the case for certain `floor`/`ceiling` invocations, like in `org.hibernate.dialect.function.ExtractFunction#extractWeek`.
=> Implicit casting support for numerics and switch to argument type as return for floor/ceiling

hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
This is helpful to the schema update tool.
This workaround was lost during my work on `Dialect`s.
=> on H2 prior to 2.0 map NUMERIC to DECIMAL (H6)

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
Apparently H2 correctly reports column types via JDBC metadata since 2.0, so this workaround is unnecessary.
Also add a default mapping for DECIMAL in superclass, just for completeness.
cc @famod WDYT? Does this look good?
=> on H2 after 2.0 don't need column type workaround (H5)

hibernate-core/src/main/java/org/hibernate/type/UUIDBinaryType.java, hibernate-core/src/main/java/org/hibernate/type/UUIDCharType.java
Previously, Hibernate generated column definitions of length 255 for `BINARY`/`CHAR` columns that will have `UUID`s stored in them. It should be:
- length 16 for `BINARY`
- length 36 for `CHAR`
=> generate sensibly-lengthed columns for UUIDs

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultResolveNaturalIdEventListener.java, hibernate-core/src/main/java/org/hibernate/internal/util/collections/ArrayHelper.java, hibernate-core/src/main/java/org/hibernate/loader/entity/EntityLoader.java, hibernate-core/src/main/java/org/hibernate/loader/entity/NaturalIdEntityJoinWalker.java, hibernate-core/src/main/java/org/hibernate/loader/entity/NaturalIdType.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/UniqueKeyLoadable.java, hibernate-core/src/test/java/org/hibernate/test/naturalid/inheritance/cache/InheritedNaturalIdNoCacheTest.java
More efficient loading for entities with a single @NaturalId property only.
Uses a unique key EntityLoader instead of two SQL selects.
This is just a proof of concept for @sebersole to take a look at and give his feedback on.
=> more efficient loading by @NaturalId

hibernate-core/src/main/java/org/hibernate/action/internal/BulkOperationCleanupAction.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/DatabaseSnapshotExecutor.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSqlAstCreationState.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/AttributeMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityAssociationMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/PropertyBasedMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/CompoundNaturalIdMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/PluralAttributeMappingImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SingleAttributeIdentifierMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/MultiTableDeleteQueryPlan.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/MultiTableUpdateQueryPlan.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SimpleDeleteQueryPlan.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SimpleInsertQueryPlan.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SimpleUpdateQueryPlan.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmCastTarget.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstWalker.java, hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/CastTarget.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedResultImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/naturalid/mutable/cached/CachedMutableNaturalIdNonStrictReadWriteTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/naturalid/mutable/cached/CachedMutableNaturalIdStrictReadWriteTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/naturalid/mutable/cached/CachedMutableNaturalIdTest.java
Here a quick overview of the changes:
* Fix issues with inverse foreign key descriptor creation
* Use proper FK property for `ToOneAttributeMapping` instead of always using the target entity PK
* Introduce `EntityAssociationMapping#createDelayedDomainResult` for forcing proxy fetching
* Register `BulkOperationCleanupAction` after bulk operations to properly clear caches
* Rewrite `DatabaseSnapshotExecutor` to produce the state that structurally matches the entity state
* Fix natural id extraction issues
=> Fix issues with FK creation

hibernate-core/src/main/java/org/hibernate/collection/internal/AbstractPersistentCollection.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
This is the implementation that was discussed during the PR meet-up. Note that I also provided an alternative implementation that snapshots the load query influencers on detach: https://github.com/hibernate/hibernate-orm/pull/3776
https://hibernate.atlassian.net/browse/HHH-11076
=> HHH-11076 Log a warning if uninitialized collection unsets session when filters are enabled

migration-guide.adoc
Just fixing wrong property name in 5.1 migration guide document.
For context see https://hibernate.atlassian.net/browse/HHH-10345
=> (HHH-10345 related) fix wrong property name in 5.1 migration guide

hibernate-core/src/main/java/org/hibernate/type/AnyType.java, hibernate-core/src/main/java/org/hibernate/type/EntityType.java
This is quite a minor cleanup, to reduce our internal dependency on `EntityTuplizer`
=> remove two unnecessary calls to deprecated getEntityTuplizer()

tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/MetaAttributeGenerationVisitor.java, tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/CollectionAsBasicTypeTest.java
This fix is needed so that we can map List, Set, or Map entity attributes to JSON columns or to map List entity attributes to ARRAY columns, as explained [in this Hibernate Types project issue](https://github.com/vladmihalcea/hibernate-types/issues/137).
Initially, this was integrated into 5.2.17, but it was causing the [HHH-12581](https://hibernate.atlassian.net/browse/HHH-12581) issue, so it got reverted completely.
I this it's worth addressing it via a fix instead of removing this functionality altogether.
@sebersole @Naros If you have time to review it, I'd really appreciate it.
=> HHH-12338 - Incorrect metamodel for basic collections

hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java
When `@WhereJoinTable` gets applied to a collection, a superfluous `and` is added to the rendered SQL unnecessarily when no discriminator filter is rendered as part of the predicate condition.
=> Don't add superfluous "and" when there is no discriminator filter

hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/DelayedCollectionInitializer.java
A NPE is thrown due to `DelayedCollectionInitializer` relying on the `AbstractCollectionInitializer` behavior for `resolveKey`.  The overridden method does not register the resolution listener since the instance hasn't yet been resolved but only resolves the key.
=> Fix NPE with DelayedCollectionInitializer

hibernate-core/src/main/java/org/hibernate/query/results/dynamic/DynamicResultBuilderBasicStandard.java
Assuming a simple query as follows:
```
session.createNativeQuery( "SELECT group_id FROM GroupMember" ).addScalar( "group_id", IntegerType.INSTANCE )
```
This led to a NPE in the `StandardRowReader#getResultJavaType` method because the underlying `ResultAssembler` was passed a null JavaTypeDescriptor.  This change guarantees that if no explicit JavaTypeDescriptor is present but a type has been resolved, we resolve the JavaTypeDescriptor from the resolved type.
=> Resolve JavaTypeDescriptor for StandardRowReader

hibernate-core/src/main/java/org/hibernate/metamodel/internal/AbstractCompositeIdentifierMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ForeignKeyDescriptor.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/CompoundNaturalIdMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddedForeignKeyDescriptor.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/PluralAttributeMappingImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
I just saw these uses which were using the PK instead of relying on the FK descriptor.
=> Use FK descriptor instead of target entity identifier

hibernate-core/src/main/java/org/hibernate/query/results/TableGroupImpl.java, hibernate-core/src/main/java/org/hibernate/sql/ast/SqlTreePrinter.java, hibernate-core/src/main/java/org/hibernate/sql/ast/tree/cte/CteTableGroup.java, hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/AbstractTableGroup.java, hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/CompositeTableGroup.java, hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/MutatingTableReferenceGroupWrapper.java, hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/TableGroup.java, hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/UnionTableGroup.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/EntityCollectionPartTableGroup.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/CriteriaEntityGraphTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/EntityGraphLoadPlanBuilderTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/HqlEntityGraphTest.java
Fix issue with the order the `TableGroupJoin`s are rendered, this fix few envers test failures
=> Wip/6.0 TableGroupJoin rendering

hibernate-core/src/main/java/org/hibernate/query/hql/internal/BasicDotIdentifierConsumer.java
Avoid the creation of a new join sqm path when it already exists
=> Wip/6.0 Implicit join path creation 

documentation/documentation.gradle, gradle/databases.gradle, gradle/java-module.gradle, gradle/libraries.gradle, hibernate-core/src/main/java/org/hibernate/dialect/BooleanDecoder.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/FirebirdDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/FirebirdSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java, hibernate-core/src/main/java/org/hibernate/dialect/sequence/FirebirdSequenceSupport.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/spi/IdentifierHelperBuilder.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/inheritance/joined/JoinedSubclassAndSecondaryTable.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/SequenceValueExtractor.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/identifier/AssignedInitialValueTableGeneratorConfiguredTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/identifier/DefaultInitialValueTableGeneratorConfiguredTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/InsertUpdateTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/StandardFunctionTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/set/SetOperationJpaCriteriaTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/set/SetOperationTest.java
Also includes:
- Some general Firebird improvements
- Tweak tests to run (or be skipped) against Firebird
- Fix to BooleanDecoder
- Add statistical/linear regression function definitions in CommonFunctionFactory
- Added the relevant functions to other dialects where I could verify they apply
- Fix for unions with parenthesized selects
- Add casts for parameters in functions
=> HHH-14484 Improve support for Firebird 4

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java, hibernate-core/src/test/java/org/hibernate/test/notfound/EagerProxyNotFoundTest.java
https://hibernate.atlassian.net/browse/HHH-14537
=> HHH-14537 : EntityNotFoundException thrown when non-existing association with @NotFound(IGNORE) mapped has proxy in PersistenceContext

hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcCoordinatorImpl.java, hibernate-core/src/main/java/org/hibernate/resource/jdbc/internal/LogicalConnectionManagedImpl.java, hibernate-core/src/test/java/org/hibernate/test/connections/BeforeCompletionReleaseTest.java
https://hibernate.atlassian.net/browse/HHH-14557
Turns out we don't have a "before transaction completion" event in the case of rollbacks, so we need to rely on the "after transaction completion" event to do some more cleanup, even when using `DELAYED_ACQUISITION_AND_RELEASE_BEFORE_TRANSACTION_COMPLETION`.
Related: https://issues.redhat.com/browse/AG-168
=> HHH-14557 Connection leaked on rollback with mode DELAYED_ACQUISITION_AND_RELEASE_BEFORE_TRANSACTION_COMPLETION

hibernate-core/src/main/java/org/hibernate/query/internal/QueryImpl.java, hibernate-core/src/test/java/org/hibernate/test/filter/DynamicFilterTest.java, hibernate-core/src/test/java/org/hibernate/test/filter/Salesperson.java
https://hibernate.atlassian.net/browse/HHH-14567
No need to backport, as the optimization that causes the bug was not backported.
=> HHH-14567 Filters are ignored if enabled after query creation but before execution

hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
As suggested by @famod we need to use `localtime` instead of `current_time` because of changes in H2.
In particular the JDBC driver now refuses to convert `TIME/TIMESTAMP WITH TIME ZONE` to plain `TIME/TIMESTAMP`.
Does this look right @famod?
=> on H2 1.4.200 and above use localtime/localtimestamp (H5)

hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/MethodNode.java, hibernate-core/src/test/java/org/hibernate/test/hql/IndicesTest.java
https://hibernate.atlassian.net/browse/HHH-14475
The problem is this change https://github.com/hibernate/hibernate-orm/commit/692f19c83fef4339112e4fbabcc09437999a1bdf#diff-f4778da5555fb08fe09fe165d0e93cc4946d4f87bc44ad9b9d194df68d6d7743R157 which caused a subquery to be rendered for the collection function, although the join was already added to the from clause.
=> HHH-14475 Don't render subquery for collection functions

gradle.properties, gradle/java-module.gradle
Without this, I simply cannot run this locally:
```
./gradlew clean :hibernate-integrationtest-java-modules:test -Ptest.jdk.version=11 -Porg.gradle.java.installations.paths=$HOME/tools/java/jdk1.8,$HOME/tools/java/jdk11
```
It fails when the (JDK8) compiler encounters the `--add-opens` option, which is normal because that option isn't supported in JDK8:
```
> Task :hibernate-core:compileJava FAILED
Compiling with '/home/yrodiere/tools/java/jdk8u222-b10'
Unrecognized option: --add-opens
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
FAILURE: Build failed with an exception.
```
For some reason we don't get this failure on CI; I have no idea why. Regardless, it seems to me that there is a problem and it should be fixed.
=> Only apply --add-opens to compiler JVM options when using JDK9+

gradle.properties, gradle/java-module.gradle
Running CI before I backport this...
=> Backport to 5.4: Only apply --add-opens to compiler JVM options when using JDK9+

hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/engine/spi/AbstractDelegatingWrapperOptions.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/WrapperOptions.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/BasicBinder.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/BooleanTypeDescriptor.java, hibernate-core/src/test/java/org/hibernate/test/nationalized/MaterializedNClobBindTest.java
Here's what I think is a better way to do this:
I've introduced `doBindNull()` in `BasicBinder` and I'm using `WrapperOptions`, `FastSessionServices`, and `getPreferredSqlTypeCodeForBoolean()` for what they're designed for.
Perhaps one might object that adding `doBindNull()` introduces an additional polymorphic call when binding null values, but if that overhead were measurable, then it would actually be worse in the case of the regular `doBind()` call that exists today for all basic types when the value is not-null, and would be an argument for eliminating `BasicBinder` altogether. So I don't see any reasonable objection to this on performance grounds.
=> cleaner workaround for Oracle setNull(BOOLEAN) bug

hibernate-core/src/main/java/org/hibernate/exception/internal/SQLStateConverter.java, hibernate-core/src/main/java/org/hibernate/tool/hbm2ddl/MultipleLinesSqlCommandExtractor.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/AbstractScriptSourceInput.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/ScriptSourceInputNonExistentImpl.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/script/MultiLineSqlScriptExtractor.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/script/SqlScriptExtractorInitiator.java, hibernate-core/src/main/java/org/hibernate/tool/schema/spi/ScriptSourceInput.java, hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/schema/SchemaManagementScriptTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/tool/schema/scripts/CommandExtractorServiceTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/tool/schema/scripts/StatementsWithoutTerminalCharsImportFileTest.java
https://hibernate.atlassian.net/browse/HHH-14601
A simple refactoring to correct the typo of `extracter` (should be `extractor`) which I found during working on my previous PR.
=> wip/6.0 Fix the typo of `extracter` in codebase

hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JdbcTypeDescriptor.java
https://hibernate.atlassian.net/browse/HHH-14605
Given we have discussed about this, especially we have confirmed with Beikov, we can go ahead to fix it right away. See the discussion in https://github.com/hibernate/hibernate-orm/pull/3974.
=> wip/6.0 HHH 14605 Handling for BLOB, CLOB and NCLOB relative to JavaTypeDescriptor `#isString` and `#isBinary`

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/LazyAttributeLoadingInterceptor.java, hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/LazyCollectionLoadingTest.java, hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/ondemandload/OnDemandLoadTest.java
https://hibernate.atlassian.net/browse/HHH-14620
As far as I can tell this is safe enough for dirty tracking:
* The collection tracker will return a size of -1 for that collection
* Which is exactly the behavior we currently get after
`$$_hibernane_clearDirtyCollectionNames` is called if a collection has
been "retrieved" (getter called) but was not initialized.
* This will mainly prevent some optimizations because we will no longer
be able to tell whether a collection is "dirty" or not.
I think we should be able to restore those optimizations: for
`PersistentCollection` instances, we would store the "initial" size
inside the collection itself upon initialization,
and we would compare THAT size to the current size in implementations
of `$$_hibernate_areCollectionFieldsDirty` (see …
=> HHH-14620 Do not initialize collections just to take a snapshot of their size

hibernate-core/src/main/java/org/hibernate/event/internal/AbstractFlushingEventListener.java
A very minor change so HR can call  `logFlushResults()`.
=> make logFlushResults() protected for the benefit of HR

gradle/libraries.gradle
https://hibernate.atlassian.net/browse/HHH-14139
The bug is as follows. Suppose one string BasicBinder field contains the "{}" string, the corresponding logging statement would end up as below:
```
binding parameter [2] as [VARCHAR] - [binding parameter [2] as [VARCHAR] - [{}]]
```
not expected statement as:
```
binding parameter [2] as [VARCHAR] - [{}]
```
The root cause is a bug which was fixed by me in jboss-logging:3.4.2.Final: https://issues.redhat.com/browse/JBLOGGING-147?_sscc=t.
This is the only bug fixed in the new version of jboss-logging: https://github.com/jboss-logging/jboss-logging/releases/tag/3.4.2.Final. After we bump our dependency fomr 3.4.1 to it, the issue would be gone automatically.
This bug is only reproducible in SL4J logging framework (as common in Spring Boot …
=> HHH-14139 BasicBinder Trace Logging Causes Duplicated Message

hibernate-core/src/main/java/org/hibernate/loader/Loader.java, hibernate-core/src/main/java/org/hibernate/loader/hql/QueryLoader.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/Loadable.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/manytoone/JoinFetchedManyToOneAllowProxyTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/manytoone/ManyToOneAllowProxyTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/manytoone/ManyToOneExplicitOptionTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/mappedby/InverseToOneAllowProxyTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/mappedby/InverseToOneExplicitOptionTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/mappedby/JoinFetchedInverseToOneAllowProxyTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/onetoone/JoinFetchedOneToOneAllowProxyTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/onetoone/OneToOneAllowProxyTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/onetoone/OneToOneExplicitOptionTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/polymorphic/JoinFetchedPolymorphicToOneTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/polymorphic/PolymorphicToOneExplicitOptionTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/polymorphic/PolymorphicToOneImplicitOptionTests.java, hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/join/HHH3949Test.java
https://hibernate.atlassian.net/browse/HHH-14659
This is not a great fix. But it should work. All the code related to loaders, and especially lazy/eager fetching, is being rewritten in ORM 6, and for good reasons. With that in mind, I think investing more in this fix would be a waste of time.
Here's an explanation of the problem, if someone wants more information:
For mapped-by associations, we generate the correct SQL and fetch the associated entities correctly, and we even add them to the session. But when we decide which value to assign to the corresponding property, we assume that since the property is lazy,  we didn't retrieve it. Which is wrong when `join fetch` is being used.
This behavior was most likely implemented when fixing …
=> HHH-14659 "join fetch" on mapped-by association is ignored when using bytecode enhancement

documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc, hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/ExtractedDatabaseMetaDataImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/spi/ExtractedDatabaseMetaData.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/spi/IdentifierHelperBuilder.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/spi/JdbcEnvironment.java, hibernate-core/src/main/java/org/hibernate/id/SequenceMismatchStrategy.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStyleGenerator.java, hibernate-core/src/test/java/org/hibernate/engine/jdbc/env/internal/SkipLoadingSequenceInformationTest.java, hibernate-core/src/test/java/org/hibernate/test/dialect/functional/SQLServerDialectSequenceInformationTest.java, hibernate-core/src/test/java/org/hibernate/test/jdbc/env/NoDatabaseMetaDataTest.java, hibernate-core/src/test/java/org/hibernate/test/schemafilter/SequenceFilterTest.java, hibernate-testing/src/main/java/org/hibernate/testing/boot/BasicTestingJdbcServiceImpl.java
This PR attempts to minimize the number of queries we need to run on bootstrap to fech database metadata and schema information, so to improve bootstrap times as apparently when having very large databases the time was getting out of hand (multiple minutes).
It turns out that some minor queries we did run were not used for any purpose; these were the simplest one to fix, simply by deleting them.
Loading the Sequences information was also reported as being very time consuming, and only useful for certain combinations of mappings - such as
- you need to have sequences
- you need to be using them
- they need to be mapped with a pooled optimizer
- not emulated via tables
If all these conditions are true, and only in this case, we would have good use for this metadata so to validate the …
=> HHH-14667 Reduce amount of Database metadata details being loaded during bootstrap

hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/ColumnNameCache.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/ResultSetWrapperProxy.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/ResultSetWrapperImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/ResultSetWrapper.java
Deprecate ResultSet wrapping related to performance of reading from ResultSet by name in preparation for removing those contracts from 6.0
=> HHH-14679 - Deprecate ResultSetWrapper and friends

tooling/hibernate-gradle-plugin/src/main/groovy/org/hibernate/orm/tooling/gradle/EnhancementHelper.java
The runtime classpath contains the dependencies as jars that are not yet built when the plugin needs them. So use the compile classpath plus the compiled classes of the current project.
=> HHH-14657 Use the compile instead of runtime classpath

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/DomainParameterXref.java
Just found this error during criteria verifying. Usually for HashMap or HashSet with expected element size, the below is a surprising common error:
```
Map<String, String> map = new HashMap<>( expectedSize );
``` 
for HashMap or HashSet's load factor is never 1 so it will end up with growing unnecessarily and time consuming, thus defeating the purpose of such size specification endeavour in the first place.
There are tons of such misuse in our codebase, but it is not the scope of this PR (I even created a PR to fix the error in ANTLR (see https://github.com/antlr/antlr4/pull/2938). I believe the misuse is a performance drain for it is used so often everywhere. Off course CollectionHelper has provided util methods for both HashMap and HashSet, but they are not used as often as expected. …
=> wip/6.0 HHH-14642 fix a misuse of IdentityHashMap

tooling/hibernate-gradle-plugin/src/main/groovy/org/hibernate/orm/tooling/gradle/EnhancementHelper.java
The runtime classpath contains the dependencies as jars that are not yet built when the plugin needs them. So use the compile classpath plus the compiled classes of the current project.
Since Spring Boot 2.6 (which uses Hibernate 5.5) will be released not before November, it would be nice to have this fix available for Spring Boot 2.5 (which uses Hibernate 5.4).
=> HHH-14657 Use the compile instead of runtime classpath (5.4 backport)

hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQL81Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/spi/IdentifierHelperBuilder.java, hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/InformationExtractorJdbcDatabaseMetaDataImpl.java, hibernate-core/src/test/java/org/hibernate/test/schemaupdate/SchemaUpdateWithUseJdbcMetadataDefaultsSettingToFalseAndQuotedNameTest.java, hibernate-core/src/test/java/org/hibernate/test/schemaupdate/SchemaUpdateWithUseJdbcMetadataDefaultsSettingToFalseTest.java
https://hibernate.atlassian.net/browse/HHH-13788
It should fix https://github.com/quarkusio/quarkus/issues/5883
=> HHH-13788 Schema update try to recreate existing tables

databases/derby/matrix.gradle, gradle/libraries.gradle
https://hibernate.atlassian.net/browse/HHH-14719
=> HHH-14719 bump apache-derby to 10.14.2.0 fixing CVE-2015-1832 and CVE-2018-1313

hibernate-core/src/test/java/org/hibernate/test/temporal/TimePropertyTest.java
Issue: https://hibernate.atlassian.net/browse/HHH-14697
JBEAP Issue: https://issues.redhat.com/browse/JBEAP-22070
=> HHH-14697 TimePropertyTest fails on MySQL 8.0 with a ComparisonFailure

hibernate-core/src/main/java/org/hibernate/mapping/Column.java, hibernate-core/src/test/java/org/hibernate/test/mapping/ColumnLastIndexNotLetterAliasTest.java
https://hibernate.atlassian.net/browse/HHH-14720
This is needed or hibernate-reactive.
=> HHH-14720 : Aliases generated for mixed-case column names that end in a number are not all lower-case

hibernate-core/src/main/java/org/hibernate/boot/model/naming/CamelCaseToUnderscoresNamingStrategy.java
Hi @philwebb , @mbhave I assume you'd be cool with this?
Please let me know, as I've heard people are commonly copying this from Spring Boot: it's probably more convenient for all if we distribute this naming strategy with ORM.
- https://hibernate.atlassian.net/browse/HHH-14728
=> HHH-14728 Include CamelCaseToUnderscoresNamingStrategy from Spring Boot

hibernate-core/src/main/java/org/hibernate/loader/Loader.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/collectioninitializer/Company.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/collectioninitializer/CostCenter.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/collectioninitializer/InitLazyToOneWithinPaddedCollectionInitializationAllowProxyTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/collectioninitializer/Offer.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/collectioninitializer/User.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/lazytoone/collectioninitializer/UserAuthorization.java
https://hibernate.atlassian.net/browse/HHH-14730
See `org.hibernate.orm.test.mapping.lazytoone.collectioninitializer.InitLazyToOneWithinPaddedCollectionInitializationAllowProxyTest#testTwoReferences` for the reproducer; I think that's the easiest way to understand the scenario (though it's still complex...).
=> HHH-14730 Failure during lazy loading of bytecode-enhancement proxy triggered by the loading of a collection with eager references to that proxy

tooling/metamodel-generator/hibernate-jpamodelgen.gradle, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/TypeRenderingVisitor.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/TypeUtils.java, tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/CollectionAsBasicTypeTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/ConcreteLike.java, tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/Goods.java, tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/Like.java
Test case for https://hibernate.atlassian.net/browse/HHH-14724
I hijacked an existing test by adding bean validation to a list converter. With this change, two tests in `org.hibernate.jpamodelgen.test.collectionbasictype.CollectionAsBasicTypeTest` result in compilation errors.
I can add a separate test-case if that makes more sense.
=> HHH-14724 Test-case for metamodel compile error with converters and validation

hibernate-core/src/test/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyBasicProxyFactoryTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/reflection/JPAXMLOverriddenAnnotationReaderTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metadata/StaticMetadataTest.java, hibernate-envers/src/test/java/org/hibernate/envers/test/integration/basic/BasicTypeColumnDefinitionTest.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/components/mappedsuperclass/EmbeddableWithDeclaredDataTest.java
Fix https://hibernate.atlassian.net/browse/HHH-14762
=> HHH-14762 Testsuite: Assert.notNull must not be used on primitive types

hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetamodelImpl.java
https://hibernate.atlassian.net/browse/HHH-14770
It causes memory leaks (`SessionFactory` instances are never garbage collected, for some reason. See the comments on the JIRA issue.
=> Revert HHH-14770 Optimise access to EntityPersister in Metamodel via Class type

hibernate-core/src/main/java/org/hibernate/resource/jdbc/internal/ResourceRegistryStandardImpl.java
The callers of the convert() method in ResourceRegistryStandardImpl expect an exception which is then thrown. This can produce NullPointerException, which has been fixed in this commit.
=> HHH-13848 - Fix for potential NullPointerException

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchSelectImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchByUniqueKeyInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/internal/domain/CircularFetchImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/notfound/OptionalEagerInEmbeddableNotFoundTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/notfound/OptionalEagerMappedByNotFoundTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/notfound/OptionalEagerNotFoundTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/notfound/OptionalEagerRefNonPKNotFoundTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/notfound/OptionalLazyNotFoundTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/notfound/RequiredLazyNotFoundTest.java, hibernate-core/src/test/java/org/hibernate/test/notfound/EagerProxyNotFoundTest.java, hibernate-core/src/test/java/org/hibernate/test/notfound/ToDeleteTest.java
Fix load toOne association not referencing a PK with `FetchMode.SELECT`
Fix throw `EntityNotFoundException` when an association not mapped with  `NotFound(IGNORE)`
=> Re-enabled additional tests

gradle/libraries.gradle
- https://hibernate.atlassian.net/browse/HHH-14812
=> HHH-14812 Upgrade integration tests to use Oracle JDBC driver v 21.3.0.0

hibernate-core/src/test/java/org/hibernate/test/hql/DeleteWhereFunctionCallTest.java
https://hibernate.atlassian.net/browse/HHH-14814
I don't know how to fix this bug in 5.x, but it turns out it's already been fixed in 6.0, somehow.
Let's merge the test and close the ticket as fixed in 6.0?
=> HHH-14814 Inconsistent rendering of table alias in delete queries

hibernate-core/src/main/java/org/hibernate/dialect/Database.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServer2016Dialect.java
SQL Server 2016 (13.x) and later support the `if exists` clause for most `drop` DDL statements. The new `SQLServer2016Dialect` dialect accounts for this and offers the advantage that no error messages get logged when using `hibernate.hbm2ddl.auto=create-drop`.
=> HHH-13999 Support SQL Server 2016

hibernate-core/src/main/java/org/hibernate/cfg/annotations/reflection/internal/JPAXMLOverriddenAnnotationReader.java, hibernate-core/src/test/java/org/hibernate/jpa/test/xml/XmlAndAnnotationAttributeOverrideTest.java, hibernate-core/src/test/java/org/hibernate/test/util/SchemaUtil.java, hibernate-core/src/test/resources/org/hibernate/jpa/test/xml/orm-empty.xml
https://hibernate.atlassian.net/browse/HHH-14827
It turns out this is a bug, caused by [HHH-14529](https://hibernate.atlassian.net/browse/HHH-14529) (the new JAXB implementation of orm.xml parsing). So it only affects 5.6 and 5.5.
The bug probably also affected `@AssociationOverride` and `@PrimaryKeyJoinColumn`; that's fixed in this PR as well.
I created a backport to 5.5 here: #4225 . Please don't forget to merge it as well.
=> HHH-14827 @AttributeOverride at type level does not work when also using orm.xml

hibernate-core/src/main/java/org/hibernate/action/internal/EntityUpdateAction.java, hibernate-core/src/test/java/org/hibernate/event/PreUpdateEventListenerVetoTest.java
https://hibernate.atlassian.net/browse/HHH-14413
Straightforward implementation and testing.
=> HHH-14413 fix issue that EntityUpdateAction increments version despite veto on update

hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQL81Dialect.java, hibernate-core/src/test/java/org/hibernate/dialect/PostgreSQL81DialectTestCase.java
Addressing issue [HHH-13661](https://hibernate.atlassian.net/browse/HHH-13661) whereby triggering a client-side query timeout for PostgreSQL (e.g. by setting the `javax.persistence.query.timeout` property) resulted in a generic JDBC exception rather than being mapped to the specific `QueryTimeoutException` provided by Hibernate.
I opted to implement this as part of the PostgreSQL dialect-specific SQL State conversion delegate. As mentioned by the original reporter (who deserves a lot of credit for doing most of the legwork on the reported issue!), there were a few other options, including adding to [some existing DB-specific checks within the generic SQL State conversion delegate](https://github.com/hibernate/hibernate-orm/blob/39e576cea49c62763e651237f3666f97205406f6/hibernate-core/src/ma …
=> HHH-13661 | Added case to PostgreSQL Dialect to map client operation cancellation to QueryTimeoutException

hibernate-core/src/main/java/org/hibernate/dialect/SQLServer2012Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
https://hibernate.atlassian.net/browse/HHH-14794
=> HHH-14794 : More changes to support SchemaMigrator/SchemaValidator using Hibernate Reactive

hibernate-core/src/main/java/org/hibernate/type/OneToOneType.java, hibernate-core/src/test/java/org/hibernate/test/onetoone/cache/OneToOneCacheEnableSelectingTest.java, hibernate-core/src/test/java/org/hibernate/test/onetoone/cache/OneToOneCacheTest.java
https://hibernate.atlassian.net/browse/HHH-14826
=> HHH-14826 - Regression: OneToOne fields are always null if parent is loaded from L2 cache

hibernate-core/src/main/java/org/hibernate/dialect/SQLServer2012Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SybaseDialect.java, hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/AbstractInformationExtractorImpl.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardSequenceExporter.java, hibernate-core/src/test/java/org/hibernate/test/schemaupdate/SchemaExportSqlServerWithSequenceDefaultSchemaCatalog.java
https://hibernate.atlassian.net/browse/HHH-14835
=> HHH-14835 : More changes to support SchemaMigrator/SchemaValidator using Hibernate Reactive

hibernate-core/src/test/java/org/hibernate/test/inheritance/TransientOverrideAsPersistentJoined.java, hibernate-core/src/test/java/org/hibernate/test/inheritance/TransientOverrideAsPersistentTablePerClass.java
https://hibernate.atlassian.net/browse/HHH-14840 
5.3 branch
=> HHH-14840 : IBM Db2 11.1 fails on TransientOverride test cases (5.3)

hibernate-core/src/main/java/org/hibernate/boot/internal/BootstrapContextImpl.java, hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/MutableJpaComplianceImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/JpaComplianceTests.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/ServiceRegistryScope.java
Allow setting all JpaCompliance flags using a single setting (`AvailableSettings#JPA_COMPLIANCE`).  This simply acts as a default which can be overridden using the individual settings
=> JpaCompliance improvement

test-case-guide.adoc
https://hibernate.atlassian.net/browse/HHH-14926
The first char in `(C)complete` was rendered as copyright symbol (&copy;) as below. Need to escape as https://docs.asciidoctor.org/asciidoc/latest/subs/prevent/#escape-with-backslashes.
@
=> HHH-14926 fix ascii error in 'test-case-guide.adoc'

documentation/src/main/asciidoc/userguide/chapters/domain/identifiers.adoc
Code sample uses `Book` entity instead of `PersonAddress`.
=> Docs: Refer correct entity in "Composite identifiers with associations" section

hibernate-testing/src/main/java/org/hibernate/testing/cleaner/JdbcConnectionContext.java
https://hibernate.atlassian.net/browse/HHH-14936
=> HHH-14936 JdbcConnectionContext in hibernate-testing throws NPE when user/password are not provided in configuration

hibernate-core/src/main/java/org/hibernate/dialect/SybaseASE15Dialect.java
As stated in https://hibernate.atlassian.net/browse/HHH-14937 our code breaks with the update to 5.6.0 due to [this commit](https://github.com/hibernate/hibernate-orm/commit/8cecdd3f43796c134688d99b6387d59600e75738)
The PR adds the support for schemas again. This is supported since ASE 15.5, see [documentation](https://infocenter.sybase.com/help/topic/com.sybase.infocenter.dc36272.1550/html/commands/X48762.htm?resultof=%22%73%63%68%65%6d%61%22%20).
=> [HHH-14937] SybaseASE15 supports schemas and catalogs

hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/NamedQueryCommentTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/onetoone/OneToOneMapsIdJoinColumnTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/InClauseParameterPaddingCriteriaTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/InClauseParameterPaddingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/MaxInExpressionParameterPaddingTest.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/jdbc/DefaultSQLStatementInspectorSettingProvider.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/AbstractEntityManagerFactoryScope.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/EntityManagerFactoryExtension.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/EntityManagerFactoryScope.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/Jpa.java
Change 'provider' attribute in @SettingProvider to ' providerClass'
Remove 'statementInspectorClass' from @Jpa and refactor its usage to use a @SettingProvider
=> Remove 'statementInspectorClass' from @Jpa

documentation/documentation.gradle, documentation/src/test/java/org/hibernate/userguide/caching/FirstLevelCacheTest.java, documentation/src/test/java/org/hibernate/userguide/caching/NonStrictReadWriteCacheTest.java, documentation/src/test/java/org/hibernate/userguide/mapping/identifier/CacheableNaturalIdTest.java, documentation/src/test/java/org/hibernate/userguide/pc/MultiLoadIdTest.java, gradle/libraries.gradle, hibernate-jcache/hibernate-jcache.gradle, hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/InsertedDataTest.java, hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/JCacheTransactionalCacheConcurrencyStrategyTest.java, hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/RefreshUpdatedDataTest.java, hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/TestHelper.java, hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/EventManager.java, hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/Product.java, release/release.gradle, settings.gradle
Hey @sebersole. My PR against ehcache3 is an enormous ball of Gradle goo, so its still waiting on some poor soul to have the courage to review it. In order to expedite things I've instead cut an informal release with the proposed changes as `3.10.0-alpha0`. This PR is my first cut at re-enabling the `hibernate-jcache` module using that release. I made a cursory attempt at the archaeology required but I probably missed some code that should have been reinstated/uncommented.
Since the proposal for Ehcache 3 is to use Gradle capabilities and feature variants to handle this split it doesn't quite play perfectly with the way Hibernate's build system abstracts its dependencies. Currently I just left the version in `gradle/libraries.gradle` and the capability requirement in the couple of …
=> HHH-14837 : Re-enable hibernate-jcache module.

gradle/libraries.gradle
Changelog:
- https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-27.html
Motivation:
- https://www.oracle.com/security-alerts/cpuoct2021.html#AppendixMSQL
=> HHH-14938 Upgrade to MySQL Connector/J 8.0.27

hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQL81Dialect.java, hibernate-core/src/test/java/org/hibernate/test/lob/PostgreSqlLobStringTest.java, migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-14211
Also see the discussion here:
=> HHH-14211 Switch to using oid for CLOB in PostgreSQL to avoid losing data after vacuumlo

hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
Previously `Session.merge()` erased the generic type parameter inherited from the supertype, obligating the client code to perform a typecast.
See https://github.com/hibernate/hibernate-orm/discussions/4391
=> fix the signature of Session.merge()

hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetamodelImpl.java, hibernate-core/src/test/java/org/hibernate/test/hql/QuerySplitterTest.java
Corresponding task: [HHH-14948](https://hibernate.atlassian.net/browse/HHH-14948)
The original change from [HHH-12485](https://hibernate.atlassian.net/browse/HHH-12485) introduced memory issues (as described in the corresponding task). As such, I am requesting that it is reverted.
I have also added a test to illustrate the issue as is the requirement for bugfix tasks. That said, I don't particularly like using reflection in the way I have so I don't mind dropping the test altogether or accepting advice from more experienced Hibernate developers on how I could perform the test better.
=> HHH-14948 - Reduce the size of the imports cache in the metamodel

hibernate-core/src/main/java/org/hibernate/StatelessSession.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/StatelessSessionTest.java
It was already annotated `@Remove`.
=> remove left-behind method createSQLQuery() from StatelessSession

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java, hibernate-core/src/test/java/org/hibernate/orm/test/stats/CriteriaStatTest.java
Running the same test with Hibernate ORM 5,
it seems that statistics are enabled on JPA criteria queries...
=> Support statistics when criteria(s) are executed

hibernate-core/src/main/java/org/hibernate/cache/spi/AbstractRegionFactory.java, hibernate-core/src/main/java/org/hibernate/cfg/BinderHelper.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/ConnectionProviderInitiator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/BasicFormatterImpl.java, hibernate-core/src/main/java/org/hibernate/exception/internal/SQLStateConversionDelegate.java, hibernate-core/src/main/java/org/hibernate/internal/util/StringHelper.java
https://hibernate.atlassian.net/browse/HHH-14970
Mainly focused on the following two new Java language features introduced from v8 to v11 (I referred to https://ondro.inginea.eu/index.php/new-features-in-java-versions-since-java-8/):
- new String's methods in JDK 11 (e.g. String#isBlank());
- new Collection factory methods in JDK 9 (i.e., List.of(), Map.of(), Set.of()); 
Demonstrably `List.of()` is better than `Arrays.asList()` even in immutability context (see https://stackoverflow.com/questions/46579074/what-is-the-difference-between-list-of-and-arrays-aslist, e.g.), but given the latter has been an established pattern, it won't be touched upon. This PR mainly focused on easy migration so it is easy to review and verify.
=> HHH-14970 make use of new Java language features from v8 to v11

hibernate-core/src/main/java/org/hibernate/mapping/Column.java
From Hibernate Search we need to have the scale of the column that is finally applied by ORM.
This is the solution we found with @dreab8 and @yrodiere.
I wouldn't have exposed such a method but instead `getColumnSize` without any parameter, but I was one versus two :)
=> Cache and expose column size to get the (default and non-default) scale

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/MetamodelBoundedCacheTest.java, hibernate-core/src/test_legacy/org/hibernate/test/hql/QuerySplitterTest.java
This particular test is disabled as it's located in `test_legacy` .. it's also not compiling but it's a 1:1 port of the contribution already applied on 5.6 so I'd first align these to not forget.
I'll try to conver the test soon with @dreab8
=> HHH-14948 Adapt contributed patch to 6.0 branch

hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/MiddleTableCollectionMetadataGenerator.java, hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/EntityConfiguration.java, hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/RelationDescription.java, hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/internal/CriteriaTools.java, hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/internal/NotNullAuditExpression.java, hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/internal/NullAuditExpression.java, hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/internal/RelatedAuditEqualityExpression.java, hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/internal/RelatedAuditInExpression.java, hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/internal/SimpleAuditExpression.java, hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/AuditAssociationQueryImpl.java, hibernate-envers/src/test/java/org/hibernate/envers/test/integration/dynamic/AuditedDynamicComponentsAdvancedCasesTest.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/components/dynamic/SanityCheckTest.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/query/AssociationToManyJoinQueryTest.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/query/AssociationToNotAuditedManyJoinQueryTest.java
https://hibernate.atlassian.net/browse/HHH-11735
This PR supersedes PR #1904 by retargetting against `main` rather than 5.6.
=> HHH-11735 Support traversal of to-many-associations in audit queries.

hibernate-envers/src/main/java/org/hibernate/envers/query/AuditQuery.java, hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/AbstractAuditQuery.java, hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/AuditAssociationQueryImpl.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/query/AssociationQueryWithOnClauseTest.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/query/ComponentQueryTest.java
https://hibernate.atlassian.net/browse/HHH-11896
This PR supersedes PR #1967 by targetting ORM 6 `main` branch.  This PR currently depends upon PR #4479 and should only be merged after the parent pull request passes CI and is merged.
=> HHH-11896 Support 'on-clause' criterion when traversing audit query relations

hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/AbstractAuditAssociationQuery.java, hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/AbstractAuditQuery.java, hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/EntitiesAtRevisionAssociationQuery.java, hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/EntitiesAtRevisionQuery.java, hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/EntitiesModifiedAtRevisionQuery.java, hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/RevisionsOfEntityAssociationQuery.java, hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/RevisionsOfEntityQuery.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/BaseEnversFunctionalTestCase.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/query/AssociationRevisionsOfEntitiesQueryStoreAtDeletionTest.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/query/AssociationRevisionsOfEntitiesQueryTest.java
https://hibernate.atlassian.net/projects/HHH/issues/HHH-13817
This PR offers preliminary support for `traverseRelation` calls for `RevisionsOfEntityQuery` types.  The support for traversing to-many associations across the various query types will be introduced in another pull request as there is currently no support for that across all query types.
=> HHH-13817 Support to-one traverseRelations for RevisionsOfEntity queries

hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/CollectionMetadataContext.java, hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/MiddleTableCollectionMetadataGenerator.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/manytomany/BasicWhereTest.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/onetomany/BasicWhereTest.java
https://hibernate.atlassian.net/browse/HHH-9432
This PR supersedes #1729; however, this PR requires work from [HHH-14977](https://hibernate.atlassian.net/browse/HHH-14977) in order to be merged since at least one of the test cases fail due to improper ORM rendering of the `@Where` clause.  
This fix was tested against 5.6 and works so its just a simple matter of addressing the dependency issue and then this can be merged thereafter.  
@Sanne @sebersole  in terms of backports; this won't backport directly to 5.6 since the metadata generators have changed a bit since 5.x due to the removal of Dom4j.  Do you want me to open a specific PR that targets 5.6 with this fix or are you okay with this going directly into 6.0 only?
=> HHH-9432 Fix audit queries when `@Where` applied to discriminator mappings

hibernate-core/src/main/java/org/hibernate/Hibernate.java, hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentSortedMap.java, hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentSortedSet.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/detached/DetachedCollectionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/detached/Many.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/detached/One.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/detached/Several.java
This is designed to be useful for object-graph deserialization.
It's just a rough draft for discussion.
Summary: right now, you can create an uninitialized detached collection just by doing `new PersistentList()` or `new PersistentSet()`, or whatever, and it seems to work. But that exposes you to internal Hibernate APIs.
This PR adds an API to the `Hibernate` class that let's you do things like:
Hibernate.<Element>set().createDetachedInstance()
Hibernate.<Key,Value>Map().createNewInstance()
which is useful for this sort of generic code.
=> proposed API for instantiation of detached collections

hibernate-core/src/main/java/org/hibernate/SynchronizeableQuery.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/metamodel/MappingMetamodel.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappingMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/spi/MetamodelImplementor.java, hibernate-core/src/main/java/org/hibernate/procedure/ProcedureCall.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java, hibernate-core/src/main/java/org/hibernate/query/NativeQuery.java, hibernate-core/src/main/java/org/hibernate/query/Query.java, hibernate-core/src/main/java/org/hibernate/query/QueryProducer.java, hibernate-core/src/main/java/org/hibernate/query/TupleTransformer.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/QueryProducerImplementor.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sql/spi/NativeQueryImplementor.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/query/QueryAndSQLTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/QueryTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/formula/FormulaNativeQueryTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/resultmapping/EntityResultTests.java, hibernate-core/src/test/java/org/hibernate/test/sql/hand/query/NativeSQLQueriesTest.java
The main goal of this work is to alleviate the problem of warning in the client program resulting from invocations of raw `Query`s returned by Hibernate `Session` methods.
This is a difficult problem due to the requirements of backward compatibility with ancient versions of Hibernate, and due to the inheritance from `EntityManager` which still uses raw types.
As discussed, I have:
- Preferred the use of `@SuppressWarnings("rawtypes")` to wildcards `<?>` in methods of `Query`.
- `@Deprecated` `createXxxxQuery()` methods which accept no class.
- improved the `createNativeQuery()` methods with additional overloads, and the ability to accept a non-entity result class.
This solution is imperfect, but it's at least an improvement.
=> proposed fixes to Query API

hibernate-core/src/main/java/org/hibernate/query/Query.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java, hibernate-core/src/test/java/org/hibernate/orm/test/exceptionhandling/ExceptionExpectations.java, hibernate-core/src/test/java/org/hibernate/orm/test/exceptionhandling/QueryExceptionHandlingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/QueryTest.java
which incorrectly described the semantics of this method
=> fix the javadoc of Query.getSingleResult()

documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc, hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractIdentifiableType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/IdentifiableDomainType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AttributeContainer.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmPolymorphicRootDescriptor.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/domain/gambit/GambitDomainModel.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/domain/gambit/VersionedEntity.java
I noticed that the grammar defines `id()`, `version()`, and `naturalid()` functions.
Two of these were already working, but weren't documented, and I could not find where they were tested. So I added documentation and tests.
`naturalid()` was unimplemented, so I (roughly) implemented it, at least for the case of a single`@NaturalId` field.
=> id(), version(), and naturalid()

hibernate-core/src/main/java/org/hibernate/dialect/identity/H2IdentityColumnSupport.java
This should be cherry picked into Hibernate 5.x
=> HHH-14985 H2Dialect does not work properly with h2 2.0.202 on inserts

hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/query/Query.java, hibernate-core/src/main/java/org/hibernate/query/QueryProducer.java, hibernate-core/src/main/java/org/hibernate/query/spi/QueryProducerImplementor.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/InsertUpdateTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/InsertWithSubSelectTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/LiteralTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/NamedHqlQueriesTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/OrderByTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/ScrollableTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/SizeAttributeReferenceTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/StandardFunctionTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/SubqueryOperatorsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/TupleTest.java
So, I kinda messed up, and forgot that `createQuery()` is used for running things that aren't queries (insert, update, and delete statements).
But it's OK, because this is much better anyway.
=> createStatement() methods for QueryProducer

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/SqmMapEntryResult.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/StandardFunctionTests.java
And add tests for HQL collection functions.
The reason I noticed is that hamcrest didn't consider the two entries the same. `Map.entry()` has been around since Java 9, so I would say it's perfectly safe for us to use, right?
=> use Map.entry() instead of our own MapEntryImpl for entry() function

hibernate-core/src/main/java/org/hibernate/Hibernate.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/FetchGraphTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/ProxyDeletionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/connections/HibernateCreateBlobFailedCase.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/NativeQueryResultTypeAutoDiscoveryTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/lob/BlobLocatorTest.java
This is in principle a breaking change, but one I consider pretty innocuous, since I can't imagine why anyone was calling `Hibernate.getLobCreator(session)` instead of `session.getLobHelper()`.
It's important that we not leak internal APIs like `SessionImplementor` into the signature of public APIs in `org.hibernate`.
=> remove the layer-breaking getLobCreator() methods from Hibernate class

documentation/src/test/java/org/hibernate/userguide/schema/CheckTest.java, hibernate-core/src/main/java/org/hibernate/annotations/Check.java, hibernate-core/src/main/java/org/hibernate/annotations/ForeignKey.java, hibernate-core/src/main/java/org/hibernate/annotations/Index.java, hibernate-core/src/main/java/org/hibernate/annotations/Table.java, hibernate-core/src/main/java/org/hibernate/cfg/AnnotatedColumn.java, hibernate-core/src/main/java/org/hibernate/cfg/AnnotatedJoinColumn.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/EntityBinder.java
This was a bug!
Also:
- add `checkConstraint` member to `@Table` to allow check constraints on secondary tables, and
- clean up some Javadoc of some related annotations.
=> make @Check work when applied at the field level

hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
Strictly, `elements()` and `indices()` don't make sense as select items, but we have tests for this, and users who reported bugs and sent in patches, etc, etc, so I'm going to go ahead and keep accepting them in the select clause as a blessed misuse.
I'm not however going to allow them to be dereferenced because no, that's why.
=> sort out some confusion with elements() vs value() + indices() vs index()

.github/workflows/contributor-build.yml
So that we don't use too much resources for builds of older commits that we don't care about anymore.
This is basically the same config as Quarkus.
See
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
for the documentation of this feature.
Essentially, this gives the following behavior:
* For pull requests, only the most recent HEAD gets built. Builds for
  previous HEADs get cancelled automatically.
* For branches (main, ...), we can only ever have two concurrent builds:
  one running, and one (more recent) pending.
  If a build is running and another one gets requested (because of a
  push), the second one will be pending and wait for the first one to
  finish.
  If a third build gets requested before the first one finishes,
  the second build …
=> Limit concurrent Github Actions builds

hibernate-core/src/main/java/org/hibernate/Query.java, hibernate-core/src/main/java/org/hibernate/jpa/spi/ParameterRegistration.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/ParameterParser.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/ParameterRecognizerImpl.java
They're not really positional in JPA, they're just labelled by integers.
Also use "argument" instead of "value", since that's the proper term.
=> get rid of the language "positional parameter"

hibernate-core/src/main/java/org/hibernate/boot/model/relational/SqlStringGenerationContext.java, hibernate-core/src/main/java/org/hibernate/boot/model/relational/internal/SqlStringGenerationContextImpl.java, hibernate-core/src/main/java/org/hibernate/hql/spi/id/AbstractMultiTableBulkIdStrategyImpl.java, hibernate-core/src/test/java/org/hibernate/test/hql/DeleteAllWithTablePerClassAndDefaultSchemaTest.java
https://hibernate.atlassian.net/browse/HHH-15022
It turns out the problem only affects 5.6, not 6.0. So the fix is only present in this PR, not in #4658
=> Backport HHH-15022 to branch 5.6 - Test and fix deleting all entities of a given type in a table-per-class hierarchy with a default schema

hibernate-core/src/test/java/org/hibernate/test/boot/database/qualfiedTableNaming/DefaultCatalogAndSchemaTest.java
https://hibernate.atlassian.net/browse/HHH-15036
> MariaDB < 10.3 doesn’t support sequences, and adapting this test to only use sequences conditionally would be a hassle, so I’d rather not even try.
This should fix test failures on https://ci.hibernate.org/job/hibernate-orm-5.6-mariadb/
I don't think we need to port this to 6.0 as, to the best of my knowledge, we don't even run ORM 6.0 tests against older MariaDB versions.
=> HHH-15036 Disable DefaultCatalogAndSchemaTest when testing against MariaDB < 10.3

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/AbstractSqmRestrictedDmlStatement.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/ManipulationCriteriaTest.java
multiple arguments
Also removed extraneous `applyPredicate(null)` calls.
https://hibernate.atlassian.net/browse/HHH-15037
=> HHH-15037 Criteria Update/Delete with vararg parameters throws NullPointerException

hibernate-core/src/test/java/org/hibernate/orm/test/hql/DeleteAllWithTablePerClassAndDefaultSchemaTest.java
https://hibernate.atlassian.net/browse/HHH-15022
It turns out the problem only affects 5.6, not 6.0, but I figured I would still add a non-regression test in 6.0
=> HHH-15022 Test deleting all entities of a given type in a table-per-class hierarchy with a default schema

hibernate-core/src/main/java/org/hibernate/dialect/DB2zDialect.java
DB2z in Version 12 and beyond supports the "offset"-clause.
Current behavior:
Hibernate uses the "fetch first ..."-clause but does not use "offset" for paging requests.
Expected behavior:
For DB2z Databases in Version 12 and beyond the dialect should use the now supported "offset"-clause
IBM Docs:
https://www.ibm.com/docs/en/db2-for-zos/12?topic=subselect-offset-clause
https://www.ibm.com/docs/en/db2-for-zos/12?topic=subselect-fetch-clause
Test:
Because there is no DB2z Docker-DB testing this comes down to testing against an z/OS DB2 Instance.
I tested it against the DB2z Instance (v12.1.0) at work without any issues.
=> HHH-15042: add offset-clause usage for DB2zDialect

hibernate-core/src/main/java/org/hibernate/dialect/DerbySqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/H2SqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/HSQLSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmExpression.java, hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java, hibernate-core/src/test/java/org/hibernate/orm/test/formulajoin/FormulaJoinTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/CriteriaToBigDecimalTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/ProdTest.java
for `SqmBinaryArithmetic` i think we do not need the following code
```
final SqmExpressable<?> sqmExpressable = QueryHelper.highestPrecedenceType(
expression.getLeftHandOperand().getNodeType(),
expression.getRightHandOperand().getNodeType()
);
```
to determine the correct expression type, when we built it we already resolve the correct type 
```
(SqmExpressable<T>) domainModel.getTypeConfiguration().resolveArithmeticType(
lhsOperand.getNodeType(),
rhsOperand.getNodeType(),
operator
)
```
=> Fix expression type for arithmetic operations

hibernate-core/src/main/java/org/hibernate/annotations/DialectOverride.java, hibernate-core/src/main/java/org/hibernate/cfg/AnnotatedColumn.java, hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java, hibernate-core/src/main/java/org/hibernate/cfg/BinderHelper.java, hibernate-core/src/main/java/org/hibernate/cfg/ColumnsBuilder.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/IdBagBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/formula/FormulaTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/sqldefault/OverriddenDefaultTest.java
Introduces the `@ForDialect` annotation, which is really a perfectly elegant thing if you're careful not to look at its implementation.
This approach has the advantage that it doesn't impact the existing annotations at all: it's completely self-contained.
See https://github.com/hibernate/hibernate-orm/discussions/4528.
=> different approach to overriding SQL in annotations

documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc, hibernate-core/src/main/java/org/hibernate/SessionBuilder.java, hibernate-core/src/main/java/org/hibernate/StatelessSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java, hibernate-core/src/main/java/org/hibernate/engine/spi/AbstractDelegatingSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java, hibernate-core/src/main/java/org/hibernate/internal/SessionCreationOptions.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/util/ReflectHelper.java, hibernate-core/src/main/java/org/hibernate/jpa/spi/JpaCompliance.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureParameterBindingImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingsImpl.java, hibernate-core/src/main/java/org/hibernate/query/spi/QueryParameterBindingValidator.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/internal/util/ReflectHelperTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/QueryParametersValidationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/QueryParametersWithDisabledValidationTest.java
This was apparently a sorta nasty bandaid to a performance problem in query compilation and it caused problems for some users, breaking interpretation of enum values.
=> remove 'hibernate.query.conventional_java_constants' and 'hibernate.query.validate_parameters'

hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2SqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2iDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2iSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2zDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2zSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/DB2iDialectInitTestCase.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/DB2zDialectInitTestCase.java
During DB2zDialect and DB2iDialect initialization the private property “version” might be 
used resulting in an NullpointerException.
For DB2zDialect this is happening when the ColumnType “TIMESTAMP_WITH_TIMEZONE” is being registered in the overriden Method columnType().
For DB2iDialect this is happing because the createUniqueDelegate() Method is override and uses the private property. 
Expected Behavior is the correct initialization of both Dialects without errors.
As a fix I merged the version property of the class DB2Dialect and the private version of DB2zDialect/DB2iDialect.
I added two TestCases which reproduce the issues.
=> HHH-15046/fix db2z i dialect init error

hibernate-core/src/main/java/org/hibernate/mapping/Component.java
This fix prevents an NPE in org.hibernate.mapping.SimpleValue.isValid() and likely elsewhere
=> Fix race condition that allowed Component.getType() to return null

hibernate-core/src/main/java/org/hibernate/cfg/BinderHelper.java, hibernate-core/src/main/java/org/hibernate/cfg/SetBasicValueTypeSecondPass.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/ArrayBinder.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/BagBinder.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/BasicValueBinder.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/IdBagBinder.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/ListBinder.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/MapBinder.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/PropertyBinder.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/SetBinder.java
I can only speculate as to why `BasicValueBinder` had an unused type parameter. I think it should be removed.
=> remove type parameter from BasicValueBinder

hibernate-core/src/main/java/org/hibernate/EmptyInterceptor.java, hibernate-core/src/main/java/org/hibernate/Interceptor.java, hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java, hibernate-core/src/main/java/org/hibernate/classic/Lifecycle.java, hibernate-core/src/main/java/org/hibernate/metamodel/spi/EntityRepresentationStrategy.java
see https://github.com/hibernate/hibernate-orm/pull/4404/commits/9898151ddafa1264de0c83f42747648eb6c9c44e
This change broke the ability to selectively implement methods of `Interceptor`,   and also broke backwards compatibility with older implementations of `Interceptor`.
=> unbreak Interceptor.onSave()

documentation/src/main/asciidoc/userguide/chapters/query/hql/Query.adoc
This is no longer true, according to H6 migration guide, so undocument it.
@sebersole is this right?
=> Streams are no longer closed by terminal operations

documentation/src/test/java/org/hibernate/userguide/persister/CollectionPersister.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/LazyAttributesMetadata.java, hibernate-core/src/main/java/org/hibernate/event/internal/AbstractLockUpgradeEventListener.java, hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java, hibernate-core/src/main/java/org/hibernate/persister/collection/BasicCollectionPersister.java, hibernate-core/src/main/java/org/hibernate/persister/collection/OneToManyPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/UnionSubclassEntityPersister.java, hibernate-core/src/main/java/org/hibernate/tuple/PropertyFactory.java, hibernate-core/src/main/java/org/hibernate/tuple/entity/BytecodeEnhancementMetadataPojoImpl.java, hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/persister/PersisterTest.java
`PersisterCreationContext` was deprecated, but was still being used.
=> get rid of some warnings about use of deprecated APIs

hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/manytomany/ManyToManyListBidirectionalTest.java
https://hibernate.atlassian.net/browse/HHH-15057
Explanation (copied from the ticket):
> See https://hibernate.zulipchat.com/#narrow/stream/132094-hibernate-orm-dev/topic/List.20are.20no.20longer.20bags.20by.20default.3F
> 
> The problem seems to be that we add an order column for both sides of the association, which is not supported (even when using `@OrderColumn` explicitly, even in ORM 5.x).
>
> So the non-owning side of a many-to-many association will have to remain a bag, independently from whatever is configured as the default list semantics.
> 
> From what I’ve seen this will have to be implemented in `org.hibernate.cfg.annotations.CollectionBinder#determineCollectionClassification(java.lang.Class<?>, org.hibernate.annotations.common.reflection.XProperty, …
=> HHH-15057 JdbcSQLException: NULL not allowed for column "BOOKS_ORDER" when inserting into many-to-many list

hibernate-core/src/main/java/org/hibernate/engine/internal/NonNullableTransientDependencies.java
See hibernate-reactive issue [#1077](https://github.com/hibernate/hibernate-reactive/issues/1077) 
non-nullable association requires reactive to determine non-nullable transient dependencies in order to perform the insert.  The non-visible `NonNullableTransientDependencies.add(..)` method is preventing access to using this class.
=> HHH-15067 Set add() method as public to allow non-nullable associations

documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc, documentation/src/test/java/org/hibernate/userguide/hql/HQLTest.java, hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4, hibernate-core/src/main/java/org/hibernate/query/hql/internal/QualifiedJoinPathConsumer.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/StrictJpaComplianceViolation.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/domain/gambit/SimpleEntity.java
This feels more consistent to me, and avoids introducing "new" syntax, instead reusing syntax element we already have.
=> change the new syntax for HQL collection-aggregates

hibernate-core/src/main/java/org/hibernate/boot/jaxb/internal/stax/LocalXmlResourceResolver.java, hibernate-core/src/test/java/org/hibernate/boot/jaxb/internal/stax/LocalXmlResourceResolverTest.java
https://hibernate.atlassian.net/browse/HHH-15094
Turns out the HTTPS part was already implemented in 6, so I just had to add a test for that part. That was not the case in 5.x though, so the backport PR (#4842) includes a bit more code.
This also fixes a few problems I noticed in passing.
=> HHH-15094 Handle http://hibernate.org and https://* for all DTDs in LocalXmlResourceResolver

hibernate-core/src/main/java/org/hibernate/boot/jaxb/internal/stax/LocalXmlResourceResolver.java, hibernate-core/src/test/java/org/hibernate/boot/jaxb/internal/stax/LocalXmlResourceResolverTest.java
https://hibernate.atlassian.net/browse/HHH-15094
Backport of  #4841 to branch 5.6.
=> Backport HHH-15094 to branch 5.6 - Handle http://hibernate.org and https://* for all DTDs in LocalXmlResourceResolver

hibernate-core/hibernate-core.gradle, hibernate-envers/hibernate-envers.gradle, hibernate-testing/hibernate-testing.gradle
A little cleanup of the dependency metadata: let's treat Jandex, Classmate and HCANN as internal dependencies.
=> Jandex, Classmate and commons annotations shouldn't be listed as API

hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
Signed-off-by: Scott Marlow <smarlow@redhat.com>
=> fix typo by removing spaces from hibernate.connection.datasource, hibernate.connection.pool_size, hibernate.connection.isolation

documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc, documentation/src/test/java/org/hibernate/userguide/mapping/basic/DurationMappingLegacyTests.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/model/process/spi/MetadataBuildingProcess.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataBuildingContext.java, hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/BasicValueBinder.java, hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/TimestampdiffFunction.java, hibernate-core/src/main/java/org/hibernate/internal/util/config/ConfigurationHelper.java, hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java, hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/StandardFunctionReturnTypeResolvers.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/type/StandardBasicTypes.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/DurationJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JdbcTypeIndicators.java, hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java, migration-guide.adoc
* Introduce an option to control the storage for `Duration` but default to `INTERVAL_SECOND` (with fallback to `NUMERIC`)
* Fix the resolved return type for `timestampdiff(second)` to match JPA 3.1 expectation for `extract(second)`
* Switch back to storing amount of nanoseconds instead of seconds with fractional parts to retain backwards compatibility
=> Timestampdiff and duration fixes

hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/lock/LockReference.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/lock/LockTest.java
https://hibernate.atlassian.net/browse/HHH-13135
As can be seen from the test runs, most databases implement the semantics that PostgreSQL introduced with `FOR NO KEY UPDATE`. I don't know if it makes sense to introduce new `LockMode` entries, but if so, we need the following:
* `WRITE_KEY` or `WRITE_ALL` which will block inserts for FKs pointing to the locked row
* `READ_KEY` which will prevent row deletions or changes of the PK pointed to through FKs
We could also implement the `FOR NO KEY UPDATE` locking for HANA by using `... for update of col1, col2, ...` i.e. by listing all non-primary key columns. Maybe it's even enough to list just a single non-PK column. Also see https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.06/en-US/20fcf24075191014a89e9dc7b8408b26.html#loio20f …
=> HHH-13135 Use FOR NO KEY UPDATE when locking in PostgreSQL

hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/TimestampdiffFunction.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
Builds on top of https://github.com/hibernate/hibernate-orm/pull/4901
The main change is to allow `timestampdiff` to return an interval as result when a null duration unit is passed to avoid extra SQL for extracting nanoseconds
=> Timestampdiff interval support

tooling/metamodel-generator-jakarta/hibernate-jpamodelgen-jakarta.gradle
* [HHH-15147](https://hibernate.atlassian.net/browse/HHH-15147): hibernate-jpamodelgen-jakarta annotation processor ignores jakarta.* annotations
* [HHH-15146](https://hibernate.atlassian.net/browse/HHH-15146): Run tests against hibernate-jpamodelgen-jakarta
See also https://hibernate.zulipchat.com/#narrow/stream/132096-hibernate-user/topic/Hibernate.20jpamodegen.205.2E6.2E7.2EFinal.20does.20not.20work , https://github.com/spring-projects/spring-boot/issues/30445
=> HHH-15146 + HHH-15147 Fix jpamodelgen-jakarta annotation processor processing javax.* annotations instead of jakarta.* annotations

documentation/documentation.gradle, documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc, documentation/src/main/asciidoc/userguide/chapters/domain/basic_types.adoc, documentation/src/test/java/org/hibernate/userguide/mapping/basic/InetAddressMappingTests.java, documentation/src/test/java/org/hibernate/userguide/mapping/basic/JsonMappingTests.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MimerSQLDialect.java, hibernate-core/src/main/java/org/hibernate/annotations/MapKeyCompositeType.java, hibernate-core/src/main/java/org/hibernate/annotations/MapKeyType.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/model/process/spi/MetadataBuildingProcess.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataBuildingContext.java, hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java, hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java, hibernate-core/src/main/java/org/hibernate/cfg/CollectionPropertyHolder.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/BasicValueBinder.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/MapBinder.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DerbyDialect.java, hibernate-core/src/main/java/org/hibernate/internal/util/config/ConfigurationHelper.java, hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java, hibernate-core/src/main/java/org/hibernate/type/StandardBasicTypes.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/InetAddressJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/InstantJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JdbcTypeIndicators.java, migration-guide.adoc
Rename `MapKeyCustomCompositeType` to `MapKeyCompositeType` and `MapKeyCustomType` to `MapKeyType` i.e. remove the `Custom` part from the name to be consistent with other annotations.
=> Do some renaming for consistency and update documentation for new SQL types

hibernate-core/src/main/antlr/hql-sql.g, hibernate-core/src/main/antlr/hql.g, hibernate-core/src/main/antlr/sql-gen.g, hibernate-core/src/main/java/org/hibernate/hql/internal/ast/SqlASTFactory.java, hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/DotNode.java, hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/FkRefNode.java, hibernate-core/src/test/java/org/hibernate/orm/test/notfound/FkRefTests.java
Issue: https://hibernate.atlassian.net/browse/HHH-15106
Related EAP Issue: https://issues.redhat.com/browse/JBEAP-23147
=> HHH-15106 - fk() HQL function

hibernate-core/src/main/java/org/hibernate/criterion/LikeExpression.java
Locale.ROOT does not correctly lowercase Turkish "I"s.  Using the "tr_TR" locale should lowercase "I" to a dotless "ı".
=> HHH-15196 - Use default locale when lowercasing

gradle/libraries.gradle, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/crosspackage/CrossPackageMappedSuperclassWithEmbeddableTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/crosspackage/base/BaseEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/crosspackage/base/EmbeddableType.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/crosspackage/derived/TestEntity.java
* [HHH-15209](https://hibernate.atlassian.net/browse/HHH-15209): Upgrade to bytebuddy 1.12.9
* [HHH-15141](https://hibernate.atlassian.net/browse/HHH-15141): Bytecode enhancement fails for a protected, embedded field in a MappedSuperclass from a different package than the entity
=> HHH-15141 + HHH-15209 Upgrade to bytebuddy 1.12.9

gradle/libraries.gradle, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/crosspackage/CrossPackageMappedSuperclassWithEmbeddableTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/crosspackage/base/BaseEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/crosspackage/base/EmbeddableType.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/crosspackage/derived/TestEntity.java
* [HHH-15209](https://hibernate.atlassian.net/browse/HHH-15209): Upgrade to bytebuddy 1.12.9
* [HHH-15141](https://hibernate.atlassian.net/browse/HHH-15141): Bytecode enhancement fails for a protected, embedded field in a MappedSuperclass from a different package than the entity
Backport of #4968 to branch 5.6.
=> Backport HHH-15141 + HHH-15209 to branch 5.6 - Upgrade to bytebuddy 1.12.9

hibernate-core/src/main/java/org/hibernate/boot/registry/internal/StandardServiceRegistryImpl.java, hibernate-core/src/main/java/org/hibernate/service/internal/AbstractServiceRegistryImpl.java
https://hibernate.atlassian.net/browse/HHH-15219
This is essentially re-introducing a method which has been "cleaned up" during ORM 6 refactorings. We still need this method to integrate with Quarkus, I'd appreciate simply restoring it as-is.
Clarified the related comments a bit.
=> HHH-15219 Re-introduce the ability to stop and then reactivate a ServiceRegistry

hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
This pull request enhances OracleDialect by supporting 128 bytes for maximum identifier length starting from 12.2 database version.
This new feature is described [here](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/newft/new-features.html#GUID-64283AD6-0939-47B0-856E-5E9255D7246B).
Thanks
Loïc
=> HHH-15210 Increase Oracle Dialect MaxIdentifierLength to 128 for 12.2+

hibernate-core/src/main/java/org/hibernate/query/criteria/internal/compile/CriteriaCompiler.java, hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/ParameterExpressionImpl.java, hibernate-core/src/test/java/org/hibernate/jpa/test/query/CriteriaUpdateWithParametersTest.java, hibernate-core/src/test/java/org/hibernate/jpa/test/query/ReuseCriteriaWithMixedParametersTest.java
https://hibernate.atlassian.net/browse/HHH-15142
=> HHH-15142 Conversion of CriteriaQuery to TypedQuery with Like predicate and escape character fails when repeated.

hibernate-core/src/main/java/org/hibernate/boot/model/relational/SimpleAuxiliaryDatabaseObject.java, hibernate-core/src/main/java/org/hibernate/boot/model/relational/SqlStringGenerationContext.java, hibernate-core/src/main/java/org/hibernate/boot/model/relational/internal/SqlStringGenerationContextImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/database/qualfiedTableNaming/DefaultCatalogAndSchemaTest.java, hibernate-core/src/test/resources/org/hibernate/orm/test/boot/database/qualfiedTableNaming/database-object-using-catalog-placeholder.hbm.xml, hibernate-core/src/test/resources/org/hibernate/orm/test/boot/database/qualfiedTableNaming/database-object-using-schema-placeholder.hbm.xml
https://hibernate.atlassian.net/browse/HHH-15212
cc @NathanQingyangXu 
Backport to branch 5.6: #4990
=> HHH-15212 SchemaExport.execute does not replace the ${schema}-placeholder in HBM database-object with configured schema

hibernate-core/src/main/java/org/hibernate/boot/model/relational/AuxiliaryDatabaseObject.java, hibernate-core/src/main/java/org/hibernate/boot/model/relational/SimpleAuxiliaryDatabaseObject.java, hibernate-core/src/main/java/org/hibernate/boot/model/relational/SqlStringGenerationContext.java, hibernate-core/src/main/java/org/hibernate/boot/model/relational/internal/SqlStringGenerationContextImpl.java, hibernate-core/src/test/java/org/hibernate/test/boot/database/qualfiedTableNaming/DefaultCatalogAndSchemaTest.java, hibernate-core/src/test/resources/org/hibernate/test/boot/database/qualfiedTableNaming/database-object-using-catalog-placeholder.hbm.xml, hibernate-core/src/test/resources/org/hibernate/test/boot/database/qualfiedTableNaming/database-object-using-schema-placeholder.hbm.xml
https://hibernate.atlassian.net/browse/HHH-15212
Backport of #4989 to branch 5.6.
=> Backport HHH-15212 to branch 5.6 - SchemaExport.execute does not replace the ${schema}-placeholder in HBM database-object with configured schema

documentation/src/main/style/asciidoctor/js/toc.js
So I added the missing "previous current" or v5.5 link when v5.6 became the new "current" (see https://github.com/hibernate/hibernate-orm/pull/4370); now we need to do similar thing when v6 became the new "current".
It would be great to keep that in mind when new version got released: the previous "current" needs to be added explicitly in documentation/src/main/style/js/toc.js
Or could we make it automatic so there is zero delay before the "previous version" doc was added?
=> HHH-15239 add 5.6 link in user guide after v6 became the new "current"

hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/VersionResolution.java, hibernate-core/src/test/java/org/hibernate/orm/test/version/UserVersionTest.java
https://hibernate.atlassian.net/browse/HHH-15240
The issue is that `legacyType` is an instance of `CustomType` and its `JdbcType` is an instance of `UserTypeSqlTypeAdapter` while `recommendedJdbcType` is an instcance of `BigIntTypeDescriptor` so the assertion falis.
=> HHH-15240 Defining a UserVersionType causes AssertionError from VersionResolution if running in JVM with -ea flag set

hibernate-core/src/main/java/org/hibernate/type/AbstractStandardBasicType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/converter/AttributeConverterTypeAdapter.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/elementCollection/CollectionEmbeddableElementConversionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/elementCollection/embeddable/EmbeddableTests.java
https://hibernate.atlassian.net/browse/HHH-15211
The root cause is we did not sync up '**equalness**' with '**hash code**' for such edge case (collection of **Embeddable** element to be converted)
=> HHH-15211 Fix Embeddable element collection converter bug

hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/notfound/exception/NotFoundExceptionTest.java
https://hibernate.atlassian.net/browse/HHH-15229
=> HHH-15229 Query returns null for broken foreign key reference and NotFoundAction.EXCEPTION

hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardTableExporter.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/database/qualfiedTableNaming/DefaultCatalogAndSchemaTest.java, hibernate-core/src/test/resources/org/hibernate/orm/test/boot/database/qualfiedTableNaming/implicit-file-level-catalog-and-schema.hbm.xml, hibernate-core/src/test/resources/org/hibernate/orm/test/boot/database/qualfiedTableNaming/no-file-level-catalog-and-schema.hbm.xml, hibernate-core/src/test/resources/org/hibernate/orm/test/boot/database/qualfiedTableNaming/no-file-level-catalog-and-schema.orm.xml
* [HHH-15270](https://hibernate.atlassian.net/browse/HHH-15270): Inconsistent precedence of orm.xml implicit catalog over "default_catalog" in XML-mapped entities
* [HHH-15265](https://hibernate.atlassian.net/browse/HHH-15265): SchemaExport.execute does not add the configured schema to comments
See also backports:
* To 6.0: #5047
* To 5.6: #5048
=> HHH-15265 + HHH-15270 Default catalog/schema fixes

hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardTableExporter.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/database/qualfiedTableNaming/DefaultCatalogAndSchemaTest.java, hibernate-core/src/test/resources/org/hibernate/orm/test/boot/database/qualfiedTableNaming/implicit-file-level-catalog-and-schema.hbm.xml, hibernate-core/src/test/resources/org/hibernate/orm/test/boot/database/qualfiedTableNaming/no-file-level-catalog-and-schema.hbm.xml, hibernate-core/src/test/resources/org/hibernate/orm/test/boot/database/qualfiedTableNaming/no-file-level-catalog-and-schema.orm.xml
* [HHH-15270](https://hibernate.atlassian.net/browse/HHH-15270): Inconsistent precedence of orm.xml implicit catalog over "default_catalog" in XML-mapped entities
* [HHH-15265](https://hibernate.atlassian.net/browse/HHH-15265): SchemaExport.execute does not add the configured schema to comments
Backport of #5046 to branch 6.0.
=> Backport HHH-15265 + HHH-15270 to branch 6.0 - Default catalog/schema fixes

hibernate-core/src/main/java/org/hibernate/cache/spi/QueryKey.java
[…](https://hibernate.atlassian.net/browse/HHH-15267)
=> HHH-15267 Make ParameterBindingsMemento extend Serializable so that cache keys can be serialized

hibernate-core/src/main/java/org/hibernate/Session.java
The newly added method overrides (i.e., https://github.com/hibernate/hibernate-orm/commit/aa08c90b52c4de2c86f33f31b0d5d27b461d1afc) "hide" the JavaDoc from QueryProducer (at least in Eclipse 2022-03). Explicitly add the javadoc here to provide users the @deprecated JavaDoc hint on how to resolve the deprecation warnings in Eclipse.
=> [HHH-15259] Explicitly add JavaDoc to make @deprecated hint visible in Eclipse

hibernate-core/src/main/java/org/hibernate/cfg/OneToOneSecondPass.java, hibernate-core/src/main/java/org/hibernate/mapping/Component.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/embeddedid/OneToOneWithEmbeddedIdTest.java
https://hibernate.atlassian.net/browse/HHH-15153
The root cause is the following code snippet in 
```
boolean referencesDerivedId = false;
try {
referencesDerivedId = otherSide.getIdentifier() instanceof Component
&& ( (Component) otherSide.getIdentifier() ).getProperty( mappedBy ) != null;
}
catch ( MappingException e ) {
// ignore
}
boolean referenceToPrimaryKey  = referencesDerivedId || mappedBy == null;
value.setReferenceToPrimaryKey( referenceToPrimaryKey );
```
We reuse the `Component#getProperty(String)` to test whether `mappedBy` property exists or not; however, when the property cannot be found, the `MappingException` would be caught and then ignored, ending up with `referencesDerivedId ` remaining `false`.
Another noticeable performance optimization trick is if `mappedBy` has …
=> HHH-15153 - @OneToOne does not support @EmbeddedId

local-build-plugins/src/main/java/org/hibernate/orm/docs/PublishTask.java
By adding "/"  at the end of the stagingDirPath only the content of the stagingDirPath is copied,
so on the server it will be created the following dir structure :
```
hibernate /
orm/
${releaseFamily}/
incubating/
integrationguide/
...
userguide/
```
without the dir structure would be :
```
hibernate/
orm/
${releaseFamily}/
documentation/
incubating/
integrationguide/
...
userguide/
```
see 
https://docs.jboss.org/hibernate/orm/6.0/
or 
https://docs.jboss.org/hibernate/orm/5.5/
created by the previous releases
and the wrong
https://docs.jboss.org/hibernate/orm/6.0/documentation/
created during the last release
=> Copy only the content of the documentation staging directory

hibernate-core/src/main/java/org/hibernate/action/internal/AbstractEntityInsertAction.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/AbstractCollectionInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/DelayedCollectionInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/SelectEagerCollectionInitializer.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/orphan/onetomany/EagerOneToManyOrphanWithIdentityIdTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/orphan/onetomany/LazyOneToManyOrphanWithIdentityIdTest.java
https://hibernate.atlassian.net/browse/HHH-15258
The issue is fixed by this https://github.com/hibernate/hibernate-orm/compare/main...dreab8:HHH-15258?expand=1#diff-68e234b1b90c3573e2efd14e73cb756666049314c0f886884a8f0b88dee704f8R118
The `persistentCollection` is added by the persist of the `Parent` that happpens in the same Session of the query.
then I just refactored the common code of the `DelayedCollectionInitializer#resolveInstance` and `SelectEagerCollectionInitializer#resolveInstance` methods into the `AbstractCollectionInitializer`.
=> HHH-15258 Orphan removal for OneToMany relations is broken when used with GenerationType.IDENTITY

hibernate-core/src/main/java/org/hibernate/query/results/complete/CompleteResultBuilderBasicValuedStandard.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/resultmapping/NamedNativeQueryWithCountColumnTest.java
https://hibernate.atlassian.net/browse/HHH-15283
=> HHH-15283 - fix NPE for NamedNativeQuery + SqlResultSetMapping (columns)

hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/boot/archive/scan/spi/AbstractScannerImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/spi/PluralAttributeMapKeySource.java, hibernate-core/src/main/java/org/hibernate/boot/query/HbmResultSetMappingDescriptor.java, hibernate-core/src/main/java/org/hibernate/cfg/AbstractPropertyHolder.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentCollection.java, hibernate-core/src/main/java/org/hibernate/dialect/pagination/SQLServer2005LimitHandler.java, hibernate-core/src/main/java/org/hibernate/dialect/unique/UniqueDelegate.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/JdbcServices.java, hibernate-core/src/main/java/org/hibernate/mapping/Component.java, hibernate-core/src/main/java/org/hibernate/pretty/MessageHelper.java, hibernate-core/src/main/java/org/hibernate/proxy/ProxyFactory.java, hibernate-core/src/main/java/org/hibernate/query/results/complete/CompleteResultBuilderBasicValuedConverted.java, hibernate-core/src/main/java/org/hibernate/query/results/complete/CompleteResultBuilderBasicValuedStandard.java, hibernate-core/src/main/java/org/hibernate/type/OneToOneType.java, hibernate-core/src/main/java/org/hibernate/usertype/CompositeUserType.java
https://hibernate.atlassian.net/browse/HHH-15292
An example overlooking of html char escaping leads to wrong JavaDoc:
The corresponding JavaDoc is:
```
* ResultBuilder for scalar results defined via:<ul>
*     <li>JPA {@link jakarta.persistence.ColumnResult}</li>
*     <li>`<return-scalar/>` as part of a `<resultset/>` stanza in `hbm.xml`</li>
* </ul>
```
After html char (most of time, only '<', '>' and '&' are needed to escape in JavaDoc), the warning number in gradle's javadoc task drops from 100 to 37.
Also fixed some obvious other JavaDoc issues along the way.
=> HHH-15292 escape html chars in JavaDoc

hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
=> HHH-15293 BYTES column type in CockroachDB does not support a length

hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/SqlStatementLogger.java, hibernate-core/src/test/java/org/hibernate/engine/jdbc/spi/SqlStatementLoggerTest.java
Enabling logging of slow queries increases memory usage.
As a result of checking, statement.toString() is called even though the slow query threshold is not exceeded, and it seems to waste resources.
It would be good to change to call toString() only when the slow query threshold is exceeded.
[hibernate-orm/SqlStatementLogger.java at 6.0.2 · hibernate/hibernate-orm](https://github.com/hibernate/hibernate-orm/blob/6.0.2/hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/SqlStatementLogger.java#L144)
Jira Ticket : https://hibernate.atlassian.net/browse/HHH-15300
=> HHH-15300 - Lazy evaluation to statement.toString() when logging a slow query

hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
https://hibernate.atlassian.net/browse/HHH-15324
=> HHH-15324 Hibernate internally use Query#setHint with legacy java.persistence properties causing deprecation log warnings

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
See https://hibernate.atlassian.net/browse/HHH-15325 for more info.
If accepted, a backport to 5.x would be highly appreciated.
Cheers,
Christoph
=> HHH-15325 Avoid allocations from BitSet.stream() in AbstractEntityPersister

hibernate-core/src/main/java/org/hibernate/integrator/spi/Integrator.java, hibernate-testing/README.adoc, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/BootstrapServiceRegistry.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DomainModel.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DomainModelExtension.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DomainModelFunctionalTesting.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/FailureExpected.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/FailureExpectedGroup.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/FunctionalEntityManagerFactoryTesting.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/LoggingInspections.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/MessageKeyInspection.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/RequiresDialect.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/RequiresDialectFeature.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/RequiresDialectFeatureGroup.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/RequiresDialects.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/ServiceRegistry.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/ServiceRegistryExtension.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/ServiceRegistryFunctionalTesting.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/SessionFactory.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/SessionFactoryExtension.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/SessionFactoryFunctionalTesting.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/SkipForDialect.java, hibernate-testing/src/test/java/org/hibernate/testing/annotations/AnotherEntity.java, hibernate-testing/src/test/java/org/hibernate/testing/annotations/methods/DomainModelTesting.java, hibernate-testing/src/test/java/org/hibernate/testing/annotations/methods/ServiceRegistryTesting.java, hibernate-testing/src/test/java/org/hibernate/testing/annotations/methods/SessionFactoryTesting.java, hibernate-testing/src/test/java/org/hibernate/testing/annotations/methods/package-info.java
HHH-15344 - Ability to apply testing annotations at method-level
https://hibernate.atlassian.net/browse/HHH-15344
Ability to apply `@BootstrapServiceRegistry`, `@ServiceRegistry`, `@DomainModel` and `@SessionFactory on methods in addition to classes including natural mixing as well as "hiding"
=> HHH-15344 - Ability to apply testing annotations at method-level

Jenkinsfile
=> Test against JDK 20 (early access)

ci/snapshot-publish.Jenkinsfile
I'm not *completely* sure that's the right command/settings, but from what I gathered from disabled (and probably obsolete...) Jenkins jobs, that should be close. Let's try, worst case the CI run will just fail?
=> Backport snapshot-publish.Jenkinsfile to branch 5.6

documentation/src/main/asciidoc/userguide/chapters/query/hql/Query.adoc
See the link "next chapter" at the beginning of this section:
https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#hql
=> Fix dead link in documentation section "Java API for HQL and JPQL"

settings.gradle
https://hibernate.atlassian.net/browse/HHH-15451
=> HHH-15451 Upgrade PostgreSQL JDBC driver to 42.5.0

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/MetamodelBoundedCacheTest.java
"forward port" from 5.6 branch of #5224 - slightly different as this changed
=> HHH-15100 Limitation of metamodel imports cache causes severe performance drops in large projects

.github/workflows/contributor-build.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> HHH-15468 Set permissions

hibernate-core/src/main/java/org/hibernate/boot/archive/scan/spi/ClassFileArchiveEntryHandler.java
The only change in Jandex 3.0.0 relevant to Hibernate ORM is that
`Indexer.index()` used to return `ClassInfo`, but now returns `void`.
This is a breaking change, but Jandex 3.0.0 has a synthetic bridge
method with the old signature for binary compatibility -- except
it always return `null`. Therefore, with this commit, Hibernate ORM
simply ignores the return value completely, which makes it compatible
with Jandex 3.0.0 at runtime, even though it is still compiled against
Jandex 2.4. The code is also source-compatible with Jandex 3.0.0 if
that is ever needed.
=> HHH-15466 Compatibility with Jandex 3.0.0

hibernate-core/src/main/java/org/hibernate/boot/internal/BootstrapContextImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/annotations/AnnotationMetadataSourceProcessorImpl.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/reflection/JPAXMLOverriddenAnnotationReader.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/reflection/JPAXMLOverriddenMetadataProvider.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/reflection/XMLContext.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/reflection/internal/PropertyMappingElementCollector.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/reflection/JPAXMLOverriddenAnnotationReaderTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/reflection/XMLContextTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/xml/ejb3/Ejb3XmlTestCase.java
https://hibernate.atlassian.net/browse/HHH-15216
This PR moves `JPAXMLOverriddenMetadataProvider` out of package `internal` and makes it non final.
=> HHH-15216 Cannot change MetadataProvider implementation because JPAXMLOverriddenMetadataProvider is final and precisely expected by a cast operator

hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDeleteEventListener.java, hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java, hibernate-core/src/main/java/org/hibernate/persister/collection/CollectionPersister.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/DelayedCollectionFetch.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/DelayedCollectionInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/UnfetchedCollectionAssembler.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/detached/RemoveUninitializedLazyCollectionTest.java
https://hibernate.atlassian.net/browse/HHH-14387
I experimented a lot to reach a condition where the initialization of the collection during deletion could cause issues, but ultimately couldn't come up with anything. Cancelling removes of entities (that refer to uninitialized collection) through cascades also didn't show any issues.
=> HHH-14387 Fix flush issues with bytecode enhanced lazy collections

hibernate-core/src/main/java/org/hibernate/query/spi/DelegatingQueryOptions.java, hibernate-core/src/main/java/org/hibernate/query/spi/QueryOptions.java, hibernate-core/src/main/java/org/hibernate/query/spi/SqlOmittingQueryOptions.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeSelectQueryPlanImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/spi/ListResultsConsumer.java
just an attempt to address the potential perf issue mentioned in the https://github.com/hibernate/hibernate-orm/pull/4924 discussion.
https://hibernate.atlassian.net/browse/HHH-15479
=> Improve ListresultConsumer duplication check method performance

hibernate-core/src/main/java/org/hibernate/boot/SessionFactoryBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/cascade/CascadeDeleteCollectionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/cascade/CascadeDeleteCollectionWithCollectionInDefaultFetchGroupFalseTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/cascade/CascadeOnUninitializedTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/cascade/CascadeOnUninitializedWithCollectionInDefaultFetchGroupFalseTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/DirtyTrackingCollectionInDefaultFetchGroupFalseTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/DirtyTrackingCollectionInDefaultFetchGroupTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/DirtyTrackingPersistTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/LazyCollectionDetachTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/LazyCollectionDetachWithCollectionInDefaultFetchGroupFalseTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/LazyCollectionLoadingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/MultipleBagsInLazyFetchGroupTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/cache/UninitializedAssociationsInCacheTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/BytecodeEnhancedLazyLoadingOnDeletedEntityTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/LazyProxyBytecodeEnhancementCollectionInitializationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/SimpleUpdateTestWithLazyLoading.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/SimpleUpdateWithLazyLoadingWithCollectionInDefaultFetchGroupFalseTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/ondemandload/OnDemandLoadTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/ondemandload/OnDemandLoadWithCollectionInDefaultFetchGroupFalseTest.java
https://hibernate.atlassian.net/browse/HHH-15473
Note the first two commits could be (and IMO, should be) applied to the `main` branch regardless of whether we merge the third commit. See the commit messages for more information.
As to whether getting rid of this specific performance optimization is a good idea:
1. I think we can all agree that performance optimizations should be balanced against usability; at least in this case [Gavin](https://github.com/hibernate/hibernate-orm/pull/3558#issuecomment-695003875) and [Sanne](https://github.com/hibernate/hibernate-orm/pull/3558#issuecomment-701440788) agree.
2. The optimization was not about avoiding database calls, just memory allocations.
3. As far as I know, we don't have numbers telling us whether the optimization was worth it.
4. As …
=> HHH-15473 Instantiate collections in the default fetch group by default

documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/LockOptions.java, hibernate-core/src/main/java/org/hibernate/dialect/AbstractTransactSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DerbyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java, hibernate-core/src/main/java/org/hibernate/sql/ForUpdateFragment.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/StandardFunctionTests.java
Add `pi` to the list of "standard" functions (emulating it using `acos(-1)`).
Add `<code>` blocks to the function list.
UPDATE: also adds `log(base, x)`.
=> HHH-15515/HHH-15516 make pi and log(b,x) portable in HQL

README.adoc
This is the standard badge to point to the Gradle Enterprise instance associated with the Hibernate project so that contributors can easily browse build scans related to the project.
=> HHH-15526 Add Revved up by Gradle Enterprise Badge

hibernate-core/src/main/java/org/hibernate/type/EntityType.java, hibernate-core/src/main/java/org/hibernate/type/OneToOneType.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetoone/EmbeddedIdTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/cache/MainObject.hbm.xml, hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/cache/MainObject.java, hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/cache/Object2.hbm.xml, hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/cache/Object2.java, hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/cache/OneToOneCacheTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/cache/OneToOneConstrainedCacheTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/flush/DirtyFlushTest.java
https://hibernate.atlassian.net/browse/HHH-15045
https://hibernate.atlassian.net/browse/HHH-15235
This PR reverts [HHH-14216](https://hibernate.atlassian.net/browse/HHH-14216), see [discussion](https://github.com/hibernate/hibernate-orm/pull/5061) and [HHH-15540](https://hibernate.atlassian.net/browse/HHH-15540)
=> HHH-15045 + HHH-15235

documentation/src/test/java/org/hibernate/userguide/sql/OracleStoredProcedureTest.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/NativeQueryResultTypeAutoDiscoveryTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/procedure/OracleStoredProcedureTest.java, migration-guide.adoc
This just seems wrong to me. We have no way to say that a `NUMBER(1,0)` column isn't a single-digit number.
I mean, we might just as well say that every `CHAR(1)` column is a boolean, but we don't.
=> HHH-15549 remove mapping of NUMBER(1,0) to BOOLEAN on Oracle

hibernate-core/src/main/java/org/hibernate/annotations/SecondaryRow.java, hibernate-core/src/main/java/org/hibernate/annotations/SecondaryRows.java, hibernate-core/src/main/java/org/hibernate/annotations/SelectBeforeUpdate.java, hibernate-core/src/main/java/org/hibernate/annotations/Table.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java, hibernate-core/src/main/java/org/hibernate/cfg/OneToOneSecondPass.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/mapping/Join.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java, hibernate-core/src/main/java/org/hibernate/resource/jdbc/spi/StatementInspector.java, hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java, hibernate-core/src/test/java/org/hibernate/orm/test/secondarytable/Record.java, hibernate-core/src/test/java/org/hibernate/orm/test/secondarytable/SecondaryRowTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/secondarytable/SpecialRecord.java
Apparently, the code underlying `@Table(fetch=SELECT)` was removed in H6, but the `fetch` member was not deprecated, and some cruft was left lying around.
=> HHH-15564 add @SecondaryRow and HHH-15565 remove zombie code

hibernate-core/src/main/java/org/hibernate/dialect/SpannerDialect.java
https://hibernate.atlassian.net/browse/HHH-15582
throwing the exception causes the `JdbcEnvironmentInitiator` to initialize the `JdbcEnvironmentImpl` without using the JDBC metadata causing an issue to determine the correct `IdentifierCaseStrategy`, this lead to not being able to correctly compare the name coming from the database metadata during the schema update.
=> HHH-15582 SpannerDialect, schema update tries to create existing tables

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SybaseDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/CountFunction.java
The HQL `count()` function has type `Long`, which maps naturally to `count_big()` in TSQL.
=> HHH-15584 use count_big() on Sybase and SQL Server

hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4, hibernate-core/src/main/java/org/hibernate/query/criteria/JpaDerivedFrom.java, hibernate-core/src/main/java/org/hibernate/query/criteria/JpaDerivedJoin.java, hibernate-core/src/main/java/org/hibernate/query/criteria/JpaSelectCriteria.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/QuerySplitter.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmDerivedRoot.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/AbstractSqmSelectQuery.java
This is currently ignored by HQL, is undocumented, and untested, and anyway would be a synonym for `join lateral`.
Also squash some warnings in `SemanticQueryBuilder`.
=> HHH-15613 remove 'lateral' from fromRoot rule

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java
Signed-off-by: Scott Marlow <smarlow@redhat.com>
I happen to be working on understanding https://issues.redhat.com/browse/WFLY-16974 + https://hibernate.atlassian.net/browse/HHH-15514 and this change helps me to see loaded entity as generated proxies.  The same change should be made to upstream also.
=> add DEBUG flag for saving of loaded entity as proxy

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java
Signed-off-by: Scott Marlow <smarlow@redhat.com>
Back port of https://github.com/hibernate/hibernate-orm/pull/5309 for 5.3 branch in case it is ever needed.
=> add DEBUG flag save of loaded entity as proxy

hibernate-core/src/main/java/org/hibernate/cfg/BinderHelper.java, hibernate-core/src/main/java/org/hibernate/mapping/Column.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/basics/BasicsRefColNamesTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/basics/PostalCode.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/basics/Region.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/basics/Town.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/basics/TownCode.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/embedded/EmbeddedRefColNamesTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/embedded/PostalCode.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/embedded/Region.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/embedded/Town.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/embedded/TownCode.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/embeddedid/EmbeddedIdRefColNamesTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/embeddedid/PostalCode.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/embeddedid/Region.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/embeddedid/Town.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/embeddedid/TownCode.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/mixed/MixedRefColNamesTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/mixed/PostalCode.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/mixed/Region.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/mixed/Town.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/mixed/TownCode.java
So this was *really* tricky to get right, but now:
- we handle embeddables forming part of the unique key in the target entity
- error messages are *much* improved (the previous error was incomprehensible)
- the code is *much* more robust and easier to understand
- I have left *copious* comments in the code explaining WFT is going on, because it was previously really difficult to understand
=> HHH-12930 much more flexible handling of associations on non-primary keys

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/InlineDirtyCheckerEqualsHelper.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/InlineDirtyCheckingHandler.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/LazyLoadingByEnhancerSetterTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/NoDirtyCheckingContext.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/basic/LazyBasicFieldAccessTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/basic/LazyBasicPropertyAccessTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/basic/MultiLazyBasicUpdateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/basic/MultiLazyBasicUpdateToNullTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/basic/OnlyLazyBasicUpdateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/basic/OnlyLazyBasicUpdateToNullTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/group/MultiLazyBasicInLazyGroupUpdateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/group/MultiLazyBasicInLazyGroupUpdateToNullTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/group/OnlyLazyBasicInLazyGroupBasicUpdateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/group/OnlyLazyBasicInLazyGroupBasicUpdateToNullTest.java
=> HHH-15634 Lazy basic property does not get updated on change

hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
Since we deprecated `delete()` there's been no blessed way to do this.
=> HHH-15652 add missing Session.remove(entityName, object) method

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DriverManagerConnectionProviderImpl.java
https://hibernate.atlassian.net/browse/HHH-15656
https://hibernate.atlassian.net/browse/HHH-15655
https://issues.redhat.com/browse/WFLY-17196
Add security manager privileged operation for:
> [javatest.batch] Caused by: java.lang.IllegalStateException: java.security.AccessControlException: WFSM000001: Permission check failed (permission "("java.lang.RuntimePermission" "defineClass")" in code source "(vfs:/content/jpa_core_entityManager_vehicles.ear/jpa_core_entityManager_pmservlet_vehicle_web.war/WEB-INF/classes <no signer certificates>)" of "ModuleClassLoader for Module "deployment.jpa_core_entityManager_vehicles.ear.jpa_core_entityManager_pmservlet_vehicle_web.war" from Service Module Loader")
> [javatest.batch]        at net.bytebuddy//net.bytebuddy.dynamic.loading.ClassInjector$UsingLoo …
=> HHH-15655 HHH-15656 ByteBuddyState should use privileged action when defining classes and same for calling ScheduledExecutorService.shutdown

hibernate-core/src/main/java/org/hibernate/action/internal/ComparableEntityAction.java, hibernate-core/src/main/java/org/hibernate/action/internal/EntityAction.java, hibernate-core/src/main/java/org/hibernate/action/internal/EntityUpdateAction.java, hibernate-core/src/main/java/org/hibernate/event/internal/AbstractVisitor.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/EventUtil.java, hibernate-core/src/main/java/org/hibernate/event/internal/WrapVisitor.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdLoadPlan.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcSelectExecutorStandardImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/internal/ResultsHelper.java, hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/DeferredResultSetAccess.java
A list of changes I need to make ORM 6 work with Hibernate Reactive.
I had to add a new interface so that I can create different actions for the insert operations: https://github.com/hibernate/hibernate-orm/commit/d098526e3d78f7f223b76e843d8ae7705526723d and https://github.com/hibernate/hibernate-orm/commit/076006120149b80ce97db435f0ecf8cb9613d32f
That's because in Hibernate Reactive we have an  interface `ReactiveEntityInsertAction` and it wasn't possible to add it to the queue when there was only using `Comparable<EntityAction>` (if somebody has a solution, I'm listening).
All the other changes make it possible for Hibernate Reactive to reuse or overrides some methods.
I've pushed the Hibernate Reactive branch upstream: https://github.com/hibernate/hibernate-reactive/tree/wip/ORM-6
I …
=> HHH-15581 Changes for the integration between Hibernate Reactive and ORM 6

hibernate-core/src/main/java/org/hibernate/SessionFactory.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionFactoryDelegatingImpl.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
- added `getDefinedFetchProfileNames()` for consistency
- added `findEntityGraphByName()` which already existed but was not exposed
- deprecated `getFilterDefinition()` since it's a layer-breaker
- improved+added some Javadoc
See HHH-15678, HHH-15677, and HHH-15676.
=> HHH-15678, HHH-15677, HHH-15676 add two methods to SessionFactory and deprecate one

documentation/src/main/asciidoc/userguide/chapters/query/native/Native.adoc, documentation/src/main/asciidoc/userguide/chapters/schema/Schema.adoc, documentation/src/test/java/org/hibernate/userguide/sql/SQLTest.java
The result transformer-part that is mentioned in the doc has disappeared from the test, rendering it effectively identical to the `sql-hibernate-entity-associations-query-many-to-one-join-example` test just above it, so I suggest removing the duplicate.
=> Correction to the native sql queries section

hibernate-core/src/main/java/org/hibernate/type/descriptor/java/OffsetTimeJavaType.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/AbstractJavaTimeTypeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/OffsetTimeTest.java
The idea is: convert all `OffsetTimes` to the system offset before sending them on.
The justification for that move is that when we _read them back_, we give them the system offset.
@beikov @yrodiere WDYT?
=> HHH-15679 proposed fix to OffsetTime handling

hibernate-core/src/main/java/org/hibernate/SessionEventListener.java, hibernate-core/src/main/java/org/hibernate/resource/jdbc/spi/StatementInspector.java
- relieves the user of having to implement all methods
- also, mark it @Incubating, as was already documented
- improve the jdoc for `SessionEventListener` and `StatementInspector`
=> use default noop methods on SessionEventListener

hibernate-core/src/main/java/org/hibernate/internal/util/ReflectHelper.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/RegistryHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/TypeVariableTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/WildcardsTest.java
- https://hibernate.atlassian.net/browse/HHH-15624 java.lang.ClassCastException: class sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to class java.lang.reflect.ParameterizedType when using generics and Wildcard
- https://hibernate.atlassian.net/browse/HHH-15646 Using a generic DTO i get a ClassCastException: class sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to class java.lang.reflect.ParameterizedType
=> HHH-15624 & HHH-15646 Generics 

documentation/src/test/java/org/hibernate/userguide/pc/FilterSqlFragementAliasTest.java, hibernate-core/src/main/java/org/hibernate/Filter.java, hibernate-core/src/main/java/org/hibernate/Length.java, hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/SessionFactory.java, hibernate-core/src/main/java/org/hibernate/StatelessSession.java, hibernate-core/src/main/java/org/hibernate/annotations/AnyDiscriminator.java, hibernate-core/src/main/java/org/hibernate/annotations/Check.java, hibernate-core/src/main/java/org/hibernate/annotations/ColumnDefault.java, hibernate-core/src/main/java/org/hibernate/annotations/DialectOverride.java, hibernate-core/src/main/java/org/hibernate/annotations/DiscriminatorFormula.java, hibernate-core/src/main/java/org/hibernate/annotations/DiscriminatorOptions.java, hibernate-core/src/main/java/org/hibernate/annotations/Filter.java, hibernate-core/src/main/java/org/hibernate/annotations/FilterDef.java, hibernate-core/src/main/java/org/hibernate/annotations/FilterJoinTable.java, hibernate-core/src/main/java/org/hibernate/annotations/Formula.java, hibernate-core/src/main/java/org/hibernate/annotations/GeneratedColumn.java, hibernate-core/src/main/java/org/hibernate/annotations/GenerationTime.java, hibernate-core/src/main/java/org/hibernate/annotations/IdGeneratorType.java, hibernate-core/src/main/java/org/hibernate/annotations/JoinFormula.java, hibernate-core/src/main/java/org/hibernate/annotations/OrderBy.java, hibernate-core/src/main/java/org/hibernate/annotations/ParamDef.java, hibernate-core/src/main/java/org/hibernate/annotations/SqlFragmentAlias.java, hibernate-core/src/main/java/org/hibernate/annotations/TenantId.java, hibernate-core/src/main/java/org/hibernate/annotations/TimeZoneColumn.java, hibernate-core/src/main/java/org/hibernate/annotations/TimeZoneStorage.java, hibernate-core/src/main/java/org/hibernate/annotations/TimeZoneStorageType.java, hibernate-core/src/main/java/org/hibernate/annotations/UuidGenerator.java, hibernate-core/src/main/java/org/hibernate/annotations/Where.java, hibernate-core/src/main/java/org/hibernate/relational/SchemaManager.java
Also:
- deprecate a layer-breaking method of `org.hibernate.Filter` (consistent with what we already did on `SessionFactory`)
- fix the incorrect `@Target` of `@SqlFragmentAlias`
- add some missing `@since` annotations
=> improve javadoc for annotations related to filters + discriminators

docker_db.sh, hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchOptimisticLockingTest.java
This PR fixes the test failure for BatchOptimisticLockingTest.testBatchAndOptimisticLocking.
It also improves the CockroachDB v22.1 configuration which (hopefully) fixes the cascade of build failures we see from build #34 onwards (see e.g. https://ci.hibernate.org/job/hibernate-orm-nightly/job/main/34/)
=> HHH-15668 Fix CockroachDB test failure

hibernate-core/src/main/java/org/hibernate/engine/internal/CacheHelper.java
Unfortunately this didn't have a JIRA to track, I think it's ok as it's a very minor change - but it does have performance implications so it would be best to backport.
=> Cache helper backports from main

hibernate-core/src/test/java/org/hibernate/orm/test/version/sybase/SybaseTimestampVersioningTest.java
Folks, so this test was failing because apparently the version of `User` no longer gets incremented when its owned collection changes. I feel like that's supposed to happen, but perhaps it's not.
Note that this has nothing to do with my work: removing `source="db"` does not make the test pass.
Possibly it's to do with @sebersole's work but that's just speculation. Need to see if it was passing earlier.
This PR simply squashes the failure, but we need to investigate it first.
=> fix a flaky Sybase test

hibernate-core/src/main/java/org/hibernate/boot/internal/NamedNativeQueryDefinitionImpl.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NamedNativeQueryMementoImpl.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sql/spi/NamedNativeQueryMemento.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/RegisterNamedQueryWithParameterTest.java
https://hibernate.atlassian.net/browse/HHH-15653
The issue is that the sql string of the memento used by `addNamedQuery` has been adjusted, so instead of the named parameter it contains the `?` , this causes the creation of a ordinal instead of using the registered name parameter.
=> HHH-15653 Named Native Query cannot be registered/used with named parameters

gradle/databases.gradle, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
This PR allows the `OracleDialect` to know if the targeted database is an Autonomous Database cloud service. As Autonomous Databases come with all features (OSON support _even in 19c_, Autonomous/Automatic features, Exadata features, Core database features...) this can avoid limiting the feature set available for Hibernate.
It also provides new `oracle_cloud_autonomous_tls` database settings to easily connect to an [Autonomous Database using TLS connection](https://docs.oracle.com/en/cloud/paas/autonomous-database/adbsa/support-tls-mtls-authentication.html#GUID-4C2093B7-4DF0-4CF4-BB2D-33E1FC5D5184) (no requirement regarding separate wallet management).
Remark: to make 100% of the hibernate-spatial tests pass, the Autonomous Database being used must have the in-database JVM enabled (see …
=> HHH-15758 HHH-15755 Add Oracle Autonomous Database awareness to OracleDialect

hibernate-core/src/main/java/org/hibernate/Session.java
Explicitly add the JavaDoc to Session.java to provide users the @deprecated JavaDoc hint on how to resolve the deprecation warnings.
Without this patch, e.g., in Eclipse, there are no warning generated when the method createSQLQuery is used which makes upgrading to 6.x harder (cf. #5032).
=> HHH-15792: Explicitly add JavaDoc to make @deprecated hint for createSQLQuery visible in Eclipse

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacySqlAstTranslator.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacySqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/CockroachSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLSqlAstTranslator.java
[HHH-15736](https://hibernate.atlassian.net/browse/HHH-15736) - Solve errors in CockroachDB and MySQL 5.7 highlighted by new tests introduced in the previous PR https://github.com/hibernate/hibernate-orm/pull/5746.
=> HHH-15736 Make sure dialects have default like-predicate escape char configured

hibernate-core/src/main/java/org/hibernate/persister/collection/BasicCollectionPersister.java
A minor change for allowing Hibernate Reactive to reuse the method
=> HHH-15904 Change scope of BasicCollectionPersister#buildRowMutationOperations

hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaWindowFunctionTest.java
Skip tests with unsupported window functions on DB2 10.5.
=> HHH-15654 Fix failing window function tests on DB2 10.5

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/hhh15842/EnumForeignKeyParameterMappingTest.java
In [HHH-15842](https://hibernate.atlassian.net/browse/HHH-15842), selecting and persisting entities which have a many-to-one relationship to another entity whose primary key is an enum fails because the foreign key values are not converted to the appropriate JDBC type, thus at some point parameter binding fails with a ClassCastException or an AssertionError in JdbcParameterBindingImpl:20.
This commit modifies SimpleForeignKeyDescriptor so that disassemble, forEachDisassembledJdbcValue, breakDownJdbcValues and forEachJdbcValue will attempt to convert the value to a relational one using the appropriate JdbcMapping
=>  HHH-15842 Convert simple foreign key values before binding

documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CUBRIDDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2LegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DerbyLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/HSQLLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/IngresDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/RDMSOS2200Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DerbyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SybaseDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java, hibernate-core/src/main/java/org/hibernate/query/sqm/function/MultipatternSqmFunctionDescriptor.java, hibernate-core/src/main/java/org/hibernate/query/sqm/function/SqmFunctionRegistry.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
Still non-"standard" because tricky to implement on Sybase and Derby.
=> HHH-15919 make trunc() / truncate() portable in HQL

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/hhh15842/EnumForeignKeyParameterMappingTest.java
Same as [#5802](https://github.com/hibernate/hibernate-orm/pull/5802). Disassemble method adapted to work with 6.1 JdbcMapping
=> HHH-15842 Convert simple foreign key values before binding (6.1)

hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java, hibernate-core/src/test/java/org/hibernate/test/procedure/StoredProcedureParameterTypeTest.java
Fix https://github.com/spring-projects/spring-data-jpa/issues/2544
=> HHH-15618 Accept TypedParameterValue for procedure

hibernate-core/src/main/java/org/hibernate/annotations/RowId.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EntityRowIdMappingImpl.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/RowIdJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/SmallIntJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/internal/JdbcTypeBaseline.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/package-info.java, hibernate-core/src/test/java/org/hibernate/orm/test/rowid/RowIdTest.java, hibernate-testing/src/main/java/org/hibernate/testing/DialectChecks.java
- the rowid pseudo-column and type are now determined automatically from Dialect
- works (after all these years) in Postgres (and also on h2)
- introduce RowIdJdbcType (not strictly necessary, but a nicety)
=> HHH-15958 much better impl of @RowId annotation

databases/oracle/matrix.gradle, docker_db.sh, documentation/src/test/java/org/hibernate/userguide/events/InterceptorTest.java, gradle/databases.gradle, hibernate-core/src/test/java/org/hibernate/orm/test/type/AbstractJavaTimeTypeTest.java, hibernate-hikaricp/src/test/resources/hibernate.properties, hibernate-testing/src/main/java/org/hibernate/testing/jdbc/SharedDriverManagerConnectionProviderImpl.java, settings.gradle
This PR brings some optimizations to reduce CI build duration when targeting Oracle database:
- Docker XE image setup: datafiles and tablespaces configuration, initialization parameters
- Update of the Oracle JDBC driver (21.8 instead of 21.3)
- Better management of JDBC connection pool in `SharedDriverManagerConnectionProviderImpl` (minimum size and removing `reset()` invocations in `AbstractJavaTimeTypeTest`)
- HikariCP timeout configuration
=> HHH-15961 Speed-up Oracle CI build

hibernate-core/src/main/java/org/hibernate/tool/schema/spi/SchemaManagementTool.java
https://hibernate.atlassian.net/browse/HHH-15962
- make both `getSchemaTruncator/buildGenerationTargets` as default methods throwing `UnsupportedOperationException`
Also, a quick question on `buildGenerationTargets(..)` - do we want to expose it in the interface since the `SchemaCreatorImpl`/`SchemaDropperImpl`/`SchemaTruncatorImpl` that are using it all require the `HibernateSchemaManagementTool` internal implementation rather than the SPI interface?
=> HHH-15962 Provide simple default impl for new members of `SchemaManagementTool` interface

ci/build.sh, docker_db.sh, gradle/databases.gradle
This PR fixes nightly 11g build:
- by forcing the oracle_legacy_ci profile hence targeting XE database service name (instead of xepdb1 when using oracle_ci profile)
- it also optimizes this build by disabling the recycle bin and increasing the session_cached_cursors parameter (from 50 to 500)
=> HHH-15971 Fix Oracle CI build for 11g version

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/EagerOneToOneMappedByInDoubleEmbeddedTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/LazyOneToOneMappedByInDoubleEmbeddedTest.java
https://hibernate.atlassian.net/browse/HHH-15967
Needed for ease of testing in Hibernate Search in particular, but I'm sure this will help people using ORM 6.1 too.
[HHH-15967]: https://hibernate.atlassian.net/browse/HHH-15967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Backport HHH-15967 to branch 6.1 - @OneToOne(mappedBy = ..., fetch = LAZY) in embedded referencing an association within another embedded 

hibernate-envers/src/test/java/org/hibernate/orm/test/envers/AbstractOneSessionTest.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/entities/converter/BasicModelingTest.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/strategy/AuditStraegySelectorTest.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integrator/BasicIntegratorTest.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/various/ExportIdentifierTest.java
This PR fixes some hibernate-envers tests so that they rely on `SharedDriverManagerConnectionProviderImpl` instead of the default `DriverManagerConnectionProviderImpl` Connection Provider.
Tests modified:
- BasicModelingTest
- ReadEntityWhitEntityNameTest
- ReadEntityWithAuditedCollectionTest
- ReadEntityAssociatedAuditedTest
- ReadEntityAssociatedNotAuditedTest
- ReadEntityWithAuditedManyToManyTest
- ReadEntityWithAuditedCollectionTest
- SingleDomainObjectToMultipleTablesTest
- HasChangedAuditedManyToManyTest
- AuditStraegySelectorTest
- ExportIdentifierTest
- BasicIntegratorTest
=> HHH-15973 hibernate-envers tests must rely on SharedDriverManagerConnectionProviderImpl

documentation/src/test/java/org/hibernate/userguide/naming/AcmeCorpPhysicalNamingStrategyTest.java, documentation/src/test/java/org/hibernate/userguide/transactions/TransactionsTest.java
This PR fixes some documentation tests so that they rely on SharedDriverManagerConnectionProviderImpl instead of the default DriverManagerConnectionProviderImpl Connection Provider.
Tests modified:
- AcmeCorpPhysicalNamingStrategyTest
- TransactionsTest
=> HHH-15975 documentation tests must rely on SharedDriverManagerConnectionProviderImpl

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/onetoone/BidirectionalOneToOneWithConverterEagerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/onetoone/BidirectionalOneToOneWithConverterLazyTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/bidirectional/BidirectionalOneToOneEagerFKTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/bidirectional/BidirectionalOneToOneLazyFKTest.java
Refactor tests as suggested by https://github.com/hibernate/hibernate-orm/pull/5921#discussion_r1064505664.
Also, only set `bidirectionalAttributeName` when needed and rollback the check for bidirectional associations that was wrongly using the table expression.
=> HHH-15982 Refactor tests to use StatementInspector and correct bidirectionalAttributeName handling

hibernate-core/src/main/java/org/hibernate/SharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
This makes these operations available on `StatelessSession` instead of just on `Session`.
See https://twitter.com/omidboot/status/1612019552904253441
@sebersole what do you think of this proposal?
=> promote joinTransaction() and isJoinedToTransaction() to SharedSessionContract

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2iLegacySqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2iSqlAstTranslator.java
https://hibernate.atlassian.net/browse/HHH-15890
The issue was already solved for `DB2400Dialect` (deprecated) which uses `DB2SqlAstTranslator` but not for `DB2iDialect` / `DB2iSqlAstTranslator`.
=> HHH-15890 Fix shouldEmulateFetchClause method for DB2(i)SqlAstTranslator

hibernate-core/src/main/java/org/hibernate/action/internal/AbstractEntityInsertAction.java, hibernate-core/src/main/java/org/hibernate/action/internal/EntityDeleteAction.java, hibernate-core/src/main/java/org/hibernate/action/internal/EntityUpdateAction.java, hibernate-core/src/main/java/org/hibernate/cache/internal/NaturalIdCacheKey.java, hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java, hibernate-core/src/main/java/org/hibernate/engine/internal/ImmutableEntityEntry.java, hibernate-core/src/main/java/org/hibernate/engine/internal/MutableEntityEntry.java, hibernate-core/src/main/java/org/hibernate/engine/internal/NaturalIdResolutionsImpl.java, hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/spi/EntityEntry.java, hibernate-core/src/main/java/org/hibernate/engine/spi/NaturalIdResolutions.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultEvictEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractNaturalIdLoader.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoaderStandard.java, hibernate-core/src/main/java/org/hibernate/loader/internal/NaturalIdLoadAccessImpl.java, hibernate-core/src/main/java/org/hibernate/loader/internal/SimpleNaturalIdLoadAccessImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/NaturalIdMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/CompoundNaturalIdMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleNaturalIdMapping.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java, hibernate-core/src/test/java/org/hibernate/orm/test/caching/mocked/NaturalIdCacheKeyTest.java
These bugs are visible just by inspection of the code.
- fix place where id and entity had always been passed in reversed order
- fix place where whole state array was passes instead of natural id array
- change the API of NaturalIdResolutions because it never needs the session, and the fix involved calling it from a place we did not have one
- and also clean up a bunch of warnings
=> HHH-16010 fix two bugs in natural id handling 

hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/function/SelfRenderingFunctionSqlAstExpression.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
This was another bug that resulted from the unnecessary use of the untypesafe `getChild()` method in `SemanticQueryBuilder`.
It's really important that we migrate away from that, who knows how many other bugs are lurking?
=> fix queries like 'select ... where ...' with no 'from' clause

hibernate-core/src/main/java/org/hibernate/SessionBuilder.java, hibernate-core/src/main/java/org/hibernate/SessionFactory.java, hibernate-core/src/main/java/org/hibernate/StatelessSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
- the TP of `StatelessSessionBuilder` was missed when `SessionBuilder` was done
- `SessionFactory.getOptions()` is a layer-breaker, returning an SPI interface
=> remove type parameter from StatelessSessionBuilder + deprecate an operation of SessionFactory

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MariaDBLegacySqlAstTranslator.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacySqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/MariaDBSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLSqlAstTranslator.java
Fix CI errors on [MySQL 5.7](https://ci.hibernate.org/job/hibernate-orm-nightly/job/main/86/testReport/junit/org.hibernate.orm.test.query.hql/FunctionTests/Build___mysql_5_7___Test___testIn_SessionFactoryScope_/) and [MariaDB 10.3](https://ci.hibernate.org/job/hibernate-orm-nightly/job/main/86/testReport/junit/org.hibernate.orm.test.query.hql/FunctionTests/Build___mariadb_10_3___Test___testIn_SessionFactoryScope_/).
=> Fix select without from in old versions of MySQL and MariaDB

Jenkinsfile
JDK 18 EOL'd on 2022-09-20
See https://endoflife.date/java
=> Test against JDK 21 EA, stop testing against JDK 18 

hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteInsertHandler.java
And the relax scope of a private method.
This way Hibernate Reactive can access them.
Additional commit for https://hibernate.atlassian.net/browse/HHH-16059
=> HHH-16059 Add getters to CteInsertHandler

hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java, hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
It's actually a JPA hint, and rightfully belongs on `HibernateHints`.
cc @Sanne
=> deprecate config property org.hibernate.flushMode on AvailableSettings

hibernate-core/src/main/java/org/hibernate/bytecode/internal/BytecodeProviderInitiator.java, hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java, hibernate-core/src/main/java/org/hibernate/cfg/Environment.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/enhance/EnhancingClassTransformerImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableRepresentationStrategyPojo.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/EntityRepresentationStrategyPojoStandard.java, hibernate-core/src/main/java/org/hibernate/proxy/AbstractLazyInitializer.java, hibernate-core/src/main/java/org/hibernate/proxy/AbstractSerializableProxy.java, hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/SerializableProxy.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/ReflectionOptimizerTest.java, hibernate-testing/src/main/java/org/hibernate/testing/bytecode/enhancement/BytecodeEnhancerRunner.java, tooling/hibernate-ant/src/main/java/org/hibernate/tool/enhance/EnhancementTask.java, tooling/hibernate-enhance-maven-plugin/src/main/java/org/hibernate/orm/tooling/maven/MavenEnhancePlugin.java, tooling/hibernate-gradle-plugin/src/main/java/org/hibernate/orm/tooling/gradle/enhance/EnhancementHelper.java
https://hibernate.atlassian.net/browse/HHH-16058
cc/ @sebersole and @DavideD for awareness
=> HHH-16058 Removing Environment#getBytecodeProvider

hibernate-core/src/main/java/org/hibernate/cache/internal/NoCachingTransactionSynchronizationImpl.java, hibernate-core/src/main/java/org/hibernate/cache/spi/AbstractCacheTransactionSynchronization.java, hibernate-core/src/main/java/org/hibernate/cache/spi/CacheTransactionSynchronization.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
- https://hibernate.atlassian.net/browse/HHH-16072
Not ideal to restore this, but it's otherwise impossible to run integration tests on WildFly.
=> HHH-16072 Restore SPI removal SharedSessionContractImplementor.getTransactionStartTimestamp()

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderBatchKey.java, hibernate-core/src/test/java/org/hibernate/orm/test/batchfetch/NestedLazyManyToOneTest.java, hibernate-testing/src/main/java/org/hibernate/testing/jdbc/SQLStatementInspector.java
https://hibernate.atlassian.net/browse/HHH-16043
=> HHH-16043 Hibernate 6.x breaks collection batch fetching

hibernate-core/src/test/java/org/hibernate/orm/test/type/VarbinaryArrayTest.java, migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-16085
Backport of #6004 to 6.1, with an additional commit to update the migration guide.
=> Backport HHH-16085 to branch 6.1 - Test and document using @JdbcTypeCode(Types.VARBINARY) on arrays to revert to pre-6.1 behavior

hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/TypeDefinition.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotationBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/BasicValueBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/DelayedParameterizedTypeBean.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingMetadataBuildingOptions.java, hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataBuildingOptions.java, hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java, hibernate-core/src/main/java/org/hibernate/id/factory/internal/StandardIdentifierGeneratorFactory.java, hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java, hibernate-core/src/main/java/org/hibernate/mapping/MappingHelper.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/ManagedTypeRepresentationResolverStandard.java, hibernate-core/src/main/java/org/hibernate/resource/beans/internal/Helper.java, hibernate-core/src/main/java/org/hibernate/type/ComponentType.java, hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java, hibernate-core/src/test/java/org/hibernate/orm/test/cdi/type/CdiSmokeTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/cdi/type/ExtendedBeanManagerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/cdi/type/OtherBean.java, hibernate-core/src/test/java/org/hibernate/orm/test/cdi/type/SimpleTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/cdi/type/UrlType.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/UserDefinedGeneratorsTests.java, hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/ComponentMetadataGenerator.java, hibernate-envers/src/main/java/org/hibernate/envers/internal/revisioninfo/DefaultRevisionInfoGenerator.java, migration-guide.adoc
This is a fourth option for dealing with "deferred" CDI access.
In this one we only look for converters and listeners in CDI by default.  To enable resolving Hibernate extensions in CDI, a setting (`hibernate.cdi.extensions`, false by default) has been introduced
=> HHH-16069 - Skip CDI for Hibernate extensions by default

hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/AttributeAnalysis.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
Additional logging cleanups related to
- https://hibernate.atlassian.net/browse/HHH-16099
=> HHH-16099 Introduce three-state handling for dirty levels to avoid excessive warnings

hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/JpaCompliantLifecycleStrategy.java, hibernate-core/src/test/java/org/hibernate/orm/test/cdi/lifecycle/ExtendedBeanManagerNotAvailableDuringCustomUserTypeInitTest.java
Add a null check for BeanManager in org.hibernate.resource.beans.container.internal.JpaCompliantLifecycleStrategy.NamedBeanImpl.initialize and use fallback producer if null.
[HHH-16096](https://hibernate.atlassian.net/browse/HHH-16096)
[HHH-16096]: https://hibernate.atlassian.net/browse/HHH-16096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HHH-16096 Passing an ExtendedBeanManager which is notified too late leads to initialization error

hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesSourceProcessingStateStandardImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/spi/ListResultsConsumer.java, hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchPostLoadTest.java
https://hibernate.atlassian.net/browse/HHH-16106
=> HHH-16106 Using BatchEntitySelectFetchInitializer causes PostLoad to be called before references are initialized

hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/jakarta/JakartaSchemaToolingTests.java
https://hibernate.atlassian.net/browse/HHH-16150
cc @beikov , that's the problem I mentioned to you during our last video chat.
=> HHH-16150 Hibernate ORM no longer drops the schema when using the create-drop strategy and a session factory observer throws an exception on startup

hibernate-core/src/main/java/org/hibernate/boot/beanvalidation/TypeSafeActivator.java
Failure to automatically integrate with Bean Validation is excessively noisy
https://hibernate.atlassian.net/browse/HHH-16194
=> HHH-16194 Failure to automatically integrate with Bean Validation is excessively noisy

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/GeneratedValuesProcessor.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
This change would need to be backported to `6.2` in order for us to proceed with the HR [work](https://github.com/hibernate/hibernate-reactive/pull/1462)
=> Apply changes needed for support of @ValueGenerationType in Hibernate Reactive

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
An incorrect error log message is given about @Immutable is declared to non-root entities that are not @Immutable declared.
@Immutable can only be declared on the Root Entity.
That is, it is not wrong to say that a non-root entity is mutable, so should not send the message `@Immutable used on a non root entity` to non-root entity that are not declared with @Immutable.
This should only happen for non-root entities that are immutable.
https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues/HHH-16233
=> HHH-16233 Fix logs for mutable non-root entity

hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/AbstractCollectionInitializer.java
The previous version of the code lead to misleading log statements being printed when debug logging
was enabled for 'org.hibernate.orm.results.loading.collection'
=> Fix logging in AbstractCollectionInitializer

hibernate-core/src/main/java/org/hibernate/mapping/Component.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractEmbeddableMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddableMappingTypeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/IdClassEmbeddable.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/VirtualIdEmbeddable.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetomany/orderby/Department.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetomany/orderby/DepartmentId.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetomany/orderby/ECompany.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetomany/orderby/IdClassAndOrderByTest.java
https://hibernate.atlassian.net/browse/HHH-16009
the fix is https://github.com/hibernate/hibernate-orm/commit/da4d87ab7236c09e646fbc4f2bfe3003d97d4da5
when the order by refers to a property of an `IdClass` and the `finishInitialization` method of the `PluralAttribute` is executed before the one of the `EmbeddableMappingType` then when hibernate tries to resolve the path of the order by the `EmbeddableMappingType #findAttributeMapping(String name)` returns null (its attributes have not yet been initialized) and a `ColumnReference` is created assuming that the name of the column is equal to the name of the property, but this does not work when a physical naming strategy is provided.
=> HHH-16009 jakarta @OrderBy annotation generates a non-transformed column name in the SQL query for a composite key's field

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
change a couple methods to protected to allow reactive implementations of natural ID loader logic
=> method access changes for reactive overrides in AbstractEntityPersister

hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/internal/MutationExecutorPostInsert.java
This is useful for implementing the [reactive version](https://github.com/hibernate/hibernate-reactive/pull/1481) of the class
=> Allow access to fields of MutationExecutorPostInsert

hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultPersistEventListener.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java, hibernate-core/src/test/java/org/hibernate/orm/test/cache/CircularityTest.java
https://hibernate.atlassian.net/browse/HHH-16197
=> HHH-16197 Circular references of the same entity result in different Java objects when caching is enabled and using a query

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/main/java/org/hibernate/spi/NavigablePath.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/EmbeddableWithIdenticallyNamedAssociationTest.java
https://hibernate.atlassian.net/browse/HHH-16209
=> HHH-16209 Identically-named association in entity root and embeddable leads to mixup during association loading

migration-guide.adoc
Quoting: "5.x used the type code `Types.BIGINT`".
So, in order to retain backwards-compatibility, one needs to set the JDBC type to `BIGINT`, not to `NUMERIC`.
Tested locally on a schema created with 5.x by starting an application using 6.x: with `NUMERIC`, schema validation fails; with `BIGINT` it does not.
=> Fix recommendation in migration guide for duration mapping backwards-compatibility

hibernate-core/src/main/java/org/hibernate/cache/internal/BasicCacheKeyImplementation.java
https://hibernate.atlassian.net/browse/HHH-16172
Original HHH-16172 fix neglected to make this class public so that it can be instantiated outside the org.hibernate.cache.internal package.
=> [6.2] HHH-16172 BasicCacheKeyImplementation must be public to support externalization.

hibernate-core/src/main/java/org/hibernate/cache/internal/BasicCacheKeyImplementation.java
https://hibernate.atlassian.net/browse/HHH-16172
Original HHH-16172 fix neglected to make this class public so that it can be instantiated outside the org.hibernate.cache.internal package.
=> HHH-16172 BasicCacheKeyImplementation must be public to support externalization.

documentation/src/main/asciidoc/userguide/chapters/query/spatial/Spatial.adoc
the new Maven group is org.hibernate.orm (and so referenced in Spring Boot 3)
=> update maven dependency of hibernate-spatial

documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc, hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/ConnectionProviderInitiator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/ExtractedDatabaseMetaDataImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcServicesImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/multitenancy/schema/AbstractSchemaBasedMultiTenancyTest.java
https://hibernate.atlassian.net/browse/HHH-16310
We probably also need an entry about `hibernate.multiTenancy` being removed in the 6.0 migration guide. I'll send another PR for that.
=> HHH-16310 Fix regressions in documentation and support for MultiTenantConnectionProvider

documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc, hibernate-core/src/main/java/org/hibernate/TimeZoneStorageStrategy.java, hibernate-core/src/main/java/org/hibernate/annotations/TimeZoneStorageType.java, hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
https://hibernate.atlassian.net/browse/HHH-16302
Backport to 6.2: #6253
=> HHH-16302 Document that TimeZoneStorageType.NORMALIZE normalizes to the JVM timezone, not to `hibernate.jdbc.time_zone`, upon reading values

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/BasicValuedPathInterpretation.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EmbeddableValuedPathInterpretation.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ql/MapIssueTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/orderby/EmbeddedIdOrderByAndAggregateFunctionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/orderby/OrderByAndAggregateFunctionTest.java
https://hibernate.atlassian.net/browse/HHH-16189
=> HHH-16189 wrong order by and group by generated

hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/OneToOneSecondPass.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mappedBy/ManyToManyMappedByTypeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mappedBy/OneToManyMappedByTypeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mappedBy/OneToOneMappedByTypeTest.java
https://hibernate.atlassian.net/browse/HHH-16336
Modify the `mappedBy` type checks to be more lenient in case of subtypes or entity types which map to the same table.
=> HHH-16336 Throw an appropriate error when a mappedBy property references the wrong entity type

hibernate-core/src/main/java/org/hibernate/jdbc/Expectation.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/DeleteCoordinator.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/InsertCoordinator.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java, hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchSizeAndStatelessSessionTest.java
Disable batching when no transaction is used in a stateless session
=> HHH-16249 - Add test

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
https://hibernate.atlassian.net/browse/HHH-16380
=> HHH-16380 Avoid map-based mapping metamodel access when instantiating entity instances

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
Backport of https://github.com/hibernate/hibernate-orm/pull/6299.
=> HHH-16380 Avoid map-based mapping metamodel access when instantiating entity instances 

hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
Fix [HHH-16399](https://hibernate.atlassian.net/browse/HHH-16399)
This is for Hibernate Reactive.
Hibernate ORM recognizes the error because, when it comes from the JDBC driver,
it's an instance of `java.sql.SQLIntegrityConstraintViolationException`.
[HHH-16399]: https://hibernate.atlassian.net/browse/HHH-16399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Recognize ConstraintViolationException from error code in Sql Server

hibernate-core/src/test/java/org/hibernate/orm/test/association/GenericAssociationTest.java
This doesn't fail, showing HHH-16378 is a regression.
See also #6296.
=> Backport of reproducer for HHH-16378 SQM fails to resolve target type of association defined in mappersuperclass with generics

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/HibernateMethodLookupDispatcher.java
https://hibernate.atlassian.net/browse/HHH-16400
Definitely not something we need to backport to 6.2, but would be nice to have in 6.3 IMO.
=> HHH-16400 Avoid reflection for calls to StackWalker

hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/GenericMapAssociationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/naturalid/compound/CompoundNaturalIdCacheTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/onetomany/RefreshWithPropertyAccessAndCollectionMapManipulationInSetterMethodTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/onetomany/RefreshWithPropertyAccessAndListManipulationInSetterMethodTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/NamedParameterInSelectAndWhereTest.java
Fix a couple failing tests due to unsupported features and Oracle 11 table name length restriction:
https://ci.hibernate.org/job/hibernate-orm-nightly/job/main/155/
=> Fix failing tests on CockroachDB and Oracle 11

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SimpleDatabaseVersion.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/HANADialectTestCase.java
Fix for https://hibernate.atlassian.net/browse/HHH-16444
This is what the log will look like:
```
INFO SQL dialect [vert.x-worker-thread-0] HHH000400: Using dialect: org.hibernate.dialect.MariaDBDialect, version: 10.11
```
=> HHH-16444 When logging the selected dialect, log the db version too

hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcServicesImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/SqlStatementLoggerInitiator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/SqlStatementLogger.java, hibernate-core/src/main/java/org/hibernate/service/StandardServiceInitiators.java
This way is possible to get the logger without having to initialize the JdbcServices service.
Something that I need for Hibernate Reactive.
Before I clean up the changes, is this acceptable?
=> HHH-16443 Convert SqlStatementLogger into a Service

hibernate-core/src/main/java/org/hibernate/action/internal/EntityDeleteAction.java
These changes are already in main but we need them in 6.2 for reactive
=> Relax scopes of methods in EntityDeleteAction

hibernate-core/src/test/java/org/hibernate/orm/test/mapping/naturalid/compound/CompoundNaturalIdTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/ops/HANANoColumnInsertTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/timezones/UTCNormalizedInstantTest.java
Should also fix some [timestamp failures on s390x](https://ci.hibernate.org/job/hibernate-orm-pipeline/job/main/1721/testReport/junit/org.hibernate.orm.test.timezones/UTCNormalizedInstantTest/Build___s390x_h2___Test___test_SessionFactoryScope_/).
=> Fix test that caused sporadic CI failures and shorten entity names for ORA11

hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/superclass/ReferencedJoinedSuperclassColumnTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/superclass/ReferencedSuperclassColumnTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/superclass/ReferencedUnionSuperclassColumnTest.java
See https://hibernate.atlassian.net/browse/HHH-16501 and https://stackoverflow.com/questions/76079159/joincolumn-references-a-column-but-the-target-entity-has-no-property-which-maps
=> HHH-16501 allow referencedColumnName to column mapped by superclass of target entity

tooling/metamodel-generator/hibernate-jpamodelgen.gradle, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/JPAMetaModelEntityProcessor.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/MetaAttributeGenerationVisitor.java, tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/records/Address.java, tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/records/Author.java, tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/records/Java14RecordsTest.java
=> Fix for Jira issue HHH-16261

hibernate-testing/src/main/java/org/hibernate/testing/AfterClassOnce.java, hibernate-testing/src/main/java/org/hibernate/testing/BeforeClassOnce.java, hibernate-testing/src/main/java/org/hibernate/testing/FailureExpected.java, hibernate-testing/src/main/java/org/hibernate/testing/OnExpectedFailure.java, hibernate-testing/src/main/java/org/hibernate/testing/OnFailure.java, hibernate-testing/src/main/java/org/hibernate/testing/RequiresDialect.java, hibernate-testing/src/main/java/org/hibernate/testing/RequiresDialectFeature.java, hibernate-testing/src/main/java/org/hibernate/testing/RequiresDialects.java, hibernate-testing/src/main/java/org/hibernate/testing/Skip.java, hibernate-testing/src/main/java/org/hibernate/testing/SkipForDialect.java, hibernate-testing/src/main/java/org/hibernate/testing/SkipForDialects.java, hibernate-testing/src/main/java/org/hibernate/testing/TestForIssue.java
https://hibernate.atlassian.net/browse/HHH-16497
Technically we could keep `TestForIssue` undeprecated since it "works" on JUnit 5 as well, but I suppose `org.hibernate.testing.orm.junit.JiraKey` was introduced for a reason, so we may as well avoid duplicating the feature.
Personally I wouldn't backport to 6.2, but YMMV.
=> HHH-16497 Deprecate JUnit 4 testing annotations

hibernate-core/src/test/java/org/hibernate/orm/test/mapping/onetoone/ToOneSelfReferenceTest.java
Adding a test for [HHH-16488](https://hibernate.atlassian.net/browse/HHH-16488).
This issue is also related to https://github.com/hibernate/hibernate-orm/pull/6356, both are caused by table-reference resolution when an entity has an association with itself.
[HHH-16488]: https://hibernate.atlassian.net/browse/HHH-16488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HHH-16488 Hibernate ORM 6.2.1 / Wrong select clause generated / OneToOne between the same entity

migration-guide.adoc
As mentioned in [HHH-16392](https://hibernate.atlassian.net/browse/HHH-16392)'s comments, the `@Where` annotation's behavior was changed in 6.0 without mentioning it in the Migration Guide. This PR adds a dedicated chapter.
[HHH-16392]: https://hibernate.atlassian.net/browse/HHH-16392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HHH-16392 @Where annotation 6.0 migration guide chapter

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/boot/model/TypeContributions.java, hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleArrayJdbcType.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleArrayJdbcTypeConstructor.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleJdbcHelper.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/AbstractArrayJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ArrayJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/BasicCollectionJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/ArrayJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/ArrayJdbcTypeConstructor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JdbcTypeConstructor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/spi/JdbcTypeRegistry.java
previously, there was a global instance of `ArrayJdbcType` registered by the `Dialect`s, in an inconsistent state, that acted as a factory for correctly-initialized instances
=>  HHH-16125 introduce JdbcTypeConstructor instead of using JdbcTypes as their own factories

hibernate-core/src/main/java/org/hibernate/boot/model/internal/BasicValueBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/InferredBasicValueResolver.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleJdbcHelper.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleNestedTableJdbcType.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleNestedTableJdbcTypeConstructor.java, hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java, hibernate-core/src/main/java/org/hibernate/mapping/Column.java, hibernate-core/src/main/java/org/hibernate/type/BasicArrayType.java, hibernate-core/src/main/java/org/hibernate/type/ConvertedBasicArrayType.java, hibernate-core/src/main/java/org/hibernate/type/SqlTypes.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/converter/internal/ArrayConverter.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/AbstractArrayJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ArrayJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/ArrayJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JdbcTypeIndicators.java, hibernate-core/src/main/java/org/hibernate/type/internal/ConvertedBasicTypeImpl.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/SessionFactoryExtension.java
This PR lets you write stuff like:
```java
@Column(length = 25)
@JdbcTypeCode(SqlTypes.TABLE)
String[] strings;
```
To get a nested table instead of a `varray` on Oracle.
This was surprisingly difficult to do, due to how array types are set up and initialized.
=> HHH-16544 POC support for Oracle nested tables

hibernate-core/src/main/java/org/hibernate/dialect/SQLServer2016Dialect.java
Use version 13 as suggestion in the deprecation warning instead of 11 which is version MS SQL 2012
=> HHH-16556 Correct MS SQL 2016 deprecation version

hibernate-core/src/main/java/org/hibernate/persister/collection/BasicCollectionPersister.java
In the changes added to `BasicCollectionPersister` during [HHH-15393](https://hibernate.atlassian.net/browse/HHH-15393), it looks as if `generateUpdateRowOperation` has maybe been copy-pasted from `generateInsertRowOperation` (which is perfectly fine), but when the custom sql update row operation is generated, the mutation details for the insert case rather than the ones for the update case are fetched.
In case that this assumption is correct, there are some more in `buildCustomSqlUpdateRowOperation`, where  `getDeleteDetails()` is used instead of `getUpdateDetails()`.
[HHH-15393]: https://hibernate.atlassian.net/browse/HHH-15393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HHH-15393 fix for what looks like a copy & paste error

docker_db.sh, nightly.Jenkinsfile
The guys at Cockroach Labs asked to test also against the 23.1 version. 
I've added the configuration to the docker startup script. Could you add a job for the new version to Jenkins? Maybe replace the 20.1 job with this one?
=> HHH-16552 - Add CockroachDB v23.1 to docker startup script

hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
Fix [HHH-16579](https://hibernate.atlassian.net/browse/HHH-16579)
[HHH-16579]: https://hibernate.atlassian.net/browse/HHH-16579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HHH-16579 - Add constructor for CockroachDialect that parses the version without querying the db

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/cache/internal/QueryResultsCacheImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/cache/NonRootEntityWithCacheAnnotationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/cfg/cache/DefaultCacheConcurrencyPropertyTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/cacheable/annotation/ConfigurationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/ExplicitJavaTypeDescriptorTest.java
1. Throw instead of logging a `WARN` if `@Cache` is on a subclass. 
3. Fix interpretation of `SharedCacheMode.UNSPECIFIED` (UPDATE: this was the root cause of https://hibernate.atlassian.net/browse/HHH-9763)
I just lost 1/2 an hour of my life due to this being a WARN. Logging WARNs is a terrible way to report user error! I've complained about this practice lots of times, and just got bitten by it myself.
=> HHH-16603, HHH-9763 fix two issues with interpreting @Cache/@Cacheable annotations

hibernate-core/src/main/java/org/hibernate/internal/util/ReflectHelper.java
This PR fixes typo in the javadoc of `getGetterOrNull`.
=> HHH-16542 - Correct typo in javadoc

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
because some amazing geniuses on stackoverflow who know much more than me about Hibernate are obsessing over this DEBUG-level log message
=> get rid of a stack trace from debug-level log

hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/quarkus/MetadataCopyingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/quarkus/package-info.java
https://hibernate.atlassian.net/browse/HHH-16625
=> HHH-16625 Restore Quarkus compatibility

hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/OracleNumericTypesTest.java
Oracle reports `FLOAT`/`DOUBLE PRECISION` as `NUMBER`, which is wrong. The workaround was to look at the scale, which it reports as -127 for `FLOAT`. But certain other expression also get scale -127, and this could cause truncation of least-significant digits in conversion of a huge `NUMBER` to `Double`.
=> HHH-16650 fix for native queries with "unknown" numeric types on Oracle

documentation/src/main/asciidoc/introduction/Interacting.adoc, hibernate-core/src/main/java/org/hibernate/IdentifierLoadAccess.java, hibernate-core/src/main/java/org/hibernate/MultiIdentifierLoadAccess.java, hibernate-core/src/main/java/org/hibernate/NaturalIdMultiLoadAccess.java, hibernate-core/src/main/java/org/hibernate/graph/Graph.java, hibernate-core/src/main/java/org/hibernate/loader/internal/SimpleNaturalIdLoadAccessImpl.java
1. make fetch/load graph distinction clearer in the `XxxxLoadAccess` APIs
2. `addPluralSubgraph()`, which is missing in JPA
=> HHH-16645 two API improvements to EntityGraphs

hibernate-core/src/main/java/org/hibernate/Hibernate.java, hibernate-core/src/main/java/org/hibernate/annotations/LazyCollection.java, hibernate-core/src/main/java/org/hibernate/annotations/LazyCollectionOption.java, hibernate-core/src/main/java/org/hibernate/collection/spi/AbstractPersistentCollection.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentBag.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentList.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentMap.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentSet.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/basic/CollectionSizeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/basic/Contact.java
in which static remove methods were added to the Hibernate class
The reason for this is that the methods in fact don't work, since the machinery behind them just isn't there, nor has it even been.
The CollectionSizeTest that was modified to test these new methods was incomplete and hid this fact.
=> HHH-16649 - This commit effectively reverts d8bf6499 (HHH-15910)

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java
don't generate a 'not null' constraint for a field of an embeddable class if it belongs to a subclass in single table inheritance hierarchy
=> HHH-16600 @Basic(optional=false) on embeddable held by single table subclass

hibernate-core/src/main/java/org/hibernate/id/ForeignGenerator.java, hibernate-core/src/main/java/org/hibernate/id/IdentifierGeneratorHelper.java, hibernate-core/src/main/java/org/hibernate/mapping/Component.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/RowVersionJavaType.java
because apparently some users depend on them: https://hibernate.atlassian.net/browse/HHH-16692
Also mark `IdentifierGeneratorHelper` as `@Internal`.
=> mark some ancient hacks as deprecated

hibernate-core/src/main/java/org/hibernate/engine/spi/LoadQueryInfluencers.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderStandardImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/LoadingSmokeTests.java
and remove an `AtomicInteger` that existed only for the benefit of `LoadingSmokeTests`
=> clean up the code in SingleIdEntityLoaderStandardImpl

hibernate-core/src/main/java/org/hibernate/query/criteria/HibernateCriteriaBuilder.java
in some cases, it overrides JPA methods with non-varargs forms
=> HibernateCriteriaBuilder should use varargs

hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/basic/ExtendedEnhancementNonStandardAccessTest.java
I originally wrote this to compare the behavior with what we get in Quarkus (where part of the bytecode enhancement is done by Panache instead).
Turns out there is nothing wrong and these tests already pass, but we might as well merge this to get more non-regression tests?
=> Test non-standard access with extended bytecode enhancement

hibernate-core/src/main/java/org/hibernate/query/SyntaxException.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/SqlExpressionResolver.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/WindowFunctionTest.java
- we should throw `SyntaxException` for expected conditions
- also, avoid the use of weirdo non-standard hyphenation in error messages
=> don't throw ParsingException (it represents a bug in the parser)

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmJdbcExecutionContextAdapter.java, hibernate-core/src/main/java/org/hibernate/sql/exec/spi/ExecutionContext.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/internal/RowProcessingStateStandardImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/locking/OptimisticAndPessimisticLockTest.java
https://hibernate.atlassian.net/browse/HHH-16461
I checked and it seems that in 5.6 we execute the version check only for hql queries https://github.com/hibernate/hibernate-orm/blob/5.6/hibernate-core/src/main/java/org/hibernate/loader/Loader.java#L1703
=> HHH-16461 @Version + session.refresh(entity, LockMode.PESSIMISTIC_WRITE) leads to StaleObjectStateException

hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java
This is a small follow-up on https://hibernate.atlassian.net/browse/HHH-16815
In Hibernate Search, we are using the `AbstractQuery` SPI. It would be easier for us to support both 6.2 and 6.3 at the same time if `AbstractQuery` (or `AbstractSelectionQuery`) would implement the new sorting methods even if that's just throwing an unsupported exception 
https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-dependency-update/detail/main/111/pipeline/222/
```
[ERROR] /mnt/jenkins-workdir/workspace/te-search-dependency-update_main/mapper/orm/src/main/java/org/hibernate/search/mapper/orm/search/query/impl/HibernateOrmSearchQueryAdapter.java:[53,13] error: HibernateOrmSearchQueryAdapter is not abstract and does not override abstract method unordered() in Query
[ERROR]   where R is a …
```
=> followup: HHH-16815

hibernate-core/src/test/java/org/hibernate/orm/test/jpa/lock/LockTest.java
https://hibernate.atlassian.net/browse/HHH-16275
I started https://hibernate.zulipchat.com/#narrow/stream/132094-hibernate-orm-dev/topic/HHH-16275.20testLockInsertFkTarget/near/363815861 on Zulip to discuss this change.  Feedback is welcome here as well.
=> HHH-16275 wait longer for LockTest.testLock*FkTarget to insert/update row on the database server to avoid occasional fail with timeout getting lock

documentation/src/main/asciidoc/userguide/Credits.adoc, documentation/src/main/asciidoc/userguide/Hibernate_User_Guide.adoc
I tried to filter out contributors who only fixed typos, hopefully I didn't forget anyone.
=> User guide credits: Move them to a dedicated section and add some missing names

hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/JavaTypeHelper.java, hibernate-core/src/main/java/org/hibernate/type/format/jaxb/JaxbXmlFormatMapper.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/BulkManipulationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/pagination/DistinctSelectTest.java
the previous implementation was not compliant with the JPA spec and defied logic
=> HHH-16843 fix interpretation of 'value = null' in HQL

hibernate-core/src/main/java/org/hibernate/sql/ast/spi/SqlAliasStemHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/associations/FieldWithUnderscoreTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/graph/HHH15065Test.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/ManyToOneJoinReuseTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/InheritanceQueryGroupByTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/TreatDisjunctionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/DepthOneBatchTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/DepthOneTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/CompareEntityValuedPathsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/QueryTimeOutTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/SameTableAliasInSubqueryWithEmbeddedTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/ast/SmokeTests.java
- because Oracle hates that
- also, as suggested by @sebersole common in code, start generating "acronym"-based aliases
=> HHH-16619 don't generate table aliases beginning with _

hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessEnhancedImpl.java, hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyEnhancedImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/access/PropertyAccessTest.java
https://hibernate.atlassian.net/browse/HHH-16799
While the test case itself may look a bit silly, it was as close as I got to get to the same state as in the original issue caused by using Kotlin in Quarkus 🙈 (https://github.com/quarkusio/quarkus/issues/33740)
If the fix isn't ok -- let me know 😄
=> HHH-16799 Backport 6.2: Don't fall back to field access type too early

hibernate-core/src/main/java/org/hibernate/query/OutputableType.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/ArgumentTypesValidator.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/CurrencyJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/EnumJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/JdbcTimestampJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JdbcType.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/CompositeIdFkUpdateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/EnumComparisonTest.java
In particular, correctly type check comparisons between enums and other enums, literal integers, and literal strings. 
Actually I'm not a great fan of comparing enums with int/string literals but since we used to support it in 5, and kinda mostly support it in earlier releases of 6, on balance we might as well continue to allow it. It's not like it's wrong wrong, just something that's probably bad most of the time.
Indeed, this patch goes so far as to allow this sort of comparison _in general_ when JDBC types match in a "reasonable" way. Where "reasonable" involves some handwavey heuristics. Not perfect but I guess this probably a case where worse is better.
UPDATE: I was also obligated to "fix" the non-bug HHH-16859 by side-effect of cleaning up another issue with type-checking of enum …
=> HHH-16858 improve typechecking for comparisons/assignments

gradle/java-module.gradle
See JIRA [HHH-16896](https://hibernate.atlassian.net/browse/HHH-16896)
The `JavaCompile` tasks [reference](https://github.com/hibernate/hibernate-orm/blob/39bc616cd97a505f0a8816a3422e09a009eac576/gradle/java-module.gradle#L527) the `stubs` argument (through the [check-framework-gradle-plugin](https://github.com/kelloggm/checkerframework-gradle-plugin)) plugin which is defined as an absolute path to the `checkerstubs` folder.
When the project folder is different (CI vs local build for instance), this absolute path is different which changes the build cache key of the task and prevents from getting a build cache hit.
See related issue https://github.com/kelloggm/checkerframework-gradle-plugin/issues/252
Experimenting locally, the impact is 5mn28s of CPU time (starting with an empty cache): …
=> Fix build cache misses on JavaCompile tasks when project is relocated

hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/TupleInListAlternativeTests.java
This PR fixes the issue documented in https://hibernate.atlassian.net/browse/HHH-16886 with the incorrect SQL alternative for tuple-in-lists on DBMS not supporting tuple-in-lists.
=> HHH-16886 fix sql mutli value emulation for dialects not supporting row constructor syntax in list

hibernate-core/src/main/java/org/hibernate/boot/jaxb/internal/stax/LocalXmlResourceResolver.java, hibernate-core/src/test/java/org/hibernate/boot/jaxb/internal/stax/LocalXmlResourceResolverTest.java
https://hibernate.atlassian.net/browse/HHH-16892
Backported to:
* branch 6.2 as #6940
* branch 5.6 as #6941
=> HHH-16892 LocalXmlResourceResolver does not resolve dtd URLs that use https scheme

hibernate-core/src/main/java/org/hibernate/boot/jaxb/internal/stax/LocalXmlResourceResolver.java, hibernate-core/src/test/java/org/hibernate/boot/jaxb/internal/stax/LocalXmlResourceResolverTest.java
https://hibernate.atlassian.net/browse/HHH-16892
Backport of #6939 to branch 5.6
=> Backport HHH-16892 to branch 5.6 - LocalXmlResourceResolver does not resolve dtd URLs that use https scheme

hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
https://hibernate.atlassian.net/browse/HHH-16695
Hey @gavinking 
Hibernate Search tests caught some incompatibility on the ORM version upgrade. With these changes, it allows to keep Search working with both 6.2 and 6.3 ORM versions. Does that look OK to you? Thanks!
=> HHH-16695 Make AbstractQuery backwards compatible

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/version/DetachedEntityWithNullVersionTest.java
https://hibernate.atlassian.net/browse/HHH-16586
=> HHH-16586 When merging a persisted entity with a null Version, Hibernate treats entity as transient instead of throwing an Exception

hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/TableSet.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateValuesAnalysis.java
- https://hibernate.atlassian.net/browse/HHH-16884
Preliminary benchmarking using Techempower's endpoint `/update`, which stresses the update operations via batching 20 updates in each transaction, shows a reduction of 60% of memory allocations overall. I'd consider this very significant, however I don't expect same benefits to translate on a general purpose application as this benchmark literally only performs updates, and on a very simplistic model.
This is caused by the fact that when reducing the amount of `HashSet` allocations, and their usage, there's also an impact on the amount of wrapped `HashMap` instances, their internal arrays, and all entry objects.
=> HHH-16884 Improve efficiency of UpdateCoordinatorStandard in tracking tables to be updated

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/UniqueKeyEntry.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java, hibernate-core/src/test/java/org/hibernate/orm/test/cfg/persister/GoofyPersisterClassProvider.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ejb3configuration/PersisterClassProviderTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/legacy/CustomPersister.java
https://hibernate.atlassian.net/browse/HHH-16728
This requires exposing a new accessor on `EntityPersister` so I'd prefer to ask for some feedback; otherwise it seems straight forward and I'd already have applied it.
Would love to have this backported as well as the impact is quite strong, but no rush.
=> HHH-16728 Optimise iteration of AssociationType properties within a Persister

hibernate-core/src/main/java/org/hibernate/InstantiationException.java, hibernate-core/src/main/java/org/hibernate/PropertyAccessException.java, hibernate-core/src/main/java/org/hibernate/jpa/spi/NativeQueryConstructorTransformer.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmFrom.java, hibernate-core/src/test/java/org/hibernate/orm/test/property/access/spi/GetterMethodImplTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/property/access/spi/SetterMethodImplTest.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/JPAMetaModelEntityProcessor.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaType.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/Constants.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/TypeUtils.java, tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/hqlsql/Books.java
1. typechecking for the return type of `@HQL` query methods
2. adds generation of `Book_.class_` returning `EntityType<Book>` (with appropriate support for `@Embeddable`s and `@MappedSuperclass`es.
=> HHH-16633, HHH-16940 validate the return type of @HQL query methods

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmPath.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/CriteriaToOneIdJoinTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/nestedfetch/NestedFetchTest.java
https://hibernate.atlassian.net/browse/HHH-16905
https://hibernate.atlassian.net/browse/HHH-16926
Fixes a regression in `NavigablePath` copy logic introduced by #6814.
=> HHH-16905, HHH-16926 Fix navigable path copy logic when identifiers are involved

hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/version/InheritanceVersionedParentTest.java
https://hibernate.atlassian.net/browse/HHH-16667
Backport of #6928
=> HHH-16667 Hibernate 6 PrimaryKeyJoinColumn causes implicit version update to fail

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmInterpretationsKey.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/order/OrderTest.java
Roll back my always-intended-to-be-temporary bandaid to allow caching of the query plan after calls to `setOrder()`. Instead, just disable caching of the query plan. When the query plan cache can handle caching of criteria queries, change to use that strategy instead.
=> remove order-by list from the query plan cache key

hibernate-core/src/main/java/org/hibernate/dialect/lock/PessimisticReadSelectLockingStrategy.java, hibernate-core/src/main/java/org/hibernate/dialect/lock/PessimisticWriteSelectLockingStrategy.java, hibernate-core/src/main/java/org/hibernate/dialect/lock/SelectLockingStrategy.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/ResultSetReturn.java, hibernate-core/src/main/java/org/hibernate/id/GUIDGenerator.java, hibernate-core/src/main/java/org/hibernate/id/IncrementGenerator.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStructure.java, hibernate-core/src/main/java/org/hibernate/id/insert/AbstractSelectingDelegate.java, hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetomany/OrderByTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/list/PersistentListTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/exception/SQLExceptionConversionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/SequenceValueExtractor.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/custom/CustomSequenceGenerator.java, hibernate-core/src/test/java/org/hibernate/orm/test/jdbc/internal/AggressiveReleaseTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jdbc/internal/BasicConnectionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/autodiscovery/AutoDiscoveryTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/typeparameters/TypeParameterTest.java, hibernate-envers/src/main/java/org/hibernate/envers/strategy/internal/ValidityAuditStrategy.java
https://hibernate.atlassian.net/browse/HHH-13741
Simpler (and I'd argue more correct) alternative  to https://github.com/hibernate/hibernate-orm/pull/5088
=> HHH-13741 - LOG_SLOW_QUERY parameter doesn't always log SQL

hibernate-core/src/main/java/org/hibernate/mapping/KeyValue.java
This is a band-aid over an error occurring in Liquibase. But it seems to me that Liquibase itself should be updated to use the new APIs.
https://hibernate.atlassian.net/browse/HHH-16912
=> HHH-16912 return null from deprecated method instead of producing a CCE

hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/StrictJpaComplianceViolation.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/nofrom/NoFromTest.java
<https://hibernate.atlassian.net/browse/HHH-16973>
- Makes the `from` clause optional when the result class is an entity type.
- Misc code and typing cleanups to SQB.
=> HHH-16973 optional 'from' clause

tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractQueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/CriteriaFinderMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/QueryMethod.java, tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/dao/Dao.java
This is not necessary for `@Id` or `@NaturalId`-based `@Find` methods, because they don't return multiple results.
=> allow criteria-based @Find methods to specify Page and Order

hibernate-core/src/main/java/org/hibernate/internal/util/MathHelper.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/internal/util/MathHelperTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/MaxInExpressionParameterPaddingTest.java
See [HHH-16826](https://hibernate.atlassian.net/browse/HHH-16826).
In the first commit I added some parameterized tests to `MaxInExpressionParameterPaddingTest` since they are much less verbose for this kind of test. I also added some of the constellation of the existing tests to the parameterized test data. Now some constellations are tested twice, since I did not dare to remove the existing tests. Some of the existing tests have annotations like `@TestForIssue(jiraKey = "HHH-14109")`. If I were to remove the existing tests in favor of the parameterized tests I wasn't sure what to do with those annotations. Since the annotation is not repeatable I can't add multiple annotations to the parameterized test and I don't know what you use those annotations for.
To avoid the test duplication I …
=> HHH-16826 - IN-Clause Parameter Padding should grow exponentially for Dialects with InExpressionCountLimit

gradle.properties, hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/registry/classloading/PhantomReferenceLeakDetector.java
Follow up to [HHH-16911](https://hibernate.atlassian.net/browse/HHH-16911) , possibly fixing the issues on x390
Many thanks to Andrew Haley for suggesting it.
[HHH-16911]: https://hibernate.atlassian.net/browse/HHH-16911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HHH-16911 Ensure the PhantomReference doesn't get collected before having had a change to trigger

hibernate-core/src/main/java/org/hibernate/action/internal/EntityInsertAction.java, hibernate-core/src/main/java/org/hibernate/action/internal/EntityUpdateAction.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
Reactive support for ORM currently uses redundant code already in ORM.  Changing the visibility of a handful of methods from `private` to `protected` will simplify HR code and reduce risk of future errors.
https://hibernate.atlassian.net/browse/HHH-16999
=> HHH-16999 Relax visibility of some methods for hibernate-reactive

hibernate-core/src/main/java/org/hibernate/id/AbstractPostInsertGenerator.java, hibernate-core/src/main/java/org/hibernate/id/IdentifierGeneratorHelper.java
I should not have removed this class, I messed up there.
https://hibernate.atlassian.net/browse/HHH-17009
=> HHH-17009 put back AbstractPostInsertGenerator in deprecated mode

Jenkinsfile, ci/build.sh, gradle/databases.gradle, hibernate-core/src/main/java/org/hibernate/dialect/SybaseDialect.java, hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/AbstractInformationExtractorImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemamanager/SchemaManagerExplicitSchemaTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/timezones/AutoZonedTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/timezones/ColumnZonedTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/timezones/DefaultZonedTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/timezones/JDBCTimeZoneZonedTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/timezones/PassThruZonedTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/timezones/UTCNormalizedInstantTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/timezones/UTCNormalizedZonedTest.java, nightly.Jenkinsfile
https://hibernate.atlassian.net/browse/HHH-16611
=> HHH-16611 Switch NameQualifierSupport for Sybase to BOTH

hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/DirtyCheckingWithEmbeddableAndNonVisibleGenericMappedSuperclassTest.java
https://hibernate.atlassian.net/browse/HHH-16832
=> Backport HHH-16832 to branch 6.2 - Follow-up: add missing test annotation

settings.gradle
Just checking if the Hibernate ORM main branch testsuite passes with ByteBuddy 1.14.5 which is the most recent BB release and includes the latest ASM release that has a constant defined for Java SE 21.
https://hibernate.atlassian.net/browse/HHH-16971
=> HHH-16971 Upgrade ByteBuddy to 1.14.5

hibernate-core/src/main/java/org/hibernate/boot/model/internal/ClassPropertyHolder.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/CodeTemplates.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableRepresentationStrategyPojo.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/DirtyCheckingWithEmbeddableAndNonVisibleGenericMappedSuperclassWithDifferentGenericParameterNameTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/DirtyCheckingWithEmbeddableAndTwiceRemovedNonVisibleGenericMappedSuperclassTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/DirtyCheckingWithEmbeddableExtedingAnotherEmbeddableAndTwiceRemovedNonVisibleGenericMappedSuperclassTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/DirtyCheckingWithEmbeddableExtendingMappedSuperclassTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/DirtyCheckingWithEmbeddableNonVisibleGenericExtendsSerializableMappedSuperclassTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/MyNonVisibleGenericExtendsSerializableMappedSuperclass.java, hibernate-core/src/test/java/org/hibernate/orm/test/component/EmbeddableAndGenericExtendingSerializableMappedSuperclassTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/component/EmbeddableAndGenericMappedSuperclass2Test.java, hibernate-core/src/test/java/org/hibernate/orm/test/component/EmbeddableAndGenericMappedSuperclassTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/component/EmbeddableExtendsMappedSuperclassTest.java
- https://hibernate.atlassian.net/browse/HHH-17034 Bytecode enhancement leads to broken constructor for a generic embedded field in a twice removed MappedSuperclass
- https://hibernate.atlassian.net/browse/HHH-17035 Bytecode enhancement leads to StackOverflowError with specific setup involving different generic parameter names  
- https://hibernate.atlassian.net/browse/HHH-17041 Embeddable and Generics throws IllegalArgumentException
=> HHH-17034 + HHH-17035 + HHH-17041

hibernate-core/src/main/java/org/hibernate/boot/model/internal/JPAXMLOverriddenAnnotationReader.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyMappingElementCollector.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/jaxb/mapping/HibernateOrmSpecificAttributesMappingTest.java, hibernate-core/src/test/resources/xml/jaxb/mapping/partial/hibernate-orm-specific-attributes.xml
https://hibernate.atlassian.net/browse/HHH-17072
This one is for Search integration. It seems that the tenant id element was present but then ignored when converting to annotation proxies (https://github.com/hibernate/hibernate-orm/blob/4666d774e42266da90d6fc132193454020b37019/hibernate-core/src/main/resources/org/hibernate/xsd/mapping/mapping-3.1.0.xsd#L472C16-L472C17)
=> HHH-17072 Process tenant-id from XML mapping

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/LazyToOneJoinOnNonPrimaryKeyColumnTest.java
https://hibernate.atlassian.net/browse/HHH-17075
=> HHH-17075 Lazy loading of association with non-PK referencedColumnName always yields null when bytecode enhancement is enabled

hibernate-core/src/main/java/org/hibernate/dialect/lock/PessimisticForceIncrementLockingStrategy.java, hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultPostLoadEventListener.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderHelper.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinator.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java, hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchSelectAndForceIncrementVersionTest.java
https://hibernate.atlassian.net/browse/HHH-16939
=> HHH-16939 Optimistic and Pessimistic Force Increment Update Statements are not committed when using a batch

documentation/src/main/asciidoc/userguide/chapters/caching/Caching.adoc
---
I found a typo while reading docs.
I'm reading it useful. Thank you.
To fIx typo in documentation [13.1.2. Caching configuration properties](https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#caching-config-properties)
---
=> Fix typo in documentation `13.1.2. Caching configuration properties`

hibernate-core/src/main/java/org/hibernate/action/internal/BulkOperationCleanupAction.java, hibernate-core/src/main/java/org/hibernate/action/internal/CollectionAction.java, hibernate-core/src/main/java/org/hibernate/action/internal/EntityAction.java, hibernate-core/src/main/java/org/hibernate/action/spi/Executable.java, hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java, hibernate-core/src/main/java/org/hibernate/persister/collection/CollectionPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/UnionSubclassEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/cfg/persister/GoofyPersisterClassProvider.java, hibernate-core/src/test/java/org/hibernate/orm/test/engine/action/NonSortedExecutableListTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/engine/action/SortedExecutableListTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ejb3configuration/PersisterClassProviderTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/legacy/CustomPersister.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/validation/MockCollectionPersister.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/validation/MockEntityPersister.java
Migrating `Serializable[] getPropertySpaces()` to `String[] getPropertySpaces()` : we seem to require these to be String[] and need to occasionally do some casting; might as well make it explicit?
Please let me know if this is considered an SPI breaking change, I could do it with a deprecation cycle and choosing a new methodname... I hope that's unnecessary in this case.
=> Migrating `Serializable[] getPropertySpaces()` to `String[] getPropertySpaces()`

Jenkinsfile, ci/build.sh, docker_db.sh, edb/edb11.Dockerfile, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CommunityDialectSelector.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQL10Dialect.java, hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/CommunityDialectSelectorTest.java, hibernate-core/src/main/java/org/hibernate/boot/registry/selector/internal/DefaultDialectSelector.java, hibernate-core/src/main/java/org/hibernate/dialect/DerbyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2SqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiLoadSubSelectCollectionDialectWithLimitTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/contributed/BasicContributorTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/DepthOneBatchTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/FetchSizeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/InExpressionCountLimitExceededTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/strategyselectors/DefaultDialectSelectorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/tool/schema/internal/StandardForeignKeyExporterTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/H2JsonListTest.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java, nightly.Jenkinsfile, settings.gradle
https://hibernate.atlassian.net/browse/HHH-15177 - Remove support for PostgreSQL versions older than 11
https://hibernate.atlassian.net/browse/HHH-15194 - Remove support for PostgreSQL Advanced Server versions older than 11
https://hibernate.atlassian.net/browse/HHH-15535 - Remove support for H2 versions older than 2.1
https://hibernate.atlassian.net/browse/HHH-15203 - Remove support for Derby versions older than 10.15
=> HHH-15491 - Remove support for database versions that are unsupported by vendors 6.3 edition

hibernate-core/src/main/java/org/hibernate/engine/spi/SubselectFetch.java
Back-ported some of the changes to SubselectFetch in 6.3 that refactored/removed the restrictive check on the
class EntityResultInitializer
This change will fix Hibernate Reactive tests
* [#1502 - SubSelectTest fails](https://github.com/hibernate/hibernate-reactive/issues/1502)
* [#1501 - BatchFetchTest.testQuery() fails](https://github.com/hibernate/hibernate-reactive/issues/1501)
https://hibernate.atlassian.net/browse/HHH-17130
=> HHH-17130 remove restrictive instanceof EntityResultInitializer check

hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/literal/CriteriaLiteralWithSingleQuoteTest.java
https://hibernate.atlassian.net/browse/HHH-14669
https://issues.redhat.com/browse/JBEAP-22059
=> [HHH-14669] CriteriaLiteralWithSingleQuoteTest: SAP ASE16.0 does not support grouping by column heading or alias

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/Enhancer.java, hibernate-core/src/main/java/org/hibernate/bytecode/spi/ClassTransformer.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/enhance/EnhancingClassTransformerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/BootstrapTest.java
https://hibernate.atlassian.net/browse/HHH-17154
=> HHH-17154 Fix NullPointerException is thrown when constructing EntityManagerFactoryBuilderImpl

hibernate-core/src/main/java/org/hibernate/mapping/Component.java, hibernate-core/src/test/java/org/hibernate/orm/test/cut/generic/EnumPlaceholder.java, hibernate-core/src/test/java/org/hibernate/orm/test/cut/generic/EnumPlaceholderUserType.java, hibernate-core/src/test/java/org/hibernate/orm/test/cut/generic/GenericCompositeUserTypeEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/cut/generic/GenericCompositeUserTypeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/cut/generic/Weekdays.java
This PR fixes an issue when using a composite user type to map a class that  has generic arguments. The issue was already reported by Jira ticket [HHH-17079](https://hibernate.atlassian.net/browse/HHH-17079) (reported by Adam Pawlak and assigned to @beikov ).
[HHH-17079]: https://hibernate.atlassian.net/browse/HHH-17079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HHH-17079 - Fixed NPE when mapping a generic class as a composite user type

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedColumn.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedJoinColumn.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedJoinColumns.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ColumnsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/TableBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ToOneBinder.java, hibernate-core/src/main/java/org/hibernate/mapping/Column.java, hibernate-core/src/main/java/org/hibernate/mapping/Table.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/mapsid/DefaultedMapsIdTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/mapsid/MapsEmbeddedIdTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/mapsid/MapsEmbeddedIdWithOverrideTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/mapsid/MapsIdSpecTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/mapsid/MapsIdTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/mapsid/NoIdClassMapsIdTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/mapsid/NoMapsIdTest.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/ids/embeddedid/CorrectChild.java
Previously, the `value` member of the `@MapsId` annotation was essentially ignored, at least for `@ManyToOne` mappings. This forced the user to specify duplicate mappings for the columns.
https://hibernate.atlassian.net/browse/HHH-16592
=> HHH-16592 value of @MapsId should be used to infer column mappings for @ManyToOne

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/MergeCoordinator.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
Reactive support for `upsert()` feature in ORM requires relaxed visibility changes to a few methods
see:  https://github.com/hibernate/hibernate-reactive/issues/1702 for details and this [PR](https://github.com/hibernate/hibernate-reactive/pull/1757)
https://hibernate.atlassian.net/browse/HHH-17204
=> HHH-17204 visibility changes for Reactive upsert() support

hibernate-core/src/main/java/org/hibernate/internal/MultiIdentifierLoadAccessImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiIdEntityLoadTests.java
https://hibernate.atlassian.net/browse/HHH-17201
=> HHH-17201 Unexpected value type exception for unordered multi id Load with ordered return disable

hibernate-core/src/main/java/org/hibernate/annotations/RowId.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/AbstractMutationCoordinator.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/DeleteCoordinator.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java, hibernate-core/src/test/java/org/hibernate/orm/test/rowid/RowIdUpdateAndDeleteTest.java
https://hibernate.atlassian.net/browse/HHH-17167
=> HHH-17167 Unable to locate parameter for RESTRICT - DELETE error when removing entity with RowId

documentation/src/main/asciidoc/userguide/chapters/batch/Batching.adoc
The example 478, 481 code only has the `Person` class. In the description of this code, `Customer` is listed, so modify it to `Person`.
=> Fix typo in `12.Batching`

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DialectDelegateWrapper.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/TimestampaddFunction.java
https://hibernate.atlassian.net/browse/HHH-17242
=> HHH-17242 Improve temporal arithmetic SQL rendering

documentation/documentation.gradle, documentation/src/main/asciidoc/userguide/Hibernate_User_Guide.adoc, documentation/src/main/asciidoc/userguide/chapters/compatibility/Compatibility.adoc, local-build-plugins/src/main/java/org/hibernate/orm/post/DialectReportTask.java, local-build-plugins/src/main/java/org/hibernate/orm/post/ReportGenerationPlugin.java, settings.gradle
https://hibernate.atlassian.net/browse/HHH-17259
To test locally:
```shell
./gradlew renderUserGuides
xdg-open documentation/target/asciidoc/userguide/html_single/Hibernate_User_Guide.html
```
The result:
I think there's something wrong with the dialect report, in particular that "GenericDialect" thing, and we might also want to add the name of the relevant databases in the table someday. But those are pre-existing problems, and this, at least, is a start, so I'd just merge it.
=> HHH-17259 Document compatibility constraints in the user guide

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLiteDialect.java
- Added `getAlterTableToAddUniqueKeyCommand()`, which always returns `""`,  because SQLite does not support unique constraints in `ALTER TABLE`  statements (see [here](https://www.sqlite.org/omitted.html)). 
- Added `getDefaultUseGetGeneratedKey()`, which always returns `false`, as the Xerial driver apparently does not support GET_GENERATED_KEYS.
https://hibernate.atlassian.net/browse/HHH-17245
=> HHH-17245 Better conform to SQLite/Xerial driver limitations.

hibernate-core/src/main/java/org/hibernate/id/enhanced/TableGenerator.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/TableStructure.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
backported version, targeting 6.2.10
https://hibernate.atlassian.net/browse/HHH-17220
=> HHH-17220 Avoid runtime lookups of JdbcService from TableGenerator and TableStructure

hibernate-core/src/main/java/org/hibernate/tool/schema/internal/ColumnDefinitions.java
This "fix" is not really strictly-speaking necessary, but it does reduce false positives in a very tiny number of cases.
https://hibernate.atlassian.net/browse/HHH-17233
=> HHH-17233 be a little more forgiving when comparing column types in schema validation

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddableMappingTypeImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/ElementCollectionAllNonOptionalPropertyUpdateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/ElementCollectionAllPrimitivePropertyUpdateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/ElementCollectionNonOptionalPropertyUpdateTest.java
https://hibernate.atlassian.net/browse/HHH-17257 
this should resolve a case the user reported that  https://github.com/hibernate/hibernate-orm/pull/7372 haven't fixed
=> HHH-17257 ElementCollection is missing elements after update if embeddable type has primitive columns marked as nullable

databases/oracle/matrix.gradle, settings.gradle
This PR updates the Oracle JDBC driver to the latest version to date (released on the 2nd of October 2023 on Maven Central).
https://hibernate.atlassian.net/browse/HHH-17286
=> HHH-17286 Upgrade integration tests to use Oracle JDBC driver version 23.3.0.23.09

hibernate-core/src/main/java/org/hibernate/internal/FetchingScrollableResultsImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/StatelessQueryScrollingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/FetchGraphTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/QueryScrollingWithInheritanceProxyEagerManyToOneTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/QueryScrollingWithInheritanceProxyTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/hqlfetchscroll/QueryScrollingWithInheritanceTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/fetching/StatelessSessionFetchingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/stream/NestedCollectionFetchStreamTest.java
https://hibernate.atlassian.net/browse/HHH-17212
=> HHH-17212 Avoid jdbc isBeforeFirst() and isAfterLast() in scrollable results calls when possible

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java, hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/TableGroupJoinProducer.java, hibernate-core/src/test/java/org/hibernate/orm/test/associations/NotFoundTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/notfound/IsNullAndNotFoundTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/notfound/MutationQueriesAndNotFoundActionTest.java
HHH-17143 - Bad handling of not-found association references in mutation queries
https://hibernate.atlassian.net/browse/HHH-17143
=> HHH-17143 - Bad handling of not-found association references in mutation queries

hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/MultiTableSqmMutationConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/DeleteWhereFunctionCallTest.java
https://hibernate.atlassian.net/browse/HHH-16897
Found this while was trying to clean up the workarounds for https://hibernate.atlassian.net/browse/HHH-14814 in Search.
Opening as a draft since its more of a reproducer (I'm not sure that the suggested fix is ok 😃)
=> HHH-16897 Delete query for entity using table-per-class inheritance may result in NullPointerException

hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/TypeDefinition.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotationBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/BasicValueBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingMetadataBuildingOptions.java, hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataBuildingOptions.java, hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java, hibernate-core/src/main/java/org/hibernate/mapping/Component.java, hibernate-core/src/main/java/org/hibernate/mapping/MappingHelper.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/ManagedTypeRepresentationResolverStandard.java, hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java, hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/ComponentMetadataGenerator.java
https://hibernate.atlassian.net/browse/HHH-16935
=> HHH-16935 Fix inconsistent method name

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java
Hibernate Reactive needs to override these methods to implement `setOrder`
Fix https://hibernate.atlassian.net/browse/HHH-17150
=> Remove final from SqmSelectionQueryImpl#setOrder

docker_db.sh
Today Oracle database users for testing/CI have way too much privileges that may have impacts when querying Database Metadata (i.e. seeing tables that should not be seen).
Current set of privileges are enough:
- RESOURCE role
- CREATE VIEW
- CREATE SESSION
- CREATE SYNONYM
- CREATE ANY INDEX (for XMLType tables)
- EXECUTE ANY TYPE (to avoid a grant just after type creation)
For 23c, DB_DEVELOPER_ROLE would be perfect.
https://hibernate.atlassian.net/browse/HHH-17315
=> HHH-17315 Reduce Oracle database user privileges to avoid cross schemas clashes

hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleSqlAstTranslator.java
New Oracle database 23c feature, SELECT queries supports no FROM clause.
Note: DUAL table still exists!
https://hibernate.atlassian.net/browse/HHH-15757
=> HHH-15757 SELECT without FROM

hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
This will make Hibernate support the new Oracle database 23c feature:
- `DROP TABLE IF EXISTS <TABLE_NAME>`  ([documentation](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/DROP-TABLE.html))
- `DROP VIEW IF EXISTS <VIEW_NAME>` ([documentation](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/DROP-VIEW.html))
- `DROP TYPE IF EXISTS <TYPE_NAME>` ([documentation](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/DROP-TYPE.html))
- `ALTER TABLE IF EXISTS <TABLE_NAME>` ([documentation](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/ALTER-TABLE.html))
It should reduce the amount of logged stacktraces...
https://hibernate.atlassian.net/browse/HHH-15754
=> HHH-15754 IF [NOT] EXISTS DDL

.github/hibernate-github-bot.yml
See https://github.com/hibernate/hibernate-github-bot/pull/196
This should avoid pesky Jira-related checks on at least some PRs that blatantly don't need these checks.
=> Ignore JIRA checks for commits targeting only build-related files

migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-17157
I thought this could be useful if anyone else comes to us asking why they this error about missing Antlr classes. WDYT @sebersole ?
=> HHH-17157 More guidance in the migration guide for hibernate-jpamodelgen changes

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
For Hibernate Reactive, it extends the class and needs to be able to call the method.
Fix [HHH-17390](https://hibernate.atlassian.net/browse/HHH-17390) 
[HHH-17390]: https://hibernate.atlassian.net/browse/HHH-17390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Change scope of AbstractEntityInitializer#resolveInstance

hibernate-core/src/main/java/org/hibernate/engine/jdbc/dialect/internal/DialectFactoryImpl.java
Hey hey 😃 
I noticed that this message was suggesting using an older version of properties (`hibernate.connection.url` is deprecated and `javax.persistence.jdbc.url` is no longer 😃)
=> Use jakarta property in message when Dialect cannot be determined

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/version/EntityWithNullVersionAndMapsIdTest.java
https://hibernate.atlassian.net/browse/HHH-17380
=> HHH-17380 Persisting an entity with a non generated id and @MapsId throws PropertyValueException

hibernate-core/src/main/java/org/hibernate/dialect/temptable/StandardTemporaryTableExporter.java
The position argument in `ParameterMarkerStrategy#createMarker` is 1-based, but `StandardTemporaryTableExporter#getSqlTruncateCommand` calls it passing a 0.
Hibernate Reactive is affected by this when running queries on CockroachDB. Hibernate ORM generates queries using `?` as marker and it's not affected by it unless somebody implements the service.
https://hibernate.atlassian.net/browse/HHH-17428
=> ParameterMarkerStrategy markers are 1 based

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/BasicValuedPathInterpretation.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EmbeddableValuedPathInterpretation.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ql/MapIssueTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/LeftJoinNullnessPredicateQueryTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/RightJoinNullnessPredicateQueryTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/exec/onetoone/bidirectional/EntityWithBidirectionalAssociationsOneOfWhichIsAJoinTableTest.java
https://hibernate.atlassian.net/browse/HHH-17379
https://hibernate.atlassian.net/browse/HHH-17397
=> HHH-17379, HHH-17397 Correct use of target table column for non-optimizable joins

hibernate-core/src/main/java/org/hibernate/tool/schema/internal/ColumnDefinitions.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemavalidation/DurationValidationTest.java
https://hibernate.atlassian.net/browse/HHH-17293
PostgreSQL returns `interval` and not `interval second` as type name.
=> HHH-17293 Schema validation fails on postgres interval seconds type

README.adoc, settings.gradle
- Updated Revved up by Gradle Enterprise badge to say Revved up by Develocity (after GE -> Develocity rename)
- Bumped Gradle Enterprise and Common Custom User Data plugins to latest versions
- Updated build cache config to only push when authenticated
https://hibernate.atlassian.net/browse/HHH-17551
=> HHH-17551 Gradle enterprise update 

shared/javadoc/overview.html
- fix the link to JPA Javadoc
- list of important JPA APIs
=> update the Javadoc overview

hibernate-core/src/main/java/org/hibernate/dialect/OracleServerConfiguration.java
According to https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/SYS_CONTEXT.html#GUID-B9934A5D-D97B-4E51-B01B-80C76A5BD086
>> Returns DWCS on autonomous database management systems (ADW), OLTP on autonomous transaction processing systems (ATP), and JDCS on autonomous JSON database systems.
https://hibernate.atlassian.net/browse/HHH-17570
=> HHH-17570 Fix wrong name when checking Oracle autonomous JSON database

documentation/src/main/asciidoc/userguide/chapters/domain/embeddables.adoc, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableResultImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/OneToManyInEmbeddedQueryTest.java
https://hibernate.atlassian.net/browse/HHH-17528
This introduces a check to explicitly disallow explicit selection of an embeddable type that contains collections.
=> HHH-17528 Explicit selection of an @Embeddable property containing associated collections doesn't work

hibernate-envers/src/main/java/org/hibernate/envers/internal/revisioninfo/DefaultRevisionInfoGenerator.java
Please refer to the following bug: 
https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues/HHH-16881
I think that this PR should be backported to 6.2 and 6.3 also.
I don't find the test regarding this behavior, so I haven't included new one, but you can test using the demo that I provide in the bug.
=> HHH-16881 - RevisionListener is not created when Hibernate CDI Extensions are enabled

hibernate-core/src/test/java/org/hibernate/orm/test/hql/joinedSubclass/JoinedSubclassNativeQueryTest.java
Hi,
not sure how to do PRs against this repository, but at least here's the code, feel free to use it any way you like
Note: I tested with ./gradlew hibernate-core:test --tests 'JoinedSubclassNativeQueryTest'
without the "null as companyName", I get the org.hibernate.exception.SQLGrammarException: Unable to find column position by name: companyName [Column "companyName" not found [42122-220]] [n/a]
with it the test passes
https://hibernate.atlassian.net/browse/HHH-17303
=> Improve testJoinedInheritanceNativeQuery to operate on an entity with actual inheritance

hibernate-core/src/main/java/org/hibernate/metamodel/internal/EntityRepresentationStrategyPojoStandard.java, hibernate-core/src/test/java/org/hibernate/orm/test/proxy/ProxyWithGenericsTest.java
This occurs when trying to call a method on a HibernateProxy where the parameter type is defined by generics/class hierarchy.
Courtesy of Oliver Henly.
https://hibernate.atlassian.net/browse/HHH-17578
=> HHH-17578 - Fix intermittent ClassCastException 

.mailmap
This is a hidden metadata file which is very handy as it is taken into account by several (but not all, and sometimes an opt-in flag needs to be specified) git commands.
It's particularly useful to reports and stats; it will better understand, for example that `Steve Ebersole <steve@hibernate.org>` and `Steve Ebersole <steve@apollo.(none)>` are the same person, and many more such cases which are either small mistakes or people who simply changed preferred names / address.
Thanks @yrodiere for the suggestion ! It's been really useful.
@hibernate/orm-dev agreable to merge?  I don't expect this to be perfectly maintained, but it's been very useful even when it's not perfect and I think it will again.
An example git command, if you want to try it out:
git shortlog -n -s -e
Try this w/o the …
=> Adding a .mailmap mapping configuration for contributor's metadata

hibernate-core/src/main/java/org/hibernate/type/descriptor/java/CurrencyJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/YearJavaType.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/CurrencyMappingTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/type/java/YearMappingTests.java
- removed util class that was used for WrapperOptions
- fixed unwrap() metod in CurrencyJavaType
- unwrap() was already ok in YearJavaType
- fixed existing tests to avoid usage of (removed) util class in both CurrencyMappingTests and YearMappingTests
- added few new tests to test unwrap() method in both CurrencyMappingTests and YearMappingTests
https://hibernate.atlassian.net/browse/HHH-17507
https://hibernate.atlassian.net/browse/HHH-17574
=> HHH-17507 HHH-17574 Fixed wrap() & unwrap() & updated unit tests

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/UnionSubclassEntityPersister.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/ManyToOneInheritanceSubTypeTest.java
https://hibernate.atlassian.net/browse/HHH-17483
=> HHH-17483 Nested subtypes filtered out in bidirectional OneToMany association load

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultRefreshEventListener.java, hibernate-core/src/test/java/org/hibernate/orm/test/locking/LockRefreshReferencedTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/proxy/ProxyTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/readonly/ReadOnlyProxyTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/readonly/ReadOnlySessionTest.java
https://hibernate.atlassian.net/browse/HHH-1645
https://hibernate.atlassian.net/browse/HHH-17395
=> HHH-17395 Refresh with PESSIMISTIC_WRITE ignored for lazy loaded entity HHH-1645 refresh with LockMode on an unitialized proxy does not work

ci/quarkus.Jenkinsfile, hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/EnumeratedValueResolution.java, hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/InferredBasicValueResolver.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractDomainPath.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/FkDomainPathContinuation.java, hibernate-core/src/main/java/org/hibernate/type/EnumType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/converter/internal/NamedEnumValueConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/EnumSingleCharTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/orderby/OrderByToOneTest.java
https://hibernate.atlassian.net/browse/HHH-17623
https://hibernate.atlassian.net/browse/HHH-17106
=> 6.2 backports

hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/SharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/AbstractStatefulStatelessFilterTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/CriteriaQueryWithAppliedFilterTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/FilterDotNameTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/FilterParameterTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/OneToManyWithDynamicFilterTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/hql/BasicFilteredBulkManipulationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/hql/JoinedFilteredBulkManipulationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/secondarytable/SecondaryTableTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/subclass/MappedSuperclass/FilterInheritanceTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/subclass/SubClassTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/subclass/joined/JoinedSubClassTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/subclass/joined2/JoinedInheritanceFilterTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/subclass/singletable/SingleTableDefaultSchemaFilterTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/subclass/singletable/SingleTableInheritanceFilterTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/subclass/singletable/SingleTableTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/subclass/tableperclass/TablePerClassTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/tenantid/TenantIdTest.java
I've moved the multitenancy configuration in the first commit and then noticed that filters are not exposed through `StatelessSession` so I've moved a few filter-related methods to `SharedSessionContract` in the next commit. 
if both changes make sense, I'll create JIRAs for both and update the messages.
https://hibernate.atlassian.net/browse/HHH-17620
https://hibernate.atlassian.net/browse/HHH-17619
=> HHH-17619/HHH-17620 Stateless session multi tenancy + filters

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/GeneratorNotAppliedToIdEmbeddableFieldsShouldThrowAnExceptionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/GeneratorNotAppliedToIdFieldsShouldThrowAnExceptionTest.java
https://hibernate.atlassian.net/browse/HHH-17653
before 6.4.0 Hibernate just silently ignored `@GeneratedValue` applied to a fields not belonging to an identifier, but after the changes made for https://hibernate.atlassian.net/browse/HHH-15074 if a field of an embeddable is annotatted with `@GeneratedValue` the strategy is applied to the entity identifier that contains the embeddable.
My change log a warning not only for this use case but every time a non id property is annotated with `@GeneratedValue`.
=> HHH-17653 Error in generating schema when @Generator annotation is applied to a non id embeddable property 

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/GeneratorNotAppliedToIdEmbeddableFieldsShouldThrowAnExceptionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/GeneratorNotAppliedToIdFieldsShouldThrowAnExceptionTest.java, migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-17653
backport of https://github.com/hibernate/hibernate-orm/pull/7719 with a note of the change in the [migration guide](https://github.com/hibernate/hibernate-orm/pull/7720/files#diff-8cdbb5170b6040e0f492f90f3b66b0e2db3822d08e2d9d06ba98ab359bfce705R79)
=> HHH-17653 Error in generating schema when @Generator annotation is applied to a non id embeddable property

hibernate-core/src/main/java/org/hibernate/resource/beans/internal/BeansMessageLogger.java
Also, removed a constant and a method: both unused.
https://hibernate.atlassian.net/browse/HHH-17659
=> HHH-17659 Review default logging verbosity of BeansMessageLogger

hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetoone/JoinColumnTest.java
https://hibernate.atlassian.net/browse/HHH-17420
Not sure this is a good solution, but not able to find a better one. The issue occurs when binding [midEntity](https://github.com/hibernate/hibernate-orm/pull/7728/files#diff-1af5497bc6094fadc87d89a1c72517b1fa6960ea472121edfd2ae631bc529d18R97)
in the `MidEntity` ,the [aLeftEntity](https://github.com/hibernate/hibernate-orm/pull/7728/files#diff-1af5497bc6094fadc87d89a1c72517b1fa6960ea472121edfd2ae631bc529d18R79) property is processed before all the other properties and has 2 `Selectable` matching the Join columns of `midEntity` , this causes `https://github.com/hibernate/hibernate-orm/pull/7728/files#diff-1367dbe77e6fa4e6ae9a25e199b858cea584e7aa3db83d2fd37ab31072a07526L496`.
=> HHH-17420 JoinColumn throws an `occurs out of order` AnnotationException

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/EntityTableMapping.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateValuesAnalysis.java, hibernate-core/src/main/java/org/hibernate/sql/model/TableMapping.java, hibernate-core/src/main/java/org/hibernate/sql/model/internal/OptionalTableUpdate.java, hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/OptionalTableUpdateOperation.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/secondarytable/SecondaryTableDynamicUpateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/secondarytables/SecondaryTableDynamicUpateTest.java
backport of https://hibernate.atlassian.net/browse/HHH-17587 to 6.4
=> HHH-17587 Setting to null a property from a @SecondaryTable and @DynamicUpdate deletes the whole entry from database

hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/ColumnReference.java
`getExpressionText()` already contains `qualifier`
https://hibernate.atlassian.net/browse/HHH-17707
=> HHH-17707 Improve ColumnReference.toString() to remove repeated qualifier

Jenkinsfile, gradle/java-module.gradle, hibernate-core/hibernate-core.gradle, tooling/metamodel-generator/hibernate-jpamodelgen.gradle
The hope is that whenever we add a new JDK version to test, we'll notice this setting, will try to remove it and upgrade bytebuddy if necessary. This would avoid mess-ups like the one that caused https://github.com/hibernate/hibernate-orm/pull/7790
=> Move setting of net.bytebuddy.experimental to the Jenkinsfile

hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaTransactionAdapterTransactionManagerImpl.java
Why was this empty?
Let's see if this immediately breaks something...
https://hibernate.atlassian.net/browse/HHH-17716
=> HHH-17716 implement JtaTransactionAdapterTransactionManagerImpl.setTimeOut()

Jenkinsfile, gradle/java-module.gradle, hibernate-core/hibernate-core.gradle, tooling/metamodel-generator/hibernate-jpamodelgen.gradle
The hope is that whenever we add a new JDK version to test, we'll notice this setting, will try to remove it and upgrade bytebuddy if necessary. This would avoid mess-ups like the one that caused https://github.com/hibernate/hibernate-orm/pull/7790
Backport of #7792 to branch 6.4
=> Backport to branch 6.4: Move setting of net.bytebuddy.experimental to the Jenkinsfile

hibernate-core/src/main/java/org/hibernate/boot/model/process/spi/MetadataBuildingProcess.java, hibernate-core/src/main/java/org/hibernate/dialect/AbstractPostgreSQLStructJdbcType.java, hibernate-core/src/main/java/org/hibernate/dialect/JsonHelper.java, hibernate-core/src/main/java/org/hibernate/dialect/XmlHelper.java, hibernate-core/src/main/java/org/hibernate/internal/util/config/ConfigurationHelper.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/TypecheckUtil.java, hibernate-core/src/main/java/org/hibernate/type/SqlTypes.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/DurationJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/internal/JdbcTypeBaseline.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/ConvertedAttributesTypecheckTest.java
https://hibernate.atlassian.net/browse/HHH-17693
=> HHH-17693 Cannot use 'like' operand when an AttributeConverter is used to convert the attribute in a String

docker_db.sh
This should fix currently failing PostgreSQL GH Action (see e.g. [this run](https://github.com/hibernate/hibernate-orm/actions/runs/7865338629/job/21458153080)) due to aborting db startup when installing the `pgvector` package through `apt`.
=> Fix failing PostgreSQL GH Actions check

hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/query/internal/NamedObjectRepositoryImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryInterpretationCacheDisabledImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryInterpretationCacheStandardImpl.java, hibernate-core/src/main/java/org/hibernate/query/spi/HqlInterpretation.java, hibernate-core/src/main/java/org/hibernate/query/spi/QueryInterpretationCache.java, hibernate-core/src/main/java/org/hibernate/query/spi/SimpleHqlInterpretationImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java
and delete a deprecated method of an @Incubating API
=> make HqlInterpretation generic to eliminate warnings / unchecked casts

hibernate-core/src/main/java/org/hibernate/engine/jdbc/BlobProxy.java, hibernate-core/src/test/java/org/hibernate/engine/jdbc/BlobProxyTest.java
This causes NegativeArraySizeException: -1294967296 when Blob contents > 2Gb
https://hibernate.atlassian.net/browse/HHH-17770
=> HHH-17770: Avoid casting long to int

tooling/metamodel-generator/hibernate-jpamodelgen.gradle, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/Context.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/JPAMetaModelEntityProcessor.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractQueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/CriteriaFinderMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/QueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/Constants.java, tooling/metamodel-generator/src/quarkusHrPanache/java/org/hibernate/jpamodelgen/test/hrPanache/BookRepositoryWithSession.java, tooling/metamodel-generator/src/quarkusHrPanache/java/org/hibernate/jpamodelgen/test/hrPanache/PanacheBook.java, tooling/metamodel-generator/src/quarkusHrPanache/java/org/hibernate/jpamodelgen/test/hrPanache/PanacheBookRepository.java, tooling/metamodel-generator/src/quarkusHrPanache/java/org/hibernate/jpamodelgen/test/hrPanache/QuarkusBookRepository.java, tooling/metamodel-generator/src/quarkusHrPanache/java/org/hibernate/jpamodelgen/test/hrPanache/QuarkusHrPanacheTest.java, tooling/metamodel-generator/src/quarkusOrmPanache/java/org/hibernate/jpamodelgen/test/ormPanache/PanacheBook.java, tooling/metamodel-generator/src/quarkusOrmPanache/java/org/hibernate/jpamodelgen/test/ormPanache/PanacheBookRepository.java, tooling/metamodel-generator/src/quarkusOrmPanache/java/org/hibernate/jpamodelgen/test/ormPanache/QuarkusBookRepository.java, tooling/metamodel-generator/src/quarkusOrmPanache/java/org/hibernate/jpamodelgen/test/ormPanache/QuarkusOrmPanacheTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/util/CompilationRunner.java, tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/util/CompilationStatement.java, tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/util/CompilationTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/util/TestUtil.java
Please @gavinking can you review this?
- Support ORM/HR+Panache types such as anything that extends `PanacheEntityBase` or `PanacheRepositoryBase` to make sure to use their session getter type, but never generate a DAO because Quarkus will call the generated static methods. Also support annotations on `native` methods.
- Support `Uni<Mutiny.Session>` session types
- Support session getters with a default implementation, in which case never store the session in a field but always call the getter. This is mostly because reactive sessions can't be stored in a CDI context and need to be obtained for each call.
- Fix update/delete method return types that have to return `Uni<Integer|Void>` for HR
- When ORM/HR+Panache is detected, for types that are _not_ Panache entities or repositories, …
=> Jpamodelgen fixes for panache

hibernate-core/src/main/java/org/hibernate/binder/AttributeBinder.java, hibernate-core/src/main/java/org/hibernate/binder/TypeBinder.java, hibernate-core/src/main/java/org/hibernate/engine/spi/ExecuteUpdateResultCheckStyle.java, hibernate-core/src/main/java/org/hibernate/mapping/Join.java, hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java, hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/UnionSubclassEntityPersister.java, hibernate-core/src/main/java/org/hibernate/query/package-info.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/attributebinder/typebinder/NoResultCheck.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/attributebinder/typebinder/ResultCheckBinderTest.java
This was already possible, but not very comfortable when not also setting custom SQL.
https://hibernate.atlassian.net/browse/HHH-9110
=> HHH-9110 make it easier to set ResultCheckType from TypeBinder

hibernate-core/src/main/java/org/hibernate/dialect/unique/CreateTableUniqueDelegate.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/uniqueconstraint/MultiUniqueConstraintNameTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/uniqueconstraint/UniqueConstraintNameTest.java
Note that HHH-17132 and PR #7376 already attempted to fix the reported problem, but the fix introduced a new bug, an NPE.
https://hibernate.atlassian.net/browse/HHH-17825
=> HHH-17825 fix npe for single-column @UniqueConstraint

hibernate-core/src/main/java/org/hibernate/annotations/ResultCheckStyle.java, hibernate-core/src/main/java/org/hibernate/annotations/SQLDelete.java, hibernate-core/src/main/java/org/hibernate/annotations/SQLDeleteAll.java, hibernate-core/src/main/java/org/hibernate/annotations/SQLInsert.java, hibernate-core/src/main/java/org/hibernate/annotations/SQLUpdate.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/engine/spi/ExecuteUpdateResultCheckStyle.java, hibernate-core/src/main/java/org/hibernate/jdbc/Expectation.java, hibernate-core/src/main/java/org/hibernate/jdbc/Expectations.java, hibernate-core/src/main/java/org/hibernate/mapping/Collection.java, hibernate-core/src/main/java/org/hibernate/mapping/Join.java, hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java, hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/UnionSubclassEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/size/WhereClauseOrderBySizeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/attributebinder/typebinder/NoResultCheck.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/CustomSQLTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/write/CustomSqlWithExpectationTests.java
Use of class objects is simpler, more elegant, and more flexible.
https://hibernate.atlassian.net/browse/HHH-15587
=> HHH-15587 replace use of enums for specifying Expectations

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/flush/NonTransactionalDataAccessTest.java
Please check https://discourse.hibernate.org/t/jakarta-persistence-transactionrequiredexception-on-query-modifying-and-transactional-methods/9042
https://hibernate.atlassian.net/browse/HHH-17743
=> HHH-17743 Allow updates outside transaction

hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcCoordinatorImpl.java
https://hibernate.atlassian.net/browse/HHH-9482
=> HHH-9482 - Avoid automatic timing out when requested timeout is 1 second

.github/hibernate-github-bot.yml, Jenkinsfile, gradle/gradle-enterprise.gradle
Oddly, it seems the build cache and, more annoyingly, build scans, were not enabled in the Jenkinsfile. So this fixes that. Note that for pull requests, we use a different access key which is not able to push to the build cache -- for security reasons.
Also, this enables a new feature in hibernate-github-bot that basically adds a GitHub check next to the existing ones for GitHub Actions or Jenkins, and inside that check is a list of build scans, along with some context (tags, ...).
Note this works best when build scans are tagged properly, e.g. you add a `postgresql` tag to CI runs against postgresql. So I adjusted GitHub Actions workflows and the Jenkinsfile accordingly.
See https://github.com/hibernate/hibernate-github-bot/pull/227
=> Enable build scans and build cache in Jenkinsfile and list build scans in a GitHub check

hibernate-testing/src/main/java/org/hibernate/testing/jta/JtaAwareConnectionProviderImpl.java
Tests were re-using the `JtaAwareConnectionProviderImpl#ConnectionWrapper` object, preventing `ResourceRegistry` from correctly clearing resources.
=> Prevent caching JtaAwareConnectionProviderImpl wrapped Connections

tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java
=> let a handwritten metamodel "override" the generated one

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/AbstractSqmSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/KeyedResult.java
It was returning the results in reverse order. This caused a failure in the Data TCK.
=> fix previous-page navigation with KeyedResultList

hibernate-core/src/main/java/org/hibernate/result/internal/OutputsImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/DeferredResultSetAccess.java, hibernate-core/src/test/java/org/hibernate/orm/test/connections/ConnectionCloseAfterStatementTest.java
https://hibernate.atlassian.net/browse/HHH-17887
when `logicalConnection.afterStatement();` is called before releasing the executed `Statement` from the `ResourceRegystry` the check in the `LogicalConnectionManagedImpl` is executed
```
if ( connectionHandlingMode.getReleaseMode() == AFTER_STATEMENT ) {
if ( getResourceRegistry().hasRegisteredResources() ) {
log.debug( "Skipping aggressive release of JDBC Connection after-statement due to held resources" );
}
else {
log.debug( "Initiating JDBC connection release from afterStatement" );
releaseConnection();
}
}
```
but the `getResourceRegistry().hasRegisteredResources() ` returns `true` then the connection is not released.
=> HHH-17887 Release mode After Statment with deferred result set access does not work

hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/delegate/GeneratedWritableDelegateTest.java
https://hibernate.atlassian.net/browse/HHH-10921
Add a test case that demonstrates how one can use `@Generated( writable = true )` to retrieve on-execution generated values efficiently.
=> Test case for HHH-10921 - Support generated values via returning clause

hibernate-core/src/main/java/org/hibernate/tool/schema/internal/ColumnDefinitions.java
1. MySQL returns `int` even `integer` is specified
2. H2 returns `character large object` and `binary large object` even `clob` and `blob` is specified
=> Add more type name alias mappings

hibernate-core/src/main/java/org/hibernate/type/SqlTypes.java
=> Fix SqlTypes::isStringType

.github/workflows/atlas.yml, .github/workflows/contributor-build.yml, Jenkinsfile, nightly.Jenkinsfile
This PR:
* Makes sure that the Jenkins pipeline won't execute for PRs of external contributors until it's been approved. No approval is needed for members of the Hibernate organization.
* Makes sure that secrets are exposed only to build steps that really need them, and in particular not to the actual build
* Changes the GitHub actions build to use the `pull_request_target` event instead of `pull_request`, to have access to secrets, while still checkout out the PR head. This is a bit dodgy but safe if we're careful, see comments. More importantly this is strictly equivalent to what we're doing on Jenkins.
* Adds publication of build scans to both the GitHub Actions build and the Jenkins build.
For Jenkins, the approval screen (using BlueOcean) will look like this:
Note we'll need to merge …
=> Require approval for Jenkins builds on PRs from external contributors + Safely publish build scans even for pull requests

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/IdFinderMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/LifecycleMethod.java
SS does not do exception translation, so we need to catch native Hibernate exceptions instead.
=> fix exceptions thrown from JD lifecycle method

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/EnhancementAsProxyLazinessInterceptor.java, hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/spi/EntityHolder.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java, hibernate-core/src/test/java/org/hibernate/orm/test/caching/CachingBatchLoadNoProxiesAndCircularRelationshipTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/manytoone/ManyToOneBidirectionalEagerTest.java
https://hibernate.atlassian.net/browse/HHH-17783
https://hibernate.atlassian.net/browse/HHH-17918
Alternative solution to #8110, including the reproducer kindly provided by @gtoison in #8136.
=> HHH-17783, HHH-17918 - Allow early initialization of entity instance by non-owning initializer

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/EnhancerConstants.java, hibernate-core/src/main/java/org/hibernate/bytecode/internal/BytecodeEnhancementMetadataPojoImpl.java, hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java, hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryContext.java, hibernate-core/src/main/java/org/hibernate/engine/internal/ManagedTypeHelper.java, hibernate-core/src/main/java/org/hibernate/engine/spi/ManagedEntity.java, hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/version/SimpleEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/basic/BasicSessionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/merge/MergeEnhancedEntityDynamicUpdateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/merge/MergeEnhancedEntityTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/cache/ByteCodeEnhancedImmutableReferenceCacheTest.java
https://hibernate.atlassian.net/browse/HHH-17761
6.5 Backport
=> HHH-17761 Merging a bytecode enhanced entity with all properties set to null does not apply the update

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SybaseDialect.java, hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/InformationExtractorJdbcDatabaseMetaDataImpl.java
This should fix 
- org.hibernate.orm.test.schemaupdate.ColumnNamesTest.testSchemaUpdateWithQuotedColumnNames
- org.hibernate.orm.test.schemaupdate/ColumnNamesTest
- org.hibernate.orm.test.schemaupdate.SchemaUpdateWithUseJdbcMetadataDefaultsSettingToFalseAndQuotedNameTest
- org.hibernate.orm.test.schemaupdate.SchemaUpdateWithUseJdbcMetadataDefaultsSettingToFalseTest
when using sybase jconnect driver
=> Fix SybaseASEDialect column lenght resolution

.github/workflows/atlas.yml, .github/workflows/contributor-build.yml, ci/snapshot-publish.Jenkinsfile, gradle/gradle-develocity.gradle, settings.gradle
A followup on https://github.com/hibernate/hibernate-orm/pull/8121 (we've noticed the warnings in Search build and made changes here https://github.com/hibernate/hibernate-search/commit/ff7621bf1952a2f85103a7937a3884a512325b80) and after looking at the ORM build logs -- there's similar warnings there too 🙈 
With 3.17 env variable `GRADLE_ENTERPRISE_ACCESS_KEY` is deprecated and the config changed a bit:
https://docs.gradle.com/enterprise/gradle-plugin/legacy/#develocity_migration
I've also added IP obfuscation.
=> Update Develocity build scan configuration

hibernate-core/src/main/java/org/hibernate/engine/jdbc/Size.java, hibernate-core/src/main/java/org/hibernate/type/AbstractType.java
IMO It doesn't make much sense, `n*1024*1024` is more simple and intuitional.
https://hibernate.atlassian.net/browse/HHH-17951
=> HHH-17951 Deprecate unused Size.LobMultiplier

hibernate-core/src/main/java/org/hibernate/Session.java
yes, these methods actually do still accept detached objects as of today, but that's already deprecated and we're going to turn it off in the future
=> make javadoc consistent

hibernate-envers/src/main/java/org/hibernate/envers/internal/revisioninfo/RevisionTimestampValueResolver.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/revfordate/RevisionForDate.java
In case the revision timestamp is persisted as a long (i.e. a unix timestamp with millisecond precision) and the request to resolve a revision is made with an object of type `Instant`, the resulting parameter is returned as a unix timestamp with seconds precision instead of the expected milliseconds. This leads to (usually) not finding any revisions.
This PR fixes this path to work the same as the case in line 85 where the call is made with an object of type `LocalDateTime`.
https://hibernate.atlassian.net/browse/HHH-17975
=> Fix RevisionTimestampValueResolver to provide correct precisision for Instants

docker_db.sh
6.4 backport of https://github.com/hibernate/hibernate-orm/pull/8099
=> Upgrade docker mssql image to 2022-CU12-ubuntu-22.04

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/ByteBuddyEnhancementContext.java
This is the first patch on a series, motivated by the analysis of bootstrap times using https://github.com/topicusonderwijs/tribe-krd-quarkus.
https://hibernate.atlassian.net/browse/HHH-17980
This patch in isolation will not dramatically improve things, as contention is currently quite low - however this lock becomes a problem as other bottlenecks are resolved. I'm resolving the other bottlenecks via a combination of patches on the Quarkus side and other improvements coming on the ORM side.
Not all improvements on the ORM side will be suitable for pre-7 versions, still I'd apply this one on 6.5+ as well as the combination of improvements on 6.5 is still meaningful enough to make this lock problematic.
=> HHH-17980 Excessive contention during getter identification in the ByteBuddy enhancer

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmAttributeJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmFrom.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/AbstractSqmSelectQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectStatement.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSubQuery.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CountQueryTests.java
- Add test for issue (already fixed on main)
- Backport the minimal necessary bits of HHH-16931 and https://github.com/hibernate/hibernate-orm/pull/7883 to fix the NPE
https://hibernate.atlassian.net/browse/HHH-17967
=> HHH-17967 - NullPointerException

Jenkinsfile, ci/jpa-3.1-tck.Jenkinsfile, ci/release/Jenkinsfile, ci/snapshot-publish.Jenkinsfile, nightly.Jenkinsfile
Mainly to improve tracing in case `requireApprovalForPullRequest` doesn't work properly, but also simply to keep things up to date.
https://github.com/hibernate/hibernate-jenkins-pipeline-helpers/compare/1.9...1.11 https://github.com/hibernate/hibernate-jenkins-pipeline-helpers/compare/1.5...1.11
=> Upgrade to hibernate-jenkins-pipeline-helpers 1.11

.github/hibernate-github-bot.yml, Jenkinsfile, nightly.Jenkinsfile
1. Rename some env variables to remove a few warnings
2. Enable build scans in night Jenkins jobs (for some reason there were not enabled there)
3. Improve the format of the report
Regarding the report, here's what it looks like before recent changes to the bot, and before this patch:
And here's what it could looks like after the patch (example with Hibernate Search):
=> Develocity reports improvements

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-18035
=> HHH-18035 Change Oracle default timestamp precision to 9

hibernate-core/src/main/java/org/hibernate/type/descriptor/java/JdbcDateJavaType.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/descriptor/java/JdbcDateJavaTypeDescriptorTest.java
https://hibernate.atlassian.net/browse/HHH-18036
=> HHH-18036 Truncate time-related milliseconds when creating a java.sql.Date

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/ByteBuddyEnhancementContext.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/CoreTypePool.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerClassLocator.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImplConstants.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/ModelTypePool.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/OverridingClassFileLocator.java, hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java, hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java
This PR might look scary, but let me break it down. Best to look at the first commit in isolation.
**CoreTypePool** and **ModelTypePool** are two new types, however they are essentially an extension of the ByteBuddy core type pool with some additional caching capabilities.
There are two of them as the strategies we want to use are best kept different, so I created different types to best represent their purpose - and to benefit from typesafety in regards to which one needs to be used in each case.
The main difference is that CoreTypePool is meant to cache introspection of JDK classes and mapping annotations: these are classes which are allowed to be loaded, so we refer to their actual java Class which is slightly more efficient. For all other classes however we force to parse the bytecode …
=> HHH-18011 Parallel entity enhancement causes a classloader cache stampede

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/ByteBuddyEnhancementContext.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/CoreTypePool.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerClassLocator.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImplConstants.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/ModelTypePool.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/OverridingClassFileLocator.java, hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java, hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java
Backport of #8263
https://hibernate.atlassian.net/browse/HHH-18011
=> HHH-18011 Parallel entity enhancement causes a classloader cache stampede [6.5]

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DerbyLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DerbyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
https://hibernate.atlassian.net/browse/HHH-18018
=> HHH-18018 Use NO_PLAIN_PARAMETER for Derby functions that use the length function

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java, migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-18043
=> HHH-18043 Change SQL Server default timestamp precision to 7

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2LegacyDialect.java, hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/OracleTruncFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/PostgreSQLTruncRoundFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/SumReturnTypeResolver.java, hibernate-core/src/main/java/org/hibernate/dialect/function/TransactSQLStrFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/TrimFunction.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/BlobJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/ClobJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/NClobJdbcType.java, hibernate-core/src/test/java/org/hibernate/orm/test/nationalized/MaterializedNClobBindTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/descriptor/sql/StringValueMappingTest.java
https://hibernate.atlassian.net/browse/HHH-18020
=> HHH-18020 Align behavior of ClobJdbcType with BlobJdbcType

documentation/src/main/asciidoc/querylanguage/Expressions.adoc, documentation/src/main/asciidoc/querylanguage/Relational.adoc, documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc, hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
Fix duration arithmetic involving fractional seconds on databases where `dateadd(second, ... )` truncates.
https://hibernate.atlassian.net/browse/HHH-18053
=> HHH-18053  duration arithmetic involving fractional seconds

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityAssociationMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractEntityCollectionPart.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ManyToManyCollectionPart.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/BasicValuedPathInterpretation.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EmbeddableValuedPathInterpretation.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQuerySpec.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ql/MapIssueTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/ManyToManyGroupByOrderByTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/exec/onetoone/bidirectional/EntityWithBidirectionalAssociationsOneOfWhichIsAJoinTableTest.java
https://hibernate.atlassian.net/browse/HHH-17837
=> HHH-17837 Join + GroupBy: Wrong column used for many-to-many association

hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CollectionEntry.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultInitializeCollectionEventListener.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderNamedQuery.java, hibernate-core/src/main/java/org/hibernate/sql/results/internal/ResultsHelper.java
and code cleanups
(Note that this typecast has actually been there since 2012, though it only used to happen when batching was enabled.)
https://hibernate.atlassian.net/browse/HHH-18067
=> HHH-18067 get rid of a typecast to AbstractPersistentCollection

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/version/TablePerClassAbstractRootTypeVersionUpdateTest.java
https://hibernate.atlassian.net/browse/HHH-17834
=> HHH-17834 lock(e, OPTIMISTIC_FORCE_INCREMENT) with TABLE_PER_SUBCLASS

hibernate-core/src/main/java/org/hibernate/type/descriptor/java/JdbcTimeJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/LocalTimeJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/OffsetTimeJavaType.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/descriptor/java/JdbcTimeJavaTypeDescriptorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/descriptor/java/LocalTimeJavaTypeDescriptorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/descriptor/java/OffsetTimeJavaTypeDescriptorTest.java
https://hibernate.atlassian.net/browse/HHH-17229
=> HHH-17229 Test and fix for handling negative milliseconds from java.sql.Time

hibernate-core/src/main/java/org/hibernate/annotations/processing/Exclude.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetoone/ShowDescription.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/Context.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/Constants.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/includeexclude/Bar.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/includeexclude/Baz.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/includeexclude/Foo.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/includeexclude/IncludeExcludeTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/util/WithProcessorOption.java
and rename `@Suppress` -> `@Exclude`
=> introduce include/exclude options for HibernateProcessor

hibernate-core/src/main/java/org/hibernate/event/spi/PostActionEventListener.java, hibernate-core/src/main/java/org/hibernate/integrator/spi/Integrator.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/LoadEntityWithElementCollectionTest.java
default impls for:
- `Integrator.disintegrate()`
- `PostActionEventListener.requiresPostCommitHandling()`
=> a couple of small optimizations to writing Integrators

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/pagination/IngresLimitHandler.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/pagination/RowsLimitHandler.java, hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/IngresLimitHandlerTest.java, hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/RowsLimitHandlerTest.java, hibernate-core/src/main/java/org/hibernate/dialect/pagination/AbstractLimitHandler.java, hibernate-core/src/main/java/org/hibernate/dialect/pagination/DerbyLimitHandler.java, hibernate-core/src/main/java/org/hibernate/dialect/pagination/LimitLimitHandler.java, hibernate-core/src/main/java/org/hibernate/dialect/pagination/Oracle12LimitHandler.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/AbstractLimitHandlerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/DB2LimitHandlerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/DerbyLimitHandlerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/LimitLimitHandlerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/OffsetFetchLimitHandlerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/Oracle12LimitHandlerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/QueryTest.java
https://hibernate.atlassian.net/browse/HHH-18033
=> HHH-18033 Fix LimitHandler detect wrong statement end if sql contains quoted semicolon

hibernate-core/src/main/java/org/hibernate/query/hql/internal/BasicDotIdentifierConsumer.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/ProcessorSessionFactory.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/constant/BadEnumConstantInNamedQueryTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/constant/BookType.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/constant/CookBook.java
See Jira issue [HHH-18102](https://hibernate.atlassian.net/browse/HHH-18102)
Method `org.hibernate.processor.validation.MockSessionFactory.MockJpaMetamodelImpl#enumValue` is not checking for enum value existence
[HHH-18102]: https://hibernate.atlassian.net/browse/HHH-18102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HHH-18102 - @CheckHQL is not reporting error when non-existing enum constant is referenced in named HQL query

hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardTableExporter.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/tableoptions/TableOptionsTest.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java
removed `Dialect#supportsTableOptions`
https://hibernate.atlassian.net/browse/HHH-18056
=> HHH-18056 Support for JPA 32 table options

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedColumn.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedDiscriminatorColumn.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedJoinColumn.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ColumnsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/IndexColumn.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/ManagedTypeProcessor.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/XmlAnnotationHelper.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/db/JoinColumnProcessing.java, hibernate-core/src/main/java/org/hibernate/mapping/Column.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/ColumnDefinitions.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/columnoptions/AnotherTestEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/columnoptions/ColumnOptionsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/columnoptions/TestEntity.java, hibernate-core/src/test/resources/org/hibernate/orm/test/schemaupdate/columnoptions/TestEntity.xml
https://hibernate.atlassian.net/browse/HHH-18057
=> HHH-18057 Support for JPA 3.2 column options

hibernate-testing/src/main/java/org/hibernate/testing/env/ConnectionProviderBuilder.java
Hey 😃 
We are using this `ConnectionProviderBuilder` in Search tests and in those cases, we usually have database settings coming from a Junit extension, which may be too late as `Environment.getProperties()` are already initialized. These changes would allow us to pass the settings from an extension into this builder. 
Let me know if it makes sense to apply this, or if maybe you have other suggestions on how we can address the problem at hand 😃.
=> Provide a way to override global env properties in a test ConnectionProviderBuilder

hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/action/internal/EntityVerifyVersionProcess.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/lock/AbstractSelectLockingStrategy.java, hibernate-core/src/main/java/org/hibernate/dialect/lock/OptimisticForceIncrementLockingStrategy.java, hibernate-core/src/main/java/org/hibernate/dialect/lock/PessimisticReadSelectLockingStrategy.java, hibernate-core/src/main/java/org/hibernate/dialect/lock/PessimisticWriteSelectLockingStrategy.java, hibernate-core/src/main/java/org/hibernate/dialect/lock/SelectLockingStrategy.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/functional/SQLServerDialectTest.java
- remove duplicated code
- handle `UPGRADE_NOWAIT` and `UPGRADE_SKIPLOCKED` as flavors of `PessimisticWriteSelectLockingStrategy`
- improve Javadoc
=> clean up locking strategies

tooling/metamodel-generator/hibernate-jpamodelgen.gradle, tooling/metamodel-generator/src/jakartaData/java/io/quarkus/hibernate/orm/panache/_PanacheEntity.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/quarkus/JakartaDataBookRepository.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/quarkus/PanacheBook.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/quarkus/QuarkusOrmPanacheTest.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/quarkusHrPanache/java/io/quarkus/hibernate/reactive/panache/_PanacheEntity.java, tooling/metamodel-generator/src/quarkusHrPanache/java/org/hibernate/processor/test/hrPanache/JakartaDataBookRepository.java, tooling/metamodel-generator/src/quarkusHrPanache/java/org/hibernate/processor/test/hrPanache/QuarkusHrPanacheTest.java, tooling/metamodel-generator/src/quarkusOrmPanache/java/org/hibernate/processor/test/ormPanache/PanacheBook.java, tooling/metamodel-generator/src/quarkusOrmPanache/java/org/hibernate/processor/test/ormPanache/QuarkusOrmPanacheTest.java
And tests
As discussed at https://hibernate.atlassian.net/browse/HHH-17960
=> HHH-17960: Fix proper default session type for JD repositories even in Quarkus

hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HANADialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HANAServerConfiguration.java, hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/database/metadata/MetadataAccessTests.java
https://hibernate.atlassian.net/browse/HHH-18112
We were testing Oracle only, hence the undetected failures.
I kept this test as a unit test, but I wonder if it shouldn't rather be an integration test TBH. That would require some changes to `database.gradle`, e.g. to add the product name, so that we can (somehow) retrieve it from the test. Probably better do that as a separate improvement, on `main` only, and when we're not being rushed.
Backport to branch 6.5: #8381
=> HHH-18112 Some dialects use the wrong default version

hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HANADialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HANAServerConfiguration.java, hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/database/metadata/MetadataAccessTests.java
https://hibernate.atlassian.net/browse/HHH-18112
Backport of #8380 to branch 6.5.
=> Backport HHH-18112 to branch 6.5 - Some dialects use the wrong default version

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
Fixes errors in [FunctionTests.testIntervalScaleExpressions](https://ci.hibernate.org/job/hibernate-orm-nightly/job/main/516/testReport/junit/org.hibernate.orm.test.query.hql/FunctionTests/Build___cockroachdb_cockroachdb___Test___testIntervalScaleExpressions_SessionFactoryScope_/) and [StandardFunctionTests.testIntervalScaleExpressions](https://ci.hibernate.org/job/hibernate-orm-nightly/job/main/516/testReport/junit/org.hibernate.orm.test.query.hql/StandardFunctionTests/Build___cockroachdb_cockroachdb___Test___testIntervalScaleExpressions_SessionFactoryScope_/).
=> Fix CockroachDB timestampdiff errors caused by `round()` return type

hibernate-core/src/main/java/org/hibernate/boot/internal/GenerationStrategyInterpreter.java, hibernate-core/src/main/java/org/hibernate/boot/model/relational/Sequence.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/ManagedTypeProcessor.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/XmlAnnotationHelper.java, hibernate-core/src/main/java/org/hibernate/dialect/sequence/NoSequenceSupport.java, hibernate-core/src/main/java/org/hibernate/dialect/sequence/SequenceSupport.java, hibernate-core/src/main/java/org/hibernate/id/PersistentIdentifierGenerator.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStructure.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStyleGenerator.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/TableGenerator.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/TableStructure.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardSequenceExporter.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/sequencegenerator/SequenceGeneratorOptionsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/sequencegenerator/TestEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/tableoptions/TableOptionsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/tableoptions/TestEntity.java, hibernate-core/src/test/resources/org/hibernate/orm/test/schemaupdate/sequencegenerator/TestEntity.xml, hibernate-core/src/test/resources/org/hibernate/orm/test/schemaupdate/tableoptions/TestEntity.xml
https://hibernate.atlassian.net/browse/HHH-18096
=> HHH-18096 Support for JPA 3.2 database generator options

hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureOutputsImpl.java, hibernate-core/src/main/java/org/hibernate/result/internal/OutputsImpl.java
https://hibernate.atlassian.net/browse/HHH-18116
=> HHH-18116 Support slow query logging for stored procedures

tooling/metamodel-generator/src/main/java/org/hibernate/processor/Context.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/mappedsuperclass/dao/Child.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/mappedsuperclass/dao/DaoTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/mappedsuperclass/dao/Parent.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/mappedsuperclass/dao/Queries.java
`Elements.getAllMembers()` does not do what it appears to do
https://hibernate.atlassian.net/browse/HHH-18137
=> HHH-18137 private fields inherited from supertypes in HibernateProcessor

hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/BasicCollectionJavaType.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/type/java/BasicCollectionJavaTypeDescriptorTest.java
https://hibernate.atlassian.net/browse/HHH-18073
=> HHH-18073 `BasicCollectionJavaType::wrap` should retain order of `Set` to keep consistent with `deepCopy`

hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HANASqlAstTranslator.java
https://hibernate.atlassian.net/browse/HHH-18132
=> HHH-18132 Add support for skip locked for HANA

hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/main/java/org/hibernate/engine/internal/UnsavedValueFactory.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/EntityState.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/merge/MergeDetachedCascadedCollectionInEmbeddableTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/exceptionhandling/StaleObjectMergeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/exceptionhandling/StaleVersionedObjectMergeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ops/MergeNewTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/ops/MergeTest.java, migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-1661
=> HHH-1661 throw when merge() applied to a definitely-removed instance 

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMeta.java
A typecast which works on javac doesn't work on ecj, but I agree that ecj is correct here.
https://hibernate.atlassian.net/browse/HHH-18149
=> HHH-18149 fix for HibernateProcessor on ecj

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/JpaMetamodel.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappingMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/BasicDotIdentifierConsumer.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/ProcessorSessionFactory.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/constant/ConstantInNamedQueryTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/constant/CookBookWithoutCheck.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/util/CompilationRunner.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/util/CompilationStatement.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/util/TestUtil.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/util/WithClasses.java, tooling/metamodel-generator/src/test/resources/org/hibernate/processor/test/constant/CookBookWithCheck.java, tooling/metamodel-generator/src/test/resources/org/hibernate/processor/test/constant/NumericBookType.java
See Jira issue [HHH-18106](https://hibernate.atlassian.net/browse/HHH-18106)
When named query in entity method annotated with @CheckHQL contains valid Java constant, processor should not report error
[HHH-18106]: https://hibernate.atlassian.net/browse/HHH-18106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HHH-18106 - @CheckHQL is reporting error when named query contains valid Java constant

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/JpaMetamodel.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappingMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/Context.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMeta.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/NamedQueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/ProcessorSessionFactory.java
This stores an index of entities and enum values in the entity.index directory. This approach has some downsides but works around some limitations of the processor API.
supersedes #8436
https://hibernate.atlassian.net/browse/HHH-18162
=> HHH-18162 index creation in HibernateProcessor

hibernate-core/src/main/java/org/hibernate/query/sqm/spi/SqmCreationHelper.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EmbeddableValuedExpression.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/AbstractSqmDmlStatement.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/AbstractSqmSelectQuery.java
https://hibernate.atlassian.net/browse/HHH-18170
Possible implementation replaces various `System.nanoTime()` calls, used to generate an unique identifier, with a counter.
=> HHH-18170 Subquery randomly generating wrong SQL due to duplicate alias

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/BiDirectionalAssociationHandler.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/PersistentAttributeTransformer.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/LazyLoadingAndParameterizedInheritanceTest.java
https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues/HHH-18151
**My first PR. :)**
The issue turned to be quite similar to 
https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues/HHH-16459
with fix https://github.com/hibernate/hibernate-orm/pull/6404
The problem was that the method `$$_$$_hibernate_read_GENERIC_ATTRIBUTE` that was defined in concrete class did not override the same method in its MappedSuperclass. 
Because method signature (return type) was different.
=> HHH-18151 Fix lazy loading with generics and inheritance

hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
https://hibernate.atlassian.net/browse/HHH-18139
=> HHH-18139 throw an exception when assigned id is null in StatelessSession.insert()

hibernate-agroal/src/test/resources/META-INF/services/org.junit.platform.launcher.LauncherSessionListener, hibernate-c3p0/src/test/resources/META-INF/services/org.junit.platform.launcher.LauncherSessionListener, hibernate-community-dialects/src/test/resources/META-INF/services/org.junit.platform.launcher.LauncherSessionListener, hibernate-core/src/test/resources/META-INF/services/org.junit.platform.launcher.LauncherSessionListener, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/AbstractEnversTest.java, hibernate-envers/src/test/resources/META-INF/services/org.junit.platform.launcher.LauncherSessionListener, hibernate-hikaricp/src/test/resources/META-INF/services/org.junit.platform.launcher.LauncherSessionListener, hibernate-jcache/src/test/resources/META-INF/services/org.junit.platform.launcher.LauncherSessionListener, hibernate-jfr/src/test/resources/META-INF/services/org.junit.platform.launcher.LauncherSessionListener, hibernate-micrometer/src/test/resources/META-INF/services/org.junit.platform.launcher.LauncherSessionListener, hibernate-spatial/src/test/resources/META-INF/services/org.junit.platform.launcher.LauncherSessionListener, hibernate-testing/src/main/java/org/hibernate/testing/bytecode/enhancement/extension/engine/BytecodeEnhancedTestEngine.java, hibernate-testing/src/main/java/org/hibernate/testing/junit4/BaseUnitTestCase.java, hibernate-testing/src/main/java/org/hibernate/testing/schema/CheckClearSchemaListener.java, hibernate-vector/src/test/resources/META-INF/services/org.junit.platform.launcher.LauncherSessionListener
This is only related to the JUnit change from the PR related to the JIRA mentioned in the title (https://github.com/hibernate/hibernate-orm/pull/8413)
We'd want to reuse this engine/extension in Hibernate Search, and this check `BaseUnitTestCase.checkClearSchema();` leads to failure there 😔. 
Here, I've added a listener and referenced it in the core module so that it is not automatically picked up by those who just want to use the testing jar.
Alternatively, if you think that the listener isn't a good idea, we could try to use engine config parameters and make this check optional through them ...
https://hibernate.atlassian.net/browse/HHH-17030
=> HHH-17030 Followup: move schema check from the engine into a listener

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java
I propose using float precision 8 since the documentation [smallfoat documentation](https://www.ibm.com/docs/en/informix-servers/14.10?topic=types-smallfloat) states that the SMALLFLOAT data type stores single-precision floating-point numbers with approximately nine significant digits.
https://hibernate.atlassian.net/browse/HHH-18150
=> HHH-18150 Fix for Informix float and double precision in decimal digits

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/FirebirdDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/pagination/FirstSkipLimitHandler.java, hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/FirebirdDialectTest.java
Fixes an issue where the LimitHandler generates `skip ? first ?` instead of `first ? skip ?` on Firebird 2.5 and older.
https://hibernate.atlassian.net/browse/HHH-18213
=> HHH-18213 Fix LimitHandler for Firebird 2.5 and older

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/AbstractInformationExtractorImpl.java, hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/InformationExtractorJdbcDatabaseMetaDataImpl.java
... DatabaseMetaData.crossReferences(...) not used
Most dialects retrieve all foreign keys when calling getImportedKeys(), hence the useCrossReferenceForeignKeys() method returns false in the Dialect. The ParentTable parameter of the getCrossReference() method must be non-null for Informix, resulting in the getCrossReferenceParentTableFilter() method returning a wildcard expression for the like condition (Select statement identified during debugging in the Informix driver). Upon verification, many dialects also accept a null value, in which case this condition is ignored.
There is no explicit command in Informix equivalent to "drop schema schema_name". After deleting objects, it is not necessary to explicitly drop the schema.
https://hibernate.atlassian.net/browse/HHH-18221
=> HHH-18221 Fix for Incomplete list of existing foreign keys

hibernate-core/src/main/java/org/hibernate/jpa/HibernatePersistenceProvider.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/PersistenceXmlParser.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/spi/Bootstrap.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/spi/PersistenceXmlParser.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/PersistenceUnitNameTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/jakarta/JakartaXmlSmokeTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/persistenceunit/DuplicatePersistenceUnitNameTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/persistenceunit/ExcludeUnlistedClassesTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/persistenceunit/PersistenceXmlParserTest.java, hibernate-core/src/test/resources/org/hibernate/jpa/test/persistenceunit/META-INF/multipu.xml, hibernate-core/src/test/resources/org/hibernate/jpa/test/persistenceunit/META-INF/pu1.xml, hibernate-core/src/test/resources/org/hibernate/jpa/test/persistenceunit/META-INF/pu2.xml, hibernate-core/src/test/resources/org/hibernate/jpa/test/persistenceunit/META-INF/pu3.xml
https://hibernate.atlassian.net/browse/HHH-18231
Two commits:
1. Fix PersistenceXmlParser to take into account the "provided" classloader/classloaderservice
2. Expose PersistenceXmlParser as an SPI (and remove superfluous methods in the process, because we don't want SPIs to expose too much)
=> HHH-18231: SPI for persistence XML parsing

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/sql/InFragment.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/PredicateTest.java
It turns out that SQL databases (IMO wrongly) treat the expression `null in (select 1 where false)` as false instead of null. And as of JPA 3.2, we're free to interpret `null in ()` consistently with that, which we should do.
So my change made things worse rather than better.
Relevant sections of JPA 3.2 spec are 4.6.5 and 3.11.8.
https://hibernate.atlassian.net/browse/HHH-17804
=> HHH-18241 (was HHH-17804) roll back change to semantics of 'null in ()'

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/sql/InFragment.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/PredicateTest.java
https://hibernate.atlassian.net/browse/HHH-18241
Backport of #8528 to branch 6.5.
Backporting is necessary due to huge performance degradation apparently caused by the changes we’re reverting: https://hibernate.atlassian.net/browse/HHH-18235
Was https://hibernate.atlassian.net/browse/HHH-17804
=> Backport HHH-18241 to branch 6.5 - roll back change to semantics of 'null in ()'

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java
I suggest using the SelectItemReferenceStrategy.POSITION strategy even though SelectItemReferenceStrategy.ALIAS is also supported. Consider this from the perspective of performance, readability, and so on.
https://hibernate.atlassian.net/browse/HHH-18244
=> HHH-18244 Fix for Informix SelectItemReferenceStrategy

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
After the change in InformixDialect, where the `supportsValuesListForInsert()` method returns `false`, another error occurred:
```
org.hibernate.query.IllegalQueryOperationException: Dialect does not support values lists for insert statements
at app//org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitValuesListStandard(AbstractSqlAstTranslator.java:1671)
at app//org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitValuesList(AbstractSqlAstTranslator.java:1666)
at app//org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitInsertSource(AbstractSqlAstTranslator.java:1333)
at app//org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitInsertStatementOnly(AbstractSqlAstTranslator.java:1313)
at app//org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitInsertStatement(AbstractSqlAst …
```
=> HHH-18250 Informix multi insert not supported

hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
Fix https://hibernate.atlassian.net/browse/HHH-18254
So that I can re-use the code when implementing ReactiveSelectQueryPlan#getReactiveResultsCount in Hibernate Reactive
The PR is for 6.5 but it should be applied on all the other branches (I think).
I expect it's possible to cherry pick the same commit, but let me know if I have to send new PRs for each
=> Change `NativeQueryImpl#createCountQueryPlan` scope to protected

MAINTAINERS.md, branching.adoc, ci/release/Jenkinsfile
I think the file was mostly ready, I just:
* added some safety: parsing of version strings to check they are correct, mandatory release version for manual releases
* prevented automatic releases on the main branch (so we can enable the Jenkins job on the main branch)
* removed some duplication (release script checkout) and improved formatting a little bit (long lines)
Next tasks:
1. Enable the Jenkins job on the main branch.
2. Check that all these credentials really are necessary... it seems weird that we need an SSH agent to prepare a release, for example.
=> Release Jenkinsfile: enable manual releases

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2390Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2390V8Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB297Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DerbyTenFiveDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DerbyTenSevenDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DerbyTenSixDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MariaDB102Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MariaDB103Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MariaDB10Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MariaDB53Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQL55Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQL57Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQL5Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/Oracle10gDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/Oracle12cDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/Oracle8iDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/Oracle9iDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQL10Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQL81Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQL82Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQL91Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQL92Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQL93Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQL94Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQL95Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQL9Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServer2005Dialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServer2008Dialect.java
https://hibernate.atlassian.net/browse/HHH-17735
=> HHH-17735 Community dialects for MySQL 5.7 give invalid SQL syntax for locks since 6.4.4

hibernate-core/src/main/java/org/hibernate/sql/results/internal/RowTransformerConstructorImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/instantiation/InstantiationWithGenericsTest.java
Jira issue [HHH-18218](https://hibernate.atlassian.net/browse/HHH-18218)
Problem tackled here is similar to one solved with pull request [#8527](https://github.com/hibernate/hibernate-orm/pull/8527) .
In added test case query
`select new ConstructorDto(e.id, e.data) from ConcreteEntity e`
is changed to
`select e.id, e.data from ConcreteEntity e`
This is causing new test to fail throwing `NoSuchMethodException`. [Actually, both existing test cases are failing unless `Before/AfterAll` is replaced with `Before/AfterEach`]
Suggested solution is similar used in [#8527](https://github.com/hibernate/hibernate-orm/pull/8527) when `TupleElement` is implementing `SqmExpressibleAccessor`. Otherwise, it will fall back to original implementation.
[HHH-18218]: …
=> HHH-18218 Projection without explicitly specifying new DtoClass(...)

hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetomany/OneToManyNonPrimaryKeyJoinTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/cache/polymorphism/CacheHolder.java, hibernate-core/src/test/java/org/hibernate/orm/test/cache/polymorphism/Cacheable.java, hibernate-core/src/test/java/org/hibernate/orm/test/cache/polymorphism/PolymorphicCacheTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/bidirectional/BiDirectionalOneToOneFetchTest.java
Test cases from old PR's:
- HHH-12752; `OneToManyNonPrimaryKeyJoinTest` passes, added it because I believe there is no similar one yet
- HHH-12885; `BiDirectionalOneToOneFetchTest.testSelectInverseOneToOne(X)` all pass, don't think this is already tested somewhere else, but not 100% sure
- HHH-10162; `PolymorphicCacheTest.testPolymorphismAndCacheWithHolder` fails (test assertion failure)
=> HHH-12752 / HHH-12885 / HHH-10162

documentation/src/main/asciidoc/querylanguage/Expressions.adoc, hibernate-core/src/main/java/org/hibernate/dialect/function/SumReturnTypeResolver.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/DomainQueryExecutionContext.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmElementAggregateFunction.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmIndexAggregateFunction.java, hibernate-core/src/main/java/org/hibernate/sql/results/internal/StandardRowReader.java, hibernate-core/src/main/java/org/hibernate/sql/results/spi/ListResultsConsumer.java, hibernate-core/src/main/java/org/hibernate/sql/results/spi/RowReader.java, hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayAggregateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/embeddable/EmbeddableInheritanceMappedSuperclassAndGenericsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/MultiSelectResultTypeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/TemporalParameterPlusDurationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/exec/EntityWithEmbeddedIdTest.java
https://hibernate.atlassian.net/browse/HHH-17956
=> HHH-17956 Criteria multiselect ignores type of the criteria query and always returns list of Object[]

hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/cfg/PersistenceSettings.java, hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CascadingActions.java, hibernate-core/src/main/java/org/hibernate/event/internal/AbstractFlushingEventListener.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/embedded/EmbeddableWithManyToOneCircularityTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/embedded/EmbeddableWithManyToOneTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/formula/ManyToManyNotIgnoreLazyFetchingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/manytoone/ManyToOneJoinTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetoone/OptionalOneToOneMappedByTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/LazyOneToOneRemoveFlushAccessTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/inlinedirtychecking/LoadUninitializedCollectionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/cascade/multicircle/MultiCircleJpaCascadeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/cascade2/CascadeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/bidirectional/BidirectionalOneToOneCascadeRemoveTest.java
https://hibernate.atlassian.net/browse/HHH-18212
Alternative solution that tries to fix the `TransientObjectException` check for associations removed in the same flush. I had to change a few of the existing ORM tests because we were not clearing removed associated entity instances in all cases.
=> HHH-18212 Accessing a removed lazy association results in a NullPointerException 

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/schema/SubclassIndexTest.java
I'm definitely not a fan of `@Table` annotations on subclasses in `SINGLE_TABLE` hierarchies. However, unfortunately we've already decided to tolerate it.
https://hibernate.atlassian.net/browse/HHH-18288
=> HHH-18288 @Index specified by subclass in SINGLE_TABLE inheritance

tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/packageinfo/PackageInfoMetamodelTest.java, tooling/metamodel-generator/src/test/resources/org/hibernate/processor/test/packageinfo/Message.java, tooling/metamodel-generator/src/test/resources/org/hibernate/processor/test/packageinfo/package-info.java
Jira issue [https://hibernate.atlassian.net/browse/HHH-18278](HHH-18278)
Since version 6.6 meta model generator is ignoring package.info.java
In previous versions (last checked version 6.5.2) meta model generator was creating from
`a.b.c.package-info`
class
`a.b.c.c_`
Problem is in method `org.hibernate.processor.HibernateProcessor.included(Element)` which is accepting only `TypeElement`'s and ignoring `PackageElement`'s
=> HHH-18278 Metamodel generator is ignoring JPA/Hibernate annotations in package-info

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/lob/BlobLocatorTest.java
In my opinion, the test `org.hibernate.orm.test.lob.BlobLocatorTest#testBoundedBlobLocatorAccess` should not require the dialect feature `DialectChecks.SupportsUnboundedLobLocatorMaterializationCheck`. It does not test the case where the dialect supports access to BLOBs within a transaction. …
=> Informix Blob locator fix

docker_db.sh, gradle/databases.gradle, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JsonAsStringJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/NClobJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/NVarcharJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/XmlAsStringJdbcType.java, hibernate-core/src/test/java/org/hibernate/orm/test/nationalized/MaterializedNClobBindTest.java
Solution similar to DB2Dialect, which was accepted for issue HHH-12753:
```
jdbcTypeRegistry.addDescriptor(Types.NCHAR, CharJdbcType.INSTANCE);
jdbcTypeRegistry.addDescriptor(Types.NVARCHAR, VarcharJdbcType.INSTANCE);
jdbcTypeRegistry.addDescriptor(Types.LONGNVARCHAR, LongVarcharJdbcType.INSTANCE);
```
This is not entirely correct, because in this way the table schema is also created directly with the type (`CHAR / VARCHAR / LONGVARCHAR`) even though the database supports the types (`NCHAR / NVARCHAR / LONGNVARCHAR`). Therefore, it is only necessary to replace calls to `setNString()` with `setString()` within the `doBind()` methods. There may be another way to solve this, so that the creation of the schema is preserved even with the data types `NCHAR / NVARCHAR / LONGNVARCHAR` and at the …
=> HHH-18312 Fix for Informix nationalized JDBC types support

hibernate-core/src/test/java/org/hibernate/orm/test/annotations/query/AllTables.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/query/QueryAndSQLTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/joinedSubclass/JoinedSubclassNativeQueryTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/Item.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/Wallet.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/QueryTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/loaders/SqlSelectTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/formula/FormulaNativeQueryTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/NativeQueryWithDuplicateColumnTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/NativeQueryResultBuilderTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/SQLTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/hand/query/NativeSQLQueriesTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/LongListTypeContributorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/typeparameters/TypeParameterTest.java, hibernate-core/src/test/resources/org/hibernate/orm/test/annotations/idclass/xml/HabitatSpeciesLink.xml, hibernate-core/src/test/resources/org/hibernate/orm/test/sql/hand/query/NativeSQLQueries.hbm.xml, hibernate-core/src/test/resources/org/hibernate/orm/test/stateless/Document.hbm.xml, hibernate-core/src/test/resources/org/hibernate/orm/test/typeparameters/Widget.hbm.xml, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/multiplerelations/GroupMemberTest.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/nativequery/SimpleEntity.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/domain/gambit/EntityOfBasics.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/domain/userguide/CreditCardPayment.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/domain/userguide/Person.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/domain/userguide/PersonPhoneCount.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/domain/userguide/Phone.java
Some unit tests with Informix are failing because Informix interprets identifiers in lowercase. Setting the physical naming strategy globally for all unit tests also doesn't make sense because many tests have hardcoded expected values. The solution is to change the column mapping in problematic tests to lowercase values to accommodate all dialects.
https://www.ibm.com/docs/en/informix-servers/12.10?topic=variable-specify-field-names
This topic was discussed here: https://hibernate.zulipchat.com/#narrow/stream/132096-hibernate-user/topic/Global.20hibernate.20properties.20for.20unit.20tests
=> Fixed Informix physical naming strategy compatibility

hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hhh18291/BooleanSubqueryTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hhh18291/InvoiceBE.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hhh18291/PaidInvoiceBE.java
Jira issue [HHH-18292](https://hibernate.atlassian.net/browse/HHH-18292)
When boolean expression is subquery, type can not be resolved directly as Java type; expressible Java type should be used instead.
[HHH-18292]: https://hibernate.atlassian.net/browse/HHH-18292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://hibernate.atlassian.net/browse/HHH-18291
=> HHH-18291 Boolean expression type not resolved properly for subquery

documentation/src/main/asciidoc/userguide/chapters/bootstrap/Bootstrap.adoc
https://hibernate.atlassian.net/browse/HHH-18318
seems we reuse the link URL as the link text, which is sloppy and inappropriate
=> HHH-18318 fix user guide bootstrap minor link text issue

hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/H2FormatJsonJdbcType.java
https://hibernate.atlassian.net/browse/HHH-17840
=> HHH-17840 Fix `H2FormatJsonJdbcType` deprecation

hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryBuilder.java
The issue manifests itself when it was mixed with other parent class/interface sharing similar methods. Java compiler complains that same methods have incompatible returning types from different classes.
https://hibernate.atlassian.net/browse/HHH-18340
=> HHH-18340 Fix incorrect method return types in AbstractDelegatingSessionFactoryBuilder class

settings.gradle
https://hibernate.atlassian.net/browse/HHH-18324
This update keeps popping up for Hibernate Search. It would be nice if we could update it in ORM, as the Jandex version in Search is aligned with the one in ORM.
=> HHH-18324 Upgrade to Jandex 3.2.0

hibernate-core/src/main/java/org/hibernate/boot/model/convert/internal/ConverterHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/GenericConverterAutoApplyTest.java
https://hibernate.atlassian.net/browse/HHH-18012
=> HHH-18012 Fix array type matching for auto applying AttributeConverter

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacySqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/H2SqlAstTranslator.java
H2 supports the filter clause (as it can be seen [here](https://www.h2database.com/html/functions-aggregate.html)) but in the H2SqlAstTranslator the supportsFilterClause is not overridden to be set to true.
https://hibernate.atlassian.net/browse/HHH-18339
=> HHH-18339 Set support filter clause to True for H2

hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
Checking if `getRowMutationOperations().hasInsertRow()` (e.g.) is not enough to avoid a possible NPE at `getRowMutationOperations().getInsertRowOperation().getSqlString()` since `getInsertRowOperation()` can still return null …
=> HHH-17914 - correct the NPE protection in AbstractCollectionPersister.logStaticSQL()

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/AltibaseDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/AltibaseSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/mapsid/MapsIdClassTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/DirtyTrackingNotInDefaultFetchGroupPersistTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/DirtyTrackingPersistTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/inlinedirtychecking/DirtyCheckPrivateUnMappedCollectionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/inlinedirtychecking/LoadAndUpdateEntitiesWithCollectionsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/inlinedirtychecking/dynamicupdate/DynamicUpdateAndCollectionsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/StatelessSessionVersioningTest.java
Fix Altibase integration test failures.
1. Optimize imports in AltibaseDialect.java
2. Register numand, numor, numxor functions for bitwise operation
3. Drop microseconds in currentLocalTimestamp method
4. Use seconds as native precision
5. Override visitBinaryArithmeticExpression in AltibaseSqlAstTranslator.java to use floor
<After modification>
$./gradlew clean build -Pdb=altibase
...
BUILD SUCCESSFUL in 26m 24s
tests : 15367
failures : 0
ignored : 2935
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the …
=> HHH-18343 fix Altibase integration test failures since Hibernate 6.5.2

tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/ProcessorSessionFactory.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/typeliteral/TypeLiteralTest.java, tooling/metamodel-generator/src/test/resources/org/hibernate/processor/test/typeliteral/Simple.java
See Jira issue [HHH-18358](https://hibernate.atlassian.net/browse/HHH-18358)
When generating metamodel named query defined as
```@NamedQuery(name = "#simple", query = "select s from Simple s where type(s) = Simple")```
causing generation to fail with error message
```Could not interpret path expression 'Simple'```
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal …
=> HHH-18358 Metemodel generator does not resolving entity type literals

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/naturalid/NaturalIdAndAssociationTest.java
https://hibernate.atlassian.net/browse/HHH-18338
`SessionFactoryImplementor` uses the `EntityPersister` to retrieve the type of the Selectable causing an `o.h.UnknownEntityTypeException` to be thrown when  the corresponding `EntityPersister` has not been created yet , using `MetadataImplementor` instead solves this issue.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING. …
=> HHH-18338 o.h.UnknownEntityTypeException: Unable to locate persister thrown when an embeddable object is loaded before the entity it references

hibernate-core/src/main/java/org/hibernate/metamodel/internal/AbstractCompositeIdentifierMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/NonAggregatedIdentifierMappingImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/AbstractFetchParent.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/InitializerData.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableFetchImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableForeignKeyResultImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/NonAggregatedIdentifierMappingInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java
Fixes https://hibernate.atlassian.net/browse/HHH-18381
For ORM 6.6
I haven't checked ORM 7 yet, it might need similar changes but I will send a separate PR
=> Changes for Hibernate Reactive 2.4

hibernate-core/src/main/java/org/hibernate/engine/transaction/jta/platform/internal/JtaPlatformInitiator.java
Updated logging to indicate fallback provider checking when initiating JTA platform service
Currently, `org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator#initiateService` is logging the message `"No JtaPlatform was specified, checking resolver"` twice while resolving `org.hibernate.engine.transaction.jta.platform.spi.JtaPlatform` instance. I'm changing the second debug log to indicate the initialization is going through the fallback provider (currently just returning a null) …
=> HHH-12836: Improved logging when initiating service

hibernate-core/src/main/java/org/hibernate/type/EntityType.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/onetoone/OneToOneUniqueJoinColumnsTest.java
https://hibernate.atlassian.net/browse/HHH-18390
=> HHH-18390 JoinColumn leads to `NullPointerException: Cannot invoke "Object.hashCode()" because "value" is null` on load

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractIdentifiableType.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CountQueryTests.java
https://hibernate.atlassian.net/browse/HHH-18357
Backport of #8686 
=> HHH-18357 Null pointer exception in createCountQuery because Identifier descriptor is null in MappedSuperclass

hibernate-core/src/main/java/org/hibernate/ScrollableResults.java, hibernate-core/src/main/java/org/hibernate/SessionFactory.java, hibernate-core/src/main/java/org/hibernate/SharedSessionContract.java
NOTE: It's a breaking change.
https://hibernate.atlassian.net/browse/HHH-18097
=> HHH-18097 Replace `java.io.Closeable` with `java.lang.AutoCloseable`

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
The fix for [HHH-18147](https://hibernate.atlassian.net/browse/HHH-18147) add a lazy initialization that causes regressions in Hibernate Reactive.
This change makes it possible to skip the lazy initialization (Hibernate Reactive does not support it anyway) for the time being.
I might find a better solution when I have time.
This change was already part of the changes proposed here: https://github.com/hibernate/hibernate-orm/pull/8662
[HHH-18147]: https://hibernate.atlassian.net/browse/HHH-18147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://hibernate.atlassian.net/browse/HHH-18431
=> Allow Hibernate Reactive to skip lazy initialization

settings.gradle
Because we upgraded to Gradle 8.8 some time ago, which supports Java 22. See https://docs.gradle.org/8.8/release-notes.html
=> Use Java 22 bytecode in tests when testing against OpenJDK 22+

hibernate-core/src/main/java/org/hibernate/tool/schema/internal/AbstractSchemaMigrator.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaCreatorImpl.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaDropperImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/SchemaUpdateArrayPropertiesTest.java
https://hibernate.atlassian.net/browse/HHH-18406
=> HHH-18406 Oracle: schema update fails to create entity table if one of the fields is an array

gradle/javadoc.gradle, shared/javadoc/stylesheet.css
Hey @sebersole 😃 
I've looked at the JavaDocs CSS and from what it seems there're just a few colours and fonts that were modified. 
This patch should address the same for the new doclet styles.
=> Update JavaDoc CSS for new layout

hibernate-core/src/main/java/org/hibernate/annotations/TimeZoneColumn.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AbstractPropertyHolder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedColumn.java, hibernate-core/src/main/java/org/hibernate/boot/models/annotations/internal/TimeZoneColumnAnnotation.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/TimeZoneColumnTest.java
https://hibernate.atlassian.net/browse/HHH-17448
@sebersole should we also add `columnOptions` and `columnComment` to `@SoftDelete`?
=> HHH-17448 Add newly standard column annotation attributes to Hibernate column annotations

docker_db.sh, hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java, nightly.Jenkinsfile
https://hibernate.atlassian.net/browse/HHH-17888
=> HHH-17888 - Remove support for MariaDB versions older than 10.5

hibernate-core/src/main/java/org/hibernate/cfg/JdbcSettings.java
deprecated PASS property was linked to the incorrect new property in 'jakarta' namespace.
=> fixed link to new jakarta-jdbc-password property from the deprecated PASS property

hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/BooleanJavaType.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/type/java/BooleanJavaTypeDescriptorTest.java
This PR should fix the issue of Boolean Converters which change null values not being included in the check constraints generated. See the JIRA Issue for a detailed example.
https://hibernate.atlassian.net/browse/HHH-18451
=> HHH-18451 Fix CheckConstraints for Booleans with null value converters

hibernate-core/src/main/java/org/hibernate/result/internal/OutputsImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/MySQLStoredProcedureTest.java
This is to fix the issue with StoredProcedureQuery getResultList when the parameter has INOUT param.
https://hibernate.atlassian.net/browse/HHH-17847.
=> HHH-17847:  fix StoredProcedureQuery.getResultList()

hibernate-core/src/main/java/org/hibernate/query/spi/QueryParameterBindings.java
Hey @beikov , Search is using the `NO_PARAM_BINDINGS` and now that it got marked for removal, the suggested alternative is in an internal package ... maybe we can just add a static method to the interface for the empty bindings instead?
=> Provide a non-"internal" way to access empty QueryParameterBindings

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQuerySpec.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/EntityGraphAndJoinTest.java
https://hibernate.atlassian.net/browse/HHH-18378
=> HHH-18378 Avoid reusing existing joins for entity-graph fetches if they're included in the where clause

hibernate-core/src/main/java/org/hibernate/dialect/pagination/Oracle12LimitHandler.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/NativeQueryLimitOffsetTest.java
https://hibernate.atlassian.net/browse/HHH-18309
=> HHH-18309 Oracle LimitHandler does not seem to handle maxrows correctly for native queries

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnyBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/OneToOneSecondPass.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/attributebinder/Foo.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/attributebinder/FooBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/attributebinder/System.java
alternative to proposed fix #8698 by @quaff
https://hibernate.atlassian.net/browse/HHH-18414
=> HHH-18414 remove duplicated call to callAttributeBindersInSecondPass()

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/NaturalIdMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/CompoundNaturalIdMapping.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/identifier/MutableNaturalIdsTest.java
https://hibernate.atlassian.net/browse/HHH-18466
This test demonstrates a regression from 5.6.15.Final: When you have an entity with more than one `@NaturalID` instance variable (some mutable, some not), and you mutate those (mutable) fields, that entity can no longer be found. There is no workaround that I can find.
This PR is a failing test called `MutableNaturalIdsTest`
Tested with:
```
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)
```
and
```
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode, sharing)
```
Tested from the …
=> HHH-18466 Test and fix regression from 5.6.15.Final where a mutable natural IDs query cannot find an entity

hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorParameters.java, hibernate-core/src/main/java/org/hibernate/generator/GeneratorCreationContext.java, hibernate-core/src/main/java/org/hibernate/id/Configurable.java, hibernate-core/src/main/java/org/hibernate/id/ForeignGenerator.java, hibernate-core/src/main/java/org/hibernate/id/IdentifierGenerator.java, hibernate-core/src/main/java/org/hibernate/id/IncrementGenerator.java, hibernate-core/src/main/java/org/hibernate/id/PersistentIdentifierGenerator.java, hibernate-core/src/main/java/org/hibernate/id/PostInsertIdentifierGenerator.java, hibernate-core/src/main/java/org/hibernate/id/SelectGenerator.java, hibernate-core/src/main/java/org/hibernate/id/UUIDGenerator.java, hibernate-core/src/main/java/org/hibernate/id/UUIDHexGenerator.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStyleGenerator.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/TableGenerator.java, hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/SequenceStyleGeneratorBehavesLikeSequeceHiloGeneratorWitZeroIncrementSizeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/enhanced/SequenceStyleConfigUnitTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/sequence/PooledWithCustomNamingStrategyTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/enhanced/table/Db2GenerationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/NativeGenerator.java, migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-18337
Alternative solution to https://github.com/hibernate/hibernate-orm/pull/8776 on `main` (7.0), changing the `Configurable#configure` method signature to accept a `GeneratorCreationContext`.
=> HHH-18337 SequenceStyleGenerator not respecting physical naming strategy

hibernate-core/src/main/java/org/hibernate/jpa/HibernatePersistenceConfiguration.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/boot/PersistenceConfigurationTests.java
HHH-18519 - Add vararg method to HibernatePersistenceConfiguration for supplying mappings
Also adds support for auto schema export.
=> HHH-18519 - Add vararg method to HibernatePersistenceConfiguration for supplying mappings

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/ComplexValueGenerationTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/DatabaseValueGenerationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/DefaultGeneratedValueIdentityTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/DefaultGeneratedValueTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/temporals/MultipleGeneratedValuesTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/temporals/ProposedGeneratedTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/temporal/TimestampPropertyTest.java
=> Tests with current_timestamp requires Dialect UsesStandardCurrentTimestampFunction feature

hibernate-core/src/main/java/org/hibernate/engine/internal/UnsavedValueFactory.java, hibernate-core/src/main/java/org/hibernate/engine/internal/Versioning.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EntityVersionMappingImpl.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/VersionTypeSeedParameterSpecification.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/VersionJavaType.java, hibernate-core/src/test/java/org/hibernate/orm/test/ops/MergeExplicitInitialVersionTest.java
This was wrong for code like:
```java
@Version int version = 1;
```
https://hibernate.atlassian.net/browse/HHH-18487
=> HHH-18487 align version unsaved-value with semantics of persist()

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractIdentifiableType.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/MixedIdAndIdClassHandling.java
Before this commit, `IdentifiableType.getIdType()` returns unexpected `null` if multiple @Id present.
https://hibernate.atlassian.net/browse/HHH-6951
=> HHH-6951 IdentifiableType.getIdType() should respect @IdClass

hibernate-core/src/main/java/org/hibernate/dialect/SqlAstTranslatorWithMerge.java, hibernate-core/src/main/java/org/hibernate/dialect/SqlAstTranslatorWithUpsert.java
Running `org.hibernate.orm.test.stateless.UpsertTest`:
Before -> `merge into "UpsertTest$Record" as t using (select cast(? as bigint) id, cast(? as varchar) message) as s on (t.id=s.id) when not matched then insert (id, message) values (s.id, s.message)  when matched then update set message=s.message`
After  -> `merge into "UpsertTest$Record" as t using (select cast(? as bigint) id, cast(? as varchar) message) as s on (t.id=s.id) when not matched then insert (id, message) values (s.id, s.message) when matched then update set message=s.message`
and can be …
=> Remove duplicated space before `when matched`

hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/test/java/org/hibernate/dialect/MySQLDialectDatabaseVersionTest.java
Fixing version detection to be able to run hibernate on a server using mysql in azure. 
The detection logic also handles the cases it did before, but does no longer crash when suffixes are added, like e.g azure does for their versions.
https://hibernate.atlassian.net/browse/HHH-18518
=> HHH-18518 change implementation to capture MySQL custom versions better

hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/MapBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/attributeoverride/MapAttributeOverrideTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/attributeoverride/Route.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/attributeoverride/Schedule.java
When determining the type of the collection element, `CollectionBinder` considers it to be embeddable if there are `@AttributeOverride`-s on corresponding member (property or method) . This doesn't work when collection is a map (handled by `MapBinder` which extends `CollectionBinder`) because with maps `@AttributeOverride`-s can be specified not only for the map value but also for the map key, and only the former should affect the type of the collection element (map value). 
This PR makes the `@AttributeOverride` check customizable and adds an override in `MapBinder` to only check for `@AttributeOverride`-s that apply to the map value. …
=> HHH-18516 - Ignore @AttributeOverride for map key when checking type of map value

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EntityVersionMappingImpl.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
1. remove unused field `BasicAttributeMapping attributeMapping`
2. remove unused constructor parameter `MappingModelCreationProcess creationProcess`
=> Polishing `EntityVersionMappingImpl`

hibernate-core/src/main/java/org/hibernate/dialect/DB2iDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2iSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/dialect/DB2iDialectTest.java
Implementing a fix for HHH-18560 by re-introducing DB2 i-series compatible queries from 5.6 that were lost (regression in my view). 
DB2Dialect from version 6.x implements methods with 'share/update-lock'-clauses, which aren't supported by DB2 i-series.
https://www.ibm.com/docs/en/i/7.5?topic=statement-isolation-clause
I made overwritten versions of these methods in the DB2iDialect where I did not include a lock clause, as the only option on i-series is an 'exclusive' lock, which seems excessive. And on the IBM docs caution with this clause is advised.
and can be relicensed under the terms of the [LGPL …
=> HHH-18560: fix for invalid queries executed on DB2i AS/400 machine

CONTRIBUTING.md
=> Fix contributing remark about jira keys in commit messages

hibernate-core/src/main/java/org/hibernate/engine/spi/LoadQueryInfluencers.java, hibernate-core/src/test/java/org/hibernate/orm/test/engine/spi/LoadQueryInfluencersTest.java
This pull request adds a test case and fix for Jira issue HHH-18571.
https://hibernate.atlassian.net/browse/HHH-18571
The load query influencer here correctly handles override batch sizing vs. global default batch size to determine whether and entity or collection is effectively batch loadable. …
=> Fix effective batching bug described in HHH-18571

hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
The method implementation is identical to default method
=> Remove redundant methods `isBatchLoadable()`

hibernate-core/src/main/java/org/hibernate/MultiIdentifierLoadAccess.java, hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/StatelessSession.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java, hibernate-core/src/main/java/org/hibernate/internal/MultiIdentifierLoadAccessImpl.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/ExecutionContextWithSubselectFetchHandler.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderArrayParam.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderStandard.java, hibernate-core/src/main/java/org/hibernate/loader/ast/spi/MultiIdLoadOptions.java, hibernate-core/src/main/java/org/hibernate/loader/internal/IdentifierLoadAccessImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/FindAllFetchProfileTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/FindAllTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/GetAllTest.java
https://hibernate.atlassian.net/browse/HHH-17948
=> HHH-17948, HHH-18591 add Session.findAll(), StatelessSession.getAll() + missing features of MultiIdentifierLoadAccess

docker_db.sh
https://hibernate.atlassian.net/browse/HHH-18507
backport of https://github.com/hibernate/hibernate-orm/pull/8810
=> [6.2][HHH-18507] allow overwriting the default db image with environment variable in docker_db.sh

docker_db.sh
https://hibernate.atlassian.net/browse/HHH-18507
backport of https://github.com/hibernate/hibernate-orm/pull/8810
=> [6.6][HHH-18507] allow overwriting the default db image with environment variable in docker_db.sh

hibernate-core/src/main/java/org/hibernate/type/descriptor/java/CalendarDateJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/CalendarTimeJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/DateJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/JdbcTimeJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/LocalTimeJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/OffsetTimeJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/spi/DdlTypeRegistry.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/LocalTimeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/javatime/GlobalJavaTimeJdbcTypeTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/javatime/JavaTimeJdbcTypeTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/temporal/FractionalSecondsTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/temporal/JavaTimeFractionalSecondsTests.java
The default precision returned by `getDefaultTimestampPrecision()` is only appropriate for timestamps (hence the name) and should not be used for dates or plain times.
https://hibernate.atlassian.net/browse/HHH-17576
=> HHH-17576 inappropriate use of getDefaultTimestampPrecision() as default precision

hibernate-core/src/main/java/org/hibernate/engine/spi/CascadingActions.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderArrayParam.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderStandard.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/FindAllTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiLoadTest.java
https://hibernate.atlassian.net/browse/HHH-18544
https://hibernate.atlassian.net/browse/HHH-18554
=> HHH-18544 multiload() and findAll() should return existing proxies

hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingImpl.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractCommonQueryContract.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/SelectCaseWhenNullLiteralTest.java
https://hibernate.atlassian.net/browse/HHH-18556
https://github.com/hibernate/hibernate-orm/pull/8929 Backport 
=> HHH-18556 Expressions.nullExpresion() in querydsl result in NPE in SqmExpressible

hibernate-core/src/main/java/org/hibernate/loader/plan/exec/process/internal/AbstractRowReader.java
Fix race condition in `AbstractRowReader`. Described in the Jira https://hibernate.atlassian.net/browse/HHH-18475
=> HHH-18475 fix race condition in AbstractRowReader (Hibernate 5.6)

hibernate-core/src/test/java/org/hibernate/orm/test/cut/generic/GenericCompositeUserTypeTest.java
This reverts commit 7e4df3f805c6155ba3f534230958862b1fbbdba6. (https://hibernate.atlassian.net/browse/HHH-18543)
=> Revert "HHH-18543 Skip GenericCompositeUserTypeTest for JVM OpenJ9"

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/join/JoinedHierarchyDiscIdSelectTest.java
https://hibernate.atlassian.net/browse/HHH-18503
=> HHH-18503 ID select criteria query fails with joined + discriminator inheritance when entity has subtypes

hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java, hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/StandardFunctionReturnTypeResolvers.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/generics/embeddable/AbstractValueObject.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/generics/embeddable/CreationDate.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/generics/embeddable/GenericEmbeddableSuperclassMetamodelTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/generics/embeddable/Parent.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/generics/embeddable/SomeNumber.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/generics/embeddable/SomeString.java
https://hibernate.atlassian.net/browse/HHH-18490
=> HHH-18490 Static metamodel contains wrong type for Embeddable with generic attribute extending from mapped superclass

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/MultiValuedParameterTest.java
Fix 
```
java.lang.IllegalStateException: Binding is multi-valued; illegal call to #getBindValue
at org.hibernate.query.internal.QueryParameterBindingImpl.getBindValue(QueryParameterBindingImpl.java:100)
at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.resolveSqmParameter(BaseSqmToSqlAstConverter.java:6283)
at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.consumeSqmParameter(BaseSqmToSqlAstConverter.java:5861)
at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.consumeSingleSqmParameter(BaseSqmToSqlAstConverter.java:5950)
at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.processInSingleParameter(BaseSqmToSqlAstConverter.java:8178)
at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.processInSingleHqlParameter(BaseSqmToSqlAstConverter.java:8135)
at …
```
=> HHH-18575 Fix IllegalStateException while passing multi-valued BigDecimal as parameter

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/ObjectNullResolvingJdbcType.java, hibernate-core/src/test/java/org/hibernate/orm/test/typedescriptor/NullTest.java
The method `PreparedStatement.getParameterMetaData().getParameterType(int)` call is expensive for some JDBC driver such as pgJDBC, we should avoid it if the driver supports binding `Types.NULL` for `setNull()` or `null` for `setObject()`.
https://hibernate.atlassian.net/browse/HHH-18581
=> HHH-18581 Introduce `supportsBindingNullSqlTypeForSetNull()` and `supportsBindingNullForSetObject()` for `Dialect` to optimize binding null

hibernate-core/src/main/java/org/hibernate/FlushMode.java, hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/annotations/FlushModeType.java, hibernate-core/src/main/java/org/hibernate/annotations/NamedNativeQuery.java, hibernate-core/src/main/java/org/hibernate/annotations/NamedQuery.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/QueryBinder.java, hibernate-core/src/main/java/org/hibernate/boot/models/annotations/internal/NamedNativeQueryAnnotation.java, hibernate-core/src/main/java/org/hibernate/boot/models/annotations/internal/NamedQueryAnnotation.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/util/FlushModeTypeHelper.java, hibernate-core/src/main/java/org/hibernate/procedure/ProcedureCall.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java, hibernate-core/src/main/java/org/hibernate/query/CommonQueryContract.java, hibernate-core/src/main/java/org/hibernate/query/MutationQuery.java, hibernate-core/src/main/java/org/hibernate/query/NativeQuery.java, hibernate-core/src/main/java/org/hibernate/query/Query.java, hibernate-core/src/main/java/org/hibernate/query/QueryFlushMode.java, hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/hql/spi/SqmQueryImplementor.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractCommonQueryContract.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/SqmQuery.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sql/spi/NativeQueryImplementor.java, hibernate-core/src/main/java/org/hibernate/query/sqm/SqmSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/AbstractSqmSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/spi/DelegatingSqmSelectionQueryImplementor.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/NamedQueryQueryFlushModeTest.java
Redo of #5851.
- replaces `FlushModeType` in the annotation package
- much less confusing when applied to a `Query`
* what do `MANUAL` and `COMMIT` mean for a `Query`?
* how is `AUTO` useful for a `Query`?
- also make `Query.getHibernateFlushMode()` obey its documented semantics by returning the session flush mode instead of null when unset …
=> HHH-15942 introduce QueryFlushMode

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/GeneratedValuesProcessor.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/GeneratedNoOpUpdateTest.java
https://hibernate.atlassian.net/browse/HHH-18484
=> HHH-18484 Update fails when a many-to-one property on an entity with a generated value is changed

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesCacheHit.java, hibernate-core/src/test/java/org/hibernate/orm/test/querycache/QueryCacheNullValueTest.java
https://hibernate.atlassian.net/browse/HHH-18439
Alternative to https://github.com/hibernate/hibernate-orm/pull/8814, which also fixes an assertion error in query result type-check when selecting null literals.
=> HHH-18439 NullPointerException when access data from query cache

hibernate-core/src/main/java/org/hibernate/sql/results/internal/RowTransformerConstructorImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/instantiation/MatchingConstructorTest.java
Jira issue HHH-18322[](https://hibernate.atlassian.net/browse/HHH-18322)
If constructor with exact argument types does not exists `NoSuchMethodException` is throws even when matching constructor (e.g. one accepting superclass argument) exists.
To solve the problem, in case when no exact constructor exists, try finding one that matches as fallback …
=> HHH-18322 Constructor with argument of superclass type not recognized as matching constructor

hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/id/entities/Location.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/InheritanceJunctionExistsPredicateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/orphan/onetoone/embedded/OneToOneLazyOrphanRemovalInEmbeddedEntityTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/instantiation/MatchingConstructorTest.java
https://hibernate.atlassian.net/browse/HHH-18626
=> HHH-18626 fix error for @Id annotation in @Embeddable class

.git-blame-ignore-revs, CONTRIBUTING.md, gradle/java-module.gradle, hibernate-core/hibernate-core.gradle
Follow up to https://github.com/hibernate/hibernate-orm/pull/8952
=> Exclude target folder from spotless to fix gradle compilation cache and add git blame ignore list

hibernate-core/src/main/java/org/hibernate/id/factory/internal/StandardIdentifierGeneratorFactory.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/NativeGenerator.java
Also change a failing test so it doesn't pass `null` as creation context
https://hibernate.atlassian.net/browse/HHH-18337
=> HHH-18337 - SequenceStyleGenerator not respecting physical naming strategy

hibernate-core/src/main/java/org/hibernate/query/spi/AbstractCommonQueryContract.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/NodeBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/AbstractSqmSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/KeyBasedPagination.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/NoParamSqmCopyContext.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SimpleSqmCopyContext.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/SqmCopyContext.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/delete/SqmDeleteStatement.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/insert/SqmInsertSelectStatement.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/insert/SqmInsertValuesStatement.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectStatement.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/update/SqmUpdateStatement.java
https://hibernate.atlassian.net/browse/HHH-18596
=> HHH-18596 Get rid of ValueHandlingMode hack in query pagination

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/PersistentAttributeTransformer.java, tooling/hibernate-gradle-plugin/src/test/java/org/hibernate/orm/tooling/gradle/ModuleInfoProjectTests.java, tooling/hibernate-gradle-plugin/src/test/resources/projects/simple-moduleinfo/build.gradle, tooling/hibernate-gradle-plugin/src/test/resources/projects/simple-moduleinfo/src/main/java/TheEmbeddable.java, tooling/hibernate-gradle-plugin/src/test/resources/projects/simple-moduleinfo/src/main/java/TheEntity.java, tooling/hibernate-gradle-plugin/src/test/resources/projects/simple-moduleinfo/src/main/java/module-info.java
See Jira issue [HHH-18500](https://hibernate.atlassian.net/browse/HHH-18500)
When Hibernate Gradle plugin is used with extended enhancement set to true, it will throw NPE on module-info. This is caused by fact that module-info does not have super class. Solution is simple null check to avoid NPE. …
=> HHH-18500 Gradle plugin crashes on module-info when extended enhancement is set

hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorAnnotationHelper.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/IdBagIdGeneratorResolverSecondPass.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/IdGeneratorResolverSecondPass.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/StrictIdGeneratorResolverSecondPass.java, hibernate-core/src/main/java/org/hibernate/boot/model/relational/Namespace.java, hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/generator/GeneratorCreationContext.java, hibernate-core/src/main/java/org/hibernate/id/Configurable.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStyleGenerator.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/TableGenerator.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/mapping/Component.java, hibernate-core/src/main/java/org/hibernate/mapping/GeneratorSettings.java, hibernate-core/src/main/java/org/hibernate/mapping/KeyValue.java, hibernate-core/src/main/java/org/hibernate/mapping/Property.java, hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java, hibernate-core/src/main/java/org/hibernate/metamodel/spi/RuntimeModelCreationContext.java, hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java, hibernate-core/src/test/java/org/hibernate/orm/test/LocalTemporaryTableMutationStrategyNoDropTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/id/generators/UnnamedGeneratorTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/PooledHiLoSequenceIdentifierTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/custom/CustomSequenceGenerator.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/enhanced/auto/AutoGenerationTypeTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
and remove a bunch of unused parameters from methods in this package
=> simplify Generator instantiation lifecycle

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/NativeQueryWithDatetimesTest.java
https://hibernate.atlassian.net/browse/HHH-18635
=> HHH-18635 Avoid using `bigdatetime` column type on Sybase jconn when not necessary

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/test/java/org/hibernate/orm/test/tenantid/TenantIdToOneBidirectionalTest.java
https://hibernate.atlassian.net/browse/HHH-18617
=> HHH-18617 Fetching unowned side of bidirectional OneToOne mappings including tenant identifier triggers EntityFilteredException

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseAnywhereSqlAstTranslator.java
https://hibernate.atlassian.net/browse/HHH-18471
=> HHH-18471  Since 6.2.2 Dialect SybaseAnywhereDialect does not render table names in the selection query

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseAnywhereSqlAstTranslator.java
https://hibernate.atlassian.net/browse/HHH-18471
https://github.com/hibernate/hibernate-orm/pull/8969 6.6 backport
=> HHH-18471 Since 6.2.2 Dialect SybaseAnywhereDialect does not render table names in the selection query

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/MappedDiscriminatorConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/NativeQueryAndDiscriminatorTest.java
https://hibernate.atlassian.net/browse/HHH-18515 
I know it is a kind of a hack but with native query having a properties with the same name of the descriptor but type enum not able to find an easy solution without introducing overhead and massive changes
=> HHH-18515 Unrecognized discriminator value exception when running native query on entity with discriminator column

hibernate-core/src/main/java/org/hibernate/type/BasicTypeRegistry.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/array/ArrayOfArraysTest.java
https://hibernate.atlassian.net/browse/HHH-18582
The NPE itself was already fixed by https://github.com/hibernate/hibernate-orm/pull/8902 on `main` (7.0); this change generates a dedicated and more specific error message.
=> HHH-18582 Mapping array of arrays with @JdbcTypeCode(SqlTypes.ARRAY) causes NPE

hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java, hibernate-core/src/main/java/org/hibernate/type/BasicTypeRegistry.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/BasicPluralJavaType.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/basic/ListOfByteArrayTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/basic/ListOfStringTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/array/ArrayOfArraysTest.java
https://hibernate.atlassian.net/browse/HHH-18582
https://hibernate.atlassian.net/browse/HHH-17739
Backport of https://github.com/hibernate/hibernate-orm/pull/8993 and https://github.com/hibernate/hibernate-orm/pull/8902.
=> HHH-18582 + HHH-17739 Backports to 6.6

hibernate-core/src/main/java/org/hibernate/dialect/OracleUserDefinedTypeExporter.java
Add an ´IF EXISTS´ to the `DROP TYPE ` and `DROP FUNCTION ` statements in `OracleUserDefinedTypeExporter` if the dialect supports it (23+ .)
https://hibernate.atlassian.net/browse/HHH-18657
=> HHH-18657 Use IF EXISTS in OracleUserDefinedTypeExporter
