hibernate/hibernate-orm

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddedAttributeMapping.java
hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/embeddedid/OneToOneMultiLevelEmbeddedId.java

https://hibernate.atlassian.net/browse/HHH-15279

HHH-15279 NPE with Id on OneToOne referencing entity with multi-level EmbeddedId

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/CoalesceTest.java

https://hibernate.atlassian.net/browse/HHH-15291

HHH-15291 Fix translation issue with SqmCoalesce

---

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java
hibernate-core/src/test/java/org/hibernate/orm/test/idclass/IdClassWithOneAttributeTest.java

https://hibernate.atlassian.net/browse/HHH-15286

HHH-15286 Query with a Composite Identifier (@IdClass) throws an exception

---

documentation/src/main/asciidoc/userguide/appendices/Annotations.adoc

https://hibernate.atlassian.net/browse/HHH-15010

HHH-15010 - update Java type list for '@CreationTimestamp' and '@UpdateTimestamp' in user guide

---

gradle/java-module.gradle

https://hibernate.atlassian.net/browse/HHH-15297

HHH-15297 Invalid Automatic-Module-Name org.hibernate.orm.community-dialects

---

hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/ExtractedDatabaseMetaDataImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchNoUseJdbcMetadataTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/jdbc/env/NoDatabaseMetaDataTest.java

https://hibernate.atlassian.net/browse/HHH-15281

HHH-15281 INSERTs/UPDATEs no longer executed as JDBC Batch statements if hibernate.temp.use_jdbc_metadata_defaults is set to false

---

hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/identity/CockroachDBIdentityColumnSupport.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/lob/MaterializedBlobTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/hql/BulkManipulationTest.java

https://hibernate.atlassian.net/browse/HHH-15294
Some fixes that fix a number of test failures when running against CockroachDB.

HHH-15294 cockroachdb fixes

---

hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/spi/DdlTypeRegistry.java

Added a method for removing DdlTypes from the DdlTypeRegistry

---

hibernate-core/src/main/java/org/hibernate/property/access/spi/GetterFieldImpl.java

See https://hibernate.atlassian.net/browse/HHH-15329 for more info.
Cheers,
Christoph

HHH-15329 Remove workaround for HHH-10382 in GetterFieldImpl

---

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java

Backport of https://hibernate.atlassian.net/browse/HHH-15325

HHH-15325 Avoid allocations from BitSet.stream() in AbstractEntityPersister

---

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelection.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/results/BasicHqlResultTests.java

https://hibernate.atlassian.net/browse/HHH-15338

HHH-15338 Remember initial selection node alias in SqmSelection

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EntityCollectionPart.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/SelectManyToOneEmbeddedIdWithKeyManyToOneQueryTest.java

https://hibernate.atlassian.net/browse/HHH-15339

HHH-15339 Add foreign key part name as target key property name for fk optimization

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityIdentifierMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddedForeignKeyDescriptor.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/ParameterTests.java

https://hibernate.atlassian.net/browse/HHH-15341

HHH-15341 Disallow passing transient entity parameter values

---

hibernate-core/src/main/java/org/hibernate/query/internal/QueryHelper.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/SelectCaseWhenNullLiteralTest.java

https://hibernate.atlassian.net/browse/HHH-15343

HHH-15343 Fix NPE in type determination for case expression with null literal

---

migration-guide.adoc

Made minor edit to doc, replaced a `,` with `.` when referring to JDBC types.

Fixed typo

---

hibernate-core/src/main/java/org/hibernate/spi/NavigablePath.java

https://hibernate.atlassian.net/browse/HHH-15347

HHH-15347 Use equals instead of identity check in NavigablePath#relativize

---

documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc
documentation/src/test/java/org/hibernate/userguide/hql/HQLTest.java
hibernate-core/src/main/java/org/hibernate/dialect/HANASqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/function/AggregateWindowEmulationQueryTransformer.java
hibernate-core/src/main/java/org/hibernate/query/criteria/JpaDerivedFrom.java
hibernate-core/src/main/java/org/hibernate/query/criteria/JpaSelectCriteria.java
hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleType.java
hibernate-core/src/main/java/org/hibernate/query/hql/internal/QualifiedJoinPredicatePathConsumer.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/SubQueryInFromEmbeddedIdTests.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/SubQueryInFromIdClassTests.java
hibernate-testing/src/main/java/org/hibernate/testing/DialectChecks.java
hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java

The word "sub" means "submarine", "submissive", or "substitute". It's never an adjective.

"sub query" -> "subquery"

---

documentation/src/test/java/org/hibernate/userguide/associations/NotFoundTest.java
hibernate-core/src/main/java/org/hibernate/cfg/BinderHelper.java
hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityAssociationMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ForeignKeyDescriptor.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddedForeignKeyDescriptor.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EntityCollectionPart.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmMappingModelHelper.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java
hibernate-core/src/main/java/org/hibernate/spi/NavigablePath.java
hibernate-core/src/test/java/org/hibernate/orm/test/hql/CollectionMapWithComponentValueTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/CompareEntityValuedPathsTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/EntityJoinTest.java

https://hibernate.atlassian.net/browse/HHH-15349

HHH-15349 Fix rendering of EntityValuedPathInterpretation when comparing different model parts

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EntityCollectionPart.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ql/MapIssueTest.java

https://hibernate.atlassian.net/browse/HHH-15357

HHH-15357 Fix access to mapped by map key

---

hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/H2SqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/OrderedSetAggregateTest.java

https://hibernate.atlassian.net/browse/HHH-15360

HHH-15360 Fix listagg rendering on older H2 versions

---

hibernate-core/src/main/java/org/hibernate/type/descriptor/java/CalendarDateJavaType.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/CalendarJavaType.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/CalendarTimeJavaType.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/DateJavaType.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/JdbcTimestampJavaType.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/LocalDateJavaType.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/LocalDateTimeJavaType.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/LocalTimeJavaType.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/results/ImplicitSelectWithJoinTests.java
hibernate-core/src/test/java/org/hibernate/orm/test/sql/exec/HqlUpdateExecutionTests.java

https://hibernate.atlassian.net/browse/HHH-15361

HHH-15361 Fix update assignment issues due to missing JavaType#isWider impls

---

hibernate-core/src/main/java/org/hibernate/mapping/ToOne.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/mappingexception/Person.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/mappingexception/UnmappedAssociationExceptioTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/mappingexception/unmapped_association.hbm.xml

https://hibernate.atlassian.net/browse/HHH-15354

HHH-15354 Throw MappingException instead of NPE for hbm referencing unmapped class

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntitySelectFetchInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/EagerManyToOneBatchTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/LazyManyToOneBatchTest.java

https://hibernate.atlassian.net/browse/HHH-15346

HHH-15346 @ManyToOne associations not loaded correctly with default EAGER and batch fetch property set

---

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/test/bundles/prova/META-INF/persistence.xml
hibernate-core/src/test/java/org/hibernate/orm/test/where/annotations/NullWhereClauseTest.java

https://hibernate.atlassian.net/browse/HHH-15358

HHH-15358  @Where annotation with globally_quoted_identifiers causes Unable to determine TableReference Exception

---

hibernate-core/src/main/java/org/hibernate/spi/NavigablePath.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/inheritance/Animal.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/inheritance/AnimalReport.hbm.xml
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/inheritance/AnimalReport.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/inheritance/Cat.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/inheritance/CatName.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/inheritance/Dog.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/inheritance/DogName.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/inheritance/JoinedSubclassesWithSameFieldNamesButDifferentTypesTest.java

https://hibernate.atlassian.net/browse/HHH-15354

HHH-15369 UnknownTableReferenceException when two subclasses have same field with different type

---

hibernate-core/src/main/java/org/hibernate/ScrollableResults.java
hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
hibernate-core/src/main/java/org/hibernate/internal/AbstractScrollableResults.java
hibernate-core/src/main/java/org/hibernate/internal/EmptyScrollableResults.java
hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesCacheHit.java
hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesResultSetImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/spi/JdbcValues.java

For anyone who actually uses `ScrollableResults`, this is pretty useful!

HHH-15352 add ScrollableResults.setFetchSize()

---

hibernate-core/src/main/java/org/hibernate/action/internal/EntityUpdateAction.java
hibernate-core/src/test/java/org/hibernate/orm/test/cascade/circle/delete/Address.java
hibernate-core/src/test/java/org/hibernate/orm/test/cascade/circle/delete/CascadeDeleteTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/cascade/circle/delete/Person.java

https://hibernate.atlassian.net/browse/HHH-15218

HHH-15218 @OptimisticLocking(DIRTY) leads to wrong query during delete of circular reference

---

hibernate-core/src/main/java/org/hibernate/engine/jndi/internal/JndiServiceImpl.java

- https://hibernate.atlassian.net/browse/HHH-15322

HHH-15322 Allow JNDI lookups using the osgi scheme

---

hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java

HHH-15382 CockroachDB doesn't support value propagation

---

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/PowerFunctionTest.java

https://hibernate.atlassian.net/browse/HHH-15395

HHH-15395 HibernateCriteriaBuider#power(Expression<? extends Number> x, Number y) throws ClassCastException

---

hibernate-core/src/main/java/org/hibernate/query/sqm/function/SelfRenderingSqmAggregateFunction.java
hibernate-core/src/main/java/org/hibernate/query/sqm/function/SelfRenderingSqmOrderedSetAggregateFunction.java
hibernate-core/src/main/java/org/hibernate/query/sqm/function/SelfRenderingSqmWindowFunction.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/SqmTypedNode.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmCastTarget.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmDistinct.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmDurationUnit.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmExtractUnit.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmFunction.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmTrimSpecification.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmDynamicInstantiation.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmDynamicInstantiationArgument.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectableNode.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelection.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/ToHqlStringTest.java

https://hibernate.atlassian.net/browse/HHH-15390

HHH-15390 Calling  SqmQuery#getSqmStatement()#toHqlString() causes ClassCastExpection when using distinct in Criteria or HQL query

---

migration-guide.adoc

Added a link to the previous minor release migration guide

Tweak to the migration guide 

---

documentation/src/main/asciidoc/topical/index.adoc

HHH-15401 - Update the topical guide

---

hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/mappingexception/Address.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/mappingexception/Employee.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/mappingexception/UnmappedCollectionExceptionTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/mappingexception/unmapped_collection.hbm.xml

https://hibernate.atlassian.net/browse/HHH-15379

HHH-15379 NPE building mapping from HBM for collections targeting a class that does not have an HBM mapping

---

hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java
hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureOutputsImpl.java
hibernate-core/src/main/java/org/hibernate/resource/jdbc/internal/ResourceRegistryStandardImpl.java
hibernate-core/src/main/java/org/hibernate/result/internal/OutputsImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/procedure/StoreProcedureStatementsClosedTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/sql/refcursor/CursorFromCallableTest.java
hibernate-testing/src/main/java/org/hibernate/testing/orm/jdbc/PreparedStatementSpyConnectionProvider.java

https://hibernate.atlassian.net/browse/HHH-15403

HHH-15403 Likely Statement leak on invoking a stored procedure

---

hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/InformixDialectTestCase.java
hibernate-core/src/main/java/org/hibernate/boot/MetadataSources.java
hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataImpl.java
hibernate-core/src/main/java/org/hibernate/query/spi/QueryEngine.java

- https://hibernate.atlassian.net/browse/HHH-15407
- https://hibernate.atlassian.net/browse/HHH-15408
- https://hibernate.atlassian.net/browse/HHH-15409

Quarkus compatibility candidate changes

---

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java
hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/HibernateMethodLookupDispatcher.java
hibernate-core/src/main/java/org/hibernate/internal/util/securitymanager/SystemSecurityManager.java
hibernate-core/src/main/java/org/hibernate/jpa/internal/util/PersistenceUtilHelper.java
hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/ByteBuddyProxyFactory.java
hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/AbstractMapper.java
hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/lazy/initializor/AbstractCollectionInitializor.java

- https://hibernate.atlassian.net/browse/HHH-15411

HHH-15411 Introduce a system property to fully disable Hibernate's use of a SecurityManager

---

hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
hibernate-core/src/main/java/org/hibernate/query/sqm/NodeBuilder.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmLikePredicate.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/ILikeTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/LikeEscapeParameterTest.java

https://hibernate.atlassian.net/browse/HHH-15392

HHH-15392 Reinstantiate support for Character values for like expression escape character 

---

documentation/src/test/java/org/hibernate/userguide/inheritance/SingleTableDiscriminatorFormulaTest.java
documentation/src/test/java/org/hibernate/userguide/locking/ExplicitLockingTest.java
documentation/src/test/java/org/hibernate/userguide/mapping/generated/GeneratedTest.java
documentation/src/test/java/org/hibernate/userguide/mapping/identifier/RowIdTest.java
documentation/src/test/java/org/hibernate/userguide/schema/BaseSchemaGeneratorTest.java
documentation/src/test/java/org/hibernate/userguide/schema/H2SchemaGenerationTest.java
documentation/src/test/java/org/hibernate/userguide/schema/PostgreSQLSchemaGenerationTest.java
documentation/src/test/java/org/hibernate/userguide/sql/MySQLStoredProcedureTest.java
documentation/src/test/java/org/hibernate/userguide/sql/OracleCustomSQLWithStoredProcedureTest.java
documentation/src/test/java/org/hibernate/userguide/sql/OracleStoredProcedureTest.java
hibernate-c3p0/src/test/java/org/hibernate/test/c3p0/JdbcCompatibilityTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/procedure/StoreProcedureRefCursorOutParameterByNameTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/procedure/StoreProcedureRefCursorOutParameterByPositionTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/procedure/MySQLStoredProcedureTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/SQLServer2008NationalizedScalarQueryTest.java
hibernate-envers/src/main/java/org/hibernate/envers/enhanced/OrderedSequenceStructure.java
hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/SinglePropertyMapper.java
hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/basic/EmptyStringTest.java
hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/reventity/MonotonicRevisionNumberTest.java

https://hibernate.atlassian.net/browse/HHH-15406
https://hibernate.atlassian.net/browse/HHH-15413
https://hibernate.atlassian.net/browse/HHH-15414

HHH-15406 Tests annotated with org.hibernate.testing.RequiresDialect having as value a deprecated dialect are not executed

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/DiscriminatedCollectionPart.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AnyDiscriminatorSqmPath.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AnyDiscriminatorSqmPathSource.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AnyMappingDomainTypeImpl.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AnyMappingSqmPathSource.java
hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
hibernate-core/src/main/java/org/hibernate/query/sqm/SemanticQueryWalker.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmTreePrinter.java
hibernate-core/src/main/java/org/hibernate/query/sqm/spi/BaseSemanticQueryWalker.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/DiscriminatedAssociationTypePathInterpretation.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmAnyDiscriminatorValue.java
hibernate-core/src/test/java/org/hibernate/orm/test/any/annotations/AnyTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/any/annotations/EmbeddedAnyTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/any/annotations/Property.java
hibernate-core/src/test/java/org/hibernate/orm/test/any/annotations/PropertyHolder.java

https://hibernate.atlassian.net/browse/HHH-15323

HHH-15323 @AnyDiscriminator Unable to filter a polymorphic relationship in a query

---

hibernate-core/src/main/java/org/hibernate/boot/registry/classloading/internal/AggregatedServiceLoader.java

@yrodiere could you have a quick look?
- https://hibernate.atlassian.net/browse/HHH-15412

HHH-15412 Cleanup: remove reflection keeping JDK8 compatibility afloat in AggregatedServiceLoader

---

documentation/documentation.gradle
documentation/src/main/asciidoc/quickstart/tutorials/pom.xml

https://hibernate.atlassian.net/browse/HHH-15420

HHH-15420 Getting Started Guide Code does not build

---

hibernate-core/src/main/java/org/hibernate/query/results/Builders.java
hibernate-core/src/main/java/org/hibernate/query/results/implicit/ImplicitFetchBuilderDiscriminatedAssociation.java
hibernate-core/src/test/java/org/hibernate/orm/test/any/annotations/EagerAnyDiscriminatorQueryTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/any/annotations/LazyAnyDiscriminatorQueryTest.java

https://hibernate.atlassian.net/browse/HHH-15423

HHH-15423 @Any discriminated association fails to be implicitly fetched due to UnsupportedOperationException

---

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/named/basic/LoadFetchGraphWithEagerSelfReferencingEagerToOneTest.java
hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/EntityManagerFactoryExtension.java

https://hibernate.atlassian.net/browse/HHH-15391

HHH-15391 StackOverflow when applying a load entity graphs to a query

---

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/query/results/Builders.java
hibernate-core/src/main/java/org/hibernate/query/results/FetchBuilder.java
hibernate-core/src/main/java/org/hibernate/query/results/implicit/ImplicitFetchBuilderBasic.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/CompositeKeyNativeQueryTest.java

https://hibernate.atlassian.net/browse/HHH-15418

HHH-15418  Composite primary key with NativeQuery & alias not working

---

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmPath.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQueryPart.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/paths/AbstractPathImplTest.java

https://hibernate.atlassian.net/browse/HHH-15432
https://hibernate.atlassian.net/browse/HHH-15433

HHH-15432, HHH-15433 Some fixes

---

hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java

https://hibernate.atlassian.net/browse/HHH-15416

HHH-15416 Improve error messages when FormatMapper is missing

---

hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLPGObjectJdbcType.java
hibernate-core/src/main/java/org/hibernate/internal/util/config/ConfigurationHelper.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/internal/Scale6IntervalSecondDdlType.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/spi/DdlTypeRegistry.java

https://hibernate.atlassian.net/browse/HHH-15438
https://hibernate.atlassian.net/browse/HHH-15441

HHH-15438, HHH-15441 Some UX fixes

---

Jenkinsfile
databases/mssqlserver/resources/hibernate.properties
docker_db.sh
gradle/databases.gradle
hibernate-core/src/test/java/org/hibernate/orm/test/dialect/functional/SQLServerDialectSequenceInformationTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/procedure/SQLServerStoredProcedureCrossDatabaseTest.java
settings.gradle

Promoting from draft:
- https://hibernate.atlassian.net/browse/HHH-15448

HHH-15448 Upgrade tested MSSQL JDBC driver to version 11.2.0.jre11

---

hibernate-core/src/main/java/org/hibernate/cfg/OneToOneSecondPass.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/various/OneToOneOptimisticLockTest.java

https://hibernate.atlassian.net/browse/HHH-15440

HHH-15440 @OneToOne and @OptimisticLock(excluded = true) not working correctly

---

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/AbstractSqmPredicate.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmBooleanExpressionPredicate.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmGroupedPredicate.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmJunctionPredicate.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmNegatedPredicate.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/ExpressionsTest.java

https://hibernate.atlassian.net/browse/HHH-15452

HHH-15452 Predicate add expression results in UnsupportedOperationException

---

documentation/src/main/asciidoc/userguide/chapters/caching/Caching.adoc

https://hibernate.atlassian.net/browse/HHH-15455

HHH-15455 User Guide Contains a reference to hibernate-ehcache, no longer supported

---

hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcSelectExecutorStandardImpl.java
hibernate-core/src/main/java/org/hibernate/sql/exec/spi/ExecutionContext.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/AssemblerCreationState.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchSelectImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/ResultsHelper.java
hibernate-core/src/test/java/org/hibernate/orm/test/batchfetch/EagerManyToOneStreamTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/batchfetch/EagerManyToOneTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/batchfetch/LazyManyToOneStreamTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/batchfetch/LazyManyToOneTest.java

https://hibernate.atlassian.net/browse/HHH-15449

HHH-15449 @ManyToOne associations not loaded correctly with default EAGER and batch fetch property set when using TypedQuery.resultStream

---

hibernate-core/src/main/java/org/hibernate/collection/spi/AbstractPersistentCollection.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/AbstractCollectionInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/fetch/FetchModeSubselectTest.java

https://hibernate.atlassian.net/browse/HHH-15453
The hql query in translated into
select u1_0.USER_ID, u1_0.AGENCY_ID, u1_0.USER_NAME 
from
USER_TABLE u1_0 
where
u1_0.USER_ID=2
with the following Initialized
- EntitySelectFetchInitializer [User.agency] 
- SelectEagerCollectionInitializer [User.roles] << has no owner
- EntityResultInitializer [User]
EntitySelectFetchInitializer#initializeInstance() triggers: internalLoad of Agency before the User.roles collection owner has been set, the following query is executed:
select a1_0.AGENCY_ID,  a1_0.AGENCY_NAME 
from
AGENCY_TABLE a1_0 
where
a1_0.AGENCY_ID=?
with the following Initialized:
- SelectEagerCollectionInitializer [Agency.users]
- EnityResultInitializer [Agency]  
ListReusltsConsumers calls …

 java.lang.NullPointerException: Cannot invoke "org.hibernate.engine.spi.EntityEntry.getEntityKey()" because "ownerEntry" is nullHHH-15453 

---

hibernate-core/src/main/java/org/hibernate/sql/results/internal/TupleImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/tuple/TupleQueryRetrievePrimitiveTest.java

Same as #5218 for main branch (the same issue existed here as well)

HHH-15454 Retrieve primitives from tuples

---

hibernate-core/src/main/java/org/hibernate/type/TypeHelper.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/embeddables/EmbeddableWithManyToManyTest.java

https://hibernate.atlassian.net/browse/HHH-15359

HHH-15359 The entity returned by a merge doesn't contain @ManyToMany relation when the collection resides in @Embeddable

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java
hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/InformixDialectTestCase.java
hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/SybaseASESqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/function/FormatFunction.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractNaturalIdLoader.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSqlAstCreationState.java
hibernate-core/src/main/java/org/hibernate/persister/entity/UnionSubclassEntityPersister.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/StringBuilderSqlAppender.java
hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/ColumnReference.java
hibernate-core/src/main/java/org/hibernate/type/BasicArrayType.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/PrimitiveByteArrayJavaType.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JdbcLiteralFormatter.java
hibernate-core/src/test/java/org/hibernate/orm/test/sql/ast/SmokeTests.java
hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java

https://hibernate.atlassian.net/browse/HHH-15461

HHH-15461 Replace uses of method references for SqlAppender with proper implementation

---

hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/ColumnReference.java

https://hibernate.atlassian.net/browse/HHH-15462
Depends on https://github.com/hibernate/hibernate-orm/pull/5231

HHH-15462 Optimize ColumnReference rendering and reduce buffering

---

settings.gradle

https://hibernate.atlassian.net/browse/HHH-15388

HHH-15388 Upgrade to Micrometer 1.9.3

---

databases/cockroachdb/matrix.gradle
databases/pgsql/matrix.gradle
gradle/libraries.gradle
hibernate-spatial/databases/postgispg96/matrix.gradle

- https://hibernate.atlassian.net/browse/HHH-15451

Backport: HHH-15451 Upgrade to version 42.5.0 of the PostgreSQL JDBC driver

---

documentation/src/test/java/org/hibernate/userguide/mapping/basic/JsonMappingTests.java
hibernate-core/src/main/java/org/hibernate/type/jackson/JacksonJsonFormatMapper.java
hibernate-core/src/main/java/org/hibernate/type/jackson/JacksonXmlFormatMapper.java
hibernate-core/src/main/java/org/hibernate/type/jakartajson/JsonBJsonFormatMapper.java
hibernate-core/src/main/java/org/hibernate/type/jaxb/JaxbXmlFormatMapper.java

https://hibernate.atlassian.net/browse/HHH-15458

HHH-15458 Interpret String with JSON/XML type code as plain JSON/XML

---

hibernate-core/hibernate-core.gradle
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/InlineDirtyCheckingHandler.java
hibernate-core/src/main/java/org/hibernate/cfg/AccessType.java
hibernate-core/src/main/java/org/hibernate/cfg/InheritanceState.java
hibernate-core/src/main/java/org/hibernate/cfg/PropertyContainer.java
hibernate-core/src/main/java/org/hibernate/internal/util/ReflectHelper.java
hibernate-core/src/main/java/org/hibernate/mapping/Component.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableInstantiatorRecordIndirecting.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableInstantiatorRecordStandard.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/ManagedTypeRepresentationResolverStandard.java
hibernate-core/src/test/java17/org/hibernate/orm/test/records/OutOfTheBoxRecordAsEmbeddableTest.java
hibernate-core/src/test/java17/org/hibernate/orm/test/records/RecordAsEmbeddableEnhancementTest.java
settings.gradle

https://hibernate.atlassian.net/browse/HHH-15072

HHH-15072 Add out of the box support for records as embeddables

---

hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java
hibernate-core/src/test/java/org/hibernate/orm/test/filter/hql/FilterWithDifferentConditionsTest.java

https://hibernate.atlassian.net/browse/HHH-13485

HHH-13485 FilterJoinTable does not to use the defualt condition

---

hibernate-platform/hibernate-platform.gradle
tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle

https://hibernate.atlassian.net/browse/HHH-15381

HHH-15381 Try to fix gradle plugin publishing and platform publishing

---

hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/collectionelement/OrphanRemovalOfAnEntityWithElementCollectionTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/collectionelement/OrphanRemovalOfAnEntityWithElementCollectionWithUpdatesAndInsertsOrderTest.java

https://hibernate.atlassian.net/browse/HHH-15159
Not sure if executing `CollectionRemoveAction` first can cause any issue.

HHH-15159 Orphan removal of an entity with an @ElementCollection causes a ConstraintViolationException

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DerbyLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DerbyLegacySqlAstTranslator.java
hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/DerbyLegacyDialectTestCase.java
hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/unit/sequence/DerbyTenFiveDialectSequenceInformationExtractorTest.java
hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/unit/sequence/DerbyTenSevenDialectSequenceInformationExtractorTest.java
hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/unit/sequence/DerbyTenSixDialectSequenceInformationExtractorTest.java
hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java

https://hibernate.atlassian.net/browse/HHH-15191

HHH-15191 - Remove support for Derby versions older than 10.14.2.0

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacySqlAstTranslator.java

https://hibernate.atlassian.net/browse/HHH-15190

HHH-15190 - Remove support for H2 versions older than 1.4.197

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacySqlAstTranslator.java
hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/cockroachdb/CockroachDB202SpatialDialect.java

…y dialects
https://hibernate.atlassian.net/browse/HHH-15195

HHH-15195 - Remove support for CockroachDB versions older than 21.1

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacySqlAstTranslator.java
hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/SQLServer2005DialectTestCase.java
hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/unit/lockhint/SQLServer2005LockHintsTest.java
hibernate-core/src/main/java/org/hibernate/dialect/function/SQLServerFormatEmulation.java
hibernate-core/src/test/java/org/hibernate/orm/test/dialect/SQLServer2008DialectTestCase.java
hibernate-core/src/test/java/org/hibernate/orm/test/dialect/unit/lockhint/SQLServerLockHintsTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/SQLServerNationalizedScalarQueryTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/type/SQLServerNVarCharTypeTest.java

https://hibernate.atlassian.net/browse/HHH-15180

HHH-15180 - Remove support for SQL Server versions older than 2008

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MariaDBLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MariaDBLegacySqlAstTranslator.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacySqlAstTranslator.java
hibernate-core/src/test/java/org/hibernate/orm/test/dialect/functional/MariaDBExtractSequenceMetadataTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/dialect/functional/SequenceInformationMariaDBTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/dialect/unit/lockhint/MySQLStorageEngineTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/temporal/MySQLTimestampFspFunctionTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/temporal/MySQLTimestampPropertyTest.java

HHH-15179 - Moving support for MySQL versions older than 5.7 into community dialects (https://hibernate.atlassian.net/browse/HHH-15179)
HHH-15182 - Remove support for MariaDB versions older than 10.3 (https://hibernate.atlassian.net/browse/HHH-15182)

HHH-15179 / HHH-15182

---

hibernate-core/src/main/java/org/hibernate/boot/archive/scan/spi/ClassFileArchiveEntryHandler.java
local-build-plugins/build.gradle
local-build-plugins/src/main/java/org/hibernate/orm/post/IndexManager.java
local-build-plugins/src/main/java/org/hibernate/orm/post/LoggingReportTask2.java
settings.gradle

https://hibernate.atlassian.net/browse/HHH-15465

HHH-15465 Upgrade to Jandex 3.0.0

---

hibernate-core/src/main/java/org/hibernate/engine/spi/FilterDefinition.java
hibernate-core/src/main/java/org/hibernate/internal/FilterHelper.java
hibernate-core/src/main/java/org/hibernate/internal/FilterImpl.java
hibernate-core/src/main/java/org/hibernate/tuple/TenantIdBinder.java
hibernate-core/src/main/java/org/hibernate/tuple/TenantIdGeneration.java
hibernate-core/src/test/java/org/hibernate/orm/test/tenantlongid/Account.java
hibernate-core/src/test/java/org/hibernate/orm/test/tenantlongid/Client.java
hibernate-core/src/test/java/org/hibernate/orm/test/tenantlongid/TenantLongIdTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/tenantuuid/Account.java
hibernate-core/src/test/java/org/hibernate/orm/test/tenantuuid/Client.java
hibernate-core/src/test/java/org/hibernate/orm/test/tenantuuid/TenantUuidTest.java

See https://hibernate.atlassian.net/browse/HHH-15483.

HHH-15483  allow @TenantId properties of type UUID, Long, Integer

---

hibernate-graalvm/hibernate-graalvm.gradle
hibernate-graalvm/src/main/java/org/hibernate/graalvm/internal/GraalVMStaticAutofeature.java
hibernate-graalvm/src/main/java/org/hibernate/graalvm/internal/QueryParsingSupport.java

- https://hibernate.atlassian.net/browse/HHH-15484
Meant for 6.2 exclusively.

HHH-15484 Switch GraalVM native-image dependencies to org.graalvm.sdk:graal-sdk

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacySqlAstTranslator.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseLegacySqlAstTranslator.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseLegacySqmToSqlAstConverter.java
hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/unit/lockhint/SybaseASE15LockHintsTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/dialect/function/SybaseASEFunctionTest.java

https://hibernate.atlassian.net/browse/HHH-15192

HHH-15192 - Remove support for Sybase ASE versions older than 16

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2LegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2LegacySqlAstTranslator.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2iLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2iLegacySqlAstTranslator.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2zLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2zLegacySqlAstTranslator.java
hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/DB2LegacyDialectTestCase.java
hibernate-core/src/main/java/org/hibernate/dialect/sequence/LegacyDB2SequenceSupport.java

Remove support for DB2 versions older than 10.5 (https://hibernate.atlassian.net/browse/HHH-15181)
Remove support for DB2i versions older than 7.1 (https://hibernate.atlassian.net/browse/HHH-15197)
Remove support for DB2z versions older than 12.1 (https://hibernate.atlassian.net/browse/HHH-15198)

HHH-15181 / HHH-15197 / HHH-15198

---

hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/AbstractInformationExtractorImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/schematools/PrimaryKeyColumnOrderTest.java

https://hibernate.atlassian.net/browse/HHH-15356

HHH-15356 Unable to get primary information on some dialects (ex: Oracle) when the PK column's position doesn't match the alphabetical name's order

---

hibernate-core/src/main/java/org/hibernate/event/internal/WrapVisitor.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/collectionelement/recreate/BytecodeEnhancementElementCollectionRecreateCollectionsInDefaultGroupTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/collectionelement/recreate/BytecodeEnhancementElementCollectionRecreateTest.java

https://hibernate.atlassian.net/browse/HHH-14387

HHH-14387 Fix regression when bytecode enhancement enabled

---

hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/DirtyTrackingCollectionNotInDefaultFetchGroupTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/DirtyTrackingNotInDefaultFetchGroupPersistTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/MultipleBagsNotInLazyFetchGroupTest.java

https://hibernate.atlassian.net/browse/HHH-15485

HHH-15485 Tests for Collections in default FetchGroup are not enabling this property

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/naturalid/NaturalIdAndLazyLoadingTest.java

https://hibernate.atlassian.net/browse/HHH-15481

HHH-15481 NaturalId and Lazy create a class cast Exception

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/naturalid/NaturalIdAndLazyLoadingTest.java

https://hibernate.atlassian.net/browse/HHH-15481

Backport HHH-15481 NaturalId and Lazy create a class cast Exception #5266

---

hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java

See https://hibernate.atlassian.net/browse/HHH-15446

HHH-15446 - allow Dialect version to be specified separately from the dialect class name

---

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmCaseSimple.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/SelectCaseTest.java

https://hibernate.atlassian.net/browse/HHH-15482

HHH-15482 CoercionException in criteria simple case statement

---

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmCaseSimple.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/SelectCaseTest.java

https://hibernate.atlassian.net/browse/HHH-15482

Backport HHH-15482 for 6.1CoercionException in criteria simple case statement

---

Jenkinsfile
docker_db.sh
hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/VarcharUUIDJdbcType.java
hibernate-core/src/test/java/org/hibernate/orm/test/id/uuid/interpretation/UUIDBasedIdInterpretationTest.java
migration-guide.adoc

https://hibernate.atlassian.net/browse/HHH-15503

HHH-15503 Add UUID support for MariaDB 10.7

---

documentation/src/test/java/org/hibernate/userguide/mapping/identifier/UuidGeneratedValueTest.java
hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
migration-guide.adoc

https://hibernate.atlassian.net/browse/HHH-15504
Depends on https://github.com/hibernate/hibernate-orm/pull/5282

HHH-15504 Add UUID support for SQL Server

---

hibernate-core/src/main/java/org/hibernate/loader/JoinWalker.java
hibernate-core/src/main/java/org/hibernate/loader/entity/EntityJoinWalker.java
hibernate-core/src/main/java/org/hibernate/loader/entity/NaturalIdEntityJoinWalker.java
hibernate-core/src/test/java/org/hibernate/test/annotations/naturalid/NaturalIdOnManyToOne.java
hibernate-core/src/test/java/org/hibernate/test/annotations/naturalid/NaturalIdOnSingleManyToOneTest.java

https://hibernate.atlassian.net/browse/HHH-14943

HHH-14943 byNaturalId API creates unparseable query (AND keyword instead of WHERE)

---

hibernate-core/src/test/java/org/hibernate/orm/test/annotations/naturalid/NaturalIdOnSingleManyToOneTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/naturalid/NaturalIdTest.java

https://hibernate.atlassian.net/browse/HHH-14943

HHH-14943 Add test for issue

---

hibernate-core/src/main/java/org/hibernate/Session.java
hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java
hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java
hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
hibernate-core/src/test/java/org/hibernate/test/proxy/ProxyTest.java

https://hibernate.atlassian.net/browse/HHH-15508

HHH-15508 Backport Session#getReference(Object) to branch 5.6

---

hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java
hibernate-core/src/main/java/org/hibernate/dialect/DerbyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java

add some comments and two missing function registrations

---

hibernate-core/src/main/java/org/hibernate/cfg/annotations/MapBinder.java
hibernate-core/src/test/java/org/hibernate/test/jpa/ql/MapKeySubquerySchemaTest.java

https://hibernate.atlassian.net/browse/HHH-15523

HHH-15523 Make use of SqlStringGenerationContext in MapBinder#getFromAndWhereFormula

---

hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
hibernate-core/src/test/java/org/hibernate/orm/test/dialect/unit/CockroachDialectVersionTest.java

HHH-15511 - fix version determination for CockroachDB

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/HSQLLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/HSQLLegacySqlAstTranslator.java

HHH-15490 - Remove support for HSQLDB versions older than 2.6.1

---

hibernate-core/src/main/java/org/hibernate/boot/model/naming/Identifier.java
hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/temptable/TemporaryTable.java
hibernate-core/src/test/java/org/hibernate/orm/test/persister/entity/TemporaryTableSchemaTest.java

https://hibernate.atlassian.net/browse/HHH-15517

HHH-15517 Fix for temporary table prefixing the qualified table name instead of just table name

---

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/InsertSelectTests.java

https://hibernate.atlassian.net/browse/HHH-15527
Is based on https://github.com/hibernate/hibernate-orm/pull/5307

HHH-15527 Make sure that only a single query is executed when running an insert-select with an assigned id

---

hibernate-core/src/main/java/org/hibernate/cfg/annotations/PropertyBinder.java
hibernate-core/src/test/java/org/hibernate/test/annotations/various/OneOneGeneratedValueTest.java

https://hibernate.atlassian.net/browse/HHH-15520

HHH-5520 ValueGeneration on @OneToOne leads to boot error 

---

hibernate-core/src/main/java/org/hibernate/cfg/annotations/PropertyBinder.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/various/OneOneGeneratedValueTest.java

https://hibernate.atlassian.net/browse/HHH-15520

HHH-15520  ValueGeneration on @OneToOne leads to boot error 

---

hibernate-core/src/main/java/org/hibernate/Hibernate.java
hibernate-core/src/main/java/org/hibernate/collection/spi/LazyInitializable.java
hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentCollection.java
hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/lazy/proxy/CollectionProxy.java
hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/lazy/proxy/MapProxy.java
hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/lazy/proxy/SortedMapProxy.java
hibernate-envers/src/test/java/org/hibernate/orm/test/envers/entities/collection/MultipleCollectionEntity.java
hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/lazy/IsCollectionInitializedBytecodeEnhancementTest.java
hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/lazy/IsCollectionInitializedTest.java

https://hibernate.atlassian.net/browse/HHH-15522

HHH-15522 Hibernate.isInitialized method not working for Envers Collections

---

hibernate-core/src/main/java/org/hibernate/Hibernate.java
hibernate-core/src/main/java/org/hibernate/collection/spi/LazyInitializable.java
hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentCollection.java
hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/lazy/proxy/CollectionProxy.java
hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/lazy/proxy/MapProxy.java
hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/lazy/proxy/SortedMapProxy.java
hibernate-envers/src/test/java/org/hibernate/envers/test/entities/collection/MultipleCollectionEntity.java
hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/lazy/IsCollectionInitializedBytecodeEnhancementTest.java
hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/lazy/IsCollectionInitializedTest.java

https://hibernate.atlassian.net/browse/HHH-15522
Backport of #5302 to branch 5.6.

Backport HHH-15522 to branch 5.6 - Hibernate.isInitialized method not working for Envers Collections

---

hibernate-core/src/main/java/org/hibernate/Hibernate.java
hibernate-core/src/main/java/org/hibernate/collection/spi/LazyInitializable.java
hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentCollection.java
hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/lazy/proxy/CollectionProxy.java
hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/lazy/proxy/MapProxy.java
hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/lazy/proxy/SortedMapProxy.java
hibernate-envers/src/test/java/org/hibernate/orm/test/envers/entities/collection/MultipleCollectionEntity.java
hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/lazy/IsCollectionInitializedBytecodeEnhancementTest.java
hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/lazy/IsCollectionInitializedTest.java

https://hibernate.atlassian.net/browse/HHH-15522
Backport of #5302 to branch 6.1.

Backport HHH-15522 to branch 6.1 - Hibernate.isInitialized method not working for Envers Collections

---

hibernate-core/src/main/java/org/hibernate/dialect/MySQLSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java

https://hibernate.atlassian.net/browse/HHH-15537

HHH-15537 Implement lateral subquery emulation when nested correlation is unsupported

---

.github/workflows/contributor-build.yml
Jenkinsfile
README.adoc
ci/build.sh
ci/database-start.sh
docker_db.sh
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/always/GeneratedAlwaysTest.java

https://hibernate.atlassian.net/browse/HHH-15532

HHH-15532 Update PostgreSQL testing to version 10 and 14

---

documentation/src/test/java/org/hibernate/userguide/locking/ExplicitLockingTest.java
documentation/src/test/java/org/hibernate/userguide/mapping/identifier/RowIdTest.java
documentation/src/test/java/org/hibernate/userguide/sql/OracleCustomSQLWithStoredProcedureTest.java
documentation/src/test/java/org/hibernate/userguide/sql/OracleStoredProcedureTest.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacySqlAstTranslator.java
hibernate-core/src/test/java/org/hibernate/orm/test/generatedkeys/select/SelectGeneratorTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/id/array/ByteArrayIdTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/id/array/PrimitiveByteArrayIdTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/naturalid/MutableNaturalIdTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/PartiallyGeneratedComponentTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/nationalized/StringNationalizedTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/ops/OracleNoColumnInsertTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/queryhint/OracleQueryHintTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/rowid/RowIdTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/rowid/RowIdTest2.java
hibernate-core/src/test/java/org/hibernate/orm/test/schemavalidation/SynonymValidationTest.java
hibernate-envers/src/main/java/org/hibernate/envers/enhanced/OrderedSequenceStructure.java
hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/SinglePropertyMapper.java

HHH-15489 - Remove support for Oracle versions older than 11.2

---

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java

https://hibernate.atlassian.net/browse/HHH-15514

HHH-15514 Fix security manager class rewriting issue

---

hibernate-core/src/test/java/org/hibernate/orm/test/bidi/Auction.java
hibernate-core/src/test/java/org/hibernate/orm/test/bidi/Auction3.hbm.xml
hibernate-core/src/test/java/org/hibernate/orm/test/bidi/AuctionTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bidi/AuctionTest2.java
hibernate-core/src/test/java/org/hibernate/orm/test/bidi/AuctionWithAbstractBidClassTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bidi/SpecialBid.java

I believe the problems described in the aforementioned issues are solved in v6.
Providing a test to cover these use cases.
Some cleanup done also.

HHH-987 / HHH-992 

---

hibernate-core/src/main/java/org/hibernate/type/EntityType.java
hibernate-core/src/main/java/org/hibernate/type/OneToOneType.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetoone/EmbeddedIdTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/cache/MainObject.hbm.xml
hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/cache/MainObject.java
hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/cache/Object2.hbm.xml
hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/cache/Object2.java
hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/cache/OneToOneCacheTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/cache/OneToOneConstrainedCacheTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/flush/DirtyFlushTest.java

https://hibernate.atlassian.net/browse/HHH-15045
https://hibernate.atlassian.net/browse/HHH-15235
This PR reverts [HHH-14216](https://hibernate.atlassian.net/browse/HHH-14216), see [discussion](https://github.com/hibernate/hibernate-orm/pull/5061) and [HHH-15540](https://hibernate.atlassian.net/browse/HHH-15540)

HHH-15045 + HHH-15235

---

gradle/published-java-module.gradle
tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle

https://hibernate.atlassian.net/browse/HHH-15534

HHH-15534 Fix publishing of the hibernate-gradle-plugin

---

hibernate-core/src/test/java/org/hibernate/orm/test/bidi/AbstractBid.java
hibernate-core/src/test/java/org/hibernate/orm/test/bidi/Auction3.hbm.xml
hibernate-core/src/test/java/org/hibernate/orm/test/bidi/AuctionWithAbstractBidClassTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bidi/SpecialAuction.java
hibernate-core/src/test/java/org/hibernate/orm/test/bidi/SpecialBid.java

HHH-987/HHH-992 - Correction to the AuctionWithAbstractBidClassTest

---

hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/formula/ManyToManyNotIgnoreLazyFetchingTest.java
hibernate-envers/src/test/java/org/hibernate/orm/test/envers/entities/onetomany/OneToManyNotAuditedNullEntity.java

1. error if a non-@ManyToMany collection is @NotFound
2. disable constraint generation for @NotFound @ManyToMany
3. allow lazy fetching for @NotFound @ManyToMany
4. rework a completely bogus test so it makes sense

HHH-15509 correctly support @NotFound @ManyToMany

---

hibernate-core/src/main/java/org/hibernate/action/internal/CollectionRemoveAction.java
hibernate-core/src/main/java/org/hibernate/action/internal/EntityAction.java
hibernate-core/src/main/java/org/hibernate/action/internal/EntityDeleteAction.java
hibernate-core/src/main/java/org/hibernate/action/internal/EntityIdentityInsertAction.java
hibernate-core/src/main/java/org/hibernate/collection/internal/CustomCollectionTypeSemantics.java
hibernate-core/src/main/java/org/hibernate/engine/internal/ForeignKeys.java
hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
hibernate-core/src/main/java/org/hibernate/engine/spi/CascadingActions.java
hibernate-core/src/main/java/org/hibernate/engine/spi/EntityKey.java
hibernate-core/src/main/java/org/hibernate/engine/spi/PersistenceContext.java
hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java
hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDeleteEventListener.java
hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEventListener.java
hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java
hibernate-core/src/main/java/org/hibernate/persister/collection/BasicCollectionPersister.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java
hibernate-core/src/main/java/org/hibernate/proxy/AbstractLazyInitializer.java
hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java
hibernate-core/src/main/java/org/hibernate/type/CollectionType.java
hibernate-core/src/test/java/org/hibernate/orm/test/collection/delayedOperation/DetachedBagDelayedOperationTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/deleteunloaded/Child.java
hibernate-core/src/test/java/org/hibernate/orm/test/deleteunloaded/DeleteUnloadedProxyTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/deleteunloaded/Parent.java
hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiIdEntityLoadTests.java
hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiLoadTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/readonly/ReadOnlyProxyTest.java

See https://hibernate.atlassian.net/browse/HHH-15509.

HHH-15509 deletion of unloaded entity

---

hibernate-graalvm/src/main/java/org/hibernate/graalvm/internal/GraalVMStaticAutofeature.java
hibernate-graalvm/src/main/java/org/hibernate/graalvm/internal/GraalVMStaticFeature.java
hibernate-graalvm/src/main/java/org/hibernate/graalvm/internal/QueryParsingSupport.java

HHH-15555 Remove use of @AutomaticFeature in GraalVM module

---

hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/discriminator/AbstractAccount.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/discriminator/AccountOwner.hbm.xml
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/discriminator/AccountOwner.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/discriminator/CreditAccount.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/discriminator/DebitAccount.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/discriminator/MultiInheritanceDiscriminatorTest.java

HHH-1134 - tests to verify this use case

---

hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java
hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureParameterImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/procedure/OracleStoredProcedureTest.java

https://hibernate.atlassian.net/browse/HHH-15542

HHH-15542 Cannot invoke "org.hibernate.query.BindableType.getBindableJavaType()" because "parameterType" is null

---

hibernate-core/src/main/java/org/hibernate/cfg/ClassPropertyHolder.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/embeddables/EmbeddableAndMappedSuperClassWithGenericsTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/embeddables/EmbeddableWithGenericAndMappedSuperClassTest.java

https://hibernate.atlassian.net/browse/HHH-15552

HHH-15552 Embeddable type cannot be cast to org.hibernate.usertype.CompositeUserType if referred to from a mapped superclass with generic parameter

---

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/EnhancementInfo.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/basic/BasicEnhancementTest.java

https://hibernate.atlassian.net/browse/HHH-13439

HHH-13439 Encode Hibernate ORM version into build time enhanced entities

---

settings.gradle

https://hibernate.atlassian.net/browse/HHH-15562

HHH-15562 Upgrade to Jandex 3.0.1

---

hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/query/NonWhereCriteriaTest.java
hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/query/Phone.java
hibernate-core/src/test/java/org/hibernate/jpa/test/query/NonWhereQueryTest.java

HHH-15559/HHH-15257 Add tests for issues

---

hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/NonWhereQueryTest.java

HHH-15257 added test (ported over from 5.6)

---

hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/type/TypeHelper.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/embeddables/EmbeddableWithManyToManyTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/cut/CompositeDateTime.java
hibernate-core/src/test/java/org/hibernate/orm/test/cut/CompositeDateTimeUserType.java
hibernate-core/src/test/java/org/hibernate/orm/test/cut/CompositeUserTypeTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/cut/ImmutableCompositeUserTypeTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/cut/ImmutableMonetoryAmount.java
hibernate-core/src/test/java/org/hibernate/orm/test/cut/ImmutableMonetoryAmountUserType.java
hibernate-core/src/test/java/org/hibernate/orm/test/cut/MonetoryAmount.java
hibernate-core/src/test/java/org/hibernate/orm/test/cut/MonetoryAmountUserType.java
hibernate-core/src/test/java/org/hibernate/orm/test/cut/MutualFund.java
hibernate-core/src/test/java/org/hibernate/orm/test/cut/Transaction.hbm.xml
hibernate-core/src/test/java/org/hibernate/orm/test/cut/Transaction.java

https://hibernate.atlassian.net/browse/HHH-15554 Merge of an Entity with an immutable composite user type throws NPE 
https://hibernate.atlassian.net/browse/HHH-15572 Emulation of tuple comparison produces a wrong SQL query, missing a closing parenthesis
https://hibernate.atlassian.net/browse/HHH-15576 Emulation of tuple comparison produces a wrong SQL query for NOT EQUAL operator

HHH 15554 + HHH-15572

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/ops/EnumsParameterTest.java

https://hibernate.atlassian.net/browse/HHH-15498

HHH-15498  Delete Query fails to determine the ValueMapping for SqmParameter

---

hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingImpl.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/discriminator/SingleTableInheritancePersistTest.java

https://hibernate.atlassian.net/browse/HHH-15497
This is an alternative solution to https://github.com/hibernate/hibernate-orm/pull/5275

HHH-15497 Count query when counting polymorphic subclasses by type fails when run twice

---

hibernate-core/src/main/java/org/hibernate/dialect/OracleArrayJdbcType.java

https://hibernate.atlassian.net/browse/HHH-15543

HHH-15543 Don't throw CNFE with OracleDialect when JDBC driver classes are invisible

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/AbstractSchemaValidator.java
hibernate-core/src/test/java/org/hibernate/orm/test/schemavalidation/InstantValidationTest.java

https://hibernate.atlassian.net/browse/HHH-15548

HHH-15548 Fix schema validation issues on PostgreSQL with Instant type

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/function/PostgreSQLMinMaxFunction.java
hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/ArgumentTypesValidator.java
hibernate-core/src/main/java/org/hibernate/type/SqlTypes.java
hibernate-core/src/test/java/org/hibernate/orm/test/aggregation/UuidAggregationTest.java

https://hibernate.atlassian.net/browse/HHH-15495
https://hibernate.atlassian.net/browse/HHH-15578

HHH-15495/HHH-15578 Consider UUID to be comparable

---

hibernate-core/src/main/java/org/hibernate/dialect/HANASqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java

https://hibernate.atlassian.net/browse/HHH-15580

HHH-15580 Emulate lt/gt/le/ge tuple-comparisons when unsupported

---

hibernate-core/src/main/java/org/hibernate/dialect/OracleSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/SqmInsertStrategyHelper.java
hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteInsertHandler.java
hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/TableBasedInsertHandler.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/InsertSelectTests.java

https://hibernate.atlassian.net/browse/HHH-15531

HHH-15531 Use dense_rank instead of row_number when query uses distinct

---

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java

This isn't a standard function, because it can't be implemented on MySQL or Sybase, but still worth having a test for it.

add test for median()

---

documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc
hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java
hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java
hibernate-core/src/main/java/org/hibernate/dialect/function/CountFunction.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/StandardFunctionTests.java

These aren't "standard" functions, but we should test them anyway.

HHH-15518 bless degrees() and radians() as standard functions

---

hibernate-core/src/main/java/org/hibernate/dialect/SpannerDialectTableExporter.java
hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/SpannerSchemaCreationColumnTypesTest.java

https://hibernate.atlassian.net/browse/HHH-15573

HHH-15573 SpannerDialect, schema creation generates SQL containing 'null' instead of the column type

---

documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java
hibernate-core/src/main/java/org/hibernate/jdbc/Expectations.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java

Just want to see how many databases this fails on.

HHH-15588 better support for sinh() and tanh()

---

Jenkinsfile
ci/build.sh

CI: use ci/build.sh in Jenkinsfile and only run checkstyle in the H2 build

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DerbyLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/DerbyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java
hibernate-core/src/test/java/org/hibernate/orm/test/dialect/DialectSQLExceptionConversionTest.java

https://hibernate.atlassian.net/browse/HHH-15592

HHH-15592 Fix NPE for uses of JdbcExceptionHelper.extractSqlState

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/VarcharUUIDJdbcType.java
hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/DateTimeUtils.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/UUIDJdbcType.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/internal/JdbcLiteralFormatterUUIDData.java
hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/LiteralRenderingTest.java
hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/JUnitHelper.java

https://hibernate.atlassian.net/browse/HHH-15590

HHH-15590 Test that JdbcLiteralFormatter works for all supported java types

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/identity/H2FinalTableIdentityColumnSupport.java
hibernate-core/src/main/java/org/hibernate/dialect/identity/H2IdentityColumnSupport.java
hibernate-core/src/main/java/org/hibernate/dialect/identity/IdentityColumnSupport.java
hibernate-core/src/main/java/org/hibernate/id/insert/InsertSelectIdentityInsert.java
hibernate-core/src/test/java/org/hibernate/orm/test/id/IdentityIdEntityTest.java

HHH-15561 - Fixed and added test for issue

---

documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc

...and that it's the same thing as `cross apply`.

explain wtf 'join lateral' means

---

tooling/hibernate-gradle-plugin/src/main/java/org/hibernate/orm/tooling/gradle/Helper.java
tooling/hibernate-gradle-plugin/src/main/java/org/hibernate/orm/tooling/gradle/HibernateOrmPlugin.java
tooling/hibernate-gradle-plugin/src/main/java/org/hibernate/orm/tooling/gradle/HibernateOrmSpec.java
tooling/hibernate-gradle-plugin/src/test/java/org/hibernate/orm/tooling/gradle/JavaProjectTests.java
tooling/hibernate-gradle-plugin/src/test/java/org/hibernate/orm/tooling/gradle/MultiPartNameTests.java
tooling/hibernate-gradle-plugin/src/test/java/org/hibernate/orm/tooling/gradle/TestHelper.java
tooling/hibernate-gradle-plugin/src/test/java/org/hibernate/orm/tooling/gradle/TestsBase.java
tooling/hibernate-gradle-plugin/src/test/resources/projects/multi-part-source-set-name/build.gradle
tooling/hibernate-gradle-plugin/src/test/resources/projects/multi-part-source-set-name/src/mySpecialSourceSet/java/TheEmbeddable.java
tooling/hibernate-gradle-plugin/src/test/resources/projects/multi-part-source-set-name/src/mySpecialSourceSet/java/TheEntity.java
tooling/hibernate-gradle-plugin/src/test/resources/projects/simple-kotlin/build.gradle
tooling/hibernate-gradle-plugin/src/test/resources/projects/simple-kotlin/src/main/kotlin/TheEmbeddable.kt
tooling/hibernate-gradle-plugin/src/test/resources/projects/simple-kotlin/src/main/kotlin/TheEntity.kt

https://hibernate.atlassian.net/browse/HHH-15558
https://hibernate.atlassian.net/browse/HHH-15597

HHH-15558, HHH-15597 Gradle plugin fix backports

---

hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
hibernate-core/src/main/java/org/hibernate/query/criteria/JpaDerivedFrom.java
hibernate-core/src/main/java/org/hibernate/query/criteria/JpaDerivedJoin.java
hibernate-core/src/main/java/org/hibernate/query/criteria/JpaSelectCriteria.java
hibernate-core/src/main/java/org/hibernate/query/hql/internal/QuerySplitter.java
hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmDerivedRoot.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/AbstractSqmSelectQuery.java

https://hibernate.atlassian.net/browse/HHH-15613

HHH-15613 remove 'lateral' from fromRoot rule

---

hibernate-core/src/main/java/org/hibernate/boot/jaxb/hbm/transform/HbmXmlTransformer.java
hibernate-core/src/main/java/org/hibernate/cfg/annotations/reflection/internal/JPAXMLOverriddenAnnotationReader.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/query/Bar.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/query/BarPK.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/query/HbmNamedQueryConfigurationTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/query/HbmOverridesAnnotation.hbm.xml
hibernate-core/src/test/java/org/hibernate/orm/test/hbm/query/HbmOverridesAnnotation.orm.xml

https://hibernate.atlassian.net/browse/HHH-15619
https://hibernate.atlassian.net/browse/HHH-15620

HHH-15619, HHH-15620 Expose HBM query configs through respective hints and don't mark transformed HBM model as metadata complete

---

.github/workflows/contributor-build.yml
Jenkinsfile
ci/build.sh
ci/database-start.sh
docker_db.sh
edb/Dockerfile
edb/docker-entrypoint.sh
gradle/databases.gradle
gradle/java-module.gradle
hibernate-core/hibernate-core.gradle
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/dataTypes/BasicOperationsTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/filter/FilterParameterTests.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/NativeQueryResultTypeAutoDiscoveryTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/always/GeneratedAlwaysTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/type/DateArrayTest.java

https://hibernate.atlassian.net/browse/HHH-15615

HHH-15615 Add EDB PostgreSQL Advanced to test matrix and fix issues

---

Jenkinsfile
nightly.Jenkinsfile

https://hibernate.atlassian.net/browse/HHH-15615

HHH-15528 Build related fixes for Cockroach, and tryout GH actions

---

hibernate-core/src/main/java/org/hibernate/engine/spi/EntityKey.java
hibernate-core/src/main/java/org/hibernate/property/access/spi/EnhancedSetterImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java

https://hibernate.atlassian.net/browse/HHH-15632
https://hibernate.atlassian.net/browse/HHH-15633
https://hibernate.atlassian.net/browse/HHH-15635

HHH-15632, HHH-15633, HHH-15635 Various perf improvements

---

settings.gradle

https://hibernate.atlassian.net/browse/HHH-15637

Byteman upgrade

---

hibernate-core/src/main/java/org/hibernate/engine/spi/EntityKey.java
hibernate-core/src/main/java/org/hibernate/property/access/spi/EnhancedSetterImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java

https://hibernate.atlassian.net/browse/HHH-15632
https://hibernate.atlassian.net/browse/HHH-15633
https://hibernate.atlassian.net/browse/HHH-15635
The second patch didn't apply cleanly, hopefully I didn't screw it up as I edited from commandline. Letting CI figure it out.

Forward-porting #5450 to main

---

documentation/src/main/asciidoc/userguide/chapters/caching/Caching.adoc

https://hibernate.atlassian.net/browse/HHH-14544

Document Ehcache Performance degradation when the default cache is used

---

gradle/libraries.gradle

https://hibernate.atlassian.net/browse/HHH-15639

HHH-15639 Upgrade to ByteBuddy 1.12.18 / 5.6

---

settings.gradle

https://hibernate.atlassian.net/browse/HHH-15639

HHH-15639 Upgrade to ByteBuddy 1.12.18 / 6.1

---

settings.gradle

https://hibernate.atlassian.net/browse/HHH-15637

HHH-15637 Upgrade to Byteman 4.0.20 / 6.1

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java
hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/DiscriminatorColumnFetchGraphTest.java

https://hibernate.atlassian.net/browse/HHH-15622

HHH-15622 Query bug in @NamedEntityGraph when doing Eager loading of @OneToOne mappings in Single Table inheritance

---

hibernate-core/src/main/java/org/hibernate/loader/entity/CacheEntityLoaderHelper.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/IdClassEntityGraphTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/IdClassEntityGraphTest.java

https://hibernate.atlassian.net/browse/HHH-15607

HHH-15607 @NamedEntityGraph is not working when try to load Basic attribute with OneToMany relation.

---

hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/AbstractInformationExtractorImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/schemavalidation/SynonymValidationTest.java

https://hibernate.atlassian.net/browse/HHH-15585

HHH-15585  Add support for DB2 aliases for schema validation

---

hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/AbstractInformationExtractorImpl.java
hibernate-core/src/test/java/org/hibernate/test/schemavalidation/SynonymValidationTest.java

https://hibernate.atlassian.net/browse/HHH-15585

HHH-15585 Add support for DB2 aliases for schema validation

---

hibernate-core/src/main/java/org/hibernate/cfg/BinderHelper.java
hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java
hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EntityTypeImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/misc/Misc0Test.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/misc/Misc1Test.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/misc/Misc2Test.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/misc/Misc3Test.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/misc/Misc4Test.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/misc/MiscTest.java

see https://hibernate.atlassian.net/browse/HHH-15355
UPDATE: and https://hibernate.atlassian.net/browse/HHH-15277
UPDATE 2: also https://hibernate.atlassian.net/browse/HHH-14687
UPDATE 3: and in a separate commit https://hibernate.atlassian.net/browse/HHH-14940
UPDATE 4: and finally https://hibernate.atlassian.net/browse/HHH-13054

HHH-15355 + HHH-14940 multi-column inverse one-to-ones

---

hibernate-core/src/main/java/org/hibernate/Hibernate.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/PersistentAttributeTransformer.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/EnhancementAsProxyLazinessInterceptor.java
hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java
hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryContext.java
hibernate-core/src/main/java/org/hibernate/engine/internal/ManagedTypeHelper.java
hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
hibernate-core/src/main/java/org/hibernate/engine/spi/EnhancedEntity.java
hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/AbstractEntityInstantiatorPojo.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/EntityInstantiatorPojoStandard.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/EntityRepresentationStrategyPojoStandard.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyResolverStandardImpl.java
hibernate-core/src/main/java/org/hibernate/property/access/spi/EnhancedSetterImpl.java
hibernate-core/src/main/java/org/hibernate/tuple/entity/BytecodeEnhancementMetadataPojoImpl.java

Variation of https://hibernate.atlassian.net/browse/HHH-15616 for branch 6.1

HHH-15616 Mitigate performance impact of entity enhancement on Klass's _secondary_super_caches / 6.1

---

hibernate-core/src/main/java/org/hibernate/Hibernate.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/PersistentAttributeTransformer.java
hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java
hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryContext.java
hibernate-core/src/main/java/org/hibernate/engine/internal/ManagedTypeHelper.java
hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
hibernate-core/src/main/java/org/hibernate/engine/spi/EnhancedEntity.java
hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyResolverStandardImpl.java
hibernate-core/src/main/java/org/hibernate/property/access/spi/EnhancedSetterImpl.java
hibernate-core/src/main/java/org/hibernate/tuple/entity/AbstractEntityTuplizer.java
hibernate-core/src/main/java/org/hibernate/tuple/entity/BytecodeEnhancementMetadataPojoImpl.java
hibernate-core/src/main/java/org/hibernate/tuple/entity/PojoEntityInstantiator.java
hibernate-core/src/main/java/org/hibernate/tuple/entity/PojoEntityTuplizer.java

Proposal for
- https://hibernate.atlassian.net/browse/HHH-15616

HHH-15616 Mitigate performance impact of entity enhancement on Klass's _secondary_super_cache

---

hibernate-core/src/main/java/org/hibernate/Hibernate.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/PersistentAttributeTransformer.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/EnhancementAsProxyLazinessInterceptor.java
hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java
hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryContext.java
hibernate-core/src/main/java/org/hibernate/engine/internal/ManagedTypeHelper.java
hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
hibernate-core/src/main/java/org/hibernate/engine/spi/EnhancedEntity.java
hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/AbstractEntityInstantiatorPojo.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/EntityInstantiatorPojoStandard.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/EntityRepresentationStrategyPojoStandard.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyResolverStandardImpl.java
hibernate-core/src/main/java/org/hibernate/property/access/spi/EnhancedSetterImpl.java
hibernate-core/src/main/java/org/hibernate/tuple/entity/BytecodeEnhancementMetadataPojoImpl.java

https://hibernate.atlassian.net/browse/HHH-15616
Variation of #5432 but geared at branch `main`

HHH-15616 Mitigate performance impact of entity enhancement on Klass's _secondary_super_caches

---

hibernate-core/src/main/java/org/hibernate/cfg/AnnotatedColumn.java
hibernate-core/src/main/java/org/hibernate/cfg/AnnotatedJoinColumn.java
hibernate-core/src/main/java/org/hibernate/cfg/BinderHelper.java
hibernate-core/src/main/java/org/hibernate/cfg/CopyIdentifierComponentSecondPass.java
hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java
hibernate-core/src/main/java/org/hibernate/cfg/annotations/TableBinder.java
hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/manytoone/referencedcolumnname/ManyToOneReferencedColumnNameTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/manytoone/referencedcolumnname/WarehouseItem.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/manytoone/referencedcolumnname/ZItemCost.java

deprecate some operations of AnnotatedJoinColumn

---

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/InlineDirtyCheckerEqualsHelper.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/InlineDirtyCheckingHandler.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/NoDirtyCheckingContext.java
hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/LazyLoadingByEnhancerSetterTest.java
hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/basic/LazyBasicFieldAccessTest.java
hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/basic/LazyBasicPropertyAccessTest.java
hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/basic/MultiLazyBasicUpdateTest.java
hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/basic/MultiLazyBasicUpdateToNullTest.java
hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/basic/OnlyLazyBasicUpdateTest.java
hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/basic/OnlyLazyBasicUpdateToNullTest.java
hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/group/MultiLazyBasicInLazyGroupUpdateTest.java
hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/group/MultiLazyBasicInLazyGroupUpdateToNullTest.java
hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/group/OnlyLazyBasicInLazyGroupBasicUpdateTest.java
hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/group/OnlyLazyBasicInLazyGroupBasicUpdateToNullTest.java

Backport of #5461 to branch 5.6.
@dreab8 I had to backport this in order to test in Quarkus, so I figured I'd send the PR.
Feel free to use this or drop it, as you see fit.

Backport HHH-15634 to branch 5.6 - Lazy basic property does not get updated on change

---

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/InlineDirtyCheckerEqualsHelper.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/InlineDirtyCheckingHandler.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/LazyLoadingByEnhancerSetterTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/NoDirtyCheckingContext.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/basic/LazyBasicFieldAccessTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/basic/LazyBasicPropertyAccessTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/basic/MultiLazyBasicUpdateTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/basic/MultiLazyBasicUpdateToNullTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/basic/OnlyLazyBasicUpdateTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/basic/OnlyLazyBasicUpdateToNullTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/group/MultiLazyBasicInLazyGroupUpdateTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/group/MultiLazyBasicInLazyGroupUpdateToNullTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/group/OnlyLazyBasicInLazyGroupBasicUpdateTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/group/OnlyLazyBasicInLazyGroupBasicUpdateToNullTest.java

HHH-15634 Lazy basic property does not get updated on change

---

hibernate-core/src/main/java/org/hibernate/Hibernate.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/EnhancementAsProxyLazinessInterceptor.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/LazyAttributeLoadingInterceptor.java
hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java
hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryContext.java
hibernate-core/src/main/java/org/hibernate/engine/internal/ForeignKeys.java
hibernate-core/src/main/java/org/hibernate/engine/internal/ManagedTypeHelper.java
hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java
hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java
hibernate-core/src/main/java/org/hibernate/event/internal/DirtyCollectionSearchVisitor.java
hibernate-core/src/main/java/org/hibernate/event/internal/WrapVisitor.java
hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
hibernate-core/src/main/java/org/hibernate/jpa/internal/PersistenceUnitUtilImpl.java
hibernate-core/src/main/java/org/hibernate/jpa/internal/util/PersistenceUtilHelper.java
hibernate-core/src/main/java/org/hibernate/loader/entity/CacheEntityLoaderHelper.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/AbstractEntityInstantiatorPojo.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/EntityInstantiatorPojoStandard.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/EntityRepresentationStrategyPojoStandard.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyResolverStandardImpl.java
hibernate-core/src/main/java/org/hibernate/property/access/spi/EnhancedSetterImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/main/java/org/hibernate/tuple/entity/BytecodeEnhancementMetadataPojoImpl.java

- https://hibernate.atlassian.net/browse/HHH-15649

HHH-15649 Additional performance fixes relating to Klass's _secondary_super_cache interaction with entity enhancement / main

---

hibernate-core/src/main/java/org/hibernate/Hibernate.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/LazyAttributeLoadingInterceptor.java
hibernate-core/src/main/java/org/hibernate/engine/internal/ManagedTypeHelper.java
hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java
hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java
hibernate-core/src/main/java/org/hibernate/event/internal/DirtyCollectionSearchVisitor.java
hibernate-core/src/main/java/org/hibernate/event/internal/WrapVisitor.java
hibernate-core/src/main/java/org/hibernate/jpa/internal/PersistenceUnitUtilImpl.java
hibernate-core/src/main/java/org/hibernate/jpa/internal/util/PersistenceUtilHelper.java
hibernate-core/src/main/java/org/hibernate/loader/entity/CacheEntityLoaderHelper.java
hibernate-core/src/main/java/org/hibernate/tuple/entity/BytecodeEnhancementMetadataPojoImpl.java

- https://hibernate.atlassian.net/browse/HHH-15649

HHH-15649 Additional performance fixes relating to Klass's _secondary_super_cache interaction with entity enhancement / 5.6

---

hibernate-core/src/main/java/org/hibernate/Hibernate.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/EnhancementAsProxyLazinessInterceptor.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/LazyAttributeLoadingInterceptor.java
hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java
hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryContext.java
hibernate-core/src/main/java/org/hibernate/engine/internal/ForeignKeys.java
hibernate-core/src/main/java/org/hibernate/engine/internal/ManagedTypeHelper.java
hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java
hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java
hibernate-core/src/main/java/org/hibernate/event/internal/DirtyCollectionSearchVisitor.java
hibernate-core/src/main/java/org/hibernate/event/internal/WrapVisitor.java
hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
hibernate-core/src/main/java/org/hibernate/jpa/internal/PersistenceUnitUtilImpl.java
hibernate-core/src/main/java/org/hibernate/jpa/internal/util/PersistenceUtilHelper.java
hibernate-core/src/main/java/org/hibernate/loader/entity/CacheEntityLoaderHelper.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/AbstractEntityInstantiatorPojo.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/EntityInstantiatorPojoStandard.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/EntityRepresentationStrategyPojoStandard.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyResolverStandardImpl.java
hibernate-core/src/main/java/org/hibernate/property/access/spi/EnhancedSetterImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/main/java/org/hibernate/tuple/entity/BytecodeEnhancementMetadataPojoImpl.java

https://hibernate.atlassian.net/browse/HHH-15649

HHH-15649 Additional performance fixes relating to Klass's _secondary_super_cache interaction with entity enhancement / 6.1

---

hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryContext.java
hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java

https://hibernate.atlassian.net/browse/HHH-15651

  HHH-15651  StatefulPersistenceContext#clear shouldn't need defensive copies for iteration / main

---

hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryContext.java
hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java

https://hibernate.atlassian.net/browse/HHH-15651

HHH-15651 StatefulPersistenceContext#clear shouldn't need defensive copies for iteration / 6.1

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java
hibernate-core/src/main/java/org/hibernate/spi/NavigablePath.java
hibernate-core/src/test/java/org/hibernate/orm/test/hql/ManyToOneJoinReuseTest.java

https://hibernate.atlassian.net/browse/HHH-15648

HHH-15648 Fix fetching association and using implicit path in condition

---

migration-guide.adoc

Note on minimum supported versions in the migration doc.

HHH-15175 - Remove support for database versions

---

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DriverManagerConnectionProviderImpl.java

https://hibernate.atlassian.net/browse/HHH-15656
https://hibernate.atlassian.net/browse/HHH-15655
https://issues.redhat.com/browse/WFLY-17196
Cherry picked https://github.com/hibernate/hibernate-orm/pull/5486 changes for `main` branch

HHH-15655 HHH-15656 ByteBuddyState should use privileged action when defining classes and same for calling ScheduledExecutorService.shutdown

---

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/InlineDirtyCheckingHandler.java

Some minor refactoring of the already applied patches for HHH-15634
- https://hibernate.atlassian.net/browse/HHH-15634

Minor follow up to HHH-15634

---

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/InlineDirtyCheckingHandler.java

Port of #5497 to 6.1

---

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/InlineDirtyCheckingHandler.java

Port of #5497 to 5.6

---

hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryContext.java
hibernate-core/src/main/java/org/hibernate/engine/internal/ManagedTypeHelper.java

https://hibernate.atlassian.net/browse/HHH-15662

HHH-15662 ClasscastException caused by check for Managed

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/CachedQueryDirectReferenceTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/CachedQueryTest.java

https://hibernate.atlassian.net/browse/HHH-15666

HHH-15666 When a reference entry is found in the Second Level Cache there is not need to set its values 

---

documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
documentation/src/main/asciidoc/userguide/chapters/tooling/enhancement.adoc
documentation/src/main/asciidoc/userguide/chapters/tooling/gradle.adoc
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/EnhancementContext.java
hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
hibernate-core/src/main/java/org/hibernate/internal/log/DeprecationLogger.java
hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java
hibernate-testing/src/main/java/org/hibernate/testing/util/jpa/PersistenceUnitInfoAdapter.java
migration-guide.adoc
tooling/hibernate-ant/src/main/java/org/hibernate/tool/enhance/EnhancementTask.java
tooling/hibernate-enhance-maven-plugin/src/main/java/org/hibernate/orm/tooling/maven/MavenEnhancePlugin.java
tooling/hibernate-enhance-maven-plugin/src/main/resources/META-INF/maven/org.hibernate.orm.tooling/hibernate-enhance-maven-plugin/plugin-help.xml
tooling/hibernate-enhance-maven-plugin/src/main/resources/META-INF/maven/plugin.xml
tooling/hibernate-gradle-plugin/src/main/java/org/hibernate/orm/tooling/gradle/enhance/EnhancementHelper.java
tooling/hibernate-gradle-plugin/src/main/java/org/hibernate/orm/tooling/gradle/enhance/EnhancementSpec.java

https://hibernate.atlassian.net/browse/HHH-15641

HHH-15641 Enable inlineDirtyChecking and lazyLoading for enhancement by default and deprecate the setting

---

hibernate-core/src/test/java/org/hibernate/orm/test/jpa/lock/JPALockTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/lock/RepeatableReadTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/optlock/OptimisticLockTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/nullPrecedence/SupportingNotNativelyDialectTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/tm/CMTTest.java
hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java
hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFilterExtension.java

- implement RequiresDialectFeature.reverse()
- remove not-feature checks to reverse = true

HHH-15670 Implement RequiresDialectFeature.reverse()

---

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/NativeQueryWithDuplicateColumnTest.java

https://hibernate.atlassian.net/browse/HHH-15608

HHH-15608 Error In Native Query where column is mapped twice

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseLegacyDialect.java
hibernate-core/src/main/java/org/hibernate/annotations/GenerationTime.java
hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java
hibernate-core/src/main/java/org/hibernate/cfg/annotations/PropertyBinder.java
hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/SybaseDialect.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/GeneratedValueResolver.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/GeneratedValuesProcessor.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/tuple/GenerationTiming.java
hibernate-core/src/main/java/org/hibernate/tuple/ValueGeneration.java
hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/DatabaseTimestampsColumnTest.java
hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/AuditMetadataGenerator.java
hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java

This "just" adds a new value to the enum `GenerationTiming`.

HHH-15672 introduce Generated(UPDATE) for properties only generated on update

---

hibernate-core/src/main/java/org/hibernate/hql/internal/ast/HqlSqlWalker.java
hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java
hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
hibernate-core/src/main/java/org/hibernate/loader/Loader.java

https://hibernate.atlassian.net/browse/HHH-15685

HHH-15685 Improve efficiency of Dialect lookup in Loader and HqlSqlWalker

---

hibernate-core/src/main/java/org/hibernate/LockMode.java
hibernate-core/src/main/java/org/hibernate/LockOptions.java
hibernate-core/src/main/java/org/hibernate/engine/spi/CascadingActions.java
hibernate-core/src/main/java/org/hibernate/event/internal/DefaultRefreshEventListener.java
hibernate-core/src/main/java/org/hibernate/event/spi/LoadEvent.java
hibernate-core/src/main/java/org/hibernate/event/spi/LockEvent.java
hibernate-core/src/main/java/org/hibernate/event/spi/ResolveNaturalIdEvent.java
hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
hibernate-core/src/main/java/org/hibernate/jpa/HibernateHints.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java
hibernate-core/src/main/java/org/hibernate/query/spi/QueryOptionsAdapter.java
hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/MatchingIdSelectionHelper.java
hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/DeferredResultSetAccess.java

+ add some documentation around follow-on locking

HHH-15682 fix potential classloading deadlock

---

hibernate-core/src/main/java/org/hibernate/engine/query/spi/HQLQueryPlan.java
hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java

- https://hibernate.atlassian.net/browse/HHH-15690

HHH-15690 HQLQueryPlan to have a direct reference to QueryTranslatorFactory

---

hibernate-core/src/main/java/org/hibernate/EntityNameResolver.java
hibernate-core/src/main/java/org/hibernate/Session.java
hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java
hibernate-core/src/main/java/org/hibernate/engine/spi/SessionImplementor.java
hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java
hibernate-core/src/main/java/org/hibernate/internal/CoordinatingEntityNameResolver.java
hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/DeferredResultSetAccess.java
hibernate-core/src/test/java/org/hibernate/orm/test/entityname/MultipleMappingsTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/entityname/MyEntity.hbm.xml
hibernate-core/src/test/java/org/hibernate/orm/test/entityname/MyEntity.java
hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/SessionFactory.java

and add `Configuration.addEntityNameResolver()`

HHH-15689, HHH-15696, HHH-15697 fix SessionFactoryBuilder.addEntityNameResolver() 

---

hibernate-core/src/main/java/org/hibernate/query/MutationQuery.java
hibernate-core/src/main/java/org/hibernate/query/NativeQuery.java
hibernate-core/src/main/java/org/hibernate/query/Query.java
hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java
hibernate-core/src/main/java/org/hibernate/query/SynchronizeableQuery.java
hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java
hibernate-core/src/main/java/org/hibernate/query/spi/QueryImplementor.java
hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
hibernate-core/src/main/java/org/hibernate/query/sql/spi/NativeQueryImplementor.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/lock/QueryLockingTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/locking/paging/PagingAndLockingTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/AddNamedQueryTest.java

- go back to throwing the required (but bad) exception type
- make it easier for our users to bypass this dumb requirement
- _properly document what is going on with all this shit_

sort out stuff regarding JPA's unfortunate ISE

---

hibernate-core/src/main/java/org/hibernate/CacheMode.java
hibernate-core/src/main/java/org/hibernate/annotations/CacheModeType.java
hibernate-core/src/main/java/org/hibernate/annotations/NamedNativeQuery.java
hibernate-core/src/main/java/org/hibernate/annotations/NamedQuery.java
hibernate-core/src/main/java/org/hibernate/annotations/OptimisticLockType.java
hibernate-core/src/main/java/org/hibernate/annotations/OptimisticLocking.java
hibernate-core/src/main/java/org/hibernate/cfg/annotations/QueryBinder.java
hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java

HHH-15701 deprecate CacheModeType since it is a dupe of CacheMode

---

hibernate-core/src/main/java/org/hibernate/CacheMode.java
hibernate-core/src/main/java/org/hibernate/Session.java
hibernate-core/src/main/java/org/hibernate/boot/SessionFactoryBuilder.java
hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java
hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java
hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
hibernate-core/src/main/java/org/hibernate/query/NativeQuery.java
hibernate-core/src/main/java/org/hibernate/query/Query.java
hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java
hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java
hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java
hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java

This is just a convenience, but I think it's a nice thing to have.

HHH-15702 make our APIs friendly to CacheStoreMode, CacheRetrieveMode

---

hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardForeignKeyExporter.java
hibernate-core/src/test/java/org/hibernate/orm/test/tool/schema/internal/StandardForeignKeyExporterTest.java

and add test case for this issue

HHH-15704 - Fix regression in StandardForeignKeyExporter 

---

hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/internal/JdbcLiteralFormatterTemporal.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/LiteralTests.java

for Postgres, Cockroach, and H2

HHH-15709 fix rendering of timestamp literal when there is no timezone

---

hibernate-core/src/main/java/org/hibernate/type/descriptor/ValueBinder.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/ValueExtractor.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/WrapperOptions.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JdbcTypeIndicators.java

so we can easily find where these settings ultimately come from

add some cross-refs to the Javadoc

---

hibernate-core/src/main/java/org/hibernate/cache/cfg/spi/DomainDataRegionBuildingContext.java
hibernate-core/src/main/java/org/hibernate/cache/spi/CacheKeysFactory.java
hibernate-core/src/main/java/org/hibernate/cache/spi/CacheTransactionSynchronization.java
hibernate-core/src/main/java/org/hibernate/cache/spi/DirectAccessRegion.java
hibernate-core/src/main/java/org/hibernate/cache/spi/DomainDataRegion.java
hibernate-core/src/main/java/org/hibernate/cache/spi/ExtendedStatisticsSupport.java
hibernate-core/src/main/java/org/hibernate/cache/spi/FilterKey.java
hibernate-core/src/main/java/org/hibernate/cache/spi/QueryKey.java
hibernate-core/src/main/java/org/hibernate/cache/spi/QueryResultsCache.java
hibernate-core/src/main/java/org/hibernate/cache/spi/QueryResultsRegion.java
hibernate-core/src/main/java/org/hibernate/cache/spi/QuerySpacesHelper.java
hibernate-core/src/main/java/org/hibernate/cache/spi/Region.java
hibernate-core/src/main/java/org/hibernate/cache/spi/RegionFactory.java
hibernate-core/src/main/java/org/hibernate/cache/spi/TimestampsCache.java
hibernate-core/src/main/java/org/hibernate/cache/spi/TimestampsCacheFactory.java
hibernate-core/src/main/java/org/hibernate/cache/spi/TimestampsRegion.java
hibernate-core/src/main/java/org/hibernate/cache/spi/access/CachedDomainDataAccess.java

also correct some errors in the names of types - this is why it's better to use @link!!

deprecate two unused types in the cache SPI + add javadoc

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityMappingType.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java

https://hibernate.atlassian.net/browse/HHH-15569

HHH-15569 Replace list and map with array to improve state extraction for entity initializing

---

settings.gradle

- https://hibernate.atlassian.net/browse/HHH-15724

HHH-15724 Upgrade to Jandex 3.0.3

---

hibernate-core/src/main/java/org/hibernate/service/internal/AbstractServiceRegistryImpl.java

https://hibernate.atlassian.net/browse/HHH-15693

HHH-15693 Introduce a fast-path access for ClassLoaderService being retrieved from ServiceRegistry

---

hibernate-core/src/test/java/org/hibernate/orm/test/extralazy/ExtraLazyTest.java

HHH-2087 - Added test to verify issue is fixed

---

documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
etc/hibernate.properties
etc/hibernate.properties.template

This is correct, right? I might have missed it.
- https://hibernate.atlassian.net/browse/HHH-15692

HHH-15692 Remove references to hibernate.query.factory_class config property

---

hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaCreatorImpl.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/ScriptSourceInputAggregate.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/ScriptSourceInputFromFile.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/ScriptSourceInputFromReader.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/ScriptSourceInputFromUrl.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/ScriptSourceInputNonExistentImpl.java
hibernate-core/src/main/java/org/hibernate/tool/schema/spi/ScriptSourceInput.java
hibernate-core/src/test/java/org/hibernate/orm/test/tool/schema/DefaultImportFileExecutionTest.java

https://hibernate.atlassian.net/browse/HHH-15717

HHH-15717 SQL script executed twice when using persistence.xml jakarta.persistence.sql-load-script-source property with the default sql script name

---

settings.gradle

https://hibernate.atlassian.net/browse/HHH-15732

Upgrade to Hibernate Commons Annotations 6.0.5.Final

---

hibernate-core/src/main/java/org/hibernate/service/internal/AbstractServiceRegistryImpl.java

as suggested by @ andrei-ivanov  
- https://github.com/hibernate/hibernate-orm/pull/5527/files/4cb7e8b901d575f8703f726be3019447ba10f308#r1025222586
Reusing the existing JIRA since it's not closed.

HHH-15693 An additional minor polish to the previously applied optimisation

---

hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingsImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/CriteriaWhereTest.java

https://hibernate.atlassian.net/browse/HHH-15716

HHH-15716 ClassCastException in QueryParameterBindingsImpl.generateQueryKeyMemento

---

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderSubSelectFetch.java
hibernate-core/src/test/java/org/hibernate/orm/test/fetch/ElementCollectionWithSubselectFetchModeTest.java

https://hibernate.atlassian.net/browse/HHH-15640

HHH-15640 ElementCollection with SubSelect FetchMode throws NPE, "ownerEntry" is null

---

hibernate-core/src/main/java/org/hibernate/internal/FetchingScrollableResultsImpl.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/CompoundNaturalIdMapping.java
hibernate-core/src/main/java/org/hibernate/persister/walking/spi/AttributeSource.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/FetchParentAccess.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/Initializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/CollectionInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/AbstractCollectionInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/EmbeddableInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/EntityInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/AbstractBatchEntitySelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntityInsideEmbeddableSelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntitySelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityAssembler.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchSelectImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/RowProcessingStateStandardImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/StandardRowReader.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/domain/CircularBiDirectionalFetchImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/domain/CircularFetchImpl.java
hibernate-core/src/main/java/org/hibernate/tuple/component/AbstractCompositionAttribute.java
hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityBasedCompositionAttribute.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchingInheritanceTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/EmbeddableBatchingTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/EmbeddableWithNullValuesExceptForAssociationsTest.java

- HHH-15644 [ClassCastException when batch-fetching association in embeddable ](https://hibernate.atlassian.net/browse/HHH-15644)
- HHH-15695 [Batch Fetching, Embeddable with an Association is considered null when all the other Embeddable attributes are null](https://hibernate.atlassian.net/browse/HHH-15695)
- HHH-15694 [HibernateException: Unable to resolve property xyz on ManyToOne with BatchSize](https://hibernate.atlassian.net/browse/HHH-15694)

HHH-15695 + HHH-15644 + HHH-15694 Batch fetching

---

hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/MultipleBoundsTest.java

https://hibernate.atlassian.net/browse/HHH-15687 
the issue should be fixed by https://hibernate.atlassian.net/browse/HHH-15732

HHH-15687 IllegalArgumentException with Type parameters and multiple bounds

---

hibernate-core/src/main/java/org/hibernate/annotations/LazyToOne.java
hibernate-core/src/main/java/org/hibernate/annotations/LazyToOneOption.java

completey rewrite the javadoc I just wrote and pushed

---

hibernate-core/src/main/java/org/hibernate/Hibernate.java

Add the static method `Hibernate.isInstance()`.

HHH-15740 add Hibernate.isInstance() convenience method

---

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/EmbeddableAndNativeQueryTest.java

https://hibernate.atlassian.net/browse/HHH-15658

HHH-15658 Embeddable with more fields than the parent fails with Index out of Bounds

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/SingleTableInheritanceAndShareCacheModeAllTest.java

https://hibernate.atlassian.net/browse/HHH-15699

HHH-15699 HibernateException: Found shared references to a collection when ShareCacheMode.All or ShareCacheMode.DISABLE_SELECTIVE

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/LazyOneToOneMappedByInEmbeddedTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/LazyOneToOneMappedByTest.java

https://hibernate.atlassian.net/browse/HHH-15606

HHH-15606 @OneToOne(mappedBy = ..., fetch = LAZY) in embedded leads to IllegalArgumentException: Can not set [...] to LazyPropertyInitializer$1

---

hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/ArgumentTypesValidator.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionAndEnumsTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java

https://hibernate.atlassian.net/browse/HHH-15711

HHH-15711 ArgumentTypesValidator doesn't support enums in string functions

---

hibernate-core/src/main/java/org/hibernate/query/hql/internal/QuerySplitter.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmPolymorphicRootDescriptor.java
hibernate-core/src/test/java/org/hibernate/orm/test/polymorphic/PolymorphicQueriesTest.java

https://hibernate.atlassian.net/browse/HHH-15718

HHH-15718 Polymorphic queries with condition do not work

---

docker_db.sh
documentation/src/test/java/org/hibernate/userguide/mapping/basic/JsonMappingTests.java
gradle/databases.gradle
gradle/java-module.gradle
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/OracleJsonJdbcType.java
hibernate-core/src/main/java/org/hibernate/dialect/OracleTypes.java
hibernate-core/src/main/java/org/hibernate/dialect/OracleTypesHelper.java
hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JdbcTypeJavaClassMappings.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JsonBlobJdbcType.java
hibernate-core/src/main/java/org/hibernate/type/jackson/JacksonJsonFormatMapper.java
hibernate-core/src/main/java/org/hibernate/type/jackson/JacksonXmlFormatMapper.java
hibernate-core/src/main/java/org/hibernate/type/jakartajson/JsonBJsonFormatMapper.java
hibernate-core/src/main/java/org/hibernate/type/jaxb/JaxbXmlFormatMapper.java
migration-guide.adoc

https://hibernate.atlassian.net/browse/HHH-15748

HHH-15748 Use JSON DDL type on Oracle 21+ and BLOB on 12+

---

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java

Fix [HHH-15747](https://hibernate.atlassian.net/browse/HHH-15747)

Add getTupleMetadata() to select query implementations

---

hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java
hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/inheritance/joined/JoinedSubclassWithEmbeddableIdTest.java

in insert statement when InheritanceType.JOINED and @Embeddable ID'

HHH-15686 - test and fix for issue 'Envers incorrect key parameter order"

---

hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java
hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/inheritance/joined/JoinedSubclassWithEmbeddableIdTest.java

in insert statement when InheritanceType.JOINED and @Embeddable ID'

HHH-15686 - test and fix for issue 'Envers incorrect key parameter order

---

docker_db.sh

Disable dynamic sequence caching for Oracle

---

docker_db.sh

Reverts hibernate/hibernate-orm#5618

Revert "Disable dynamic sequence caching for Oracle"

---

build.gradle
tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle

Fixes [HHH-15765](https://hibernate.atlassian.net/browse/HHH-15765)

HHH-15765 Fix build failure by upgrading nu.studer.credentials to 3.0

---

gradle/javadoc.gradle
hibernate-core/hibernate-core.gradle
release/release.gradle

Make it quieter. Also delete some obsolete stuff from before move to Java 11.

gradle build is too noisy

---

hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java
hibernate-core/src/main/java/org/hibernate/boot/model/TypeDefinition.java
hibernate-core/src/main/java/org/hibernate/id/factory/IdentifierGeneratorFactory.java
hibernate-core/src/main/java/org/hibernate/id/factory/internal/StandardIdentifierGeneratorFactory.java
hibernate-core/src/main/java/org/hibernate/id/factory/internal/StandardIdentifierGeneratorFactoryInitiator.java
hibernate-core/src/main/java/org/hibernate/resource/beans/container/spi/AbstractCdiBeanContainer.java
hibernate-core/src/main/java/org/hibernate/resource/beans/internal/Helper.java
hibernate-core/src/main/java/org/hibernate/service/StandardServiceInitiators.java

https://hibernate.atlassian.net/browse/HHH-15746
Replaces #5597

HHH-15746 Allow replacing the StandardIdentifierGeneratorFactory by making it a Service again

---

hibernate-core/src/main/java/org/hibernate/CacheMode.java
hibernate-core/src/main/java/org/hibernate/annotations/CreationTimestamp.java
hibernate-core/src/main/java/org/hibernate/annotations/FlushModeType.java
hibernate-core/src/main/java/org/hibernate/annotations/Index.java
hibernate-core/src/main/java/org/hibernate/annotations/Mutability.java
hibernate-core/src/main/java/org/hibernate/annotations/Polymorphism.java
hibernate-core/src/main/java/org/hibernate/annotations/PolymorphismType.java
hibernate-core/src/main/java/org/hibernate/annotations/Proxy.java
hibernate-core/src/main/java/org/hibernate/annotations/ResultCheckStyle.java
hibernate-core/src/main/java/org/hibernate/annotations/Synchronize.java
hibernate-core/src/main/java/org/hibernate/annotations/Target.java
hibernate-core/src/main/java/org/hibernate/annotations/UpdateTimestamp.java
hibernate-core/src/main/java/org/hibernate/annotations/package-info.java

...and refresh some misc annotation javadoc

deprecate @Target which dupes functionality of JPA annotations

---

hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryContext.java
hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java

https://hibernate.atlassian.net/browse/HHH-15776

HHH-15776 Avoid type checking for ManagedEntity in StatefulPersistenceContext#addReferenceEntry

---

hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryContext.java
hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java

https://hibernate.atlassian.net/browse/HHH-15776

HHH-15776 ported to main

---

documentation/src/main/asciidoc/userguide/chapters/domain/collections.adoc
documentation/src/main/asciidoc/userguide/chapters/events/Events.adoc
documentation/src/test/java/org/hibernate/userguide/collections/MapKeyTypeTest.java
documentation/src/test/java/org/hibernate/userguide/events/ListenerTest.java
documentation/src/test/java/org/hibernate/userguide/spatial/SpatialTest.java

HHH-15715 - Fix broken links in docs

---

hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesResultSetImpl.java

https://hibernate.atlassian.net/browse/HHH-15779

HHH-15779 Avoid stateful lambdas in hot processing of JdbcValuesResultSetImpl

---

hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesResultSetImpl.java

https://hibernate.atlassian.net/browse/HHH-15779

HHH-15779 Avoid stateful lambdas in hot processing of JdbcValuesResultSetImpl [main]

---

hibernate-core/src/main/java/org/hibernate/service/NullServiceException.java
hibernate-core/src/main/java/org/hibernate/service/UnknownServiceException.java

Fixes [HHH-15775](https://hibernate.atlassian.net/browse/HHH-15775)

HHH-15775 Make UnknownServiceException and NullServiceException extend ServiceException

---

hibernate-core/src/main/java/org/hibernate/query/criteria/HibernateCriteriaBuilder.java
hibernate-core/src/main/java/org/hibernate/query/criteria/spi/CriteriaBuilderExtension.java
hibernate-core/src/main/java/org/hibernate/query/criteria/spi/HibernateCriteriaBuilderDelegate.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
hibernate-spatial/src/main/java/org/hibernate/spatial/criteria/GeolatteSpatialCriteriaBuilder.java
hibernate-spatial/src/main/java/org/hibernate/spatial/criteria/JTSSpatialCriteriaBuilder.java
hibernate-spatial/src/main/java/org/hibernate/spatial/criteria/SpatialCriteriaBuilder.java
hibernate-spatial/src/main/java/org/hibernate/spatial/criteria/internal/GeolatteSpatialCriteriaBuilderImpl.java
hibernate-spatial/src/main/java/org/hibernate/spatial/criteria/internal/GeolatteSpatialCriteriaExtension.java
hibernate-spatial/src/main/java/org/hibernate/spatial/criteria/internal/JTSSpatialCriteriaBuilderImpl.java
hibernate-spatial/src/main/java/org/hibernate/spatial/criteria/internal/JTSSpatialCriteriaExtension.java
hibernate-spatial/src/main/java/org/hibernate/spatial/criteria/internal/SpatialCriteriaBuilderImpl.java
hibernate-spatial/src/main/java/org/hibernate/spatial/predicate/GeolatteFilterPredicate.java
hibernate-spatial/src/main/java/org/hibernate/spatial/predicate/GeolatteSpatialPredicates.java
hibernate-spatial/src/main/java/org/hibernate/spatial/predicate/JTSFilterPredicate.java
hibernate-spatial/src/main/java/org/hibernate/spatial/predicate/JTSSpatialPredicates.java
hibernate-spatial/src/main/resources/META-INF/services/org.hibernate.query.criteria.spi.CriteriaBuilderExtension
hibernate-spatial/src/test/java/org/hibernate/spatial/integration/criteria/SpatialCriteriaBindingModeTest.java
hibernate-spatial/src/test/java/org/hibernate/spatial/integration/criteria/SpatialCriteriaInlineModeTest.java
hibernate-spatial/src/test/java/org/hibernate/spatial/integration/criteria/SpatialCriteriaSmokeTest.java
hibernate-spatial/src/test/java/org/hibernate/spatial/integration/criteria/SpatialCriteriaTest.java

https://hibernate.atlassian.net/browse/HHH-14982

HHH-14982 Implement JPA Criteria extension mechanism for Spatial

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/Cache71Dialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java
hibernate-core/src/main/java/org/hibernate/annotations/package-info.java
hibernate-core/src/main/java/org/hibernate/boot/MetadataSources.java
hibernate-core/src/main/java/org/hibernate/boot/query/HbmResultSetMappingDescriptor.java
hibernate-core/src/main/java/org/hibernate/cfg/Environment.java
hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/spi/Batch.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/group/PreparedStatementDetails.java
hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStyleGenerator.java
hibernate-core/src/main/java/org/hibernate/id/enhanced/TableGenerator.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/SelectableConsumer.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EntityCollectionPart.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/InsertRowsCoordinator.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java
hibernate-core/src/main/java/org/hibernate/persister/entity/Queryable.java
hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/EntityMutationTarget.java
hibernate-core/src/main/java/org/hibernate/query/results/complete/package-info.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/sql/model/MutationOperation.java
hibernate-core/src/main/java/org/hibernate/sql/model/ast/TableMutation.java
hibernate-core/src/main/java/org/hibernate/tuple/Tuplizer.java
hibernate-spatial/src/main/java/org/hibernate/spatial/SpatialFunction.java
hibernate-spatial/src/main/java/org/hibernate/spatial/SpatialRelation.java
tooling/hibernate-ant/src/main/java/org/hibernate/tool/hbm2ddl/SchemaExportTask.java
tooling/hibernate-ant/src/main/java/org/hibernate/tool/hbm2ddl/SchemaValidatorTask.java

https://hibernate.atlassian.net/browse/HHH-15785

HHH-15785 Further javadoc corrections and improvements

---

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java
hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java

https://hibernate.atlassian.net/browse/HHH-15787

HHH-15787 DefaultMergeEventlistener#onMerge is performing runtime services lookup

---

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java
hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java

https://hibernate.atlassian.net/browse/HHH-15787

HHH-15787 DefaultMergeEventlistener#onMerge is performing runtime services lookup [6.1]

---

hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/ColumnReference.java

https://hibernate.atlassian.net/browse/HHH-15793

HHH-15793  Mitigate type pollution on ColumnReference#getExpressionType

---

hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/ColumnReference.java

https://hibernate.atlassian.net/browse/HHH-15793

HHH-15793 Mitigate type pollution on ColumnReference#getExpressionType

---

hibernate-core/src/main/java/org/hibernate/cfg/annotations/PropertyBinder.java

oops, forgot to push amended commit

make @IdGeneratorType accept Generator

---

hibernate-core/src/main/java/org/hibernate/id/IdentifierGeneratorHelper.java

Fixes [HHH-15801](https://hibernate.atlassian.net/browse/HHH-15801)

HHH-15801 IdentifierGeneratorHelper should compare column names case insensitively

---

hibernate-core/src/main/java/org/hibernate/EmptyInterceptor.java
hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java
hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java
hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDeleteEventListener.java
hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
hibernate-core/src/main/java/org/hibernate/internal/EmptyInterceptor.java
hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java

https://hibernate.atlassian.net/browse/HHH-15803

HHH-15803 Have the default EmptyInterceptor avoid triggering type pollution [main]

---

hibernate-core/src/main/java/org/hibernate/EmptyInterceptor.java
hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java
hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java
hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
hibernate-core/src/main/java/org/hibernate/internal/EmptyInterceptor.java
hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java

https://hibernate.atlassian.net/browse/HHH-15803

HHH-15803 Have the default EmptyInterceptor avoid triggering type pollution [6.1]

---

hibernate-core/src/main/java/org/hibernate/engine/internal/ManagedTypeHelper.java

https://hibernate.atlassian.net/browse/HHH-15804

HHH-15804 Avoid JDK functional interfaces in ManagedTypeHelper [main]

---

hibernate-core/src/main/java/org/hibernate/engine/internal/ManagedTypeHelper.java

https://hibernate.atlassian.net/browse/HHH-15804

HHH-15804 Avoid JDK functional interfaces in ManagedTypeHelper [6.1]

---

hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/ByteBuddyProxyFactory.java

https://hibernate.atlassian.net/browse/HHH-15808

HHH-15808 ByteBuddyProxyFactory#getHibernateProxy is triggering type pollution via generic PrivilegedAction

---

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BasicProxyFactoryImpl.java
hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java
hibernate-core/src/main/java/org/hibernate/engine/spi/PrimeAmongSecondarySupertypes.java
hibernate-core/src/main/java/org/hibernate/proxy/ProxyConfiguration.java
hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/ByteBuddyProxyFactory.java
hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/ByteBuddyProxyHelper.java

https://hibernate.atlassian.net/browse/HHH-15809

HHH-15809 Secondary super-type cache pollution mitigations for HibernateBasicProxy instances [6.1]

---

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BasicProxyFactoryImpl.java
hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java
hibernate-core/src/main/java/org/hibernate/engine/spi/PrimeAmongSecondarySupertypes.java
hibernate-core/src/main/java/org/hibernate/proxy/ProxyConfiguration.java
hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/ByteBuddyProxyFactory.java
hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/ByteBuddyProxyHelper.java

https://hibernate.atlassian.net/browse/HHH-15809

HHH-15809 Secondary super-type cache pollution mitigations for HibernateBasicProxy

---

hibernate-core/src/main/java/org/hibernate/internal/FetchingScrollableResultsImpl.java
hibernate-core/src/main/java/org/hibernate/query/results/complete/EntityResultImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/FetchParentAccess.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/Initializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/EntityInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedResultImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchJoinedImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchSelectImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityResultImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityResultJoinedSubclassImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/domain/CircularBiDirectionalFetchImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/domain/CircularFetchImpl.java

https://hibernate.atlassian.net/browse/HHH-15810

HHH-15810 Avoid secondary super-type cache pollution when casting to EntityInitializer

---

hibernate-core/src/main/java/org/hibernate/internal/FetchingScrollableResultsImpl.java
hibernate-core/src/main/java/org/hibernate/query/results/complete/EntityResultImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/FetchParentAccess.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/Initializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/EntityInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedResultImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchJoinedImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchSelectImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityResultImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityResultJoinedSubclassImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/domain/CircularBiDirectionalFetchImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/domain/CircularFetchImpl.java

https://hibernate.atlassian.net/browse/HHH-15810

HHH-15810 Avoid secondary super-type cache pollution when casting to EntityInitializer [main]

---

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/AttributeMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ModelPart.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/Fetchable.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/domain/CircularBiDirectionalFetchImpl.java

https://hibernate.atlassian.net/browse/HHH-15810

HHH-15811 Avoid secondary super-type cache pollution when casting to AttributeMapping

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/TreatTest.java

https://hibernate.atlassian.net/browse/HHH-15721

HHH-15721 NullPointerException in BaseSqmToSqlAstConverter.visitJunctionPredicate with combination of treats

---

hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleSqmPathSource.java
hibernate-core/src/test/java/org/hibernate/orm/test/hql/NestedSubqueryTest.java

https://hibernate.atlassian.net/browse/HHH-15731

HHH-15731 Multi-level Derived Tables fail with Unsupported path source: org.hibernate.query.derived.AnonymousTupleSqmPathSource

---

hibernate-core/src/main/java/org/hibernate/engine/spi/SubselectFetch.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/EntityInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityResultInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/collectionelement/ElementCollectionOfEmbeddableWithEntityWithEntityCollectionTest.java

https://hibernate.atlassian.net/browse/HHH-15713

HHH-15713 UnknownTableReferenceException on @ElementCollection of @Embeddable containing a @MayToOne with a @ManyToMany

---

hibernate-core/src/main/java/org/hibernate/query/hql/internal/QuerySplitter.java
hibernate-core/src/test/java/org/hibernate/orm/test/polymorphic/PolymorphicQueriesTest2.java

https://hibernate.atlassian.net/browse/HHH-15744

HHH-15744 HQL where clause parsing fails with StackOverflow exception

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/GroupByTest.java

https://hibernate.atlassian.net/browse/HHH-15749

HHH-15749  Hibernate fails when selecting grouped by entities in a specific order

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/QueryConvertedAttributeTest.java

[HHH-15742](https://hibernate.atlassian.net/browse/HHH-15742)

Hhh 15742 Querying converter attribute fails

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/QueryConvertedAttributeTest.java

Backport for https://hibernate.atlassian.net/browse/HHH-15742

HHH-15742 Querying converter attribute fails

---

documentation/src/test/java/org/hibernate/userguide/mapping/basic/bitset/BitSetRegisteredUserTypeTest.java
hibernate-core/src/main/java/org/hibernate/annotations/CompositeType.java
hibernate-core/src/main/java/org/hibernate/annotations/Type.java
hibernate-core/src/main/java/org/hibernate/annotations/TypeRegistration.java
hibernate-core/src/main/java/org/hibernate/annotations/TypeRegistrations.java
hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java
hibernate-core/src/main/java/org/hibernate/boot/spi/InFlightMetadataCollector.java
hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
hibernate-core/src/main/java/org/hibernate/cfg/annotations/BasicValueBinder.java
hibernate-core/src/main/java/org/hibernate/usertype/CompositeUserType.java
hibernate-core/src/main/java/org/hibernate/usertype/UserType.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/strategy/usertype/registered/Person.java

see https://hibernate.atlassian.net/browse/HHH-15834

HHH-15834 add @TypeRegistration annotation

---

hibernate-core/src/main/java/org/hibernate/cache/internal/TimestampsCacheEnabledImpl.java

https://hibernate.atlassian.net/browse/HHH-15836

HHH-15836 Cleanup unneccessary String <> Serializable casts in TimestampsCacheEnabledImpl

---

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java
hibernate-core/src/main/java/org/hibernate/mapping/Column.java
hibernate-core/src/main/java/org/hibernate/mapping/Table.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardTableExporter.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/EnumJavaType.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/JavaType.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/enums/EnumTypeTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/schematools/EnumCheckTests.java

MySQL doesn't have real check constraints, but it does have something just as good for this special case

reenable check constraings on enum columns, and use MySQL enum column

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EmbeddableMappingType.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityMappingType.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ManagedMappingType.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/PluralAttributeMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractEmbeddableMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/DiscriminatedAssociationAttributeMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddableMappingTypeImpl.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/IdClassEmbeddable.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/VirtualIdEmbeddable.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AttributeMappingsList.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AttributeMappingsMap.java
hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/InsertCoordinator.java
hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
hibernate-core/src/main/java/org/hibernate/persister/internal/EmptyAttributeMappingsMap.java
hibernate-core/src/main/java/org/hibernate/persister/internal/ImmutableAttributeMappingList.java
hibernate-core/src/main/java/org/hibernate/persister/internal/ImmutableAttributeMappingsMap.java
hibernate-core/src/main/java/org/hibernate/persister/internal/MutableAttributeMappingList.java
hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleEmbeddableValuedModelPart.java
hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleEntityValuedModelPart.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/FetchableContainer.java
hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/binding/annotations/access/xml/XmlAccessTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/cfg/persister/GoofyPersisterClassProvider.java
hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/CriteriaEntityGraphTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/EntityGraphLoadPlanBuilderTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/HqlEntityGraphTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ejb3configuration/PersisterClassProviderTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/legacy/CustomPersister.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/attrorder/AttributeOrderingTests.java

https://hibernate.atlassian.net/browse/HHH-15844

HHH-15844 Introduce custom containers for AttributeMapping Lists and Maps

---

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/convert/internal/NamedEnumValueConverter.java

fix an issue spotted by @beikov

HHH-15845 sort enum values on MySQL

---

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderSubSelectFetch.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/persister/entity/UnionSubclassEntityPersister.java
hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/DeleteCoordinator.java
hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/InsertCoordinator.java
hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SimpleDeleteQueryPlan.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java

Fix [HHH-15761](https://hibernate.atlassian.net/browse/HHH-15761) 
Make it possible for Hibernate Reactive to override, reuse some methods without copying them.
[It also add a null check to avoid a NullPointerException](https://github.com/hibernate/hibernate-orm/pull/5751/commits/7723ff0b50beb5c4be948537c3c25a9c9f9d288f) (not sure if it's the right solution)

Changes for Hibernate Reactive

---

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/convert/ConvertedAttributeConcatTest.java

[HHH-15823](https://hibernate.atlassian.net/browse/HHH-15823)

HHH-15823 Unexpected java.lang.AssertionError when use AttributeConverter

---

hibernate-core/src/test/java/org/hibernate/orm/test/jdbc/internal/BasicConnectionTest.java

The test fails on e.g. CockroachDB 21.2 because first DDL is in a Transaction but not the other DML/DDL statements.

HHH-15869 Use explicit transactions for all SQL operations

---

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java
hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/SingleTableInheritanceWithShareCacheModeAllAndCacheConcurrencyStrategyTest.java

https://hibernate.atlassian.net/browse/HHH-15840

HHH-15840 HibernateException: Found shared references to a collection when loading a collection from the cache

---

hibernate-core/src/main/java/org/hibernate/cfg/BinderHelper.java
hibernate-core/src/test/java/org/hibernate/orm/test/id/GenericGeneratorTest.java

https://hibernate.atlassian.net/browse/HHH-15741

HHH-15741 Explicit declaration assigned identifier generator does not work

---

hibernate-core/src/main/java/org/hibernate/sql/results/internal/StandardEntityGraphTraversalStateImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/graphs/EntityGraphTest.java

https://hibernate.atlassian.net/browse/HHH-15859

HHH-15859 Fetching an entity with entity graph for an attribute of type Map fails with an assertion error

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MariaDBLegacySqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/MariaDBSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/TiDBSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/BatchImpl.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcCoordinatorImpl.java
hibernate-core/src/main/java/org/hibernate/engine/spi/SessionFactoryDelegatingImpl.java
hibernate-core/src/main/java/org/hibernate/engine/spi/SessionFactoryImplementor.java
hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java
hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureParameterImpl.java
hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/SqmMutationStrategyHelper.java
hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteInsertStrategy.java
hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteMutationStrategy.java
hibernate-core/src/main/java/org/hibernate/resource/jdbc/internal/LogicalConnectionManagedImpl.java
hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jdbc/internal/JdbcResourceLocalTransactionCoordinatorImpl.java
hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaTransactionCoordinatorImpl.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/sql/exec/spi/JdbcParameterBindings.java
hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/AbstractResultSetAccess.java

- https://hibernate.atlassian.net/browse/HHH-15867

HHH-15867 Avoid runtime services lookup for JdbcServices and BatchBuilder

---

Jenkinsfile
docker_db.sh
nightly.Jenkinsfile

https://hibernate.atlassian.net/browse/HHH-15863

HHH-15863 Update PostgreSQL testing to version 15

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/CompoundNaturalIdMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/DiscriminatedAssociationMapping.java
hibernate-core/src/main/java/org/hibernate/query/results/complete/EntityResultImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/AbstractFetchParent.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/EagerCollectionFetch.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/AggregateEmbeddableFetchImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/AggregateEmbeddableResultImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableExpressionResultImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableForeignKeyResultImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableResultImpl.java

https://hibernate.atlassian.net/browse/HHH-15873

HHH-15873 Micro optimisations of FetchParent#findFetch(Fetchable) operations

---

hibernate-core/src/main/java/org/hibernate/dialect/CockroachSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/H2SqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/MariaDBSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/MySQLServerConfiguration.java
hibernate-core/src/main/java/org/hibernate/dialect/MySQLSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/TiDBDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/TiDBSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/LikeEscapeDefaultTest.java

Backport of https://github.com/hibernate/hibernate-orm/pull/5746 and https://github.com/hibernate/hibernate-orm/pull/5772

HHH-15736 Make sure dialects have default like-predicate escape char configured

---

hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryContext.java
hibernate-core/src/main/java/org/hibernate/engine/internal/ManagedTypeHelper.java
hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java

https://hibernate.atlassian.net/browse/HHH-15878

HHH-15878 Micro optimisations of StatefulPersistenceContext#clear

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/CompoundNaturalIdMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/DiscriminatedAssociationMapping.java
hibernate-core/src/main/java/org/hibernate/query/results/complete/EntityResultImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/AbstractFetchParent.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/EagerCollectionFetch.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableForeignKeyResultImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableResultImpl.java

https://hibernate.atlassian.net/browse/HHH-15873

Backport for HHH-15873

---

documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/GlobalTemporaryTableStrategy.java
hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/PersistentTableInsertStrategy.java
hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/PersistentTableStrategy.java
hibernate-core/src/test/java/org/hibernate/orm/test/persister/entity/TemporaryTableStrategyTest.java
hibernate-core/src/test/resources/log4j2.properties

[HHH-15550](https://hibernate.atlassian.net/browse/HHH-15550)

HHH-15550 Allow controlling whether Global- and PersistentTemporaryTables should be created

---

hibernate-core/src/main/java/org/hibernate/dialect/MySQLSqlAstTranslator.java

Fix for problem introduced with https://github.com/hibernate/hibernate-orm/pull/5773

HHH-15736 Fix like-escape for MySQL versions before 8.0.24

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacySqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/MySQLSqlAstTranslator.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaOrderedSetAggregateTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/timezones/JDBCTimeZoneZonedTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/timezones/UTCNormalizedZonedTest.java

Fix some failing tests on Oracle 11 and other specific dbs.

HHH-15654 Fix failing criteria set-ordered tests for some dbs + some more failing tests

---

hibernate-core/src/main/java/org/hibernate/id/SelectGenerator.java
hibernate-core/src/test/java/org/hibernate/orm/test/generatedkeys/select/SelectGeneratorTest.java

https://hibernate.atlassian.net/browse/HHH-15900

HHH-15900 ID attributes  with "select" generator are mapped to identity columns

---

hibernate-core/src/main/java/org/hibernate/Hibernate.java
hibernate-core/src/main/java/org/hibernate/annotations/LazyCollection.java
hibernate-core/src/main/java/org/hibernate/annotations/LazyCollectionOption.java
hibernate-core/src/main/java/org/hibernate/collection/spi/AbstractPersistentCollection.java
hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentBag.java
hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentList.java
hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentMap.java
hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentSet.java
hibernate-core/src/test/java/org/hibernate/orm/test/collection/basic/CollectionSizeTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/collection/basic/Contact.java

HHH-15910 Add static remove methods to Hibernate.class

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/BasicAttributeMapping.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/EmbeddableLazyFetchTest.java

https://hibernate.atlassian.net/browse/HHH-15778

HHH-15778 HHH-15778 Fetching an Entity with a lazily loaded Embeddable with more fields than the parent results in an ArrayIndexOutOfBoundsException

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/BasicAttributeMapping.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/EmbeddableLazyFetchTest.java

https://hibernate.atlassian.net/browse/HHH-15778

HHH-15778 Fetching an Entity with a lazily loaded Embeddable with more fields than the parent results in an ArrayIndexOutOfBoundsException

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleNaturalIdMapping.java
hibernate-core/src/test/java/org/hibernate/orm/test/uniquekey/PrimitiveArrayNaturalIdTest.java

https://hibernate.atlassian.net/browse/HHH-15784

HHH-15784 Primitive array as Natural ID causes ClassCastException

---

hibernate-core/src/main/java/org/hibernate/dialect/MariaDBSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/MySQLSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/TiDBSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/CriteriaWithWhereClauseAndColumnDefinitionTest.java

https://hibernate.atlassian.net/browse/HHH-15805

HHH-15805 Subquery with where condition on a column with columnDefinition results in wrong SQL grammar

---

hibernate-core/src/main/java/org/hibernate/boot/model/FunctionContributor.java
hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/InferredBasicValueResolver.java
hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/EnumJavaType.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/ArrayJdbcType.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/enumerated/EnumeratedSmokeTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/binding/annotations/basics/EnumResolutionTests.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/SmokeTests.java
hibernate-core/src/test/java/org/hibernate/orm/test/sql/ast/SmokeTests.java
hibernate-core/src/test/java/org/hibernate/orm/test/type/EnumArrayTest.java

... based on the number of members of the `enum`.
See https://hibernate.atlassian.net/browse/HHH-15912.

HHH-15912 adaptively choose the DDL type for ORDINAL enums 

---

hibernate-core/src/main/java/org/hibernate/annotations/Instantiator.java
hibernate-core/src/main/java/org/hibernate/cfg/AggregateComponentSecondPass.java
hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
hibernate-core/src/main/java/org/hibernate/dialect/OracleStructJdbcType.java
hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLStructJdbcType.java
hibernate-core/src/main/java/org/hibernate/dialect/StructHelper.java
hibernate-core/src/main/java/org/hibernate/mapping/Component.java
hibernate-core/src/main/java/org/hibernate/mapping/UserDefinedType.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableHelper.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableInstantiatorPojoIndirecting.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableInstantiatorPojoStandard.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableRepresentationStrategyPojo.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/ManagedTypeRepresentationResolverStandard.java
hibernate-core/src/test/java/org/hibernate/orm/test/component/StructComponentInstantiatorTest.java
hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/ComponentMetadataGenerator.java

https://hibernate.atlassian.net/browse/HHH-15898

HHH-15898 Add @Instantiator annotation to mark canonical constructor for embeddables

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2LegacyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java
hibernate-core/src/main/java/org/hibernate/query/criteria/HibernateCriteriaBuilder.java
hibernate-core/src/main/java/org/hibernate/query/criteria/JpaCrossJoin.java
hibernate-core/src/main/java/org/hibernate/query/criteria/JpaFrom.java
hibernate-core/src/main/java/org/hibernate/query/criteria/spi/HibernateCriteriaBuilderDelegate.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmFrom.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/from/SqmCrossJoin.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaBuilderNonStandardFunctionsTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaCrossJoinTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaOrderedSetAggregateTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/HibernateCriteriaBuilderFunctionsTest.java

https://hibernate.atlassian.net/browse/HHH-15868

HHH-15868 Expose more standard HQL functions through HibernateCriteriaBuilder

---

settings.gradle

https://hibernate.atlassian.net/browse/HHH-15920

HHH-15920 Update Mockito to 4.10.0

---

hibernate-core/src/main/java/org/hibernate/query/hql/internal/QuerySplitter.java
hibernate-core/src/test/java/org/hibernate/orm/test/polymorphic/PolymorphicQueriesTest2.java

https://hibernate.atlassian.net/browse/HHH-15850

HHH-15850 NullPointerException when parsing HQL query with like statement and interface is used

---

hibernate-core/src/main/java/org/hibernate/annotations/CompositeType.java
hibernate-core/src/main/java/org/hibernate/annotations/CompositeTypeRegistration.java
hibernate-core/src/main/java/org/hibernate/annotations/Type.java
hibernate-core/src/main/java/org/hibernate/annotations/TypeRegistration.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotationBinder.java

this was almost zero work, the implementation was already there

HHH-15926 allow @Type and @CompositeType to be applied as meta-annotations

---

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQuerySpec.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/EmptyPredicateTest.java

Backport of https://github.com/hibernate/hibernate-orm/pull/5831

HHH-15901 Criteria Query throws a NullPointerException when I use an empty predicates list

---

documentation/src/test/java/org/hibernate/userguide/sql/SQLTest.java
hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java

HHH-15914 - fix native query when the result class is Object or Object[]

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/AbstractCollectionInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/orphan/onetomany/embedded/DeleteOneToManyOrphansEmbeddedTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/orphan/onetomany/embedded/OneToManyInEmbeddedTest.java

https://hibernate.atlassian.net/browse/HHH-15864

HHH-15864 OrphanRemoval does not work with embeddables when deleting entity

---

documentation/src/test/java/org/hibernate/userguide/sql/SQLTest.java

and provide an example of Tuple.class usage

HHH-15914 - remove deprecated method calls

---

documentation/src/test/java/org/hibernate/userguide/sql/SQLTest.java

HHH-15914 - Add jira tag to some tests

---

hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java

+ more cleanups of HSQLDialect

HHH-14338 use SESSION prefix instead of MODULE for temp tables on HSQLDB

---

hibernate-core/src/main/java/org/hibernate/Session.java
hibernate-core/src/main/java/org/hibernate/SessionFactory.java
hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/RelationalObjectBinder.java
hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
hibernate-core/src/main/java/org/hibernate/context/spi/CurrentSessionContext.java
hibernate-core/src/main/java/org/hibernate/dialect/temptable/TemporaryTable.java
hibernate-core/src/main/java/org/hibernate/event/spi/EventEngine.java
hibernate-core/src/main/java/org/hibernate/id/ExportableColumn.java
hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
hibernate-core/src/main/java/org/hibernate/mapping/Column.java
hibernate-core/src/main/java/org/hibernate/mapping/Formula.java
hibernate-core/src/main/java/org/hibernate/mapping/Selectable.java
hibernate-core/src/main/java/org/hibernate/mapping/package-info.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/query/sqm/function/SelfRenderingFunctionSqlAstExpression.java
hibernate-core/src/main/javadoc/overview.html

- make state model of `Column` safer
- clean up the constructor of `SessionFactoryImpl`

some work on Column and on SessionFactoryImpl

---

hibernate-core/src/main/java/org/hibernate/boot/model/TruthValue.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/Helper.java
hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java

- even though I hate most of its members, I think `NONE` is pretty useful
- anyway we may as well make it work, since it's trivial
Let's see what breaks.

HHH-15954 correct implementation of JPA SharedCacheMode for .hbm.xml

---

hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java
hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/BatchImpl.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcCoordinatorImpl.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/MutationStatementPreparerImpl.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/StatementPreparerImpl.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/JdbcServices.java
hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java
hibernate-core/src/main/java/org/hibernate/internal/JdbcObserverImpl.java
hibernate-core/src/main/java/org/hibernate/internal/JdbcSessionContextImpl.java
hibernate-core/src/main/java/org/hibernate/resource/jdbc/LogicalConnection.java
hibernate-core/src/main/java/org/hibernate/resource/jdbc/internal/LogicalConnectionManagedImpl.java
hibernate-core/src/main/java/org/hibernate/resource/jdbc/spi/JdbcObserver.java
hibernate-core/src/main/java/org/hibernate/resource/jdbc/spi/JdbcSessionContext.java
hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jdbc/internal/JdbcIsolationDelegate.java
hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jdbc/internal/JdbcResourceLocalTransactionCoordinatorBuilderImpl.java
hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jdbc/internal/JdbcResourceLocalTransactionCoordinatorImpl.java
hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaIsolationDelegate.java
hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaTransactionCoordinatorBuilderImpl.java
hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaTransactionCoordinatorImpl.java
hibernate-core/src/main/java/org/hibernate/resource/transaction/spi/TransactionCoordinator.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/transaction/batch/AbstractBatchingTest.java

- encapsulate stuff better within JdbcSessionContext
- fix lots of warnings
- deprecate stuff

clean up the JdbcSessionContext SPI + related code

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddedAttributeMapping.java
hibernate-core/src/test/java/org/hibernate/orm/test/compositefk/OneToManyNestedEmbeddedIdTest.java

https://hibernate.atlassian.net/browse/HHH-15865

HHH-15865 OneToMany foreign key relation throws when id is inside nested embeddables

---

documentation/src/main/asciidoc/userguide/chapters/pc/PersistenceContext.adoc
documentation/src/main/asciidoc/userguide/chapters/pc/extras/pc-filter-entity-example.sql

HHH-15617 : https://hibernate.atlassian.net/browse/HHH-15617
This issue was fixed as part of this PR:
Issue: https://hibernate.atlassian.net/browse/HHH-14772
PR: https://github.com/hibernate/hibernate-orm/pull/4132/files
However, some documentation changes were missed. So, adding these changes.

Fix Documentation for direct fetching with Filter

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddableMappingTypeImpl.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/test/java/org/hibernate/orm/test/compositefk/OneToManyEmbeddedIdFKNotNullableTest.java

https://hibernate.atlassian.net/browse/HHH-15866

HHH-15866 Hibernate validation fails when OneToMany refers to fereign key in embeddable object and is marked as nullable false

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/EagerOneToOneMappedByInDoubleEmbeddedTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/LazyOneToOneMappedByInDoubleEmbeddedTest.java

https://hibernate.atlassian.net/browse/HHH-15967
[HHH-15967]: https://hibernate.atlassian.net/browse/HHH-15967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HHH-15967 @OneToOne(mappedBy = ..., fetch = LAZY) in embedded referencing an association within another embedded

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/NestedEmbeddedWitnNotOptionalManyToOneTest.java

https://hibernate.atlassian.net/browse/HHH-15794
[HHH-15794]: https://hibernate.atlassian.net/browse/HHH-15794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HHH-15794 NullPointerException when constructing mapping model for nested embeddables with not optional ManyToOne

---

hibernate-core/src/main/java/org/hibernate/engine/spi/SubselectFetch.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/AbstractImmediateCollectionInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/DelayedCollectionInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/EntityInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityResultInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesSourceProcessingStateStandardImpl.java

https://hibernate.atlassian.net/browse/HHH-15854

HHH-15854 Improve CollectionInitializer and EntityDelayedFetchInitializer resolveInstance methods performance when the parent entity is initialized

---

documentation/src/test/java/org/hibernate/userguide/pc/FilterSqlFragementAliasTest.java
hibernate-core/src/main/java/org/hibernate/annotations/Comment.java
hibernate-core/src/main/java/org/hibernate/annotations/Comments.java
hibernate-core/src/main/java/org/hibernate/binder/internal/CommentsBinder.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/comment/CommentsTest.java

I didn't quite nail this one first time round :-/

HHH-15960 make @Comment annotation repeatable and properly test it

---

hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/InformixDialectTestCase.java
hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/function/ChrLiteralEmulation.java
hibernate-core/src/main/java/org/hibernate/engine/spi/SessionFactoryDelegatingImpl.java
hibernate-core/src/main/java/org/hibernate/engine/spi/SessionFactoryImplementor.java
hibernate-core/src/main/java/org/hibernate/internal/QueryParameterBindingTypeResolverImpl.java
hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
hibernate-core/src/main/java/org/hibernate/metamodel/MappingMetamodel.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappingMetamodelImpl.java
hibernate-core/src/main/java/org/hibernate/metamodel/spi/MappingMetamodelImplementor.java
hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java
hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingImpl.java
hibernate-core/src/main/java/org/hibernate/query/spi/AbstractCommonQueryContract.java
hibernate-core/src/main/java/org/hibernate/query/spi/QueryEngine.java
hibernate-core/src/main/java/org/hibernate/query/spi/QueryEngineOptions.java
hibernate-core/src/main/java/org/hibernate/query/spi/QueryParameterBindingTypeResolver.java
hibernate-core/src/main/java/org/hibernate/query/sqm/NodeBuilder.java
hibernate-core/src/main/java/org/hibernate/query/sqm/function/AbstractSqmFunctionDescriptor.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/ArgumentTypesValidator.java
hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/ArgumentsValidator.java
hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/StandardArgumentsValidators.java
hibernate-core/src/main/java/org/hibernate/sql/exec/internal/AbstractJdbcParameter.java

This is something I just didn't want to deal with last night.

sort out an issue with function argument validation

---

hibernate-core/src/main/java/org/hibernate/sql/results/internal/InitializersList.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/ResultsHelper.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/RowProcessingStateStandardImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/StandardRowReader.java
hibernate-core/src/main/java/org/hibernate/sql/results/spi/ListResultsConsumer.java
hibernate-core/src/main/java/org/hibernate/sql/results/spi/RowReader.java

https://hibernate.atlassian.net/browse/HHH-15976
[HHH-15976]: https://hibernate.atlassian.net/browse/HHH-15976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HHH-15976 Optimize row processing by pre-classifying different types of Initializer instances

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/function/PostgreSQLTruncRoundFunction.java
hibernate-core/src/test/java/org/hibernate/orm/test/dialect/function/PostgreSQLTruncRoundFunctionTest.java

https://hibernate.atlassian.net/browse/HHH-15985

HHH-15985 Use builtin PostgreSQL trunc and round two-argument functions when possible

---

hibernate-core/src/test/java/org/hibernate/orm/test/length/BinaryLengthTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/length/LengthTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/length/WithLongByteArrays.java
hibernate-core/src/test/java/org/hibernate/orm/test/length/WithLongStrings.java

to make sure it's possible to have programs with byte[] fields work across Postgres and others

add BinaryLengthTest

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedSimplePath.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/treat/HqlTreatJoinTest.java

https://hibernate.atlassian.net/browse/HHH-15839

HHH-15839 CriteriaBuilder treat method on Path causes ClassCastException

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/RefreshAndBatchTest.java

https://hibernate.atlassian.net/browse/HHH-15851

HHH-15851 Mixup of entities in refresh with BatchSize

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/RefreshAndBatchTest.java

https://hibernate.atlassian.net/browse/HHH-15851

HHH-15851 Mixup of entities in refresh with BatchSize 

---

hibernate-core/src/main/java/org/hibernate/dialect/DB2SqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/DB2iSqlAstTranslator.java

Backport for https://github.com/hibernate/hibernate-orm/pull/5924

HHH-15890 Fix shouldEmulateFetchClause method for DB2(i)SqlAstTranslator

---

hibernate-core/src/main/java/org/hibernate/dialect/DB2SqlAstTranslator.java

https://hibernate.atlassian.net/browse/HHH-15957

HHH-15957 Hibernate 6.1.6 Infinite Recursion/StackOverflow Using DB2 Custom Dialect

---

hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/test/java/org/hibernate/orm/test/hql/HqlSubselectParameterTest.java

https://hibernate.atlassian.net/browse/HHH-15647

HHH-15647 Subselect with long parameter wrongly cast to bigint for MySQL

---

hibernate-core/src/main/java/org/hibernate/sql/results/internal/domain/CircularBiDirectionalFetchImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/EagerOneToOneMappedByInDoubleEmbeddedTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/LazyToOneMappedByInDoubleEmbeddedTest.java

https://hibernate.atlassian.net/browse/HHH-15986

HHH-15986 Eager Bidirectional association, initializing an HibernateProxy should associate to the circular association the HibernateProxy  itself

---

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/SqmCopyContext.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmPath.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmEntityValuedSimplePath.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmIndexedCollectionAccessPath.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmPluralValuedSimplePath.java
hibernate-core/src/main/java/org/hibernate/spi/TreatedNavigablePath.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/TreatPathTest.java

https://hibernate.atlassian.net/browse/HHH-16004 was already solved by https://github.com/hibernate/hibernate-orm/pull/5866 but the test highlighted new issues, see: https://hibernate.atlassian.net/browse/HHH-16014.

HHH-16014 Querying property from treated path causes IllegalArgumentException: Already registered a copy

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/DelayedCollectionInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/EntityInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntityInsideEmbeddableSelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntitySelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchByUniqueKeyInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/domain/CircularBiDirectionalFetchImpl.java

- https://hibernate.atlassian.net/browse/HHH-16029
- https://hibernate.atlassian.net/browse/HHH-16030

Improve contract for entity result initializers

---

hibernate-core/src/main/java/org/hibernate/annotations/Where.java
hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
hibernate-core/src/test/java/org/hibernate/orm/test/where/annotations/EagerManyToOne2Test.java
hibernate-core/src/test/java/org/hibernate/orm/test/where/annotations/EagerManyToOne3Test.java
hibernate-core/src/test/java/org/hibernate/orm/test/where/annotations/EagerManyToOneTest.java

https://hibernate.atlassian.net/browse/HHH-15902

HHH-15902 @OneToMany relationship with @Where on child table generates wrong sql

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacySqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/SQLServerSqlAstTranslator.java
hibernate-core/src/test/java/org/hibernate/orm/test/dialect/functional/SqlServerDistinctFetchOffsetTest.java

https://hibernate.atlassian.net/browse/HHH-15928

HHH-15928 Distinct with maxResults fails under SQLServer

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ModelPartContainer.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/SelectablePath.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
hibernate-core/src/main/java/org/hibernate/spi/DotIdentifierSequence.java
hibernate-core/src/main/java/org/hibernate/spi/NavigablePath.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/FetchParentAccess.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/AggregateEmbeddableInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/EntityInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/AbstractBatchEntitySelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/embeddables/nested/fieldaccess/FieldAccessedNestedEmbeddableMetadataTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/access/NestedEmbeddableDefaultAccessTests.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/EmbeddableWithToOneAssociation2Test.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/EmbeddableWithToOneAssociation3Test.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/EmbeddableWithToOneAssociation4Test.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/EmbeddableWithToOneAssociationTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/elementcollection/EmbeddableWithToOneAssociationTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/elementcollection/EmbeddedElementCollectionWithIdenticallyNamedAssociation2Test.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/elementcollection/EmbeddedElementCollectionWithIdenticallyNamedAssociationTest.java
hibernate-envers/src/test/java/org/hibernate/orm/test/envers/entities/components/Component4.java

https://hibernate.atlassian.net/browse/HHH-15604
https://hibernate.atlassian.net/browse/HHH-15966

HHH-15604 HHH-15966 Identically-named association in entity root and elementcollection of embeddables leads to assertion error

---

hibernate-core/src/main/java/org/hibernate/dialect/SQLServerSqlAstTranslator.java
hibernate-core/src/test/java/org/hibernate/orm/test/dialect/functional/SqlServerDistinctFetchOffsetTest.java

Backport of https://github.com/hibernate/hibernate-orm/pull/5939.

 HHH-15928 Distinct with maxResults fails under SQLServer #5939

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacyDialect.java
hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/DateTimeUtils.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/StandardFunctionTests.java

...and also improve datetime literal rendering on DB2, MySQL, and (just a touch) Oracle.

more HQL duration tests

---

hibernate-core/src/main/java/org/hibernate/cache/spi/entry/StandardCacheEntryImpl.java
hibernate-core/src/main/java/org/hibernate/event/service/internal/EventListenerGroupImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/test/java/org/hibernate/event/service/internal/EventListenerDuplicationStrategyTest.java

https://hibernate.atlassian.net/browse/HHH-16046
Also related: https://github.com/hibernate/hibernate-orm/discussions/5956

HHH-16046 Improve event listener groups processing

---

hibernate-core/src/main/java/org/hibernate/event/internal/AbstractFlushingEventListener.java
hibernate-core/src/main/java/org/hibernate/event/spi/FlushEntityEvent.java

https://hibernate.atlassian.net/browse/HHH-16047

HHH-16047 Allow reusing of FlushEntityEvent instances

---

hibernate-core/src/main/java/org/hibernate/dialect/OracleSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/internal/util/collections/Stack.java
hibernate-core/src/main/java/org/hibernate/internal/util/collections/StandardStack.java
hibernate-core/src/main/java/org/hibernate/query/hql/internal/QuerySplitter.java
hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/sql/results/spi/LoadContexts.java

https://hibernate.atlassian.net/browse/HHH-16051

HHH-16051 Avoid stateful lambdas on invocations of Stack#findCurrentFirst

---

hibernate-core/src/main/java/org/hibernate/engine/spi/CollectionKey.java
hibernate-core/src/main/java/org/hibernate/engine/spi/EntityKey.java
hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
hibernate-core/src/main/java/org/hibernate/type/AbstractStandardBasicType.java
hibernate-core/src/main/java/org/hibernate/type/EntityType.java

https://hibernate.atlassian.net/browse/HHH-16052

HHH-16052 EntityKey and CollectionKey equality optimisation

---

hibernate-core/src/main/java/org/hibernate/dialect/pagination/AbstractLimitHandler.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/NativeQueryLimitOffsetTest.java

HHH-16020 - Fix for incorrect offset parameter index

---

hibernate-integrationtest-java-modules/hibernate-integrationtest-java-modules.gradle
settings.gradle

- https://hibernate.atlassian.net/browse/HHH-16060

HHH-16060 Upgrade Narayana used for integration testing to version 6.0.0.CR1

---

hibernate-core/src/main/java/org/hibernate/boot/model/FunctionContributions.java

...because in fairness this is a little hard to find.

add convenience method to retrieve Dialect from FunctionContributions

---

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmDynamicInstantiation.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/DynamicMapInstantiationTest.java

https://hibernate.atlassian.net/browse/HHH-16061

HHH-16061 SqmDynamicInstantiation warns about dynamic Map instantiation when using an entity

---

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmDynamicInstantiation.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/DynamicMapInstantiationTest.java

https://hibernate.atlassian.net/browse/HHH-16061

HHH-16061 HHH-16061 SqmDynamicInstantiation warns about dynamic Map instantiation when using an entity

---

hibernate-core/src/main/java/org/hibernate/graph/internal/parse/GraphParser.java
hibernate-core/src/main/java/org/hibernate/internal/util/collections/StandardStack.java
hibernate-core/src/main/java/org/hibernate/query/hql/internal/QuerySplitter.java
hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
hibernate-core/src/main/java/org/hibernate/query/results/DomainResultCreationStateImpl.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/DomainResultGraphPrinter.java
hibernate-core/src/main/java/org/hibernate/sql/results/spi/LoadContexts.java
hibernate-core/src/test/java/org/hibernate/orm/test/util/StandardStackTest.java

https://hibernate.atlassian.net/browse/HHH-16050

HHH-16050 Optimize iteration efficiency in StandardStack 

---

hibernate-core/src/main/java/org/hibernate/query/spi/AbstractCommonQueryContract.java
hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java

clean up impl of query hint interpretation

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacySqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/MySQLSqlAstTranslator.java

Fix for https://github.com/hibernate/hibernate-orm/pull/5944 version check.

Fix wrong version check in from dual for select only for MySQL

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedJoinColumn.java
hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDeleteEventListener.java
hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
hibernate-core/src/main/java/org/hibernate/persister/collection/BasicCollectionPersister.java
hibernate-core/src/main/java/org/hibernate/persister/collection/OneToManyPersister.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/DeleteRowsCoordinatorStandard.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java
hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
hibernate-core/src/main/java/org/hibernate/sql/model/ast/builder/RestrictedTableMutationBuilder.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/manytomany/ManyToManyInverseJoinColumnSortedSetTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/cfg/persister/GoofyPersisterClassProvider.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ejb3configuration/PersisterClassProviderTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/legacy/CustomPersister.java
hibernate-core/src/test/java/org/hibernate/orm/test/manytomanyassociationclass/nestedreference/Item.hbm.xml
hibernate-core/src/test/java/org/hibernate/orm/test/manytomanyassociationclass/nestedreference/Item.java
hibernate-core/src/test/java/org/hibernate/orm/test/manytomanyassociationclass/nestedreference/ItemSelfReferenceTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/manytomanyassociationclass/nestedreference/OtherItem.java
hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/manytomany/unidirectional/JoinTableDetachedTest.java

https://hibernate.atlassian.net/browse/HHH-16031
https://hibernate.atlassian.net/browse/HHH-16033
alternative to https://github.com/hibernate/hibernate-orm/pull/5948

HHH-16031 @ManyToMany with @JoinTable(inverseColumn = ...) and SortedSet may results in data loss

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/secondary/RefToSecondaryTableTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/subclass/Animal.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/subclass/Cat.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/subclass/RefToJoinedSuperclassTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/subclass/Toy.java

https://hibernate.atlassian.net/browse/HHH-15933

HHH-15933 broken SQL generated for @ManyToOne with @JoinColumn which references a column of a @SecondaryTable

---

hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/H2SqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/ColumnReference.java
hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/UpsertOperation.java
hibernate-core/src/test/java/org/hibernate/orm/test/secondarytable/Record.java
hibernate-core/src/test/java/org/hibernate/orm/test/secondarytable/SecondaryRowTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/secondarytable/SpecialRecord.java
hibernate-core/src/test/java/org/hibernate/orm/test/write/UpsertTests.java

https://hibernate.atlassian.net/browse/HHH-16084
H2 MERGE command support for handling optional secondary table updates

HHH-16084 - MERGE (upsert) for optional table updates - H2

---

docker_db.sh

With the previous setting the cockroach process is killed by the OOM-killer.

Update memory config for CockroachDB configuration

---

hibernate-core/src/main/java/org/hibernate/cache/internal/BasicCacheKeyImplementation.java
hibernate-core/src/main/java/org/hibernate/cache/internal/CacheKeyImplementation.java
hibernate-core/src/main/java/org/hibernate/cache/internal/DefaultCacheKeysFactory.java
hibernate-core/src/test/java/org/hibernate/orm/test/caching/mocked/CacheKeyImplementationHashCodeTest.java

https://hibernate.atlassian.net/browse/HHH-16092

HHH-16092 Trim allocation size of CacheKeyImplementation, avoid Objects::deepEquals

---

hibernate-core/src/main/java/org/hibernate/type/AbstractStandardBasicType.java

- https://hibernate.atlassian.net/browse/HHH-16090
- https://hibernate.atlassian.net/browse/HHH-16091

Avoiding megamorphic calls in AbstractStandardBasicType

---

hibernate-core/src/test/java/org/hibernate/orm/test/type/VarbinaryArrayTest.java

https://hibernate.atlassian.net/browse/HHH-16085

HHH-16085 Test using @JdbcTypeCode(Types.VARBINARY) on arrays to revert to pre-6.1 behavior

---

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderBatchKey.java
hibernate-core/src/test/java/org/hibernate/orm/test/batchfetch/NestedLazyManyToOneTest.java
hibernate-testing/src/main/java/org/hibernate/testing/jdbc/SQLStatementInspector.java

Backport of https://github.com/hibernate/hibernate-orm/pull/5991.

HHH-16043 Hibernate 6.x breaks collection batch fetching

---

hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaTimeoutTest.java

https://hibernate.atlassian.net/browse/HHH-16062

HHH-16062 jakarta.persistence.query.timeout not working on Hibernate 6.1.6 for Criteria Queries

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/BasicValuedCollectionPart.java
hibernate-core/src/main/java/org/hibernate/query/results/DomainResultCreationStateImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/basic/BasicResultAssembler.java

Very minor optimisation
- https://hibernate.atlassian.net/browse/HHH-16090

HHH-16090 BasicResultAssembler logging optimisations

---

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/H2SqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/SQLServerSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/SqlAstTranslatorWithMerge.java
hibernate-core/src/main/java/org/hibernate/sql/model/ast/builder/TableUpdateBuilderStandard.java
hibernate-core/src/main/java/org/hibernate/sql/model/internal/OptionalTableUpdate.java
hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/MergeOperation.java
hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/OptionalTableUpdateOperation.java
hibernate-core/src/test/java/org/hibernate/orm/test/write/OptionalTableUpdateTests.java

https://hibernate.atlassian.net/browse/HHH-16103

HHH-16103 - MERGE for optional table updates on SQL Server

---

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ql/NamedNativeQueryWithGenericsTest.java

https://hibernate.atlassian.net/browse/HHH-16023

HHH-16023 ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 for NamedNativeQuery with generics

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/ClassPropertyHolder.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/AttributeFactory.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java
hibernate-core/src/test/java/org/hibernate/orm/test/compositefk/OneToOneEmbeddedIdWithGenericsTest.java

https://hibernate.atlassian.net/browse/HHH-16070

HHH-16070 Exception when find by association id that is a generic @EmbeddedId with @MappedSuperclass

---

hibernate-core/src/main/java/org/hibernate/dialect/pagination/LegacyOracleLimitHandler.java

... due to the fix for HHH-16020

HHH-16020 - Fix for error that surfaced in the LegacyOracleLimitHandler

---

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmEntityValuedSimplePath.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmFkExpression.java
hibernate-core/src/test/java/org/hibernate/orm/test/persister/entity/AbstractTreeableEntityTest.java
settings.gradle

[HHH-15822](https://hibernate.atlassian.net/browse/HHH-15822)
[HHH-15822]: https://hibernate.atlassian.net/browse/HHH-15822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HHH-15822 Unexpected org.hibernate.UnknownEntityTypeException: Unable to locate persister

---

hibernate-core/src/test/java/org/hibernate/orm/test/annotations/embeddables/EmbeddableWithGenericAndMappedSuperClassTest.java

HHH-4299 - Add test for issue

---

migration-guide.adoc

- remove some unfinished sentence
- remove the paragraph describing the old behavior

Clean up "Fetch circularity determination" migration section

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/FromClauseAccess.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/SimpleFromClauseAccessImpl.java
hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/MappedByTableGroup.java
hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/StandardVirtualTableGroup.java
hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/VirtualTableGroup.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/SameTableAliasInSubqueryWithEmbeddedTest.java

https://hibernate.atlassian.net/browse/HHH-16003

HHH-16003 Wrong alias used in subquery generated from JPQL

---

hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/SequenceInformationExtractorMariaDBDatabaseImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/dialect/functional/MariaDBExtractSequenceInformationTest.java

HHH-15665 - Fix and added test for issue

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesSourceProcessingStateStandardImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/inheritance/SingleTableInheritanceEagerAssociationTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/inheritance/SingleTableInheritanceLazyAssociationTest.java

https://hibernate.atlassian.net/browse/HHH-15969

HHH-15969 Inheritance: org.hibernate.PropertyAccessException Exception

---

hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/MappedSuperclassAndGenericsTest.java

https://hibernate.atlassian.net/browse/HHH-15970
It seems the issue has been resolved in main

HHH-15970 Issue when combining Postgres driver, @MappedSuperclass, generics and enums

---

hibernate-core/src/main/java/org/hibernate/query/hql/internal/QuerySplitter.java
hibernate-core/src/main/java/org/hibernate/query/sqm/SemanticQueryWalker.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmBagJoin.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedBagJoin.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedCrossJoin.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedEntityJoin.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedListJoin.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedMapJoin.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedPluralPartJoin.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedRoot.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedRootJoin.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedSetJoin.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedSingularJoin.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelation.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmListJoin.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmMapJoin.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmSetJoin.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmSingularJoin.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/from/SqmAttributeJoin.java
hibernate-core/src/test/java/org/hibernate/orm/test/polymorphic/PolymorphicQueriesWithJoinTest.java

https://hibernate.atlassian.net/browse/HHH-15944
alternative solution to https://github.com/hibernate/hibernate-orm/pull/5999

HHH-15944 Joins on non-managed-type polymorphisms don't work

---

hibernate-core/src/main/java/org/hibernate/collection/spi/AbstractPersistentCollection.java
hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
hibernate-core/src/main/java/org/hibernate/engine/spi/PersistenceContext.java
hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesSourceProcessingStateStandardImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/spi/LoadContexts.java
hibernate-core/src/test/java/org/hibernate/orm/test/collection/list/Child.java
hibernate-core/src/test/java/org/hibernate/orm/test/collection/list/IterateOverListInTheSetMethodTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/collection/list/Parent.java
hibernate-core/src/test/java/org/hibernate/orm/test/collection/list/ParentChildMapping.hbm.xml

https://hibernate.atlassian.net/browse/HHH-16120

HHH-16120 Error advancing (next) ResultSet position

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/BasicAttributeMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/BasicEntityIdentifierMappingImpl.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/basic/BasicFetch.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/basic/BasicResult.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/basic/BasicResultAssembler.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/basic/CoercingResultAssembler.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/PrimitiveCharacterArrayJavaType.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/StringJavaType.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/TreatPathTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/joincolumn/CharArrayToStringJoinColumnTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/joincolumn/StringToCharArrayJoinColumnTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/joincolumn/embedded/CharArrayToStringInEmbeddedJoinColumnOrFormulaTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/joincolumn/embedded/CharArrayToStringInEmbeddedJoinColumnTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/joincolumn/embedded/CharArrayToStringInEmbeddedMultipleJoinColumnTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/joincolumn/embedded/StringToCharArrayInEmbeddedJoinColumnTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/joincolumn/embedded/StringToCharArrayInEmbeddedMultipleJoinColumnTest.java

https://hibernate.atlassian.net/browse/HHH-16040
https://hibernate.atlassian.net/browse/HHH-15916

HHH-16040 AssertionError for @JoinColumn with char[] property referencing a String property

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/instantiation/DynamicInstantiationWithJoinAndGroupAndOrderByByTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/instantiation/DynamicInstantiationWithJoinAndGroupByAndParameterTest.java

https://hibernate.atlassian.net/browse/HHH-15991
https://hibernate.atlassian.net/browse/HHH-15998

HHH-15998 Incomplete group by expression when with "NEW" operator

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/instantiation/DynamicInstantiationWithJoinAndGroupAndOrderByByTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/instantiation/DynamicInstantiationWithJoinAndGroupByAndParameterTest.java

Backport of https://github.com/hibernate/hibernate-orm/pull/6052.

HHH-15998 HHH-15991 Incomplete group by expression when with "NEW" operator

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionPropertyHolder.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/MapBinder.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/map/MapElementBaseTypeConversionTest.java

https://hibernate.atlassian.net/browse/HHH-15733

HHH-15733 @Convert on Map should not require "attributeName=value"

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/ClassPropertyHolder.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/HHH16122Test.java

https://hibernate.atlassian.net/browse/HHH-16122

[HHH-16122] Fix determining the type of a property during type variable resolving for mapped superclasses

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/SingularAttributeImpl.java
hibernate-core/src/main/java/org/hibernate/query/sqm/SqmJoinable.java
hibernate-core/src/main/java/org/hibernate/query/sqm/spi/SqmCreationHelper.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmAttributeJoin.java
hibernate-core/src/main/java/org/hibernate/spi/EntityIdentifierNavigablePath.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/FetchParent.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityResultImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/StandardEntityGraphTraversalStateImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/cdi/FetchEmbeddedIdTest.java

https://hibernate.atlassian.net/browse/HHH-15875

HHH-15875 Fix join fetch support for associations within embedded ids

---

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmTreePrinter.java

( for the like excape character)

HHH-16151 - Fix potential NullPointerException in SqmTreePrinter

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/association/OneToManyLazyAndEagerTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/OneToManyLazyAndEagerProxyTest.java

https://hibernate.atlassian.net/browse/HHH-16136

HHH-16136 LAZY @ManyToOne may break EAGER @ManyToOne when used on the same entity in a different parent with Bytecode Enhancement

---

hibernate-core/src/main/java/org/hibernate/persister/collection/OneToManyPersister.java
hibernate-core/src/main/java/org/hibernate/sql/model/internal/TableUpdateStandard.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/orphan/onetomany/OneToManyOrphanRemovalBatchTest.java

https://hibernate.atlassian.net/browse/HHH-16112

HHH-16112 Using hibernate.jdbc.batch_size configuration causes BatchedTooManyRowsAffectedException for OneToMany relationship with orphan removal

---

documentation/src/main/asciidoc/userguide/chapters/domain/embeddables.adoc
documentation/src/test/java/org/hibernate/userguide/mapping/embeddable/JsonEmbeddableTest.java
documentation/src/test/java/org/hibernate/userguide/mapping/embeddable/StructEmbeddableTest.java

https://hibernate.atlassian.net/browse/HHH-16143

HHH-16143 Documentation for composite aggregates

---

hibernate-core/src/main/java/org/hibernate/persister/entity/UnionSubclassEntityPersister.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/TreatAbstractSuperclassTest.java

https://hibernate.atlassian.net/browse/HHH-16123

HHH-16123 Invalid generated SQL query when accessing join from a treated abstract superclass path

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/discriminator/associations/NestedOneToOneDiscriminatorTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/discriminator/associations/OneToManyEagerDiscriminatorTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/discriminator/associations/OneToManyJoinFetchDiscriminatorTest.java

Added tests for [HHH-15829](https://hibernate.atlassian.net/browse/HHH-15829), [HHH-16037](https://hibernate.atlassian.net/browse/HHH-16037) and [HHH-16053](https://hibernate.atlassian.net/browse/HHH-16053) which were fixed by https://github.com/hibernate/hibernate-orm/pull/5936.
Added test and possible fix for [HHH-16157](https://hibernate.atlassian.net/browse/HHH-16157).
[HHH-15829]: https://hibernate.atlassian.net/browse/HHH-15829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HHH-16037]: https://hibernate.atlassian.net/browse/HHH-16037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HHH-16053]: https://hibernate.atlassian.net/browse/HHH-16053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …

HHH-16157 Query with join fetch on collection of entities with @DiscriminatorValue causes duplicate condition

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/NamedParameterInSelectAndWhereTest.java

https://hibernate.atlassian.net/browse/HHH-16137

HHH-16137 Same named parameter appearing in SELECT and WHERE clauses throws JDBC parameter value not bound error

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractDomainPath.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/manytomany/ManyToManyOrderByTest.java

https://hibernate.atlassian.net/browse/HHH-16165

HHH-16165 Incorrect SQL generated when using SELECT DISTINCT and @OrderBy

---

hibernate-core/src/main/java/org/hibernate/annotations/UuidGenerator.java
hibernate-core/src/main/java/org/hibernate/boot/registry/selector/internal/StrategySelectorImpl.java
hibernate-core/src/main/java/org/hibernate/boot/registry/selector/package-info.java
hibernate-core/src/main/java/org/hibernate/boot/registry/selector/spi/package-info.java
hibernate-core/src/main/java/org/hibernate/generator/internal/TenantIdGeneration.java
hibernate-core/src/main/java/org/hibernate/mapping/Property.java
hibernate-core/src/main/java/org/hibernate/tuple/entity/CompositeGeneratorBuilder.java
hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java
hibernate-core/src/test/java/org/hibernate/orm/test/tenantid/Record.java
hibernate-core/src/test/java/org/hibernate/orm/test/tenantid/State.java
hibernate-core/src/test/java/org/hibernate/orm/test/tenantid/TenantIdTest.java

and by side-effect allow @TenantId for embeddable properties.

HHH-16133 allow before-execution generators for embeddable properties

---

hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java

on Oracle (first workaround failed on Oracle 11)

HHH-16131 - Correction to workaround for date calculation errors

---

documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc
hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlLexer.g4
hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
hibernate-core/src/main/java/org/hibernate/dialect/DerbyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/SybaseDialect.java
hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
hibernate-core/src/main/java/org/hibernate/query/sqm/TemporalUnit.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java

Let's just see how many dbs this works on.

experimental support for 'extract(epoch from ...)' in HQL

---

hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
hibernate-core/src/test/java/org/hibernate/orm/test/type/EnumUpdateTest.java

https://hibernate.atlassian.net/browse/HHH-16170

HHH-16170 Literal enum values do not work in HQL 'set' clause.

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/notfound/NotFoundAndSelectJoinTest.java

https://hibernate.atlassian.net/browse/HHH-15990

HHH-15990 Unable to determine TableReference when associate ManyToOne fetch lazy and NotFound IGNORE: issue using Projection

---

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/query/NamedQueryTest.java

https://hibernate.atlassian.net/browse/HHH-16109

HHH-16109 createNamedQuery adds offset and limit to all queries

---

hibernate-core/src/main/java/org/hibernate/jpa/spi/NativeQueryTupleTransformer.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/NativeQueryDynamicInstantiationAndTupleResultTest.java

https://hibernate.atlassian.net/browse/HHH-16119

HHH-16119 Named native queries do not work with jakarta.persistence.Tuple result class

---

hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/InsertCoordinator.java

Fix https://hibernate.atlassian.net/browse/HHH-16183

Change scopes of private methods in InsertCoordinator

---

hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java

HHH-16082 - Correction to the epoch extraction for HANA

---

hibernate-core/src/main/java/org/hibernate/engine/spi/CollectionEntry.java

HHH-16169 - Fix potential NullPointerException in CollectionEntry

---

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java
hibernate-core/src/main/java/org/hibernate/cache/internal/CollectionCacheInvalidator.java
hibernate-core/src/test/java/org/hibernate/test/cache/TransactionalConcurrencyCollectionCacheEvictionTest.java

https://hibernate.atlassian.net/browse/HHH-14514

HHH-14514 Fix auto eviction of collection cache

---

hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/InsertCoordinator.java
hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/GeneratedAnnotationBatchTest.java

https://hibernate.atlassian.net/browse/HHH-16155

HHH-16155 Problem with @Generated and jdbc.batch_size

---

settings.gradle

https://hibernate.atlassian.net/browse/HHH-16200

HHH-16200 Upgrade to Narayana 6.0.0.Final and matching jboss-transaction-spi 8.0.0.Final

---

hibernate-core/src/main/java/org/hibernate/internal/ScrollableResultsImpl.java
hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcSelectExecutorStandardImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/spi/ListResultsConsumer.java
hibernate-core/src/test/java/org/hibernate/orm/test/collection/list/IterateOverListInTheSetMethodTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/collection/list/ParentChildMapping.hbm.xml

https://hibernate.atlassian.net/browse/HHH-16184

HHH-16184 Two queries are execute to initialize empty collections   

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/StandardEntityGraphTraversalStateImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/IncludeAllOrNoneGraphTest.java

https://hibernate.atlassian.net/browse/HHH-16175

HHH-16175  AssertionError in StandardEntityGraphTraversalStateImpl.traverse when using entity graph

---

hibernate-core/src/main/java/org/hibernate/tool/schema/internal/AbstractSchemaMigrator.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/GroupedSchemaMigratorImpl.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/IndividuallySchemaMigratorImpl.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaCreatorImpl.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaDropperImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/boot/database/qualfiedTableNaming/DefaultCatalogAndSchemaTest.java

https://hibernate.atlassian.net/browse/HHH-16177
Backported to branch 6.1: see #6119.
Backported to branch 5.6: see #6121.

HHH-16177 Catalog/schema creation/dropping sometimes ignores default catalog/schema

---

hibernate-core/src/main/java/org/hibernate/tool/schema/internal/AbstractSchemaMigrator.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/GroupedSchemaMigratorImpl.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/IndividuallySchemaMigratorImpl.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaCreatorImpl.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaDropperImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/boot/database/qualfiedTableNaming/DefaultCatalogAndSchemaTest.java

https://hibernate.atlassian.net/browse/HHH-16177
Backport of #6118 to branch 6.1.

Backport HHH-16177 to branch 6.1 - Catalog/schema creation/dropping sometimes ignores default catalog/schema

---

hibernate-core/src/main/java/org/hibernate/tool/schema/internal/AbstractSchemaMigrator.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/GroupedSchemaMigratorImpl.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/IndividuallySchemaMigratorImpl.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaCreatorImpl.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaDropperImpl.java
hibernate-core/src/test/java/org/hibernate/test/boot/database/qualifiedTableNaming/DefaultCatalogAndSchemaTest.java

https://hibernate.atlassian.net/browse/HHH-16177
Backport of #6118 to branch 5.6.

Backport HHH-16177 to branch 5.6 - Catalog/schema creation/dropping sometimes ignores default catalog/schema

---

hibernate-core/src/main/java/org/hibernate/internal/util/collections/CaseInsensitiveDictionary.java
hibernate-core/src/main/java/org/hibernate/query/sqm/function/SqmFunctionRegistry.java
hibernate-spatial/src/test/java/org/hibernate/spatial/testing/SpatialSessionFactoryAware.java

https://hibernate.atlassian.net/browse/HHH-16214

HHH-16214 Improve memory and access efficiency in SqmFunctionRegistry

---

hibernate-core/src/main/java/org/hibernate/internal/util/collections/CaseInsensitiveDictionary.java
hibernate-core/src/main/java/org/hibernate/query/sqm/function/SqmFunctionRegistry.java
hibernate-spatial/src/test/java/org/hibernate/spatial/testing/SpatialSessionFactoryAware.java

HHH-16214 Use a more efficient Map implementation in SqmFunctionRegistry

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLPGObjectJdbcType.java
hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java

https://hibernate.atlassian.net/browse/HHH-16221

HHH-16221Improve extensibility of CockroachDB and PostgreSQL dialects

---

hibernate-core/src/main/java/org/hibernate/boot/internal/NamedProcedureCallDefinitionImpl.java
hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java
hibernate-core/src/main/java/org/hibernate/query/results/ResultSetMapping.java
hibernate-core/src/main/java/org/hibernate/query/results/ResultSetMappingImpl.java
hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
hibernate-core/src/main/java/org/hibernate/query/sql/internal/ResultSetMappingProcessor.java
hibernate-core/src/main/java/org/hibernate/service/StandardServiceInitiators.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesMappingProducerProviderInitiator.java
hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesMappingProducerProviderStandard.java
hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/spi/JdbcValuesMappingProducerProvider.java
hibernate-core/src/test/java/org/hibernate/orm/test/intg/reactive/JdbcValuesMappingProducerProviderTests.java

@DavideD - here ya go.  I'll work on a 6.2 PR later

HHH-16226 - Introduce JdbcValuesMappingProducerProvider

---

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/DialectDelegateWrapper.java

https://hibernate.atlassian.net/browse/HHH-16228

HHH-16228 Introduce a Dialect wrapper base class

---

migration-guide.adoc

See https://hibernate.atlassian.net//browse/HHH-7318, https://github.com/hibernate/hibernate-orm/pull/2461, https://github.com/hibernate/hibernate-orm/pull/2461#issuecomment-1440172567

Document BIGINT mapping change

---

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
hibernate-core/src/test/java/org/hibernate/orm/test/fetch/FetchModeSubselectAndOrderByTest.java

https://hibernate.atlassian.net/browse/HHH-16202

HHH-16202 @OrderBy not applied to collections when @Fetch(value = FetchMode.SUBSELECT)

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacySqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/DialectDelegateWrapper.java
hibernate-core/src/main/java/org/hibernate/dialect/MariaDBSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/MySQLSqlAstTranslator.java
hibernate-envers/src/main/java/org/hibernate/envers/enhanced/OrderedSequenceStructure.java
hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/SinglePropertyMapper.java
hibernate-testing/src/main/java/org/hibernate/testing/DialectChecks.java
hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java
hibernate-testing/src/main/java/org/hibernate/testing/transaction/TransactionUtil.java

Another follow-up to make HHH-16228 work better.

HHH-16228 Dialect instance might be wrapped when doing instanceof checks for capabilities

---

hibernate-core/src/main/java/org/hibernate/dialect/SpannerDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/function/SybaseTruncFunction.java
hibernate-core/src/main/java/org/hibernate/query/criteria/HibernateCriteriaBuilder.java
hibernate-core/src/main/java/org/hibernate/query/criteria/spi/HibernateCriteriaBuilderDelegate.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaBuilderNonStandardFunctionsTest.java

https://hibernate.atlassian.net/browse/HHH-16130

HHH-16130 Make date_trunc function accessible via CriteriaApi

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/AbstractBatchEntitySelectFetchInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/caching/CachingWithBatchAndFetchModeSelectTest.java

https://hibernate.atlassian.net/browse/HHH-16230

HHH-16230  Wrong data in self-reference using L2C and BatchSize

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java

Hibernate Reactive needs custom initializers
Fix https://hibernate.atlassian.net/browse/HHH-16242

Change scopes in AbstractEntityInitializer and add getters/setters

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/ClassPropertyHolder.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/embeddables/EmbeddableAndMappedSuperClassWithGenericsTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/embeddables/EmbeddableWithGenericAndMappedSuperClassTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/embeddables/MappedSuperclassGenericEmbeddableQueryParamTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/compositefk/OneToOneEmbeddedIdWithGenericAttributeTest.java

https://hibernate.atlassian.net/browse/HHH-16195

HHH-16195 Hibernate 6 fails to bind appropriate type for mapped superclass with generic attribute

---

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchInitializeEntitySelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/cache/ManyToOneTest.java

https://hibernate.atlassian.net/browse/HHH-16193

HHH-16193 LazyInitializationException when accessing loaded reference after session is closed using bytecode enhancement

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/EscapeConvertedCharArrayTest.java

https://hibernate.atlassian.net/browse/HHH-16211

HHH-16211 Error with like predicate's escape literal and converted char array property

---

documentation/src/main/asciidoc/userguide/chapters/pc/PersistenceContext.adoc
documentation/src/main/asciidoc/userguide/chapters/pc/extras/pc-filter-entity-example.sql
documentation/src/test/java/org/hibernate/userguide/pc/FilterTest.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
hibernate-core/src/test/java/org/hibernate/orm/test/filter/FilterParameterTests.java
hibernate-core/src/test/java/org/hibernate/orm/test/tenantid/TenantIdTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/tenantlongid/TenantLongIdTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/tenantuuid/TenantUuidTest.java

https://hibernate.atlassian.net/browse/HHH-16179

HHH-16179 Session.find should not apply filters

---

hibernate-core/src/main/java/org/hibernate/generator/internal/CurrentTimestampGeneration.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/CreationTimestampTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/UpdateTimestampTest.java

Also, refactor TimestampGenerators out of CurrentTimestampGeneration

HHH-16240 - Add test and fix for issue

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/CaseStatementDiscriminatorMappingImpl.java
hibernate-core/src/main/java/org/hibernate/query/results/DomainResultCreationStateImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/hql/joinedSubclass/JoinedSubclassNativeQueryTest.java

AssertionError when using using native query on table with InheritanceStrategy.JOINED

HHH-16180 - Add test and fix

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/ClassPropertyHolder.java
hibernate-core/src/main/java/org/hibernate/mapping/Property.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/AttributeFactory.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractIdentifiableType.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractManagedType.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/ManagedDomainType.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/SingularPersistentAttribute.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AbstractSqmPathSource.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AnyDiscriminatorSqmPath.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AnyDiscriminatorSqmPathSource.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AnyMappingSqmPathSource.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AttributeContainer.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/BasicSqmPathSource.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/DiscriminatorSqmPathSource.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EmbeddedSqmPathSource.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EntitySqmPathSource.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappedSuperclassSqmPathSource.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/NonAggregatedCompositeSqmPathSource.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/SingularAttributeImpl.java
hibernate-core/src/main/java/org/hibernate/query/criteria/JpaPath.java
hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleSqmAssociationPathSource.java
hibernate-core/src/main/java/org/hibernate/query/sqm/SqmPathSource.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmMappingModelHelper.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmPath.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmSimplePath.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmEmbeddedValuedSimplePath.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmPolymorphicRootDescriptor.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/EmbeddedIdGenericsSuperclassTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/MultipleEmbeddedGenericsTest.java

https://hibernate.atlassian.net/browse/HHH-16188
https://hibernate.atlassian.net/browse/HHH-16238

HHH-16188 HHH-16238 Generic embeddable properties and identifiers

---

hibernate-core/src/main/java/org/hibernate/boot/jaxb/mapping/marshall/CollectionClassificationMarshalling.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/JPAXMLOverriddenMetadataProvider.java
hibernate-core/src/main/java/org/hibernate/internal/util/StringHelper.java
hibernate-core/src/main/resources/org/hibernate/xsd/mapping/mapping-3.1.0.xsd
hibernate-core/src/main/xjb/mapping-bindings.xjb

Work on the JAXB model for mapping.xml

HHH-16115 - Develop an intermediate metamodel binding model

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacySqlAstTranslator.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacySqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/OracleSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/SQLServerSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/SybaseASESqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/internal/util/collections/Stack.java
hibernate-core/src/main/java/org/hibernate/internal/util/collections/StandardStack.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/HqlUnionTest.java

https://hibernate.atlassian.net/browse/HHH-15766

HHH-15766 UNION query doesn't preserve the original parenthesis

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/caching/CachingAndVersionTest.java

https://hibernate.atlassian.net/browse/HHH-16126

HHH-16126 TransientObjectException when loading versioned entity from second-level cache

---

hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstWalker.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/subselect/SubselectOneToManyTest.java

https://hibernate.atlassian.net/browse/HHH-16213

HHH-16213 Right join wrongly added to subquery when using FetchMode.SUBSELECT and is null predicate

---

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderSubSelectFetch.java
hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/discriminator/OneToManySubSelectFetchAndInheritanceTest.java

https://hibernate.atlassian.net/browse/HHH-16258

HHH-16258 NPE with SubselectFetch and inheritance

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java
hibernate-core/src/test/java/org/hibernate/orm/test/cuk/JoinColumnOccursOutOfOrderTest.java

use a `LinkedHashSet` so that things are more deterministic
this is perhaps not a "complete" fix, but it will have to do for now

HHH-16263 fix for nondeterminism

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableFetchImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractNonLazyEntityFetch.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedResultImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchSelectImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/domain/CircularFetchImpl.java

Basically, it creates some protected methods or changes some existing ones so that Hibernate Reactive can instantiate its own classes 
Fix https://hibernate.atlassian.net/browse/HHH-16282

Make it possible for Hibernate Reactive to plug in custom fetch initializers

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/orderby/OrderByTest.java

https://hibernate.atlassian.net/browse/HHH-15885

HHH-15885 Fix wrong collection fetch element ordering

---

documentation/src/main/asciidoc/userguide/chapters/domain/collections.adoc
documentation/src/main/asciidoc/userguide/chapters/domain/extras/collections/collections-array-as-basic-example.sql
documentation/src/main/asciidoc/userguide/chapters/domain/extras/collections/collections-array-binary-example.sql
documentation/src/test/java/org/hibernate/userguide/collections/CollectionTest.java

https://hibernate.atlassian.net/browse/HHH-15664

HHH-15664 Fix array section in documentation

---

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/PluralAttributeMappingImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/onetomany/NestedOneToManyFetchTest.java

https://hibernate.atlassian.net/browse/HHH-16210

HHH-16210 Join fetching nested @OneToMany collections causes result multiplication

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/loading/EntityLoadingLoggingTest.java
hibernate-core/src/test/resources/log4j2.properties

https://hibernate.atlassian.net/browse/HHH-16234

HHH-16234  NPE when enabling DEBUG on orm.results.loading in Hibernate 6.1.7

---

hibernate-core/src/main/java/org/hibernate/action/internal/EntityUpdateAction.java
hibernate-core/src/test/java/org/hibernate/test/cache/CacheModeGetUpdateTest.java

https://hibernate.atlassian.net/browse/HHH-13627

HHH-13627 Updated items do not get invalidated when cachemode is set to CacheMode.GET

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/H2FormatJsonJdbcType.java
hibernate-core/src/test/java/org/hibernate/orm/test/type/H2JsonListTest.java

https://hibernate.atlassian.net/browse/HHH-16320

HHH-16320 Support H2's native json DDL type using custom 'format json' write expressions

---

hibernate-core/src/test/java/org/hibernate/orm/test/ops/MergeTest.java
settings.gradle

- https://hibernate.atlassian.net/browse/HHH-16325
- https://hibernate.atlassian.net/browse/HHH-16326
- https://hibernate.atlassian.net/browse/HHH-16327
- https://hibernate.atlassian.net/browse/HHH-16328
- https://hibernate.atlassian.net/browse/HHH-16329
- https://hibernate.atlassian.net/browse/HHH-16330

Some micro components upgrades

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SelectableMappingImpl.java
hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
hibernate-core/src/test/java/org/hibernate/orm/test/collection/ElementCollectionUpdateTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/collection/OneToManyUpdateTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/EmbeddableAsElementCollectionUpdateTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/EmbeddableWithNotOprionalAttributeAsElementCollectionUpdateTest.java

https://hibernate.atlassian.net/browse/HHH-16297

HHH-16297 Removing an element from a collection of elements removes the whole collection

---

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/ObjectParameterTypeForEmbeddableTest.java

https://hibernate.atlassian.net/browse/HHH-16247

HHH-16247 Criteria Query with Object-Typed Embedded Parameter throws AssertionError

---

migration-guide.adoc

https://hibernate.atlassian.net/browse/HHH-16246
I *think* that's the gist of it, but @gavinking will know for sure.

HHH-16246 Document multitenancy changes

---

hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/version/InheritanceImplicitVersionUpdateTest.java

https://hibernate.atlassian.net/browse/HHH-16237

HHH-16237 versionUpdateGroup is null for Enity extending another Entity when only ElementCollection is updated

---

hibernate-core/src/main/java/org/hibernate/dialect/temptable/TemporaryTable.java
hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractEmbeddableMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddableMappingTypeImpl.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/Initializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/joined/JoinedInheritanceSameAttributeNameTest.java

https://hibernate.atlassian.net/browse/HHH-16166

HHH-16166 ClassCastException, mixing mapping types for same field name on different entities

---

settings.gradle

- https://hibernate.atlassian.net/browse/HHH-16331

HHH-16331 Upgrade to Mockito 5.2

---

hibernate-core/src/test/java/org/hibernate/orm/test/type/H2JsonListTest.java

Backport of https://github.com/hibernate/hibernate-orm/pull/6272.

Fix test failing on older H2 versions

---

hibernate-core/src/main/java/org/hibernate/metamodel/internal/ManagedTypeRepresentationResolverStandard.java
hibernate-core/src/main/java/org/hibernate/type/ComponentType.java
hibernate-core/src/main/java/org/hibernate/type/TypeHelper.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/strategy/usertype/embedded/merge/Child.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/strategy/usertype/embedded/merge/MergeTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/strategy/usertype/embedded/merge/MyCompositeValue.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/strategy/usertype/embedded/merge/MyCompositeValueType.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/strategy/usertype/embedded/merge/Parent.java

https://hibernate.atlassian.net/browse/HHH-16015

HHH-16015 Merge operation throws a NPE: Cannot invoke org.hibernate.property.access.spi.Setter.set(Object, Object) when using CompositeUserType

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/OneToOneSecondPass.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mappedBy/ManyToManyMappedByTypeTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mappedBy/OneToManyMappedByTypeTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mappedBy/OneToOneMappedByTypeTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/polymorphic/PolymorphicAssociationTest2.java

https://hibernate.atlassian.net/browse/HHH-16313

HHH-16313 Throw an appropriate error when a mappedBy property references the wrong entity type

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/OneToOneSecondPass.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mappedBy/ManyToManyMappedByTypeTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mappedBy/OneToManyMappedByTypeTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mappedBy/OneToOneMappedByTypeTest.java

Backport of https://github.com/hibernate/hibernate-orm/pull/6278.

HHH-16336 Modify the newly introduced mappedBy type check to be more lenient

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mappedBy/OneToManyMapEntityKeyMappedByTest.java

https://hibernate.atlassian.net/browse/HHH-16355

HHH-16355 Map association with entity typed key breaks if mappedBy is specified

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/AbstractBatchEntitySelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntityInsideEmbeddableSelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntitySelectFetchInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/InheritanceManyToOneBatchingTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/InheritanceManyToOneEmbeddedBatchingTest.java

https://hibernate.atlassian.net/browse/HHH-16248

HHH-16248 Problem with batching and inheritance with @ManyToOne mapped in multiple subclasses

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractAttributeMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractEntityCollectionPart.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractSingularAttributeMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractStateArrayContributorMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/OneToManyCollectionPart.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/PluralAttributeMappingImpl.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/TableBasedInsertHandler.java
hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/UpdateExecutionDelegate.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableFetchImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchJoinedImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchSelectImpl.java

Same as https://github.com/hibernate/hibernate-orm/pull/6287
but for main.
I want to check that there are no error on CI

HHH-16353 For main

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractAttributeMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractEntityCollectionPart.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractSingularAttributeMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractStateArrayContributorMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/OneToManyCollectionPart.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/PluralAttributeMappingImpl.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/TableBasedInsertHandler.java
hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/UpdateExecutionDelegate.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableFetchImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchJoinedImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchSelectImpl.java

Fix https://hibernate.atlassian.net/browse/HHH-16353

HHH-16353 Make it possible to plug in custom reactive classes

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/TableBinder.java
hibernate-core/src/test/java/org/hibernate/orm/test/compositefk/OneToManyIdClassFKTest.java

https://hibernate.atlassian.net/browse/HHH-16274

HHH-16274 Incorrect foreign key column order for @OneToMany with multiple join columns and @IdClass

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityResultInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/notfound/OptionalEagerMappedByNotFoundTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/onetomany/RefreshWithPropertyAccessAndCollectionMapManipulationInSetterMethodTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/onetomany/RefreshWithPropertyAccessAndListManipulationInSetterMethodTest.java

https://hibernate.atlassian.net/browse/HHH-16272

HHH-16272 Hibernate 6 fails to refresh when collections are accessed in entity setter method when access type is property

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/BasicValuedMapping.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/IdClassEmbeddable.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/TupleMappingModelExpressible.java
hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleBasicValuedModelPart.java
hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/JdbcLiteral.java
hibernate-core/src/main/java/org/hibernate/sql/exec/internal/AbstractJdbcParameter.java
hibernate-core/src/main/java/org/hibernate/type/CustomType.java
hibernate-core/src/test/java/org/hibernate/orm/test/cache/QueryCacheWithObjectParameterTest.java

https://hibernate.atlassian.net/browse/HHH-16281

HHH-16281 Inconsistent Behaivor of L2 cache between Hibernate 5 and 6

---

hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/ArgumentTypesValidator.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/NamedParameterInSelectAndWhereTest.java

https://hibernate.atlassian.net/browse/HHH-16305

HHH-16305 Error when using parameter as both a select function argument and in where clause

---

hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java

Same as https://github.com/hibernate/hibernate-orm/pull/6323 but for the main branch
Fix HHH-16399

 Recognize ConstraintViolationException from error code in Sql Server #6323 

---

hibernate-core/src/main/java/org/hibernate/metamodel/internal/AttributeFactory.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractIdentifiableType.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractManagedType.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/ManagedDomainType.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AbstractPluralAttribute.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AnyMappingSqmPathSource.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AttributeContainer.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/BasicSqmPathSource.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EntitySqmPathSource.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/ListAttributeImpl.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MapAttributeImpl.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/PluralAttributeBuilder.java
hibernate-core/src/main/java/org/hibernate/query/criteria/JpaPath.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmMappingModelHelper.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmPath.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCteRoot.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmDerivedRoot.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmEmbeddedValuedSimplePath.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmPolymorphicRootDescriptor.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/GenericAssociationTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/GenericBasicValuedPathTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/GenericMapAssociationTest.java

https://hibernate.atlassian.net/browse/HHH-16378
This change includes *concrete* type resolution for both associations (that fixes the issue) and basic-valued paths.

HHH-16378 SQM fails to resolve target type of association defined in mappersuperclass with generics

---

hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmWindow.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/Over.java

https://hibernate.atlassian.net/browse/HHH-16402

HHH-16402 Fix default window frame mode to be RANGE instead of ROWS

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/loading/PreLoadEventTest.java

https://hibernate.atlassian.net/browse/HHH-16350

HHH-16350 PreLoadEvent listeners always receive PreLoadEvent with null state

---

hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java
hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/InferredBasicValueResolver.java
hibernate-core/src/main/java/org/hibernate/boot/model/process/spi/MetadataBuildingProcess.java
hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingMetadataBuildingOptions.java
hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataBuildingOptions.java
hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java
hibernate-core/src/main/java/org/hibernate/mapping/Property.java
hibernate-core/src/main/java/org/hibernate/type/BasicTypeRegistry.java
hibernate-core/src/main/java/org/hibernate/type/WrapperArrayHandling.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/AbstractArrayJavaType.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ArrayJavaType.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/BasicPluralJavaType.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/BasicCollectionJavaType.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/dataTypes/BasicOperationsTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/lob/ImageTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/ByteArrayMappingTests.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/CharacterArrayMappingTests.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/CharacterArrayNationalizedMappingTests.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/WrapperArrayHandlingDisallowTests.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/WrapperArrayHandlingLegacyTests.java
migration-guide.adoc

https://hibernate.atlassian.net/browse/HHH-16388

HHH-16388 - Configuration setting for wrapper Byte[]/Character[] treatment

---

hibernate-core/src/main/java/org/hibernate/metamodel/internal/AttributeFactory.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractIdentifiableType.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AnyMappingSqmPathSource.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/BasicSqmPathSource.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/SingularAttributeImpl.java
hibernate-core/src/main/java/org/hibernate/query/sqm/SqmExpressible.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmMappingModelHelper.java
hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/ArgumentTypesValidator.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/YearMonthConverterTest.java

https://hibernate.atlassian.net/browse/HHH-16241

HHH-16241 Unable to write/query attribute on type with AttributeConverter

---

hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java
hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java
hibernate-core/src/test/java/org/hibernate/orm/test/pagination/PaginationTest.java

Included check for that in PaginationTest
Moved PaginationTest to Junit5

HHH-16384 - Fix NPE in AbstractSelectionQuery.setFirstResult

---

hibernate-core/src/main/java/org/hibernate/property/access/spi/GetterMethodImpl.java
hibernate-core/src/main/java/org/hibernate/property/access/spi/SetterMethodImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/DirtyCheckingWithEmbeddableAndMappedSuperclassTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/DirtyCheckingWithEmbeddedOnGetterTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/DirtyCheckingWithEmbeddedTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/DirtyCheckingWithMappedsuperclassTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/property/access/spi/GetterMethodImplTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/property/access/spi/SetterMethodImplTest.java
settings.gradle

https://hibernate.atlassian.net/browse/HHH-16403

HHH-16403 Avoid unnecessary wrapping for exceptions/errors thrown by getters/setters

---

hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/discriminator/DiscriminatorInEmbeddedIdTest.java

https://hibernate.atlassian.net/browse/HHH-16340

HHH-16340 Duplicate column exception when mapping discriminator column inside an EmbeddedId

---

build.gradle
checkerstubs/jakarta.persistence.astub
gradle/java-module.gradle
hibernate-core/src/main/java/org/hibernate/internal/util/NullnessUtil.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/ClassWriter.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/Context.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/JPAMetaModelEntityProcessor.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/Version.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/MetaAttributeGenerationVisitor.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/AccessTypeInformation.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/FileTimeStampChecker.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/NullnessUtil.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/TypeRenderingVisitor.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/TypeUtils.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/xml/JpaNamespaceTransformingEventReader.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/xml/XmlParserHelper.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/xml/JpaDescriptorParser.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/xml/XmlMetaEntity.java

https://hibernate.atlassian.net/browse/HHH-16389

HHH-16389 Introduce checkerframework for nullness marking/checking and null check the JPA metamodel generator

---

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/SimpleDatabaseVersion.java
hibernate-core/src/test/java/org/hibernate/orm/test/dialect/HANADialectTestCase.java

HHH-16444 When logging the selected dialect, log the db version too

---

hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java
hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java

in AbstractSelectionQuery and AbstractQuery

Remove some unnecessary code duplications

---

hibernate-core/src/test/java/org/hibernate/orm/test/timezones/UTCNormalizedInstantTest.java

let's see if this fails on any db

add a test for round-tripping Instant

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java

https://hibernate.atlassian.net/browse/HHH-16429

HHH-16429 WF SessionFactoryTestCase test fails

---

hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/dialect/internal/DialectFactoryImpl.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java
hibernate-core/src/main/java/org/hibernate/internal/log/DeprecationLogger.java

proper logging and documentation for semi-deprecation of 'hibernate.dialect'

---

hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcServicesImpl.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/SqlStatementLoggerInitiator.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/SqlStatementLogger.java
hibernate-core/src/main/java/org/hibernate/service/StandardServiceInitiators.java

Same as https://github.com/hibernate/hibernate-orm/pull/6364 but for `main`

HHH-16443 Convert SqlStatementLogger into a Service

---

hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java

HHH-16450 cast(integer as Duration) and cast(datetime as Instant)

---

hibernate-core/src/main/java/org/hibernate/engine/jdbc/dialect/spi/DatabaseMetaDataDialectResolutionInfoAdapter.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java
hibernate-core/src/test/java/org/hibernate/orm/test/dialect/resolver/TestingDialectResolutionInfo.java

add toString()s to DialectResolutionInfo

---

hibernate-core/src/main/java/org/hibernate/annotations/Where.java
hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/HighlightingFormatter.java

fix some slightly misleading javadoc about the @Where annotation

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/idclass/IdClassQueryTest.java

https://hibernate.atlassian.net/browse/HHH-16387

HHH-16387 Entity in key not returned when querying

---

hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/BatchImpl.java
hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchUpdateAndVersionTest.java

https://hibernate.atlassian.net/browse/HHH-16394

HHH-16394 Statement Batch + Version + Dirty Collection leads to OptimisticLockException: Batch update returned unexpected row count from update

---

settings.gradle

https://hibernate.atlassian.net/browse/HHH-16460

HHH-16460 Upgrade to Jandex 3.1.0

---

documentation/src/main/asciidoc/userguide/appendices/Annotations.adoc

also @EmbeddableInstantiatorRegistration and @EmbeddableInstantiatorRegistrations

Add @EmbeddableInstantiator et al. to the annotations chapter of the user guide

---

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/PersistentAttributeTransformer.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/GenericToManyAssociationTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/GenericToOneAssociationTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/DirtyTrackingInheritanceTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/DirtyTrackingInheritanceWithGenericsTest.java
hibernate-testing/src/main/java/org/hibernate/testing/bytecode/enhancement/EnhancerTestUtils.java

https://hibernate.atlassian.net/browse/HHH-16459

HHH-16459 Bytecode-enhanced inline dirty tracking ignores generic associations from mapped superclasses

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java
hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/InheritanceQueryGroupByTest.java

https://hibernate.atlassian.net/browse/HHH-16349

HHH-16349 ORA-00979 not a group by expression when using a polymorphic entity in HQL group by

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/join/JoinWithSingleTableInheritanceTest.java

Left outer joins do not work with single table polymorphic entities because of the discriminator in the where clause

HHH-16438 - Add test for issue

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/join/JoinWithSingleTableInheritanceTest.java

because of the discriminator in the where clause
HHH-16438 - fix for issue
- move the discriminator condition from the where clause to the join clause
- add another test to JoinWithSingleTableInheritanceTest
HHH-16438 - Apply some suggestions from Christian's code review

HHH-16438 - Add test and for issue where left outer joins do not work with single table polymorphic entities

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractEntityCollectionPart.java
hibernate-core/src/test/java/org/hibernate/orm/test/cache/CacheOneToManyAndIdClassTest.java

https://hibernate.atlassian.net/browse/HHH-16493

HHH-16493 OneToManyCollectionPart doesn't disassemble properly embeddable IdClass

---

hibernate-core/src/main/java/org/hibernate/mapping/Component.java
hibernate-core/src/test/java17/org/hibernate/orm/test/records/EmbeddableInstantiatorTest.java

https://hibernate.atlassian.net/browse/HHH-16457

HHH-16457 Values returned in ValueAccess.getValues() and getValue(…) not alphabetical for Java records

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/association/OneToManyLazyAndEagerTest2.java

https://hibernate.atlassian.net/browse/HHH-16477

HHH-16477  LAZY @ManyToOne may again break EAGER @ManyToOne when used on the same entity in a different parent with Bytecode Enhancement

---

hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java
hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingsImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/cache/QueryCacheAndOneToManyTest.java

https://hibernate.atlassian.net/browse/HHH-16471

HHH-16471 Entities serialized in QueryKey causes java.lang.ClassCastException

---

hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/WindowFunctionTest.java

https://hibernate.atlassian.net/browse/HHH-16347

HHH-16347 The ORDER BY clause in a Window Function doesn't work when using multiple columns

---

hibernate-core/src/main/java/org/hibernate/boot/model/TypeDefinition.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/enumerated/EnumeratedAndGenerics2Test.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/enumerated/EnumeratedAndGenerics3Test.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/enumerated/EnumeratedAndGenericsTest.java

https://hibernate.atlassian.net/browse/HHH-16479

HHH-16479 Generic enum in @MappedSuperclass fails with java.lang.IllegalArgumentException: Named type  [...] did not implement BasicType nor UserType

---

hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingCircularDependencyFalsePositiveTest.java
hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingRCATest.java
hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingRootEntityNameDependencyTest.java

https://hibernate.atlassian.net/browse/HHH-16485

HHH-16485 Insert ordering doesn't consider root entity names

---

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/BiDirectionalAssociationHandler.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/CodeTemplates.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/association/ManyToManyAssociationListTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/association/OneToOneAssociationTest.java

https://hibernate.atlassian.net/browse/HHH-15602

HHH-15602 Fix bidirectional association management code

---

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/CodeTemplates.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/javassist/PersistentAttributesEnhancer.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/javassist/PersistentAttributesHelper.java

https://hibernate.atlassian.net/browse/HHH-15602

HHH-15602 Javassist implementation of proper bidirectional handling

---

hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/DeferredResultSetAccess.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/QuerySqlExceptionTest.java
hibernate-testing/src/main/java/org/hibernate/testing/orm/jdbc/PreparedStatementSpyConnectionProvider.java

https://hibernate.atlassian.net/browse/HHH-16458
Backport of #6394 to branch 6.2.

Backport HHH-16458 to branch 6.2 - JDBC statement is not closed when DeferredResultSetAccess fails to execute a query

---

hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/DeferredResultSetAccess.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/QuerySqlExceptionTest.java
hibernate-testing/src/main/java/org/hibernate/testing/orm/jdbc/PreparedStatementSpyConnectionProvider.java

https://hibernate.atlassian.net/browse/HHH-16458
Backported to branch 6.2 as #6396.

HHH-16458 JDBC statement is not closed when DeferredResultSetAccess fails to execute a query

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetoone/OneToOneTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/InetAddressMappingTests.java

Some follow up fixes that the TCK revealed

HHH-16382 Make sure joins are adapted to inner if non-FK parts of a path are de-referenced

---

hibernate-core/src/test/java/org/hibernate/orm/test/mapping/manytoone/ManyToOneEmbeddedIdSelfReferenceJoinFetchTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/onetoone/OneToOneEmbeddedIdSelfReferenceTest.java

https://hibernate.atlassian.net/browse/HHH-16363
https://hibernate.atlassian.net/browse/HHH-16473

HHH-16363 OneToMany object properties not set when EmbeddedId and it holds an OneToOne relationship to itself

---

gradle/java-module.gradle
hibernate-core/src/main/java/org/hibernate/internal/util/StringHelper.java
hibernate-core/src/main/java/org/hibernate/spi/DotIdentifierSequence.java
hibernate-core/src/main/java/org/hibernate/spi/NavigablePath.java
hibernate-core/src/main/java/org/hibernate/spi/TreatedNavigablePath.java

Correction to gradle/java-module.gradle for the checkerframework
Co-authored-by: Christian Beikov <christian.beikov@gmail.com>
Add @Nullable annotations to org.hibernate.spi

HHH-16515 - Add @Nullable annotations to org.hibernate.spi

---

hibernate-core/src/main/java/org/hibernate/dialect/SybaseDialect.java

https://hibernate.atlassian.net/browse/HHH-16304

HHH-16304 Default unquotedCaseStrategy to MIXED with Sybase

---

documentation/src/main/asciidoc/userguide/appendices/Annotations.adoc
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacySqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/annotations/SQLRestriction.java
hibernate-core/src/main/java/org/hibernate/annotations/Where.java
hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/DmlTargetColumnQualifierSupport.java
hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/OracleSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SimpleDeleteQueryPlan.java
hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/SqmMutationStrategyHelper.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/mutationquery/MutationQueriesFilterTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/mutationquery/MutationQueriesWhereAndFilterTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/mutationquery/MutationQueriesWhereTest.java

https://hibernate.atlassian.net/browse/HHH-16392

HHH-16392 @Where annotation generates bad query with entity name instead of alias in association subquery

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/EntityValuedPathInSubqueryTest.java

https://hibernate.atlassian.net/browse/HHH-16397

HHH-16397 Wrong SQL when HQL has subquery using FK attribute of parent query root

---

gradle/databases.gradle
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseLegacyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/SybaseDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/SybaseDriverKind.java
hibernate-core/src/main/java/org/hibernate/procedure/internal/SybaseCallableStatementSupport.java
hibernate-core/src/test/java/org/hibernate/orm/test/procedure/SybaseStoredProcedureTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/CommentGenerationTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/tool/schema/scripts/StatementsWithoutTerminalCharsImportFileTest.java
hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java

https://hibernate.atlassian.net/browse/HHH-15833
https://hibernate.atlassian.net/browse/HHH-16528

HHH-15833 Disable named parameters for jConnect JDBC driver

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseLegacyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/SybaseDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/function/SybaseTruncFunction.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/dataTypes/BasicOperationsTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/version/db/DbVersionTest.java

https://hibernate.atlassian.net/browse/HHH-16533

HHH-16533 Fix issues with jConnect driver related to temporal literals

---

Jenkinsfile
docker_db.sh
edb/edb15.Dockerfile
nightly.Jenkinsfile

https://hibernate.atlassian.net/browse/HHH-15871

HHH-15871 Update EDB testing to version 15

---

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/cte/SqmCteStatement.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/CriteriaRecursiveCteCopyTest.java

https://hibernate.atlassian.net/browse/HHH-16483

HHH-16483 Recursive CTE using Criteria API will throw `Already registered a copy: org.hibernate.query.sqm.tree.cte.SqmCteStatement` error

---

hibernate-core/src/main/java/org/hibernate/jpa/internal/util/PersistenceUtilHelper.java

https://hibernate.atlassian.net/browse/HHH-16545

HHH-16545 PersistenceUtil.MetadataCache needs to be threadsafe

---

hibernate-core/src/main/java/org/hibernate/dialect/OracleArrayJdbcType.java
hibernate-core/src/main/java/org/hibernate/dialect/OracleNestedTableJdbcType.java
hibernate-core/src/test/java/org/hibernate/orm/test/type/OracleSqlArrayTest.java

fix the tests for Oracle nested tables / arrays

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntitySelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesSourceProcessingStateStandardImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/DepthOneBatchTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/DepthOneTest.java

https://hibernate.atlassian.net/browse/HHH-16469

HHH-16469 Hibernate repeatedly issues identical SELECT queries to load an optional one-to-one association 

---

hibernate-core/src/main/java/org/hibernate/type/EntityType.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/merge/MergeWithReferenceTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/merge/MergeWithReferenceTest.java

https://hibernate.atlassian.net/browse/HHH-16298

HHH-16298 Failure merging a referenced entity 

---

hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java

https://hibernate.atlassian.net/browse/HHH-16546
Backported to branch 6.2 as #6499

HHH-16546 Reduce verbosity of logs in a few edge cases

---

hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java

https://hibernate.atlassian.net/browse/HHH-16546
Backport of #6498 to branch 6.2.

Backport HHH-16546 to branch 6.2 - Reduce verbosity of logs in a few edge cases

---

hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/StandardFunctionReturnTypeResolvers.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionsWithAnonymousTupleTest.java

https://hibernate.atlassian.net/browse/HHH-16425
Alternative to https://github.com/hibernate/hibernate-orm/pull/6375 with rewritten tests and a similar solution.

HHH-16425 Function type resolver doesn't work with anonymous tuple path sources

---

gradle/java-module.gradle
hibernate-core/src/main/java/org/hibernate/action/spi/Executable.java
hibernate-core/src/main/java/org/hibernate/bytecode/internal/BytecodeEnhancementMetadataNonPojoImpl.java
hibernate-core/src/main/java/org/hibernate/bytecode/internal/BytecodeEnhancementMetadataPojoImpl.java
hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java
hibernate-core/src/main/java/org/hibernate/bytecode/internal/none/BytecodeProviderImpl.java
hibernate-core/src/main/java/org/hibernate/bytecode/spi/BytecodeEnhancementMetadata.java
hibernate-core/src/main/java/org/hibernate/bytecode/spi/BytecodeProvider.java
hibernate-core/src/main/java/org/hibernate/bytecode/spi/ClassTransformer.java

HHH-16515 - Add @nullable annotations to org.hibernate.action.spi
HHH-16515 - Add the org.hibernate.context.spi package to nullness checking
HHH-16515 - Add the org.hibernate.bytecode.spi package to nullness checking

Nullabillity work

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedDiscriminatorColumn.java
hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/CreateCharDiscriminatorTest.java

Test case and patch for jira issue [HHH-16551](https://hibernate.atlassian.net/browse/HHH-16551)
[HHH-16551]: https://hibernate.atlassian.net/browse/HHH-16551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HHH-16551- discriminator column of type CHAR should be of length 1

---

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionBatchLoaderArrayParam.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/EntityBatchLoaderArrayParam.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/EntityBatchLoaderInPredicate.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderHelper.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderArrayParam.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoaderArrayParam.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdArrayLoadPlan.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdExecutionContext.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdLoadPlan.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/sql/exec/spi/ExecutionContext.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/NestedRowProcessingState.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityJoinedFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityResultInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/RowProcessingStateStandardImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/bag/BagAndSetFetchTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/bag/EagerBagsTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/refresh/RefreshAndInheritanceTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/refresh/RefreshTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/collection/bag/BagAndSetFetchTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/collection/bag/EagerBagsTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/onetomany/NestedOneToManySetFetchTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/refresh/JPARefreshTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/refresh/RefreshTest.java

- https://hibernate.atlassian.net/browse/HHH-16423 LazyInitializationException when calling em.refresh() on entity with lazy and eager children
- https://hibernate.atlassian.net/browse/HHH-16447 Lazy load of collection fails after EntityManager.refresh
- https://hibernate.atlassian.net/browse/HHH-16453 Loading an Entity with two eager collections, produces duplicates when one of the collection is a a bag
- https://hibernate.atlassian.net/browse/HHH-16496 Join fetching nested @OneToMany collections causes result multiplication

HHH-16423 + HHH-16447 + HHH-16453 + HHH-16496

---

hibernate-core/src/main/java/org/hibernate/tool/schema/internal/ColumnDefinitions.java
hibernate-core/src/test/java/org/hibernate/orm/test/schemavalidation/MySqlExistingEnumColumnValidationTest.java

See issue [HHH-16498](https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues/HHH-16498)
[Fixed version of [PR 6462](https://github.com/hibernate/hibernate-orm/pull/6462)]
[HHH-16498]: https://hibernate.atlassian.net/browse/HHH-16498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HHH-16498 Hibernate DDL validation fails on enum database column type

---

hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/internal/PreparedStatementGroupStandard.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchUpdateAndJoinedInheritanceTest.java

https://hibernate.atlassian.net/browse/HHH-16517

HHH-16517 H6: Problems with flush when batch is ON (without @DynamicUpdate)

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/LeftJoinNullnessPredicateQueryTest.java

https://hibernate.atlassian.net/browse/HHH-16505

HHH-16505 Interpretation of "bare" left-join alias reference in HQL

---

hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java

https://hibernate.atlassian.net/browse/HHH-16576

HHH-16576 Problem in query involving union on MariaDB and Oracle

---

hibernate-core/src/main/java/org/hibernate/dialect/function/SQLFunctionRegistry.java
hibernate-core/src/test/java/org/hibernate/sql/TemplateTest.java

https://hibernate.atlassian.net/browse/HHH-16609

HHH-16609 SQLFunctionRegistry#findSQLFunction needs to guard against null argument

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/TreatedLeftJoinInheritanceTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/TreatedLeftPluralJoinInheritanceTest.java

https://hibernate.atlassian.net/browse/HHH-16472

HHH-16472 Treated left join with restriction on entity results in incorrect query

---

hibernate-core/src/main/java/org/hibernate/engine/spi/SubselectFetch.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/FromClause.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchSubselectCollection2Test.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchSubselectCollectionTest.java

https://hibernate.atlassian.net/browse/HHH-16569

HHH-16569 Batch fetch leads to some collections to be wrongly initialized with empty due to wrong generated SQL

---

hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/quarkus/MetadataCopyingTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/quarkus/package-info.java

https://hibernate.atlassian.net/browse/HHH-16625

HHH-16625 Restore Quarkus compatibility

---

hibernate-core/src/main/java/org/hibernate/dialect/DialectLogging.java
hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java
hibernate-core/src/main/java/org/hibernate/persister/collection/OneToManyPersister.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/DeleteRowsCoordinatorStandard.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/DeleteRowsCoordinatorTablePerSubclass.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/InsertRowsCoordinatorStandard.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/InsertRowsCoordinatorTablePerSubclass.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/RemoveCoordinatorStandard.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/RemoveCoordinatorTablePerSubclass.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/UpdateRowsCoordinatorOneToMany.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/UpdateRowsCoordinatorStandard.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/UpdateRowsCoordinatorTablePerSubclass.java
hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
hibernate-core/src/test/java/org/hibernate/orm/test/quarkus/MetadataCopyingTest.java

- https://hibernate.atlassian.net/browse/HHH-16625
- https://hibernate.atlassian.net/browse/HHH-16630
- https://hibernate.atlassian.net/browse/HHH-16631

Scalability fixes, Quarkus verbosity reduction / 6.2

---

hibernate-core/src/main/java/org/hibernate/dialect/DialectLogging.java
hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java
hibernate-core/src/main/java/org/hibernate/persister/collection/OneToManyPersister.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/DeleteRowsCoordinatorStandard.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/DeleteRowsCoordinatorTablePerSubclass.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/InsertRowsCoordinatorStandard.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/InsertRowsCoordinatorTablePerSubclass.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/RemoveCoordinatorStandard.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/RemoveCoordinatorTablePerSubclass.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/UpdateRowsCoordinatorOneToMany.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/UpdateRowsCoordinatorStandard.java
hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/UpdateRowsCoordinatorTablePerSubclass.java
hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
hibernate-core/src/test/java/org/hibernate/orm/test/quarkus/MetadataCopyingTest.java

- https://hibernate.atlassian.net/browse/HHH-16625
- https://hibernate.atlassian.net/browse/HHH-16630
- https://hibernate.atlassian.net/browse/HHH-16631

Scalability fixes, Quarkus verbosity reduction

---

hibernate-core/src/main/java/org/hibernate/SessionFactory.java
hibernate-core/src/main/java/org/hibernate/TransactionManagementException.java
hibernate-core/src/main/java/org/hibernate/internal/TransactionManagement.java

also clean up the related code

HHH-16637 add methods to SessionFactory for handling lifecycle of StatelessSession

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacySqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/OracleSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/sql/ast/Clause.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/FromClause.java
hibernate-core/src/test/java/org/hibernate/orm/test/dialect/functional/OracleFollowOnLockingTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/pagination/OraclePaginationWithLocksTest.java

https://hibernate.atlassian.net/browse/HHH-16433

HHH-16433 Fix forced follow on locking with order by

---

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchAndBagCollectionTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/SetAndBagCollectionTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/collection/SetAndBagCollectionTest.java

https://hibernate.atlassian.net/browse/HHH-16570

HHH-16570 Batch fetch with FetchMode JOIN might lead to multiplication in OneToMany items

---

documentation/src/main/asciidoc/introduction/Advanced.adoc
hibernate-core/src/main/java/org/hibernate/annotations/DialectOverride.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
hibernate-core/src/test/java/org/hibernate/orm/test/customsql/CustomSqlOverrideTest.java

Been meaning to do this for a while.

 HHH-16638 allow @DialectOverride for @SQLInsert and friends

---

hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/instantiation/internal/DynamicInstantiationAssemblerConstructorImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/instantiation/internal/DynamicInstantiationAssemblerInjectionImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/instantiation/internal/DynamicInstantiationResultImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java

See https://hibernate.atlassian.net/browse/HHH-16647

HHH-16647 allow unqualified use of query result type in HQL instantiation

---

documentation/src/main/asciidoc/introduction/Advanced.adoc
documentation/src/main/asciidoc/introduction/Tuning.adoc
hibernate-core/src/main/java/org/hibernate/annotations/Fetch.java
hibernate-core/src/main/java/org/hibernate/annotations/FetchProfile.java
hibernate-core/src/main/java/org/hibernate/annotations/Fetches.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotationBinder.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/FetchOverrideSecondPass.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/FetchSecondPass.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/ToOneBinder.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/fetchprofile/Customer.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/fetchprofile/Customer2.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/fetchprofile/Customer3.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/fetchprofile/Customer5.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/fetchprofile/Customer6.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/fetchprofile/NewFetchTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/fetchprofile/mappedby/package-info.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/fetchprofile/package-info.java
hibernate-core/src/test/java/org/hibernate/orm/test/fetchprofiles/CollectionLoadedInTwoPhaseLoadTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/fetchprofiles/EntityLoadedInTwoPhaseLoadTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/fetchprofiles/join/selfReferencing/Employee.java

1. You may now declare an empty named @FetchProfile, and
2. add associations to it using @Fetch.
Note that @Fetch becomes a repeatable annotation.

HHH-16666 allow fetch profiles to be defined using the @Fetch annotation

---

hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/TreatKeywordTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ql/TreatKeywordTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/WindowFunctionTest.java
hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java

https://hibernate.atlassian.net/browse/HHH-16655
https://hibernate.atlassian.net/browse/HHH-16656
https://hibernate.atlassian.net/browse/HHH-16657

HHH-16655, HHH-16656, HHH-16657 H2 missing function registrations, window frame parse error and treat fix for subqueries

---

documentation/src/main/asciidoc/introduction/Advanced.adoc
documentation/src/main/asciidoc/introduction/Entities.adoc
documentation/src/main/asciidoc/introduction/Tuning.adoc
hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotationBinder.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/ToOneBinder.java
hibernate-core/src/main/java/org/hibernate/engine/profile/Association.java
hibernate-core/src/main/java/org/hibernate/engine/profile/Fetch.java
hibernate-core/src/main/java/org/hibernate/engine/profile/FetchProfile.java
hibernate-core/src/main/java/org/hibernate/engine/spi/LoadQueryInfluencers.java
hibernate-core/src/main/java/org/hibernate/engine/spi/SubselectFetch.java
hibernate-core/src/main/java/org/hibernate/internal/FetchProfileHelper.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/fetchprofile/FetchProfileTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/fetchprofile/NewFetchTest.java

Finally, after all these years!

HHH-16651 support all fetch styles in fetch profiles

---

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQuerySpec.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/ToHqlStringTest.java

https://hibernate.atlassian.net/browse/HHH-16676

HHH-16676 Handle treat expressions in toHqlString

---

documentation/src/main/asciidoc/introduction/Advanced.adoc
documentation/src/main/asciidoc/introduction/Tuning.adoc
hibernate-core/src/main/java/org/hibernate/annotations/Fetch.java
hibernate-core/src/main/java/org/hibernate/annotations/FetchMode.java
hibernate-core/src/main/java/org/hibernate/annotations/FetchProfile.java
hibernate-core/src/main/java/org/hibernate/annotations/FetchProfileOverride.java
hibernate-core/src/main/java/org/hibernate/annotations/FetchProfileOverrides.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotationBinder.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/DefaultFetchProfileOverride.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/FetchOverrideSecondPass.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/FetchSecondPass.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/ToOneBinder.java
hibernate-core/src/main/java/org/hibernate/engine/FetchTiming.java
hibernate-core/src/main/java/org/hibernate/engine/profile/Fetch.java
hibernate-core/src/main/java/org/hibernate/engine/profile/FetchProfile.java
hibernate-core/src/main/java/org/hibernate/engine/profile/internal/FetchProfileAffectee.java
hibernate-core/src/main/java/org/hibernate/engine/spi/LoadQueryInfluencers.java
hibernate-core/src/main/java/org/hibernate/internal/FetchProfileHelper.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
hibernate-core/src/main/java/org/hibernate/mapping/FetchProfile.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/PluralAttributeMappingImpl.java
hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmInterpretationsKey.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/fetchprofile/NewFetchTest.java

Also introduce `@FetchProfileOverride` in preference to muddying existing semantics of `@Fetch`

HHH-16654 introduce a "default" fetch profile

---

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CacheEntityLoaderHelper.java
hibernate-core/src/test/java/org/hibernate/orm/test/cache/polymorphism/PolymorphicCacheAndBatchingTest.java

https://hibernate.atlassian.net/browse/HHH-16565

HHH-16565 ClassCastException when batch fetch and 2nd level cache are enabled for polymorphic entities

---

hibernate-core/src/main/java/org/hibernate/engine/spi/SubselectFetch.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractNaturalIdLoader.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionBatchLoaderArrayParam.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionBatchLoaderInPredicate.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionElementLoaderByIndex.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderSingleKey.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/DatabaseSnapshotExecutor.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/EntityBatchLoaderInPredicate.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderHelper.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderArrayParam.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderStandard.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiKeyLoadChunker.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoadingBatcher.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdArrayLoadPlan.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderStandardImpl.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdLoadPlan.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleUniqueKeyEntityLoaderStandard.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/GeneratedValuesProcessor.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SimpleDeleteQueryPlan.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SimpleInsertQueryPlan.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SimpleUpdateQueryPlan.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
hibernate-core/src/main/java/org/hibernate/sql/exec/spi/JdbcParameterBindings.java
hibernate-core/src/main/java/org/hibernate/sql/exec/spi/JdbcParametersList.java
hibernate-core/src/test/java/org/hibernate/orm/test/customstructures/JdbcParameterListTest.java

proposal for main:
- https://hibernate.atlassian.net/browse/HHH-16679

HHH-16679 Avoid type pollution problems on iterations of List<JdbcParameter>

---

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractEntityBatchLoader.java
hibernate-core/src/main/java/org/hibernate/loader/ast/spi/SingleIdEntityLoader.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/ReferenceLoadedEnhancedEntityTest.java

https://hibernate.atlassian.net/browse/HHH-16669

HHH-16669 Batch loading prevents throwing ObjectNotFoundException on initialization of non-existent enhanced entity

---

hibernate-core/src/main/java/org/hibernate/engine/spi/SubselectFetch.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractNaturalIdLoader.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionBatchLoaderArrayParam.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionBatchLoaderInPredicate.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionElementLoaderByIndex.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderSingleKey.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/DatabaseSnapshotExecutor.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/EntityBatchLoaderInPredicate.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderHelper.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderArrayParam.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderStandard.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiKeyLoadChunker.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoadingBatcher.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdArrayLoadPlan.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderStandardImpl.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdLoadPlan.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleUniqueKeyEntityLoaderStandard.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/GeneratedValuesProcessor.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SimpleDeleteQueryPlan.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SimpleInsertQueryPlan.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SimpleUpdateQueryPlan.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
hibernate-core/src/main/java/org/hibernate/sql/exec/spi/JdbcParameterBindings.java
hibernate-core/src/main/java/org/hibernate/sql/exec/spi/JdbcParametersList.java
hibernate-core/src/test/java/org/hibernate/orm/test/customstructures/JdbcParameterListTest.java

A preview, so we can talk about this before I go much further.
In particular I'm unhappy about the SPI changes - might not be fitting for a micro release, but I'm not sure how else I could fix the performance issue.
Relates to https://hibernate.atlassian.net/browse/HHH-16629

Draft: Pollution fixes for List<JdbcParameter>

---

hibernate-core/src/main/java/org/hibernate/annotations/FetchProfile.java
hibernate-core/src/main/java/org/hibernate/annotations/FetchProfileOverride.java
hibernate-core/src/main/java/org/hibernate/annotations/View.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
hibernate-core/src/main/java/org/hibernate/mapping/Table.java
hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaCreatorImpl.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaDropperImpl.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardTableExporter.java
hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardTableMigrator.java
hibernate-core/src/test/java/org/hibernate/orm/test/view/ViewTest.java
tooling/hibernate-ant/src/main/java/org/hibernate/tool/hbm2ddl/SchemaValidator.java
tooling/hibernate-ant/src/main/java/org/hibernate/tool/hbm2ddl/SchemaValidatorTask.java

introduce @View annotation

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationProcess.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EntityPersisterConcurrentMap.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappingMetamodelImpl.java

https://hibernate.atlassian.net/browse/HHH-16683

HHH-16683 Micro optimisations for MappingMetamodelImpl.getEntityDescriptor

---

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java

https://hibernate.atlassian.net/browse/HHH-16685

HHH-16685 Avoid extreme cache misses on EntityPersister#implementsLifecycle()

---

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmPolymorphicRootDescriptor.java
hibernate-core/src/test/java/org/hibernate/orm/test/hql/MappedSuperclassAttributeQueryTest.java

https://hibernate.atlassian.net/browse/HHH-16543

HHH-16543 Attribute from MappedSuperClass can't be resolved if number of subclasses is greater than 2

---

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
hibernate-core/src/test/java/org/hibernate/orm/test/associations/any/ManyToAnyMergeTest.java

https://hibernate.atlassian.net/browse/HHH-16532

HHH-16532 Hibernate entity with @Any attribute throws a nullpointer exception when merging

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/MapBinder.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ManyToManyCollectionPart.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java
hibernate-core/src/test/java/org/hibernate/orm/test/manytomany/mapkey/ManyToManyMapKeyTest.java

https://hibernate.atlassian.net/browse/HHH-16370

HHH-16370 Using MapKey on ManyToMany leads to wrong insert SQL

---

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSqlAstCreationState.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ForeignKeyDescriptor.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddedForeignKeyDescriptor.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java
hibernate-core/src/main/java/org/hibernate/persister/entity/EntityNameUse.java
hibernate-core/src/main/java/org/hibernate/persister/entity/UnionSubclassEntityPersister.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/SqlAstQueryPartProcessingStateImpl.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/SqlAstQueryPartProcessingState.java
hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/TableGroup.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/embeddables/EmbeddableWithGenericAndMappedSuperClassTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/EntityUseJoinedSubclassOptimizationTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/EntityUseSingleTableOptimizationTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/EntityUseUnionSubclassOptimizationTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ql/TreatKeywordTest.java

https://hibernate.atlassian.net/browse/HHH-16658

HHH-16658 Propagate entity name uses from predicates and subqueries properly to the upper context

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/FakeSqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/SqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/BasicValuedPathInterpretation.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EmbeddableValuedPathInterpretation.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQuerySpec.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ql/JoinTableOptimizationTest.java

https://hibernate.atlassian.net/browse/HHH-16691

HHH-16691 Avoid join table joins for SqmPath in some more scenarios

---

hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
hibernate-core/src/main/java/org/hibernate/engine/spi/PersistenceContext.java
hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java
hibernate-core/src/main/java/org/hibernate/engine/spi/SessionImplementor.java
hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java
hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java
hibernate-core/src/main/java/org/hibernate/event/internal/EntityState.java
hibernate-core/src/main/java/org/hibernate/event/spi/EventSource.java
hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/deleteunloaded/DeleteUnloadedProxyTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/deleteunloaded/ParentSub.java

https://hibernate.atlassian.net/browse/HHH-16690

HHH-16690 Fix re-saving for unloaded deletes

---

documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc
hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java
hibernate-core/src/main/java/org/hibernate/query/criteria/HibernateCriteriaBuilder.java
hibernate-core/src/main/java/org/hibernate/query/criteria/spi/HibernateCriteriaBuilderDelegate.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaBuilderNonStandardFunctionsTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java

I know I tested this before, but I forget how many dbs it fails on...

HHH-16699  promote repeat() function

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/EntityJoinTest.java

https://hibernate.atlassian.net/browse/HHH-16495

HHH-16495 A query with an non-cross entity join that lacks the on clause should fail with a SemanticQueryException

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/AttributeMappingsList.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EmbeddableMappingType.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ManagedMappingType.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ImmutableAttributeMappingList.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MutableAttributeMappingList.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/DeleteCoordinator.java
hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
hibernate-core/src/main/java/org/hibernate/sql/ast/tree/cte/CteTable.java
hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/binding/annotations/access/xml/XmlAccessTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/CriteriaEntityGraphTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/EntityGraphLoadPlanBuilderTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/HqlEntityGraphTest.java

https://hibernate.atlassian.net/browse/HHH-16705

Refine contract of AttributeMappingsList / 6.2

---

documentation/src/main/asciidoc/userguide/chapters/envers/Envers.adoc

Fix small spelling mistake in Envers Documentation

HHH-16706 Fix spelling in Envers.adoc

---

hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
hibernate-core/src/main/java/org/hibernate/dialect/function/HypotheticalSetWindowEmulation.java
hibernate-core/src/main/java/org/hibernate/dialect/function/InverseDistributionFunction.java
hibernate-core/src/main/java/org/hibernate/dialect/function/InverseDistributionWindowEmulation.java
hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleType.java
hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
hibernate-core/src/main/java/org/hibernate/query/sqm/function/FunctionKind.java
hibernate-core/src/main/java/org/hibernate/query/sqm/function/SelfRenderingSqmOrderedSetAggregateFunction.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/WindowFunctionTest.java

- also refactor a bit that code in SQB to be more typesafe
- and get rid of some warnings

fix NPE when ordered set agg function missing 'within group'

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/cid/EmbeddedInsideEmbeddedIdTest.java

https://hibernate.atlassian.net/browse/HHH-16560

HHH-16560 Nested @Embedded within an @EmbeddedId assertion failure  "java.lang.AssertionError: isPartOfKey should have been true in this case"

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/cid/EmbeddedInsideEmbeddedIdTest.java

https://hibernate.atlassian.net/browse/HHH-16560

HHH-16560 Nested @Embedded within an @EmbeddedId assertion failure "java.lang.AssertionError: isPartOfKey should have been true in this case"

---

hibernate-core/src/main/java/org/hibernate/action/internal/CollectionAction.java
hibernate-core/src/main/java/org/hibernate/action/internal/EntityAction.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcServicesImpl.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/JdbcServices.java
hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
hibernate-core/src/main/java/org/hibernate/engine/spi/ComparableExecutable.java
hibernate-core/src/main/java/org/hibernate/engine/spi/ExecutableList.java
hibernate-core/src/main/java/org/hibernate/sql/SimpleSelect.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/test/java/org/hibernate/orm/test/engine/action/NonSortedExecutableListTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/engine/action/SortedExecutableListTest.java
hibernate-testing/src/main/java/org/hibernate/testing/boot/BasicTestingJdbcServiceImpl.java

- https://hibernate.atlassian.net/browse/HHH-16716
- https://hibernate.atlassian.net/browse/HHH-16717

More type related refactorings

---

hibernate-core/src/main/java/org/hibernate/action/internal/CollectionAction.java
hibernate-core/src/main/java/org/hibernate/action/internal/EntityAction.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcServicesImpl.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/JdbcServices.java
hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
hibernate-core/src/main/java/org/hibernate/engine/spi/ComparableExecutable.java
hibernate-core/src/main/java/org/hibernate/engine/spi/ExecutableList.java
hibernate-core/src/main/java/org/hibernate/sql/SimpleSelect.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/test/java/org/hibernate/orm/test/engine/action/NonSortedExecutableListTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/engine/action/SortedExecutableListTest.java
hibernate-testing/src/main/java/org/hibernate/testing/boot/BasicTestingJdbcServiceImpl.java

- https://hibernate.atlassian.net/browse/HHH-16717
- https://hibernate.atlassian.net/browse/HHH-16716

Type pollution fix for ExecutableList having to implement Comparable

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/collections/EmbeddedMapElementCollectionJoinTest.java

https://hibernate.atlassian.net/browse/HHH-16540

HHH-16540 UnknownTableReferenceException for entity with Embeddable key-value in map

---

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/EntityBatchLoaderArrayParam.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchAndEnumIdTest.java

https://hibernate.atlassian.net/browse/HHH-16639

HHH-16639 Cannot load entity with EnumType identifier and batch size > 1

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/idclass/IdClassWithSuperclassTest.java

https://hibernate.atlassian.net/browse/HHH-16664

HHH-16664 NPE in MappingMetamodelImpl if inheritance is used in IdClass

---

hibernate-core/src/test/java/org/hibernate/orm/test/refresh/RefreshAndCollections.java

https://hibernate.atlassian.net/browse/HHH-16665

HHH-16665 Add test for issue

---

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/DirtyTrackingDynamicUpdateAndInheritanceTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/DirtyTrackingDynamicUpdateTest.java

https://hibernate.atlassian.net/browse/HHH-16379

HHH-16379 @DynamicUpdate and 'enableDirtyTracking=true' leads to wrong update statement

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/AssemblerCreationState.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializerBuilder.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/ResultsHelper.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchFetchInstantiationTest.java

https://hibernate.atlassian.net/browse/HHH-16559

HHH-16559 Batch fetch does not initialize bi-directional entity in HQL

---

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java
hibernate-core/src/test/java/org/hibernate/orm/test/sql/exec/manytoone/EntityWithEagerManyToOneTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/sql/exec/manytoone/EntityWithLazyManyToOneTest.java

https://hibernate.atlassian.net/browse/HHH-16613

HHH-16613 @Lazy @ManyToOne @Cacheable association is retrieved as initialized

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/VirtualIdEmbeddable.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/cid/CompositeIdWithOrderedUpdatesTest.java

https://hibernate.atlassian.net/browse/HHH-16725

HHH-16725 Persisting multiple entities with one-many association and composite key with ordered updates enabled fails

---

hibernate-core/src/main/java/org/hibernate/query/hql/internal/StandardHqlTranslator.java
hibernate-core/src/test/java/org/hibernate/orm/test/hql/ASTParserLoadingTest.java

the formatting of syntax errors was terrible

HHH-16022 fix extremely ugly errors when HQL parsing failed

---

hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/TreatCorrelatedTest.java

https://hibernate.atlassian.net/browse/HHH-16680

HHH-16680 Add test for treating correlated from node

---

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/SelectOnlyArrayPropertyTest.java

https://hibernate.atlassian.net/browse/HHH-16606

HHH-16606 Only use RowTransformerArrayImpl when result type is Object[]

---

hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/CollectionJavaType.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/JsonMappingTests.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/JsonEmbeddableTest.java

https://hibernate.atlassian.net/browse/HHH-16682

HHH-16682 Test and fix dirty checking for @JdbcTypeCode(SqlTypes.JSON) maps

---

hibernate-core/src/main/java/org/hibernate/engine/spi/SubselectFetch.java
hibernate-core/src/main/java/org/hibernate/sql/exec/spi/ExecutionContext.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/NestedRowProcessingState.java
hibernate-core/src/main/java/org/hibernate/sql/results/internal/StandardRowReader.java
hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesSourceProcessingStateStandardImpl.java
hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/spi/JdbcValuesSourceProcessingState.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/SubselectTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/DepthOneBatchTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/DepthOneTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/subselect/SubselectOneToManyTest.java

https://hibernate.atlassian.net/browse/HHH-16624

HHH-16624 Do not create subselects when there are fewer than 2 results

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/ClassPropertyHolder.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/GenericAssociationOrderColumnTest.java

https://hibernate.atlassian.net/browse/HHH-16641

HHH-16641 @OrderColumn fails for a generic collection with NPE on XProperty.getMapKey()

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2LegacySqlAstTranslator.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacySqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/StatelessSession.java
hibernate-core/src/main/java/org/hibernate/dialect/DB2SqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/OracleSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/dialect/SqlAstTranslatorWithMerge.java
hibernate-core/src/main/java/org/hibernate/dialect/function/CountFunction.java
hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/BasicFormatterImpl.java
hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java
hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/MergeCoordinator.java
hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
hibernate-core/src/main/java/org/hibernate/query/sqm/function/NamedSqmFunctionDescriptor.java
hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/internal/PatternRenderer.java
hibernate-core/src/main/java/org/hibernate/sql/ast/SqlAstWalker.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstWalker.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/ExpressionReplacementWalker.java
hibernate-core/src/main/java/org/hibernate/sql/ast/spi/SqlAppender.java
hibernate-core/src/main/java/org/hibernate/sql/model/ast/AbstractRestrictedTableMutation.java
hibernate-core/src/main/java/org/hibernate/sql/model/ast/RestrictedTableMutation.java
hibernate-core/src/main/java/org/hibernate/sql/model/ast/builder/TableMergeBuilder.java
hibernate-core/src/main/java/org/hibernate/sql/model/internal/OptionalTableUpdate.java
hibernate-core/src/main/java/org/hibernate/sql/model/internal/TableUpdateNoSet.java
hibernate-core/src/test/java/org/hibernate/orm/test/jdbc/util/BasicFormatterTest.java

Here's a POC for the `upsert()` method of `StatelessSession`, but I really need @sebersole to take a look at how I've done this.

HHH-16727 StatelessSession.upsert()

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddableMappingTypeImpl.java
hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/test/java/org/hibernate/orm/test/filter/subclass/singletable/SingleTableDefaultSchemaFilterTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/JsonEmbeddableAndSchemaNameTest.java

https://hibernate.atlassian.net/browse/HHH-16661
https://hibernate.atlassian.net/browse/HHH-16612

HHH-16661, HHH-16612 Fix NPEs caused by unqualified table names when schema/catalog are set

---

hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaInheritanceJoinTest.java

https://hibernate.atlassian.net/browse/HHH-16719 
Adding test case, fixed by https://github.com/hibernate/hibernate-orm/pull/6704.

HHH-16719 Upgrading from 6.1.7.Final to 6.2.2.Final breaks Criteria queries for model with inheritance

---

hibernate-envers/hibernate-envers.gradle
hibernate-micrometer/hibernate-micrometer.gradle
settings.gradle
tooling/metamodel-generator/hibernate-jpamodelgen.gradle
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/ClassWriter.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/Context.java

https://hibernate.atlassian.net/browse/HHH-16563

HHH-16563: Using jakarta.annotation.Generated instead of javax versions

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/ClassPropertyHolder.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/GenericAssociationOrderColumnTest.java

https://hibernate.atlassian.net/browse/HHH-16641

HHH-16641 @OrderColumn fails for a generic collection with NPE on XProperty.getMapKey() 

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedColumn.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/BasicValueBinder.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractManagedType.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/BasicSqmPathSource.java
hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/SingularAttributeImpl.java
hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
hibernate-core/src/main/java/org/hibernate/query/PathElementException.java
hibernate-core/src/main/java/org/hibernate/query/PathException.java
hibernate-core/src/main/java/org/hibernate/query/TerminalPathException.java
hibernate-core/src/main/java/org/hibernate/query/sqm/SqmPathSource.java
hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/NonAggregatedCompositeSimplePath.java

and squash some warnings
UPDATE: I have rolled in my work on HHH-16731

HHH-16776, HHH-16731 more consistent reporting of errors in attribute paths

---

hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/TupleQueryTest.java

Already fixed by https://github.com/hibernate/hibernate-orm/pull/6685

HHH-16742 - Add test for issue

---

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java
hibernate-core/src/test/java/org/hibernate/orm/test/idclass/IdClassPropertiesTest.java

https://hibernate.atlassian.net/browse/HHH-16761

HHH-16761 Throw an appropriate error when an entity defines more @Id fields than its @IdClass

---

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/ByteBuddyEnhancementContext.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/InlineDirtyCheckingHandler.java
hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/PersistentAttributeTransformer.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/DirtyTrackingEmbeddableTest.java

https://hibernate.atlassian.net/browse/HHH-16774

HHH-16774 Ensure composite field tracking enhancement works also when @Embedded annotation is missing

---

hibernate-core/src/main/java/org/hibernate/type/ComponentType.java
hibernate-core/src/test/java17/org/hibernate/orm/test/records/MergeRecordPropertyTestCase.java

Jira issue [HHH-16759](https://hibernate.atlassian.net/browse/HHH-16759)
[HHH-16759]: https://hibernate.atlassian.net/browse/HHH-16759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HHH-16759 - Merge fails when entity has an Embedded Java record

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/EntityValuedInSubqueryGroupAndOrderTest.java

https://hibernate.atlassian.net/browse/HHH-16770

HHH-16770 Entity valued path expansion for GROUP BY clause causes problems for in-subquery predicates

---

hibernate-core/src/main/java/org/hibernate/tool/schema/internal/AbstractSchemaMigrator.java

Fix for [jira issue HHH-16614](https://hibernate.atlassian.net/browse/HHH-16614)

HHH-16614 - Properly handling before/after tables on creation for auxiliary database objects

---

hibernate-core/src/main/java/org/hibernate/dialect/function/FormatFunction.java
hibernate-core/src/main/java/org/hibernate/dialect/function/HypotheticalSetWindowEmulation.java
hibernate-core/src/main/java/org/hibernate/dialect/function/InverseDistributionFunction.java
hibernate-core/src/main/java/org/hibernate/dialect/function/InverseDistributionWindowEmulation.java
hibernate-core/src/main/java/org/hibernate/query/sqm/function/SelfRenderingSqmAggregateFunction.java
hibernate-core/src/main/java/org/hibernate/query/sqm/function/SelfRenderingSqmFunction.java
hibernate-core/src/main/java/org/hibernate/query/sqm/function/SelfRenderingSqmOrderedSetAggregateFunction.java
hibernate-core/src/main/java/org/hibernate/query/sqm/function/SelfRenderingSqmWindowFunction.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/MultiValuedParameterInFunctionTest.java

https://hibernate.atlassian.net/browse/HHH-16787

HHH-16787 Multi-valued parameter with single element parameter list fails with no such element exception

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/SqmParameterInterpretation.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/InsertSelectTests.java

https://hibernate.atlassian.net/browse/HHH-16786

HHH-16786 Fix NPE in SqmParameterInterpretation when binding null for select item in insert-select statement

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
hibernate-core/src/test/java/org/hibernate/orm/test/procedure/OracleStoredProcedureTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/sql/OracleStoredProcedureTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/sql/autodiscovery/AutoDiscoveryTest.java

https://hibernate.atlassian.net/browse/HHH-16697

HHH-16697 Fix auto type discovery for aggregate functions on Oracle

---

tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/ClassWriter.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/Context.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/JPAMetaModelEntityProcessor.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMeta.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaAttribute.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaPackage.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/NameMetaAttribute.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/model/MetaAttribute.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/model/Metamodel.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/Constants.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/StringUtil.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/TypeUtils.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/xml/XmlMetaAttribute.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/xml/XmlMetaEntity.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/xml/XmlMetaMap.java
tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/namedquery/AuxiliaryTest.java
tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/namedquery/Book.java
tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/namedquery/Main.java
tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/util/TestUtil.java

This time with support for package-level annotations.

generate typesafe references to named queries, fetch profiles, entity graphs, fetch profiles

---

hibernate-core/src/main/java/org/hibernate/metamodel/internal/AttributeFactory.java
hibernate-core/src/main/java/org/hibernate/metamodel/internal/BaseAttributeMetadata.java
hibernate-core/src/main/java/org/hibernate/query/internal/BindingTypeHelper.java
hibernate-core/src/main/java/org/hibernate/query/spi/AbstractCommonQueryContract.java
hibernate-core/src/main/java/org/hibernate/type/descriptor/java/TemporalJavaType.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/type/dynamicparameterized/DynamicParameterizedTypeTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/QueryTest.java

https://hibernate.atlassian.net/browse/HHH-16749

HHH-16749 Reuse BasicType from Value for JPA Metamodel instead of creating dedicated BasicDomainType instances

---

hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/internal/MutationQueryOptions.java
hibernate-core/src/main/java/org/hibernate/jpa/HibernateHints.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSqlAstCreationState.java
hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java
hibernate-core/src/main/java/org/hibernate/query/internal/QueryOptionsImpl.java
hibernate-core/src/main/java/org/hibernate/query/spi/AbstractCommonQueryContract.java
hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java
hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java
hibernate-core/src/main/java/org/hibernate/query/spi/DelegatingQueryOptions.java
hibernate-core/src/main/java/org/hibernate/query/spi/MutableQueryOptions.java
hibernate-core/src/main/java/org/hibernate/query/spi/QueryOptions.java
hibernate-core/src/main/java/org/hibernate/query/spi/QueryOptionsAdapter.java
hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmInterpretationsKey.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java
hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcSelectExecutorStandardImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/TransientOverrideAsPersistentJoined.java
hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/TransientOverrideAsPersistentMappedSuperclass.java
hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/TransientOverrideAsPersistentSingleTable.java
hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/TransientOverrideAsPersistentTablePerClass.java
hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/TransientOverrideAsPersistentWithEmbeddable.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/ILikeCriteriaTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/stat/internal/QueryPlanCacheStatisticsTest.java

https://hibernate.atlassian.net/browse/HHH-16782

HHH-16782 Allow query plan caching of criteria queries

---

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/NonAggregatedIdentifierMappingImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/cache/ManyToOneTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/cache/ManyToOneWithOptimisticLockingTest.java

https://hibernate.atlassian.net/browse/HHH-16673

HHH-16673 Fail to get access lazy fetched field ( @ManyToOne ) wich is part of a composite Id (using an @IdClass) when stored in L2 cache

---

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractCollectionBatchLoader.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionBatchLoaderArrayParam.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionBatchLoaderInPredicate.java
hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ForeignKeyDescriptor.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddedForeignKeyDescriptor.java
hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/AbstractBatchEntitySelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntityInsideEmbeddableSelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntitySelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchInitializeEntitySelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializerBuilder.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/CompositeIdAndElementCollectionBatchingTest.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/CompositeIdWithOneFieldAndElementCollectionBatchingTest.java

https://hibernate.atlassian.net/browse/HHH-16740
https://hibernate.atlassian.net/browse/HHH-16750
this is an alternative solution to https://github.com/hibernate/hibernate-orm/pull/6734

HHH-16740 + HHH-16750 Fetching an element collection on an entity with a composite id fails when batch size > 1

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/cache/StructuredEntityCacheInheritanceTest.java

https://hibernate.atlassian.net/browse/HHH-16714

HHH-16714 Caching does not work properly when hibernate.cache.use_structured_entries is turned on 

---

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/AbstractBatchEntitySelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntityInsideEmbeddableSelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntitySelectFetchInitializer.java
hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchInitializeEntitySelectFetchInitializer.java
hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/cache/ManyToOneTestReusedColumn.java

https://hibernate.atlassian.net/browse/HHH-16744

HHH-16744 Wrong class created when reusing a join column for different entities in multiple ManyToOne

---

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
hibernate-core/src/test/java/org/hibernate/orm/test/version/VersionSeedUpdateTest.java

https://hibernate.atlassian.net/browse/HHH-16678

HHH-16678 AssertionError in QueryLiteral.<init> when using "update versioned Entity ..." if @Version is a long

---

hibernate-envers/src/main/java/org/hibernate/envers/AuditReader.java
hibernate-envers/src/main/java/org/hibernate/envers/internal/reader/AuditReaderImpl.java
hibernate-envers/src/main/java/org/hibernate/envers/query/AuditQueryCreator.java

since `java.util.Date` is bad.
Also add some Javadoc to `AuditReader`.

add AuditReader.find(Class,Object, LocalDateTime)

---

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/HSQLLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MariaDBLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java
hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/FunctionalDependencyAnalysisSupport.java
hibernate-core/src/main/java/org/hibernate/dialect/FunctionalDependencyAnalysisSupportImpl.java
hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java
hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/InheritanceQueryGroupByTest.java

https://hibernate.atlassian.net/browse/HHH-16773

HHH-16773 Introduce a Dialect flag for databases that support group by / order by functional dependency

---

hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/BatchImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchRowCountWarningTest.java

https://hibernate.atlassian.net/browse/HHH-16713

HHH-16713 Unexpected warning: "HHH100001:  JDBC driver did not return the expected number of row counts"

---

hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/CorrelatedTableGroup.java
hibernate-core/src/test/java/org/hibernate/orm/test/query/JoinReuseInCorrelatedSubqueryTest.java

https://hibernate.atlassian.net/browse/HHH-16537

HHH-16537 Wrong SQL generated when root join is not used in sub-query

---

hibernate-core/src/main/java/org/hibernate/annotations/Hql.java
hibernate-core/src/main/java/org/hibernate/annotations/Sql.java
hibernate-core/src/main/java/org/hibernate/annotations/processing/CheckHQL.java
hibernate-core/src/main/java/org/hibernate/annotations/processing/GenericDialect.java
hibernate-core/src/main/java/org/hibernate/annotations/processing/HQL.java
hibernate-core/src/main/java/org/hibernate/annotations/processing/SQL.java
hibernate-core/src/main/java/org/hibernate/annotations/processing/package-info.java
hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java
hibernate-core/src/main/java/org/hibernate/query/Query.java
hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java
hibernate-core/src/main/java/org/hibernate/query/hql/spi/SqmQueryImplementor.java
hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
hibernate-core/src/main/java/org/hibernate/query/sqm/SortOrder.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java
tooling/metamodel-generator/hibernate-jpamodelgen.gradle
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/ClassWriter.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/JPAMetaModelEntityProcessor.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMeta.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaAttribute.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaPackage.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/QueryMethod.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/model/Metamodel.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/Constants.java
tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/xml/XmlMetaEntity.java
tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/generatedannotation/GeneratedAnnotationTest.java
tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/namedquery/AuxiliaryTest.java
tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/namedquery/Dao.java

Handwritten code:
```java
public interface Antirepository {
@Hql("from Book where isbn = :isbn")
Book findBookByIsbn(String isbn);
@Hql("from Book where title like ?1 order by title offset ?3 fetch first ?2 rows only")
List<Book> findBooksByTitleWithPagination(String title, int max, int start);
@Hql("from Book where title like ?1")
TypedQuery<Book> findBooksByTitle(String title);
}
```
Resulting generated code:
```java
@Generated(value = "org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor")
@StaticMetamodel(Antirepository.class)
public abstract class Antirepository_ {
public static Book findBookByIsbn(EntityManager entityManager, String isbn) {
return entityManager.createQuery(FIND_BOOK_BY_ISBN, Book.class)
.setParameter("isbn", isbn)
.getSingleResult();
}
public static List<Book> …
```

HHH-16633, HHH-16813 HHH-16815 introduce query methods to JPA metamodel generator

---

hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java
hibernate-core/src/main/java/org/hibernate/query/Query.java
hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java
hibernate-core/src/main/java/org/hibernate/query/hql/spi/SqmQueryImplementor.java
hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java
hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java
hibernate-core/src/test/java/org/hibernate/orm/test/annotations/immutable/ImmutableEntityUpdateQueryHandlingModeExceptionTest.java

and code cleanups in the `Query` hierarchy

HHH-16815 fix generic signature of ascending() / descending()
