hibernate/hibernate-orm

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializerBuilder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/cache/AbstractManyToOneNoProxyTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/cache/ManyToOneNoProxyTest.java
https://hibernate.atlassian.net/browse/HHH-16743
> HHH-16743 StackOverflowError when loading a ManyToOne whith @Proxy(lazy=false)

- hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/LazyAbstractManyToOneNoProxyTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/LazyManyToOneNoProxyTest.java
https://hibernate.atlassian.net/browse/HHH-16794
> HHH-16794 With Bytecode enhancement a lazy ManyToOne association targeting an Entity annotated with @Proxy(lazy = false) is eagerly loaded

- hibernate-core/src/main/java/org/hibernate/boot/model/TypeDefinition.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/MappedSuperclassTemporalAccessorTest.java
https://hibernate.atlassian.net/browse/HHH-16784
> HHH-16784 @MappedSuperclass with parameterized interface types no longer works

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/TiDBDialect.java
https://hibernate.atlassian.net/browse/HHH-16773
> HHH-16773 Fix functional dependency support level for TiDB and Cockroach

- hibernate-core/src/main/java/org/hibernate/metamodel/internal/AttributeFactory.java
https://hibernate.atlassian.net/browse/HHH-16784
> HHH-16784 Fix type resolution for generic interface properties

- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/MaxInExpressionParameterPaddingTest.java
https://hibernate.atlassian.net/browse/HHH-16589
> HHH-16589 Limit in clause padding to Dialect.getInExpressionCountLimit and fix negated in predicate splitting

- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/CorrelatedTableGroup.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/LazyTableGroup.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/ImplicitJoinInSubqueryTest.java
https://hibernate.atlassian.net/browse/HHH-16721
> HHH-16721 Make sure join predicate is propagated to correlation on lazy initialization

- hibernate-core/src/test/java/org/hibernate/orm/test/array/DateArrayTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cdi/general/hibernatesearch/TheFallbackBeanInstanceProducer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cdi/general/hibernatesearch/TheReflectionInstantiatedBean.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/MappedByEmbeddableTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/OrderByEmbeddableToOneTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/OrderByEmbeddableX2Test.java
- hibernate-core/src/test/java/org/hibernate/orm/test/hql/size/filter/City.java
- hibernate-core/src/test/java/org/hibernate/orm/test/hql/size/filter/Region.java
- hibernate-core/src/test/java/org/hibernate/orm/test/hql/size/filter/WhereAnnotatedOneToManySizeTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/loading/LoadContainedInDoubleContainingTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiLoadSecondLlvCacheTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/BaseIdEntityByteCodeTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/polymorphic/PolymorphicAssociationTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/polymorphic/PolymorphicAssociationTest2.java
Looks like my IDE was misconfigured when I contributed those files.
> Fix a few invalid file headers

- hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/StandardHqlTranslator.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/CdiBeanContainerExtendedAccessImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/SqlTreePrinter.java
https://hibernate.atlassian.net/browse/HHH-16831
> HHH-16831 Replace string concat with proper string format for logging

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacySqlAstTranslator.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacySqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/HANASqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/OracleSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SybaseASESqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/insert/SqmInsertValuesStatement.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/hql/HQLTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/InsertUpdateTests.java
https://hibernate.atlassian.net/browse/HHH-14483
> HHH-14483 Split insert-values statement if dialect doesn't support values lists

- hibernate-core/src/main/java/org/hibernate/action/internal/CollectionRemoveAction.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/beanvalidation/LazyCollectionValidationTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/flush/LazyCollectionInitalizationPreUpdateTest.java
https://hibernate.atlassian.net/browse/HHH-16602
https://hibernate.atlassian.net/browse/HHH-16701
> HHH-16602, HHH-16701 ActionQueue changes for collection removals of orphaned entities

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/DerivedRootExpansionUsageTest.java
https://hibernate.atlassian.net/browse/HHH-15435
> HHH-15435 Improve error when using derived root in context that needs expansion

- hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/hhh16711/Inheriting.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/hhh16711/MappedSuperclassInheritanceTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/hhh16711/otherPackage/Inherited.java
https://hibernate.atlassian.net/browse/HHH-16711
https://hibernate.atlassian.net/browse/HHH-16707
> HHH-16711/HHH-16707 Ensure static accessor methods for accessing foreign package state use visible types

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/InferredBasicValueResolver.java
- hibernate-core/src/main/java/org/hibernate/boot/query/SqlResultSetMappingDescriptor.java
- hibernate-core/src/main/java/org/hibernate/dialect/AbstractPostgreSQLStructJdbcType.java
- hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/aggregate/OracleAggregateSupport.java
- hibernate-core/src/main/java/org/hibernate/dialect/hint/IndexQueryHintHandler.java
- hibernate-core/src/main/java/org/hibernate/dialect/pagination/Oracle12LimitHandler.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
- hibernate-core/src/main/java/org/hibernate/internal/util/CharSequenceHelper.java
- hibernate-core/src/main/java/org/hibernate/metamodel/internal/JpaStaticMetaModelPopulationSetting.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/StandardHqlTranslator.java
- hibernate-core/src/main/java/org/hibernate/query/results/FromClauseAccessImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmAttributeJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmExpressionHelper.java
- hibernate-core/src/main/java/org/hibernate/sql/Template.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/CollectionTableGroup.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/CorrelatedPluralTableGroup.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
- hibernate-core/src/main/java/org/hibernate/stat/internal/CacheRegionStatisticsImpl.java
- hibernate-core/src/main/java/org/hibernate/stat/internal/SessionStatisticsImpl.java
- hibernate-core/src/main/java/org/hibernate/tuple/component/AbstractCompositionAttribute.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/tools/StringTools.java
- hibernate-testing/src/main/java/org/hibernate/testing/logger/LogInspectionHelper.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/ImportContextImpl.java
These are largely performed automatically by IntelliJ, shouldn't have any semantic impact.
> Some minor cleanup

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/CodeTemplates.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/InlineDirtyCheckingHandler.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/DirtyCheckingWithEmbeddableAndNonVisibleGenericMappedSuperclassTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/MyNonVisibleGenericMappedSuperclass.java
https://hibernate.atlassian.net/browse/HHH-16832
> HHH-16832 Bytecode enhancement leads to broken constructor for a generic embedded field in a MappedSuperclass

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddableMappingTypeImpl.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/DeleteCoordinator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/locking/EmbeddableWithManyToManyAndOptimistickLockingDeletionTest.java
https://hibernate.atlassian.net/browse/HHH-16821
> HHH-16821 Fail to delete entity with a composite id using an @IdClass with one of its fields mapped from the id of a @ManyToOne association

- hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessEnhancedImpl.java
- hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyEnhancedImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/access/PropertyAccessTest.java
https://hibernate.atlassian.net/browse/HHH-16799
and a backport to 6.2 is here https://github.com/hibernate/hibernate-orm/pull/6798
> HHH-16799 Don't fall back to field access type too early

- hibernate-core/src/main/java/org/hibernate/boot/archive/scan/spi/ClassFileArchiveEntryHandler.java
https://hibernate.atlassian.net/browse/HHH-16462
> HHH-16462 Share the same Jandex Indexer while indexing different files

- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/locking/OptimisticLockTypeDirtyWithLazyOneToOneTest.java
https://hibernate.atlassian.net/browse/HHH-16839
> HHH-16839 Failing to update a one-to-one lazy association with `OptimisticLockType.DIRTY` and enabled bytecode enhancement

- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/locking/OptimisticLockTypeDirtyWithLazyOneToOneTest.java
https://hibernate.atlassian.net/browse/HHH-16839
> HHH-16839 Failing to update a one-to-one lazy association with OptimisticLockType.DIRTY and enabled bytecode enhancement

- documentation/src/main/asciidoc/userguide/chapters/fetching/Fetching.adoc
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractEntityBatchLoader.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/EntityBatchLoaderArrayParam.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/EntityBatchLoaderInPredicate.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiKeyLoadHelper.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/lock/BatchAndLockTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/DepthOneBatchTest.java
- migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-16820
> HHH-16820 When batching enabled the LockModeType is ignored

- documentation/src/main/asciidoc/userguide/chapters/fetching/Fetching.adoc
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractEntityBatchLoader.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/lock/BatchAndLockTest.java
- migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-16820
> HHH-16820 When batching enabled the LockModeType is ignored 

- settings.gradle
https://hibernate.atlassian.net/browse/HHH-16851
> HHH-16851 Upgrade Jandex to 3.1.2

- hibernate-core/src/main/java/org/hibernate/Hibernate.java
- hibernate-core/src/main/java/org/hibernate/proxy/AbstractLazyInitializer.java
- hibernate-core/src/main/java/org/hibernate/proxy/LazyInitializer.java
- hibernate-core/src/main/java/org/hibernate/proxy/map/MapLazyInitializer.java
- hibernate-core/src/main/java/org/hibernate/proxy/pojo/BasicLazyInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/getclass/HibernateGetClassTest.java
https://hibernate.atlassian.net/browse/HHH-13857
> HHH-13857 Avoid initialization when obtaining persistent class with Hibernate.getClass()

- hibernate-core/src/main/java/org/hibernate/type/descriptor/converter/internal/JpaAttributeConverterImpl.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/internal/JdbcLiteralFormatterCharacterData.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/SQLServerNationalizedScalarQueryTest.java
> HHH-16857 fix the syntax for NVARCHAR literals on SQL Server

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/CriteriaTreatedJoinInSubqueryTest.java
https://hibernate.atlassian.net/browse/HHH-16642
> HHH-16642 Treated join in subquery results in invalid SQL

- hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentBag.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetomany/OneToManyDuplicatesTest.java
https://hibernate.atlassian.net/browse/HHH-14078
> HHH-14078 Avoid duplicate elements when initializing bag with queued operations

- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
cc/ @DavideD this is what I'm thinking to change in ORM to allow for:
- https://github.com/hibernate/hibernate-reactive/commit/d75990ead9d91a968a3b50f8f45ed1d1d242e910
> HHH-16873 Expose fast-path cloning constructors for UpdateCoordinatorStandard

- hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteDeleteHandler.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteUpdateHandler.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/CriteriaBulkUpdateQuotedInheritanceTest.java
https://hibernate.atlassian.net/browse/HHH-16792
> HHH-16792 Incorrect generated SQL query when using CriteriaUpdate on an entity with inheritance

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/CriteriaWithDynamicInstantiationAndOrderByTest.java
https://hibernate.atlassian.net/browse/HHH-15720
> HHH-15720 Using multiple select in a multiselect generates java.lang.ArrayIndexOutOfBoundsException

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/Discriminable.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/DiscriminatedAssociationModelPart.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityMappingType.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
"disciminatable" isn't standard English.
> rename Discriminatable -> Discriminable

- hibernate-core/src/main/java/org/hibernate/query/internal/ParameterMetadataImpl.java
https://hibernate.atlassian.net/browse/HHH-16853
> HHH-16853 Setting Named Query Parameters is VERY slow

- hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/BasicCollectionPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/OneToManyPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/AbstractUpdateRowsCoordinator.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/DeleteRowsCoordinatorStandard.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/DeleteRowsCoordinatorTablePerSubclass.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/InsertRowsCoordinatorStandard.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/InsertRowsCoordinatorTablePerSubclass.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/RemoveCoordinatorStandard.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/RemoveCoordinatorTablePerSubclass.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/UpdateRowsCoordinatorOneToMany.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/UpdateRowsCoordinatorStandard.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/UpdateRowsCoordinatorTablePerSubclass.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/AbstractMutationCoordinator.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/DeleteCoordinator.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/InsertCoordinator.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
https://hibernate.atlassian.net/browse/HHH-16877
> HHH-16877 Efficient lookup of MutationExecutorService

- hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/BasicCollectionPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/OneToManyPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/AbstractUpdateRowsCoordinator.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/DeleteRowsCoordinatorStandard.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/DeleteRowsCoordinatorTablePerSubclass.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/InsertRowsCoordinatorStandard.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/InsertRowsCoordinatorTablePerSubclass.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/RemoveCoordinatorStandard.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/RemoveCoordinatorTablePerSubclass.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/UpdateRowsCoordinatorOneToMany.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/UpdateRowsCoordinatorStandard.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/mutation/UpdateRowsCoordinatorTablePerSubclass.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/AbstractMutationCoordinator.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/DeleteCoordinator.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/InsertCoordinator.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
https://hibernate.atlassian.net/browse/HHH-16877
> Backport of HHH-16877

- hibernate-core/src/main/java/org/hibernate/query/QueryArgumentException.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/spi/QueryParameterBindingValidator.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/TypecheckUtil.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/ArgumentTypesValidator.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/RegistryHelper.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/ObjectParameterTypeForEmbeddableTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/literal/QueryLiteralTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
- hibernate-spatial/src/test/java/org/hibernate/spatial/dialect/postgis/PostgisDistanceOperatorsTest.java
This resolves the discussion around https://hibernate.atlassian.net/browse/HHH-16247, along with another similar problem I found with invoking "unknown" functions in HQL.
> HHH-16875 be more forgiving in the type checking code

- hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
> batch of minor improvements to the parser/SemanticQueryBuilder

- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/TupleInListAlternativeTests.java
https://hibernate.atlassian.net/browse/HHH-16886
Backport of #6929.
> HHH-16886 fix sql mutli value emulation for dialects not supporting row constructor syntax in list

- documentation/src/main/asciidoc/introduction/Introduction.adoc
- documentation/src/main/asciidoc/introduction/Tuning.adoc
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/ResultSetReturnImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/SqlStatementLoggerInitiator.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/SqlStatementLogger.java
- hibernate-core/src/main/java/org/hibernate/internal/JdbcSessionContextImpl.java
- hibernate-core/src/main/java/org/hibernate/resource/jdbc/spi/JdbcSessionContext.java
- hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/DeferredResultSetAccess.java
- hibernate-core/src/main/java/org/hibernate/stat/Statistics.java
- hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsImpl.java
- hibernate-core/src/main/java/org/hibernate/stat/internal/StatsNamedContainer.java
- hibernate-core/src/main/java/org/hibernate/stat/spi/StatisticsImplementor.java
- hibernate-core/src/test/java/org/hibernate/engine/jdbc/spi/SqlStatementLoggerTest.java
Make this property setting satisfy our conventions.
> HHH-16909 hibernate.log_slow_query

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/JPAMetaModelEntityProcessor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMeta.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/MetaAttributeGenerationVisitor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/QueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/Constants.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/TypeUtils.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/validation/Validation.java
Some fallout from work done over the w/e.
> HHH-16633 misc fixes to Metamodel Generator

- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractCollectionBatchLoader.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cache/CollectionCacheEmbeddedIdKeyTest.java
https://hibernate.atlassian.net/browse/HHH-16845
> HHH-16845 Cached entity with @EmbeddedId cannot use @ElementCollection

- hibernate-core/src/main/java/org/hibernate/procedure/ParameterTypeException.java
- hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureParameterImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcCallParameterRegistrationImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/procedure/Helper.java
- hibernate-core/src/test/java/org/hibernate/orm/test/procedure/NumericParameterTypeTests.java
https://hibernate.atlassian.net/browse/HHH-16917
> HHH-16917 - Number not allowed as type for procedure query parameter

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/test/version/DetachedEntityWithNullVersionTest.java
https://hibernate.atlassian.net/browse/HHH-16586
> HHH-16586 When merging a persisted entity with a null Version, Hibernate treats entity as transient instead of throwing an Exception

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/AbstractBatchEntitySelectFetchInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batch/EmbeddableAndFetchModeSelectTest.java
https://hibernate.atlassian.net/browse/HHH-16811
> HHH-16811 Dirty property lost and not detected with Batch Fetch, Embedded and FetchMode SELECT

- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/DeleteCoordinator.java
- hibernate-core/src/main/java/org/hibernate/sql/model/ast/builder/RestrictedTableMutationBuilder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/locking/CompositeIdBatchDeletionTest.java
https://hibernate.atlassian.net/browse/HHH-16810
> HHH-16810 Fail to delete entity with a composite id using an @IdClass with one of its fields mapped from the id of a @ManyToOne association

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/CriteriaFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/IdFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/NaturalIdFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/QueryMethod.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/hqlsql/Book.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/hqlsql/Dao.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/hqlsql/Publisher.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/hqlsql/QueryMethodTest.java
this sounds a bit crazy but why not?
> path expressions in finder method parameter names

- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/EntityJavaType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/remove/RemoveAndOrderUpdateTest.java
https://hibernate.atlassian.net/browse/HHH-16923
> HHH-16923 Deleting all entities of a given type fails when using a composite primary key and order_updates

- .github/hibernate-github-bot.yml
https://hibernate.atlassian.net/browse/HHH-16850
> HHH-16850 Enable Hibernate GitHub Bot automatic Jira linking functionality

- hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesResultSetImpl.java
https://hibernate.atlassian.net/browse/HHH-16790
> HHH-16790 Performance issue when retrieving a large bulk of entity in bidirectionnal association

- settings.gradle
https://hibernate.atlassian.net/browse/HHH-16947
> HHH-16947 Upgrade to Narayana 7.0.0.Final

- local-build-plugins/build.gradle
https://hibernate.atlassian.net/browse/HHH-16950
> HHH-16950 - Upgrade the local-build-plugins Jandex version to 3.1.2

- gradle/java-module.gradle
- hibernate-core/src/main/java/org/hibernate/HibernateException.java
- hibernate-core/src/main/java/org/hibernate/jdbc/BatchFailedException.java
- hibernate-core/src/main/java/org/hibernate/jdbc/WorkExecutor.java
Added org.hibernate.jdbc
Nullified org.hibernate.HibernateException
https://hibernate.atlassian.net/browse/HHH-16515
> HHH-16515 - Nullability work

- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmPath.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/CriteriaToOneIdJoinTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/nestedfetch/NestedFetchTest.java
https://hibernate.atlassian.net/browse/HHH-16905
https://hibernate.atlassian.net/browse/HHH-16926
Backport of #6996
> HHH-16905, HHH-16926 Fix navigable path copy logic when identifiers are involved

- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/form/AbstractFormFetchDepthTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/form/FormFetchDepth0Test.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/form/FormFetchDepth1Test.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/form/FormFetchDepth2Test.java
https://hibernate.atlassian.net/browse/HHH-16871
> HHH-16871 Queries returning null values for related entities depending on 'max_fetch_depth'

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/FakeSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/SqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/BasicValuedPathInterpretation.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EmbeddableValuedPathInterpretation.java
- hibernate-core/src/test/java/org/hibernate/orm/test/set/SetOperationJpaCriteriaTest.java
https://hibernate.atlassian.net/browse/HHH-16754
> HHH-16754 unionAll with subquery orderby using path expression throws an error

- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/version/InheritanceVersionedParentTest.java
https://hibernate.atlassian.net/browse/HHH-16667
> HHH-16667 Hibernate 6 PrimaryKeyJoinColumn causes implicit version update to fail

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddedAttributeMapping.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddedIdentifierMappingImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/orderupdates/OrderUpdateNestedEmbeddedIdTest.java
https://hibernate.atlassian.net/browse/HHH-16709
> HHH-16709 @EmbeddedId Foreign key comparator throws NPE with order_updates enabled

- hibernate-core/src/main/java/org/hibernate/PropertySetterAccessException.java
- hibernate-core/src/main/java/org/hibernate/engine/internal/ManagedTypeHelper.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/EmbeddableWithParentWithInheritance2Test.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/EmbeddableWithParentWithInheritanceTest.java
https://hibernate.atlassian.net/browse/HHH-16812
> HHH-16812 StackOverflowError an embeddable's @Parent is a subclass in an inheritance tree

- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/nulliteral/EyeColor.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/nulliteral/NullLiteralExpression.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/nulliteral/Person.java
https://hibernate.atlassian.net/browse/HHH-16803
Backport of #6956
> HHH-16803 Setting value of enum type to null using nullLiteral: "Not a managed type" 

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractDomainPath.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/manytomany/ManyToManyOrderByJoinedInheritanceTest.java
https://hibernate.atlassian.net/browse/HHH-16837
> HHH-16837 UnknownTableReferenceException with @ManyToMany and @OrderBy and InheritenceType.JOINED

- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SqmPathRegistryImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/UnrelatedEntitiesTest.java
https://hibernate.atlassian.net/browse/HHH-15917
> HHH-15917 Unrelated Entity Join throws IllegalStateException

- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SqmPathRegistryImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/UnrelatedEntitiesTest.java
https://hibernate.atlassian.net/browse/HHH-15917
> HHH-15917 Unrelated Entity Join throws IllegalStateException #7027

- hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/index/IndexesOrderTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/uniqueconstraint/UniqueConstraintColumnOrderTest.java
https://hibernate.atlassian.net/browse/HHH-16943
https://hibernate.atlassian.net/browse/HHH-16953
> HHH-16943 Column ordering leads to wrong column order in unique constraints + HHH-16953 Hibernate doesn't observe column order on multicolumn indexes

- hibernate-core/src/main/java/org/hibernate/boot/model/relational/QualifiedNameParser.java
- hibernate-core/src/test/java/org/hibernate/orm/test/naming/QualifiedNameParserTests.java
https://hibernate.atlassian.net/browse/HHH-16765
> HHH-16765 - Cannot parse quoted table name

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/OneToOneSecondPass.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/ToOneBinder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/bidirectional/BidirectionalOneToOneWithIdClassesTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/bidirectional/BidirectionalOneToOneWithIdClassesUnownedAssociationTest.java
https://hibernate.atlassian.net/browse/HHH-16908
> HHH-16908 Fail to compute column mapping on entity with idClass having one field as pk of a OneToOne association

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/AbstractBatchEntitySelectFetchInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntityInsideEmbeddableSelectFetchInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntitySelectFetchInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchInitializeEntitySelectFetchInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/internal/InitializersList.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchEntityWithDisabledProxyTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchEntityWithSubselectFetchTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/batch/BatchEntityOneToManyTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/batch/BatchEntityOneToManyWithDisabledProxyTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/batch/BatchEntityWithSelectFetchTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/batch/BatchEntityWithSelectFetchWithDisableProxyTest.java
https://hibernate.atlassian.net/browse/HHH-16890
> HHH-16890 StackOverflowError when loading entities with @Proxy(lazy = false)

- hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java
This improves performance of cascadeLogicalOneToOneOrphanRemoval handling, because entity fields are only read by reflection if the field is actually a 1:1 relation (before the change, this was done every time for every field)
> HHH-16907 moved if from inside private method to around

- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/hqlsql/Dao.java
https://hibernate.atlassian.net/browse/HHH-16955
> HHH-16955 add test for query method generation with 'join fetch'

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractEntityCollectionPart.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/OneToManyMappedByJoinedInheritanceTest.java
https://hibernate.atlassian.net/browse/HHH-16860
> HHH-16860 OneToMany with inherited classes on both sides

- hibernate-core/src/test/java/org/hibernate/bytecode/spi/ByteCodeHelper.java
- https://hibernate.atlassian.net/browse/HHH-16965
> HHH-16965 ByteCodeHelper test utility might occasionally not read the full bytestream

- hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
- hibernate-core/src/main/java/org/hibernate/mapping/Component.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
- hibernate-core/src/main/java/org/hibernate/type/AbstractType.java
- hibernate-core/src/main/java/org/hibernate/type/ComponentType.java
- hibernate-core/src/main/java/org/hibernate/type/CompositeType.java
- hibernate-core/src/main/java/org/hibernate/type/EmbeddedComponentType.java
- hibernate-core/src/main/java/org/hibernate/type/TypeHelper.java
- hibernate-core/src/main/java/org/hibernate/type/UserComponentType.java
Importantly, introduces `UserComponentType`.
> some refactoring and cleanups

- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMeta.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/validation/ProcessorSessionFactory.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/validation/Validation.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/dao/Dao.java
> support optional 'from' in @HQL query method generation

- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/id/MultipleIdMapper.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/ToOneIdMapper.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/manytoone/lazy/ManyToOneLazyProxyTest.java
https://hibernate.atlassian.net/browse/HHH-14176
> HHH-14176 Handle embedded composite ids in envers specially to avoid lazy loading

- settings.gradle
https://hibernate.atlassian.net/browse/HHH-16971
> upgrade ByteBuddy to 1.12.23

- hibernate-platform/hibernate-platform.gradle
https://hibernate.atlassian.net/browse/HHH-16915
- since it is one of the published artifacts
> HHH-16915 Add community dialects to the platform

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
- hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderSingleKey.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiKeyLoadHelper.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/GeneratedValuesProcessor.java
- hibernate-core/src/main/java/org/hibernate/query/internal/DelegatingDomainQueryExecutionContext.java
- hibernate-core/src/main/java/org/hibernate/query/internal/QueryInterpretationCacheStandardImpl.java
- hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java
- hibernate-core/src/main/java/org/hibernate/query/spi/DomainQueryExecutionContext.java
- hibernate-core/src/main/java/org/hibernate/query/spi/QueryInterpretationCache.java
- hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmJdbcExecutionContextAdapter.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/internal/CallbackImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/internal/CallbackNoOp.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcSelectExecutorStandardImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/spi/Callback.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/spi/ExecutionContext.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/NestedRowProcessingState.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/internal/RowProcessingStateStandardImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchAndClassIdAndLazyCollectionTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchAndClassIdTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchAndEmbeddedIdId2Test.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchAndEmbeddedIdIdAndLazyCollectionTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchAndEmbeddedIdIdTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiLoadSubSelectCollectionDialectWithLimitTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/sqm/BaseSqmUnitTest.java
https://hibernate.atlassian.net/browse/HHH-16981
https://hibernate.atlassian.net/browse/HHH-16982
https://hibernate.atlassian.net/browse/HHH-16983
https://hibernate.atlassian.net/browse/HHH-16984
> Performance improvements

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java
- hibernate-core/src/test/java/org/hibernate/orm/test/merge/CompositeIdWithAssociationsAndGeneratedValuesMergeTest.java
- https://hibernate.atlassian.net/browse/HHH-16825
> HHH-16825 Cascading an entity with a composite key causes NullPointerException in AbstractClassJavaType.extractHashCode 

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java
- hibernate-core/src/test/java/org/hibernate/orm/test/merge/CompositeIdWithAssociationsAndGeneratedValuesMergeTest.java
https://hibernate.atlassian.net/browse/HHH-16825
> HHH-16825 Cascading an entity with a composite key causes NullPointerException in AbstractClassJavaType.extractHashCode

- hibernate-core/src/test/java/org/hibernate/orm/test/sql/exec/HqlUpdateExecutionTests.java
- hibernate-testing/src/main/java/org/hibernate/testing/orm/domain/gambit/EntityOfBasics.java
https://hibernate.atlassian.net/browse/HHH-15939
> HHH-15939 test for fixed issue

- gradle/wrapper/gradle-wrapper.properties
https://hibernate.atlassian.net/browse/HHH-15824
> HHH-15824 Upgrade to Gradle 7.6.2

- hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java
- hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
- hibernate-core/src/main/java/org/hibernate/sql/Template.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/CheckConstraintsTest.java
https://hibernate.atlassian.net/browse/HHH-16895 @check constraint not generated when annotated on entity
> HHH-16895 @Check constraint not generated when annotated on entity

- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/AbstractMutationCoordinator.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/DeleteCoordinator.java
- hibernate-core/src/main/java/org/hibernate/sql/model/ast/ColumnValueBinding.java
- hibernate-core/src/main/java/org/hibernate/sql/model/ast/ColumnValueBindingList.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/NestedEmbeddableWithLockingDeletionTest.java
https://hibernate.atlassian.net/browse/HHH-16959
> HHH-16959 Fail to batch delete entities with nested embeddeds

- hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java
- hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
- hibernate-core/src/main/java/org/hibernate/sql/Template.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/CheckConstraintsTest.java
- https://hibernate.atlassian.net/browse/HHH-16895 @Check constraint not generated when annotated on entity
> HHH-16895 @Check constraint not generated when annotated on entity  

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializerBuilder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchEntityWithDisabledProxyTest.java
https://hibernate.atlassian.net/browse/HHH-16966
> HHH-16966 StackOverFlowError with @ManyToOne and @Proxy( lazy=false )

- hibernate-core/src/test/java/org/hibernate/orm/test/locking/RemoveEntityTest.java
https://hibernate.atlassian.net/browse/HHH-16816 
this should have been fixed by https://hibernate.atlassian.net/browse/HHH-16959
> HHH-16816 Hibernate 6.2 could not execute certain delete statements 

- gradle/java-module.gradle
Add more info to the Gradle logging , useful with github failures
> Gradle add test logging exceptionFormat = 'full'

- hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/util/collections/EmptyReadOnlyMap.java
- hibernate-core/src/main/java/org/hibernate/internal/util/collections/MapBackedClassValue.java
- hibernate-core/src/main/java/org/hibernate/internal/util/collections/ReadOnlyMap.java
- hibernate-core/src/main/java/org/hibernate/jpa/event/internal/CallbackRegistryImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/registry/classloading/ClassLoaderLeakDetector.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/registry/classloading/ClassLoaderLeaksUtilityTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/registry/classloading/HibernateCallbacksTestAction.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/registry/classloading/HibernateClassLoaderLeaksTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/registry/classloading/HibernateLoadingTestAction.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/registry/classloading/IsolatedClassLoader.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/registry/classloading/LeakUtilitySelfTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/registry/classloading/LeakingTestAction.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/registry/classloading/NotLeakingTestAction.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/registry/classloading/PhantomReferenceLeakDetector.java
Introducing some little helpers to conveniently verify that certain operations won't leak objects, with some additional tools focusing on not leaking the classloader.
Related to:
https://hibernate.atlassian.net/browse/HHH-16911
> Classloader leak detection utility for tests

- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/registry/classloading/ClassLoaderLeakDetector.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/registry/classloading/ClassLoaderLeaksUtilityTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/registry/classloading/PhantomReferenceLeakDetector.java
We're unnecessarily waiting for 3 full minutes during this test, sorry all.
https://hibernate.atlassian.net/browse/HHH-16911
> HHH-16911 Don't wait for 3m in the self-test of ClassLoaderLeaksUtilityTest

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacySqlAstTranslator.java
https://hibernate.atlassian.net/browse/HHH-17016
backport for https://github.com/hibernate/hibernate-orm/pull/7100
> HHH-17016 [Backport to 6.2] Cast to the correct MySQL dialect

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacySqlAstTranslator.java
https://hibernate.atlassian.net/browse/HHH-17016
> HHH-17016 Cast to the correct MySQL dialect

- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedEntityJoin.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/CorrelatedListJoinInSubqueryTest.java
https://hibernate.atlassian.net/browse/HHH-16888
> HHH-16888 Left join with exists subquery adds extra join

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/NonAggregatedIdentifierMappingImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/cid/Flight.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/cid/FlightSegment.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/cid/FlightSegmentConfiguration.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/cid/FlightSegmentConfigurationId.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/cid/FlightSegmentId.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/cid/Freight.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/cid/HierarchicalCompositeIdLazyTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/cid/HierarchicalCompositeIdMaxDepthTest.java
https://hibernate.atlassian.net/browse/HHH-16766
> HHH-16766: Load lazy hierarchical IdClass entities

- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/usertypes/UserTypeFunctionsTest.java
https://hibernate.atlassian.net/browse/HHH-16751
Adding a test only as the issue is already fixed on main.
> HHH-16751 Unable to use SQL functions on UserType attribute

- hibernate-core/src/main/java/org/hibernate/id/enhanced/HiLoOptimizer.java
- hibernate-core/src/main/java/org/hibernate/id/enhanced/LegacyHiLoAlgorithmOptimizer.java
- hibernate-core/src/main/java/org/hibernate/id/enhanced/PooledLoOptimizer.java
- hibernate-core/src/main/java/org/hibernate/id/enhanced/PooledOptimizer.java
When using virtual threads, holding a monitor lock when performing an I/O _pins_ the carrier thread. 
To work around this behavior, this PR replaces the monitor lock with a ReentrantLock, supported by the virtual threads (no pinning).
I've successfully tested the change in a Quarkus application (by cherry-picking the change in the 6.2 branch). The pinning disappeared. It allows having a simple (but complete) CRUD application using Hibernate from virtual threads without having any issues.
https://hibernate.atlassian.net/browse/HHH-17005
> HHH-17005 - Replace monitor with a Java lock to avoid pinning 

- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/NonAggregatedCompositeSimplePath.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmAnyValuedSimplePath.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmBasicValuedSimplePath.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmEmbeddedValuedSimplePath.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmEntityValuedSimplePath.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmPluralValuedSimplePath.java
- hibernate-core/src/test/java/org/hibernate/orm/test/persister/entity/JoinedInheritanceImplicitJoinTest.java
https://hibernate.atlassian.net/browse/HHH-16979
> [HHH-16979] Fix subclasses being skipped on generated joins.

- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
https://hibernate.atlassian.net/browse/HHH-16694
> HHH-16694 Generated enum columns should respect the enum's intended order

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/callbacks/PostLoadLazyListenerTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/callbacks/PreUpdateBytecodeEnhancementTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/callbacks/PostLoadLazyListenerTest.java
https://hibernate.atlassian.net/browse/HHH-17019
> HHH-17019 EntityListener is not triggered for a LAZY loaded association

- hibernate-core/src/main/java/org/hibernate/dialect/function/IntegralTimestampaddFunction.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/TypecheckUtil.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/LiteralTests.java
https://hibernate.atlassian.net/browse/HHH-16737
> HHH-16737 Parse non-type-suffixed number literals as types that fit the number value

- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/LobSchemaUpdateTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/LocalDateTimeAndEnumSchemaUpdateTest.java
https://hibernate.atlassian.net/browse/HHH-17011
The issue has been fixed by https://hibernate.atlassian.net/browse/HHH-16360
https://hibernate.atlassian.net/browse/HHH-16762
> HHH-17011 The ddl is applied every time the application starts, even if the table structure has not changed.

- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AbstractPluralAttribute.java
- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EmbeddedSqmPathSource.java
- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/SingularAttributeImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/spi/SqmCreationHelper.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedBagJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedCrossJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedEntityJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedListJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedMapJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedPluralPartJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedSetJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedSimplePath.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedSingularJoin.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/EmbeddableAscDescQueryTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/NestedAssociationEmbeddableTest.java
Backport of https://github.com/hibernate/hibernate-orm/pull/7110
https://hibernate.atlassian.net/browse/HHH-16901
https://hibernate.atlassian.net/browse/HHH-16997
> HHH-16997 HHH-16901 Fix detection of isPartOfKey for embeddable initializers

- hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schematools/EnumCheckColumnDefinitionTests.java
https://hibernate.atlassian.net/browse/HHH-16670
> HHH-16670 Ensure columnDefinition has precedence over specialized type declaration

- hibernate-core/src/main/java/org/hibernate/type/ComponentType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/ParentCacheTest.java
https://hibernate.atlassian.net/browse/HHH-16879
> HHH-16879 Inconsistent @Parent behavior if cache is enabled

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/associations/any/AnyBidirectionalTest.java
https://hibernate.atlassian.net/browse/HHH-16919
> HHH-16919 Bidirectional mapping with @Any causes infinite loop on fetch

- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractNaturalIdLoader.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/naturalid/LoadByNaturalIdTest.java
https://hibernate.atlassian.net/browse/HHH-16968
> HHH-16968 StackOverflowError when using NaturalIdLoadAccess and bi-directional association

- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderStandardImpl.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
Make it possible to override the SingleIdLoadPlan
and the SingleIdEntityLoader.
https://hibernate.atlassian.net/browse/HHH-17037
> HHH-17037 Changes for Hibernate Reactive

- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractManagedType.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmPath.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/CorrelatedPluralJoinInheritanceTest.java
https://hibernate.atlassian.net/browse/HHH-16988
> HHH-16988 AssertionError in AbstractSqmPath.copyTo when using subquery correlated to root with more than 1 level in the class hierarchy

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/TableGroup.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/EntityJoinTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/ImplicitJoinInOnClauseTest.java
https://hibernate.atlassian.net/browse/HHH-17033
> HHH-17033 Fix invalid SQL being generated for implicit join in entity join on clause

- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/DirtyCheckingWithEmbeddableAndNonVisibleGenericMappedSuperclassTest.java
https://hibernate.atlassian.net/browse/HHH-16832
> HHH-16832 Follow-up: add missing test annotation

- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaTruncatorImpl.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardTableCleaner.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/instantiation/InstantiationWithCollectionTest.java
https://hibernate.atlassian.net/browse/HHH-17046
> add a test for implicit collection joins in 'select' clause

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/ClassPropertyHolder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/component/genericinheritance/EmbeddableGenericsAndInterfaceTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/component/genericinheritance/ExampleEmbedded.java
- hibernate-core/src/test/java/org/hibernate/orm/test/component/genericinheritance/ExampleEntity.java
- hibernate-core/src/test/java/org/hibernate/orm/test/component/genericinheritance/ExampleSuperClassEmbedded.java
- hibernate-core/src/test/java/org/hibernate/orm/test/component/genericinheritance/UserEntity.java
https://hibernate.atlassian.net/browse/HHH-16755
> HHH-16755 NPE while retrieving static metamodel attribute of generic embeddable extending a superclass

- hibernate-core/src/main/java/org/hibernate/mapping/Any.java
- hibernate-core/src/main/java/org/hibernate/mapping/Collection.java
- hibernate-core/src/main/java/org/hibernate/mapping/Component.java
- hibernate-core/src/main/java/org/hibernate/mapping/MappingHelper.java
- hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
- hibernate-core/src/main/java/org/hibernate/mapping/Value.java
- hibernate-core/src/test/java/org/hibernate/orm/test/any/annotations/AnyOnExistingColumnsTest.java
https://hibernate.atlassian.net/browse/HHH-16918
> HHH-16918 Can't use the the primary id column as the joincolumn for @Any association

- settings.gradle
https://hibernate.atlassian.net/browse/HHH-17066
> Upgrade to H2 2.2.220

- settings.gradle
- https://hibernate.atlassian.net/browse/HHH-17066
> HHH-17066 Upgrade H2 to version 2.2.220

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/LeftJoinFetchSubclassesTest.java
https://hibernate.atlassian.net/browse/HHH-16798
> HHH-16798 ClassCastException in Hibernate 6 when "join fetch" is used in a query with entity inheritance

- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/ElementCollectionLeftJoinSubqueryTest.java
https://hibernate.atlassian.net/browse/HHH-16928
Test only, already fixed by #7103
> HHH-16928 Subquery in 'where' clause causes additional 'join' creation in SQM

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/EnhancementAsProxyLazinessInterceptor.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/DynamicUpdateTest.java
https://hibernate.atlassian.net/browse/HHH-16577
> HHH-16577 Bytecode enhancement and @DynamicUpdate causes Index Out of Bound Exception

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/AbstractUpdateOrDeleteStatement.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/delete/DeleteStatement.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/update/UpdateStatement.java
- hibernate-core/src/test/java/org/hibernate/orm/test/notfound/MutationQueriesAndNotFoundActionTest.java
https://hibernate.atlassian.net/browse/HHH-16878
> HHH-16878 Invalid SQL generated for mutation when using association with @NotFound

- hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnyBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/OneToOneSecondPass.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/OptionalDeterminationSecondPass.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/ToOneBinder.java
- hibernate-core/src/main/java/org/hibernate/mapping/ManyToOne.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/TableReferenceJoin.java
- hibernate-core/src/main/java/org/hibernate/type/ComponentType.java
- hibernate-core/src/main/java/org/hibernate/type/TypeHelper.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/bidirectional/BidirectionalOneToOneWithIdClassesTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/bidirectional/BidirectionalOneToOneWithIdClassesUnownedAssociationTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/sql/exec/onetoone/bidirectional/EntityWithBidirectionalAssociationsOneOfWhichIsAJoinTableTest.java
- hibernate-core/src/test/java17/org/hibernate/orm/test/records/MergeRecordPropertyTestCase.java
Also had to backport the fix for https://hibernate.atlassian.net/browse/HHH-16908 to be able to backport https://hibernate.atlassian.net/browse/HHH-16759
> HHH-16759 merge fails when entity has an embedded java record transient

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
https://hibernate.atlassian.net/browse/HHH-17074
> HHH-17074 Type inference in duration arithmetic is wrong

- hibernate-core/src/main/java/org/hibernate/sql/exec/spi/JdbcOperationQuerySelect.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/LimitExpressionTest.java
https://hibernate.atlassian.net/browse/HHH-17004
> HHH-17004 - Add test and fix for issue

- hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/functional/cache/SQLFunctionsInterSystemsTest.java
- hibernate-core/src/main/java/org/hibernate/internal/FetchingScrollableResultsImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/ScrollableResultsImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/spi/ScrollableResultsConsumer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batchfetch/EagerManyToOneStreamTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batchfetch/LazyManyToOneStreamTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/FetchGraphTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/connections/AggressiveReleaseTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/connections/ConnectionManagementTestCase.java
- hibernate-core/src/test/java/org/hibernate/orm/test/hql/ASTParserLoadingTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/hql/HQLTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/hql/ScrollableCollectionFetchingTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/internal/util/ScrollableResultsObjectArrayCastingTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/iterate/ScrollTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/joinedsubclassbatch/IdentityJoinedSubclassBatchingTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/joinedsubclassbatch/JoinedSubclassBatchingTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/joinedsubclassbatch/SequenceJoinedSubclassBatchingTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/CriteriaCompilingTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/fetchscroll/CriteriaToScrollableResultsFetchTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/procedure/internal/ProcedureCallImplTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/results/ImplicitSelectWithJoinTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/returns/ScrollableResultsTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/readonly/ReadOnlySessionTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/readonly/ReadOnlyTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/resulttransformer/ResultTransformerTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/stateless/StatelessSessionTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/stateless/fetching/StatelessSessionFetchingTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/stream/basic/JpaStreamTest.java
Fix the memory leak but also improve tests a bit to avoid a possible leak.
https://hibernate.atlassian.net/browse/HHH-17078
> HHH-17078 Register/Deregister load context on every scroll operation

- hibernate-core/src/main/java/org/hibernate/boot/SessionFactoryBuilder.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryBuilder.java
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
https://hibernate.atlassian.net/browse/HHH-17086
a backport of https://github.com/hibernate/hibernate-orm/pull/7185
> [Backport to 6.2] HHH-17086 Make JSON/XML format mappers modifiable in SessionFactoryOptionsBuilder

- hibernate-core/src/main/java/org/hibernate/dialect/lock/PessimisticForceIncrementLockingStrategy.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultPostLoadEventListener.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderHelper.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinator.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchSelectAndForceIncrementVersionTest.java
https://hibernate.atlassian.net/browse/HHH-16939
> HHH-16939 Optimistic and Pessimistic Force Increment Update Statements are not committed when using a batch

- hibernate-core/src/main/java/org/hibernate/type/format/jackson/JacksonJsonFormatMapper.java
https://hibernate.atlassian.net/browse/HHH-17098
> HHH-17098 Auto-discover ObjectMapper modules for JacksonJsonFormatMapper

- hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/ClassPropertyHolder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionPropertyHolder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/ColumnsBuilder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/ComponentPropertyHolder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/ImplicitToOneJoinTableSecondPass.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyHolder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/TableBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/ToOneBinder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/associations/ManyToOneJoinTableTest.java
https://hibernate.atlassian.net/browse/HHH-16583
https://hibernate.atlassian.net/browse/HHH-15629
> HHH-15629, HHH-16583 fix @ManyToOne @JoinTable with defaulted name

- hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/IndexHolder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/TableBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/UniqueConstraintHolder.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/InFlightMetadataCollector.java
- hibernate-core/src/main/java/org/hibernate/dialect/unique/AlterTableUniqueIndexDelegate.java
- hibernate-core/src/main/java/org/hibernate/mapping/Column.java
- hibernate-core/src/main/java/org/hibernate/mapping/Constraint.java
- hibernate-core/src/main/java/org/hibernate/mapping/Formula.java
- hibernate-core/src/main/java/org/hibernate/mapping/Index.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardIndexExporter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/uniqueconstraint/UniqueConstraintValidationTest.java
https://hibernate.atlassian.net/browse/HHH-17103
> HHH-17103 allow SQL expressions in @Index(columnList)

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/internal/CapacityDependentDdlType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/internal/DdlTypeImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
https://hibernate.atlassian.net/browse/HHH-16989
> HHH-16989 fix 'cast(string as String(10))' on MySQL

- documentation/src/main/asciidoc/userguide/appendices/Annotations.adoc
@CompositeType, @CompositeTypeRegistration and @CompositeTypeRegistrations
https://hibernate.atlassian.net/browse/HHH-17107
> HHH-17107 - Add missing annotation to user guide annotation section

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/AbstractImmediateCollectionInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/orphan/onetomany/embedded/OneToManyInEmbeddedTest.java
https://hibernate.atlassian.net/browse/HHH-16970
> HHH-16970 Orphan removal not working in @Embeddable for FetchType.EAGER collections

- documentation/src/main/asciidoc/querylanguage/Expressions.adoc
- hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/HibernateCriteriaBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/spi/HibernateCriteriaBuilderDelegate.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/NodeBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/TypecheckUtil.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/ExpressionsTest.java
https://hibernate.atlassian.net/browse/HHH-17109
https://hibernate.atlassian.net/browse/HHH-16891
> HHH-16891, HHH-17109 better typechecking of HQL arithmetic expressions, criteria support for date/times

- hibernate-core/src/main/java/org/hibernate/boot/internal/NamedProcedureCallDefinitionImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/results/ResultSetMapping.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
https://hibernate.atlassian.net/browse/HHH-17115
> HHH-17115 Resolve type pollution problems on lookup of JdbcValuesMappingProducerProvider

- hibernate-core/src/main/java/org/hibernate/boot/internal/NamedProcedureCallDefinitionImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/results/ResultSetMapping.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
backport for https://hibernate.atlassian.net/browse/HHH-17115
> HHH-17115 / 6.2

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityMappingType.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ModelPart.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
https://hibernate.atlassian.net/browse/HHH-17119
> HHH-17119 Avoid type pollution when casting ModelPart to EntityMappingType

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityMappingType.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ModelPart.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
Avoid type pollution when casting ModelPart to EntityMappingType
- https://hibernate.atlassian.net/browse/HHH-17119
> HHH-17119 / 6.2

- hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java
- hibernate-core/src/main/java/org/hibernate/jpa/event/spi/CallbackRegistry.java
See https://hibernate.atlassian.net/browse/HHH-17122 and https://github.com/jakartaee/persistence/issues/133
> make generated id available in @PrePersist callbacks

- hibernate-core/src/main/java/org/hibernate/sql/results/internal/SqlSelectionImpl.java
https://hibernate.atlassian.net/browse/HHH-17123
> HHH-17123 Avoid type cast to SqlExpressible in SqlSelectionImpl

- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
backport of #7224
https://hibernate.atlassian.net/browse/HHH-17124
> HHH-17124 Avoid type pollution in SqmUtil checking for parameters being of type Bindable

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EmbeddableMappingType.java
- hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleEmbeddableValuedModelPart.java
- hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleEmbeddedEntityIdentifierMapping.java
- hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleNonAggregatedEntityIdentifierMapping.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/AbstractFetchParent.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/AggregateEmbeddableFetchImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/AggregateEmbeddableResultImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableExpressionResultImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableFetchImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableForeignKeyResultImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableResultImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityResultGraphNode.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractNonLazyEntityFetch.java
https://hibernate.atlassian.net/browse/HHH-17126
> HHH-17126 Improve type narrowing in signatures of AbstractFetchParent and EmbeddableMappingType

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EmbeddableMappingType.java
- hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleEmbeddableValuedModelPart.java
- hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleEmbeddedEntityIdentifierMapping.java
- hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleNonAggregatedEntityIdentifierMapping.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/AbstractFetchParent.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/AggregateEmbeddableFetchImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/AggregateEmbeddableResultImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableExpressionResultImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableFetchImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableForeignKeyResultImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableResultImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityResultGraphNode.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractNonLazyEntityFetch.java
https://hibernate.atlassian.net/browse/HHH-17126
> HHH-17126 Improve type narrowing in signatures of AbstractFetchParent and EmbeddableMappingType / 6.2

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/ConvertedEmbeddableCollectionTest.java
https://hibernate.atlassian.net/browse/HHH-17071
> HHH-17071 Basic Collection of 'Converted' Embeddables stopped working with 6.2

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/ByteBuddyEnhancementContext.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/FieldAccessEnhancer.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/PersistentAttributeTransformer.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/DefaultEnhancementContext.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/EnhancementContext.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/EnhancementContextWrapper.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/Enhancer.java
- hibernate-core/src/main/java/org/hibernate/bytecode/spi/ClassTransformer.java
- hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/ParsedPersistenceXmlDescriptor.java
- hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/PersistenceUnitInfoDescriptor.java
- hibernate-core/src/main/java/org/hibernate/jpa/boot/spi/PersistenceUnitDescriptor.java
- hibernate-core/src/main/java/org/hibernate/jpa/internal/enhance/EnhancingClassTransformerImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/DirtyTrackingEmbeddableTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/exceptionhandling/BaseJpaOrNativeBootstrapFunctionalTestCase.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/BaseEntityManagerFunctionalTestCase.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/xml/versions/JpaXsdVersionsTest.java
- hibernate-testing/src/main/java/org/hibernate/testing/orm/jpa/PersistenceUnitDescriptorAdapter.java
- hibernate-testing/src/main/java/org/hibernate/testing/orm/jpa/PersistenceUnitInfoAdapter.java
- hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/EntityManagerFactoryBasedFunctionalTest.java
- hibernate-testing/src/main/java/org/hibernate/testing/util/jpa/DelegatingPersistenceUnitInfo.java
- hibernate-testing/src/main/java/org/hibernate/testing/util/jpa/PersistenceUnitInfoPropertiesWrapper.java
- tooling/hibernate-ant/src/main/java/org/hibernate/tool/enhance/EnhancementTask.java
- tooling/hibernate-enhance-maven-plugin/src/main/java/org/hibernate/orm/tooling/maven/MavenEnhancePlugin.java
- tooling/hibernate-gradle-plugin/src/main/java/org/hibernate/orm/tooling/gradle/enhance/EnhancementHelper.java
https://hibernate.atlassian.net/browse/HHH-16952
> HHH-16952 Don't treat fields as enhanced when composite type has no @Embeddable

- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchJoinedImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityJoinedFetchInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/rowid/RowIdUpdateTest.java
https://hibernate.atlassian.net/browse/HHH-17045
> HHH-17045 Unable to locate parameter for RESTRICT - UPDATE error when updating entity with RowId

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java
- hibernate-core/src/test/java/org/hibernate/orm/test/associations/any/AnyTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/associations/any/PropertyHolder2.java
https://hibernate.atlassian.net/browse/HHH-16938
> HHH-16938 Meta annotation @AnyDiscriminatorValue does not work

- hibernate-core/src/main/java/org/hibernate/annotations/Any.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnyBinder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/any/annotations/AnyNullabilityTest.java
https://hibernate.atlassian.net/browse/HHH-16937
> HHH-16937 Persisting entity with nullable @Any field throws “not-null property references a null or transient value”

- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/CriteriaQualifiedJoinTest.java
https://hibernate.atlassian.net/browse/HHH-17116
> HHH-17116 Fix test adding missing dialect feature checks

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/ByteBuddyEnhancementContext.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/DirtyTrackingEmbeddableTest.java
https://hibernate.atlassian.net/browse/HHH-16952
> HHH-16952 Disable enhancement expectation for attributes annotated with @Embedded when the type is not annotated with @Embeddable

- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/singletable/SingleTableOneToOneTest.java
https://hibernate.atlassian.net/browse/HHH-16916
> HHH-16916 - Add test for issue

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaMultiselectGroupByAndOrderByTest.java
https://hibernate.atlassian.net/browse/HHH-17085
> HHH-17085 SQLGrammarException when selecting property of grouped join association in HyperSQL and PostgreSQL

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/fetchmode/toone/ManyToOneWithCircularity2Test.java
- hibernate-core/src/test/java/org/hibernate/orm/test/fetchmode/toone/ManyToOneWithCircularity3Test.java
- hibernate-core/src/test/java/org/hibernate/orm/test/fetchmode/toone/ManyToOneWithCircularityTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/DepthOneTest.java
https://hibernate.atlassian.net/browse/HHH-17064
> HHH-17064 Fetch mode select causes StackOverflowError if used together with fetch type lazy

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/fetchmode/toone/ManyToOneWithCircularity2Test.java
- hibernate-core/src/test/java/org/hibernate/orm/test/fetchmode/toone/ManyToOneWithCircularity3Test.java
- hibernate-core/src/test/java/org/hibernate/orm/test/fetchmode/toone/ManyToOneWithCircularityTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/DepthOneTest.java
https://hibernate.atlassian.net/browse/HHH-17064
> HHH-17064 Fetch mode select  causes StackOverflowError if used together with fetch type lazy

- documentation/src/main/asciidoc/introduction/Advanced.adoc
- documentation/src/main/asciidoc/introduction/Tuning.adoc
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/collectionelement/ordered/Person.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/emops/Competition.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/collections/custom/parameterized/Entity.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/manytomany/BasicWhereTest.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/onetomany/BasicWhereTest.java
https://hibernate.atlassian.net/browse/HHH-17158
> HHH-17158 detect incorrect use of @JoinColumn outside @JoinTable/@CollectionTable

- Jenkinsfile
- ci/build.sh
- docker_db.sh
- edb/edb11.Dockerfile
- edb/edb15.Dockerfile
- nightly.Jenkinsfile
https://hibernate.atlassian.net/browse/HHH-17087
> HHH-17087 Update container images to the latest version

- hibernate-core/src/main/java/org/hibernate/type/CustomType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/ContributedUserTypeTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/StringWrapperUserType.java
https://hibernate.atlassian.net/browse/HHH-17100
> HHH-17100 Fix CustomType to not call UserType#disassemble wrongly

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/dao/Dao.java
https://hibernate.atlassian.net/browse/HHH-17166
https://hibernate.atlassian.net/browse/HHH-17165
> HHH-17165, HHH-17166 fixes to query method generation

- hibernate-core/src/main/java/org/hibernate/NonUniqueObjectException.java
- hibernate-core/src/main/java/org/hibernate/Session.java
- hibernate-core/src/main/java/org/hibernate/internal/ExceptionConverterImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/ops/CreateTest.java
https://hibernate.atlassian.net/browse/HHH-17163
> HHH-17163 throw EntityExistsException as required by JPA spec

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/CountFunction.java
https://hibernate.atlassian.net/browse/HHH-16945
> HHH-16945 Cast to varbinary for tuple distinct count on SQL Server to avoid collation issues

- docker_db.sh
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
https://hibernate.atlassian.net/browse/HHH-17168
> HHH-17168 correct failures in FunctionTests for db2-10.5 and cockroachdb

- hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/StandardFunctionReturnTypeResolvers.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/JoinedCollectionMaxIdTest.java
https://hibernate.atlassian.net/browse/HHH-17104
> HHH-17104 Bug with max() request inside projection

- hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/BasicCollectionPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/OneToManyPersister.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SimpleDeleteQueryPlan.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/sql/model/ast/builder/TableDeleteBuilderStandard.java
- hibernate-core/src/main/java/org/hibernate/sql/model/ast/builder/TableUpdateBuilderStandard.java
- hibernate-core/src/main/java/org/hibernate/sql/model/internal/TableDeleteStandard.java
- hibernate-core/src/main/java/org/hibernate/sql/model/internal/TableUpdateStandard.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/manytomany/ManyToManySQLJoinTableRestrictionTest.java
https://hibernate.atlassian.net/browse/HHH-17105
> HHH-17105 Include custom sql restriction in join table mutation operations

- hibernate-core/src/main/java/org/hibernate/event/internal/AbstractFlushingEventListener.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchByUniqueKeyInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/ConstructorInitializationAndDynamicUpdateTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/ConstructorInitializationTest.java
https://hibernate.atlassian.net/browse/HHH-17049
> HHH-17049 Bytecode Enhancement, extra records created for associations created in constructor

- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/AbstractSqmParameter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/hql/ParameterIsNullTest.java
https://hibernate.atlassian.net/browse/HHH-15968
> HHH-15968 Consistent error when binding collection values to single-valued parameters

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/nulliteral/NullLiteralEntityConstructTest.java
https://hibernate.atlassian.net/browse/HHH-17135
> HHH-17135 CriteriaQuery error passing nullLiteral with entity type class

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/JPAXMLOverriddenAnnotationReader.java
- hibernate-core/src/test/java/org/hibernate/orm/test/boot/jaxb/mapping/HibernateOrmSpecificAttributesMappingTest.java
- hibernate-core/src/test/resources/xml/jaxb/mapping/partial/hibernate-orm-specific-attributes.xml
https://hibernate.atlassian.net/browse/HHH-17177
> HHH-17177 Convert the JDBC type code for an id attribute from XML into an annotation

- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SimpleDeleteQueryPlan.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/ConstructorInitializationAndDynamicUpdateTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/stream/NestedCollectionFetchStreamTest.java
https://hibernate.atlassian.net/browse/HHH-17049
https://hibernate.atlassian.net/browse/HHH-17105
https://hibernate.atlassian.net/browse/HHH-17131
> Test fixes for CI failures on several DBs

- hibernate-core/src/main/java/org/hibernate/query/hql/internal/QualifiedJoinPredicatePathConsumer.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SqmPathRegistryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SqmTreeCreationHelper.java
- hibernate-core/src/main/java/org/hibernate/query/hql/spi/SqmPathRegistry.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/JpaAliasBaselineTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/JpaAliasTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/JpaCrossJoinBaselineTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/JpaCrossJoinTests.java
Playing around with JPA interpretation of multiple query roots
https://hibernate.atlassian.net/browse/HHH-17171
> HHH-17171 - JPA and multiple query roots 

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/AbstractBatchEntitySelectFetchInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/association/OneToOnEnhancedEntityLoadedAsReferenceTest.java
https://hibernate.atlassian.net/browse/HHH-17173
> HHH-17173 Getting one-to-one association through a referenece to a bytecode enchanced entity fails 

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/AbstractBatchEntitySelectFetchInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/association/OneToOnEnhancedEntityLoadedAsReferenceTest.java
https://hibernate.atlassian.net/browse/HHH-17173
> HHH-17173 Getting one-to-one association through a referenece to a bytecode enchanced entity fails

- hibernate-core/src/main/java/org/hibernate/usertype/CompositeUserType.java
Based on the conversation in https://github.com/hibernate/hibernate-orm/pull/7203. Update the confusing comments.
https://hibernate.atlassian.net/browse/HHH-17053
> HHH-17053 Fix wrong order in comments

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/AggregateColumnAssignmentHandler.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/UpdateEntityWithIdClassAndJsonFieldTest.java
https://hibernate.atlassian.net/browse/HHH-17159
> HHH-17159 java.lang.StackOverflowError during Update on Entity with Embeddable and JSON

- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/ComponentAuditedPropertiesReader.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/components/mappedsuperclass/AbstractAuditedEmbeddable.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/components/mappedsuperclass/AuditedEmbeddableWithDeclaredData.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/components/mappedsuperclass/AuditedEmbeddableWithDeclaredDataTest.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/components/mappedsuperclass/AuditedEmbeddableWithNoDeclaredData.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/components/mappedsuperclass/AuditedEmbeddableWithNoDeclaredDataTest.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/components/mappedsuperclass/EntityWithAuditedEmbeddableWithDeclaredData.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/components/mappedsuperclass/EntityWithAuditedEmbeddableWithNoDeclaredData.java
https://hibernate.atlassian.net/browse/HHH-17189
> HHH-17189 Respect Audited annotations in component mapped super types

- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractCollectionBatchLoader.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionBatchLoaderArrayParam.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchAndClassIdCollectionTest.java
https://hibernate.atlassian.net/browse/HHH-17202
> HHH-17202 Fix ArrayStoreException for single field id class entity collection batch loading

- hibernate-core/src/main/java/org/hibernate/id/enhanced/TableGenerator.java
- hibernate-core/src/main/java/org/hibernate/id/enhanced/TableStructure.java
https://hibernate.atlassian.net/browse/HHH-17220
> HHH-17220 Avoid runtime lookups of JdbcService from TableGenerator and TableStructure

- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/subselect/SubselectAndSingleAttributeIdClassTest.java
https://hibernate.atlassian.net/browse/HHH-17221
> HHH-17221 AssertionError initializing a collection with FetchMode.SUBSELECT and IdClass having only one field

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/EmbeddableReusedColumnInheritanceTest.java
https://hibernate.atlassian.net/browse/HHH-17156
> HHH-17156 NPE when an Embeddable column is reused in another class related by inheritance

- hibernate-core/src/test/java/org/hibernate/test/resource/transaction/jdbc/autocommit/PostgreSQLSkipAutoCommitTest.java
https://hibernate.atlassian.net/browse/HHH-14676
https://issues.redhat.com/browse/JBEAP-22074
> [HHH-14676] PostgreSQLSkipAutoCommitTest ends up with a NPE on PostgreSQL Plus 13.1

- hibernate-envers/src/main/java/org/hibernate/envers/internal/revisioninfo/RevisionTimestampValueResolver.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/reventity/Custom.java
https://hibernate.atlassian.net/browse/HHH-17080
> HHH-17080 Fix LocalDateTime resolved value precision

- hibernate-core/src/test/java/org/hibernate/orm/test/collection/ElementCollectionSQLRestrictionTest.java
https://hibernate.atlassian.net/browse/HHH-17203
Test only, already fixed by #7283
> HHH-17203 ElementCollection doesn't consider @Where annotation on delete of elements

- checkerstubs/java.lang.astub
- checkerstubs/jboss.logging.astub
- gradle/java-module.gradle
- hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentCollection.java
- hibernate-core/src/main/java/org/hibernate/engine/query/spi/EntityGraphQueryHint.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/AssociationKey.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/BatchFetchQueue.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/CollectionEntry.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/CollectionKey.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/EffectiveEntityGraph.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/EntityKey.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/EntityUniqueKey.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/ExecutableList.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/ExecuteUpdateResultCheckStyle.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/FilterDefinition.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/IdentifierValue.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/LoadQueryInfluencers.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/PrimeAmongSecondarySupertypes.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionDelegatorBaseImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/TypedValue.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/UnsavedValueStrategy.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/VersionValue.java
- hibernate-core/src/main/java/org/hibernate/graph/spi/AppliedGraph.java
- hibernate-core/src/main/java/org/hibernate/internal/util/StringHelper.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ModelPart.java
- hibernate-core/src/main/java/org/hibernate/query/internal/QueryOptionsImpl.java
https://hibernate.atlassian.net/browse/HHH-16515
> HHH-16515 - Add o.h.engine.spi to nullness checking - WIP

- checkerstubs/javax.lang.astub
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/TypeUtils.java
https://hibernate.atlassian.net/browse/HHH-16515
> HHH-16515 - Get rid of nullness suppressions in jpamodelgen - WIP

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/singletable/SingleTableOneToOneTest.java
to single-table-inheritance subclass attributes
https://hibernate.atlassian.net/browse/HHH-17228
> HHH-17228 - apply the discriminator for 1-1 mappings

- hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java
- hibernate-core/src/test/java/org/hibernate/orm/test/readonly/ReadOnlyUserDefinedTest.java
https://hibernate.atlassian.net/browse/HHH-15317
> HHH-15317 - Add test for issue

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
https://hibernate.atlassian.net/browse/HHH-17240
> HHH-17240 Make ClassTransformer enhancement thread safe

- hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java
- hibernate-core/src/test/java/org/hibernate/orm/test/readonly/ReadOnlyUserDefinedTest.java
https://hibernate.atlassian.net/browse/HHH-15317
> HHH-15317 - Test and Fix for issue

- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/Compatibility.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/instantiation/InstantiationWithMultiplePrimitiveConstructorsTest.java
https://hibernate.atlassian.net/browse/HHH-17155
> HHH-17155 DynamicInstantiationResult wrong java type constructor selected

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/idclass/IdClassOneToOneTest.java
https://hibernate.atlassian.net/browse/HHH-17205
> HHH-17205 QueryException: could not resolve property: null on OneToOne with composite key

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/CompoundNaturalIdMapping.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/DomainResultAssembler.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/basic/BasicResultAssembler.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/EmbeddableInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/AbstractNonAggregatedIdentifierMappingInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableAssembler.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/querycache/QueryCacheExistingEntityInstanceTest.java
https://hibernate.atlassian.net/browse/HHH-17188
> HHH-17188 Query Cache contains null values when entity is found in Persistence Context

- hibernate-core/src/main/java/org/hibernate/persister/collection/BasicCollectionPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/OneToManyPersister.java
- hibernate-core/src/main/java/org/hibernate/sql/model/ast/builder/CollectionRowDeleteBuilder.java
- hibernate-core/src/main/java/org/hibernate/sql/model/ast/builder/CollectionRowDeleteByUpdateSetNullBuilder.java
- hibernate-core/src/main/java/org/hibernate/sql/model/ast/builder/TableDeleteBuilderStandard.java
- hibernate-core/src/main/java/org/hibernate/sql/model/ast/builder/TableUpdateBuilderStandard.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/collections/ElementCollectionCustomSqlMutationsTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/manytomany/ManyToManyCustomSqlMutationsTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/onetomany/OneToManyCustomSqlMutationsTest.java
https://hibernate.atlassian.net/browse/HHH-17170
> HHH-17170 Custom @SQLDelete, @SQLDeleteAll and @SQLUpdate not working on associated collections

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/BasicValuedPathInterpretation.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/MapManyToManyTreatJoinTest.java
https://hibernate.atlassian.net/browse/HHH-17255
> HHH-17255 Cannot resolve table reference for treated many-to-many map collection simple attribute

- documentation/src/main/asciidoc/userguide/chapters/domain/natural_id.adoc
- hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/naturalid/ValidationTests.java
https://hibernate.atlassian.net/browse/HHH-17197 - Add check for illegal combo of to-one + natural-id + not-found https://hibernate.atlassian.net/browse/HHH-17196 - Documentation for @NaturalId should be more explicit about non-nullability
> natural-id + not-found

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/graphs/EntityGraphTest.java
https://hibernate.atlassian.net/browse/HHH-17192
> HHH-17192 Register entity name usage for entity graph/fetch profile related join fetches

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/IndexBinder.java
- hibernate-core/src/main/java/org/hibernate/dialect/unique/CreateTableUniqueDelegate.java
- hibernate-core/src/main/java/org/hibernate/mapping/Table.java
- hibernate-core/src/main/java/org/hibernate/mapping/UniqueKey.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/naturalid/NaturalIdUniqueConstraintNameTest.java
https://hibernate.atlassian.net/browse/HHH-17132
> HHH-17132 Cleanse non-explicit unique keys with matching columns

- hibernate-core/src/main/java/org/hibernate/annotations/NaturalId.java
> mention that @NaturalId cannot be null in javadoc

- hibernate-core/src/main/java/org/hibernate/query/sqm/ComparisonOperator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/EntityUseJoinedSubclassOptimizationTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/EntityUseSingleTableOptimizationTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/EntityUseUnionSubclassOptimizationTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/NotEqualComparisonOperatorTest.java
Change the "!=" not equal operator to "<>"
https://hibernate.atlassian.net/browse/HHH-17234
> HHH-17234 - Add test case and fix for issue

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/ElementCollectionInitializationTest.java
https://hibernate.atlassian.net/browse/HHH-17256
> HHH-17256 Elementcollection embeddable contains only nulls when loading in multiple steps 

- hibernate-core/src/main/java/org/hibernate/collection/spi/AbstractPersistentCollection.java
- hibernate-core/src/main/java/org/hibernate/type/AnyType.java
- hibernate-core/src/main/java/org/hibernate/type/ComponentType.java
- hibernate-core/src/main/java/org/hibernate/type/CompositeType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/ElementCollectionAllNonOptionalPropertyUpdateTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/ElementCollectionNonOptionalPropertyUpdateTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/ElementCollectionOptionalPropertyUpdateTest.java
https://hibernate.atlassian.net/browse/HHH-17257
> HHH-17257 ElementCollection is missing elements after update if embeddable type has primitive columns marked as nullable

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/ElementCollectionInitializationTest.java
https://hibernate.atlassian.net/browse/HHH-17256
> HHH-17256 Elementcollection embeddable contains only nulls when loading in multiple steps

- hibernate-core/src/main/java/org/hibernate/boot/model/process/spi/MetadataBuildingProcess.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/customtype/DurationTest.java
https://hibernate.atlassian.net/browse/HHH-17243
> HHH-17243 - java.time.Duration handling in Envers

- hibernate-core/src/main/java/org/hibernate/boot/internal/BootstrapContextImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/InferredBasicValueResolver.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/BootstrapContext.java
- hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java
- hibernate-core/src/main/java/org/hibernate/type/BasicTypeRegistry.java
- hibernate-core/src/test/java/org/hibernate/orm/test/type/OverrideStandardJavaTypeTest.java
- hibernate-testing/src/main/java/org/hibernate/testing/boot/BootstrapContextImpl.java
https://hibernate.atlassian.net/browse/HHH-16781
> HHH-16781 @JavaType annotation is ignored when basic type is already registered for the preferred JdbcType

- hibernate-core/src/main/java/org/hibernate/metamodel/internal/AbstractCompositeIdentifierMapping.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/PluralAttributeMappingImpl.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/TableGroupJoinProducer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/EntityGraphAttributeNodesTest.java
https://hibernate.atlassian.net/browse/HHH-16885
> HHH-16885 Hibernate 6.x changes outer to inner join when @EntityGraph and @Id

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/BasicValuedPathInterpretation.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EmbeddableValuedPathInterpretation.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedBagJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedListJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedMapJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedSetJoin.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/TreatedPluralJoinIsNullTest.java
https://hibernate.atlassian.net/browse/HHH-17178
Backport of #7382
> HHH-17178 Is null predicate on treated plural path causes InterpretationException

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/EntityValuedInSubqueryGroupAndOrderTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaMultiselectGroupByAndOrderByTest.java
https://hibernate.atlassian.net/browse/HHH-17231
> HHH-17231 SQLGrammarException when selecting property of grouped join association in subquery

- hibernate-core/src/main/java/org/hibernate/sql/results/internal/InitializersList.java
- hibernate-core/src/main/java/org/hibernate/sql/results/internal/NavigablePathMapToInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/internal/ResultsHelper.java
https://hibernate.atlassian.net/browse/HHH-17282
> HHH-17282 Introduce a specialized Map for NavigablePath to Initializer

- documentation/src/main/asciidoc/introduction/Generator.adoc
- documentation/src/main/asciidoc/userguide/chapters/query/hql/Query.adoc
- documentation/src/main/asciidoc/userguide/chapters/tooling/extras/maven-example-metamodel.pom
- documentation/src/main/asciidoc/userguide/chapters/tooling/gradle.adoc
- documentation/src/main/asciidoc/userguide/chapters/tooling/maven.adoc
- documentation/src/main/asciidoc/userguide/chapters/tooling/modelgen.adoc
- migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-17157
> HHH-17157 - Some improvements to the metamodel generator documentation

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/ClassIdNativeQueryTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/CompositeIdNativeQueryTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/EmbeddedIdNativeQueryTest.java
https://hibernate.atlassian.net/browse/HHH-17108
> HHH-17108 Error In Native Query when adding two Entity's and using composite key. Error: Unable to find column position by name.

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/query/results/dynamic/DynamicFetchBuilderStandard.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/NativeQueryEagerAssociationTest.java
https://hibernate.atlassian.net/browse/HHH-17224
> HHH-17224 Hibernate 6.x - native queries for multiple entities do not respect FetchMode.EAGER annotation directives

- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/ExpressionsTest.java
https://hibernate.atlassian.net/browse/HHH-17223
> HHH-17223 Test fix for HANA

- hibernate-core/src/test/java/org/hibernate/dialect/DialectContextTest.java
- hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectContext.java
https://hibernate.atlassian.net/browse/HHH-17295
> HHH-17295 Change which constructor is looked-up in DialectContext test utils

- hibernate-core/src/main/java/org/hibernate/action/internal/EntityUpdateAction.java
Fix [HHH-17281](https://hibernate.atlassian.net/browse/HHH-17281)
[HHH-17281]: https://hibernate.atlassian.net/browse/HHH-17281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Make EntityUpdateAction#handleDeleted protected

- hibernate-jcache/src/test/java/org/hibernate/orm/test/caching/FirstLevelCacheTest.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/caching/NonStrictReadWriteCacheTest.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/caching/SecondLevelCacheTest.java
Closes [HHH-17284](https://hibernate.atlassian.net/browse/HHH-17284).
[HHH-17284]: https://hibernate.atlassian.net/browse/HHH-17284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HHH-17284 Fix indentation in caching tests/documentation

- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/script/SingleLineSqlScriptExtractor.java
- local-build-plugins/src/main/java/org/hibernate/orm/antlr/AntlrHelper.java
This PR uses try-with-resources to close reader / writer.
> Use try-with-resources to close reader / writer

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
- hibernate-core/src/test/java/org/hibernate/orm/test/type/OracleBigDecimalArrayTest.java
https://hibernate.atlassian.net/browse/HHH-17176
> HHH-17176 Map SDO_ORDINATE_ARRAY to BigDecimal[] for Oracle

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotationBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/annotations/AnnotationMetadataSourceProcessorImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/idclass/Helper.java
https://hibernate.atlassian.net/browse/HHH-17300
> HHH-17300 detect and throw exception for @Table annotation on @MappedSuperclass

- hibernate-core/src/main/java/org/hibernate/boot/archive/internal/ByteArrayInputStreamAccess.java
- hibernate-core/src/main/java/org/hibernate/boot/archive/internal/FileInputStreamAccess.java
- hibernate-core/src/main/java/org/hibernate/boot/archive/internal/UrlInputStreamAccess.java
- hibernate-core/src/main/java/org/hibernate/boot/archive/scan/internal/ClassDescriptorImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/archive/scan/internal/MappingFileDescriptorImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/archive/scan/internal/PackageDescriptorImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/archive/scan/internal/ScanResultImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/scanning/ScannerTest.java
https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues/HHH-16840
> HHH-16840 Allow serialization of ScanResultImpl

- documentation/src/main/asciidoc/introduction/Entities.adoc
https://hibernate.atlassian.net/browse/HHH-17304
> HHH-17304 Fix typos in Introduction guide

- hibernate-envers/src/main/java/org/hibernate/envers/AuditReader.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/RevisionInfoConfiguration.java
- hibernate-envers/src/main/java/org/hibernate/envers/exception/RevisionDoesNotExistException.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/RevisionTimestampData.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/reader/AuditReaderImpl.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/revisioninfo/RevisionInfoQueryCreator.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/revisioninfo/RevisionTimestampValueResolver.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/entities/reventity/CustomInstantRevEntity.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/reventity/CustomInstantRevEntityTest.java
https://hibernate.atlassian.net/browse/HHH-17139
> HHH-17139 Support Instant as revision timestamps

- hibernate-core/src/main/java/org/hibernate/dialect/sequence/MariaDBSequenceSupport.java
https://hibernate.atlassian.net/browse/HHH-17302
> HHH-17302 - Use nocache for MariaDB sequences

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
https://hibernate.atlassian.net/browse/HHH-17306
> HHH-17306 NPE in AbstractEntityPersister#logStaticSQL() when debug logging is enabled

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/DiscriminatedAssociationMapping.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/Fetch.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/FetchList.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/EagerCollectionFetch.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/AggregateEmbeddableFetchImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableFetchImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityResultGraphNode.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/EntityFetch.java
- hibernate-core/src/test/java/org/hibernate/orm/test/merge/MergeWithAssociatedCollectionAndCascadeTest.java
https://hibernate.atlassian.net/browse/HHH-17193
> HHH-17193 Error when merging entity with composite PK and nested to-many collection

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AnyDiscriminatorPart.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AnyKeyPart.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/DiscriminatedAssociationMapping.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddedForeignKeyDescriptor.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/AnyDiscriminatorPathInterpretation.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/DiscriminatedAssociationPathInterpretation.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/FromClause.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/TableGroup.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/VirtualTableGroup.java
- hibernate-core/src/test/java/org/hibernate/orm/test/any/annotations/AnyExplicitSelectTest.java
https://hibernate.atlassian.net/browse/HHH-17208
https://hibernate.atlassian.net/browse/HHH-17211
> HHH-17211 HHH-17208 Fixes for explicit `@Any` path selections

- documentation/src/main/asciidoc/userguide/chapters/schema/Schema.adoc
- hibernate-core/src/main/java/org/hibernate/boot/model/relational/ColumnOrderingStrategyStandard.java
- hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
- hibernate-core/src/main/java/org/hibernate/mapping/PrimaryKey.java
- hibernate-core/src/main/java/org/hibernate/mapping/Table.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/uniqueconstraint/CompositePrimaryKeyColumnOrderTest.java
https://hibernate.atlassian.net/browse/HHH-17065
https://hibernate.zulipchat.com/#narrow/stream/132096-hibernate-user/topic/Ordering.20columns.20of.20primary.20key
> [HHH-17065] Unique Index on PrimaryKey orders primary key columns

- settings.gradle
Jira-Issue: [https://hibernate.atlassian.net/browse/HHH-17153](https://hibernate.atlassian.net/browse/HHH-17153)
https://hibernate.atlassian.net/browse/HHH-17153
> HHH-17153: Upgrade antlr4 to version 4.13.0

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AnyDiscriminatorPart.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AnyKeyPart.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/DiscriminatedAssociationMapping.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddedForeignKeyDescriptor.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/AnyDiscriminatorPathInterpretation.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/BasicValuedPathInterpretation.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/DiscriminatedAssociationPathInterpretation.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EmbeddableValuedPathInterpretation.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/FromClause.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/TableGroup.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/VirtualTableGroup.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/Fetch.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/FetchList.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/EagerCollectionFetch.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/AggregateEmbeddableFetchImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableFetchImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityResultGraphNode.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/EntityFetch.java
- hibernate-core/src/test/java/org/hibernate/orm/test/any/annotations/AnyExplicitSelectTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/merge/MergeWithAssociatedCollectionAndCascadeTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/SelectForeignKeyWithMissingFromTest.java
https://hibernate.atlassian.net/browse/HHH-17225
https://hibernate.atlassian.net/browse/HHH-17208
https://hibernate.atlassian.net/browse/HHH-17193
https://hibernate.atlassian.net/browse/HHH-17211
> 6.3 Backports

- hibernate-core/src/main/java/org/hibernate/dialect/temptable/StandardTemporaryTableExporter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/LocalTemporaryTableMutationStrategyNoDropTest.java
https://hibernate.atlassian.net/browse/HHH-16486
> HHH-16486 StandardTemporaryTableExporter generates queries with the wrong parameter marker

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/JPAXMLOverriddenAnnotationReader.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/usertypes/xmlmapping/Account.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/usertypes/xmlmapping/AccountCurrencyUnit.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/usertypes/xmlmapping/CurrencyUnit.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/usertypes/xmlmapping/CurrencyUnitTypeDescriptor.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/usertypes/xmlmapping/CurrencyUnitUserType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/usertypes/xmlmapping/UserTypeTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/usertypes/xmlmapping/entities.xml
https://hibernate.atlassian.net/browse/HHH-17262
> HHH-17262 JdbcTypeRecommendationException when using <mapping-file> of persistence.xml file

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/JPAXMLOverriddenAnnotationReader.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/usertypes/xmlmapping/Account.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/usertypes/xmlmapping/AccountCurrencyUnit.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/usertypes/xmlmapping/CurrencyUnit.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/usertypes/xmlmapping/CurrencyUnitTypeDescriptor.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/usertypes/xmlmapping/CurrencyUnitUserType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/usertypes/xmlmapping/UserTypeTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/usertypes/xmlmapping/entities.xml
https://hibernate.atlassian.net/browse/HHH-17262
> HHH-17262 JdbcTypeRecommendationException when using <mapping-file> of persistence.xml file 

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/OneToOneSecondPass.java
- hibernate-core/src/main/java/org/hibernate/mapping/Component.java
- hibernate-core/src/test/java/org/hibernate/orm/test/idclass/IdClassWithOneToOneTest.java
https://hibernate.atlassian.net/browse/HHH-17288
> [HHH-17288] Reference primary key only if all properties match

- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityMappingType.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/PluralAttributeMapping.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/WhereRestrictable.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ManyToManyCollectionPart.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/PluralAttributeMappingImpl.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/CollectionTableGroup.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/ArrayInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/BagInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/ListInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/MapInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/SetInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchJoinedImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cfg/persister/GoofyPersisterClassProvider.java
- hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/CriteriaEntityGraphTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/EntityGraphLoadPlanBuilderTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/HqlEntityGraphTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ql/JoinTableOptimizationTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ql/MapIssueTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/CompareEntityValuedPathsTest.java
https://hibernate.atlassian.net/browse/HHH-16595
> HHH-16595 Optimize away nested table group joins when possible

- hibernate-core/src/main/java/org/hibernate/internal/NaturalIdMultiLoadAccessStandard.java
- hibernate-core/src/main/java/org/hibernate/query/spi/SelectQueryPlan.java
- hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeSelectQueryPlanImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/AggregatedSelectQueryPlanImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/spi/DelegatingSqmSelectionQueryImplementor.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/spi/SqmSelectionQueryImplementor.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcSelectExecutorStandardImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/spi/JdbcSelectExecutor.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/sqm/DelegatingSqmSelectionQueryImplementorTest.java
https://hibernate.atlassian.net/browse/HHH-17226
> HHH-17226 Generify result retrieval in JdbcSelectExecutor, SelectQueryPlan and SqmSelectionQuery

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/MapBinder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/collections/MapKeyToOneInEmbeddedIdTest.java
https://hibernate.atlassian.net/browse/HHH-17285
> HHH-17285 @MapdKey fails with name attribute that represetns a path with dots separator

- settings.gradle
https://hibernate.atlassian.net/browse/HHH-17331
> HHH-17331 Test against H2 2.2.224

- hibernate-c3p0/src/test/java/org/hibernate/test/c3p0/C3P0ConnectionProviderTest.java
- hibernate-c3p0/src/test/resources/hibernate.properties
- hibernate-envers/src/test/resources/hibernate.properties
- hibernate-jcache/src/test/resources/hibernate.properties
- hibernate-micrometer/src/test/resources/hibernate.properties
- hibernate-proxool/src/test/resources/hibernate.properties
- hibernate-spatial/src/test/resources/hibernate.properties
- hibernate-testing/src/test/resources/hibernate.properties
https://hibernate.atlassian.net/browse/HHH-17301
> HHH-17301 - Reduce amount of connections

- hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/model/TypeContributions.java
- hibernate-core/src/main/java/org/hibernate/boot/model/process/spi/MetadataBuildingProcess.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingMetadataBuildingOptions.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataBuildingOptions.java
- hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/ContributedUserTypeTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/MyCompositeValue.java
- hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/MyCompositeValueType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/MyCompositeValueTypeContributor.java
https://hibernate.atlassian.net/browse/HHH-17181
> HHH-17181 Cannot register `CompositeUserType` using `TypeContributions.contributeType`

- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/DomainType.java
- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EmbeddableTypeImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmAttributeJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmEmbeddedValuedSimplePath.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmExpression.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectableNode.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSubQuery.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/EmbeddedTupleSubqueryComparisonTest.java
https://hibernate.atlassian.net/browse/HHH-17283
> HHH-17283 Subquery using Entity with composite Id causes SemanticException

- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappingMetamodelImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/hql/InSubqueryPredicateAnonymousTupleTest.java
https://hibernate.atlassian.net/browse/HHH-17332
> HHH-17332 NullPointerException in TupleMappingModelExpressible constructor

- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/cfg/QuerySettings.java
- hibernate-core/src/main/java/org/hibernate/engine/query/internal/NativeQueryInterpreterStandardImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/query/spi/NativeQueryInterpreterInitiator.java
- hibernate-core/src/main/java/org/hibernate/engine/query/spi/ParamLocationRecognizer.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionDelegatorBaseImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
- hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sql/internal/ParameterParser.java
- hibernate-core/src/main/java/org/hibernate/query/sql/internal/ParameterRecognizerImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sql/spi/ParameterRecognizer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/NativeQueryParameterTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/ParameterParserTest.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/validation/MockSessionFactory.java
in native queries
https://hibernate.atlassian.net/browse/HHH-17314
> HHH-17314 - Add a configuration option to ignore jdbc parameters

- hibernate-core/src/main/java/org/hibernate/boot/model/process/spi/MetadataBuildingProcess.java
https://hibernate.atlassian.net/browse/HHH-17351
> HHH-17351 Add missing basic type registration after changing preferred jdbc type

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/querycache/QueryCacheExistingEntityInstanceTest.java
https://hibernate.atlassian.net/browse/HHH-17329
Backport of #7472
> HHH-17329 Query Cache contains null values when entity was loaded as proxy

- documentation/src/main/asciidoc/userguide/chapters/batch/Batching.adoc
- hibernate-core/src/main/java/org/hibernate/boot/registry/selector/internal/StrategySelectorBuilder.java
- hibernate-core/src/main/java/org/hibernate/cfg/SchemaToolingSettings.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/GlobalTemporaryTableStrategy.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/LocalTemporaryTableStrategy.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/PersistentTableStrategy.java
- hibernate-core/src/test/resources/hibernate.properties
- hibernate-micrometer/src/test/resources/hibernate.properties
- hibernate-testing/src/test/resources/hibernate.properties
https://hibernate.atlassian.net/browse/HHH-17162
> HHH-17162 - Polish SQM insert/mutation strategies

- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/superclass/auditparents/MultipleAuditParentsTest.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/superclass/auditparents/SingleAuditParentsTest.java
Fix typos in javadoc(SingleAuditParentsTest.java, MultipleAuditParentsTest.java)
https://hibernate.atlassian.net/browse/HHH-17340
> HHH-17340 Fix typos in javadoc

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2zLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/DB2iDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/DB2zDialect.java
https://hibernate.atlassian.net/browse/HHH-17344
> HHH-17344 - Fix potential NPE

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/ElementCollectionLazyToOneTest.java
https://hibernate.atlassian.net/browse/HHH-17383
> HHH-17383 Association is null in lazy initialized element collection

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java
- hibernate-core/src/main/java/org/hibernate/id/CompositeNestedGeneratedValueGenerator.java
- hibernate-core/src/main/java/org/hibernate/mapping/Component.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/identifier/EmbeddedIdGeneratedValueTest.java
- hibernate-core/src/test/java17/org/hibernate/orm/test/records/RecordEmbeddedIdGeneratedValueTest.java
https://hibernate.atlassian.net/browse/HHH-15074
> HHH-15074 Allow partial composite id generation for EmbeddedId

- documentation/src/main/asciidoc/quickstart/guides/obtaining.adoc
https://hibernate.atlassian.net/browse/HHH-17367
> HHH-17367 - Add links to the tutorial's example source code

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/TreatedSubclassSameTypeTest.java
https://hibernate.atlassian.net/browse/HHH-17299
> HHH-17299 AssertionError in DiscriminatorPathInterpretation when treating a path with the same subtype

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/HSQLLegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MaxDBDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/pagination/RowsLimitHandler.java
- hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/pagination/AbstractSimpleLimitHandler.java
- hibernate-core/src/main/java/org/hibernate/dialect/pagination/LimitLimitHandler.java
- hibernate-core/src/main/java/org/hibernate/dialect/pagination/LimitOffsetLimitHandler.java
- hibernate-core/src/main/java/org/hibernate/dialect/pagination/Oracle12LimitHandler.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/NativeQueryLimitOffsetTest.java
https://hibernate.atlassian.net/browse/HHH-17389
https://hibernate.atlassian.net/browse/HHH-17409
> HHH-17409 Support offset without limit in some LimitHandlers

- hibernate-core/src/test/java/org/hibernate/orm/test/cache/LazyOneToOneWithCollectionTest.java
https://hibernate.atlassian.net/browse/HHH-17289
Test only, the issue was already fixed by #7303
> HHH-17289 NonUniqueResultException for HQL single entity select by id with join fetch and caching

- migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-17089
> HHH-17089 - Add a link to the supported dialects report in the migration guide

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DerbyLegacySqlAstTranslator.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacySqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/DerbySqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/H2SqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/TableGroup.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mappedBy/IsNullAndMappedByTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/notfound/IsNullAndNotFoundTest.java
https://hibernate.atlassian.net/browse/HHH-17384
> HHH-17384 OneToMany association with @NotFound results in SQL with different JOIN-type for SELECT (LEFT JOIN) and COUNT (JOIN)

- hibernate-core/src/main/java/org/hibernate/query/criteria/CriteriaDefinition.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/JpaCriteriaQuery.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/SqmCopyContext.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmBagJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmListJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmMapJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmSetJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmSingularJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/AbstractSqmExpression.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmInListPredicate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectStatement.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/CountQueryTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/CriteriaExpressionAsValueTests.java
https://hibernate.atlassian.net/browse/HHH-17412
https://hibernate.atlassian.net/browse/HHH-17410
> HHH-17410 Support creating count query from existing query

- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/AbstractSqmExpression.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmInListPredicate.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/CriteriaExpressionAsValueTests.java
https://hibernate.atlassian.net/browse/HHH-17412
> HHH-17412 Special case SqmExpression passed as criteria value to help with surprising javac compiler choices

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DriverManagerConnectionProviderImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayAggregateTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayAppendTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayConcatTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayConstructorTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayContainsArrayTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayContainsTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayFillTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayGetTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayLengthTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayOverlapsTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayPositionTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayPositionsTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayPrependTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayRemoveIndexTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayRemoveTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayReplaceTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArraySetTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArraySliceTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayToStringTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayTrimTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/BasicCollectionMappingTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/type/OracleNestedTableTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/type/OracleSqlArrayTest.java
- hibernate-testing/src/main/java/org/hibernate/testing/jdbc/SharedDriverManagerConnectionProviderImpl.java
- hibernate-testing/src/main/java/org/hibernate/testing/jdbc/SharedDriverManagerTypeCacheClearingIntegrator.java
https://hibernate.atlassian.net/browse/HHH-17417
> HHH-17417 Workaround Oracle driver issue to reduce connection creation

- hibernate-core/src/main/java/org/hibernate/boot/query/SqlResultSetMappingDescriptor.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/CaseStatementDiscriminatorMappingImpl.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ExplicitColumnDiscriminatorMappingImpl.java
- hibernate-core/src/main/java/org/hibernate/query/internal/ResultMementoEntityJpa.java
- hibernate-core/src/main/java/org/hibernate/query/results/complete/CompleteFetchBuilderBasicPart.java
- hibernate-core/src/main/java/org/hibernate/query/results/complete/CompleteResultBuilderEntityJpa.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/resultmapping/InheritanceTests.java
https://hibernate.atlassian.net/browse/HHH-17102
> HHH-17102 Fix @SqlResultSetMapping issue for joined inheritance entity result

- hibernate-core/src/main/java/org/hibernate/query/hql/internal/QualifiedJoinPathConsumer.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmBagJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmListJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmMapJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmSetJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmSingularJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedBagJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedListJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedMapJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedSetJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedSingularJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/from/SqmAttributeJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQuerySpec.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/treat/HqlTreatJoinFetchTest.java
https://hibernate.atlassian.net/browse/HHH-17411
> HHH-17411 Fix fetch join on treated join leads to not cause owner not selected error

- hibernate-core/src/main/java/org/hibernate/boot/query/SqlResultSetMappingDescriptor.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/resultmapping/ResultMappingAssociationIdClassTest.java
https://hibernate.atlassian.net/browse/HHH-17308
> HHH-17308 AssertionError when mixing @SQLSelect and composite ID

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/EntityValuedPathsGroupByOrderByTest.java
https://hibernate.atlassian.net/browse/HHH-17415
> HHH-17415 NullPointerException: EntityValuedPathInterpretation - getNavigablePath()

- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/inheritance/SingleTableInheritanceLazyAssociationTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/associations/ManyToOneBidirectionalTest.java
https://hibernate.atlassian.net/browse/HHH-17140
The test shows that the issue has been fixed by https://hibernate.atlassian.net/browse/HHH-17309
> HHH-17140 Add test for issue

- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractManagedType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/MultiLevelInheritanceQueryTest.java
https://hibernate.atlassian.net/browse/HHH-17292
> HHH-17292 MappedSuperclass with more than 1 subclass level leads to "UnknownPathException: Could not resolve attribute"

- hibernate-core/src/main/java/org/hibernate/dialect/temptable/StandardTemporaryTableExporter.java
Same as https://github.com/hibernate/hibernate-orm/pull/7548 but for the `6.3` branch.
https://hibernate.atlassian.net/browse/HHH-17428
> Parameters strategy marker are 1 based

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/InheritedTypeAssociationJoinedFetchTest.java
https://hibernate.atlassian.net/browse/HHH-17328
> HHH-17328 Retrieve entity using entity graph not adding type in the where clause for @Inheritance(strategy = InheritanceType.SINGLE_TABLE)

- documentation/src/main/asciidoc/userguide/chapters/fetching/Fetching.adoc
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/CollectionPart.java
https://hibernate.atlassian.net/browse/HHH-17328
> HHH-17328 - Fix a couple of doc erratas

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/instantiation/internal/DynamicInstantiationAssemblerInjectionImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/CriteriaDynamicInstantiationInheritanceTest.java
https://hibernate.atlassian.net/browse/HHH-17382
> HHH-17382 Dynamic instantiation leads to superclass fields not found when using injection

- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/TypecheckUtil.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmBasicValuedSimplePath.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmEmbeddedValuedSimplePath.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/GenericPathComparisonTest.java
https://hibernate.atlassian.net/browse/HHH-17454
> HHH-17454 SemanticException caused by type check when comparing generic path to parameter expression

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/QueryBinder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/readonly/ReadOnlyNamedQueryTest.java
https://hibernate.atlassian.net/browse/HHH-17313
> HHH-17313 Session#setDefaultReadOnly is ignored by named queries

- documentation/documentation.gradle
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MariaDBLegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/cfg/DialectSpecificSettings.java
- hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/Database.java
- hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLServerConfiguration.java
- hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/OracleServerConfiguration.java
- hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/TiDBDialect.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/dialect/spi/DialectResolutionInfo.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/HibernateSchemaManagementTool.java
- hibernate-core/src/test/java/org/hibernate/orm/test/dialect/resolver/DialectSpecificConfigTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/dialect/resolver/TestingDialectResolutionInfo.java
https://hibernate.atlassian.net/browse/HHH-17425
> HHH-17425 Introduce some new dialect-specific config params

- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/WrappedEntityCriteriaTest.java
https://hibernate.atlassian.net/browse/HHH-8891
> HHH-8891 - Added test for issue (no fix required)

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddedForeignKeyDescriptor.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/EmbeddedForeignKeyInSubqueryTest.java
https://hibernate.atlassian.net/browse/HHH-17280
> HHH-17280 UnknownTableReferenceException in subquery selecting embeddable foreign key

- hibernate-core/src/main/java/org/hibernate/cache/internal/NaturalIdCacheKey.java
https://hibernate.atlassian.net/browse/HHH-17474
> HHH-17474 Change org.hibernate.cache.internal.NaturalIdCacheKey constructor scope

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultEvictEventListener.java
- hibernate-core/src/test/java/org/hibernate/orm/test/eviction/CascadeAllEvictTest.java
https://hibernate.atlassian.net/browse/HHH-17464
> HHH-17464 6.4.0 regression: NullPointerException in DefaultEvictEventListener#onEvict

- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/ConvertedListAttributeQueryTest.java
https://hibernate.atlassian.net/browse/HHH-17393
> HHH-17393 Incorrect return type for List attribute, wrap in additional list

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaWindowFunctionTest.java
https://hibernate.atlassian.net/browse/HHH-17391
https://hibernate.atlassian.net/browse/HHH-17392
> HHH-17391 HHH-17392 Fix errors when using criteria window functions and multiselect

- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/DomainModelHelper.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/MappedSuperclassAttributeInMultipleSubtypesTest.java
https://hibernate.atlassian.net/browse/HHH-17491
> HHH-17491 UnknownEntityTypeException thrown when multiple subclasses define an attribute with the same name and one is a MappedSuperclass

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/ImplicitJoinInSubqueryTest.java
https://hibernate.atlassian.net/browse/HHH-17445
> HHH-17445 Don't force initialization of correlated joined table group

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchByUniqueKeyInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/querycache/QueryCacheExistingEntityInstanceTest.java
https://hibernate.atlassian.net/browse/HHH-17359
> HHH-17359 Query Cache contains null values for entity associations when entity was already loaded

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/StringUtil.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/StringUtilTest.java
> HHH-17494 Metamodel generator produce an uncompilable class when an EntityGraph name contains a comma

- hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesCacheHit.java
https://hibernate.atlassian.net/browse/HHH-17456
> HHH-17456 java.util.UnknownFormatConversionException thrown why logging set to TRACE

- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/TypecheckUtil.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmPath.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/GenericManyToOneParameterTest.java
https://hibernate.atlassian.net/browse/HHH-17402
> HHH-17402 UnknownEntityTypeException: Unable to locate persister - when using Inheritance on entities

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/discriminator/CaseStatementWithTypeTest.java
https://hibernate.atlassian.net/browse/HHH-17413
> HHH-17413 Invalid SQL with TYPE() function and CASE expression in SELECT clause

- Jenkinsfile
- databases/cockroachdb/matrix.gradle
- databases/db2/matrix.gradle
- databases/hana/matrix.gradle
- databases/mariadb/matrix.gradle
- databases/mssqlserver/matrix.gradle
- databases/mysql/matrix.gradle
- databases/pgsql/matrix.gradle
- docker_db.sh
- edb/edb16.Dockerfile
- nightly.Jenkinsfile
- settings.gradle
https://hibernate.atlassian.net/browse/HHH-17544
https://hibernate.atlassian.net/browse/HHH-17534
https://hibernate.atlassian.net/browse/HHH-17545
https://hibernate.atlassian.net/browse/HHH-17542
https://hibernate.atlassian.net/browse/HHH-17543
https://hibernate.atlassian.net/browse/HHH-17537
https://hibernate.atlassian.net/browse/HHH-17538
https://hibernate.atlassian.net/browse/HHH-17535
https://hibernate.atlassian.net/browse/HHH-17546
https://hibernate.atlassian.net/browse/HHH-17536
https://hibernate.atlassian.net/browse/HHH-17540
https://hibernate.atlassian.net/browse/HHH-17541
https://hibernate.atlassian.net/browse/HHH-17539
> Dependency updates

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/BasicCollectionPersister.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/EmbeddableAsElementCollectionWithUpdatableFalseTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/EmbeddableAsOrderedElementCollectionWithUpdatableFalseTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/collections/ElementCollectionMapUpdateTest.java
https://hibernate.atlassian.net/browse/HHH-17334
Alternative solution to #7513.
> HHH-17334 Duplicated columns when updating indexed @ElementCollection with non updatable fields

- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/AbstractSqmParameter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmNamedParameter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/sql/exec/EmbeddedIdEntityTest.java
https://hibernate.atlassian.net/browse/HHH-17499
> HHH-17499 SemanticException when querying embedded id entity with positional parameter

- documentation/src/main/asciidoc/introduction/Entities.adoc
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/identifier/NaiveEqualsHashCodeEntityTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/identifier/NaturalIdEqualsHashCodeEntityTest.java
https://hibernate.atlassian.net/browse/HHH-17555
> HHH-17555 don't use getClass() inside entity equals()

- hibernate-core/src/main/java/org/hibernate/dialect/OracleServerConfiguration.java
https://hibernate.atlassian.net/browse/HHH-17561
> HHH-17561 NullPointerException at OracleServerConfiguration class

- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/SingLeTableWithEmbeddedIdTest.java
https://hibernate.atlassian.net/browse/HHH-17525
test showing the issue has been resolved on main
> HHH-17525 StackOverflowError when using @ManyToMany with composite id

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/DurationJavaType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/type/PostgresIntervalSecondNoScaleTest.java
https://hibernate.atlassian.net/browse/HHH-17520
> HHH-17520 Schema creation fails with interval second data type on PostgreSQL

- hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
- hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesSourceProcessingStateStandardImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/spi/JdbcValuesSourceProcessingState.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/collection/PostLoadTest.java
https://hibernate.atlassian.net/browse/HHH-17489
> HHH-17489 ConcurrentModificationException after upgrading to 6.4.0

- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/TypecheckUtil.java
- hibernate-core/src/main/java/org/hibernate/type/QueryParameterJavaObjectType.java
- hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/HHH17416Test.java
https://hibernate.atlassian.net/browse/HHH-17416
> [HHH-17416] Add new inheritor JavaObjectType for specifying unresolved query parameter

- hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/NamedQueryTest.java
https://hibernate.atlassian.net/browse/HHH-17566
> HHH-17566 addNamedQuery leads to "Named query exists, but did not specify a resultClass"

- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/Compatibility.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/instantiation/internal/DynamicInstantiationResultImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/instantiation/InstantiationWithMultipleWrapperConstructorsTest.java
https://hibernate.atlassian.net/browse/HHH-17515
> HHH-17515 DynamicInstantiationResult wrong java type constructor selected

- .github/workflows/atlas.yml
- .github/workflows/codeql.yml
- .github/workflows/contributor-build.yml
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java
- hibernate-core/src/main/java/org/hibernate/usertype/UserType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mappedBy/MappedByNonAssociationTest.java
- settings.gradle
https://hibernate.atlassian.net/browse/HHH-16593
> 6.2 Backports

- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQuerySpec.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableResultImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/OneToManyInEmbeddedQueryTest.java
https://hibernate.atlassian.net/browse/HHH-17572
> HHH-17572 Persist of entity with ToOne association which contains an embeddable with associated collection fails with SemanticException

- hibernate-core/src/main/java/org/hibernate/boot/registry/internal/StandardServiceRegistryImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/connection/PropertiesTest.java
https://hibernate.atlassian.net/browse/HHH-17463
> HHH-17463 UnsupportedOperationException when using JAKARTA_JDBC_URL

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/TypeUtils.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/circulartypevariable/CircularTypeVariableTest.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/circulartypevariable/RoleAccess.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/circulartypevariable/User.java
https://hibernate.atlassian.net/browse/HHH-17253
> HHH-17253 - Fix for StackOverflowError in static metamodel generator

- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLEnumJdbcType.java
https://hibernate.atlassian.net/browse/HHH-17496
> [HHH-17496] Use Enum#name() for DB value

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/selectbeforeupdate/SelectBeforeUpdateWithCascadeTest.java
https://hibernate.atlassian.net/browse/HHH-17560
> HHH-17560 ArrayIndexOutOfBoundsException in DirtyHelper.isModified()

- hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/XmlElementMetadata.java
Fix typos in javadoc(XmlElementMetadata.java)
https://hibernate.atlassian.net/browse/HHH-17396
> HHH-17396 fix typos in javadoc

- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmFunction.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/ToHqlStringTest.java
https://hibernate.atlassian.net/browse/HHH-16526
> HHH-16526 - Add missing first argument in toHqlString()

- hibernate-core/src/main/java/org/hibernate/id/IncrementGenerator.java
https://hibernate.atlassian.net/browse/HHH-17327
> HHH-17327 Adding support for Union All in IncrementGenerator

- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/EntityJavaType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/proxy/ProxyAsQueryParameterTest.java
https://hibernate.atlassian.net/browse/HHH-17467
> HHH-17467 QueryArgumentException when using a proxy as parameter value in a query

- gradle/databases.gradle
- gradle/java-module.gradle
- hibernate-core/hibernate-core.gradle
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/ConnectionProviderInitiator.java
- hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
- hibernate-ucp/hibernate-ucp.gradle
- hibernate-ucp/src/main/java/org/hibernate/ucp/internal/StrategyRegistrationProviderImpl.java
- hibernate-ucp/src/main/java/org/hibernate/ucp/internal/UCPConnectionProvider.java
- hibernate-ucp/src/main/java/org/hibernate/ucp/internal/package-info.java
- hibernate-ucp/src/main/resources/META-INF/services/org.hibernate.boot.registry.selector.StrategyRegistrationProvider
- hibernate-ucp/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- hibernate-ucp/src/test/java/org/hibernate/test/ucp/UCPConnectionProviderTest.java
- hibernate-ucp/src/test/java/org/hibernate/test/ucp/UCPTransactionIsolationConfigTest.java
- hibernate-ucp/src/test/resources/hibernate.properties
- settings.gradle
https://hibernate.atlassian.net/browse/HHH-17414
> HHH-17414 Create a UCP connection pool module

- hibernate-core/src/main/java/org/hibernate/id/IdentifierGenerator.java
- hibernate-core/src/main/java/org/hibernate/id/factory/internal/IdentifierGeneratorUtil.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/MixedTimingGeneratorsTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/SequenceOrAssignedGeneratorTest.java
https://hibernate.atlassian.net/browse/HHH-17472
> HHH-17472 Allow persisting Entity with manually assigned id for column annotated with @GeneratedValue

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLUUIDJdbcType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/id/uuid/PostgreSQLUUIDTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/type/PreferredUuidJdbcTypeTest.java
https://hibernate.atlassian.net/browse/HHH-14358
> HHH-14358 - Added test and fix to support null binding for PostgreSQL

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/softdelete/HHH17511Test.java
https://hibernate.atlassian.net/browse/HHH-17511
> HHH-17511 - Test and fix for missing condition in join with a @SoftDelete marked Entity

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultRefreshEventListener.java
- hibernate-core/src/test/java/org/hibernate/orm/test/refresh/RefreshTest.java
https://hibernate.atlassian.net/browse/HHH-14821
> HHH-14821 - Test and fix for issue

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/instantiation/internal/DynamicInstantiationArgument.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/CriteriaWithDynamicInstantiationAndOrderByTest.java
https://hibernate.atlassian.net/browse/HHH-17530
> HHH-17530 Criteria query with nested dynamic instantiations and sorting is not working

- hibernate-core/src/main/java/org/hibernate/query/hql/internal/QualifiedJoinPathConsumer.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmPath.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/GenericMappedSuperclassNestedJoinTest.java
https://hibernate.atlassian.net/browse/HHH-17606
> HHH-17606 Cannot resolve path of nested generic mapped-superclass joins

- hibernate-core/src/main/java/org/hibernate/Hibernate.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultRefreshEventListener.java
- hibernate-core/src/test/java/org/hibernate/orm/test/refresh/RefreshTest.java
https://hibernate.atlassian.net/browse/HHH-14821
> HHH-14821 fix thrown exception types

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DerbyLegacySqlAstTranslator.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/FirebirdSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/DerbySqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/QueryTest.java
https://hibernate.atlassian.net/browse/HHH-17490
> HHH-17490 NOT IN clause does not work with empty list

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractDomainPath.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/FkDomainPathContinuation.java
- hibernate-core/src/test/java/org/hibernate/orm/test/orderby/OrderByToOneTest.java
https://hibernate.atlassian.net/browse/HHH-17623
> HHH-17623 Test and fix use of association in @OrderBy

- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderSubSelectFetch.java
https://hibernate.atlassian.net/browse/HHH-17307
> HHH-17307 Hibernate 6 ListResultsConsumer.Results#addUnique really slow for ElementCollections

- hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/OneToManyPersister.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/collections/ReadOnlyCollectionsTest.java
https://hibernate.atlassian.net/browse/HHH-17468
> HHH-17468 Allow mapping of "read-only" collections with non insertable/updatable join columns

- hibernate-core/src/main/java/org/hibernate/type/TypeHelper.java
- hibernate-core/src/test/java/org/hibernate/orm/test/any/annotations/AnyMergeTest.java
https://hibernate.atlassian.net/browse/HHH-17621
> HHH-17621 UnsupportedOperationException when merging an entity with a @Any mapping 

- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/EnumSingleCharTest.java
https://hibernate.atlassian.net/browse/HHH-17106
> HHH-17106 Fix ClassCastException when using length 1 named enum mapping

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/softdelete/secondary/JoinedSubclassSoftDeleteTests.java
https://hibernate.atlassian.net/browse/HHH-17615
> HHH-17615 @SoftDelete query problem with Joined Inheritance hierarchy structure

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/AltibaseDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2LegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/HSQLLegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MaxDBDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/RDMSOS2200Dialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLiteDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseLegacyDialect.java
- hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
- hibernate-core/src/main/java/org/hibernate/dialect/AbstractTransactSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/DialectDelegateWrapper.java
- hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SybaseDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/TrimFunction.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/dialect/function/AnsiTrimEmulationFunctionTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
https://hibernate.atlassian.net/browse/HHH-17435
> HHH-17435 Trim function not escaping single quotes and not allowing input parameters as trim character

- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/update/JoinedInheritanceTest.java
https://hibernate.atlassian.net/browse/HHH-17632
> HHH-17632 AssertionError when updating entity with lazy loading property and bytecode enhancement

- hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/ArgumentTypesValidator.java
https://hibernate.atlassian.net/browse/HHH-17637
> HHH-17637 improve an error message

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MariaDBLegacySqlAstTranslator.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacySqlAstTranslator.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacySqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/MariaDBSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/SQLServerSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/TiDBSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
https://hibernate.atlassian.net/browse/HHH-17639
> HHH-17639 Make recursive CTE cycle detection emulation independent of collation

- hibernate-core/src/main/java/org/hibernate/dialect/AbstractTransactSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/TrimFunction.java
- hibernate-core/src/test/java/org/hibernate/orm/test/dialect/function/AnsiTrimEmulationFunctionTest.java
https://hibernate.atlassian.net/browse/HHH-17435
> HHH-17435 Small fixes to trim() function

- databases/mysql/matrix.gradle
- settings.gradle
https://hibernate.atlassian.net/browse/HHH-17536
> Backport test: HHH-17536 Update MySQL JDBC driver to 8.2.0

- hibernate-core/src/main/java/org/hibernate/boot/model/process/spi/MetadataBuildingProcess.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/MonetaryAmountUserType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/ContributedUserTypeTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/ServiceLoadedCustomUserTypeTypeContributor.java
when contributed through a service provider
https://hibernate.atlassian.net/browse/HHH-17635
> HHH-17635 - register custom user types

- hibernate-core/src/main/java/org/hibernate/bytecode/internal/BytecodeProviderInitiator.java
- hibernate-core/src/main/java/org/hibernate/bytecode/spi/BytecodeProvider.java
- hibernate-core/src/main/java/org/hibernate/cfg/BytecodeSettings.java
- hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/SerializableProxy.java
- hibernate-core/src/main/resources/META-INF/services/org.hibernate.bytecode.spi.BytecodeProvider
- hibernate-core/src/test/java/org/hibernate/orm/test/serialization/ProxySerializationNoSessionFactoryTest.java
https://hibernate.atlassian.net/browse/HHH-17643
Alternative solution to #7700.
> HHH-17643 Allow uninitialized proxy serialization even when a SessionFactory is not available

- hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
- hibernate-core/src/test/java/org/hibernate/orm/test/softdelete/SoftDeleteMappedColumnTest.java
https://hibernate.atlassian.net/browse/HHH-17461
> HHH-17461 Add explicit @SoftDelete column duplication validation

- hibernate-core/src/main/java/org/hibernate/query/sql/internal/ResultSetMappingProcessor.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/NativeQueryMultipleEntityResultTest.java
https://hibernate.atlassian.net/browse/HHH-17605
> HHH-17605 NativeQuery - Multiple entities of same type are translated into the same single object

- hibernate-core/src/main/java/org/hibernate/sql/results/spi/ListResultsConsumer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batch/ManyToOneBatchLoadErrorTest.java
https://hibernate.atlassian.net/browse/HHH-17526
> HHH-17526 During eager batch fetching, real exceptions swallowed by exception in finally

- hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
- hibernate-core/src/main/java/org/hibernate/query/sql/internal/ResultSetMappingProcessor.java
- hibernate-core/src/main/java/org/hibernate/sql/results/spi/ListResultsConsumer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batch/ManyToOneBatchLoadErrorTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/NativeQueryMultipleEntityResultTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/softdelete/SoftDeleteMappedColumnTest.java
Backport of #7706, #7712 and #7710.
https://hibernate.atlassian.net/browse/HHH-17526
https://hibernate.atlassian.net/browse/HHH-17605
https://hibernate.atlassian.net/browse/HHH-17461
> 6.4 Backports

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java
- hibernate-core/src/test/java/org/hibernate/orm/test/merge/CompositeIdWithAssociationsAndGeneratedValuesMerge2Test.java
- hibernate-core/src/test/java/org/hibernate/orm/test/merge/SimpleMergeTest.java
https://hibernate.atlassian.net/browse/HHH-17634
> HHH-17634 Merging a new entity having a @GeneratedValue id should not set the generated id to the original entity

- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/ConvertedListAttributeQueryTest.java
https://hibernate.atlassian.net/browse/HHH-17598
> HHH-17598 Criteria multiselect doesn't work properly for array types other than Object[]

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/ToOneBinder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/foreignkeys/disabled/DefaultConstraintModeTest.java
https://hibernate.atlassian.net/browse/HHH-17550
> HHH-17550 NO_CONSTRAINT not honored by InheritanceType.JOINED

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyContainer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/discriminator/SingleTableAndGenericsTest.java
https://hibernate.atlassian.net/browse/HHH-17644
> HHH-17644 Mapping of generic types in single table inheritance depends on lexicographical order of parent and child classnames

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/JoinedInheritanceDiscriminatorRemovalByTypeTest.java
https://hibernate.atlassian.net/browse/HHH-17667
> HHH-17667 Delete by type query with @DiscriminatorColumn generates SQL with a missing join

- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/FromClause.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchSubselectCollection3Test.java
https://hibernate.atlassian.net/browse/HHH-17670
> HHH-17670 Test and fix for NPE in FromClause#findTableGroup

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
- hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/FindWithEntityGraphTest.java
https://hibernate.atlassian.net/browse/HHH-16960
> HHH-16960 OneToOne lazy loading fails when fetch graph is involved

- hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
- hibernate-core/src/test/java/org/hibernate/orm/test/eviction/EvictAndGetTest.java
https://hibernate.atlassian.net/browse/HHH-17674
> HHH-17674 NullPointerException thrown when loading entity previously evicted and proxied

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/EntityGraphAndJoinTest.java
https://hibernate.atlassian.net/browse/HHH-17629
> HHH-17629 Criteria and Entity graph generates same join clause twice

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/discriminator/JoinedInheritanceForceDiscriminatorTest.java
https://hibernate.atlassian.net/browse/HHH-17113
> HHH-17113 Incorrect SQL generated on DiscriminatorColumn when combined with bidirectional relation and @DiscriminatorOptions(force = true)

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultRefreshEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/spi/RefreshContext.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/refresh/MergeAndRefreshTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/locking/LockRefreshReferencedAndCascadingTest.java
https://hibernate.atlassian.net/browse/HHH-17668
> HHH-17668 NullPointerException when refreshing bytecode-enhanced entity from second-level cache

- hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/StandardFunctionReturnTypeResolvers.java
- hibernate-core/src/main/java/org/hibernate/sql/results/internal/SqlSelectionImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
Resolves a very confusing error message.
https://hibernate.atlassian.net/browse/HHH-17677
> HHH-17677 handle literal null arguments more elegantly in StandardFunctionReturnTypeResolvers

- tooling/hibernate-ant/src/main/java/org/hibernate/tool/enhance/EnhancementTask.java
https://hibernate.atlassian.net/browse/HHH-14429 fix regression introduced by https://hibernate.atlassian.net/browse/HHH-11795
> HHH-14429 Restore <fileset/> support for ant enhance task

- hibernate-core/src/main/java/org/hibernate/query/sqm/function/AbstractSqmSelfRenderingFunctionDescriptor.java
https://hibernate.atlassian.net/browse/HHH-17681
> HHH-17681 Restore AbstractSqmSelfRenderingFunctionDescriptor backwards compatibility

- hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/ManyToManyJoinTableAndInheritanceTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/OneToManyJoinedInheritanceAndDiscriminatorTest.java
https://hibernate.atlassian.net/browse/HHH-17679
> HHH-17679 Unnecessary entity name usage leads to collection element join

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
https://hibernate.atlassian.net/browse/HHH-17683
> HHH-17683 never look for session getters in mapped superclasses or embeddables

- hibernate-core/src/main/java/org/hibernate/dialect/function/TruncFunction.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/TruncConvertedDatetimeAttributeTest.java
https://hibernate.atlassian.net/browse/HHH-17666
> HHH-17666 Datetime truncation fails when argument is a converted property

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/EntityTableMapping.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/InsertCoordinatorStandard.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateValuesAnalysis.java
- hibernate-core/src/main/java/org/hibernate/sql/model/TableMapping.java
- hibernate-core/src/main/java/org/hibernate/sql/model/internal/OptionalTableUpdate.java
- hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/OptionalTableUpdateOperation.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/secondarytable/SecondaryTableDynamicUpateTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/secondarytables/SecondaryTableDynamicUpateTest.java
https://hibernate.atlassian.net/browse/HHH-17587
> HHH-17587 Setting to null a property from a @SecondaryTable and @DynamicUpdate deletes the whole entry from database

- hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/PersistenceContext.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/proxy/narrow/BidirectionalManyToOneNarrowingTest.java
https://hibernate.atlassian.net/browse/HHH-17665
https://hibernate.atlassian.net/browse/HHH-17594
> HHH-17665 HHH-17665 Fix errors caused by supertype proxies assigned to subtype lazy association property

- tooling/hibernate-enhance-maven-plugin/src/main/resources/META-INF/maven/org.hibernate.orm.tooling/hibernate-enhance-maven-plugin/plugin-help.xml
- tooling/hibernate-enhance-maven-plugin/src/main/resources/META-INF/maven/plugin.xml
backport of https://hibernate.atlassian.net/browse/HHH-17326 to 6.4
> HHH-17326 deprecated lazyLoading no longer working

- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleUniqueKeyEntityLoaderStandard.java
https://hibernate.atlassian.net/browse/HHH-17689
> HHH-17689 Cache SQL statement for unique key lookup

- .github/workflows/atlas.yml
https://hibernate.atlassian.net/browse/HHH-17319
> HHH-17319 Use Oracle GraalVM for Atlas builds

- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/NamedTableReference.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/UnionTableReference.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/ToOneSingleTableInheritanceAutoFlushTest.java
https://hibernate.atlassian.net/browse/HHH-17686
> HHH-17686 Join with inheritance subtype association doesn't trigger auto-flush

- hibernate-envers/src/main/java/org/hibernate/envers/strategy/internal/ValidityAuditStrategy.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/strategy/ValidityAuditStrategyPartialFlushCountTest.java
https://hibernate.atlassian.net/browse/HHH-17442
> HHH-17442 Use FlushMode.MANUAL for select query in ValidityAuditStrategy

- hibernate-core/src/main/java/org/hibernate/engine/internal/CacheHelper.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/internal/AbstractJdbcParameter.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcParameterBindingsImpl.java
- hibernate-core/src/main/java/org/hibernate/type/CustomType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/converter/spi/BasicValueConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/AttributeConverterAndNullTest.java
https://hibernate.atlassian.net/browse/HHH-17687
> HHH-17687 AttributeConverter, query does not use converter to convert 'null' fields

- hibernate-core/src/main/java/org/hibernate/engine/internal/CacheHelper.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/internal/AbstractJdbcParameter.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcParameterBindingsImpl.java
- hibernate-core/src/main/java/org/hibernate/type/CustomType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/converter/spi/BasicValueConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/AttributeConverterAndNullTest.java
backport of https://hibernate.atlassian.net/browse/HHH-17687
> HHH-17687 AttributeConverter, query does not use converter to convert 'null' field

- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/JavaTypeBaseline.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/basic/SetAsBasicTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/basic/TreeMapAsBasicTypeTest.java
backport of https://hibernate.atlassian.net/browse/HHH-17320
> HHH-17320 A basic attribute of type TreeMap causes a JdbcTypeRecommendationException

- documentation/src/main/asciidoc/introduction/Generator.adoc
- hibernate-core/src/main/java/org/hibernate/annotations/processing/Find.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
> clarify use of Order and Page with @Find

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/QueryMethod.java
don't include session parameter type where not necessary
> small fixes to @Find and @HQL methods

- hibernate-core/src/main/java/org/hibernate/boot/archive/scan/package-info.java
- hibernate-core/src/main/java/org/hibernate/boot/archive/scan/spi/package-info.java
- hibernate-core/src/main/java/org/hibernate/boot/archive/spi/package-info.java
- hibernate-core/src/main/java/org/hibernate/boot/model/package-info.java
- hibernate-core/src/main/java/org/hibernate/boot/model/source/spi/PluralAttributeMapKeySource.java
- hibernate-core/src/main/java/org/hibernate/cfg/QuerySettings.java
- hibernate-core/src/main/java/org/hibernate/collection/spi/CollectionInitializerProducer.java
- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/SqlServerConvertTruncFunction.java
- hibernate-core/src/main/java/org/hibernate/dialect/identity/IdentityColumnSupport.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/package-info.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/ResultSetReturn.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SessionImplementor.java
- hibernate-core/src/main/java/org/hibernate/jpa/package-info.java
- hibernate-core/src/main/java/org/hibernate/proxy/package-info.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/spi/SqmMultiTableInsertStrategy.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/spi/SqmMultiTableMutationStrategy.java
and slightly improve some jdoc in Dialect
also deprecate an unused method with incorrect jdoc
> fix some warnings and wrong info in the javadoc

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/AltibaseDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/AltibaseSqlAstTranslator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/interfaceproxy/InterfaceProxyTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/delegate/MutationDelegateJoinedInheritanceTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/javatime/GlobalJavaTimeJdbcTypeTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/javatime/JavaTimeJdbcTypeTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/temporal/FractionalSecondsTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/temporal/JavaTimeFractionalSecondsTests.java
- hibernate-ucp/src/test/java/org/hibernate/test/ucp/UCPTransactionIsolationConfigTest.java
- settings.gradle
Updated AltibaseDialect to support Altibase 7.1 server and fixed several test failures since last merge.
❯ ./gradlew clean build -Pdb=altibase
...
BUILD SUCCESSFUL in 12m 45s
https://hibernate.atlassian.net/browse/HHH-17696
> HHH-17696 Update AltibaseDialect to support Altibase 7.1 and above

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/OracleArrayJdbcTypeConstructor.java
- hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/OracleNestedTableJdbcTypeConstructor.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/AbstractArrayJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/BasicCollectionJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/ArrayJdbcType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/spi/JdbcTypeRegistry.java
- hibernate-core/src/test/java/org/hibernate/orm/test/type/descriptor/jdbc/ArrayJdbcTypeTest.java
https://hibernate.atlassian.net/browse/HHH-17662
> HHH-17662 Fix memory leak issue due to ArrayJdbcType not having equals/hashCode

- hibernate-core/src/main/java/org/hibernate/bytecode/internal/BytecodeProviderInitiator.java
https://hibernate.atlassian.net/browse/HHH-17705
> HHH-17705 NullPointerException during enhancement when using the default BytecodeProvider in Wildfly

- settings.gradle
https://hibernate.atlassian.net/browse/HHH-17713
> HHH-17713 Upgrade ByteBuddy to 1.14.11

- settings.gradle
cc/ @scottmarlow
https://hibernate.atlassian.net/browse/HHH-17713
> Backporting HHH-17713 to 6.4

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/internal/AbstractMutationExecutor.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/internal/MutationExecutorSingleNonBatched.java
- hibernate-core/src/main/java/org/hibernate/id/insert/AbstractReturningDelegate.java
- hibernate-core/src/main/java/org/hibernate/id/insert/AbstractSelectingDelegate.java
- hibernate-core/src/main/java/org/hibernate/id/insert/GetGeneratedKeysDelegate.java
- hibernate-core/src/main/java/org/hibernate/id/insert/InsertReturningDelegate.java
- hibernate-core/src/main/java/org/hibernate/id/insert/SybaseJConnGetGeneratedKeysDelegate.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/delegate/MutationDelegateStatementReleaseTest.java
- hibernate-core/src/test/resources/log4j2.properties
https://hibernate.atlassian.net/browse/HHH-17688
> HHH-17688 Mutation statements using delegates do not consistently release statements

- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/hql/QueryComparingAssociationToNullTest.java
https://hibernate.atlassian.net/browse/HHH-16974
> HHH-16974 IllegalStateException Unsupported tuple comparison combination

- documentation/src/main/asciidoc/introduction/Generator.adoc
- hibernate-core/src/main/java/org/hibernate/annotations/processing/HQL.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/QueryMethod.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/dao/Dao.java
https://hibernate.atlassian.net/browse/HHH-17719
> HHH-17719 Supports boolean as return type of mutation query method

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
- hibernate-core/src/test/java/org/hibernate/orm/test/filter/FilterWithILikeTest.java
- hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java
https://hibernate.atlassian.net/browse/HHH-16454
> HHH-16454 PostgreSQL ILIKE Keyword is considered a column name when deducing alias injection points

- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/EntityJavaType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/proxy/DetachedProxyAsQueryParameterTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/proxy/ProxyAsQueryParameterTest.java
https://hibernate.atlassian.net/browse/HHH-17704
> HHH-17704  Query using detached Proxy as parameter fails with LazyInitializationException

- hibernate-core/src/main/java/org/hibernate/query/criteria/HibernateCriteriaBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/spi/HibernateCriteriaBuilderDelegate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/NodeBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/CountEntityWithCompositeIdTest.java
and remove some unused type parameters
https://hibernate.atlassian.net/browse/HHH-17724
> HHH-17724 add count(*) to HibernateCriteriaBuilder

- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/AbstractArrayJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/BasicCollectionJavaType.java
https://hibernate.atlassian.net/browse/HHH-15551
> HHH-15551 improve error message for missing association annotations

- hibernate-core/src/main/java/org/hibernate/cfg/JdbcSettings.java
- hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentBag.java
- hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentList.java
- hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentMap.java
- hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentSet.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java
The micro database version was always 0.
Further misc cleanups.
> populate the micro database version

- hibernate-core/src/main/java/org/hibernate/annotations/processing/HQL.java
- hibernate-core/src/main/java/org/hibernate/boot/model/TypeBeanInstanceProducer.java
- hibernate-core/src/main/java/org/hibernate/id/enhanced/CustomOptimizerDescriptor.java
- hibernate-core/src/main/java/org/hibernate/internal/util/ReflectHelper.java
- hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableInstantiatorRecordStandard.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/StandardHqlTranslator.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/Compatibility.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmDynamicInstantiation.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/instantiation/internal/DynamicInstantiationAssemblerInjectionImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/instantiation/internal/DynamicInstantiationResultImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/instantiation/internal/InstantiationHelper.java
- hibernate-core/src/main/java/org/hibernate/type/EnumType.java
- hibernate-core/src/main/java/org/hibernate/type/SerializableToBlobType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/ToHqlStringTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/DynamicInstantiationTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/instantiation/InstantiationWithMultiplePrimitiveConstructorsTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/querycache/AbstractQueryCacheResultTransformerTest.java
- hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectContext.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/validation/Validation.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/hqlsql/Book.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/hqlsql/Dao.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/hqlsql/Dto.java
https://hibernate.atlassian.net/browse/HHH-17729
> HHH-17729 Instantiation validation

- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/joinorder/JoinOrderTest.java
https://hibernate.atlassian.net/browse/HHH-16522
> HHH-16522 add test for fixed bug

- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SqmPathRegistryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/AliasCollisionException.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/from/SqmEntityJoin.java
- hibernate-core/src/main/java/org/hibernate/sql/results/internal/RowTransformerConstructorImpl.java
and missing add javadoc to AliasCollisionException
> improve error messages coming from SqmPathRegistryImpl

- hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
https://hibernate.atlassian.net/browse/HHH-15753
> HHH-15753 GROUP BY ALIAS support in 23c

- hibernate-core/src/main/java/org/hibernate/dialect/JsonHelper.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/NestedJsonEmbeddableTest.java
https://hibernate.atlassian.net/browse/HHH-17695
> HHH-17695 Persistence fails when nested JSON aggregate is null

- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappingMetamodelImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/hql/InSubqueryPredicateAnonymousTupleTest.java
https://hibernate.atlassian.net/browse/HHH-17701
> HHH-17701 @Converter ignored for attributes used in tuples leading to NullPointerException in TupleMappingModelExpressible constructor

- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/cte/SqmCteTable.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaCteUnionTest.java
https://hibernate.atlassian.net/browse/HHH-17508
> HHH-17508 java.lang.IllegalStateException when using union query as source for CTE expression

- hibernate-core/src/main/java/org/hibernate/query/sql/internal/ParameterParser.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/ParameterParserTest.java
https://hibernate.atlassian.net/browse/HHH-17717
> HHH-17717 Add semicolon(`;`) to hql separators

- documentation/src/main/asciidoc/querylanguage/Expressions.adoc
- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/cfg/QuerySettings.java
- hibernate-core/src/main/java/org/hibernate/dialect/MariaDBSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/OracleSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgresPlusDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/ExtractFunction.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/FormatFunction.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/IntegralTimestampaddFunction.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/hql/spi/SqmCreationOptions.java
- hibernate-core/src/main/java/org/hibernate/query/internal/QueryEngineImpl.java
- hibernate-core/src/main/java/org/hibernate/query/spi/QueryEngineOptions.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/BinaryArithmeticOperator.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCreationOptionsStandard.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/IntegerDivisionTest.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/validation/MockSessionFactory.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/validation/Validation.java
Still not sure that we should actually do this, it's just an idea.
https://hibernate.atlassian.net/browse/HHH-16048
> HHH-16048 add 'hibernate.query.hql.portable_integer_division'

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/ManyToManyTreatJoinTest.java
https://hibernate.atlassian.net/browse/HHH-17096
> HHH-17096 treat() operator for @ManyToMany join generates SQL without discriminator condition

- documentation/src/main/asciidoc/querylanguage/Expressions.adoc
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/EnumComparisonTest.java
https://hibernate.atlassian.net/browse/HHH-17748
> HHH-17748 accept abbreviated enum value names in HQL 'when' clause

- hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
https://hibernate.atlassian.net/browse/HHH-15756
> HHH-15756 Table Value Constructor (INSERT, FROM column aliasing at table alias, CTE)

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/discriminator/CaseStatementWithTypeTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/discriminator/JoinedInheritanceDiscriminatorSelectionTest.java
https://hibernate.atlassian.net/browse/HHH-17727
> HHH-17727 Omit subclass tables in SQL when selecting only discriminator just like we do for basic attributes

- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/sqm/ConcurrentConcreteSqmSelectQueryPlainTest.java
https://hibernate.atlassian.net/browse/HHH-17742
> HHH-17742 Race condition in ConcreteSqmSelectQueryPlan#withCacheableSqmInterpretation

- documentation/src/main/asciidoc/introduction/Interacting.adoc
- hibernate-core/src/main/java/org/hibernate/generator/internal/SourceGeneration.java
- hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java
- hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/JpaCriteriaQuery.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/QuerySplitter.java
- hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/spi/DelegatingSqmSelectionQueryImplementor.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/SqmStatement.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmAttributeJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmFrom.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/from/SqmAttributeJoin.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/AbstractSqmSelectQuery.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectStatement.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSubQuery.java
- hibernate-core/src/main/java/org/hibernate/sql/results/spi/SingleResultConsumer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/count/CountTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CountQueryTests.java
This is a feature that Panache can use, and that we're also going to need for Jakarta Data.
And frankly, the conversation with @FroMage convinced me that we should have had it for a long time.
https://hibernate.atlassian.net/browse/HHH-16931
> HHH-16931 add SelectionQuery.getResultCount()

- Jenkinsfile
- settings.gradle
https://hibernate.atlassian.net/browse/HHH-17754
> HHH-17754 Upgrade to Byte Buddy 1.14.12

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/ImportContextImpl.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/hhh17613/ChildB.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/hhh17613/HHH17613Test.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/hhh17613/Parent.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/hhh17613/a/ChildA.java
See Jira issue [HHH-17613](https://hibernate.atlassian.net/browse/HHH-17613)
This time not so dirty solution
[HHH-17613]: https://hibernate.atlassian.net/browse/HHH-17613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HHH-17613 Generated metamodel contains invalid import when using generics

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/ImportContextImpl.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/hhh17661/Entity.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/hhh17661/HHH17661Test.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/hhh17661/Tree.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/hhh17661/TreeRelation.java
https://hibernate.atlassian.net/browse/HHH-17613
https://hibernate.atlassian.net/browse/HHH-17661
> HHH-17613, HHH-17661 minor cleanup and test

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java
- hibernate-core/src/main/java/org/hibernate/id/ForeignGenerator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/mapsid/MapsIdClassTest.java
https://hibernate.atlassian.net/browse/HHH-17755
> HHH-17755 populate @Id property from @MapsId association with @IdClass

- hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStyleGenerator.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/spi/SchemaManagementToolCoordinator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/id/hhh12973/PostgreSQLSequenceGeneratorWithSerialTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/id/hhh12973/SequenceMismatchStrategyDefaultExceptionTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/id/hhh12973/SequenceMismatchStrategyFixWithSequenceGeneratorTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/id/hhh12973/SequenceMismatchStrategyLogTest.java
when hdb2ddl will recreate them anyway
https://hibernate.atlassian.net/browse/HHH-17691
> HHH-17691 - Avoid unnecessary sequence queries

- local-build-plugins/src/main/java/org/hibernate/orm/toolchains/JavaModulePlugin.java
The previous implementation was not doing anything: somehow Gradle was erasing any change. Most likely the list passed to setJvmArgs is getting copied and later changes to that list are just ignored.
> Actually set JVM options in JavaModulePlugin

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/QueryMethod.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/dao/Dao.java
https://hibernate.atlassian.net/browse/HHH-17765
> HHH-17765 Support some special chars in query method queries

- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/TypecheckUtil.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmUnaryOperation.java
- hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/ConvertedAttributesTypecheckTest.java
https://hibernate.atlassian.net/browse/HHH-17766
> HHH-17766 Improve type of numeric and by unit expressions applied to converted attributes

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/ConnectionProviderInitiator.java
https://hibernate.atlassian.net/browse/HHH-17734
> HHH-17734 Ensure provider_class has precedence over datasource

- hibernate-core/src/main/java/org/hibernate/query/Order.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/HibernateCriteriaBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/spi/HibernateCriteriaBuilderDelegate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/NodeBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSortSpecification.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/select/SortSpecification.java
- settings.gradle
- tooling/metamodel-generator/hibernate-jpamodelgen.gradle
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/JPAMetaModelEntityProcessor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/CriteriaFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/DaoConstructor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/IdFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/LifecycleMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/NaturalIdFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/QueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/Constants.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/TypeUtils.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/data/Author.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/data/Book.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/data/BookAuthorRepository.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/data/DataTest.java
Current status:
https://hibernate.atlassian.net/browse/HHH-17773
> HHH-17772, HHH-17773 initial support for Jakarta Data annotations

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/ClassWriter.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/ContainsAttributeTypeVisitor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/Context.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/JPAMetaModelEntityProcessor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMeta.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaAttribute.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaPackage.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/BasicAttributeVisitor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/CriteriaFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/DefaultConstructor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/IdFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/LifecycleMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/MetaAttributeGenerationVisitor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/NamedQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/NaturalIdFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/QueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/RepositoryConstructor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/model/Metamodel.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/Constants.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/TypeRenderingVisitor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/TypeUtils.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/validation/ProcessorSessionFactory.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/xml/XmlMetaEntity.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/supresswarnings/SuppressWarningsAnnotationGeneratedTest.java
> HHH-17772 more work on repositories

- tooling/metamodel-generator/hibernate-jpamodelgen.gradle
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/ClassWriter.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/Context.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/JPAMetaModelEntityProcessor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaAttribute.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaMap.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaPackage.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaType.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/DataAnnotationMetaAttribute.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/DataMetaAttributeGenerationVisitor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/DefaultConstructor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/LifecycleMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/MetaAttributeGenerationVisitor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/NameMetaAttribute.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/NamedQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/RepositoryConstructor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/model/Metamodel.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/BasicAttributeVisitor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/TypeUtils.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/validation/MockEntityPersister.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/validation/MockSessionFactory.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/xml/XmlMetaEntity.java
> HHH-17772 Jakarta Data static metamodel

- hibernate-core/src/main/java/org/hibernate/annotations/processing/Find.java
- hibernate-core/src/main/java/org/hibernate/annotations/processing/HQL.java
- hibernate-core/src/main/java/org/hibernate/annotations/processing/SQL.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/CriteriaFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/DefaultConstructor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/LifecycleMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/QueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/Constants.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/dao/Dao.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/data/BookAuthorRepository.java
> allow query and finder methods to return Optional

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/Constants.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/data/BookAuthorRepository.java
> HHH-17772 support Jakarta Data PageRequest as a parameter

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/CriteriaFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/OrderBy.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/QueryMethod.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/data/BookAuthorRepository.java
> HHH-17772 support @OrderBy for @Query methods

- documentation/src/main/asciidoc/userguide/appendices/BestPractices.adoc
- documentation/src/main/asciidoc/userguide/chapters/batch/Batching.adoc
- documentation/src/main/asciidoc/userguide/chapters/domain/identifiers.adoc
- documentation/src/main/asciidoc/userguide/chapters/fetching/Fetching.adoc
- documentation/src/main/asciidoc/userguide/chapters/query/native/Native.adoc
- hibernate-core/src/main/java/org/hibernate/annotations/BatchSize.java
- hibernate-core/src/main/java/org/hibernate/id/enhanced/NoopOptimizer.java
https://hibernate.atlassian.net/browse/HHH-17775
> HHH-17775 Standardize spelling of "round-trip" & "roundtrip" to "round trip"

- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/LazyProxyWithCollectionTest.java
https://hibernate.atlassian.net/browse/HHH-17750
> HHH-17750 JPA entities containing LAZY loaded relations cannot be merged in another transaction

- hibernate-core/src/main/java/org/hibernate/engine/spi/EffectiveEntityGraph.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
- hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java
- hibernate-core/src/main/java/org/hibernate/query/KeyedPage.java
- hibernate-core/src/main/java/org/hibernate/query/KeyedResultList.java
- hibernate-core/src/main/java/org/hibernate/query/Page.java
- hibernate-core/src/main/java/org/hibernate/query/Query.java
- hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java
- hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/NodeBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/AbstractSqmSelectionQuery.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/KeyBasedPagination.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/KeyedResult.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/spi/DelegatingSqmSelectionQueryImplementor.java
- hibernate-core/src/test/java/org/hibernate/orm/test/paging/keybased/KeyBasedPagingTest.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/CriteriaFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/QueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/Constants.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/keypage/Book.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/keypage/Dao.java
Needed for Jakarta Data
https://hibernate.atlassian.net/browse/HHH-17779
> HHH-17779 New key-based pagination API

- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/BooleanJavaType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/type/java/BooleanJavaTypeDescriptorTest.java
Can handle NULL for a boolean value (e.g. NULL relational value for java boolean "false")
https://hibernate.atlassian.net/browse/HHH-17275
> HHH-17275: Fix NPE in BooleanJavaType for converter returning NULL

- hibernate-core/src/main/java/org/hibernate/query/IllegalQueryOperationException.java
- hibernate-core/src/main/java/org/hibernate/query/KeyedPage.java
- hibernate-core/src/main/java/org/hibernate/query/KeyedResultList.java
- hibernate-core/src/main/java/org/hibernate/query/Order.java
- hibernate-core/src/main/java/org/hibernate/query/Page.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/AbstractSqmSelectionQuery.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/KeyBasedPagination.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/KeyedResult.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
- hibernate-core/src/test/java/org/hibernate/orm/test/paging/keybased/KeyBasedPagingTest.java
https://hibernate.atlassian.net/browse/HHH-17779
> improvements to key-based pagination

- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/TimeZoneJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ZoneIdJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ZoneOffsetJavaType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/TimeZoneMappingTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/ZoneOffsetMappingTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/type/java/ZoneMappingTests.java
https://hibernate.atlassian.net/browse/HHH-17726
> HHH-17726 Additional java types missing same type in wrap/unwrap

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/CriteriaFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/IdFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/NaturalIdFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/QueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/Constants.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/dao/DaoTest.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/data/BookAuthorRepository.java
> HHH-17772 support KeysetAwareSlice from Jakarta Data

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/CriteriaFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/QueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/Constants.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/data/BookAuthorRepository.java
> HHH-17772 support KeysetAwarePage from Jakarta Data

- hibernate-core/src/main/java/org/hibernate/annotations/processing/Find.java
- hibernate-core/src/main/java/org/hibernate/annotations/processing/HQL.java
- hibernate-core/src/main/java/org/hibernate/query/KeyedPage.java
- hibernate-core/src/main/java/org/hibernate/query/Order.java
- hibernate-core/src/main/java/org/hibernate/query/Page.java
- hibernate-core/src/main/java/org/hibernate/query/package-info.java
https://hibernate.atlassian.net/browse/HHH-17779
> HHH-17779 update Javadoc

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/Constants.java
> HHH-17772 support Jakarta Data Page and Slice as return types

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/CriteriaFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/IdFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/NaturalIdFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/QueryMethod.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/data/BookAuthorRepository.java
> rework of sorting, now I understand JD spec better

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/Context.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/JPAMetaModelEntityProcessor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/DefaultConstructor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/RepositoryConstructor.java
> HHH-17772 new approach to PU injection in Quarkus

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/CriteriaFinderMethod.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/dao/Dao.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/data/BookAuthorRepository.java
> HHH-17772 allow array as return type for @Find methods

- tooling/metamodel-generator/hibernate-jpamodelgen.gradle
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/jpamodelgen/test/data/data/Author.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/jpamodelgen/test/data/data/Book.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/jpamodelgen/test/data/data/BookAuthorRepository.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/jpamodelgen/test/data/data/DataTest.java
thanks @FroMage and others for giving me an example of how to do this
> tests for Jakarta Data

- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/jpamodelgen/test/data/data/BookAuthorRepository.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/jpamodelgen/test/data/data/DataTest.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/DataAnnotationMetaAttribute.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/LifecycleMethod.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/util/TestUtil.java
This is useless for us, but JD requires it.
> support returning argument from lifecycle method

- documentation/src/main/asciidoc/querylanguage/Concepts.adoc
- documentation/src/main/asciidoc/querylanguage/extras/on_conflict_bnf.txt
- documentation/src/main/asciidoc/querylanguage/extras/statement_insert_bnf.txt
- hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotationBinder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/insert/SqmConflictClause.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/InsertConflictOnConstraintTest.java
https://hibernate.atlassian.net/browse/HHH-17795
> HHH-17795 fix NPE in 'on conflict on constraint'

- hibernate-core/src/test/java/org/hibernate/orm/test/unionsubclass/UnionSubclassTest.java
https://hibernate.atlassian.net/browse/HHH-17800
> HHH-17800 Fix CockroachDB transaction error when forcing connection acquisition

- hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
- hibernate-core/src/test/java/org/hibernate/dialect/H2DialectDatabaseVersionTest.java
https://hibernate.atlassian.net/browse/HHH-17791
> HHH-17791 Support SNAPSHOT versions of H2

- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/AbstractSchemaMigrator.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/AbstractSchemaValidator.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/GroupedSchemaMigratorImpl.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/GroupedSchemaValidatorImpl.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/IndividuallySchemaMigratorImpl.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/IndividuallySchemaValidatorImpl.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaCreatorImpl.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaDropperImpl.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaTruncatorImpl.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/spi/ExecutionOptions.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/spi/SchemaManagementToolCoordinator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schemafilter/SchemaFilterProviderTest.java
https://hibernate.atlassian.net/browse/HHH-17763
> HHH-17763 Hibernate Schema Validation filter is not working after upgrading to Hibernate 6

- hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/internal/StandardJdbcMutationExecutor.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/InsertConflictOnConstraintTest.java
> fix some constraint name extractors, and improve matching of constraint name in 'on conflict on constraint'

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/sql/InFragment.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
https://hibernate.atlassian.net/browse/HHH-17804
> HHH-17804 treat 'null in ()' correctly

- hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java
https://hibernate.atlassian.net/browse/HHH-17789
> HHH-17789 fix the blob/clob/nclob not free caused hana memory issue

- hibernate-core/src/main/java/org/hibernate/dialect/DerbySqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/HSQLSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQuerySpec.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/subquery/SubqueryTests.java
https://hibernate.atlassian.net/browse/HHH-17776
> HHH-17776 - Add test and fix

- CONTRIBUTING.md
Updated Jira Pull Request Handling and cleaned up some grammer issues.
https://hibernate.atlassian.net/browse/HHH-17794
> HHH-17794 Updated CONTRIBUTING guide

- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/PredicateTest.java
https://hibernate.atlassian.net/browse/HHH-17804
> HHH-17804 add tests for 'null in ()'

- tooling/metamodel-generator/hibernate-jpamodelgen.gradle
https://hibernate.atlassian.net/browse/HHH-17805
> HHH-17805 Fix new hibernate-jpamodelgen source set compilation and test with JDK >= 17

- hibernate-core/src/main/java/org/hibernate/jpa/HibernateHints.java
- hibernate-core/src/main/java/org/hibernate/query/spi/AbstractCommonQueryContract.java
https://hibernate.atlassian.net/browse/HHH-17797
> HHH-17797 support query hint database indexes

- hibernate-vector/src/main/java/org/hibernate/vector/VectorJdbcType.java
https://hibernate.atlassian.net/browse/HHH-17808
> HHH-17808 NPE when null vector is read with VectorJdbcType

- hibernate-core/src/main/java/org/hibernate/dialect/function/array/ArrayArgumentValidator.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/array/ArrayContainsArgumentValidator.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/QueryMethod.java
- tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/hqlsql/Dao.java
Also fix an NPE in the validation of arguments to `array_contains()`.
https://hibernate.atlassian.net/browse/HHH-17807
> HHH-17807 array-typed parameters in query methods

- hibernate-core/src/main/java/org/hibernate/dialect/DerbySqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/HSQLSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQuerySpec.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/subquery/SubqueryTests.java
https://hibernate.atlassian.net/browse/HHH-17776
> HHH-17776 - Add test, fix and fix whitespace padding issues on hsql and derby

- databases/mssqlserver/matrix.gradle
https://hibernate.atlassian.net/browse/HHH-17813
> HHH-17813 Update SQL Server JDBC driver to 12.6.1

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/SimpleFromClauseAccessImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/notfound/ignore/NotFoundManyToOneCountTest.java
https://hibernate.atlassian.net/browse/HHH-17638
> HHH-17638 OneToMany association annotated with @NotFound generates different JOINs for SELECT and COUNT

- tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java
> use e.printStackTrace(PrintWriter)

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
> detect use of custom SQL with @DynamicInsert/@DynamicUpdate

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/discriminator/JoinedInheritanceDiscriminatorSelectionTest.java
https://hibernate.atlassian.net/browse/HHH-17806
> HHH-17806 Reduce the number of unnecessary joins with `JOINED` inheritance and parameterized discriminator predicates

- tooling/hibernate-enhance-maven-plugin/src/main/java/org/hibernate/orm/tooling/maven/MavenEnhancePlugin.java
- tooling/hibernate-enhance-maven-plugin/src/main/resources/META-INF/maven/org.hibernate.orm.tooling/hibernate-enhance-maven-plugin/plugin-help.xml
- tooling/hibernate-enhance-maven-plugin/src/main/resources/META-INF/maven/plugin.xml
- tooling/hibernate-enhance-maven-plugin/src/test/java/org/hibernate/orm/tooling/maven/MavenEnhancePluginTest.java
- tooling/hibernate-gradle-plugin/src/main/java/org/hibernate/orm/tooling/gradle/enhance/EnhancementHelper.java
- tooling/hibernate-gradle-plugin/src/main/java/org/hibernate/orm/tooling/gradle/enhance/EnhancementSpec.java
https://hibernate.atlassian.net/browse/HHH-17817
> HHH-17817 - Add option to Enable Byte Code Enhancement for specific classes

- hibernate-core/src/test/java/org/hibernate/orm/test/schemafilter/SchemaFilterProviderTest.java
https://hibernate.atlassian.net/browse/HHH-17763
> HHH-17763 Run test for schema filter provider only on H2

- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/IdFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/NaturalIdFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/QueryMethod.java
also fix up some newline handling
> implement support for requestTotals() in processor

- hibernate-core/src/main/java/org/hibernate/annotations/BatchSize.java
- hibernate-core/src/main/java/org/hibernate/binder/AttributeBinder.java
- hibernate-core/src/main/java/org/hibernate/binder/TypeBinder.java
- hibernate-core/src/main/java/org/hibernate/binder/internal/BatchSizeBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotationBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnyBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/OneToOneSecondPass.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyPreloadedData.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/InFlightMetadataCollector.java
- hibernate-core/src/main/java/org/hibernate/mapping/Collection.java
- hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
- hibernate-core/src/main/java/org/hibernate/mapping/Property.java
- hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java
- hibernate-core/src/test/java/org/hibernate/orm/test/any/annotations/AnyTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/DepthOneBatchTest.java
introduce BatchSizeBinder to prove it works
various cleanups in binders + mapping package
https://hibernate.atlassian.net/browse/HHH-17831
> HHH-17831 make AttributeBinder work for collections and @Any

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/AbstractPropertyHolder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/ComponentPropertyHolder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/registry/classloading/internal/ClassLoaderServiceImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
- hibernate-core/src/main/java/org/hibernate/mapping/JoinedSubclass.java
- hibernate-core/src/main/java/org/hibernate/mapping/RootClass.java
- hibernate-core/src/main/java/org/hibernate/mapping/SingleTableSubclass.java
- hibernate-core/src/main/java/org/hibernate/mapping/Subclass.java
- hibernate-core/src/main/java/org/hibernate/mapping/UnionSubclass.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/inheritance/mixed/Document.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/override/inheritance/EntityInheritanceAttributeOverrideTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/binding/annotations/attributeOverrides/TablePerClassOverrideTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cfg/AnnotationBinderTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/filter/subclass/singletable/Human.java
- hibernate-core/src/test/java/org/hibernate/orm/test/filter/subclass/singletable/Mammal.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/discriminator/embeddable/SingleTableWithEmbeddableTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/insertordering/InsertOrderingWithSecondaryTable.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/Elephant.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/Human.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/components/EntitySuperclassComponentWithCollectionTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hhh12076/AnnotationMappingJoinClassTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/joinorder/JoinOrderTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/treat/DiscriminatedTreatSmokeTesting.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/treat/DiscriminatedTreatSqmSmokeTesting.java
- hibernate-core/src/test/java/org/hibernate/orm/test/tool/schema/IndividuallySchemaValidatorImplTest.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/manytoone/lazy/ChildUser.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/entities/onetomany/detached/ListJoinColumnBidirectionalInheritanceRefEdChildEntity.java
- hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/EntityManagerFactoryBasedFunctionalTest.java
Finally decided to just put an end to this because it's bad and that's that.
https://hibernate.atlassian.net/browse/HHH-17833
> HHH-17833 change log warnings for invalid mappings to exceptions

- hibernate-core/src/main/java/org/hibernate/query/Order.java
- hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java
https://hibernate.atlassian.net/browse/HHH-17773
> HHH-17773 review and improve API of Order class

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/BasicFormatterImpl.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/JoinedInheritanceTreatedJoinNullnessTest.java
https://hibernate.atlassian.net/browse/HHH-17711
> HHH-17711 Multiple level joined inheritance leads to incorrect discriminator alias

- hibernate-core/src/main/java/org/hibernate/jdbc/Expectation.java
- hibernate-core/src/main/java/org/hibernate/jdbc/Expectations.java
- hibernate-core/src/main/java/org/hibernate/jdbc/package-info.java
https://hibernate.atlassian.net/browse/HHH-15587
> HHH-15587 some enhancements and cleanups to Expectations stuff

- hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
- hibernate-core/src/test/java/org/hibernate/orm/test/hql/SelectWithFkInPackageTest.java
https://hibernate.atlassian.net/browse/HHH-17823
I'm not sure if there's a simple way to get all of those possible keywords from the HqlParser list so the test isn't that nice 😔
> HHH-17823 Add FK to identifier in HQL parser

- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmPath.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/CriteriaIsNullTest.java
https://hibernate.atlassian.net/browse/HHH-17671
> HHH-17671 Test and fix for SqmPredicate copy failure

- documentation/src/main/asciidoc/userguide/chapters/envers/Envers.adoc
https://hibernate.atlassian.net/browse/HHH-17839
> HHH-17839 remove reference to org.hibernate.envers.using_modified_flag

- hibernate-core/src/main/java/org/hibernate/boot/beanvalidation/TypeSafeActivator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/beanvalidation/Address.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/beanvalidation/DDLTest.java
https://hibernate.atlassian.net/browse/HHH-14810
I've worked on the content of the issue. Please comment if there's anything to modify.
and, I hope everyone here has a happy day. 🎄
> HHH-14810 @NotBlank and @NotEmpty were used, "NOT NULL" option wasn't add in generated DDL.

- hibernate-core/src/main/java/org/hibernate/persister/collection/OneToManyPersister.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/collections/OrderColumnListIndexBaseTest.java
See Jira issue [HHH-17600](https://hibernate.atlassian.net/browse/HHH-17600)
[HHH-17600]: https://hibernate.atlassian.net/browse/HHH-17600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HHH-17600 - Annotation @ListIndexBase is not properly handled

- hibernate-core/src/main/java/org/hibernate/annotations/SQLDelete.java
- hibernate-core/src/main/java/org/hibernate/annotations/SQLDeleteAll.java
- hibernate-core/src/main/java/org/hibernate/annotations/SQLInsert.java
- hibernate-core/src/main/java/org/hibernate/annotations/SQLUpdate.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/customsql/CustomSqlPrimaryTableExplicitTest.java
just cleaning up a TODO I left behind a while ago
https://hibernate.atlassian.net/browse/HHH-17848
> HHH-17848 tolerate primary table name in @SqlXxxx annotations

- tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/xml/XmlParserHelper.java
Fixes https://hibernate.atlassian.net/browse/HHH-17579
Tested OK against the https://github.com/laurentschoelens/hibernate-orm-xml-java11 repository
> HHH-17579 fix classloader issues with JAXBContext since JDK11

- hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/ByteBuddyProxyHelper.java
Update code to replace deprecated Byte Buddy code
with replacement.
https://hibernate.atlassian.net/browse/HHH-17596
> HHH-17596 Use new Byte Buddy API

- hibernate-core/src/main/java/org/hibernate/annotations/Comments.java
- hibernate-core/src/main/java/org/hibernate/boot/model/relational/QualifiedNameParser.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Address.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Author.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Book.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/EgTest.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Library.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Publisher.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Type.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/Constants.java
- overloaded lifecycle methods
- handling of delimited compound names
- some missing imports
https://hibernate.atlassian.net/browse/HHH-17853
https://hibernate.atlassian.net/browse/HHH-17851
> HHH-17851, HHH-17853 fix three bugs in Jakarta Data impl

- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/PluralAttributeMappingImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/internal/TableGroupJoinHelper.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ql/JoinTableOptimizationTest.java
https://hibernate.atlassian.net/browse/HHH-17830
> HHH-17830 Fix rendering custom predicate for element collection joins

- documentation/src/main/asciidoc/querylanguage/Expressions.adoc
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLiteSqlAstTranslator.java
- hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlLexer.g4
- hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
- hibernate-core/src/main/java/org/hibernate/dialect/function/SqlColumn.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/spi/ConnectionProvider.java
- hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java
- hibernate-core/src/main/java/org/hibernate/property/access/internal/AccessStrategyHelper.java
- hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyBackRefImpl.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
- hibernate-testing/src/main/java/org/hibernate/testing/orm/domain/gambit/EntityOfBasics.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java
https://hibernate.atlassian.net/browse/HHH-17858
https://hibernate.atlassian.net/browse/HHH-17859
> HHH-17859, HHH-17858 function() and column() functions

- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/BookAuthorRepository.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaFinderMethod.java
- tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/dao/Dao.java
exactly as I'm proposing for Jakarta Data
> treat a multivalued param of @Find method as an 'in' condition

- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/where/OneToManySQLRestrictionTests.java
https://hibernate.atlassian.net/browse/HHH-17854
> HHH-17854 Avoid adding plural attribute restrictions multiple times

- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/BookAuthorRepository.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/QueryMethod.java
- tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/hqlsql/Dao.java
This is being proposed for Jakarta Data
> allow @Query/@HQL/@SQL methods to return an array type

- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/BookAuthorRepository.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/EgTest.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Library.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
this is a bit of a wart, and I hope we can find a better solution eventually
for now, let's just implement it
> add support for Jakarta Data @By("#id")

- documentation/src/main/asciidoc/introduction/Generator.adoc
- hibernate-core/src/main/java/org/hibernate/annotations/processing/Pattern.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/Constants.java
- tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/dao/Dao.java
https://hibernate.atlassian.net/browse/HHH-17868
> HHH-17868 introduce @Pattern annotation

- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/keypage/Dao.java
- tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/keypage/KeyBasedTest.java
- tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/keypage/Queries.java
> fix and test for KeyedResultList with EntityManager

- hibernate-core/src/main/java/org/hibernate/internal/log/DeprecationLogger.java
- hibernate-core/src/main/java/org/hibernate/query/sql/internal/ParameterParser.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/ParameterParserTest.java
https://hibernate.atlassian.net/browse/HHH-17759
> HHH-17759 Avoid need for undocumented escaping of colon characters in native queries

- hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java
https://hibernate.atlassian.net/browse/HHH-17779
> HHH-17779 Add UnsupportedOperationException throwing impl of getKeyedResultList to the AbstractQuery

- hibernate-core/src/main/java/org/hibernate/annotations/GenericGenerator.java
- hibernate-core/src/main/java/org/hibernate/annotations/GenericGenerators.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorBinder.java
- hibernate-core/src/main/java/org/hibernate/id/factory/internal/IdentifierGeneratorUtil.java
https://hibernate.atlassian.net/browse/HHH-17874
> HHH-17874 deprecate @GenericGenerator

- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/superdao/Book.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/superdao/Repo.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/superdao/SuperRepo.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/superdao/SuperRepoTest.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/superdao/generic/Book.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/superdao/generic/Repo.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/superdao/generic/SuperRepo.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/superdao/generic/SuperRepoTest.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/DefaultConstructor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/RepositoryConstructor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/TypeUtils.java
- tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/superdao/Book.java
- tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/superdao/Dao.java
- tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/superdao/SuperDao.java
- tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/superdao/SuperDaoTest.java
- tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/superdao/generic/Book.java
- tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/superdao/generic/Dao.java
- tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/superdao/generic/SuperDao.java
- tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/superdao/generic/SuperDaoTest.java
Needed for Jakarta Data, and useful. Limited to single inheritance for now, but that will have to be fixed.
https://hibernate.atlassian.net/browse/HHH-17873
> HHH-17873 repository inheritance and generics

- hibernate-core/src/main/java/org/hibernate/annotations/processing/Suppress.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetoone/ShowDescription.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/DataMetaAttributeGenerationVisitor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/MetaAttributeGenerationVisitor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/Constants.java
https://hibernate.atlassian.net/browse/HHH-17875
> HHH-17875 validate association mappings in processor

- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/BookAuthorRepository.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Bookshop.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Library.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/superdao/generic/SuperRepo.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractCriteriaMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaDeleteMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/QueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/Constants.java
https://hibernate.atlassian.net/browse/HHH-17860
> HHH-17860 query-based @Delete

- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
https://hibernate.atlassian.net/browse/HHH-17860
> HHH-17860 report bad return type for @Delete

- tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/DataAnnotationMetaAttribute.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/DataMetaAttributeGenerationVisitor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/Constants.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/TypeUtils.java
https://hibernate.atlassian.net/browse/HHH-17864
> HHH-17864 generate static metamodel fields for embeddables

- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractCriteriaMethod.java
because I got a requirement removed from spec
> simplification to JD generated code

- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
We want them to have interceptors.
> move Quarkus Repositories to normal scope

- tooling/metamodel-generator/hibernate-jpamodelgen.gradle
> add missing processor dependencies that are needed in Maven

- hibernate-core/src/main/java/org/hibernate/id/Assigned.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractCriteriaMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaDeleteMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/QueryMethod.java
squashes a deprecation warning in Maven
> use createMutationQuery() and createSelectionQuery()

- gradle/gradle-enterprise.gradle
- local-build-plugins/build.gradle
- local-build-plugins/src/main/java/org/hibernate/orm/env/EnvironmentSettingsPlugin.java
- local-build-plugins/src/main/java/org/hibernate/orm/toolchains/JdkVersionSettingsPlugin.java
- settings.gradle
https://hibernate.zulipchat.com/#narrow/stream/132094-hibernate-orm-dev/topic/rootProject.2Eproperties.20in.20gradle-enterprise.2Egradle
> Fix Develocity tags

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorBinder.java
- hibernate-core/src/main/java/org/hibernate/id/factory/internal/IdentifierGeneratorUtil.java
- hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/SequenceOrAssignedGeneratorTest.java
https://hibernate.atlassian.net/browse/HHH-17878
> HHH-17878 Enable Configurable identifier generators to work with @IdGeneratorType

- hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaIsolationDelegate.java
Hey hey 😃,
I was looking into a bug reported on the Quarkus side, and I've noticed that there can be this situation when we'd try to throw an exception here:
https://github.com/hibernate/hibernate-orm/blob/24db2b04ccf328618d33d47ba108be8bce5e799c/hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaIsolationDelegate.java#L185-L187
But because we are trying to do that within the `JdbcEnvironmentInitiator` things aren't yet fully initialized 🙈 which leads to a null pointer and can hide an actual problem 😕 
soooo, my thinking here was that it'd be better to create a helper relying on a default converter rather than fail like:
```
2024-02-20 10:36:04,960 WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (JPA Startup Thread) HHH000342: Could not obtain …
```
> HHH-17872 Make sure that JdbcServicesImpl does not return a null SqlExceptionHelper

- hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/InferredBasicValueResolver.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayPositionTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/EntityWithArrays.java
- hibernate-core/src/test/java/org/hibernate/orm/test/function/array/Label.java
https://hibernate.atlassian.net/browse/HHH-17801
> HHH-17801 Resolve enum basic types to avoid type validation issues

- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/JoinedInheritanceToOneSameHierarchyTest.java
https://hibernate.atlassian.net/browse/HHH-17867
Test only, already fixed by #7815.
> HHH-17867 WrongClassException when trying to query by the base type with joined inheritance type

- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
> support for 'id(this)'

- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/EgTest.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Publishers.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
> test and fix for bug in repo method parameter checking

- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Bookshop.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Library.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/ClassWriter.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractAnnotatedMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractCriteriaMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaPackage.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaDeleteMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/IdFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/LifecycleMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/NaturalIdFinderMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/QueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/model/MetaAttribute.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/model/Metamodel.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/xml/XmlMetaEntity.java
as required by the spec
https://hibernate.atlassian.net/browse/HHH-17891
> HHH-17891 support toplevel interceptors for JD repositories

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
Fix for InformixDialect
https://hibernate.atlassian.net/browse/HHH-14080
> HHH-14080 Dialect-Aware Rendering of Null Value Literals

- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
I guess this must have slipped through :)
> Update javax.transaction to jakarta.transaction

- .github/workflows/atlas.yml
- .github/workflows/codeql.yml
- .github/workflows/contributor-build.yml
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/QualifiedJoinPathConsumer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/CteTests.java
https://hibernate.atlassian.net/browse/HHH-17897
> HHH-17897 Fix support for joining CTEs in HQL

- ci/build.sh
- ci/database-start.sh
- docker_db.sh
- gradle/databases.gradle
https://hibernate.atlassian.net/browse/HHH-17736
> HHH-17736 Improve Atlas for atps

- hibernate-core/src/main/java/org/hibernate/boot/jaxb/hbm/transform/HbmXmlTransformer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/boot/jaxb/JaxbHelper.java
- hibernate-core/src/test/java/org/hibernate/orm/test/boot/jaxb/hbm/BasicComposition.java
- hibernate-core/src/test/java/org/hibernate/orm/test/boot/jaxb/hbm/BasicEntity.java
- hibernate-core/src/test/java/org/hibernate/orm/test/boot/jaxb/hbm/BasicTransformationTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/boot/jaxb/hbm/TransformationHelper.java
- hibernate-core/src/test/java/org/hibernate/orm/test/boot/jaxb/mapping/BasicMappingJaxbTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/boot/jaxb/mapping/HbmTransformationJaxbTests.java
- hibernate-core/src/test/resources/mappings/hbm/basic.xml
- hibernate-core/src/test/resources/mappings/hbm/simple.xml
HHH-17429 - Complete implementation of HbmXmlTransformer (6.x)
HHH-16822 - Fail to marshall transformed content with HbmXmlTransformer
> HHH-17429 - Complete implementation of HbmXmlTransformer (6.x)

- hibernate-core/src/main/java/org/hibernate/mapping/Any.java
- hibernate-core/src/test/java/org/hibernate/orm/test/associations/any/ManyToAnySubClassAccessPropertyTest.java
https://hibernate.atlassian.net/browse/HHH-17871
Problem : keyMapping and metaMapping are null, when the Any is compared
Correction : nullSafe
> HHH-17871 Error if defining a ManyToAny in the child classes which references a @MappedSuperclass

- hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java
- hibernate-core/src/main/java/org/hibernate/usertype/DynamicParameterizedType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/type/dynamicparameterized/DynamicParameterizedTypeTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/type/dynamicparameterized/Entity3.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/type/dynamicparameterized/MyGenericType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/type/dynamicparameterized/MyStringType.java
https://hibernate.atlassian.net/browse/HHH-12202
> HHH-12202 Introduce `ParameterType.getReturnedJavaType()` as companion of `getReturnedClass()`

- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/AbstractNegatableSqmPredicate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmLikePredicate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmNegatedPredicate.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/NegatedPredicateTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/WithJpaComplianceNegatedPredicateTest.java
https://hibernate.atlassian.net/browse/HHH-17493
> HHH-17493 - add tests and fix

- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLEnumJdbcType.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/converter/internal/EnumHelper.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/internal/NativeEnumDdlTypeImpl.java
https://hibernate.atlassian.net/browse/HHH-17884
https://hibernate.atlassian.net/browse/HHH-17906
> HHH-17884 Respect ordering guarantee of ORDINAL/STRING when using native enums

- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/JpaMetamodel.java
- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java
- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappingMetamodelImpl.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/JpaTupleElement.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/BasicDotIdentifierConsumer.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/basic/Author.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/basic/Book.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/basic/BookAuthorRepository.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/basic/DataTest.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Library.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/ProcessorSessionFactory.java
This is a rough start on HHH-17901 and HHH-17782, to get these things at least working.
> HHH-17901, HHH-17782 make fully-qualified enum literals in @Query pass the validation

- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Publishers.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
add a test for empty query string in @Query
> fix a bug in @Query handling

- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappingMetamodelImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/hql/InSubqueryPredicateAnonymousTupleTest.java
https://hibernate.atlassian.net/browse/HHH-17803
> HHH-17803 NPE in TupleMappingModelExpressible constructor when enum is used in "in" clause tuple within subquery

- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java
as required by Jakarta Data TCK
> tolerate badly-typed PageRequest parameters

- documentation/src/main/asciidoc/userguide/chapters/tooling/modelgen.adoc
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/ClassWriter.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/Context.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java
- tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/supresswarnings/SuppressExplicitWarningsAnnotationGeneratedTest.java
https://hibernate.atlassian.net/browse/HHH-17882
> HHH-17882 accept a list of warnings to suppress in addSuppressWarningsAnnotation

- migration-guide.adoc
Let's get CI running
https://hibernate.atlassian.net/browse/HHH-17460
> HHH-17460 - Ongoing JPA 32 work

- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java
> simplify the generated code for cursored pagination

- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/RepositoryConstructor.java
at least when `jakarta.inject` is available
> when CDI is missing, do still add an @Inject annotation on the constructor

- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
don't think this is even strictly-speaking required by Jakarta Data but we will allow it
> fix to @OrderBy for @Query methods with primary entity type

- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/namedquery/Author.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/namedquery/Book.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/namedquery/BookAuthorRepository$.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/namedquery/BookAuthorRepository.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/namedquery/NamedQueryTest.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
for our work on the Jakarta Data TCK
Alternative to #8084.
> support for queries defined in intermediate classes

- hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/NamedConverterResolution.java
- hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java
- hibernate-core/src/main/java/org/hibernate/metamodel/internal/AttributeFactory.java
- hibernate-core/src/main/java/org/hibernate/type/internal/CustomMutabilityConvertedPrimitiveBasicTypeImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/ConvertedPrimitiveAttributeAsFunctionArgumentTest.java
https://hibernate.atlassian.net/browse/HHH-17835
> HHH-17835 Converted primitive boolean columns can no longer be used in comparable functions

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/QueryBinder.java
I took the occasion and also deleted few unused methods, the fix is the `createStoredProcedure` change.
https://hibernate.atlassian.net/browse/HHH-17460
>  HHH-17460 - Ongoing JPA 32 work

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/SubQueryInFromTests.java
https://hibernate.atlassian.net/browse/HHH-17898
> HHH-17898 Throw error if non-lateral from-clause subquery uses outer from node

- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderHelper.java
- hibernate-core/src/test/java/org/hibernate/orm/test/locking/LockExistingBytecodeProxyTest.java
https://hibernate.atlassian.net/browse/HHH-17828
> HHH-17828 Find and locking a lazy referenced entity fails with Bytecode Enhancement enabled

- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderHelper.java
- hibernate-core/src/test/java/org/hibernate/orm/test/locking/ExplicitLockingTest.java
https://hibernate.atlassian.net/browse/HHH-16672
> HHH-16672 Locking entities created in the same transaction fails

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/naturalid/QueryWithProxyAsParametersTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/naturalid/QueryWithProxyAsParametersTest.java
https://hibernate.atlassian.net/browse/HHH-17881
> HHH-17881 Unable to use a proxy as parameter in Query when the FK does not target the PK

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractEmbeddableMapping.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddableMappingTypeImpl.java
- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/NavigableRole.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/binding/annotations/embedded/Address.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/binding/annotations/embedded/AddressBis.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/binding/annotations/embedded/EmbeddedTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/binding/annotations/embedded/Person.java
https://hibernate.atlassian.net/browse/HHH-17885
> HHH-17885 Same named attribute of different Embedded uses same selection expression

- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Bookshop.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/namedquery/Book.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/namedquery/BookAuthorRepository$.java
- tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/namedquery/BookAuthorRepository.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
- fix bug importing type arguments in @Query methods
- consider indirectly-implemented interfaces in determining primary entity type
> more fixes for Jakarta Data TCK

- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
and with Scott's preprocessor
produce WARNINGs instead of ERRORs in some cases
> better cooperation with other Jakarta Data implementations

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/QueryToManyWithNestedToOneTest.java
https://hibernate.atlassian.net/browse/HHH-17857
> HHH-17857 Query with consecutive OneToMany and ManyToOne join will fail with AssertionError

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/QueryToManyWithNestedToOneTest.java
https://hibernate.atlassian.net/browse/HHH-17857
Backport of #8114
> HHH-17857 Query with consecutive OneToMany and ManyToOne join will fail with AssertionError 

- hibernate-core/src/main/java/org/hibernate/internal/ScrollableResultsImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/iterate/ForwardOnlyScrollNoTransactionTest.java
https://hibernate.atlassian.net/browse/HHH-17826
> HHH-17826 ResultSet closed while scrolling results

- hibernate-core/src/main/java/org/hibernate/result/internal/OutputsImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/DeferredResultSetAccess.java
- hibernate-core/src/test/java/org/hibernate/orm/test/connections/ConnectionCloseAfterStatementTest.java
https://hibernate.atlassian.net/browse/HHH-17887
backport of https://github.com/hibernate/hibernate-orm/pull/8111 to 6.4
> HHH-17887 Release mode After Statment with deferred result set access does not work

- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/delegate/GeneratedWritableDelegateTest.java
https://hibernate.atlassian.net/browse/HHH-10921
Backport of #8134
> Test case for HHH-10921 - Support generated values via returning clause

- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java
> update generated pagination code to new JD PageRequest API

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/JoinedInheritanceCircularBiDirectionalFetchTest.java
https://hibernate.atlassian.net/browse/HHH-17832
> HHH-17832 Select with circular bidirectional association with joined inheritance subclass SyntaxErrorException

- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/DomainParameterXref.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/MultiTypedBasicAttributesEntity.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/ParameterTest.java
https://hibernate.atlassian.net/browse/HHH-17912
> HHH-17912 Disallow multiple valued binding for BasicCollectionType

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/EnhancementAsProxyLazinessInterceptor.java
- hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/EntityHolder.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/caching/CachingBatchLoadNoProxiesAndCircularRelationshipTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/manytoone/ManyToOneBidirectionalEagerTest.java
https://hibernate.atlassian.net/browse/HHH-17783
https://hibernate.atlassian.net/browse/HHH-17918
Backport of #8149
> HHH-17783, HHH-17918 - Allow early initialization of entity instance by non-owning initializer

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/EnhancerConstants.java
- hibernate-core/src/main/java/org/hibernate/bytecode/internal/BytecodeEnhancementMetadataPojoImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java
- hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryContext.java
- hibernate-core/src/main/java/org/hibernate/engine/internal/ManagedTypeHelper.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/ManagedEntity.java
- hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/version/SimpleEntity.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/basic/BasicSessionTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/merge/MergeEnhancedEntityDynamicUpdateTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/merge/MergeEnhancedEntityTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cache/ByteCodeEnhancedImmutableReferenceCacheTest.java
https://hibernate.atlassian.net/browse/HHH-17761
> HHH-17761 Merging a bytecode enhaced entity with all properties set to null does not apply the update 

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java
backport of https://github.com/hibernate/hibernate-orm/pull/8167/commits to 6.5
> Fix sybase LobSchemaUpdateTest failure

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SybaseDialect.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/InformationExtractorJdbcDatabaseMetaDataImpl.java
backport of https://github.com/hibernate/hibernate-orm/pull/8170/commits to 6.5
> Fix SybaseASEDialect column lenght resolution

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultInitializeCollectionEventListener.java
- hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/fetch/FetchTest.java
https://hibernate.atlassian.net/browse/HHH-17953
> HHH-17953 fix StatelessSession.fetch() for empty collection

- hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionDelegatorBaseImpl.java
- hibernate-core/src/main/java/org/hibernate/event/spi/AbstractCollectionEvent.java
- hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/stateless/EagerCollectionInStatelessTest.java
https://hibernate.atlassian.net/browse/HHH-17966
> HHH-17966 EAGER collections in StatelessSession

- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/AbstractSqmRestrictedDmlStatement.java
see https://hibernate.atlassian.net/browse/HHH-17969
(bug exposed by Jakarta Data TCK)
> HHH-17969 fix an NPE that occurred if a criteria delete statement had no predicate

- documentation/src/main/asciidoc/repositories/Repositories.adoc
- hibernate-core/src/main/java/org/hibernate/StatelessSession.java
> talk about lack of lazy fetching in Jakarta Data

- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/CriteriaNoPredicateTest.java
Already fixed in https://github.com/hibernate/hibernate-orm/pull/8190.
https://hibernate.atlassian.net/browse/HHH-17969
> HHH-17969 test for issue

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/TeradataSqlAstTranslator.java
https://hibernate.atlassian.net/browse/HHH-17174
> HHH-17174 Fix empty query string

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/ClassPropertyHolder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/embeddables/generics/CompositeUserTypeInGenericSuperclassTest.java
https://hibernate.atlassian.net/browse/HHH-17916
Backport of #8183
> HHH-17916 CCE when @CompositeType attribute is contained in a generic @MappedSuperclass

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLEnumJdbcType.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLEnumJdbcType.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLOrdinalEnumJdbcType.java
- hibernate-core/src/main/java/org/hibernate/type/SqlTypes.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/converter/internal/EnumHelper.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/EnumJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/EnumJdbcType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/OrdinalEnumJdbcType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/internal/NamedNativeOrdinalEnumDdlTypeImpl.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/internal/NativeOrdinalEnumDdlTypeImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/enumerated/EnumeratedSmokeTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/enumerated/ormXml/OrmXmlEnumTypeTest.java
https://hibernate.atlassian.net/browse/HHH-17884
> HHH-17884 Introduce special SqlTypes constants for ordinal based enums

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLEnumJdbcType.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLEnumJdbcType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/converter/internal/EnumHelper.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/EnumJdbcType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/enumerated/EnumeratedSmokeTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/enumerated/ormXml/OrmXmlEnumTypeTest.java
https://hibernate.atlassian.net/browse/HHH-17884
> HHH-17884 Fix the enum value sorting for EnumeratedType.STRING enums

- hibernate-core/src/main/java/org/hibernate/Session.java
- hibernate-core/src/main/java/org/hibernate/StatelessSession.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultInitializeCollectionEventListener.java
- hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/AbstractSqmRestrictedDmlStatement.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/fetch/FetchTest.java
- tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
https://hibernate.atlassian.net/browse/HHH-17955
https://hibernate.atlassian.net/browse/HHH-17953
> backports from main to 6.5

- hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java
https://hibernate.atlassian.net/browse/HHH-17988
> HHH-17988 MetadataContext should consistently use ClassLoaderService

- hibernate-core/src/main/java/org/hibernate/internal/util/ReflectHelper.java
https://hibernate.atlassian.net/browse/HHH-17987
This brings some surprisingly strong memory savings during bootstrap.
> HHH-17987 Improve allocation rate of ReflectHelper#setterMethodOrNull

- hibernate-core/src/main/java/org/hibernate/action/internal/CollectionRemoveAction.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/EnhancementAsProxyLazinessInterceptor.java
- hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/stateless/StatelessSessionStatisticsTest.java
https://hibernate.atlassian.net/browse/HHH-17984
https://hibernate.atlassian.net/browse/HHH-14968
> HHH-17984 statistics for StatelessSession

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java
https://hibernate.atlassian.net/browse/HHH-17991
> HHH-17991 Reduce overhead from @DialectOverride discovery

- tooling/hibernate-enhance-maven-plugin/src/main/java/org/hibernate/orm/tooling/maven/MavenEnhancePlugin.java
https://hibernate.atlassian.net/browse/HHH-17994
> HHH-17817 defensive check for the case when classNames wasn't set

- hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java
https://hibernate.atlassian.net/browse/HHH-17993
> HHH-17993 Metamodel processing on bootstrap: avoid retrying same metamodel class name multiple times

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/ExecuteUpdateResultCheckStyle.java
- hibernate-core/src/main/java/org/hibernate/internal/util/ReflectHelper.java
- hibernate-core/src/main/java/org/hibernate/jdbc/Expectations.java
- hibernate-core/src/main/java/org/hibernate/mapping/Collection.java
- hibernate-core/src/main/java/org/hibernate/mapping/Join.java
- hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/attributebinder/typebinder/NoResultCheck.java
for Quarkus and @yrodiere
https://hibernate.atlassian.net/browse/HHH-17999
> use Constructor<Expectation> instead of Class<Expectation>

- documentation/src/main/asciidoc/userguide/chapters/domain/entity.adoc
- documentation/src/main/asciidoc/userguide/chapters/domain/extras/entity/entity-concrete-proxy-find.sql
- documentation/src/main/asciidoc/userguide/chapters/domain/extras/entity/entity-concrete-proxy-reference.sql
- hibernate-core/src/main/java/org/hibernate/annotations/ConcreteProxy.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/EntityConcreteTypeLoader.java
- hibernate-core/src/main/java/org/hibernate/loader/internal/IdentifierLoadAccessImpl.java
- hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
- hibernate-core/src/main/java/org/hibernate/mapping/RootClass.java
- hibernate-core/src/main/java/org/hibernate/mapping/Subclass.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityMappingType.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/CaseStatementDiscriminatorMappingImpl.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/AbstractNonJoinedEntityFetch.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchSelectImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/internal/domain/CircularFetchImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/proxy/concrete/AbstractConcreteProxyTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/proxy/concrete/BytecodeConcreteProxyTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/proxy/concrete/LazyOptionalOneToOneConcreteProxyTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/proxy/concrete/ProxyConcreteProxyTest.java
https://hibernate.atlassian.net/browse/HHH-17818
> HHH-17818 Add new ConcreteProxy annotation

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/ExecuteUpdateResultCheckStyle.java
- hibernate-core/src/main/java/org/hibernate/internal/util/ReflectHelper.java
- hibernate-core/src/main/java/org/hibernate/jdbc/Expectations.java
- hibernate-core/src/main/java/org/hibernate/mapping/Collection.java
- hibernate-core/src/main/java/org/hibernate/mapping/Join.java
- hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/attributebinder/typebinder/NoResultCheck.java
https://hibernate.atlassian.net/browse/HHH-17999
> HHH-17999 backport fix to 6.5

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/ByteBuddyEnhancementContext.java
- hibernate-core/src/main/java/org/hibernate/internal/util/ReflectHelper.java
- hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java
- https://hibernate.atlassian.net/browse/HHH-17980
- https://hibernate.atlassian.net/browse/HHH-17987
- https://hibernate.atlassian.net/browse/HHH-17988
- https://hibernate.atlassian.net/browse/HHH-17991
- https://hibernate.atlassian.net/browse/HHH-17993
> Backporting bootstrap optimisations

- hibernate-core/src/main/java/org/hibernate/mapping/PrimaryKey.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/joined/JoinedInheritanceEmbeddedIdTest.java
https://hibernate.atlassian.net/browse/HHH-17883
> HHH-17883 Wrong order of primary key join columns with @EmbeddedId and joined inheritance

- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/EntityBatchLoaderArrayParam.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/EntityBatchLoaderInPredicate.java
- hibernate-core/src/test/java/org/hibernate/orm/test/caching/CachingBatchLoadNoProxiesAndCircularRelationshipTest.java
https://hibernate.atlassian.net/browse/HHH-17983
> HHH-17983 - StackOverflowError on 6.5.CR2 with @Proxy(lazy=false), @BatchSize and @ManyToOne

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/TableBinder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/collectionelement/ElementCollectionAndCompositeKeyTest.java
https://hibernate.atlassian.net/browse/HHH-17964
> HHH-17964 Hibernate using wrong column order for ElementCollection query when composite ID is present

- hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CountQueryTests.java
https://hibernate.atlassian.net/browse/HHH-17967
> HHH-17967 - Add test for issue (already fixed on main, fails pre-6.5)

- hibernate-core/src/main/java/org/hibernate/CacheMode.java
- hibernate-core/src/main/java/org/hibernate/EnabledFetchProfile.java
- hibernate-core/src/main/java/org/hibernate/LockMode.java
- hibernate-core/src/main/java/org/hibernate/LockOptions.java
- hibernate-core/src/main/java/org/hibernate/ReadOnlyMode.java
- hibernate-core/src/main/java/org/hibernate/Session.java
- hibernate-core/src/main/java/org/hibernate/action/internal/EntityVerifyVersionProcess.java
- hibernate-core/src/main/java/org/hibernate/dialect/lock/OptimisticLockingStrategy.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultPostLoadEventListener.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/util/LockModeConverter.java
- hibernate-core/src/main/java/org/hibernate/jpa/internal/util/CacheModeHelper.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderHelper.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderStandardImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/findoptions/FindOptionsTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/findoptions/LockOptionsTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/findoptions/RefreshOptionsTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/lock/BatchAndLockTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/lock/LockTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/locking/LockModeTest.java
https://hibernate.atlassian.net/browse/HHH-18024
https://hibernate.atlassian.net/browse/HHH-18001
https://hibernate.atlassian.net/browse/HHH-18023
> HHH-18001, HHH-18023, HHH-18024, HHH-18025 introduce support for FindOptions, RefreshOptions, LockOptions

- hibernate-core/src/main/java/org/hibernate/LockMode.java
- hibernate-core/src/main/java/org/hibernate/action/internal/EntityVerifyVersionProcess.java
- hibernate-core/src/main/java/org/hibernate/dialect/lock/OptimisticLockingStrategy.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultPostLoadEventListener.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/util/LockModeConverter.java
- hibernate-core/src/main/java/org/hibernate/jpa/internal/util/CacheModeHelper.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderHelper.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderStandardImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/lock/BatchAndLockTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/lock/LockTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/locking/LockModeTest.java
https://hibernate.atlassian.net/browse/HHH-18024
https://hibernate.atlassian.net/browse/HHH-18023
> HHH-18023, HHH-18024 fix bugs with read-only mode and versioned lock modes

- ci/jpa-3.2-tck.Jenkinsfile
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQuerySpec.java
https://hibernate.atlassian.net/browse/HHH-17982
> HHH-17982 Setup JPA 3.2 TCK testing automation for ORM 7

- hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataImpl.java
https://hibernate.atlassian.net/browse/HHH-18034
> HHH-18034 Configuration property `hibernate.event.listener.eventType` should be more lenient against spaces

- hibernate-core/src/main/java/org/hibernate/boot/model/internal/ClassPropertyHolder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/ComponentPropertyHolder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/AnnotationConverterAndEmbeddableTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/AnnotationConverterAndEmbeddableTest2.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/AnnotationConverterAndExceptionTest.java
https://hibernate.atlassian.net/browse/HHH-18028
> HHH-18028 TCK test failure with attribute converter and Embeddable

- hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/ManagedTypeProcessor.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/cacheable/disableselective/City.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/cacheable/disableselective/DisableCacheTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/cacheable/disableselective/Person.java
- hibernate-core/src/test/resources/org/hibernate/orm/test/jpa/cacheable/disableselective/orm.xml
https://hibernate.atlassian.net/browse/HHH-18041
> HHH-18041 With SharedCacheMode.DISABLE_SELECTIVE entities with cacheable false should not be cached

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
https://hibernate.atlassian.net/browse/HHH-18043
> HHH-18043 Change the temporal arithmetic to use nanoseconds

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2LegacySqlAstTranslator.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DerbyLegacySqlAstTranslator.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacySqlAstTranslator.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/HSQLLegacySqlAstTranslator.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacySqlAstTranslator.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacySqlAstTranslator.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacySqlAstTranslator.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseAnywhereSqlAstTranslator.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseLegacySqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/DB2SqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/DerbySqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/H2SqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/HANASqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/HSQLSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/MariaDBSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/SQLServerSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/SybaseASESqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/SybaseSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/TiDBSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/hql/InferenceTest.java
https://hibernate.atlassian.net/browse/HHH-18046
> HHH-18046 Cast parameters used as arithmetic operands on DB2

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityAssociationMapping.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractEntityCollectionPart.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ManyToManyCollectionPart.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/BasicValuedPathInterpretation.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EmbeddableValuedPathInterpretation.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQuerySpec.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ql/MapIssueTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/ManyToManyGroupByOrderByTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/sql/exec/onetoone/bidirectional/EntityWithBidirectionalAssociationsOneOfWhichIsAJoinTableTest.java
https://hibernate.atlassian.net/browse/HHH-17837
Backport of #8274
> HHH-17837 Join + GroupBy: Wrong column used for many-to-many association

- hibernate-core/src/test/java17/org/hibernate/orm/test/records/RecordAsEmbeddableEnhancementTest.java
https://ge.hibernate.org/s/lg3u4hlbrnq44/console-log/task/:hibernate-core:compileTestJava17Java?anchor=20&page=1
> Fix java 17 bytecode-enhanced test missing imports

- settings.gradle
https://hibernate.atlassian.net/browse/HHH-18050
> HHH-18050 Upgrade to Jackson 2.17.0

- hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
and enable some commented tests in `FunctionTests`.
https://hibernate.atlassian.net/browse/HHH-18053
> HHH-18053 fix fractional seconds duration addition on SQL Server 

- hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
- hibernate-core/src/main/java/org/hibernate/dialect/function/array/JsonArrayViaElementArgumentReturnTypeResolver.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/FullyQualifiedReflectivePathTerminal.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/SemanticQueryWalker.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmTreePrinter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/spi/BaseSemanticQueryWalker.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmBasicValuedSimplePath.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmFkExpression.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmFunctionPath.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmFunction.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/EmbeddableFunctionTableGroup.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/EmbeddableFunctionTableReference.java
- hibernate-core/src/test/java/org/hibernate/orm/test/notfound/FkRefTests.java
https://hibernate.atlassian.net/browse/HHH-18066
> Array aggregate function

- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/order/OrderTest.java
https://hibernate.atlassian.net/browse/HHH-18068
> HHH-18068 case-insensitive Order

- hibernate-core/src/main/java/org/hibernate/internal/util/LockModeConverter.java
consistent with the similar levels they have
cc @beikov
https://hibernate.atlassian.net/browse/HHH-18023
> HHH-18023 treat LockMode.WRITE as similar to PESSIMISTIC_FORCE_INCREMENT

- hibernate-core/src/main/java/org/hibernate/internal/util/LockModeConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/order/OrderTest.java
https://hibernate.atlassian.net/browse/HHH-18068
https://hibernate.atlassian.net/browse/HHH-18023
> frontports from 6 to 7

- documentation/src/main/asciidoc/introduction/Advanced.adoc
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
https://hibernate.atlassian.net/browse/HHH-18043
> Backports from 7 to 6

- docker_db.sh
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/TiDBDialect.java
https://hibernate.atlassian.net/browse/HHH-18053
Fixes for TiDB and CockroachDB
> HHH-18053 duration arithmetic with fractional seconds

- Jenkinsfile
- ci/jpa-3.1-tck.Jenkinsfile
- ci/release/Jenkinsfile
- ci/snapshot-publish.Jenkinsfile
- nightly.Jenkinsfile
For this: https://github.com/hibernate/hibernate-jenkins-pipeline-helpers/pull/25
> Upgrade to jenkins-pipeline-helpers 1.13

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/version/TablePerClassAbstractRootTypeVersionUpdateTest.java
https://hibernate.atlassian.net/browse/HHH-17834
Backport of #8266
> HHH-17834 lock(e, OPTIMISTIC_FORCE_INCREMENT) with TABLE_PER_SUBCLASS

- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metamodel/EntityInterfaceExtendsMapTest.java
https://hibernate.atlassian.net/browse/HHH-17827
> HHH-17827 “Not a managed type” error when using entity interface extending from java.util.Map

- hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/callbacks/PrePersistAndCompositeIdTest.java
https://hibernate.atlassian.net/browse/HHH-18032
> HHH-18032 CompositeId, when the id assigned by PrePersist method an HibernateException: identifier of an instance of _ was altered is thrown

- hibernate-core/src/main/java/org/hibernate/query/hql/internal/QuerySplitter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmPolymorphicRootDescriptor.java
- hibernate-core/src/test/java/org/hibernate/orm/test/polymorphic/PolymorphicQueriesTest.java
https://hibernate.atlassian.net/browse/HHH-17305
> HHH-17305 Test and fix for keeping order of tables in polymorphic queries

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacySqlAstTranslator.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacySqlAstTranslator.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseLegacySqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/SQLServerSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/SybaseASESqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/dialect/SybaseSqlAstTranslator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/locking/jpa/AdvancedFollowOnLockingTest.java
https://hibernate.atlassian.net/browse/HHH-17421
> HHH-17421 Ensure that no follow-on locking happens on SQL Server and Sybase ASE

- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/AbstractSqmSelectionQuery.java
- hibernate-core/src/test/java/org/hibernate/orm/test/paging/keybased/KeyBasedPagingTest.java
https://hibernate.atlassian.net/browse/HHH-18077
> HHH-18077 Fix key selection when paging to previous pages

- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/AbstractSqmSelectionQuery.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/KeyedResult.java
https://hibernate.atlassian.net/browse/HHH-18077
> HHH-18077 extremely minor cleanup after fix

- hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/ManagedTypeProcessor.java
- hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/XmlAnnotationHelper.java
- hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/db/ForeignKeyProcessing.java
- hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/db/JoinColumnProcessing.java
- hibernate-core/src/main/xjb/mapping-bindings.xjb
- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/secondarytable/SecondaryTableTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/secondarytable/TestEntity.java
- hibernate-core/src/test/resources/org/hibernate/orm/test/schemaupdate/secondarytable/TestEntity.xml
XML  <secondary-table/> element is not added to JdkClassDetails
https://hibernate.atlassian.net/browse/HHH-18081
> HHH-18081 XML  <secondary-table/> element is not added to JdkClassDetails

- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacyDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacyDialect.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedColumn.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedColumns.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedJoinColumn.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/internal/TableBinder.java
- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
- hibernate-core/src/main/java/org/hibernate/mapping/CheckConstraint.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/ColumnDefinitions.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardTableExporter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/checkconstraint/column/Another.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/checkconstraint/column/AnotherTestEntity.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/checkconstraint/column/ColumnCheckConstraintTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/checkconstraint/column/TestEntity.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/checkconstraint/table/Another.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/checkconstraint/table/AnotherTestEntity.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/checkconstraint/table/EntityWithSecondaryTables.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/checkconstraint/table/TableCheckConstraintTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/checkconstraint/table/TestEntity.java
- hibernate-core/src/test/resources/org/hibernate/orm/test/schemaupdate/checkconstraint/column/mapping.xml
- hibernate-core/src/test/resources/org/hibernate/orm/test/schemaupdate/checkconstraint/table/mapping.xml
https://hibernate.atlassian.net/browse/HHH-18054
> HHH-18054 Support for JPA 3.2 @CheckConstraint

- settings.gradle
https://hibernate.atlassian.net/browse/HHH-18091
> HHH-18091 Upgrade to ByteBuddy 1.14.15

- settings.gradle
https://hibernate.atlassian.net/browse/HHH-18091
> HHH-18091 Upgrade to ByteBuddy 1.14.15 (branch 6.5)

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImplConstants.java
- hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java
https://hibernate.atlassian.net/browse/HHH-18094
> HHH-18094 Bytebuddy enhancer: make better use of constants and memory
