hibernate/hibernate-orm

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImplConstants.java, hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java
https://hibernate.atlassian.net/browse/HHH-18094
=> HHH-18094 Bytebuddy enhancer: make better use of constants and memory (6.5)

hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/TableBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/tablecomment/JpaTableCommentTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/tablecomment/TestEntity.java, hibernate-core/src/test/resources/org/hibernate/orm/test/schemaupdate/tablecomment/TestEntity.xml
https://hibernate.atlassian.net/browse/HHH-18055
=> HHH-18055 Support for JPA 3.2 table comment

hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ImplicitToOneJoinTableSecondPass.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/TableBinder.java, hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/mapping/Table.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardTableExporter.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/tableoptions/TableOptionsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/tableoptions/TestEntity.java, hibernate-core/src/test/resources/org/hibernate/orm/test/schemaupdate/tableoptions/TestEntity.xml, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java
https://hibernate.atlassian.net/browse/HHH-18056
=> HHH-18056 Support for JPA 32 table options

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/tck2_2/caching/InheritedCacheableTest.java
https://hibernate.atlassian.net/browse/HHH-18098
=> HHH-18098 fix @Cacheable(false) for polymorphic lookups

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/tck2_2/caching/InheritedCacheableTest.java
https://hibernate.atlassian.net/browse/HHH-18098
=> HHH-18098 backport to main

hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/EnumeratedValueConverter.java, hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/InferredBasicValueResolver.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/EnumJavaType.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/enums/ConvertedEnumCheckConstraintsTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/enumeratedvalue/BadEnumeratedValueTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/enumeratedvalue/CharEnumerateValueTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/enumeratedvalue/EnumeratedValueTests.java, migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-16153
=> HHH-16153 - Support JPA 3.2 `@EnumeratedValue`

documentation/src/main/style/asciidoctor/css/hibernate-layout.css
HHH-18105 added missing semicolon in CSS file
=> HHH-18105 added missing semicolon in CSS file

hibernate-core/src/main/java/org/hibernate/action/internal/QueuedOperationCollectionAction.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/engine/internal/Collections.java, hibernate-core/src/main/java/org/hibernate/event/internal/AbstractFlushingEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDeleteEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/WrapVisitor.java, hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java, hibernate-core/src/main/java/org/hibernate/persister/collection/BasicCollectionPersister.java, hibernate-core/src/main/java/org/hibernate/persister/collection/OneToManyPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/collectionelement/OnDeleteCascadeToElementCollectionTest.java
https://hibernate.atlassian.net/browse/HHH-4301
=> HHH-4301 @OnDelete with @ElementCollection and @ManyToMany

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnyBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ToOneBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/derivedidentities/e1/b/Dependent.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/IdClassEntityGraphTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/refresh/RefreshTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/IdClassEntityGraphTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/IdClassManyToOneCascadeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/notfound/OptionalEagerNotFoundTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/notfound/OptionalEagerRefNonPKNotFoundTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/notfound/OptionalLazyNotFoundTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/notfound/RequiredLazyNotFoundTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/refresh/JPARefreshTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/refresh/RefreshTest.java
https://hibernate.atlassian.net/browse/HHH-12251
https://hibernate.atlassian.net/browse/HHH-18129
=> HHH-18129 don't force cascade=PERSIST for @MapsId fields

migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-18129
=> HHH-18129 add to migration guide

hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java, hibernate-core/src/main/java/org/hibernate/generator/OnExecutionGenerator.java, hibernate-core/src/main/java/org/hibernate/id/Configurable.java, hibernate-core/src/main/java/org/hibernate/id/ExportableColumn.java, hibernate-core/src/main/java/org/hibernate/id/IdentifierGenerator.java, hibernate-core/src/main/java/org/hibernate/id/IdentityGenerator.java, hibernate-core/src/main/java/org/hibernate/id/PostInsertIdentifierGenerator.java, hibernate-core/src/main/java/org/hibernate/id/factory/IdentifierGeneratorFactory.java, hibernate-core/src/main/java/org/hibernate/id/factory/internal/StandardIdentifierGeneratorFactory.java, hibernate-core/src/main/java/org/hibernate/id/factory/spi/CustomIdGeneratorCreationContext.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/mapping/Column.java, hibernate-core/src/main/java/org/hibernate/mapping/Component.java, hibernate-core/src/main/java/org/hibernate/mapping/KeyValue.java, hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java, hibernate-core/src/main/java/org/hibernate/mapping/Table.java, hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/ColumnDefinitions.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardTableMigrator.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/identity/hhh10429/IdentityGeneratorExtendsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/NativeGenerator.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/NativeGeneratorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/NativeId.java
https://hibernate.atlassian.net/browse/HHH-18136
=> HHH-18136 make it easier to write Generators which delegate to old id generation infrastructure

hibernate-core/src/main/java/org/hibernate/generator/values/GeneratedValueBasicResultBuilder.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/delegate/MutationDelegateIdentityTest.java
https://hibernate.atlassian.net/browse/HHH-18026
=> HHH-18026 Prevent dialects not supporting arbitrary values retrieval in `getGeneratedKeys()` from logging a SQL exception

hibernate-core/src/main/java/org/hibernate/generator/values/GeneratedValueBasicResultBuilder.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/delegate/MutationDelegateIdentityTest.java
Backport of https://github.com/hibernate/hibernate-orm/pull/8391
https://hibernate.atlassian.net/browse/HHH-18026
=> HHH-18026 Prevent dialects not supporting arbitrary values retrieval in getGeneratedKeys() from logging a SQL exception

hibernate-core/src/main/java/org/hibernate/tool/schema/internal/ColumnDefinitions.java
and similar cases where the column type doesn't have explicit length
https://hibernate.atlassian.net/browse/HHH-18140
=> HHH-18140 schema migration for @Column(length=LONG) on MySQL

tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/map/MapOfMapEntity.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/map/MetamodelGeneratedTest.java
https://hibernate.atlassian.net/browse/HHH-17514
=> HHH-17514 Add test for issue to show that it has alredy been resolved

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/sequence/OracleSequenceSupport.java
https://hibernate.atlassian.net/browse/HHH-18142
=> HHH-18142 Add Oracle Database 23ai support for DROP SEQUENCE IF EXISTS

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/AbstractSchemaValidator.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/ColumnDefinitions.java
https://hibernate.atlassian.net/browse/HHH-16531
=> HHH-16531 be more forgiving in handling of integral types in schema validation/update

hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleServerConfiguration.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleTypes.java, hibernate-core/src/main/java/org/hibernate/type/SqlTypes.java, hibernate-core/src/main/java/org/hibernate/type/StandardBasicTypes.java, hibernate-vector/src/main/java/org/hibernate/vector/AbstractOracleVectorJdbcType.java, hibernate-vector/src/main/java/org/hibernate/vector/OracleByteVectorJdbcType.java, hibernate-vector/src/main/java/org/hibernate/vector/OracleDoubleVectorJdbcType.java, hibernate-vector/src/main/java/org/hibernate/vector/OracleFloatVectorJdbcType.java, hibernate-vector/src/main/java/org/hibernate/vector/OracleVectorFunctionContributor.java, hibernate-vector/src/main/java/org/hibernate/vector/OracleVectorJdbcType.java, hibernate-vector/src/main/java/org/hibernate/vector/OracleVectorTypeContributor.java, hibernate-vector/src/main/java/org/hibernate/vector/VectorArgumentValidator.java, hibernate-vector/src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor, hibernate-vector/src/main/resources/META-INF/services/org.hibernate.boot.model.TypeContributor, hibernate-vector/src/test/java/org/hibernate/vector/OracleByteVectorTest.java, hibernate-vector/src/test/java/org/hibernate/vector/OracleDoubleVectorTest.java, hibernate-vector/src/test/java/org/hibernate/vector/OracleFloatVectorTest.java, hibernate-vector/src/test/java/org/hibernate/vector/OracleGenericVectorTest.java
https://hibernate.atlassian.net/browse/HHH-17738
=> HHH-17738 : Add support for Oracle database AI Vector Search

hibernate-core/src/main/java/org/hibernate/dialect/DialectDelegateWrapper.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/reflection/JPAXMLOverriddenAnnotationReaderTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/scanning/PackagedEntityManagerTest.java
Just fix a typo `s/overriden/overridden`
=> chore: s/overriden/overridden

tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java
https://hibernate.atlassian.net/browse/HHH-18019
=> HHH-18019 fix package present detection on ecj

hibernate-core/src/main/java/org/hibernate/boot/SessionFactoryBuilder.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/multitenancy/AbstractMultiTenancyTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/tenantid/TenantIdTest.java
https://hibernate.atlassian.net/browse/HHH-17972
=> HHH-17972 - Allow changing tenant identifier in SharedSessionBuilder

hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleEnumJdbcType.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleOrdinalEnumJdbcType.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/OracleEnumTest.java
https://hibernate.atlassian.net/browse/HHH-17909
=> HHH-17909 Use domain type for NAMED_ENUM

hibernate-testing/src/main/java/org/hibernate/testing/cleaner/OracleDatabaseCleaner.java
https://hibernate.atlassian.net/browse/HHH-18156
=> HHH-18156 Fix operation is not allowed from within a pluggable database

hibernate-core/src/test/java/org/hibernate/orm/test/type/OracleEnumTest.java
https://hibernate.atlassian.net/browse/HHH-17909
=> HHH-17909 Improve test to cover schema generated by named ordinal enum

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/CharacterColumnTest.java
See Jira issue [HHH-18117](https://hibernate.atlassian.net/browse/HHH-18117)
[HHH-18117]: https://hibernate.atlassian.net/browse/HHH-18117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HHH-18117 Character literal is not properly handled in query

documentation/src/main/asciidoc/quickstart/guides/obtaining.adoc, documentation/src/main/asciidoc/userguide/Bibliography.adoc, documentation/src/main/asciidoc/userguide/appendices/Legacy_Native_Queries.adoc, documentation/src/main/asciidoc/userguide/chapters/query/extensions/Vector.adoc, documentation/src/main/asciidoc/userguide/chapters/query/spatial/Spatial.adoc
Documentation only PR! No need to run any tests :)
https://hibernate.atlassian.net/browse/HHH-18157
=> HHH-18157 Document 23ai new features where necessary

hibernate-jfr/src/main/java/org/hibernate/event/jfr/internal/CacheGetEvent.java, hibernate-jfr/src/main/java/org/hibernate/event/jfr/internal/CachePutEvent.java, hibernate-jfr/src/main/java/org/hibernate/event/jfr/internal/DirtyCalculationEvent.java, hibernate-jfr/src/main/java/org/hibernate/event/jfr/internal/FlushEvent.java, hibernate-jfr/src/main/java/org/hibernate/event/jfr/internal/JdbcBatchExecutionEvent.java, hibernate-jfr/src/main/java/org/hibernate/event/jfr/internal/JdbcConnectionAcquisitionEvent.java, hibernate-jfr/src/main/java/org/hibernate/event/jfr/internal/JdbcConnectionReleaseEvent.java, hibernate-jfr/src/main/java/org/hibernate/event/jfr/internal/JdbcPreparedStatementCreationEvent.java, hibernate-jfr/src/main/java/org/hibernate/event/jfr/internal/JdbcPreparedStatementExecutionEvent.java, hibernate-jfr/src/main/java/org/hibernate/event/jfr/internal/JfrEventManager.java, hibernate-jfr/src/main/java/org/hibernate/event/jfr/internal/PartialFlushEvent.java, hibernate-jfr/src/main/java/org/hibernate/event/jfr/internal/PrePartialFlushEvent.java, hibernate-jfr/src/test/java/org/hibernate/event/jfr/DirtyCalculationEventTests.java, hibernate-jfr/src/test/java/org/hibernate/event/jfr/JdbcBatchExecutionEventTests.java, hibernate-jfr/src/test/java/org/hibernate/event/jfr/JdbcPreparedStatementEventTests.java, hibernate-jfr/src/test/java/org/hibernate/event/jfr/cache/CacheGetEventTests.java, hibernate-jfr/src/test/java/org/hibernate/event/jfr/cache/EntityInsertCachePutEventTests.java, hibernate-jfr/src/test/java/org/hibernate/event/jfr/cache/EntityUpdateCachePutEventTests.java, hibernate-jfr/src/test/java/org/hibernate/event/jfr/cache/NaturalIdGetCacheTests.java, hibernate-jfr/src/test/java/org/hibernate/event/jfr/cache/NaturalIdPutCacheTests.java, hibernate-jfr/src/test/java/org/hibernate/event/jfr/cache/QueryCachePutEventTests.java, hibernate-jfr/src/test/java/org/hibernate/event/jfr/flush/AutoFlushTests.java, hibernate-jfr/src/test/java/org/hibernate/event/jfr/flush/ExplicitFlushTests.java, hibernate-jfr/src/test/java/org/hibernate/event/jfr/flush/FlushTests.java, hibernate-jfr/src/test/java/org/hibernate/event/jfr/flush/PrePartialFlushTest.java
https://hibernate.atlassian.net/browse/HHH-18109
=> HHH-18109 Remove executionTime from JFR events

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/unique/InformixUniqueDelegate.java
https://hibernate.atlassian.net/browse/HHH-18153
=> HHH-18153 Fix for Informix unique constraints on nullness columns

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java
https://hibernate.atlassian.net/browse/HHH-18163
=> HHH-18163 Fix for Informix foreign key on cascade delete syntax

hibernate-core/src/main/java/org/hibernate/boot/SessionFactoryBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryBuilder.java, hibernate-core/src/main/java/org/hibernate/cfg/JpaComplianceSettings.java, hibernate-core/src/main/java/org/hibernate/event/internal/AbstractFlushingEventListener.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/JpaComplianceImpl.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/MutableJpaComplianceImpl.java, hibernate-core/src/main/java/org/hibernate/jpa/spi/JpaCompliance.java, hibernate-core/src/main/java/org/hibernate/jpa/spi/MutableJpaCompliance.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/cascade/persist/CascadePersistJpaTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/cascade/persist/CascadePersistSFTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/JpaComplianceStub.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/model/AbstractJPATest.java
https://hibernate.atlassian.net/browse/HHH-18166
=> HHH-18166 introduce hibernate.jpa.compliance.cascade

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractEntityCollectionPart.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleEntityValuedModelPart.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/JoinedInheritanceCollectionSameHierarchyTest.java
https://hibernate.atlassian.net/browse/HHH-17161
=> HHH-17161 org.hibernate.WrongClassException thrown, when getting a persisted Set, for a discriminator that should not be considered in the query

tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java
for some reason my fingers always make this mistake
=> fix a comment

hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/IdGeneratorTypeWithBeanContainerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/SimpleBeanContainer.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/SimpleGenerator.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/SimpleId.java
https://hibernate.atlassian.net/browse/HHH-18164
=> HHH-18164 Make @IdGeneratorType respect BeanContainer

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/ReuseQueryWithExpandedParameterTest.java
https://hibernate.atlassian.net/browse/HHH-18027
=> HHH-18027 Clear expansions NonSelectQueryPlan.executeUpdate call

documentation/src/main/asciidoc/userguide/chapters/jdbc/Database_Access.adoc
Documentation only
https://hibernate.atlassian.net/browse/HHH-18173
=> HHH-18173 Document Oracle Universal Connection Pool

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
https://hibernate.atlassian.net/browse/HHH-18168
=> HHH-18168 Use count(*) instead of count(1) for size() translation

hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmBasicValuedSimplePath.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmEmbeddedValuedSimplePath.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmAliasedNode.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/MappedSuperclassWithGenericsTest.java
https://hibernate.atlassian.net/browse/HHH-18007
=> HHH-18007 Creating criteria query for a generic identifier with a @MappedSuperclass leads to an exception

hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/type/CollectionType.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/manytomany/ManyToManyNonAggregatedIdJoinColumnTest.java
https://hibernate.atlassian.net/browse/HHH-17925
=> HHH-17925 Mapping a Many To Many Relationship on Single Key when Composite Key is defined

hibernate-core/src/main/java/org/hibernate/result/internal/OutputsImpl.java, hibernate-jfr/src/test/java/org/hibernate/event/jfr/JdbcPreparedStatementEventTests.java
https://hibernate.atlassian.net/browse/HHH-18111
=> HHH-18111 Call EventManager for stored procedures

hibernate-ucp/src/main/java/org/hibernate/oracleucp/internal/StrategyRegistrationProviderImpl.java, hibernate-ucp/src/main/java/org/hibernate/oracleucp/internal/UCPConnectionProvider.java, hibernate-ucp/src/main/java/org/hibernate/oracleucp/internal/package-info.java
=> HHH-18107 fixed package name

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultPersistEventListener.java, hibernate-core/src/main/java/org/hibernate/generator/CustomIdGeneratorCreationContext.java, hibernate-core/src/main/java/org/hibernate/generator/Generator.java, hibernate-core/src/main/java/org/hibernate/generator/GeneratorCreationContext.java, hibernate-core/src/main/java/org/hibernate/id/Assigned.java, hibernate-core/src/main/java/org/hibernate/id/ForeignGenerator.java, hibernate-core/src/main/java/org/hibernate/id/IdentifierGeneratorHelper.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/mapping/Property.java, hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/resource/beans/internal/Helper.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/jaxb/mapping/HibernateOrmSpecificAttributesMappingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/IdGeneratorTypeWithBeanContainerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/SimpleBeanContainer.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/SimpleGenerator.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/SimpleId.java
https://hibernate.atlassian.net/browse/HHH-18139
https://hibernate.atlassian.net/browse/HHH-18164
=> HHH-18139 further work on unifying legacy and new Generators

hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorBinder.java, hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java, hibernate-core/src/main/java/org/hibernate/generator/Assigned.java, hibernate-core/src/main/java/org/hibernate/generator/Generator.java, hibernate-core/src/main/java/org/hibernate/id/Assigned.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/InsertCoordinatorStandard.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java
rework the Assigned generator, to eliminate instanceof checks
https://hibernate.atlassian.net/browse/HHH-18139
=> HHH-18139 introduce org.hibernate.generator.Assigned

hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/StatelessSessionVersioningTest.java
https://hibernate.atlassian.net/browse/HHH-18175
=> HHH-18175 StatelessSession not incrementing @Version for entities with IDENTITY id generation

hibernate-core/src/test/java/org/hibernate/orm/test/stateless/UpsertVersionedTest.java
https://hibernate.atlassian.net/browse/HHH-18176
=> HHH-18176 enable an older test on Oracle

hibernate-core/src/main/java/org/hibernate/graph/internal/AbstractGraph.java, hibernate-core/src/main/java/org/hibernate/graph/spi/GraphImplementor.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/FetchGenericAttributesTest.java
https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues/HHH-18138
=> HHH-18138 entity graphs must respect concrete generic attribute

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
https://hibernate.atlassian.net/browse/HHH-18179
=> HHH-18179 incorrect warning issued for mappedBy with property access

hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java
and make the state model more transparent
https://hibernate.atlassian.net/browse/HHH-18205
=> HHH-18205 respect property-configured naming strategies in Configuration

hibernate-core/src/main/java/org/hibernate/query/sqm/spi/BaseSemanticQueryWalker.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/CteTests.java
https://hibernate.atlassian.net/browse/HHH-17968
=> HHH-17968 java.lang.IllegalStateException when using inline parameters in CTE expression on subquery

hibernate-core/src/test/java/org/hibernate/orm/test/ops/multiload/MultiLoadEntityGraphTest.java
https://hibernate.atlassian.net/browse/HHH-14034
=> HHH-14034 add test showing issue fixed

hibernate-core/src/main/java/org/hibernate/StatelessSession.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/LifecycleMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/Constants.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/TypeUtils.java
https://hibernate.atlassian.net/browse/HHH-18216
=> HHH-18216 @Save methods with @GeneratedValue ids

hibernate-core/src/main/java/org/hibernate/query/sql/internal/SQLQueryParser.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/NativeQuerySchemaPlaceholderTest.java
https://hibernate.atlassian.net/browse/HHH-18215
https://hibernate.atlassian.net/browse/HHH-2744
=> HHH-18215, HHH-2744 fix parsing of native SQL queries to handle quoting

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MimerSQLDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/TeradataDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DialectDelegateWrapper.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/NClobProxy.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/WrapperOptions.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/BlobJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/CharacterArrayJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ClobJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/NClobJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/PrimitiveCharacterArrayJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/StringJavaType.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/type/java/AbstractDescriptorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/descriptor/sql/StringValueMappingTest.java
🔥 **Please wait for my green light before merging that one once the tests are successful.** 🔥
https://hibernate.atlassian.net/browse/HHH-18206
=> HHH-18206 Switch to JDBC LOB APIs for Oracle Dialect

tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/AccessTypeInformation.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/TypeUtils.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/elementcollection/Homework.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/elementcollection/OfficeBuilding.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/embeddable/generics/EmbeddableGenericsTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/embeddable/genericsinheritance/EmbeddableGenericsAndInterfaceTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/embeddable/genericsinheritance/ExampleEmbedded.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/embeddable/genericsinheritance/ExampleEntity.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/embeddable/genericsinheritance/ExampleSuperClassEmbedded.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/embeddable/genericsinheritance/UserEntity.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/embeddable/nested/field/Address.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/embeddable/nested/field/Author.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/embeddable/nested/field/NestedEmbeddableTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/embeddable/nested/field/Postcode.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/embeddable/nested/property/Address.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/embeddable/nested/property/Author.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/embeddable/nested/property/NestedEmbeddableTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/embeddable/nested/property/Postcode.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/inheritance/basic/InheritanceTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/inheritance/unmappedclassinhierarchy/UnmappedClassInHierarchyTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/util/TestUtil.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/xmlmapped/XmlMappingTest.java
https://hibernate.atlassian.net/browse/HHH-13620
https://hibernate.atlassian.net/browse/HHH-13869
=> HHH-13620, HHH-13869 fix handling of nested embeddable access type in HibernateProcessor

hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
https://hibernate.atlassian.net/browse/HHH-17973
=> HHH-17973 - Deprecate ALLOW_REFRESH_DETACHED_ENTITY

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/sequence/InformixSequenceSupport.java
https://hibernate.atlassian.net/browse/HHH-18180
=> HHH-18180 Informix IF EXISTS clauses support

hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/generics/GenericPathComparisonTest.java
https://hibernate.atlassian.net/browse/HHH-17959
=> HHH-17959 SemanticException caused by type check against 'in' generic fields within expressions

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixSqlAstTranslator.java
https://hibernate.atlassian.net/browse/HHH-18225
=> HHH-18225 Fix for Informix syntax error in DISTINCT clause before SKIP clause

hibernate-core/src/main/java/org/hibernate/NonUniqueObjectException.java, hibernate-core/src/main/java/org/hibernate/PropertyValueException.java, hibernate-core/src/main/java/org/hibernate/StaleObjectStateException.java, hibernate-core/src/main/java/org/hibernate/TransientPropertyValueException.java, hibernate-core/src/main/java/org/hibernate/UnresolvableObjectException.java, hibernate-core/src/main/java/org/hibernate/boot/MappingException.java, hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java, hibernate-core/src/main/java/org/hibernate/engine/internal/ForeignKeys.java, hibernate-core/src/main/java/org/hibernate/engine/internal/NonNullableTransientDependencies.java, hibernate-core/src/main/java/org/hibernate/engine/internal/Nullability.java, hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CascadeStyles.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CascadingAction.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CascadingActions.java, hibernate-core/src/main/java/org/hibernate/event/internal/AbstractFlushingEventListener.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/AbstractSchemaMigrator.java, hibernate-core/src/main/java/org/hibernate/type/EntityType.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/cascade/multicircle/MultiCircleJpaCascadeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/cascade2/CascadeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/NativeQueryEagerAssociationTest.java
https://hibernate.atlassian.net/browse/HHH-6999
=> HHH-6999 check for unsaved refs after processing all cascade persists

hibernate-core/src/main/java/org/hibernate/engine/spi/CascadeStyles.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/orphan/onetomany/DeleteOneToManyOrphansTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/orphan/onetoone/A.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/orphan/onetoone/B.java
https://hibernate.atlassian.net/browse/HHH-9568
=> HHH-9571 fix and reenable tests for orphan delete

hibernate-core/src/main/java/org/hibernate/engine/spi/CascadeStyles.java
don't need to run CHECK_ON_FLUSH with cascade=ALL, since ALL includes PERSIST_ON_FLUSH
https://hibernate.atlassian.net/browse/HHH-6999
=> HHH-6999 optimization

hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableRepresentationStrategyPojo.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/InvalidAnnotatedClassTypesTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/embeddable/EmbeddableInheritanceMappedSuperclassAdnGenericsTest.java
https://hibernate.atlassian.net/browse/HHH-18172
=> HHH-18172 Fix embeddable inheritance for types extending @MappedSuperclass

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/LazyOneToOneRemoveFlushAccessTest.java
https://hibernate.atlassian.net/browse/HHH-18212
=> HHH-18212 Accessing a removed lazy association results in a NullPointerException 

hibernate-core/src/main/java/org/hibernate/dialect/DerbyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java, hibernate-core/src/main/java/org/hibernate/dialect/function/TimestampaddFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/TimestampdiffFunction.java, hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/internal/PatternRenderer.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmBinaryArithmetic.java, hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/TemporalParameterPlusDurationTest.java
https://hibernate.atlassian.net/browse/HHH-18201
=> HHH-18201 - Addition/subtraction of duration to/from temporal parameter wrongly resolved as duration during query parsing

hibernate-core/src/main/java/org/hibernate/engine/spi/CascadeStyles.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CascadingActions.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDeleteEventListener.java, hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java, hibernate-core/src/main/java/org/hibernate/type/CollectionType.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/FindWithEntityGraphTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/iterate/ForwardOnlyScrollNoTransactionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/cascade/multicircle/MultiCircleJpaCascadeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/JoinTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/graphs/EntityGraphTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/orderupdates/OrderUpdatesTest.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/proxy/RemovedObjectQueryTest.java
This is too heavy-handed as implemented here.
https://hibernate.atlassian.net/browse/HHH-18230
=> HHH-18230 detect transient entity references in collections

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectStatement.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CountQueryTests.java
https://hibernate.atlassian.net/browse/HHH-18121
=> HHH-18121 Error when using createCountQuery() from distinct dynamic instantiation query

hibernate-core/src/main/java/org/hibernate/dialect/OracleSqlAstTranslator.java
https://hibernate.atlassian.net/browse/HHH-18242
=> HHH-18242 23ai supports natively Tuple Comparison

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java
In the `getSelectClauseNullString(...)` method, using `getRawTypeName()` is not sufficient because it does not consider the castType when using `CapacityDependentDdlType`.
The `if (descriptor == null)` condition is necessary for cases like the test `org.hibernate.orm.test.jpa.query.QueryWithLiteralsInSelectExpressionTest.testSelectNullLiterals`, which executes the query:
`SELECT cast(null as boolean), false, e.name FROM MyEntity e`
Without the condition, the query would fail with a NullPointerException
https://hibernate.atlassian.net/browse/HHH-16844
=> HHH-16844 Fix for Informix VARCHAR, NVARCHAR mappings errors

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmDynamicInstantiation.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/instantiation/InstantiationWithGenericsTest.java
https://hibernate.atlassian.net/browse/HHH-18218
=> HHH-18218 Dynamic instantiation with generic entity attribute fails constructor argument type validation

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2LegacySqlAstTranslator.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2zLegacySqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2SqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2zSqlAstTranslator.java
https://hibernate.atlassian.net/browse/HHH-18232
=> HHH-18232 Use change table modifier new and final consistently on DB2 and zOS

documentation/src/main/asciidoc/introduction/Entities.adoc
URL: https://docs.jboss.org/hibernate/orm/6.5/introduction/html_single/Hibernate_Introduction.html#entities
@ManyToMany
Declare either side of a one-to-one association?
@ManyToMany
Declare either side of a --> [many-to-many] association?
=> HHH-\d+ Fix Table 19. Declaring entity associations - Documentation

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmPathVisitor.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/FakeSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/SqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQuerySpec.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/ManyToManyGroupByOrderByTest.java
https://hibernate.atlassian.net/browse/HHH-18202
=> HHH-18202 Error with distinct query + order by aggregate function on an association key

README.adoc, docker_db.sh, gradle/databases.gradle
Message "Informix failed to start and configure after 5 minutes" even though the server is running.
=> Informix run fix

hibernate-core/src/main/java/org/hibernate/sql/Template.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/TemplateTest.java
https://hibernate.atlassian.net/browse/HHH-18256
=> HHH-18256 Don't prefix literal type prefix in SQL fragments

settings.gradle
Replacing #8544
https://hibernate.atlassian.net/browse/HHH-18255
=> HHH-18255 Upgrade to HCANN 7.0.1.Final

hibernate-core/hibernate-core.gradle, settings.gradle
I'm not totally sure of this; relates to
- https://hibernate.zulipchat.com/#narrow/stream/132094-hibernate-orm-dev/topic/build.20puzzles
=> Keep dependency repository definitions well defined

hibernate-core/src/main/java/org/hibernate/mapping/Component.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/AttributeFactory.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EmbeddableDiscriminatorConverter.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddableMappingTypeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AnyDiscriminatorSqmPath.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EmbeddableTypeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EmbeddedDiscriminatorSqmPath.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EmbeddedDiscriminatorSqmPathSource.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EmbeddedSqmPathSource.java, hibernate-core/src/main/java/org/hibernate/persister/entity/DiscriminatorHelper.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/BasicDotIdentifierConsumer.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmPluralValuedSimplePath.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmLiteralEmbeddableType.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmLiteralEntityType.java, hibernate-core/src/test/java/org/hibernate/orm/test/any/annotations/AnyImplicitDiscriminatorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/any/annotations/AnyTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/embeddable/ElementCollectionEmbeddableInheritanceTest.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java
https://hibernate.atlassian.net/browse/HHH-18125
=> HHH-18125 - Fix the type of embeddable discriminator paths and type literals

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/naturalid/PersistEntityWithProxyAssociationTest.java
https://hibernate.atlassian.net/browse/HHH-18147
=> HHH-18147 Hibernate fails to persist an entity when a natural id association is a proxy

hibernate-core/src/main/java/org/hibernate/cfg/DialectSpecificSettings.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleServerConfiguration.java
https://hibernate.atlassian.net/browse/HHH-18220
=> HHH-18220 Detect if Application Continuity is enabled for Oracle dialect

hibernate-core/src/main/java/org/hibernate/sql/results/internal/RowTransformerConstructorImpl.java
https://hibernate.atlassian.net/browse/HHH-18218
=> HHH-18218 - Fix possible null pointer

hibernate-core/src/main/java/org/hibernate/boot/jaxb/hbm/transform/HbmXmlTransformer.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/attr/ManyToOneAttributeProcessing.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/attr/OneToOneAttributeProcessing.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/db/JoinColumnProcessing.java, hibernate-core/src/main/resources/org/hibernate/xsd/mapping/mapping-7.0.xsd, hibernate-core/src/main/xjb/mapping-bindings.xjb, hibernate-core/src/test/java/org/hibernate/orm/test/boot/models/hbm/joinformula/ManyToOneTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/models/hbm/joinformula/OneToOneTests.java, hibernate-core/src/test/resources/mappings/models/hbm/joinformula/many-to-one.xml, hibernate-core/src/test/resources/mappings/models/hbm/joinformula/one-to-one.xml
HHH-18060 - HbmXmlTransformer #8560
`<join-formula/>`
https://hibernate.atlassian.net/browse/HHH-18060
=> HHH-18060 - HbmXmlTransformer

docker_db.sh, gradle/databases.gradle, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixSqlAstTranslator.java
There is one more commit in this pull request related to building with Informix in Docker.
https://hibernate.atlassian.net/browse/HHH-18267
=> HHH-18267 Informix insert value to identity column error

hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/ArgumentTypesValidator.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/BooleanJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JdbcType.java
https://hibernate.atlassian.net/browse/HHH-18016
=> HHH-18016 change ArgumentTypesValidator to delegate to the JdbcType

hibernate-core/src/main/java/org/hibernate/boot/jaxb/hbm/transform/HbmXmlTransformer.java, hibernate-core/src/main/java/org/hibernate/boot/models/HibernateAnnotations.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/XmlAnnotationHelper.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/attr/CommonPluralAttributeProcessing.java
https://hibernate.atlassian.net/browse/HHH-18264
=> HHH-18264 HbmXmlTransformer collection classification

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/delegate/MutationDelegateJoinedInheritanceTest.java
https://hibernate.atlassian.net/browse/HHH-18259
=> HHH-18259 Joined Inheritence with Generated wrongly resolves columns for base entity

hibernate-core/src/main/java/org/hibernate/boot/model/internal/ClassPropertyHolder.java, hibernate-core/src/main/java/org/hibernate/mapping/Component.java, hibernate-core/src/test/java17/org/hibernate/orm/test/records/RecordIdClassTest2.java
by rolling back [HHH-15184](https://hibernate.atlassian.net/browse/HHH-15184)
[HHH-15184]: https://hibernate.atlassian.net/browse/HHH-15184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://hibernate.atlassian.net/browse/HHH-18158
https://hibernate.atlassian.net/browse/HHH-18251
https://hibernate.atlassian.net/browse/HHH-18062
=> HHH-18158, HHH-18251, HHH-18062 fix composite id handling

hibernate-core/src/main/java/org/hibernate/boot/jaxb/hbm/transform/HbmXmlTransformer.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/models/hbm/collections/list/Category.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/models/hbm/collections/list/ListTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/models/hbm/collections/list/Root.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/models/hbm/collections/list/User.java, hibernate-core/src/test/resources/mappings/models/hbm/list/hbm.xml
https://hibernate.atlassian.net/browse/HHH-18265
=> HHH-18265 HbmXmlTransformer transform hbm <key column=/>

hibernate-core/src/main/java/org/hibernate/dialect/DB2400Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2iDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2zDialect.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/ColumnDefinitions.java
Apparently this is now supported ... let's find out...
https://hibernate.atlassian.net/browse/HHH-18301
=> HHH-18301 'drop table if exists' on Db2

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaDropperImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/schemagen/SchemaCreateDropExtraWarningsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/schemagen/SchemaDatabaseFileGenerationFailureTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/schemagen/SchemaScriptFileGenerationFailureTest.java
https://hibernate.atlassian.net/browse/HHH-18296
=> HHH-18296 call set client_min_messages = WARNING before dropping tables on Postgres

hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/enums/ConvertedEnumCheckConstraintsTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/enumeratedvalue/CharEnumerateValueTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/enumeratedvalue/EnumeratedValueTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/secondarytable/SecondaryTableTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/tablecomment/JpaTableCommentTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/tableoptions/TableOptionsTest.java
Should fix all failures in current HANA nightly CI: https://ci.hibernate.org/view/ORM/job/hibernate-orm-nightly/job/wip%252F7.0/54/
=> Fix some tests failing on HANA 

hibernate-core/src/main/java/org/hibernate/jpa/internal/enhance/EnhancingClassTransformerImpl.java
A backport of #8582
https://hibernate.atlassian.net/browse/HHH-18108
=> HHH-18108 for 6.5

hibernate-core/src/main/java/org/hibernate/jpa/internal/enhance/EnhancingClassTransformerImpl.java
We should not allow to apply the JPA ClassTransformer on classes which we will be loading during the transformation process.
In particular after the optimisations of HHH-18011, in which we introduce a `CoreTypePool` which allows the ByteBuddy enhancer to load some classes directly, we should apply a similar filter to the ClassTransformer.
There's an obvious drawback in maintenance as this increases coupling between CoreTypePool and EnhancingClassTransformerImpl, but I'm preferring to take this technical debt over stepping back on the optimisations as they are very significant; with this patch we will now also improve efficiency of the JPA ClassTransformer, which had been neglected by my previous work, and allow any framework which is using the JPA standard transformer to benefit from …
=> HHH-18108 Avoid applying the ClassTransformer on types we will be loading

settings.gradle
https://hibernate.atlassian.net/browse/HHH-18293
=> HHH-18293 Upgraded geolatte to 1.9.1

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2LegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DerbyLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DerbyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/DecimalJdbcType.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/NationalizedTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/StringNationalizedMappingTests.java
Was https://github.com/hibernate/hibernate-orm/pull/8613, now targeting H7 branch.
https://hibernate.atlassian.net/browse/HHH-18314
https://hibernate.atlassian.net/browse/HHH-18317
https://hibernate.atlassian.net/browse/HHH-18316
=> HHH-18314, HHH-18316, HHH-18317 @Nationalized strings on Db2, MySQL, and Sybase

hibernate-ucp/src/test/resources/log4j2.properties
https://hibernate.atlassian.net/browse/HHH-17414
=> HHH-17414 - Add a basic test logging configuration for UCP

documentation/src/main/asciidoc/userguide/chapters/domain/inheritance.adoc, migration-guide.adoc, release-announcement.adoc
https://hibernate.atlassian.net/browse/HHH-18285
=> HHH-18285 Migration guide entry for embeddable inheritance and annotated class type validation

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/EntityValuedPathsGroupByOrderByTest.java
https://hibernate.atlassian.net/browse/HHH-18272
=> HHH-18272 UnsupportedOperationException when order / group by clause contains aliased item

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/CachedQueryShallowSharedCollectionTest.java
https://hibernate.atlassian.net/browse/HHH-18085
=> HHH-18085 Executing SELECT query twice in a transaction, leads to "Shared references of collection error"

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2LegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/procedure/DB2StoredProcedureTest.java
https://hibernate.atlassian.net/browse/HHH-18332
=> HHH-18332 DB2 stored procedures returning REF_CURSORs are not working with the standard support

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/TeradataDialect.java
https://hibernate.atlassian.net/browse/HHH-18334
=> HHH-18334 Fix that Teradata doesn't support variable limit

databases/mariadb/matrix.gradle, docker_db.sh
Updates to MariaDB server version and the latest MariaDB Connector J.
Also simplify the wait until start.
=> Mariadb ci updates

hibernate-agroal/src/main/java/org/hibernate/agroal/internal/AgroalConnectionProvider.java, hibernate-core/src/main/java/org/hibernate/cfg/AgroalSettings.java, hibernate-core/src/main/java/org/hibernate/cfg/HikariCPSettings.java, hibernate-core/src/main/java/org/hibernate/cfg/JdbcSettings.java, hibernate-hikaricp/src/main/java/org/hibernate/hikaricp/internal/HikariConfigurationUtil.java
https://hibernate.atlassian.net/browse/HHH-18327
=> HHH-18327 Add Agroal and HikariCP settings constants

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacyDialect.java, hibernate-core/hibernate-core.gradle, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2JsonJdbcType.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmLiteral.java, hibernate-core/src/main/java/org/hibernate/type/EnumType.java, hibernate-core/src/main/java/org/hibernate/type/Type.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/JavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/MutabilityPlan.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ObjectArrayJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/BasicCollectionJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/FormatMapperBasedJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/H2FormatJsonJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/format/AbstractJsonFormatMapper.java, hibernate-core/src/main/java/org/hibernate/type/format/jackson/JacksonJsonFormatMapper.java, hibernate-core/src/main/java/org/hibernate/type/format/jakartajson/JsonBJsonFormatMapper.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/JsonMappingTests.java
https://hibernate.atlassian.net/browse/HHH-17840
=> HHH-17840 Fix null handling for Json type

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/querycache/SingleTableInheritanceQueryCacheTest.java
https://hibernate.atlassian.net/browse/HHH-18017
=> HHH-18017 Query cache on Polymorphic entities leads to InstantiationException (Cannot instantiate abstract class)

hibernate-core/src/main/java/org/hibernate/spi/NavigablePath.java, hibernate-core/src/main/java/org/hibernate/spi/TreatedNavigablePath.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/AggregateEmbeddableFetchImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableFetchImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityResultImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/MultipleJoinFetchesDifferentAliasTest.java
https://hibernate.atlassian.net/browse/HHH-18086
=> HHH-18086 Assertion Error when using JOIN FETCH on ToOneAttribute with multiple JOINs of parent entity

hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/internal/DdlTypeImpl.java, hibernate-core/src/test/resources/mappings/subselectfetch/Name.hbm.xml, hibernate-core/src/test/resources/org/hibernate/orm/test/bidi/Auction.hbm.xml, hibernate-core/src/test/resources/org/hibernate/orm/test/bidi/Auction2.hbm.xml, hibernate-core/src/test/resources/org/hibernate/orm/test/bidi/Auction3.hbm.xml
https://hibernate.atlassian.net/browse/HHH-18347
=> HHH-18347 Casted parameter rendering broken for some DDL types when using @Column

hibernate-core/src/main/java/org/hibernate/dialect/OracleSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
https://hibernate.atlassian.net/browse/HHH-18352
=> HHH-18352 Don't emulate tuple comparison with subquery if possible

hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/annotations/AnnotationMetadataSourceProcessorImpl.java
This PR aims to improve the partial order sorting implementation in AnnotationMetadataSourceProcessorImpl in terms of readability and complexity.
The trick is to maintain the partial order during the phase of collecting of all ancestor classes annotated with `@Entity` or `@MappedSuperclass`, so we don't need a separate complex ordering phase based on recursion.
https://hibernate.atlassian.net/browse/HHH-18335
=> HHH-18335 Improve partial order algorithm in AnnotationMetadataSourceProcessorImpl

hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java
https://hibernate.atlassian.net/browse/HHH-18342
=> HHH-18342 Improve javadoc in SharedSessionContractImplementor

documentation/src/main/asciidoc/introduction/Interacting.adoc
=> mention @ConcreteProxy and the problem it solves in Introduction doc

hibernate-core/src/main/java/org/hibernate/sql/results/graph/AssemblerCreationState.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/FetchList.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/FetchParent.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/Initializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/LoadingCollectionEntry.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/AbstractCollectionInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/AbstractImmediateCollectionInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/ArrayInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/BagInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/EagerCollectionFetch.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/ListInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/MapInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/SetInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableInitializerImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/DiscriminatedEntityInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/internal/LoadingCollectionEntryImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/StandardJdbcValuesMapping.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/collections/ElementCollectionCachePerfTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/collections/ElementCollectionPerfTest.java
https://hibernate.atlassian.net/browse/HHH-18375
=> HHH-18375 Reuse previous row state when result cardinality is duplicated

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultAutoFlushEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDirtyCheckEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultEvictEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultInitializeCollectionEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLockEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultPersistEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultPreLoadEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultRefreshEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultReplicateEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultSaveEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultSaveOrUpdateEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultUpdateEventListener.java
=> add missing @Override annotations

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/naturalid/NaturalIdAndAssociationTest.java
https://hibernate.atlassian.net/browse/HHH-18338
backort of https://github.com/hibernate/hibernate-orm/pull/8660 to 6.5
=> HHH-18338 o.h.UnknownEntityTypeException: Unable to locate persister thrown when an embeddable object is loaded before the entity it references

hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcCoordinatorImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcServicesImpl.java, hibernate-core/src/main/java/org/hibernate/resource/jdbc/internal/LogicalConnectionManagedImpl.java, hibernate-core/src/main/java/org/hibernate/resource/jdbc/spi/JdbcSessionOwner.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jdbc/internal/JdbcIsolationDelegate.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaIsolationDelegate.java, hibernate-core/src/test/java/org/hibernate/orm/test/connection/ConnectionCreatorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jdbc/JdbcCoordinatorTest.java
https://hibernate.atlassian.net/browse/HHH-18313
=> HHH-18313 NullPointerException because JdbcIsolationDelegate.sqlExceptionHelper() returns null

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgresPlusLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgresPlusDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SqlAstTranslatorWithUpsert.java, hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/OptionalTableUpdateOperation.java, hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayTrimTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/ManipulationCriteriaTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/delegate/GeneratedWritableDelegateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/procedure/DB2StoredProcedureTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/UpsertVersionedTest.java, nightly.Jenkinsfile
https://hibernate.atlassian.net/browse/HHH-17949
=> 6.5 backports

settings.gradle
https://hibernate.atlassian.net/browse/HHH-18393
=> HHH-18393 - Upgrade JBoss Logging Tools (processor) to 3.0.0.Final

hibernate-core/src/main/java/org/hibernate/engine/internal/Collections.java, hibernate-core/src/main/java/org/hibernate/metamodel/spi/MetamodelImplementor.java, hibernate-core/src/main/java/org/hibernate/resource/jdbc/internal/ResourceRegistryStandardImpl.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java
=> fix an error message

hibernate-core/src/main/java/org/hibernate/annotations/NamedNativeQuery.java, hibernate-core/src/main/java/org/hibernate/annotations/NamedQuery.java, hibernate-core/src/main/java/org/hibernate/boot/models/annotations/internal/NamedNativeQueryAnnotation.java, hibernate-core/src/main/java/org/hibernate/boot/models/annotations/internal/NamedQueryAnnotation.java
cc @sebersole 
https://hibernate.atlassian.net/browse/HHH-18184
=> HHH-18184 rescue @NamedQuery/@NamedNativeQuery.cacheMode

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractIdentifiableType.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CountQueryTests.java
https://hibernate.atlassian.net/browse/HHH-18357
=> HHH-18357 Null pointer exception in createCountQuery because Identifier descriptor is null in MappedSuperclass

hibernate-core/src/main/java/org/hibernate/boot/models/annotations/internal/UuidGeneratorAnnotation.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-testing/src/main/java/org/hibernate/testing/util/uuid/IdGeneratorCreationContext.java
Should fix the compilation errors of wip/7.0 branch
https://hibernate.atlassian.net/browse/HHH-18127
https://hibernate.atlassian.net/browse/HHH-18411
https://hibernate.atlassian.net/browse/HHH-18224
=> Compilation errors

hibernate-core/src/main/java/org/hibernate/boot/jaxb/hbm/transform/HbmXmlTransformer.java, hibernate-core/src/main/java/org/hibernate/boot/jaxb/mapping/spi/JaxbEntity.java, hibernate-core/src/main/java/org/hibernate/boot/jaxb/mapping/spi/JaxbNamedQuery.java, hibernate-core/src/main/java/org/hibernate/boot/jaxb/mapping/spi/JaxbQueryHintContainer.java, hibernate-core/src/main/java/org/hibernate/boot/models/annotations/internal/NamedQueryAnnotation.java, hibernate-core/src/main/java/org/hibernate/boot/models/annotations/internal/NamedQueryJpaAnnotation.java, hibernate-core/src/main/java/org/hibernate/boot/models/internal/GlobalRegistrationsImpl.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/QueryProcessing.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/XmlDocumentImpl.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/spi/XmlDocument.java, hibernate-core/src/main/xjb/mapping-bindings.xjb
https://hibernate.atlassian.net/browse/HHH-17720
=> HHH-17720 - Add common JAXB contracts for named queries

hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/annotations/CascadeType.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionImplementor.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/test/java/org/hibernate/event/service/internal/NewlyInstantiatdCollectionSkipDeleteOrphanTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/ops/OneToManyMappedByCascadeDeleteTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/ops/OneToManyMappedByOrderColumnTest.java, hibernate-envers/src/main/java/org/hibernate/envers/internal/synchronization/work/AbstractAuditWorkUnit.java, migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-18428
=> HHH-18428 Remove Session#delete

hibernate-core/src/main/java/org/hibernate/action/internal/AbstractEntityInsertAction.java, hibernate-core/src/main/java/org/hibernate/collection/spi/AbstractPersistentCollection.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentCollection.java, hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CollectionEntry.java, hibernate-core/src/main/java/org/hibernate/event/internal/AbstractFlushingEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/WrapVisitor.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderSubSelectFetch.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/type/CollectionType.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/NonPkCompositeJoinColumnCollectionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/NonPkJoinColumnCollectionTest.java
https://hibernate.atlassian.net/browse/HHH-18229
=> HHH-18229 Handle null owner key for collections

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/identifier/EmbeddedIdManyToOneFetchTest.java
https://hibernate.atlassian.net/browse/HHH-18330
=> HHH-18330 UnknownTableReferenceException in JPQL query when join fetching to-one in embedded id

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/mapping/Component.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/IdClassEmbeddable.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/IdClassRepresentationStrategy.java, hibernate-core/src/test/java17/org/hibernate/orm/test/records/RecordIdClassAndMapsIdTest.java
https://hibernate.atlassian.net/browse/HHH-18062
=> HHH-18062 'Could not instantiate entity ... due to argument type mismatch' with record @IdClass

hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/merge/MergeUnsavedEntitiesTest.java
https://hibernate.atlassian.net/browse/HHH-18177
=> HHH-18177 org.hibernate.AssertionFailure: null identifier for collection of role thrown when merging entity with generated id

hibernate-core/src/main/java/org/hibernate/boot/SessionFactoryBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryBuilder.java, hibernate-core/src/main/java/org/hibernate/cfg/JpaComplianceSettings.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/JpaComplianceImpl.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/MutableJpaComplianceImpl.java, hibernate-core/src/main/java/org/hibernate/jpa/spi/JpaCompliance.java, hibernate-core/src/main/java/org/hibernate/jpa/spi/MutableJpaCompliance.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/JpaComplianceStub.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/JpaComplianceTests.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/EntityManagerFactoryExtension.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/Jpa.java
https://hibernate.atlassian.net/browse/HHH-18443
=> HHH-18443 - Drop SessionFactoryBuilder#enableJpaListCompliance

hibernate-core/src/main/java/org/hibernate/annotations/DynamicInsert.java, hibernate-core/src/main/java/org/hibernate/annotations/DynamicUpdate.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/boot/models/annotations/internal/DynamicInsertAnnotation.java, hibernate-core/src/main/java/org/hibernate/boot/models/annotations/internal/DynamicUpdateAnnotation.java, hibernate-core/src/main/java/org/hibernate/boot/models/categorize/internal/EntityTypeMetadataImpl.java, migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-18442
=> HHH-18442 Drop DynamicInsert#value and DynamicUpdate#value

hibernate-core/src/test/java/org/hibernate/orm/test/collection/delayedOperation/BagDelayedOperationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/map/MapIndexFormulaTest.java, migration-guide.adoc
migration guide changes
https://hibernate.atlassian.net/browse/HHH-18195
=> HHH-18195  Remove Session#save / Session#update / Session#saveOrUpdate

hibernate-core/src/main/java/org/hibernate/query/criteria/JpaExpression.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/FullyQualifiedReflectivePathTerminal.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/AbstractSqmExpression.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmExpression.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmFieldLiteral.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSubQuery.java
https://hibernate.atlassian.net/browse/HHH-18448
https://hibernate.atlassian.net/browse/HHH-18448
=> HHH-18448 Add cast and notEqualTo methods to JpaExpression and SqmExpression

hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java, hibernate-core/src/main/java/org/hibernate/internal/JdbcSessionContextImpl.java, hibernate-core/src/main/java/org/hibernate/resource/jdbc/spi/JdbcSessionContext.java, hibernate-core/src/test/java/org/hibernate/orm/test/jdbc/JdbcCoordinatorTest.java
https://hibernate.atlassian.net/browse/HHH-18437
=> HHH-18437 - Remove deprecations from JdbcSessionContext

hibernate-core/src/main/java/org/hibernate/Interceptor.java, hibernate-core/src/test/java/org/hibernate/orm/test/caching/mocked/ReadWriteCacheTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/dirtiness/CustomDirtinessStrategyTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/interceptor/CollectionInterceptor.java, hibernate-core/src/test/java/org/hibernate/orm/test/interceptor/InstantiateInterceptor.java, hibernate-core/src/test/java/org/hibernate/orm/test/interceptor/InterceptorNonNullTransactionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/interceptor/InterceptorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/interceptor/InterceptorTransactionEventTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/interceptor/PropertyInterceptor.java, hibernate-core/src/test/java/org/hibernate/orm/test/interceptor/StatefulInterceptor.java, hibernate-core/src/test/java/org/hibernate/orm/test/interfaceproxy/DocumentInterceptor.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/callbacks/PreUpdateDirtyCheckingInterceptorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ejb3configuration/ExceptionInterceptor.java, hibernate-core/src/test/java/org/hibernate/orm/test/mixed/DocumentInterceptor.java, hibernate-core/src/test/java/org/hibernate/orm/test/querycache/QueryCacheTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/tm/InterceptorTransactionTest.java, hibernate-envers/src/test/java/org/hibernate/envers/test/integration/tm/TestInterceptor.java, migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-18452
=> HHH-18452 Remove deprecated org.hibernate.Interceptor methods

hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java
https://hibernate.atlassian.net/browse/HHH-18454
=> HHH-18454 - Skip connection provider retrieval and DB info logging when booting offline

hibernate-core/src/test/java/org/hibernate/orm/test/procedure/PostgreSQLStoredProcedureTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/sqm/BasicSelectionQueryTests.java
https://hibernate.atlassian.net/browse/HHH-18280
=> Fix HANA and PostgreSQL vs < 14 test failures

hibernate-core/src/main/java/org/hibernate/sql/results/graph/Initializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/AbstractCollectionInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/DelayedCollectionInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableInitializerImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/NonAggregatedIdentifierMappingInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/DiscriminatedEntityInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/ReloadWithPreviousRowEntityTest.java
https://hibernate.atlassian.net/browse/HHH-18271
=> HHH-18271 Fix faulty maybe lazy set determination leading to issue with previous row optimization

hibernate-core/src/main/java/org/hibernate/sql/ast/SqlAstNodeRenderingMode.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
https://hibernate.atlassian.net/browse/HHH-18359
=> HHH-18359 Add a wrap parameter rendering mode for Informix

hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/fetchscroll/CriteriaScrollFetchTest.java, hibernate-core/src/test/resources/org/hibernate/orm/test/hqlfetchscroll/ParentChild.hbm.xml
https://hibernate.atlassian.net/browse/HHH-17497
=> HHH-17497 - Add test case for issue (testScrollWithoutFetch)

hibernate-core/src/test/java/org/hibernate/orm/test/procedure/DB2StoredProcedureTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/procedure/SybaseStoredProcedureTest.java
=> Fix Sybase using jconn driver failures and DB2 10.5 failures

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/JpaCriteriaParameter.java, hibernate-core/src/test/java/org/hibernate/orm/test/bulkid/AbstractMutationStrategyIdTest.java
https://hibernate.atlassian.net/browse/HHH-18373
=> HHH-18373 - Add test and fix

build.gradle, gradle/java-module.gradle, settings.gradle
=> Fix forbiddenapis failure with GraalVM 21

hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableFetchImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/EntityGraphEmbeddedAttributesTest.java
https://hibernate.atlassian.net/browse/HHH-18391
=> HHH-18391 EntityGraphs are not considering Embedded attributes

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/onetoone/OneToOneJoinTableSelfReferenceTest.java
https://hibernate.atlassian.net/browse/HHH-18399
=> HHH-18399 Unable to persist self-referencing entity with @OneToOne and @JoinTable

hibernate-core/src/main/java/org/hibernate/cfg/DialectSpecificSettings.java, hibernate-core/src/main/java/org/hibernate/dialect/AzureSQLServerDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
https://hibernate.atlassian.net/browse/HHH-18463
=> HHH-18463 Add AzureDialect and determine SQL Server version based on compatibility level

hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/metadata/MetadataTest.java
https://hibernate.atlassian.net/browse/HHH-17465
=> HHH-17465 Incorrect metamodel for shared version attribute in @MappedSuperclass

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/caching/CacheReadOnlyStrategyTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/caching/CachingWithTriggerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/caching/ChacheReadOnlyStartegyTest.java
https://hibernate.atlassian.net/browse/HHH-17997
=> HHH-17997 Querying an Entity with CacheConcurrencyStrategy.READONLY throws UnsupportedOperationException: Can't update readonly object

hibernate-core/src/main/java/org/hibernate/boot/model/internal/ClassPropertyHolder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ComponentPropertyHolder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/InheritanceState.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyHolderBuilder.java, hibernate-core/src/main/java/org/hibernate/mapping/Component.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/AttributeFactory.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/EmbeddableMetaModelTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/Height.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/Measurement.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/Person.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/components/mappedsuperclass/AuditedEmbeddableWithNoDeclaredDataTest.java
https://hibernate.atlassian.net/browse/HHH-18103
=> HHH-18103 MappedSuperclass handling for Embeddable is broken in metamodel

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractEmbeddableMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddableMappingTypeImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/AbstractImmediateCollectionInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/EmbeddableInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableInitializerImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/NonAggregatedIdentifierMappingInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/EntityInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/ReloadWithPreviousRowEntityTest2.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/ReloadWithPreviousRowEntityTest3.java, hibernate-core/src/test/java/org/hibernate/orm/test/stream/KeyToOneCollectionFetchScrollTest.java
https://hibernate.atlassian.net/browse/HHH-18476
=> HHH-18476 Reset resolved entities after resolveEntityKeyOnly and improve loading further

hibernate-core/src/main/java/org/hibernate/LobHelper.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/BlobProxy.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/ClobProxy.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/LobCreator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/NClobProxy.java
and mark XlobProxy as @Internal
=> improve javadoc surrounding Blob/Clob APIs

hibernate-core/src/main/java/org/hibernate/sql/results/internal/StandardRowReader.java
=> remove unused Logger reference

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/TypecheckUtil.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/ConvertedAttributesTypecheckTest.java
https://hibernate.atlassian.net/browse/HHH-18400
=> HHH-18400 AttributeConverter causing type-check failure when comparing Date field to parameter

hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/ArrayInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/BagInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/ListInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/MapInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/SetInitializer.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/join/ReloadMultipleCollectionElementsTest.java
https://hibernate.atlassian.net/browse/HHH-18493
=> HHH-18493 Resolving already initialized collection elements leads to assertion error

hibernate-core/src/main/java/org/hibernate/internal/util/MarkerObject.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
=> minor code cleanups in AbstractEntityPersister

hibernate-core/src/main/java/org/hibernate/sql/exec/spi/JdbcSelectExecutor.java, hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesSourceProcessingStateStandardImpl.java
=> some very minor cleanups

tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java
https://hibernate.atlassian.net/browse/HHH-18505
=> HHH-18505 fix npe occurring while processing module descriptor

hibernate-core/src/main/java/org/hibernate/id/IdentifierGeneratorHelper.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/Optimizer.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStructure.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStyleGenerator.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/TableGenerator.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/TableStructure.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteInsertHandler.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/SchemaUpdateTableBackedSequenceTest.java, hibernate-envers/src/main/java/org/hibernate/envers/enhanced/OrderedSequenceStructure.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/various/ExportIdentifierTest.java
=> code cleanups to SequenceStyleGenerator and TableGenerator

hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/EnumeratedValueConverter.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleArrayJdbcType.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleEnumJdbcType.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleOrdinalEnumJdbcType.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLArrayJdbcType.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLEnumJdbcType.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLOrdinalEnumJdbcType.java, hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/converter/internal/EnumHelper.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/converter/spi/BasicValueConverter.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/EnumJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/ArrayJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/internal/ArrayDdlTypeImpl.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/internal/DdlTypeImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayAggregateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/enumeratedvalue/NamedEnumEnumerateValueTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/enumeratedvalue/PostgresqlNamedEnumEnumerateValueTests.java
https://hibernate.atlassian.net/browse/HHH-18512
=> HHH-18512 @EnumeratedValue and PostgreSQL named enum types

hibernate-core/src/test/java/org/hibernate/orm/test/records/GenericEnbeddedIdRecordTest.java
https://hibernate.atlassian.net/browse/HHH-18158
=> HHH-18158 additional test

hibernate-core/src/main/java/org/hibernate/query/criteria/CriteriaDefinition.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectStatement.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/query/CriteriaDefinitionTest.java
https://hibernate.atlassian.net/browse/HHH-18517
=> allow composition of CriteriaDefinitions

hibernate-core/src/main/java/org/hibernate/engine/internal/UnsavedValueFactory.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EntityVersionMappingImpl.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/VersionJavaType.java, hibernate-core/src/test/java/org/hibernate/orm/test/ops/MergeExplicitInitialVersionTest.java
https://hibernate.atlassian.net/browse/HHH-18487
=> HHH-18487 backport to 6.6

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/identifier/CompositeIdGenerationTypeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/tenantidpk/Account.java, hibernate-core/src/test/java/org/hibernate/orm/test/tenantidpk/TenantizedId.java
https://hibernate.atlassian.net/browse/HHH-18524
=> HHH-18524 @IdClass and composite key generation not working with meta-annotated @IdGenerationType

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/temporal/FractionalSecondsTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/temporal/JavaTimeFractionalSecondsTests.java
https://hibernate.atlassian.net/browse/HHH-18531
=> HHH-18531 Fix for Informix timestamp literal error

local-build-plugins/src/main/java/org/hibernate/orm/env/JpaVersion.java
=> update to final release of JPA 3.2

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AbstractPropertyHolder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedColumn.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedJoinColumns.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/spi/AbstractAttributeKey.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/model/source/AttributePathTest.java
also take the opportunity to "do" a todo
cc @NathanQingyangXu 
https://hibernate.atlassian.net/browse/HHH-18341
=> HHH-18341 fix the issue simply by removing obsolete code

hibernate-core/src/main/java/org/hibernate/annotations/Comment.java, hibernate-core/src/main/java/org/hibernate/annotations/Comments.java, hibernate-core/src/main/java/org/hibernate/annotations/NamedNativeQuery.java, hibernate-core/src/main/java/org/hibernate/mapping/RootClass.java, hibernate-core/src/main/java/org/hibernate/mapping/Table.java, hibernate-core/src/main/java/org/hibernate/query/Query.java, hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/spi/DelegatingSqmSelectionQueryImplementor.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmBagJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedBagJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedListJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedMapJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedSetJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedSingularJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmListJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmMapJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmSetJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmSingularJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedBagJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedListJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedMapJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedSetJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatedSingularJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/from/SqmAttributeJoin.java, hibernate-core/src/main/java/org/hibernate/type/ComponentType.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/SchemaUpdateSchemaNameTest.java
=> remove stuff annotated @Remove

hibernate-core/src/main/java/org/hibernate/boot/model/naming/CamelCaseToUnderscoresNamingStrategy.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/namingstrategy/CamelCaseToUnderscoresNamingStrategyTest.java
Issue: https://hibernate.atlassian.net/browse/HHH-17310
=> HHH-17310: Bug with names with digits in CamelCaseToUnderscoresNamingStrategy

hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DatasourceConnectionProviderImpl.java
https://hibernate.atlassian.net/browse/HHH-18538
=> HHH-18538 Improve database connection info from configured DataSource

tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java
https://hibernate.atlassian.net/browse/HHH-18505
=> HHH-18505 backport to 6.6

hibernate-core/src/main/java/org/hibernate/annotations/Cache.java, hibernate-core/src/main/java/org/hibernate/annotations/QueryHints.java, hibernate-core/src/main/java/org/hibernate/boot/archive/scan/spi/ScanOptions.java, hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedColumns.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/QueryBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/relational/SqlStringGenerationContext.java, hibernate-core/src/main/java/org/hibernate/boot/model/relational/internal/SqlStringGenerationContextImpl.java, hibernate-core/src/main/java/org/hibernate/bytecode/internal/BytecodeProviderInitiator.java, hibernate-core/src/main/java/org/hibernate/cache/RegionFactory.java, hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java, hibernate-core/src/main/java/org/hibernate/cfg/BatchSettings.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/identity/DB2390IdentityColumnSupport.java, hibernate-core/src/main/java/org/hibernate/dialect/sequence/LegacyDB2SequenceSupport.java, hibernate-core/src/main/java/org/hibernate/query/NullPrecedence.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/JavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/InstantAsTimestampJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/InstantAsTimestampWithTimeZoneJdbcType.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/PostgreSQLDialectTestCase.java
=> Miscellaneous cleanups to @Deprecated

hibernate-core/src/main/java/org/hibernate/dialect/aggregate/PostgreSQLAggregateSupport.java
=> fix a typo in previous commit

hibernate-core/src/main/java/org/hibernate/ReplicationMode.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultReplicateEventListener.java
and improve readability in DefaultReplicateEventListener
even though they are deprecated
=> fix the typing in ReplicationMode

hibernate-core/src/main/java/org/hibernate/cfg/JdbcSettings.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DatasourceConnectionProviderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/spi/DataSourceBasedMultiTenantConnectionProviderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java
https://hibernate.atlassian.net/browse/HHH-18538
=> HHH-18538 better handling of DataSources in logging

hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorBinder.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/ConnectionProviderInitiator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/ResultSetReturnImpl.java, hibernate-core/src/main/java/org/hibernate/id/insert/BasicSelectingDelegate.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/ContainerManagedLifecycleStrategy.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/JpaCompliantLifecycleStrategy.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/spi/AbstractCdiBeanContainer.java
=> some cleanups

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java, hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionFactoryDelegatingImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionFactoryImplementor.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionImplementor.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java, hibernate-core/src/main/java/org/hibernate/event/spi/EventSource.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/PersistenceUnitInfoDescriptor.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/spi/PersistenceUnitDescriptor.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/DiscriminatedAssociationAttributeMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/DiscriminatedAssociationMapping.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/PooledHiLoSequenceIdentifierTest.java
=> SessionImplementor removals

hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryContext.java, hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/event/internal/AbstractFlushingEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDeleteEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java, hibernate-core/src/main/java/org/hibernate/event/service/internal/EventListenerGroupImpl.java, hibernate-core/src/main/java/org/hibernate/event/service/spi/EventListenerGroup.java, hibernate-core/src/main/java/org/hibernate/event/service/spi/JpaBootstrapSensitive.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/readonly/ReadOnlyProxyTest.java
Rebase of #8866.
https://hibernate.atlassian.net/browse/HHH-18553
=> HHH-18553 allow remove() on a detached instance, even when there is a managed instance

hibernate-core/src/test/java/org/hibernate/orm/test/cut/generic/GenericCompositeUserTypeTest.java
https://hibernate.atlassian.net/browse/HHH-18543
=> HHH-18543 Skip GenericCompositeUserTypeTest for JVM OpenJ9

hibernate-core/src/main/java/org/hibernate/internal/CoreLogging.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/internal/EntityManagerMessageLogger.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryRegistry.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryRegistryMessageLogger.java, hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/SessionFactoryNamingTests.java
=> split out SessionFactoryRegistryMessageLogger

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java
Please, backport also to 6.6 branch if possible
https://hibernate.atlassian.net/browse/HHH-18558
=> HHH-18558 Fix for Informix UUID type support

hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/MergedSettings.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/ServiceRegistryCloser.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/spi/Bootstrap.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/JpaEntityNotFoundDelegate.java, hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/scanning/PackagedEntityManagerTest.java
=> continue in attempt to clean up EMFBuilderImpl

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java
Please, backport also to 6.6 branch
https://hibernate.atlassian.net/browse/HHH-18561
=> HHH-18561 Fix for Informix primary key constraint syntax error

hibernate-core/src/main/java/org/hibernate/boot/model/naming/NamingHelper.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/AccessTypeInformation.java
=> very minor code cleanups

migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-18584
=> HHH-18584 add to migration guide

hibernate-core/src/main/java/org/hibernate/query/criteria/HibernateCriteriaBuilder.java, hibernate-core/src/main/java/org/hibernate/query/criteria/spi/HibernateCriteriaBuilderDelegate.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/CteTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaBuilderNonStandardFunctionsTest.java
https://hibernate.atlassian.net/browse/HHH-16954
=> HHH-16954 introduce HibernateCriteriaBuilder.parameterList()

hibernate-core/src/main/java/org/hibernate/StaleObjectStateException.java, hibernate-core/src/main/java/org/hibernate/StaleStateException.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/BatchImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/spi/Batch.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/MutationExecutor.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/internal/AbstractMutationExecutor.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/internal/ModelMutationHelper.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/internal/MutationExecutorSingleBatched.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/internal/MutationExecutorStandard.java, hibernate-core/src/main/java/org/hibernate/jdbc/Expectations.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/AbstractDeleteCoordinator.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/AbstractMutationCoordinator.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/InsertCoordinatorStandard.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/UpdateCoordinatorStandard.java, hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchOptimisticLockingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchUpdateAndVersionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/transaction/batch/AbstractBatchingTest.java
and some minor cleanups to the Coordinators
https://hibernate.atlassian.net/browse/HHH-18586
=> HHH-18586 report StaleObjectStateExceptions when batch update fails

hibernate-core/src/main/java/org/hibernate/mapping/DenormalizedTable.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/DenormalizedTableForeignKeyGeneratorTest.java
cc @pariaSadatHosseiny 
https://hibernate.atlassian.net/browse/HHH-18470
=> HHH-18470 backport

hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java, hibernate-core/src/main/java/org/hibernate/type/BasicTypeRegistry.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/BasicPluralJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/BasicCollectionJavaType.java, hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/basic/ListOfByteArrayTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/basic/ListOfStringTest.java
https://hibernate.atlassian.net/browse/HHH-17739
=> HHH-17739 fix NPE for field with unsupported collection type

hibernate-core/src/main/java/org/hibernate/Hibernate.java, hibernate-core/src/main/java/org/hibernate/collection/spi/AbstractPersistentCollection.java, hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
https://hibernate.atlassian.net/browse/HHH-18492
=> HHH-18492 add Hibernate.isEmpty() for pure convenience

hibernate-core/src/main/java/org/hibernate/boot/model/process/spi/MetadataBuildingProcess.java
=> clean up obsolete code in MetadataBuildingProcess

docker_db.sh
…ariable in docker_db.sh
https://hibernate.atlassian.net/browse/HHH-18507
If approved, I will make similar changes to the 6.6 (in WF.next), 6.4 (in WF currently), and 6.2 (in EAP) branches.
=> [HHH-18507] allow overwriting the default db image with environment variable in docker_db.sh

nightly.Jenkinsfile
https://hibernate.atlassian.net/browse/HHH-18528
https://hibernate.atlassian.net/browse/HHH-18488
- build reproducibility check builds on top of the previous PR and executes the check on CI. It will build ORM two times publishing artifacts to two different "maven repositories" and then use the `compare-build-results.sh` script to compare the artifacts. The script returns !=0 if there are some differences (so that should fail the build). 
- As for the JAXP strict settings, I've done the same as for the Validator check, but if anyone has other ideas I'm happy to try them out 😃 
And the build with these two new executions is running here: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-orm-personal-marko/detail/build%2Frepo-check/30/pipeline/
By …
=> HHH-18528 Test strict Jaxp security settings with JDK 23 / HHH-18488 CI check for build reproducibility

tooling/metamodel-generator/hibernate-processor.gradle
=> enable Jakarta Data tests

hibernate-core/src/main/java/org/hibernate/query/sqm/NodeBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/AbstractSqmSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
=> reset the ValueHandlingMode after pagination

hibernate-core/src/main/java/org/hibernate/annotations/Cascade.java, hibernate-core/src/main/java/org/hibernate/annotations/CascadeType.java
https://hibernate.atlassian.net/browse/HHH-18554
=> HHH-18554 deprecate @Cascade and CascadeType

hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/spi/PersistenceContext.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CacheEntityLoaderHelper.java
+ code cleanups in CacheEntityLoaderHelper
=> clean up warnings in PersistenceContext

hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/spi/PersistenceContext.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CacheEntityLoaderHelper.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/TypecheckUtil.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/EnumJavaType.java
https://hibernate.atlassian.net/browse/HHH-16880
=> HHH-16880 tighten up handling of converted types in TypecheckUtil

hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingImpl.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractCommonQueryContract.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/SelectCaseWhenNullLiteralTest.java
https://hibernate.atlassian.net/browse/HHH-18556
=> HHH-18556 Expressions.nullExpresion() in querydsl result in NPE in SqmExpressible

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/basic/ReloadAssociatedEntitiesTest.java
https://hibernate.atlassian.net/browse/HHH-18565
=> HHH-18565 Bytecode enhancement, assertion error on reloading *toOne entities

migration-guide.adoc
=> Add notes about removal of EmptyInterceptor and TestForIssue to migration guide doc

hibernate-core/src/main/java/org/hibernate/dialect/function/array/ArrayConstructorFunction.java, hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayConstructorInSelectClauseTest.java
https://hibernate.atlassian.net/browse/HHH-18353
=> HHH-18353 ArrayConstructorFunction comparing argument types by reference causes FunctionArgumentException

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HANADialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HANAServerConfiguration.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SimpleDatabaseVersion.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/database/metadata/MetadataAccessTests.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectContext.java
https://hibernate.atlassian.net/browse/HHH-18602
=> HHH-18602 Expose `determineDatabaseVersion` in `Dialect`

hibernate-core/src/main/java/org/hibernate/type/descriptor/java/BlobJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ClobJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/NClobJavaType.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/BlobAttributeQueryUpdateTest.java
https://hibernate.atlassian.net/browse/HHH-18480
https://github.com/hibernate/hibernate-orm/pull/8935 backport
=> HHH-18480 ClassCastException when updating a Blob with Oracle

hibernate-core/src/main/java/org/hibernate/internal/util/compare/ComparableComparator.java, hibernate-core/src/main/java/org/hibernate/internal/util/compare/RowVersionComparator.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractEmbeddableMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddableMappingTypeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/GeneratedValuesProcessor.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SingleAttributeIdentifierMapping.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/MatchingIdSelectionHelper.java, hibernate-core/src/main/java/org/hibernate/result/internal/OutputsImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/internal/RowTransformerArrayImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/internal/RowTransformerListImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/internal/RowTransformerSingularReturnImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/internal/RowTransformerStandardImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/internal/StandardRowReader.java, hibernate-core/src/main/java/org/hibernate/sql/results/spi/ScrollableResultsConsumer.java, hibernate-core/src/main/java/org/hibernate/sql/results/spi/SingleResultConsumer.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/AbstractClassJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/Immutability.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ImmutableMutabilityPlan.java
=> Mark field `INSTANCE` as private or deprecated for removal if method `instance()` present

hibernate-core/src/main/java/org/hibernate/internal/CoordinatingEntityNameResolver.java, hibernate-core/src/test/java/org/hibernate/orm/test/dynamicmap/CustomEntityNameResolverTest.java, hibernate-core/src/test/resources/org/hibernate/orm/test/dynamicmap/artist.hbm.xml
https://hibernate.atlassian.net/browse/HHH-18486
=> HHH-18486 Unable to add Persist the object because of EntityNameResolver being ignored

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/joinfetch/JoinFetchNestedAssociationsTest.java
https://hibernate.atlassian.net/browse/HHH-18469
=> HHH-18469 Assertion Error when fetch joining complex entities structure

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmFieldLiteral.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSubQuery.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/CriteriaSubqueryInPredicateTest.java
https://hibernate.atlassian.net/browse/HHH-18502
=> HHH-18502 Type conversion error due to surprising javac method selection in SqmSubQuery#in

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/CompoundNaturalIdMapping.java, hibernate-core/src/test/java/org/hibernate/orm/test/cache/NaturalIdTest.java
https://hibernate.atlassian.net/browse/HHH-18511
=> HHH-18511 ArrayIndexOutOfBoundsException in ImmutableFetchList

hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/IndexBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/MapBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ToOneBinder.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DialectDelegateWrapper.java, hibernate-core/src/main/java/org/hibernate/dialect/SpannerDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/unique/AlterTableUniqueDelegate.java, hibernate-core/src/main/java/org/hibernate/dialect/unique/CreateTableUniqueDelegate.java, hibernate-core/src/main/java/org/hibernate/mapping/Column.java, hibernate-core/src/main/java/org/hibernate/mapping/Constraint.java, hibernate-core/src/main/java/org/hibernate/mapping/DenormalizedTable.java, hibernate-core/src/main/java/org/hibernate/mapping/Index.java, hibernate-core/src/main/java/org/hibernate/mapping/ManyToOne.java, hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java, hibernate-core/src/main/java/org/hibernate/mapping/Table.java, hibernate-core/src/main/java/org/hibernate/mapping/ToOne.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/AbstractSchemaMigrator.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/ColumnDefinitions.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaCreatorImpl.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaDropperImpl.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaTruncatorImpl.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardForeignKeyExporter.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardIndexExporter.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardSequenceExporter.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardTableExporter.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardUniqueKeyExporter.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/options/OptionsTest.java
Redo #8364. Still don't know how to test it.
https://hibernate.atlassian.net/browse/HHH-18619
=> HHH-18619 add support for @ForeignKey(options), @UniqueConstraint(options), @Index(options)

hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/cfg/QuerySettings.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/DateJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JdbcTypeIndicators.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/TimeJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/TimestampJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/NativeQueryResultTypeAutoDiscoveryTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/NativeQueryWithDatetimesTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/DateArrayTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/TimeArrayTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/TimestampArrayTest.java
... by default, with a setting to recover old behavior.
https://hibernate.atlassian.net/browse/HHH-17557
=> HHH-17557 native queries return LocalDate and LocalDateTime instead of java.sql types

migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-17557
=> HHH-17557 update migration guide

hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyContainer.java, hibernate-core/src/test/java/org/hibernate/orm/test/records/RecordEmbeddedPropertyNamesTest.java
https://hibernate.atlassian.net/browse/HHH-18445
=> HHH-18445 Embeddable as Java Record has wrong order of columns

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSqlAstCreationState.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/PluralAttributeMappingImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/SqlAstCreationState.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/FindGraphCollectionOrderByTest.java
https://hibernate.atlassian.net/browse/HHH-18436
=> HHH-18436 Wrong order-by rendering order for nested collections if loaded with entity graph

hibernate-core/src/test/java/org/hibernate/orm/test/tool/schema/DefaultImportFileExecutionTest.java
https://hibernate.atlassian.net/browse/HHH-18612
=> HHH-18612 Avoid writing files to classpath in tests to avoid spurious failures

hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyContainer.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSqlAstCreationState.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/GeneratedValuesProcessor.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/PluralAttributeMappingImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/SqlAstCreationState.java, hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesCacheHit.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/FindGraphCollectionOrderByTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/GeneratedNoOpUpdateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/querycache/QueryCacheNullValueTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/tool/schema/DefaultImportFileExecutionTest.java, hibernate-core/src/test/java17/org/hibernate/orm/test/records/RecordEmbeddedPropertyNamesTest.java
=> 6.6 backports

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/engine/spi/LoadQueryInfluencersTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/options/OptionsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/TemplateTest.java
=> Misc fixes for failures on nightly CI

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/InheritanceJunctionExistsPredicateTest.java
https://hibernate.atlassian.net/browse/HHH-18174
=> HHH-18174 Hibernate polymorphic join in complex subquery not using discriminator

ci/build.sh
commit @27db266 had almost opposite the intended effect ... oops!
=> really disable checkstyle

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/EntityMutationTarget.java, hibernate-core/src/test/java/org/hibernate/orm/test/cfg/persister/GoofyPersisterClassProvider.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/InheritanceJunctionExistsPredicateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ejb3configuration/PersisterClassProviderTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/legacy/CustomPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/instantiation/MatchingConstructorTest.java
=> clean up some obsolete code in AbstractEntityPersister

hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ql/NamedNativeQueryWithGenericsTest.java, settings.gradle
https://hibernate.atlassian.net/browse/HHH-18630
=> HHH-18630 Upgrade H2 to 2.3.232 and H2GIS to 2.2.2

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java
https://hibernate.atlassian.net/browse/HHH-18635
Backport of https://github.com/hibernate/hibernate-orm/pull/8980
=> HHH-18635 Avoid using bigdatetime column type on Sybase jconn when not necessary

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/test/java/org/hibernate/orm/test/tenantid/TenantIdToOneBidirectionalTest.java
https://hibernate.atlassian.net/browse/HHH-18617
Backport of https://hibernate.atlassian.net/browse/HHH-18617
=> HHH-18617 Fetching unowned side of bidirectional OneToOne mappings including tenant identifier triggers EntityFilteredException

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
https://hibernate.atlassian.net/browse/HHH-18632
=> HHH-18632 Concurrency issue with AbstractEntityPersister#nonLazyPropertyLoadPlansByName

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/MappedDiscriminatorConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/NativeQueryAndDiscriminatorTest.java
https://hibernate.atlassian.net/browse/HHH-18515
https://github.com/hibernate/hibernate-orm/pull/8966 6.6 backport
=> HHH-18515 Unrecognized discriminator value exception when running native query on entity with discriminator column

hibernate-core/src/main/java/org/hibernate/cfg/DialectSpecificSettings.java
=> remove redundant modifiers in DialectSpecificSettings

hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java, hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CascadeStyle.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CascadeStyles.java, hibernate-core/src/main/java/org/hibernate/engine/spi/EffectiveEntityGraph.java, hibernate-core/src/main/java/org/hibernate/engine/spi/ManagedEntity.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SubselectFetch.java, hibernate-core/src/main/java/org/hibernate/mapping/Any.java, hibernate-core/src/main/java/org/hibernate/mapping/CheckConstraint.java, hibernate-core/src/main/java/org/hibernate/mapping/Column.java, hibernate-core/src/main/java/org/hibernate/mapping/Index.java, hibernate-core/src/main/java/org/hibernate/mapping/RootClass.java, hibernate-core/src/main/java/org/hibernate/mapping/Set.java, hibernate-core/src/main/java/org/hibernate/mapping/Subclass.java, hibernate-core/src/main/java/org/hibernate/mapping/ToOne.java, hibernate-core/src/main/java/org/hibernate/mapping/Value.java, hibernate-core/src/main/java/org/hibernate/type/AbstractStandardBasicType.java, hibernate-core/src/main/java/org/hibernate/type/CollectionType.java, hibernate-core/src/main/java/org/hibernate/type/EntityType.java, hibernate-core/src/main/java/org/hibernate/type/internal/ConvertedBasicTypeImpl.java
=> squash more warnings

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/CriteriaSelectOneToOneUnownedTest.java
https://hibernate.atlassian.net/browse/HHH-18628
=> HHH-18628 Regression: Unable to determine TableReference

hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/ManagedTypeProcessor.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/models/xml/complete/CompletePartialTests.java, hibernate-core/src/test/resources/mappings/models/dynamic/dynamic-id-class.xml
https://hibernate.atlassian.net/browse/HHH-18662
=> HHH-18662 Attribute not mentioned in orm.xml ends up not being mapped in Hibernate ORM 7

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2LegacyDialect.java, hibernate-core/src/main/java/org/hibernate/id/IdentityGenerator.java
https://hibernate.atlassian.net/browse/HHH-18642
Backport of https://github.com/hibernate/hibernate-orm/pull/9005
=> HHH-18642 DB2: select from new table with identity column not working when missing read permission

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/detached/RemoveDetachedInstanceTest.java
https://hibernate.atlassian.net/browse/HHH-18631
https://github.com/hibernate/hibernate-orm/pull/8984 6.6 backport
=> HHH-18631 AssertionError when loading an entity after removing another, associated entity

.gitignore
=> Add .idea/.gitignore to .gitignore

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/HANALegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/HANALegacyServerConfiguration.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/HANALegacySqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/function/json/HANAJsonArrayAggFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/json/HANAJsonObjectAggFunction.java
Also, create a legacy HANA dialect in the community dialects module
https://hibernate.atlassian.net/browse/HHH-18643
=> HHH-18643 - Remove support for SAP HANA versions older than 2.0 SPS 05

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/batch/RefreshAndBatchTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/batch/RefreshAndBatchTest2.java
https://hibernate.atlassian.net/browse/HHH-18608
https://github.com/hibernate/hibernate-orm/pull/8961 backport to 6.6
=> HHH-18608 NPE in EntityInitializerImpl.resolveInstanceSubInitializers

hibernate-core/src/main/java/org/hibernate/NonUniqueResultException.java
https://hibernate.atlassian.net/browse/HHH-18674
=> HHH-18674 Expose result count of NonUniqueResultException

hibernate-core/src/main/java/org/hibernate/spi/NavigablePath.java, hibernate-core/src/main/java/org/hibernate/spi/TreatedNavigablePath.java
=> remove some deprecated/unused methods

hibernate-core/src/main/java/org/hibernate/boot/models/categorize/internal/ClassLoaderServiceLoading.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/OracleArrayIncludesFunction.java, settings.gradle
https://hibernate.atlassian.net/browse/HHH-18663
=> HHH-18663 - Upgrade to hibernate-models 0.9.1

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappingMetamodelImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/CoalesceTest.java
https://hibernate.atlassian.net/browse/HHH-18321
Backport of https://github.com/hibernate/hibernate-orm/pull/9032
=> HHH-18321 SqlTreeCreationException when using sum/diff with coalesce on properties of embeddable component

hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
=> remove @Deprecated methods of CoreMessageLogger

hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/JdbcBatchLogging.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/BatchImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcCoordinatorImpl.java
+ very minor code cleanups in BatchImpl & JdbcCoordinatorImpl
=> move some logging in BatchImpl to typed methods

hibernate-core/src/main/java/org/hibernate/mapping/Property.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java, hibernate-core/src/test/java/org/hibernate/orm/test/manytomany/generic/ManyToManyGenericTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/manytomany/generic/ManyToManyNonGenericTest.java
Cherry picked changes from main branch into 6.6 branch.
https://hibernate.atlassian.net/browse/HHH-18675
=> Backport of HHH-18675 to 6.6 branch

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/AbstractBatchEntitySelectFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntitySelectFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/batch/BatchLazyProxyTest.java
https://hibernate.atlassian.net/browse/HHH-18645
=> HHH-18645 Handle proxies when resolving from existing entity in batch initializer

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/SingleSelectionArrayResultTest.java
https://hibernate.atlassian.net/browse/HHH-18450
Backport of https://github.com/hibernate/hibernate-orm/pull/9012
=> HHH-18450 Inconsistent "SELECT 1" versus "SELECT ?1" with result type Object[]

tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Bookshop.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/Constants.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/StringUtil.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockCollectionPersister.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockEntityPersister.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/ProcessorSessionFactory.java
https://hibernate.atlassian.net/browse/HHH-18667
=> Hibernate Processor fixes backport to 6.6

hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/test/java/org/hibernate/engine/internal/StatisticalLoggingSessionEventListenerTest.java
=> miscellaneous code cleanups and refactoring

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractIdentifiableType.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/basic/Concrete.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/basic/DataTest.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/basic/IdOperations.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/basic/Thing.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/versioned/SpecialVersioned.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/versioned/SpecialVersionedRepo.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/versioned/Versioned.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/versioned/VersionedRepo.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/versioned/VersionedTest.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockEntityPersister.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/ProcessorSessionFactory.java
also remove 'this' hacks made obsolete by Steve's work on core
=> HHH-18699 backport #8950 to 6.6

hibernate-core/src/main/java/org/hibernate/id/IncrementGenerator.java, hibernate-core/src/main/java/org/hibernate/internal/util/config/ConfigurationHelper.java, hibernate-core/src/main/java/org/hibernate/mapping/RootClass.java
=> some small improvements

documentation/src/main/asciidoc/querylanguage/Expressions.adoc, documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc, hibernate-core/src/test/java/org/hibernate/orm/test/hql/EnumTest.java
Added documentation for https://hibernate.atlassian.net/browse/HHH-16861
=> HHH-16861 documentation for HQL `ordinal()` function

.gitignore
=> gitignore exclude .idea folder except .idea/codeStyles/Project.xml and .idea/inspectionProfiles/Project_Default.xml

hibernate-core/src/main/java/org/hibernate/boot/beanvalidation/TypeSafeActivator.java
=> minor cleanups in TypeSafeActivator

settings.gradle
https://hibernate.atlassian.net/browse/HHH-18726
This one should contain the change for the incremental build improvement 🤞🏻 
=> HHH-18726 Upgrade JBoss Logging Tools (processor) to 3.0.2.Final

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java, hibernate-core/src/main/java/org/hibernate/event/spi/MergeContext.java, hibernate-core/src/main/java/org/hibernate/internal/util/EntityPrinter.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/PersistenceUnitUtilImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityIdentifierMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/InverseNonAggregatedIdentifierMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/NonAggregatedIdentifierMappingImpl.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java, hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleBasicEntityIdentifierMapping.java, hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleEmbeddedEntityIdentifierMapping.java, hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleNonAggregatedEntityIdentifierMapping.java, hibernate-core/src/main/java/org/hibernate/type/AnyType.java, hibernate-core/src/main/java/org/hibernate/type/EntityType.java, hibernate-core/src/test/java/org/hibernate/engine/internal/StatisticalLoggingSessionEventListenerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/cid/CompositeIdAndMergeTest.java
https://hibernate.atlassian.net/browse/HHH-18131
=> HHH-18131 Composite identifiers with associations stopped working with @IdClass`

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
https://hibernate.atlassian.net/browse/HHH-18734
=> HHH-18734 detect erroneous/unsupported use of @SQLRestriction on subclass entity

tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockEntityPersister.java
https://hibernate.atlassian.net/browse/HHH-18712
=> HHH-18712 Warning about attempts to update an immutable entity for normal (not immutable) entity

hibernate-core/src/main/java/org/hibernate/dialect/StructHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/component/StructComponentManyToOneCompositeTest.java
https://hibernate.atlassian.net/browse/HHH-18730
=> HHH-18730 Multi-column association in aggregate component doesn't work

hibernate-core/src/main/java/org/hibernate/annotations/FractionalSeconds.java
=> deprecate @FractionalSeconds

hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DriverManagerConnectionCreator.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/internal/log/ConnectionInfoLogger.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/SimpleBeanContainer.java
=> slight improvements to error messages when driver class missing

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SingleStoreDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/hint/IndexQueryHintHandler.java, hibernate-core/src/main/java/org/hibernate/dialect/hint/QueryHintHandler.java, hibernate-core/src/main/java/org/hibernate/dialect/hint/package-info.java
https://hibernate.atlassian.net/browse/HHH-18740
=> HHH-18740 - Deprecate org.hibernate.dialect.hint

hibernate-core/src/main/java/org/hibernate/StatelessSession.java
=> fix typo in SS jdoc

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
https://hibernate.atlassian.net/browse/HHH-18739
=> HHH-18739 Do not support join queries when using Mysql

hibernate-core/src/main/java/org/hibernate/dialect/hint/IndexQueryHintHandler.java
https://hibernate.atlassian.net/browse/HHH-18739
=> HHH-18739 - Fix for hints in queries containing joins

hibernate-core/src/main/java/org/hibernate/engine/spi/ExecuteUpdateResultCheckStyle.java, hibernate-core/src/main/java/org/hibernate/graph/GraphSemantic.java
=> modernize code in GraphSemantic and ExecuteUpdateResultCheckStyle

hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/MultiTableSqmMutationConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/AbstractSqlAstQueryNodeProcessingStateImpl.java
this class was full of EXTREMELY long methods and lots of typecasts
=> major cleanup to BaseSqmToSqlAstConverter

hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/StatelessSession.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/FindMultipleFetchProfileTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/FindMutipleTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/GetMultipleTest.java
=> rename findAll -> findMultiple, getAll -> getMultiple

documentation/src/main/asciidoc/introduction/Interacting.adoc
=> Update Interacting.adoc for JPA 3.2

hibernate-core/src/test/java/org/hibernate/orm/test/mapping/array/ArrayOfArraysTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/tenantid/TenantIdToOneBidirectionalTest.java
=> Fix a couple failures on CockroachDB

documentation/src/main/asciidoc/repositories/Repositories.adoc
=> fix a tiny typo

hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaTruncatorImpl.java
https://hibernate.atlassian.net/browse/HHH-18690
=> HHH-18690 Add test methods to SchemaTruncatorImpl to allow integration with search

hibernate-core/src/main/java/org/hibernate/type/EntityType.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/derivedidentities/OneToManyEmbeddableId.java
https://hibernate.atlassian.net/browse/HHH-18702
https://github.com/hibernate/hibernate-orm/pull/9071#pullrequestreview-2382050898 backport to 6.6
=> HHH-18702 Exception using @EmbeddedId with @OneToMany that refers to an alternate key column

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQueryGroup.java, hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesMappingProducerProviderStandard.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/UnionAllSelectNullTest.java
https://hibernate.atlassian.net/browse/HHH-18720
=> HHH-18720 Type check on select columns in union all gives SemanticException when there is a null column

hibernate-core/src/main/java/org/hibernate/cfg/QuerySettings.java
https://hibernate.atlassian.net/browse/HHH-18671
=> HHH-18671 Fix setting name (spelling)

hibernate-core/src/main/java/org/hibernate/annotations/NativeGenerator.java, hibernate-core/src/main/java/org/hibernate/boot/models/HibernateAnnotations.java, hibernate-core/src/main/java/org/hibernate/boot/models/annotations/internal/NativeGeneratorAnnotation.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/id/NativeGenerator.java
Additional work on @NativeGenerator
https://hibernate.atlassian.net/browse/HHH-18620
=> HHH-18620 - Add @NativeGenerator

documentation/src/main/asciidoc/introduction/Entities.adoc, documentation/src/main/asciidoc/introduction/Introduction.adoc
=> a bit about aggregates

documentation/src/main/asciidoc/introduction/Introduction.adoc
=> split a rant into two

documentation/src/main/asciidoc/introduction/Entities.adoc, documentation/src/main/asciidoc/querylanguage/Concepts.adoc, documentation/src/main/asciidoc/querylanguage/Expressions.adoc, documentation/src/main/asciidoc/querylanguage/Preface.adoc, documentation/src/main/asciidoc/repositories/Preface.adoc
=> more doc update for JPA 3.2

documentation/src/main/asciidoc/introduction/Introduction.adoc, documentation/src/main/asciidoc/introduction/Processor.adoc
=> fix broken code examples, and make 'em more readable

tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Bookshop.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java
=> minor fix to generated @see jdoc annotation in @Find method

hibernate-core/src/main/java/org/hibernate/query/results/dynamic/DynamicResultBuilderEntityStandard.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/ResultSetMappingProcessor.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/NativeQueryJoinTableTest.java
https://hibernate.atlassian.net/browse/HHH-18494
=> HHH-18494 UnknownTableReferenceException in native query with placeholder when entity contains a to-one with a join table

hibernate-core/src/main/java/org/hibernate/engine/internal/TwoPhaseLoad.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CacheEntityLoaderHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/cache/QueryCacheIncompleteTest.java
https://hibernate.atlassian.net/browse/HHH-18689
=> HHH-18689 Maintain proxy targets when converting cache entries

hibernate-core/src/main/java/org/hibernate/type/ManyToOneType.java, hibernate-core/src/test/java/org/hibernate/orm/test/associations/ManyToOneUniqueKeyReferenceWithCustomIdTest.java
Backport of https://github.com/hibernate/hibernate-orm/pull/9172 by @stringintech 
https://hibernate.atlassian.net/browse/HHH-18764
=> HHH-18764 Fix incorrect type resolution in ManyToOneType dirty check

hibernate-core/src/test/java/org/hibernate/orm/test/hql/InSubqueryPredicateAnonymousTupleTest.java
https://hibernate.atlassian.net/browse/HHH-17630
=> HHH-17630 Added test (no fix needed)

hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4, migration-guide.adoc
=> two minor things

hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlLexer.g4
https://hibernate.atlassian.net/browse/HHH-18807
=> HHH-18807 Fix a bug in HqlLexer.g4

hibernate-core/src/main/java/org/hibernate/internal/util/StringHelper.java, hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java, hibernate-core/src/main/java/org/hibernate/mapping/FetchProfile.java, hibernate-core/src/main/java/org/hibernate/mapping/Formula.java, hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java, hibernate-core/src/main/java/org/hibernate/mapping/Table.java, hibernate-core/src/main/java/org/hibernate/mapping/ToOne.java, hibernate-core/src/main/java/org/hibernate/mapping/Value.java
=> some misc cleanups to mapping package

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/object/ConvertedClassAttributeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/object/Status.java
https://hibernate.atlassian.net/browse/HHH-18564
Backport of https://github.com/hibernate/hibernate-orm/pull/9190
=> HHH-18564 Literal expressions using AttributeConverters stopped working in hibernate 6

hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java, hibernate-core/src/test/java/org/hibernate/persister/entity/JoinedSubclassEntityPersisterTest.java
https://hibernate.atlassian.net/browse/HHH-18703
=> HHH-18703 Use natural order table numbers for subclass column closure

hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
=> remove wrong keyword list from DB2Dialect

hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/manytomany/ManyToManyMaxFetchDepth0Test.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/UserEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hhh12076/AnnotationMappingJoinClassTest.java
and fix tests which had ignored such annotations
https://hibernate.atlassian.net/browse/HHH-18840
=> HHH-18840 validate collection mapping annotations

documentation/src/main/asciidoc/introduction/Advanced.adoc, documentation/src/main/asciidoc/introduction/Mapping.adoc
=> add a link to the new blog post

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/FakeSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/SqmToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/ExistsSubqueryForeignKeyTest.java
https://hibernate.atlassian.net/browse/HHH-18816
Backport of https://github.com/hibernate/hibernate-orm/pull/9216
=> HHH-18816 Error when rendering the fk-side of an association in an exists subquery

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaMutationQueryFkValuesTest.java
https://hibernate.atlassian.net/browse/HHH-18647
Backport of https://github.com/hibernate/hibernate-orm/pull/9238
=> HHH-18647 SemanticException when using createCriteriaInsertValues to insert into foreign key column

hibernate-core/src/main/java/org/hibernate/dialect/function/xml/HANAXmlTableFunction.java, hibernate-core/src/main/java/org/hibernate/query/Order.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java
=> add Order.reversedIf() and ignoringCaseIf() to simplify generated code

.github/workflows/ci.yml, ci/build.sh, gradle/java-module.gradle
Alternative to https://github.com/hibernate/hibernate-orm/pull/9011
https://hibernate.atlassian.net/browse/HHH-18678
=> HHH-18678 Specific task for CI build and separate step for format checks

hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/MappingMetamodel.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappingMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/spi/MappingMetamodelImplementor.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/entitynonentity/EntityNonEntityTest.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java
- deprecate some operations
- remove some already-deprecated operations
=> clean up the MappingMetamodel interface

documentation/src/main/asciidoc/introduction/Mapping.adoc
=> add an example use of hibernate.type.preferred_instant_jdbc_type

documentation/src/main/asciidoc/introduction/Entities.adoc, documentation/src/main/asciidoc/introduction/Mapping.adoc, documentation/src/main/asciidoc/querylanguage/Expressions.adoc, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/cfg/MappingSettings.java, hibernate-core/src/main/java/org/hibernate/query/spi/QueryEngineOptions.java, hibernate-core/src/main/java/org/hibernate/type/ArrayType.java, hibernate-core/src/main/java/org/hibernate/type/MapType.java, hibernate-core/src/main/java/org/hibernate/type/SqlTypes.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/BooleanJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/EnumJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/JavaType.java
=> Documentation improvements and minor cleanups

documentation/src/main/asciidoc/introduction/Entities.adoc, hibernate-core/src/main/java/org/hibernate/type/SqlTypes.java
=> Revision to new section

hibernate-core/src/main/java/org/hibernate/type/CollectionType.java
=> clean up CollectionType

hibernate-core/src/test/java/org/hibernate/orm/test/instant/InstantTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/instant/InstantWithNormalizedTest.java
=> yet another time zone test

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/EntityValuedPathsGroupByOrderByTest.java
https://hibernate.atlassian.net/browse/HHH-18862
The issue was fixed by https://github.com/hibernate/hibernate-orm/pull/9216, added a test and some small cleanups.
=> HHH-18862 Group by error due to subselect using foreign key reference instead of primary key in HQL query

hibernate-core/src/main/java/org/hibernate/dialect/function/array/ArrayContainsArgumentTypeResolver.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayContainsTest.java
https://hibernate.atlassian.net/browse/HHH-18851
=> HHH-18851 Fix parameter type inference issue when IN predicate is uses array_contains()

hibernate-core/src/main/java/org/hibernate/Transaction.java, hibernate-core/src/main/java/org/hibernate/engine/transaction/internal/TransactionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/ExceptionConverterImpl.java, hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/MutableJpaComplianceImpl.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jdbc/internal/JdbcResourceLocalTransactionCoordinatorImpl.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaTransactionCoordinatorImpl.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/spi/TransactionCoordinatorBuilder.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/transaction/TransactionCommitFailureTest.java, tooling/hibernate-ant/src/main/java/org/hibernate/tool/hbm2ddl/SchemaUpdateTask.java, tooling/hibernate-ant/src/main/java/org/hibernate/tool/hbm2ddl/SchemaValidatorTask.java
along with some minor aesthetic code cleanups
=> improve exception messages and logging related to tx management

tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockEntityPersister.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/ProcessorSessionFactory.java
=> minor code style issues in the query validator

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/discriminator/JoinedInheritanceDiscriminatorSelectionTest.java
https://hibernate.atlassian.net/browse/HHH-18583
=> HHH-18583 Joined + discriminator inheritance treat in where clause not restricting to subtype

hibernate-core/src/test/java/org/hibernate/orm/test/query/InClauseParameterPaddingCriteriaTest.java
https://hibernate.atlassian.net/browse/HHH-14119
=> HHH-14119 test showing parameter padding works with criteria literals

documentation/src/main/asciidoc/introduction/Interacting.adoc, documentation/src/main/asciidoc/introduction/Introduction.adoc
https://hibernate.atlassian.net/browse/HHH-14119
=> talk about events and about EntityListeners in the intro doc

documentation/src/main/asciidoc/introduction/Interacting.adoc
=> add CAUTION to doc

hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
So that people will stop thinking this is a bug :)
https://hibernate.atlassian.net/browse/HHH-9897
https://hibernate.atlassian.net/browse/HHH-12997
=> HHH-12997,HHH-9897 throw meaningful error for @JoinFomula with @OneToMany

hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
https://hibernate.atlassian.net/browse/HHH-15228
=> HHH-15228 test showing round() works with BigDecimal

hibernate-core/src/test/java/org/hibernate/orm/test/cache/FullLayoutQueryCacheTest.java
to show that https://hibernate.atlassian.net/browse/HHH-18323 has been resolved
=> HHH-18323 Add test for issue

ci/release/Jenkinsfile
HHH-18861 - Improve GitHub release announcement body for automated releases
https://hibernate.atlassian.net/browse/HHH-18861
=> HHH-18861 - Improve GitHub release announcement body for automated releases

hibernate-core/src/main/java/org/hibernate/dialect/JsonHelper.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/TableStructure.java, hibernate-core/src/main/java/org/hibernate/metamodel/spi/RuntimeModelCreationContext.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/AbstractMutationCoordinator.java, hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/DeleteOrUpsertOperation.java, hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/OptionalTableUpdateOperation.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/AbstractNonJoinedEntityFetch.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityFetchJoinedImpl.java, hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/AbstractInformationExtractorImpl.java, hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JsonArrayJdbcType.java
Fix ups for failures on https://github.com/hibernate/hibernate-orm/pull/9264
https://hibernate.atlassian.net/browse/HHH-18854
=> Changes for Hibernate Reactive (fix ups)

hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/BasicFormatterImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/hand/query/NativeSQLQueriesTest.java
Supersedes #4852.
https://hibernate.atlassian.net/browse/HHH-15102
=> HHH-15102 allow -- style comments in native SQL query

hibernate-core/src/main/java/org/hibernate/annotations/DialectOverride.java, hibernate-core/src/test/java/org/hibernate/orm/test/customsql/CustomSqlRestrictionOverridesTest.java
=> HHH-18893 fix @DialectOverrides.SQLRestrictions

hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/CriteriaQueryTypeQueryAdapterTest.java
https://hibernate.atlassian.net/browse/HHH-13932
=> HHH-13932 add test showing issue fixed

hibernate-core/src/test/java/org/hibernate/orm/test/idclass/JoinedSubclassWithIdClassTest.java
was #6113 by @realabertian.
https://hibernate.atlassian.net/browse/HHH-16054
=> HHH-16054 add test showing issue fixed

documentation/src/main/asciidoc/querylanguage/Expressions.adoc, hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HANADialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java, hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/ArgumentTypesValidator.java, hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/FunctionParameterType.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
https://hibernate.atlassian.net/browse/HHH-18892
=> HHH-18892 add hex() function

hibernate-core/src/test/java/org/hibernate/orm/test/annotations/manytomany/UnmodifiableCollectionMergeTest.java
upon merge of an unmodifiable collection
https://hibernate.atlassian.net/browse/HHH-1914
=> HHH-1914 - test case for UnsupportedOperationException

tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java
=> clean up some minor formatting / code style issues

hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/LazySqlResultMappingTest.java
https://hibernate.atlassian.net/browse/HHH-15667
https://hibernate.atlassian.net/browse/HHH-953
=> HHH-953 / HHH-15667 Test cases for these issues

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/NonManagedMetamodel.java
=> remove unnecessary code

hibernate-core/src/test/java/in/from/Any.java, hibernate-core/src/test/java/in/from/TestEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/InPackageTest.java
test showing https://hibernate.atlassian.net/browse/HHH-13943 has been solved
=> HHH-13943 Add test showing the issue has been solved

hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HANADialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
- fix the incorrect version numbers
- add links to docs
=> improve the javadoc headers of the main dialects

hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/BasicLazyPropertyUpdateTest.java
test showing https://hibernate.atlassian.net/browse/HHH-14244 has been solved
=> HHH-14244 Add test showing the issue has been solved

hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/TreatKeywordTest.java
test showing https://hibernate.atlassian.net/browse/HHH-13765 has been solved
=> HHH-13765 Add test showing the issue has been solved

documentation/src/main/asciidoc/querylanguage/Relational.adoc, hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java
=> improve test + docs for median() function

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
Cherry-pick of https://github.com/hibernate/hibernate-orm/pull/9381.
https://hibernate.atlassian.net/browse/HHH-18917
=> HHH-18917 Follow all of the JavaBeans rules in enhance/internal/bytebuddy/EnhancerImpl when checking if a class can be enhanced

hibernate-core/src/test/java/org/hibernate/orm/test/jpa/graphs/queryhint/EmbeddableQueryHintEntityGraphTest.java
https://hibernate.atlassian.net/browse/HHH-14349
=> HHH-14349 Add test showing the issue has been solved

documentation/src/main/asciidoc/introduction/Tuning.adoc
=> fix links to settings from doc

hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java, hibernate-core/src/test/java/org/hibernate/orm/test/idclass/mappedsuperclass/BaseSummary.java, hibernate-core/src/test/java/org/hibernate/orm/test/idclass/mappedsuperclass/MappedSuperclassIdClassAttributesTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/idclass/mappedsuperclass/PKey.java, hibernate-core/src/test/java/org/hibernate/orm/test/idclass/mappedsuperclass/Summary.java
https://hibernate.atlassian.net/browse/HHH-18868
=> HHH-18868 Cleanup tests and mapper-supers identifier mapper check

hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dynamic/DynamicStatusLazyGroupOnBasicFieldTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dynamic/DynamicStatusSingleLazyGroupOnBasicFieldTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dynamic/DynamicStatusWithMultipleToManyRelationTest.java
https://hibernate.atlassian.net/browse/HHH-15186
=> HHH-15186 Add test showing the issue has been resolved

hibernate-core/src/main/java/org/hibernate/collection/spi/AbstractPersistentCollection.java
https://hibernate.atlassian.net/browse/HHH-13790
=> HHH-13790 Temporary session not being closed

hibernate-core/src/main/java/org/hibernate/stat/Statistics.java, hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsInitiator.java, hibernate-core/src/main/java/org/hibernate/stat/spi/StatisticsFactory.java, hibernate-core/src/main/java/org/hibernate/stat/spi/StatisticsImplementor.java
=> improve documentation of stats.spi

hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/BatchBuilderInitiator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/MultiTenantConnectionProviderInitiator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/internal/MutationExecutorServiceInitiator.java, hibernate-core/src/main/java/org/hibernate/event/internal/EntityCopyObserverFactoryInitiator.java, hibernate-core/src/main/java/org/hibernate/persister/internal/PersisterClassResolverInitiator.java, hibernate-core/src/main/java/org/hibernate/persister/internal/PersisterFactoryInitiator.java, hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsImpl.java, hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsInitiator.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaManagementToolInitiator.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/script/SqlScriptExtractorInitiator.java
=> modernize some typecasts in Initiators

hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
=> very minor cleanup in SessionImpl

tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/StringUtil.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/TypeUtils.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/uppercase/Person.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/uppercase/UppercaseTest.java
https://hibernate.atlassian.net/browse/HHH-18949
=> HHH-18949 fix underscores within uppercase names

tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/uppercase/Person.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/uppercase/UppercaseTest.java
https://hibernate.atlassian.net/browse/HHH-18949
=> HHH-18949 slightly improve test

hibernate-core/src/main/java/org/hibernate/sql/Template.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/formula/FormulaWithQuotedTableNamesAndQuotedColumnNamesTest.java
https://hibernate.atlassian.net/browse/HHH-13612
=> HHH-13612 Quoted table name in FROM clause in @Formula gets wrongly qualified with generated alias

build.gradle, ci/release/Jenkinsfile, gradle/published-java-module.gradle, tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
https://hibernate.atlassian.net/browse/HHH-18912
Backport to 6.6
See https://github.com/hibernate/hibernate-orm/pull/9413
=> HHH-18912 - ORM release process

ci/release/Jenkinsfile, ci/snapshot-publish.Jenkinsfile
=> Various release script fixes

hibernate-core/src/test/java/org/hibernate/orm/test/formulajoin/AssociationFormulaTest.java
https://hibernate.atlassian.net/browse/HHH-9952
=> HHH-9952 Add test showing the issue has been solved

hibernate-core/src/test/java/org/hibernate/orm/test/annotations/embeddables/GenericEmbeddableWthSubclassTest.java
Add test showing the issue has been solved
https://hibernate.atlassian.net/browse/HHH-15560
=> HHH-15560 Querying Parametrized Embeddable Subclass not supported

hibernate-core/src/main/java/org/hibernate/StatelessSession.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/multivaluebinding/TopicPostTest.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/ClassWriter.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractAnnotatedMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaDeleteMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/IdFinderMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/LifecycleMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/NaturalIdFinderMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/QueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/TypeUtils.java
https://hibernate.atlassian.net/browse/HHH-18953
https://hibernate.atlassian.net/browse/HHH-18743
=> HHH-18953 Jakarta Data exception translation for reactive repos

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
[HHH-18960](https://hibernate.atlassian.net/browse/HHH-18960)
Revert changes that were only for testing, not for commit :-(
[HHH-18960]: https://hibernate.atlassian.net/browse/HHH-18960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HHH-18960 Reverted mistakenly commited change

gradle/java-module.gradle
=> Increase javac maximum memory to avoid builds getting stuck

ci/release/Jenkinsfile
https://hibernate.atlassian.net/browse/HHH-18963
=> HHH-18963 Switch to scheduled releases instead of release on push

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/temporal/MySQLTimestampFspFunctionTest.java
https://hibernate.atlassian.net/browse/HHH-18968
=> HHH-18968 Fix localtime return type for MySQL

hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java
=> remove todo

documentation/src/main/asciidoc/introduction/Entities.adoc, documentation/src/main/asciidoc/introduction/Interacting.adoc, documentation/src/main/asciidoc/introduction/Tuning.adoc, hibernate-core/src/main/java/org/hibernate/dialect/lock/LockingStrategy.java
=> Optimistic locking doc improvements

hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java
https://hibernate.atlassian.net/browse/HHH-18181
=> HHH-18181 Include property and class for PropertyBinder errors

hibernate-core/src/main/java/org/hibernate/annotations/processing/Find.java, hibernate-core/src/main/java/org/hibernate/annotations/processing/HQL.java, hibernate-core/src/main/java/org/hibernate/query/Restriction.java, hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java
https://hibernate.atlassian.net/browse/HHH-18979
=> HHH-18979 make Order/Restriction more prominent in jdoc for SelectionQuery

hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/ConnectionProviderInitiator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DatabaseConnectionInfoImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DatasourceConnectionProviderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DriverManagerConnectionProviderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/spi/ConnectionProvider.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/ExtractedDatabaseMetaDataImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/spi/ExtractedDatabaseMetaData.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/GlobalTemporaryTableStrategy.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/LocalTemporaryTableStrategy.java, hibernate-core/src/main/java/org/hibernate/resource/beans/internal/Helper.java, hibernate-core/src/test/java/org/hibernate/orm/test/datasource/DataSourceTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/datasource/TestDataSourceConnectionProvider.java, hibernate-testing/src/main/java/org/hibernate/testing/jdbc/ConnectionProviderDelegate.java, hibernate-testing/src/main/java/org/hibernate/testing/jta/JtaAwareConnectionProviderImpl.java
https://hibernate.atlassian.net/browse/HHH-18989
=> HHH-18989 log more info when DataSource is used

documentation/src/main/asciidoc/introduction/Interacting.adoc, hibernate-core/src/main/java/org/hibernate/query/AttributeRange.java, hibernate-core/src/main/java/org/hibernate/query/Conjunction.java, hibernate-core/src/main/java/org/hibernate/query/NamedAttributeRange.java, hibernate-core/src/main/java/org/hibernate/query/Negation.java, hibernate-core/src/main/java/org/hibernate/query/Path.java, hibernate-core/src/main/java/org/hibernate/query/PathElement.java, hibernate-core/src/main/java/org/hibernate/query/PathRange.java, hibernate-core/src/main/java/org/hibernate/query/PathRoot.java, hibernate-core/src/main/java/org/hibernate/query/Restriction.java, hibernate-core/src/main/java/org/hibernate/query/range/CaseInsensitiveValue.java, hibernate-core/src/main/java/org/hibernate/query/range/EmptyRange.java, hibernate-core/src/main/java/org/hibernate/query/range/FullRange.java, hibernate-core/src/main/java/org/hibernate/query/range/Interval.java, hibernate-core/src/main/java/org/hibernate/query/range/LowerBound.java, hibernate-core/src/main/java/org/hibernate/query/range/Pattern.java, hibernate-core/src/main/java/org/hibernate/query/range/UpperBound.java, hibernate-core/src/main/java/org/hibernate/query/range/Value.java, hibernate-core/src/main/java/org/hibernate/query/range/ValueList.java, hibernate-core/src/test/java/org/hibernate/orm/test/datasource/DataSourceTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/restriction/RestrictionTest.java
https://hibernate.atlassian.net/browse/HHH-18990
=> HHH-18990 introduce Path, allowing Restrictions on compound paths

hibernate-core/src/main/java/org/hibernate/boot/archive/internal/ExplodedArchiveDescriptor.java, hibernate-core/src/main/java/org/hibernate/boot/archive/internal/JarFileBasedArchiveDescriptor.java, hibernate-core/src/main/java/org/hibernate/boot/archive/internal/JarInputStreamBasedArchiveDescriptor.java, hibernate-core/src/main/java/org/hibernate/boot/archive/internal/JarProtocolArchiveDescriptor.java, hibernate-core/src/main/java/org/hibernate/boot/archive/scan/internal/DisabledScanner.java, hibernate-core/src/main/java/org/hibernate/boot/archive/spi/ArchiveDescriptor.java, hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/scanning/ScannerTest.java
https://hibernate.atlassian.net/browse/HHH-18987
=> HHH-18987 Implement discovery for META-INF/orm.xml also for DisabledScanner

hibernate-core/src/main/java/org/hibernate/query/criteria/CriteriaDefinition.java, hibernate-core/src/main/java/org/hibernate/query/criteria/JpaCriteriaQuery.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmDynamicInstantiation.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectStatement.java
=> some code reorg related to dynamic instantiation

hibernate-core/src/test/java/org/hibernate/orm/test/collection/basic/CollectionOneToManySizeTest.java
https://hibernate.atlassian.net/browse/HHH-3319
=> HHH-3319 Test for extra lazy ops on unowned one-to-many with restriction

hibernate-core/src/main/java/org/hibernate/cfg/PersistenceSettings.java, hibernate-core/src/main/java/org/hibernate/graph/AttributeNode.java, hibernate-core/src/main/java/org/hibernate/graph/Graph.java, hibernate-core/src/main/java/org/hibernate/graph/internal/AttributeNodeImpl.java, hibernate-core/src/main/java/org/hibernate/graph/internal/GraphImpl.java, hibernate-core/src/main/java/org/hibernate/graph/internal/RootGraphImpl.java, hibernate-core/src/main/java/org/hibernate/graph/internal/SubGraphImpl.java, hibernate-core/src/main/java/org/hibernate/graph/internal/parse/GraphParser.java, hibernate-core/src/main/java/org/hibernate/graph/internal/parse/PathQualifierType.java, hibernate-core/src/main/java/org/hibernate/graph/internal/parse/SubGraphGenerator.java, hibernate-core/src/main/java/org/hibernate/graph/spi/AttributeNodeImplementor.java, hibernate-core/src/main/java/org/hibernate/graph/spi/GraphImplementor.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/MapPersistentAttribute.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/AppliedGraphs.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/internal/StandardEntityGraphTraversalStateImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/parser/EntityGraphParserTest.java, migration-guide.adoc
=> Migration guide for graphs + further deprecations/typesafety

documentation/src/main/asciidoc/userguide/chapters/fetching/Fetching.adoc, hibernate-core/src/main/java/org/hibernate/graph/internal/AttributeNodeImpl.java, hibernate-core/src/main/java/org/hibernate/graph/spi/AttributeNodeImplementor.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/SingularPersistentAttribute.java, hibernate-core/src/test/java/org/hibernate/orm/test/fetching/GraphParsingTest.java, migration-guide.adoc
=> Graphpocalypse: one more refactor for extra typesafety

hibernate-core/src/main/java/org/hibernate/type/MappingContext.java
https://hibernate.atlassian.net/browse/HHH-18462
=> HHH-18462 fix up javadoc for MappingContext

Jenkinsfile, settings.gradle
https://hibernate.atlassian.net/browse/HHH-18972
Also backported to 6.6 as #9478.
=> HHH-18972 Upgrade to ByteBuddy 1.15.11

hibernate-core/src/main/java/org/hibernate/boot/MetadataBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ToOneBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/IdentifierSourceAggregatedCompositeImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/IdentifierSourceNonAggregatedCompositeImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/spi/CompositeIdentifierSource.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingMetadataBuilderImplementor.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingMetadataBuildingOptions.java, hibernate-core/src/main/java/org/hibernate/boot/spi/InFlightMetadataCollector.java, hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataBuildingOptions.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/derivedidentities/e1/b/specjmapid/Customer.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/derivedidentities/e1/b/specjmapid/CustomerInventory.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/derivedidentities/e1/b/specjmapid/CustomerInventoryPK.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/derivedidentities/e1/b/specjmapid/IdMapManyToOneSpecjTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/derivedidentities/e1/b/specjmapid/Item.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/derivedidentities/e1/b/specjmapid/lazy/CompositeKeyDeleteTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/derivedidentities/e1/b/specjmapid/lazy/CustomerInventoryTwo.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/derivedidentities/e1/b/specjmapid/lazy/CustomerTwo.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java
=> clean up the @MapsId inference ("specj") stuff

hibernate-core/src/main/java/org/hibernate/graph/EntityGraphs.java, hibernate-core/src/main/java/org/hibernate/graph/Graph.java, hibernate-core/src/main/java/org/hibernate/graph/RootGraph.java
https://hibernate.atlassian.net/browse/HHH-19023
=> HHH-19023 add operations on EntityGraphs to allow for session-free graph creation

hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/SharedSessionContract.java
=> improve the Javadoc for EntityGraph-related methods of Session

hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/EmbeddableMetaModelTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/Weight.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/WeightClass.java
https://hibernate.atlassian.net/browse/HHH-18819
=> HHH-18819 Error resolving persistent property of @MapperSuperclass if subtype @Embeddable used as @IdClass

hibernate-core/src/test/java/org/hibernate/orm/test/collection/PersistAfterRemoveTest.java
https://hibernate.atlassian.net/browse/HHH-4468
=> HHH-4468 Test persist after committing a remove

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/secondarytable/SecondaryTableQuotingTest.java
https://hibernate.atlassian.net/browse/HHH-6328
=> HHH-6328 Test and fix SecondaryRow/Table name matching with respect to physical name strategies

hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ComponentPropertyHolder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/InheritanceState.java, hibernate-core/src/main/java/org/hibernate/boot/spi/InFlightMetadataCollector.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java
=> some very minor cleanups to Binders

hibernate-core/src/test/java/org/hibernate/orm/test/orphan/one2one/fk/bidirectional/DeleteOneToOneOrphansTest.java
https://hibernate.atlassian.net/browse/HHH-7122
=> HHH-7122 Add test for inverse one-to-one orphan removal

documentation/src/main/asciidoc/querylanguage/Expressions.adoc
=> fix heading level

hibernate-core/src/test/java/org/hibernate/orm/test/collection/map/EntityMapKeyWithUniqueKeyEqualsHashCodeTest.java
https://hibernate.atlassian.net/browse/HHH-7045
=> HHH-7045 Test entity as map key with equals/hashCode based on unique key

hibernate-core/src/main/java/org/hibernate/binder/internal/CommentBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/comment/CommentElementCollectionTest.java
Proposal as it was suggested to backport the fix.
https://hibernate.atlassian.net/browse/HHH-19011
=>  HHH-19011 Backport to 6.6

hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentBag.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentIdentifierBag.java, hibernate-core/src/main/java/org/hibernate/type/CollectionType.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/manytomany/UnmodifiableCollectionMergeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/ops/MergeTest.java
Additional fix on top of https://github.com/hibernate/hibernate-orm/pull/9600
https://hibernate.atlassian.net/browse/HHH-1914
=> HHH-1914 Fix merge support for unmodifiable collections

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SingleStoreDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/hint/IndexQueryHintHandler.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryOptionsImpl.java, hibernate-core/src/test/java/org/hibernate/dialect/DialectTest.java
=> rename a confusingly-named method

hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
https://hibernate.atlassian.net/browse/HHH-2862
=> HHH-2862 Throw error instead of replacing collection with same key

hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/spi/PersistenceContext.java, hibernate-core/src/main/java/org/hibernate/type/CollectionType.java
https://hibernate.atlassian.net/browse/HHH-1914
https://hibernate.atlassian.net/browse/HHH-2862
=> HHH-2862, HHH-1914 Make collection replacement a first class operation on PersistenceContext

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CommunityDatabase.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CommunityDialectSelector.java, hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/CommunityDialectSelectorTest.java
https://hibernate.atlassian.net/browse/HHH-19033
=> HHH-19033 - Restore Derby dialect in the community dialects

documentation/src/main/asciidoc/repositories/Pagination.adoc, documentation/src/main/asciidoc/repositories/Repositories.adoc
=> document dynamic restrictions in Jakarta Data repos

hibernate-envers/src/test/java/org/hibernate/orm/test/envers/entities/onetomany/SetRefEdEntity.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/entities/onetomany/SetRefIngEntity.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/jta/OneToManyLazyJtaSessionClosedBeforeCommitTest.java
https://hibernate.atlassian.net/browse/HHH-14061
=> HHH-14061 Add test showing the issue has been resolved

hibernate-core/src/main/java/org/hibernate/LockMode.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/uuid/rfc9562/UUidV6V7GeneratorTest.java
=> A couple of typo fixes

hibernate-core/src/main/java/org/hibernate/boot/model/internal/BasicValueBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/InferredBasicValueResolution.java, hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/InferredBasicValueResolver.java, hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/NamedBasicTypeResolution.java, hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/NamedConverterResolution.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java, hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java, hibernate-core/src/main/java/org/hibernate/mapping/Column.java, hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddableMappingTypeImpl.java
along with some other compiler warnings
=> clean up some generic typing

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java
https://hibernate.atlassian.net/browse/HHH-19069
=> HHH-19069 Call startLoading on entity sub-initializers only once

hibernate-core/src/main/java/org/hibernate/boot/MetadataSources.java, hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/EnumeratedValueConverter.java, hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/ManagedResourcesImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/VersionResolution.java, hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java
=> fix some more warnings and add static imports

release/release.gradle
https://hibernate.atlassian.net/browse/HHH-19078
=> HHH-19078 Improve release process error message when no issues with corresponding version are found

release/release.gradle
https://hibernate.atlassian.net/browse/HHH-19078
=> [6.6] HHH-19078 Improve release process error message when no issues with corresponding version are found

hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/any/annotations/AnyFetchEagerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/any/annotations/LazyPropertySet.java
https://hibernate.atlassian.net/browse/HHH-13243
=> HHH-13243 Respect @ManyToAny.fetch setting to FetchType.EAGER

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmFrom.java, hibernate-core/src/test/java/org/hibernate/orm/test/join/JoinAndFetchWithCriteriaSelectionQueryTest.java
Fix for https://hibernate.atlassian.net/browse/HHH-19034
For main
=> Fix wrong reuse for Joins in main

documentation/src/main/asciidoc/introduction/Tuning.adoc, hibernate-core/src/main/java/org/hibernate/Cache.java, hibernate-core/src/main/java/org/hibernate/query/Query.java
=> Second-level cache doc enhancement

.github/workflows/ci.yml, databases/oracle/matrix.gradle, docker_db.sh, documentation/src/main/asciidoc/introduction/Configuration.adoc, documentation/src/main/asciidoc/repositories/Configuration.adoc, hibernate-ucp/hibernate-ucp.gradle, local-build-plugins/src/main/groovy/local.databases.gradle, settings.gradle
https://hibernate.atlassian.net/browse/HHH-18877
=> HHH-18877 Switch to ojdbc17 version 23.6.0.24.10

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/CoreCacheProvider.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/CorePrefixFilter.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/CoreTypePool.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/ModelTypePool.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/OverridingClassFileLocator.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/SafeCacheProvider.java, hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/PersistenceUnitInfoDescriptor.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/enhance/EnhancingClassTransformerImpl.java
Forward-ported to `main` the patch we discussed in #9636 
- https://hibernate.atlassian.net/browse/HHH-18901
=> HHH-18901 The entity enhancement process made defensive against concurrent enhancement

tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Bookshop.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/ClassWriter.java
=> HHH-19106 deconstruct inherited annotations before printing them

hibernate-core/src/main/java/org/hibernate/tool/schema/internal/Helper.java
=> very minor code changes in Helper

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java, hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessEnhancedImpl.java, hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyEnhancedImpl.java, hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyResolverStandardImpl.java, hibernate-core/src/main/java/org/hibernate/property/access/spi/EnhancedGetterFieldImpl.java, hibernate-core/src/main/java/org/hibernate/property/access/spi/GetterFieldImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/access/PropertyAccessMemberTest.java
https://hibernate.atlassian.net/browse/HHH-18928
Backport of https://github.com/hibernate/hibernate-orm/pull/9694.
=> [6.6] HHH-18928 Consider the default Access Type as per Spec section 2.3.1 and skip enhancement of properties accessor

documentation/src/main/asciidoc/userguide/chapters/batch/Batching.adoc, etc/hibernate.properties, etc/hibernate.properties.template, hibernate-spatial/src/test/resources/hibernate.properties
https://hibernate.atlassian.net/browse/HHH-18621
=> HHH-18621 remove hibernate.jdbc.batch_versioned_data from docs

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddableMappingTypeImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/columndiscriminator/Author.java, hibernate-core/src/test/java/org/hibernate/orm/test/columndiscriminator/Book.java, hibernate-core/src/test/java/org/hibernate/orm/test/columndiscriminator/BookDetails.java, hibernate-core/src/test/java/org/hibernate/orm/test/columndiscriminator/BoringBookDetails.java, hibernate-core/src/test/java/org/hibernate/orm/test/columndiscriminator/ColumnDiscrimnatorWithSchemaTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/columndiscriminator/SpecialBookDetails.java, hibernate-core/src/test/resources/org/hibernate/orm/test/columndiscriminator/orm.xml
https://hibernate.atlassian.net/browse/HHH-18988
=> HHH-18988 Embeddable inheritance + default_schema results in NPE at startup (6.6 backport)

documentation/src/main/asciidoc/userguide/chapters/caching/Caching.adoc
https://hibernate.atlassian.net/browse/HHH-19121
=> HHH-19121 Update link to Infinispan integration

hibernate-core/src/main/java/org/hibernate/cfg/SchemaToolingSettings.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaCreatorImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/tool/schema/SkipDefaultImportFileExecutionTest.java
https://hibernate.atlassian.net/browse/HHH-19098
=> HHH-19098 Disable implicit loading of the default import script

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AbstractPluralAttribute.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmPluralValuedSimplePath.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmMemberOfPredicate.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/paths/PluralAttributeExpressionsTest.java
https://hibernate.atlassian.net/browse/HHH-19126
=> HHH-19126 Plural valued paths should be collection-typed instead of element typed

hibernate-core/src/main/java/org/hibernate/collection/spi/AbstractPersistentCollection.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/ListAndSetProxyTest.java
https://hibernate.atlassian.net/browse/HHH-11801
=> HHH-11801 Ensure ListProxy and SetProxy implement equals/hashCode

hibernate-core/src/main/java/org/hibernate/LockOptions.java, hibernate-core/src/main/java/org/hibernate/sql/results/spi/ListResultsConsumer.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaAttribute.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/DataAnnotationMetaAttribute.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/TypeUtils.java
=> two minor changes

hibernate-core/src/main/java/org/hibernate/pretty/MessageHelper.java, hibernate-core/src/main/java/org/hibernate/type/CollectionType.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/delayedOperation/DetachedBagDelayedOperationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/pc/FilterTest.java
=> Entity log format

hibernate-core/src/main/java/org/hibernate/type/EntityType.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/cid/NestedCompositeIdWithOrderedUpdatesTest.java
https://hibernate.atlassian.net/browse/HHH-19110
=> HHH-19110 - Update ordering with nested composite Ids

hibernate-core/src/main/java/org/hibernate/action/internal/AbstractEntityInsertAction.java, hibernate-core/src/main/java/org/hibernate/engine/internal/Nullability.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CascadingActions.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDeleteEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
includes a bugfix to nullability checking of composite collection elements
=> improvements to Nullability and CascadingActions

hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/query/sql/spi/NativeQueryImplementor.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/collectionelement/ordered/ElementCollectionSortingTest.java, local-build-plugins/src/main/groovy/local.javadoc.gradle
=> Very minor changes

hibernate-core/src/main/java/org/hibernate/Hibernate.java, hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/UnknownEntityTypeException.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappingMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/NamedCallableQueryMementoImpl.java, hibernate-core/src/main/java/org/hibernate/procedure/spi/NamedCallableQueryMemento.java, hibernate-core/src/main/java/org/hibernate/query/Query.java, hibernate-core/src/main/java/org/hibernate/query/QueryProducer.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterNamedImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterPositionalImpl.java, hibernate-core/src/main/java/org/hibernate/query/named/NamedQueryMemento.java, hibernate-core/src/main/java/org/hibernate/query/named/NamedResultSetMappingMemento.java, hibernate-core/src/main/java/org/hibernate/query/results/internal/Builders.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/QueryImplementor.java, hibernate-core/src/main/java/org/hibernate/query/spi/QueryProducerImplementor.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/query/QueryAndSQLTest.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DomainModelScope.java
=> refactoring of handling of named and native Query construction

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java, hibernate-core/src/main/java/org/hibernate/mapping/RootClass.java, shared/javadoc/overview.html
=> some minor things

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacySqlAstTranslator.java
https://hibernate.atlassian.net/browse/HHH-19173
=> HHH-19173 Add visitInArrayPredicate to PostgreSQLLegacySqlAstTranslator

hibernate-core/src/main/java/org/hibernate/query/internal/BindingTypeHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/DateTimeParameterTest.java
https://hibernate.atlassian.net/browse/HHH-17151
=> HHH-17151 NPE when binding null parameter in native query with explicit TemporalType

databases/oracle/matrix.gradle, settings.gradle
https://hibernate.atlassian.net/browse/HHH-19176
=> HHH-19176 Upgrade Oracle JDBC drivers to 23.7

docker_db.sh
=> Try increase Sybase heap memory to avoid transient errors

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/InlineDirtyCheckingHandler.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/DirtyTrackingIdTest.java
https://hibernate.atlassian.net/browse/HHH-19206
=> HHH-19206 Skip dirty tracking for embedded id fields

ci/build.sh, docker_db.sh, edb/edb13.Dockerfile, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/json/PostgreSQLJsonMergepatchFunction.java, hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayTrimTest.java, nightly.Jenkinsfile
https://hibernate.atlassian.net/browse/HHH-17316
=> HHH-17316/HHH-17317/HHH-17318 Remove support for PostgreSQL and EDB 12

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/embeddable/InheritedPropertyTest.java
https://hibernate.atlassian.net/browse/HHH-19195
Backport of https://github.com/hibernate/hibernate-orm/pull/9785
=> HHH-19195 Embeddable inheritance: discriminator values are not hierarchically ordered

hibernate-core/src/main/java/org/hibernate/annotations/FetchMode.java
=> Fix typo at Javadoc comment

hibernate-envers/src/main/java/org/hibernate/envers/event/spi/EnversPostUpdateEventListenerImpl.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/lazy/LazyFieldsTest.java
https://hibernate.atlassian.net/browse/HHH-19220
=> HHH-19220 ClassCastException: class org.hibernate.bytecode.enhance.spi.LazyPropertyInitializer$1 cannot be cast to class java.lang.String

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/EntityGraphAndJoinFetchTest.java
https://hibernate.atlassian.net/browse/HHH-19246
=> HHH-19246 Traverse entity graph also for explicit join fetches

hibernate-core/src/main/java/org/hibernate/property/access/internal/AccessStrategyHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/access/HierarchyPropertyAccessTest.java
https://hibernate.atlassian.net/browse/HHH-19140
=> Backport of PR#9758 : HHH-19140 Reproducer test and issue fix (#9758)

hibernate-core/src/main/java/org/hibernate/sql/Template.java, hibernate-core/src/test/java/org/hibernate/orm/test/joinsubquery/JoinSubqueryTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/TemplateTest.java
Jira issue [HHH-18570](https://hibernate.atlassian.net/browse/HHH-18570)
Backporting PR [#8892](https://github.com/hibernate/hibernate-orm/pull/8892) to `6.6`
This is also fixing Jira issue [HHH-19052](https://hibernate.atlassian.net/browse/HHH-19052)
[HHH-18570]: …
=> HHH-18570 backport to 6.6 ; solving problem described in HHH-19052

documentation/src/main/asciidoc/introduction/Interacting.adoc, hibernate-core/src/main/java/org/hibernate/Interceptor.java, hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java
=> minor improvements

hibernate-core/src/main/java/org/hibernate/boot/model/TypeContributions.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/hhh18787/CustomData.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/hhh18787/CustomDataType.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/hhh18787/SomeEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/hhh18787/TypesContributor.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/hhh18787/UserTypeNotRecognisedTestCase.java
Jira issue [HHH-18787](https://hibernate.atlassian.net/browse/HHH-18787)
Backporting changes from PR [#9205](https://github.com/hibernate/hibernate-orm/pull/9205) to 6.6
[HHH-18787]: https://hibernate.atlassian.net/browse/HHH-18787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
=> HHH-18787 [6.6 backport] Custom UserType not recognised for array properties

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/main/java/org/hibernate/boot/models/spi/JpaEventListener.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/XmlAnnotationHelper.java, hibernate-core/src/main/java/org/hibernate/internal/log/DeprecationLogger.java, hibernate-core/src/main/java/org/hibernate/jpa/event/internal/CallbackDefinitionResolver.java, hibernate-core/src/main/java/org/hibernate/jpa/event/internal/EmbeddableCallback.java, hibernate-core/src/main/java/org/hibernate/mapping/Property.java, migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-19253
=> HHH-19253 deprecate callbacks declared by embeddables (and related cleanups)

hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorAnnotationHelper.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/InheritanceState.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/test/java/org/hibernate/IdGeneratorOverridingTest.java
https://hibernate.atlassian.net/browse/HHH-19252
=> HHH-19252 detect unsupported @Id generation overriding

hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java, hibernate-spatial/src/test/java/org/hibernate/spatial/integration/functions/CommonFunctionTests.java, hibernate-spatial/src/test/java/org/hibernate/spatial/testing/SpatialSessionFactoryAware.java
- Fixes issues HHH-19254
- Fixes spatial functions test suite  
=> HHH-19254 fix envelope function on MariaDB

hibernate-core/src/main/java/org/hibernate/cfg/JdbcSettings.java
=> document default for hibernate.jdbc.use_get_generated_keys

hibernate-core/src/main/java/org/hibernate/ScrollMode.java, hibernate-core/src/main/java/org/hibernate/ScrollableResults.java, hibernate-core/src/main/java/org/hibernate/internal/EmptyScrollableResults.java, hibernate-core/src/main/java/org/hibernate/internal/FetchingScrollableResultsImpl.java, hibernate-core/src/main/java/org/hibernate/internal/ScrollableResultsImpl.java, hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcSelectExecutorStandardImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesCacheHit.java, hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesResultSetImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/ScrollableCollectionFetchingTest.java
https://hibernate.atlassian.net/browse/HHH-19266
=> HHH-19266 fix bugs and inconsistencies in ScrollableResults

documentation/src/main/asciidoc/introduction/Entities.adoc
=> fix field name in @OneToOne examples

documentation/documentation.gradle, hibernate-testing/src/main/java/org/hibernate/testing/bytecode/enhancement/extension/engine/BytecodeEnhancedTestEngine.java, local-build-plugins/src/main/groovy/local.java-module.gradle, settings.gradle, tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
https://hibernate.atlassian.net/browse/HHH-19196
=> HHH-19196 Upgrade to JUnit 5.12.0

hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/LoadGraphMergeTest.java
https://hibernate.atlassian.net/browse/HHH-15271
=> HHH-15271 Don't initialize lazy associations via merge

settings.gradle
https://hibernate.atlassian.net/browse/HHH-19223
=> HHH-19223 Upgrade JBoss Logging Tools (processor) to 3.0.4.Final

migration-guide.adoc
=> improvements to the migration guide

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationProcess.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, tooling/hibernate-ant/src/main/java/org/hibernate/tool/hbm2ddl/SchemaExport.java, tooling/hibernate-ant/src/main/java/org/hibernate/tool/hbm2ddl/SchemaUpdate.java
=> various minor code cleanups

tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java
presence of JTA was not detected due to misspelling of package name
https://hibernate.atlassian.net/browse/HHH-19109
=> Backport of #9855 - HHH-19109 fix use of @TransactionScoped by repository

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java, hibernate-core/src/test/java/org/hibernate/orm/test/lazyonetoone/LazyOneToOneWithEntityGraphTest.java
https://hibernate.atlassian.net/browse/HHH-19017
=> HHH-19017: Address ClassCastException for PersistentAttributeInterceptable

hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/StatelessSession.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
much more convenient for the caller
=> use List<?> to pass ids to Session.findMultiple() and StatelessSession.getMultiple()

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
=> clean up some obsolete code in EntityBinder

hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java, hibernate-core/src/main/java/org/hibernate/exception/ConstraintViolationException.java
=>  HHH-19300 further Improvements to constraint violation interpretation

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java, hibernate-core/src/main/java/org/hibernate/exception/spi/TemplatedViolatedConstraintNameExtractor.java, hibernate-core/src/main/java/org/hibernate/mapping/CheckConstraint.java, hibernate-core/src/test/java/org/hibernate/orm/test/constraint/ConstraintInterpretationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/constraint/ConstraintInterpretationTest2.java
=> HHH-19300 tests for constraint interpretation and tiny bugfixes

hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HANADialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/constraint/ConstraintInterpretationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/constraint/ConstraintInterpretationTest2.java
=> More constraint interpretation fixes

documentation/src/main/asciidoc/introduction/Introduction.adoc
=> add mea culpa about stateful vs stateless

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/spi/SqmMultiTableInsertStrategy.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/spi/SqmMultiTableMutationStrategy.java
=> refactor a much too long and confusing method on AbstractEntityPersister

release_notes.md
=> Fix a typo in the release note url

hibernate-core/src/main/java/org/hibernate/tuple/entity/CompositeGeneratorBuilder.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/CreationUpdatedTimestampInEmbeddableTest.java
https://hibernate.atlassian.net/browse/HHH-19306
=> HHH-19306 Only apply the composite sub-generator if the event type is acceptable

ci/release/Jenkinsfile
=> Test the ci-commiter before checking the release type (manual/automatic)

hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/exception/TransactionSerializationException.java
this code is basically a copy/paste job so lets keep it that way
=> sync impl of error interpretation on Cockroach and Postgres

settings.gradle
https://hibernate.atlassian.net/browse/HHH-19325
=> HHH-19325 - Upgrade to Jandex 3.3.0

hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
=> add a comment explaining motivation for @beikov's fix

hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/unit/locktimeout/PostgreSQLLockTimeoutTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiLoadLockingTest.java
https://hibernate.atlassian.net/browse/HHH-19330
=> HHH-19330 - Fix for issue

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/insert/AbstractSqmInsertStatement.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/insert/SqmConflictClause.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/insert/SqmInsertSelectStatement.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/insert/SqmInsertValuesStatement.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/InsertConflictWithCriteriaCopyTreeEnabledTests.java
https://hibernate.atlassian.net/browse/HHH-19314
backport of https://github.com/hibernate/hibernate-orm/pull/9953 for 6.6
=> HHH-19314 StackOverflowException when using onConflict with createCriteriaInsertValues and createCriteriaInsertSelect

hibernate-core/src/main/java/org/hibernate/boot/model/internal/NamedGraphCreatorJpa.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/DdlTypeHelper.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/JsonArrayViaElementArgumentReturnTypeResolver.java, hibernate-core/src/main/java/org/hibernate/graph/internal/AttributeNodeImpl.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderStandardImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AnyMappingDomainType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/BasicDomainType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/DomainType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/IdentifiableDomainType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/ManagedDomainType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/SimpleDomainType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AbstractDomainType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AbstractManagedType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EmbeddableTypeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/SingularAttributeImpl.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/TypecheckUtil.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmBasicValuedSimplePath.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmDomainType.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectableNode.java, hibernate-core/src/main/java/org/hibernate/type/BasicType.java, hibernate-core/src/main/java/org/hibernate/type/CustomType.java
https://hibernate.atlassian.net/browse/HHH-16972
=> HHH-16972 fallout

README.adoc, gradle/gradle-enterprise.gradle
=> HIB-140 Switch to develocity.commonhaus.dev instance

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDeleteEventListener.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
https://hibernate.atlassian.net/browse/HHH-19345
=> HHH-19345 Relax JPA bootstrap entity state checks for remove

Jenkinsfile, README.adoc, gradle/gradle-develocity.gradle
=>  HIB-140 Switch to access keys for develocity.commonhaus.dev

hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/cfg/QuerySettings.java, hibernate-core/src/main/java/org/hibernate/query/spi/ImmutableEntityUpdateQueryHandlingMode.java, hibernate-core/src/main/java/org/hibernate/query/spi/QueryEngineOptions.java, hibernate-core/src/main/java/org/hibernate/query/sqm/NodeBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/update/SqmUpdateStatement.java
https://hibernate.atlassian.net/browse/HHH-19349
=> HHH-19349 move an enum to SPI package where its usage is

hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/util/CacheModeHelper.java
=> use switch expressions in CacheModeHelper

ci/quarkus.Jenkinsfile
=> Exclude Quarkus module that consumes too much memory

hibernate-core/src/main/java/org/hibernate/dialect/OracleSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/BasicValuedPathInterpretation.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EmbeddableValuedPathInterpretation.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/NonAggregatedCompositeValuedPathInterpretation.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/SqlTupleContainer.java
=> reduce copy/paste in some code in org.hibernate.query.sqm.sql.internal

hibernate-core/src/main/java/org/hibernate/CustomEntityDirtinessStrategy.java, hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java
=> add code example to javadoc of CustomEntityDirtinessStrategy

hibernate-core/src/main/java/org/hibernate/query/range/Interval.java, hibernate-core/src/main/java/org/hibernate/query/range/Pattern.java, hibernate-core/src/main/java/org/hibernate/query/range/ValueList.java
https://hibernate.atlassian.net/browse/HHH-18991
=> HHH-18991 enable more use of parameters in Restrictions

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MariaDBLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MariaDBLegacySqlAstTranslator.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacySqlAstTranslator.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SingleStoreDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SingleStoreSqlAstTranslator.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/TiDBDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/TiDBSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/sql/ast/MariaDBSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/sql/ast/MySQLSqlAstTranslator.java
https://hibernate.atlassian.net/browse/HHH-19370
=> Dialect typecasts

hibernate-core/src/main/java/org/hibernate/query/QueryProducer.java, hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/MutationSpecification.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/QuerySpecification.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/SelectionSpecification.java, hibernate-core/src/main/java/org/hibernate/query/restriction/Path.java, hibernate-core/src/main/java/org/hibernate/query/restriction/Restriction.java
=> update the javadoc after the addition of QuerySpecification

documentation/src/main/asciidoc/introduction/Introduction.adoc
=> add a note about "leaky abstractions"

documentation/src/main/asciidoc/introduction/Configuration.adoc, documentation/src/main/asciidoc/introduction/Entities.adoc, documentation/src/main/asciidoc/introduction/Interacting.adoc, documentation/src/main/asciidoc/introduction/Introduction.adoc
=> misc updates to Short Guide before release

documentation/src/main/asciidoc/introduction/Interacting.adoc, documentation/src/main/asciidoc/introduction/Processor.adoc
=> clarify a point in the Short Guide

tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java
also look for io.quarkus.hibernate.reactive
=> improve test for whether we should use Quarkus injection

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
I don't love this at all -- see the comment :-/
=> make repositories always @Dependent-scoped

hibernate-core/src/main/java/org/hibernate/query/programmatic/MutationSpecification.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/QuerySpecification.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/SelectionSpecification.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/internal/MutationSpecificationImpl.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/internal/SelectionSpecificationImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/AbstractSqmSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/dynamic/SimpleQuerySpecificationTests.java
=> HHH-19364 make a Specification convertible to a CriteriaQuery

hibernate-core/src/main/java/org/hibernate/query/programmatic/QuerySpecification.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/SelectionSpecification.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/internal/MutationSpecificationImpl.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/internal/SelectionSpecificationImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/dynamic/SimpleQuerySpecificationTests.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractCriteriaMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaDeleteMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaFinderMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/QueryMethod.java
=> HHH-19364 continue rewriting Processor to use Specifications

hibernate-core/src/main/java/org/hibernate/query/programmatic/SelectionSpecification.java
=> HHH-19364 add a tiny bit of additional jdoc

hibernate-core/src/main/java/org/hibernate/query/AttributeOrder.java, hibernate-core/src/main/java/org/hibernate/query/ElementOrder.java, hibernate-core/src/main/java/org/hibernate/query/NamedAttributeOrder.java, hibernate-core/src/main/java/org/hibernate/query/Order.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/KeyBasedPagination.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
=> reimplement Order using record classes

documentation/src/main/asciidoc/introduction/Querying.adoc, documentation/src/main/asciidoc/introduction/Tuning.adoc
=> expand a doc section about SS

hibernate-core/src/main/java/org/hibernate/query/Order.java, hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/restriction/Restriction.java, hibernate-core/src/main/java/org/hibernate/query/specification/MutationSpecification.java, hibernate-core/src/main/java/org/hibernate/query/specification/SelectionSpecification.java
=> HHH-19364 final touches to jdoc before release

ci/release/Jenkinsfile
=> HHH-19341 Align env variable names to match the release scripts

migration-guide.adoc
=> add two more items to migration guide

documentation/src/main/asciidoc/introduction/Processor.adoc
=> add more words and subsections to Hibernate Processor doc chapter

hibernate-core/src/main/java/org/hibernate/type/internal/UserTypeJavaTypeWrapper.java, hibernate-core/src/main/java/org/hibernate/usertype/UserType.java
=> UserType recommendation of its JdbcType

ci/snapshot-publish.Jenkinsfile, jreleaser.yml, local-build-plugins/src/main/groovy/local.publishing.gradle, release/README.adoc
=> HHH-19341 Use publish Gradle plugin for snapshot publishing

hibernate-core/src/test/java/org/hibernate/orm/test/boot/models/xml/dynamic/DynamicTypingTests.java
https://hibernate.atlassian.net/browse/HHH-19324
=> HHH-19324 Additional `DynamicTypingTests` fix for hana_cloud

hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/LimitOffsetTest.java
https://hibernate.atlassian.net/browse/HHH-19397
=> HHH-19397 allow LIMIT + OFFSET without ORDER BY

hibernate-core/src/test/java/org/hibernate/orm/test/query/binding/Address.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/binding/ParameterBindTypeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/binding/Person.java
https://hibernate.atlassian.net/browse/HHH-19449
=> HHH-19449 proper test demoing use of static metamodel for parameter binding

hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureParameterImpl.java, hibernate-core/src/main/java/org/hibernate/query/CommonQueryContract.java, hibernate-core/src/main/java/org/hibernate/query/TypedParameterValue.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingImpl.java, hibernate-core/src/main/java/org/hibernate/query/spi/QueryParameterBindingValidator.java, hibernate-core/src/main/java/org/hibernate/sql/exec/spi/JdbcParameterBindings.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/TemporalJavaType.java, hibernate-core/src/main/java/org/hibernate/type/internal/BindingTypeHelper.java
https://hibernate.atlassian.net/browse/HHH-19449
=> HHH-19449 mop up

hibernate-core/src/main/java/org/hibernate/LockMode.java, hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/Timeouts.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, migration-guide.adoc, whats-new.adoc
https://hibernate.atlassian.net/browse/HHH-19449
https://hibernate.atlassian.net/browse/HHH-19440
=> Two last things

documentation/src/main/asciidoc/introduction/Interacting.adoc
=> much better placement/flow of new doc section

hibernate-core/src/test/java/org/hibernate/orm/test/annotations/xml/ejb3/Ejb3XmlTestCase.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/models/SourceModelTestHelper.java, settings.gradle
https://hibernate.atlassian.net/browse/HHH-19456
=> HHH-19456 - Upgrade to hibernate-models 1.0.0.CR3

tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java
so we don't need to go locating and instantiating unnecessary services
https://hibernate.atlassian.net/browse/HHH-19458
=> HHH-19458 6.6 backport processor reactive fix for Quarkus

build.gradle, ci/release/Jenkinsfile, gradle/published-java-module.gradle, gradle/publishing-pom.gradle, hibernate-platform/hibernate-platform.gradle, tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
=> HHH-19341 Backport JReleaser config to 6.2

build.gradle, ci/release/Jenkinsfile, ci/snapshot-publish.Jenkinsfile, gradle/published-java-module.gradle, gradle/publishing-pom.gradle, hibernate-platform/hibernate-platform.gradle, tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
=> HHH-19341 Backport JReleaser config to 6.4

.github/workflows/codeql.yml, .github/workflows/contributor-build.yml, .release/.gitignore, build.gradle, ci/release/Jenkinsfile, ci/snapshot-publish.Jenkinsfile, gradle/published-java-module.gradle, gradle/publishing-repos.gradle, hibernate-infinispan/hibernate-infinispan.gradle, release/release.gradle
=> HHH-19341 Add automated release to 5.6

hibernate-orm-modules/hibernate-orm-modules.gradle
=> HHH-19341 Fix hibernate-orm-modules snapshot release issue

documentation/src/main/asciidoc/introduction/Advanced.adoc, hibernate-core/src/main/java/org/hibernate/EnabledFetchProfile.java, hibernate-core/src/main/java/org/hibernate/annotations/FetchProfileOverride.java
=> properly document EnabledFetchProfile

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedColumn.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedJoinColumn.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/TableBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/naming/ImplicitNamingStrategyJpaCompliantImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/naming/NamingHelper.java, hibernate-core/src/main/java/org/hibernate/mapping/Table.java, hibernate-core/src/main/java/org/hibernate/query/sql/spi/SelectInterpretationsKey.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardSequenceExporter.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardUniqueKeyExporter.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/namingstrategy/DummyNamingStrategy.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/namingstrategy/LongIdentifierNamingStrategy.java
=> various minor fixes

changelog.txt
=> Update ORM version in the changelog

hibernate-core/src/main/java/org/hibernate/jpa/spi/NativeQueryArrayTransformer.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/SingleSelectionArrayResultTest.java
The fix is quite simple and obvious. I also refactored the test that was previously introduced for [HHH-18450](https://hibernate.atlassian.net/browse/HHH-18450) to cover more cases and make it easier to maintain.
My understanding is that when executing queries (any kind), we either provide a row transformer, a tuple transformer or the expected result class. Sqm-based queries are providing the row transformer directly (based on the result class) while native queries are currently implemented with providing directly the tuple transformer.
So I went with fitting in the existing code by supporting `Object[]` at the tuple transformer level for native queries.
Alternatively I looked into producing a row transformer in `NativeSelectQueryPlanImpl` or moving all the default row transformer …
=> HHH-19472: native queries can return Object[]

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/ForeignPackageSuperclassAccessorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/SuperclassEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/AncestorEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/ChildEntity3.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/ChildEntity4.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/ChildEntity5.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/ChildEntity6.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/ChildEntity7.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/ChildEntity8.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/ChildEntity9.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/HierarchyBytecodeOptimizerMethodVisibilityTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/HierarchyBytecodeOptimizerOrderingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/HierarchyBytecodeOptimizerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/ParentEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/child/ChildEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/child/ChildEntity10.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/parent/Ancestor.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/parent/ChildEntity2.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/foreignpackage/ConcreteEntity.java
https://hibernate.atlassian.net/browse/HHH-19369
https://hibernate.atlassian.net/browse/HHH-19372
=> HHH-19372 HHH-19369 Test and fix CCE and IAE with access optimizer and inheritance

hibernate-core/src/main/java/org/hibernate/dialect/temptable/TemporaryTableHelper.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/internal/PreparedStatementDetailsStandard.java, hibernate-core/src/main/java/org/hibernate/id/insert/AbstractSelectingDelegate.java, hibernate-core/src/main/java/org/hibernate/id/insert/GetGeneratedKeysDelegate.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/AbstractDeleteCoordinator.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureOutputsImpl.java, hibernate-core/src/main/java/org/hibernate/result/internal/OutputsImpl.java, hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/DeleteOrUpsertOperation.java, hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/OptionalTableUpdateOperation.java, hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/DeferredResultSetAccess.java, hibernate-core/src/test/java/org/hibernate/orm/test/jdbc/internal/AggressiveReleaseTest.java
https://hibernate.atlassian.net/browse/HHH-19477
=> HHH-19477 ConnectionReleaseMode.AFTER_STATEMENT ineffective due to missing connection release

hibernate-core/src/main/java/org/hibernate/TransientPropertyValueException.java, hibernate-core/src/main/java/org/hibernate/action/internal/UnresolvedEntityInsertActions.java, hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java, hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CascadingAction.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CascadingActions.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityIdentifierMapping.java
=> produce more helpful TransientPropertyValueExceptions

ci/release/Jenkinsfile
=> [6.6] Backport "Use a script to release on Jira + avoid auto-release when there are no "releasable" commits"

ci/release/Jenkinsfile
Backport of https://github.com/hibernate/hibernate-orm/pull/10235
=> [6.4] Backport "Use a script to release on Jira + avoid auto-release when there are no "releasable" commits"

hibernate-core/src/main/java/org/hibernate/engine/internal/ForeignKeys.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDeleteEventListener.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/BasicEntityIdentifierMappingImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddedIdentifierMappingImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/NonAggregatedIdentifierMappingImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java, hibernate-core/src/main/java/org/hibernate/proxy/pojo/BasicLazyInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/AbstractBatchEntitySelectFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/DiscriminatedEntityInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/JpaProxyComplianceEnabledTest.java
https://hibernate.atlassian.net/browse/HHH-19476
https://github.com/hibernate/hibernate-orm/pull/10207 backport for 6.6
=> HHH-19476 claimEntityHolderIfPossible Assertion Error

hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/sql/ast/DB2SqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/UpsertTest.java
https://hibernate.atlassian.net/browse/HHH-19494
=> HHH-19494 MERGE on Db2

hibernate-core/src/main/java/org/hibernate/action/internal/CollectionAction.java, hibernate-core/src/main/java/org/hibernate/action/internal/CollectionUpdateAction.java, hibernate-core/src/main/java/org/hibernate/action/internal/EntityAction.java, hibernate-core/src/main/java/org/hibernate/cfg/BatchSettings.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentArrayHolder.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentBag.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentCollection.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentIdentifierBag.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentList.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentMap.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentSet.java, hibernate-core/src/main/java/org/hibernate/engine/internal/ForeignKeys.java, hibernate-core/src/main/java/org/hibernate/engine/internal/NonNullableTransientDependencies.java, hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java, hibernate-core/src/main/java/org/hibernate/engine/spi/ExecutableList.java, hibernate-core/src/test/java/org/hibernate/orm/test/actionqueue/CollectionUpdateOrderingTest.java
https://hibernate.atlassian.net/browse/HHH-19508
=> HHH-19508 sort CollectionUpdateActions to avoid UK violations

documentation/src/main/asciidoc/introduction/Configuration.adoc
https://hibernate.atlassian.net/browse/HHH-16548
=> HHH-16548 add documentation to Short Guide

ci/jpa-3.1-tck.Jenkinsfile
=> [6.2] Limit disk usage of TCK reports

ci/release/Jenkinsfile
This will take effect after the next release (7.0.2).
=> Enable weekly releases (if there's something new) for branch 7.0

hibernate-core/src/main/java/org/hibernate/jpa/spi/NativeQueryConstructorTransformer.java
https://hibernate.atlassian.net/browse/HHH-19533
Backport of https://github.com/hibernate/hibernate-orm/pull/10307
=> [6.6] implement equals() / hashCode() for NativeQueryConstructorTransformer

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/LazyAttributeLoadingInterceptor.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/LazyAttributesMetadata.java
A straight-forward optimisation.
https://hibernate.atlassian.net/browse/HHH-19537
=> HHH-19537 Simplify amount of computations performed during LazyAttributeLoadingInterceptor ctor

ci/release/Jenkinsfile, ci/snapshot-publish.Jenkinsfile, local-build-plugins/src/main/groovy/local.publishing.gradle
=> Move to Central publishing 7.0

ci/release/Jenkinsfile, ci/snapshot-publish.Jenkinsfile, gradle/publishing-pom.gradle
=> Move to Central publishing 6.4

ci/release/Jenkinsfile, gradle/publishing-pom.gradle
=> Move to Central publishing 6.2

ci/release/Jenkinsfile, ci/snapshot-publish.Jenkinsfile, gradle/publishing-repos.gradle
=> Move to Central publishing

ci/release/Jenkinsfile, ci/snapshot-publish.Jenkinsfile, gradle/publishing-repos.gradle
=> Move to Central publishing 5.3

Jenkinsfile
=> Allow builds with test jdk versions on PRs with custom labels

Jenkinsfile
Backport of https://github.com/hibernate/hibernate-orm/pull/10348
=> [7.0] Allow builds with test jdk versions on PRs with custom labels

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
https://hibernate.atlassian.net/browse/HHH-19547
=> HHH-19547 backport to 7.0

hibernate-core/src/main/java/org/hibernate/type/BasicArrayType.java, hibernate-core/src/main/java/org/hibernate/type/BasicCollectionType.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/ByteArrayMappingTests.java
https://hibernate.atlassian.net/browse/HHH-19573
=> [6.2] HHH-19573 Special case primitive type names for plural basic types

hibernate-core/src/main/java/org/hibernate/type/BasicArrayType.java, hibernate-core/src/main/java/org/hibernate/type/BasicCollectionType.java, hibernate-core/src/main/java/org/hibernate/type/ConvertedBasicArrayType.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/ByteArrayMappingTests.java
https://hibernate.atlassian.net/browse/HHH-19573
=> [6.6] HHH-19573 Special case primitive type names for plural basic types

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractCriteriaMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/QueryMethod.java
this is something we just agreed to require in the 1.1. spec
=> check that arguments to special parameters of repository methods are non-null

hibernate-core/src/test/java/org/hibernate/orm/test/lob/InformixLobStringTest.java
https://hibernate.atlassian.net/browse/HHH-8511
=> HHH-8511 add passing test

hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/EmbeddableWithJavaTypeTest.java
https://hibernate.atlassian.net/browse/HHH-18898
=> [6.6] HHH-18898 fix of a NPE when using an embeddable with a specified JavaType

gradle/version.properties
Fix snapshot version as `6.6.19.Final` was released.
=> Post-steps for release : 6.6.19.Final

hibernate-core/src/main/java/org/hibernate/metamodel/internal/AttributeFactory.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/identifier/composite/CompositeInheritanceFailTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/identifier/composite/CompositeInheritanceWorkingTest.java
https://hibernate.atlassian.net/browse/HHH-19076
=> HHH-19076 Resolve member of MappedSuperclass specially

ci/build.sh
=> Fix MariaDB nightly support in build.sh

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDirtyCheckEventListener.java, hibernate-core/src/test/java/org/hibernate/orm/test/IsDirtyImmutableTest.java
https://hibernate.atlassian.net/browse/HHH-19604
=> HHH-19604 fix Session.isDirty() with @Immutable entity (7.0)

hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/JdbcBatchLogging.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/BatchBuilderImpl.java
=> log that JDBC batching is enabled at startup

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelation.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/subquery/AttributeJoinOnCorrelatedOrderedJoinTest.java
https://hibernate.atlassian.net/browse/HHH-19550
=> [7.0] HHH-19550 Attribute join on correlated from node receives wrong root

hibernate-platform/hibernate-platform.gradle
https://hibernate.atlassian.net/browse/HHH-19622
=> HHH-19622 Include hibernate-vector in the platform pom

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2iLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2iDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/DB2SubstringFunction.java
https://hibernate.atlassian.net/browse/HHH-19621
=> [7.0] HHH-19621 Don't render code units for DB2 for i

hibernate-testing/src/main/java/org/hibernate/testing/bytecode/enhancement/extension/engine/BytecodeEnhancedTestEngine.java, settings.gradle
https://hibernate.atlassian.net/browse/HHH-19516
=> Ensure compatibility with JUnit < 5.13

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2iLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2iDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/DB2SubstringFunction.java
https://hibernate.atlassian.net/browse/HHH-19621
=> [6.6] HHH-19621 Don't render code units for DB2 for i

hibernate-core/src/main/java/org/hibernate/boot/archive/scan/internal/ScannerLogger.java, hibernate-core/src/main/java/org/hibernate/boot/archive/scan/spi/Scanner.java, hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/ScanningCoordinator.java, hibernate-core/src/main/java/org/hibernate/internal/util/cache/InternalCacheFactoryImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/BootLoggingTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/SessionFactoryNamingTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/scanning/ScanningCoordinatorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jdbc/env/LobCreationCheckSkipTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/schemagen/SchemaCreateDropExtraWarningsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/enums/OrdinalEnumTypeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/enums/VarcharEnumTypeTest.java, hibernate-core/src/test/resources/log4j2.properties, hibernate-scan-jandex/src/main/java/org/hibernate/archive/scan/spi/AbstractScannerImpl.java, hibernate-testing/src/main/java/org/hibernate/testing/logger/LogInspectionHelper.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/MessageKeyWatcherImpl.java
=> Scanning logging

docker_db.sh
=> Update MariaDB testing to latest GA release 11.8.2

hibernate-core/src/main/java/org/hibernate/service/internal/SessionFactoryServiceRegistryBuilderImpl.java
https://hibernate.atlassian.net/browse/HHH-19633
=> HHH-19633 Don't override parent provided service with default service

release/release.gradle
And also fix the query to look only for "done" tickets that would include resolved ones and no in-progress.
=> Update to the new JIRA search API (as previous one is getting deprecated)

hibernate-core/src/main/java/org/hibernate/generator/values/internal/GeneratedValuesMappingProducer.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/main/java/org/hibernate/query/results/DomainResultCreationStateImpl.java, hibernate-core/src/main/java/org/hibernate/query/results/ResultSetMappingImpl.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/SqlAstCreationState.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/NativeQueryJoinTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/embeddedid/OneToOneEmbeddedIdTest.java
https://hibernate.atlassian.net/browse/HHH-19524
https://github.com/hibernate/hibernate-orm/pull/10484 backport for 6.6
=> [6.6] HHH-19524 @OnetoOne relationship unnecessary joins in nativeQuery

hibernate-core/src/main/java/org/hibernate/generator/values/internal/GeneratedValuesMappingProducer.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/main/java/org/hibernate/query/results/internal/DomainResultCreationStateImpl.java, hibernate-core/src/main/java/org/hibernate/query/results/internal/ResultSetMappingImpl.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/SqlAstCreationState.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/NativeQueryJoinTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/embeddedid/OneToOneEmbeddedIdTest.java
https://hibernate.atlassian.net/browse/HHH-19524
https://github.com/hibernate/hibernate-orm/pull/10484 backport for 7.0
=> [7.0] HHH-19524 @OnetoOne relationship unnecessary joins in nativeQuery

hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/lob/LargeObjectMappingTest.java
https://hibernate.atlassian.net/browse/HHH-16253
Backport of https://github.com/hibernate/hibernate-orm/pull/10593
=> [7.0] HHH-16253 - Schema Validation Failure With Audited (N)Clob Column

settings.gradle
https://hibernate.atlassian.net/browse/HHH-19654
=> [7.0] HHH-19654 Upgrade hibernate-models to 1.0.1

gradle/wrapper/gradle-wrapper.properties
=> Upgrade Gradle to 8.14.3

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MariaDBLegacySqlAstTranslator.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacySqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/sql/ast/MariaDBSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/sql/ast/MySQLSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/CriteriaUpdateAndDeleteWithJoinTest.java
https://hibernate.atlassian.net/browse/HHH-19579
=> HHH-19579 Criteria update join - Column 'code' in SET is ambiguous

hibernate-core/src/main/java/org/hibernate/dialect/function/array/ArrayAndElementArgumentTypeResolver.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/ArrayToStringFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/H2ArrayToStringFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/HSQLArrayToStringFunction.java, hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayToStringWithArrayAggregateTest.java
https://hibernate.atlassian.net/browse/HHH-18981
=> HHH-18981 IndexOutOfBoundsException when using arrayToString with arrayAgg

hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/ResultSetMappingProcessor.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/SQLQueryParser.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/javatime/GlobalJavaTimeJdbcTypeTests.java
=> improve error messages in SQLQueryParser

hibernate-core/src/main/java/org/hibernate/dialect/function/array/JsonArrayViaElementArgumentReturnTypeResolver.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/OracleArrayAggEmulation.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/OracleArrayToStringFunction.java, hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayAggregateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayToStringWithArrayAggregateTest.java
https://hibernate.atlassian.net/browse/HHH-19666
=> HHH-19666 Oracle error for array_agg with element type not appearing as array in domain model

release/release.gradle
because that new API only returns the fields you request from it .... 
=> Include `fixVersions` field in the search request to JIRA API

hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/NonAggregatedIdentifierMappingInitializer.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/CompositeIdRepeatedQueryTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/IdClassRepeatedQueryTest.java
https://hibernate.atlassian.net/browse/HHH-19031
backport of https://github.com/hibernate/hibernate-orm/pull/10504 to 6.6
=> HHH-19031 Loading an Entity a second time when it contains an embedded object causes IllegalArgumentException

hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorBinder.java
=> tiny fix to error message

hibernate-core/src/main/java/org/hibernate/boot/beanvalidation/HibernateTraversableResolver.java
https://hibernate.atlassian.net/browse/HHH-19696
=> HHH-19696 Do not iterate over validated path in the TraversableResolver unless necessary

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2iLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2iDialect.java
https://hibernate.atlassian.net/browse/HHH-19453
=> HHH-19453 Fix sequence information extraction on DB2 for i

hibernate-core/src/main/java/org/hibernate/type/format/StringJsonDocumentWriter.java
https://hibernate.atlassian.net/browse/HHH-19699
=> HHH-19699 String JSON document writer code only runs with assertions

hibernate-core/src/main/java/org/hibernate/dialect/sequence/SequenceSupport.java
https://hibernate.atlassian.net/browse/HHH-19701
=> HHH-19701 add 'if exists' to 'drop sequence' on Maria

hibernate-core/src/main/java/org/hibernate/dialect/sequence/MariaDBSequenceSupport.java, hibernate-core/src/main/java/org/hibernate/dialect/sequence/SequenceSupport.java
https://hibernate.atlassian.net/browse/HHH-19701
=> HHH-19701 redo

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/NativeQueryResultBuilderColumnDeduplicationTest.java
https://hibernate.atlassian.net/browse/HHH-19712
=> [6.6] HHH-19712 Column deduplication leads to wrong alias calculation for native query alias expansion

hibernate-core/src/test/java/org/hibernate/orm/test/locking/options/LockedRowsTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/typeoverride/TypeOverrideTest.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFilterExtension.java
=> Ci fixes 7.1

hibernate-platform/hibernate-platform.gradle
https://hibernate.atlassian.net/browse/HHH-19721
=> HHH-19721 Jakarta Data is missing from hibernate-platform (BOM)

.github/hibernate-github-bot.yml
See https://lists.jboss.org/archives/list/hibernate-dev@lists.jboss.org/thread/BJ7OTXCGST6U7XB2TEY54SBA3ZMAS4ZE/
And hopefully for the last time, here's the thing:
=> Skip license agreement for people who agreed explicitly for all contributions

hibernate-core/src/main/java/org/hibernate/annotations/Filter.java
=> fix @Filter javadoc

hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/MutatingTableReferenceGroupWrapper.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/mutationquery/MutationQueriesCollectionTableTest.java
https://hibernate.atlassian.net/browse/HHH-19740
=> HHH-19740 Delegate table related resolving to mutating table reference

documentation/src/main/asciidoc/repositories/Configuration.adoc, documentation/src/main/asciidoc/repositories/Repositories.adoc
https://hibernate.atlassian.net/browse/HHH-19734
https://hibernate.atlassian.net/browse/HHH-19740
=> fix some defects in repositories doc

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/embeddable/EmbeddableInheritanceRecursiveTest.java
https://hibernate.atlassian.net/browse/HHH-19648
Backport of https://github.com/hibernate/hibernate-orm/pull/10748
=> [7.1] HHH-19648 Recursive @Embeddable mapping leads to stack overflow

hibernate-core/src/main/java/org/hibernate/annotations/Filter.java
=> add a code example of @Filter applied to a one-to-many

hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/delegate/MutationDelegateIdentityTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/delegate/MutationDelegateJoinedInheritanceTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/delegate/MutationDelegateTest.java
=> Fix MutationDelegateTest insert and update query assertions

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/HANALegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HANADialect.java, hibernate-core/src/main/java/org/hibernate/dialect/lock/internal/HANALockingSupport.java, hibernate-core/src/main/java/org/hibernate/sql/ast/internal/StandardLockingClauseStrategy.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/unit/locktimeout/HANALockTimeoutTest.java
=> [7.1] Fix lock handling for HANA

hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/main/java/org/hibernate/persister/internal/PersisterClassResolverInitiator.java, hibernate-core/src/main/java/org/hibernate/persister/internal/PersisterFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/persister/internal/PersisterFactoryInitiator.java
=> very minor aesthetic improvements to SessionXxxImpl

hibernate-core/src/main/java/org/hibernate/query/hql/internal/QualifiedJoinPredicatePathConsumer.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQuerySpec.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSubQuery.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/SubQueryShadowingTest.java
https://hibernate.atlassian.net/browse/HHH-19745
=> HHH-19745 Use identity sensitive collections/operations where necessary after introducing equals implementation for SqmPath

hibernate-core/src/main/java/org/hibernate/dialect/function/array/ArrayAndElementArgumentValidator.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/TypecheckUtil.java, hibernate-core/src/main/java/org/hibernate/type/BasicTypeRegistry.java
Was #10876.
https://hibernate.atlassian.net/browse/HHH-19276
=> HHH-19276 fix memory leak with enum list parameter

hibernate-core/src/main/java/org/hibernate/SessionBuilder.java, hibernate-core/src/main/java/org/hibernate/SharedSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/engine/creation/internal/SessionBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/creation/internal/SharedSessionBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/creation/spi/SessionBuilderImplementor.java, hibernate-core/src/main/java/org/hibernate/engine/creation/spi/SharedSessionBuilderImplementor.java, hibernate-core/src/main/java/org/hibernate/engine/spi/AbstractDelegatingSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/engine/spi/AbstractDelegatingSharedSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/engine/spi/LoadQueryInfluencers.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java
the machinery was already there
=> expose two additional useful settings via SessionBuilder

hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/internal/PatternRenderer.java
https://hibernate.atlassian.net/browse/HHH-19795
=> HHH-19795 better error message for an illegal use of ? in a pattern

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
https://hibernate.atlassian.net/browse/HHH-19784
=> HHH-19784 Avoid using package-private field access with bytecode enhanced entity hierarchy

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractCriteriaMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaDeleteMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaFinderMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/QueryMethod.java
https://hibernate.atlassian.net/browse/HHH-19713
Backport of https://github.com/hibernate/hibernate-orm/pull/10993
=> HHH-19713 Store JD repository query in local variable for reuse

hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, local-build-plugins/src/main/java/org/hibernate/orm/post/LoggingReportTask.java
https://hibernate.atlassian.net/browse/HHH-19806
=> HHH-19806 Make LoggingReportTask more resilient to missing annotation values

hibernate-core/src/main/java/org/hibernate/stat/internal/CacheRegionStatisticsImpl.java
=> avoid unnecessarily holding onto Region in CacheRegionStatisticsImpl

hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/JdbcMapping.java, hibernate-core/src/main/java/org/hibernate/query/results/internal/complete/CompleteResultBuilderBasicValuedConverted.java, hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/JdbcLiteral.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/AbstractJdbcOperationQuery.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcOperationQuerySelect.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/basic/BasicResult.java
=> don't use a raw type in JdbcMapping

release/release.gradle
and fix the query to look only for "done" tickets that would include resolved ones and no in-progress
(cherry picked from commit 007d2f190e6219d972f73dd95d5ba2d42e777ecc)
=> [6.6] Update to the new JIRA search API (as previous one is getting deprecated)

release/release.gradle
https://hibernate.atlassian.net/browse/HHH-19388
backport for 5.3
https://hibernate.atlassian.net/browse/HHH-19800
=> HHH-19800 Migrate to release scripts for documentation publishing

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/EnhancementAsProxyLazinessInterceptor.java, hibernate-core/src/main/java/org/hibernate/bytecode/internal/BytecodeEnhancementMetadataPojoImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/AbstractEntityInstantiatorPojo.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/EntityRepresentationStrategyPojoStandard.java, hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java
Changes needed to fix https://github.com/hibernate/hibernate-reactive/issues/1770
see https://github.com/hibernate/hibernate-reactive/pull/2513
https://hibernate.atlassian.net/browse/HHH-19825
=> Add methods and change method access for Hibernate Reactive

local-build-plugins/src/main/groovy/local.java-module.gradle
https://hibernate.atlassian.net/browse/HHH-19767
=> HHH-19767 Include license file in the META-INF of published artifacts

hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/id/AbstractCompositeIdMapper.java, hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/id/EmbeddedIdMapper.java, hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/id/MultipleIdMapper.java, hibernate-envers/src/test/java/org/hibernate/envers/test/integration/query/ids/RecordIdRelatedIdQueryTest.java
https://hibernate.atlassian.net/browse/HHH-19393
Backport of https://github.com/hibernate/hibernate-orm/pull/11065
=> [7.1] HHH-19393 Hibernate Envers can not handle ID class if it is implemented as Java record

changelog.txt
=> Update the changelog to match the released JIRAs

tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
=> Add a publish plugin task dependency to releasePerform
