docker_db.sh, gradle/databases.gradle, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/entity/Forest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/uniqueconstraint/UniqueConstraintTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/HQLTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/array/PrimitiveByteArrayIdTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/uuid/sqlrep/sqlbinary/UUIDBinaryTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/InheritanceQueryGroupByTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/QueryBuilderTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/length/LengthTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/always/GeneratedAlwaysTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/CteTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/QueryTimeOutTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/LiteralTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/SchemaMigratorHaltOnErrorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/SchemaUpdateHaltOnErrorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/UUIDTypeConverterTest.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java
Fixes for some of the Informix tests
=> Informix tests fixes

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2LegacyDialect.java, hibernate-core/src/main/java/org/hibernate/id/IdentityGenerator.java
https://hibernate.atlassian.net/browse/HHH-18642
=> HHH-18642 DB2: select from new table with identity column not working when missing read permission

hibernate-core/src/main/java/org/hibernate/id/uuid/UuidVersion6Strategy.java
Fix NPE for private static final field
https://hibernate.atlassian.net/browse/HHH-18377
=> HHH-18377 - Support for uuid v6 and v7 generated ids

tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockCollectionPersister.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockEntityPersister.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/ProcessorSessionFactory.java
https://hibernate.atlassian.net/browse/HHH-18667
=> HHH-18667 attempt to fix by making TypeConfiguration nonstatic

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/detached/RemoveDetachedInstanceTest.java
https://hibernate.atlassian.net/browse/HHH-18631
=> HHH-18631 AssertionError when loading an entity after removing another, associated entity

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/CompoundNaturalIdMapping.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/naturalid/ByteArrayNaturalIdTest.java
https://hibernate.atlassian.net/browse/HHH-18409 
=> HHH-18409 byte[] instance variables annotated with @NaturalId cannot be found with a natural ID query

.gitignore, .idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, .idea/inspectionProfiles/Project_Default.xml
This only includes:
- coding conventions, and
- configuration of warnings.
=> try adding minimal IntelliJ project config

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/instantiation/internal/DynamicInstantiationResultImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/instantiation/internal/InstantiationHelper.java, hibernate-core/src/main/java/org/hibernate/sql/results/internal/RowTransformerConstructorImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/instantiation/DynamicInstantiationConstructorMatchingTest.java
https://hibernate.atlassian.net/browse/HHH-18664
=> HHH-18664 Allow primitive-type parameters in constructors used to build query result types

hibernate-core/src/main/java/org/hibernate/dialect/OracleSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/OracleArrayContainsFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/OracleArrayIncludesFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/OracleArrayIntersectsFunction.java
https://hibernate.atlassian.net/browse/HHH-18587
Implement the functions `array_contains`, `array_includes` and `array_intersects` using set operations on Oracle. This is done using the [column_value pseudocolumn](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/COLUMN_VALUE-Pseudocolumn.html) and the `TABLE` function. Similar to this
```sql
SELECT *
FROM entity
WHERE needle IN (SELECT column_value FROM TABLE(?))
```
With Oracle 23 we could also use
```sql
SELECT *
FROM entity
WHERE needle = ANY (SELECT column_value FROM TABLE(?))
```
But this wouldn't work in Oracle 19.
The `_nullable` variants keep calling the stored procedures. …
=> HHH-18587 Implement Oracle array functions using set operations

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/batch/RefreshAndBatchTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/batch/RefreshAndBatchTest2.java
https://hibernate.atlassian.net/browse/HHH-18608
=> HHH-18608 NPE in EntityInitializerImpl.resolveInstanceSubInitializers

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java, hibernate-core/src/test/java/org/hibernate/bytecode/internal/bytebuddy/GenerateProxiesTest.java, hibernate-core/src/test/java/org/hibernate/bytecode/internal/bytebuddy/MappedSuperclassEntity.java, hibernate-core/src/test/java/org/hibernate/bytecode/internal/bytebuddy/mappedsuperclass/BaseMappedSuperclass.java
https://hibernate.atlassian.net/browse/HHH-16772
https://issues.redhat.com/browse/JBEAP-28131
Backport of https://github.com/hibernate/hibernate-orm/pull/6756
=> [HHH-16772][JBEAP-28131] Generated bytecode for HibernateAccessOptimizer class is invalid and causes operand stack overflow issue

hibernate-core/src/main/java/org/hibernate/mapping/Property.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java, hibernate-core/src/test/java/org/hibernate/orm/test/manytomany/generic/ManyToManyGenericTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/manytomany/generic/ManyToManyNonGenericTest.java
Hibernate should not map synthetic properties. However by copying the synthetic property the synthetic aspect is not copied. To circumvent this create a SyntheticProperty on copying. And ignore the property in the jpa-model.
https://hibernate.atlassian.net/browse/HHH-18675
=> HHH-18675. Ignore generic, synthetic property in JPA-model

documentation/src/main/asciidoc/quickstart/guides/obtaining.adoc
[Simple documentation fix]
Trivial doc fix to add the missing xml anchor to import the hibernate BOM.
Thanks
=> Documentation fix for Maven BOM import instructions

local-build-plugins/src/main/java/org/hibernate/orm/jakarta/JakartaPublishingPlugin.java
1. fix `Note: Recompile with -Xlint:unchecked for details.`
2. return value of method `addVariant` is not used.
3. refine lambda.
4. remove unused import.
=> Polishing JakartaPublishingPlugin

tooling/metamodel-generator/src/main/java/org/hibernate/processor/ClassWriter.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMeta.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaPackage.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/NameMetaAttribute.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/model/Metamodel.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/xml/XmlMetaEntity.java
=> two small improvements to HibernateProcessor

tooling/metamodel-generator/src/main/java/org/hibernate/processor/ClassWriter.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/ImportContextImpl.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractFinderMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaAttribute.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaMap.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaType.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/DataAnnotationMetaAttribute.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/QueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/TypedMetaAttribute.java
=> more improvements to generated Javadoc in Hibernate Processor

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappingMetamodelImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/CoalesceTest.java
https://hibernate.atlassian.net/browse/HHH-18321
Alternative solution to https://github.com/hibernate/hibernate-orm/pull/8730
=> HHH-18321 SqlTreeCreationException when using sum/diff with coalesce on properties of embeddable component

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
StatelessSession does not have a byNaturalId() method
=> fix a bug in generation of @Find method for @NaturalId fields

hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/JdbcBatchLogging.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/BatchImpl.java
https://hibernate.atlassian.net/browse/HHH-13547
=> HHH-13547 - remove logging of BatchImpl rethrown exceptions

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/AbstractBatchEntitySelectFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntitySelectFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/batch/BatchLazyProxyTest.java
https://hibernate.atlassian.net/browse/HHH-18645
=> HHH-18645 Handle proxies when resolving from existing entity in batch initializer

hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaIsolationDelegate.java
This PR avoid calling  `transactionManager.resume()` in `JtaIsolationDelegate.doInSuspendedTransaction` when no surrounding transaction exists. It fixes an unpleasant warning in Atomikos' transaction manager.
https://hibernate.atlassian.net/browse/HHH-18491
=> HHH-18491 Do no try to resume non-existant transaction in doInSuspendedTransaction.

hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/JdbcBatchLogging.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/BatchImpl.java
https://hibernate.atlassian.net/browse/HHH-13547
=> Backport to 6.6 of HHH-13547 (remove logging of BatchImpl rethrown exceptions)

documentation/src/main/asciidoc/introduction/Advanced.adoc, documentation/src/main/asciidoc/introduction/Configuration.adoc, documentation/src/main/asciidoc/introduction/Entities.adoc, documentation/src/main/asciidoc/introduction/Generator.adoc, documentation/src/main/asciidoc/introduction/Interacting.adoc, documentation/src/main/asciidoc/introduction/Introduction.adoc, documentation/src/main/asciidoc/introduction/Mapping.adoc, documentation/src/main/asciidoc/introduction/Tuning.adoc
https://hibernate.atlassian.net/browse/HHH-18588
Fixed some minor defects.
=> HHH-18588 fix minor defects in Hibernate Introduction article

hibernate-testing/src/main/java/org/hibernate/testing/orm/domain/gambit/Shirt.java
- Optimized convertToEntityAttribute method by removing redundant Integer.valueOf() call.
- The dbData parameter is already an Integer, making this conversion unnecessary.
This is my first contribution to this project. Please let me know if there's anything I need to improve or if you need any additional information. I'm open to feedback and eager to learn. Thank you.
For more information on …
=> remove unnecessary Integer.valueOf() in ShirtStringToIntegerConverter

local-build-plugins/src/main/java/org/hibernate/orm/jakarta/JakartaPublishingPlugin.java
Note: hibernate-orm/local-build-plugins/src/main/java/org/hibernate/orm/jakarta/JakartaPublishingPlugin.java uses unchecked or unsafe operations.
=> Fix "uses unchecked or unsafe operations"

hibernate-agroal/src/main/java/org/hibernate/agroal/internal/AgroalConnectionProvider.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java, hibernate-hikaricp/src/main/java/org/hibernate/hikaricp/internal/HikariCPConnectionProvider.java, hibernate-vibur/src/main/java/org/hibernate/vibur/internal/ViburDBCPConnectionProvider.java
Resolve the driver name from the connection metadata, in case it wasn't explicitly set and access to the database metadata is allowed
https://hibernate.atlassian.net/browse/HHH-18669
=> HHH-18669 - Fix NPE

hibernate-agroal/src/main/java/org/hibernate/agroal/internal/AgroalConnectionProvider.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java, hibernate-hikaricp/src/main/java/org/hibernate/hikaricp/internal/HikariCPConnectionProvider.java, hibernate-vibur/src/main/java/org/hibernate/vibur/internal/ViburDBCPConnectionProvider.java
https://hibernate.atlassian.net/browse/HHH-18669
=> HHH-18669 - resolve the driver name from the connection metadata, in case it wasn't explicitly set and access to the database metadata is allowed

hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/SubQuerySelectCaseWhenTest.java
https://hibernate.atlassian.net/browse/HHH-18681
=> HHH-18681 InterpretationException executing subquery in case-when : o.h.query.sqm.tree.select.SqmSelection.getExpressible() is null

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java, hibernate-core/src/main/java/org/hibernate/event/spi/MergeContext.java, hibernate-core/src/main/java/org/hibernate/internal/util/EntityPrinter.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/PersistenceUnitUtilImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityIdentifierMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/InverseNonAggregatedIdentifierMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/NonAggregatedIdentifierMappingImpl.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java, hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleBasicEntityIdentifierMapping.java, hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleEmbeddedEntityIdentifierMapping.java, hibernate-core/src/main/java/org/hibernate/query/derived/AnonymousTupleNonAggregatedEntityIdentifierMapping.java, hibernate-core/src/main/java/org/hibernate/type/AnyType.java, hibernate-core/src/main/java/org/hibernate/type/EntityType.java, hibernate-core/src/test/java/org/hibernate/engine/internal/StatisticalLoggingSessionEventListenerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/cid/CompositeIdAndMergeTest.java
https://hibernate.atlassian.net/browse/HHH-18131
https://github.com/hibernate/hibernate-orm/pull/9013 backport to 6.6
=> HHH-18131 Composite identifiers with associations stopped working with @IdClass`

documentation/src/main/asciidoc/introduction/Advanced.adoc, documentation/src/main/asciidoc/userguide/chapters/multitenancy/MultiTenancy.adoc, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/ConnectionProviderInitiator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/MultiTenantConnectionProviderInitiator.java, hibernate-core/src/test/java/org/hibernate/orm/test/connections/ConnectionProviderFromBeanContainerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/UserDefinedGeneratorsTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/multitenancy/AbstractMultiTenancyTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/multitenancy/beancontainer/AbstractTenantResolverBeanContainerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/multitenancy/beancontainer/MultiTenantConnectionProviderFromBeanContainerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/multitenancy/beancontainer/MultiTenantConnectionProviderFromSettingsOverBeanContainerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/multitenancy/beancontainer/TenantResolverFromBeanContainerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/multitenancy/beancontainer/TenantResolverFromSettingsOverBeanContainerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/multitenancy/beancontainer/TestBeanContainer.java, hibernate-core/src/test/java/org/hibernate/orm/test/multitenancy/beancontainer/TestCurrentTenantIdentifierResolver.java, hibernate-core/src/test/java/org/hibernate/orm/test/multitenancy/beancontainer/TestEntity.java
https://hibernate.atlassian.net/browse/HHH-15422
=> HHH-15422 Pick up `CurrentTenantIdentifierResolver` and `MultiTenantConnectionProvider` from BeanContainer if not explicit set

hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/SessionFactory.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionImplementor.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/util/LockModeConverter.java
It was always weird and inconsistent that you sometimes had to use get(), and this is also better documented this way (i.e. Hibernate-specific semantics of find() are not documented by EntityManager)
Also add some missing @Overload annotations
Also move some impl down off the interface
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/C …
=> HHH-18748 Add missing overloads of find() to Session

docker_db.sh
Default CockroachDB version is now 24.1.5.
Removed the CockroachDB 22.2 release as that is now EOL.
https://hibernate.atlassian.net/browse/HHH-18747
=> HHH-18747 - Update CockroachDB Docker configuration.

hibernate-core/src/main/java/org/hibernate/generator/internal/GeneratedGeneration.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/InsertCoordinatorStandard.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/GeneratedWritableIdTest.java
https://hibernate.atlassian.net/browse/HHH-18679
=> HHH-18679 Allow @Generated(writeble=true) on id properties to use assigned identifiers

hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/merge/MergeTest.java
Test to show `merge` doesn't suffer of https://hibernate.atlassian.net/browse/HHH-18713 abd
https://hibernate.atlassian.net/browse/HHH-18614.
`update` and `saveOrUpdate` have been removed from Hibernate 7
=> HHH-18713 HHH-18614 Add test to show issue does not persist with merge

hibernate-core/src/main/java/org/hibernate/Session.java
This method is essentially redundant as things stand today, and I want to open up the possibility of changing its semantics in the future.
https://hibernate.atlassian.net/browse/HHH-18749
=> HHH-18749 deprecate Session.get()

hibernate-core/src/main/java/org/hibernate/type/EntityType.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/derivedidentities/OneToManyEmbeddableId.java
https://hibernate.atlassian.net/browse/HHH-18702
=> HHH-18702 Exception using @EmbeddedId with @OneToMany that refers to an alternate key column

hibernate-core/src/main/java/org/hibernate/SessionFactory.java, hibernate-core/src/main/java/org/hibernate/SharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/InsertCoordinatorStandard.java
=> remove two default impls that threw UnsupportedOperationException

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQueryGroup.java, hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesMappingProducerProviderStandard.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/UnionAllSelectNullTest.java
https://hibernate.atlassian.net/browse/HHH-18720
https://github.com/hibernate/hibernate-orm/pull/9094 backport to 6.6
=> HHH-18720 Type check on select columns in union all gives SemanticException when there is a null column

hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/spi/EntityHolder.java, hibernate-core/src/main/java/org/hibernate/engine/spi/PersistenceContext.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultEvictEventListener.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/DetachedPreviousRowStateTest.java
https://hibernate.atlassian.net/browse/HHH-18719
https://github.com/hibernate/hibernate-orm/pull/9102 backport to 6.6
=> HHH-18719 Previous row state reuse can provide detaches entities to the consumer

hibernate-core/src/main/java/org/hibernate/SharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/StatelessSession.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/main/java/org/hibernate/resource/jdbc/spi/JdbcSessionOwner.java, migration-guide.adoc
1. ignore `hibernate.jdbc.batch_size setting`
2. add `insertMultiple()` and friends
https://hibernate.atlassian.net/browse/HHH-18743
=> HHH-18743 make batching explicit for StatelessSession

hibernate-core/src/main/java/org/hibernate/annotations/AnyDiscriminator.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnyBinder.java, hibernate-core/src/main/java/org/hibernate/boot/models/annotations/internal/AnyDiscriminatorAnnotation.java, hibernate-core/src/main/java/org/hibernate/mapping/Any.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/DiscriminatorConverter.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EmbeddableDiscriminatorConverter.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ExplicitDiscriminatorConverter.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ImplicitDiscriminatorConverter.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MixedDiscriminatorConverter.java, hibernate-core/src/main/java/org/hibernate/type/AnyDiscriminatorValueStrategy.java, hibernate-core/src/test/java/org/hibernate/orm/test/any/mixed/AnyDiscriminatorValueHandlingTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/any/mixed/AnyDiscriminatorValueStrategyTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/any/mixed/CardPayment.java, hibernate-core/src/test/java/org/hibernate/orm/test/any/mixed/CashPayment.java, hibernate-core/src/test/java/org/hibernate/orm/test/any/mixed/CheckPayment.java, hibernate-core/src/test/java/org/hibernate/orm/test/any/mixed/Order.java, hibernate-core/src/test/java/org/hibernate/orm/test/any/mixed/Payment.java
https://hibernate.atlassian.net/browse/HHH-18728
=> HHH-18728 - Allow mixed discriminator-value mappings for ANY

documentation/src/main/asciidoc/introduction/Configuration.adoc, documentation/src/main/asciidoc/introduction/Entities.adoc, documentation/src/main/asciidoc/introduction/Hibernate_Introduction.adoc, documentation/src/main/asciidoc/introduction/Introduction.adoc, documentation/src/main/asciidoc/introduction/Mapping.adoc, documentation/src/main/asciidoc/introduction/Preface.adoc, documentation/src/main/asciidoc/shared/url-attributes.adoc, hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java, hibernate-core/src/main/java/org/hibernate/jpa/HibernatePersistenceConfiguration.java
=> documentation updates for H7

documentation/src/main/asciidoc/introduction/Hibernate_Introduction.adoc, documentation/src/main/asciidoc/introduction/Introduction.adoc, documentation/src/main/asciidoc/introduction/Preface.adoc
=> updates to doc for H7

hibernate-core/src/test/java/org/hibernate/orm/test/collection/multisession/MultipleSessionCollectionTest.java
On CockroachDB the method
`testCopyPersistentCollectionReferenceAfterFlush` causes a deadlock, which is resolved eventually by a TimeoutException.
This problem has been discussed in
https://github.com/cockroachdb/cockroach/issues/61269. The CockroachDB developers do not see this as a bug that needs to be fixed. Therefore we skip this test for CockroachDB. …
=> HHH-18755 - Skip test that causes deadlock

hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/LongVarbinaryJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/LongVarcharJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/internal/JdbcTypeBaseline.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/LongNullTest.java
Jira issue [HHH-18446](https://hibernate.atlassian.net/browse/HHH-18446)
Fixing problem by adding (configurable) default SQL type code to LongVarbinaryJdbcType abd LongVarcharJdbcType
[HHH-18446]: https://hibernate.atlassian.net/browse/HHH-18446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …
=> HHH-18446 Cannot use @JdbcTypeCode(SqlTypes.LONG32VARBINARY) on field with null value

.github/workflows/ci-report.yml, .github/workflows/ci.yml
Ripped off from Quarkus
Here's how it will work:
1. We create a cache entry on push only. Pull requests only restore it.
2. We create a new cache entry every day, prefixed with something like
2024-10-25.
3. When restoring the cache, we try the entry for the day first
(2024-10-25) and default to the one for the month (2024-10-*).
Critically, this means we will build each day's cache based on the
previous day's cache.
4. Atlas infra uses its own, separate cache entries.
Opening as draft, because this is based on #9163, which must be merged first. …
=> Improve build cache strategy

.github/workflows/ci-report.yml, .github/workflows/ci.yml
We don't need the whole cache, since most (all?) of it is stored on Develocity already.
Including ./gradle/caches/modules-2 is enough, because that's where Maven dependencies are stored, and *those* are not stored on Develocity.
=> Do not include the whole Gradle cache in GH Actions caches

hibernate-core/src/main/java/org/hibernate/id/enhanced/TableGenerator.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/TableStructure.java, hibernate-core/src/main/java/org/hibernate/resource/jdbc/spi/JdbcEventHandler.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/StatelessSessionStatisticsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/stats/StatisticsWithNoCachingTest.java
https://hibernate.atlassian.net/browse/HHH-17989
=> HHH-17989 - Fix for StatisticsImplementor.closeStatement() never called

hibernate-core/src/main/java/org/hibernate/BatchSize.java, hibernate-core/src/main/java/org/hibernate/MultiIdentifierLoadAccess.java, hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/exception/AuthException.java, hibernate-core/src/main/java/org/hibernate/exception/DataException.java, hibernate-core/src/main/java/org/hibernate/exception/internal/SQLStateConversionDelegate.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/util/JdbcExceptionHelper.java, hibernate-core/src/main/java/org/hibernate/internal/util/collections/CollectionHelper.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractMultiIdEntityLoader.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderArrayParam.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderStandard.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
1. Add `BatchSize`, a `FindOption` synonymous with `MultiIdLoadAccess.withBatchSize()`.
3. Make `MultiIdEntityLoaderArrayParam` respect explicit batch sizes.
https://hibernate.atlassian.net/browse/HHH-18767 …
=> HHH-18767, HHH-18772 add BatchSize for use with findMultiple()

.github/workflows/ci-report.yml, .github/workflows/ci.yml
Don't tar them, as this was broken: we ended up uploading the build-scan-data directory instead of the tar, while still expecting a tar when dowloading, which made everything fail.
We don't need tars anyway, as workflow artifacts are already zipped.
=> Fix upload of Develocity build scans

hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesMappingResolutionImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/SelectJoinedAssociationMultipleTimesTest.java
https://hibernate.atlassian.net/browse/HHH-18773
=> HHH-18773 Deduplicate result initializers to avoid double initialization issues

hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
https://hibernate.atlassian.net/browse/HHH-18777
=> HHH-18777 Performance optimization for entities-by-key hashmap access

hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java, hibernate-core/src/main/java/org/hibernate/exception/TransactionSerializationException.java, hibernate-core/src/main/java/org/hibernate/internal/ExceptionConverterImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchUpdateAndVersionTest.java
This is a proposal to fix the Failing unit test in `BatchUpdateAndVersionTest` on CockroachDB.
https://hibernate.atlassian.net/browse/HHH-18760
=> HHH-18760 - CockroachDB dialect remaps serialization error

hibernate-core/src/main/java/org/hibernate/type/ManyToOneType.java, hibernate-core/src/test/java/org/hibernate/orm/test/associations/ManyToOneUniqueKeyReferenceWithCustomIdTest.java
This pull request addresses a bug in the `isDirty` method when dealing with ManyToOne associations that are referenced by a unique key instead of a primary key, particularly when the primary key is a custom type.
This bug stems from a mismatch in how `isDirty` checks for changes: while it correctly retrieves the unique key value using `getIdentifier`, it incorrectly relies on `getIdentifierType`, which only considers the primary key type. This results in unexpected behavior—in this case, a `ClassCastException` when attempting to call the custom ID type's equals method.
The fix replaces `getIdentifierType` with `getIdentifierOrUniqueKeyType`, ensuring that `isDirty` correctly accounts for both primary keys and unique keys. This issue is demonstrated in the unit test …
=> HHH-18764 Fix incorrect type resolution in ManyToOneType dirty check

.github/ci-prerequisites-atlas.sh, .github/workflows/atlas.yml, .github/workflows/contributor-build.yml, ci/release/Jenkinsfile, ci/snapshot-publish.Jenkinsfile, gradle/gradle-enterprise.gradle, settings.gradle
Similar to #9176 , but more conservative as we didn't publish build scan from GitHub Actions in this branch.
This is a backport of #9163 (limited to two commits) #9165 #9166.
=> Backport CI improvements from main to 6.4 (partially)

.github/ci-prerequisites-atlas.sh, .github/workflows/atlas.yml, .github/workflows/contributor-build.yml, ci/release/Jenkinsfile, gradle/gradle-enterprise.gradle, settings.gradle
Similar to #9176 , but more conservative as we didn't publish build scan from GitHub Actions in this branch. Almost identical to #9177.
This is a backport of #9163 (limited to two commits) #9165 #9166.
=> Backport CI improvements from main to 6.2 (partially)

hibernate-core/src/main/java/org/hibernate/dialect/MariaDBSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
Based on #9194.
@cigaly WDYT?
https://hibernate.atlassian.net/browse/HHH-18783
=> HHH-18783 cast(x as Character) on MySQL and Maria

hibernate-core/src/main/java/org/hibernate/annotations/Formula.java, hibernate-core/src/main/java/org/hibernate/annotations/Generated.java, hibernate-core/src/main/java/org/hibernate/generator/values/internal/GeneratedValuesHelper.java, hibernate-core/src/main/java/org/hibernate/id/insert/InsertReturningDelegate.java, hibernate-core/src/main/java/org/hibernate/id/insert/SybaseJConnGetGeneratedKeysDelegate.java, hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java, hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/ColumnReference.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/formula/FormulaGeneratedTest.java
https://hibernate.atlassian.net/browse/HHH-18809
=> HHH-18809 @Formula @Generated

hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/aggregate/H2AggregateSupport.java, hibernate-core/src/main/java/org/hibernate/dialect/function/json/H2JsonQueryFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/json/H2JsonTableFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/json/H2JsonValueFunction.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/EnumJdbcType.java
https://hibernate.atlassian.net/browse/HHH-18792
=> HHH-18792 Add JSON aggregate support for H2

hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4, hibernate-core/src/main/java/org/hibernate/query/hql/internal/HqlParseTreeBuilder.java
https://hibernate.atlassian.net/browse/HHH-18808
Not sure why not move the keyword list into HqlLexer.g4, which would simplify a lot and I think we could still overwrite HqlLexer class. But here is a quick and effective bug fix.
=> HHH-18808 Fix the bug of wrong logging output when keyword is used as identifier in HqlParser.g4

hibernate-jfr/src/main/java/org/hibernate/event/jfr/internal/JfrEventManager.java, hibernate-jfr/src/test/java/org/hibernate/event/jfr/flush/AutoFlushJfrDisabledTests.java
https://hibernate.atlassian.net/browse/HHH-18770
https://github.com/hibernate/hibernate-orm/pull/9180 backport to 6.6
=> HHH-18770 NPE when using the JFR integration with JFR disabled

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/object/ConvertedClassAttributeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/object/Status.java
https://hibernate.atlassian.net/browse/HHH-18564
=> HHH-18564 Literal expressions using AttributeConverters stopped working in hibernate 6

hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
=> some minor cleanups

hibernate-core/src/main/java/org/hibernate/query/hql/internal/StandardHqlTranslator.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/Validation.java
https://hibernate.atlassian.net/browse/HHH-18754
Below is the code pattern for HQL parsing (at `org.hibernate.query.hql.internal.StandardHqlTranslator`):
```
// Build the lexer
final HqlLexer hqlLexer = HqlParseTreeBuilder.INSTANCE.buildHqlLexer( hql );
// Build the parse tree
final HqlParser hqlParser = HqlParseTreeBuilder.INSTANCE.buildHqlParser( hql, hqlLexer );
ANTLRErrorListener errorListener = new ANTLRErrorListener() {
@Override
public void syntaxError(Recognizer<?, ?> recognizer, Object offendingSymbol, int line, int charPositionInLine, String msg, RecognitionException e) {
throw new SyntaxException( prettifyAntlrError( offendingSymbol, line, charPositionInLine, msg, e, hql, true ), hql );
}
@Override
public void reportAmbiguity(Parser recognizer, DFA dfa, int startIndex, int …
```
=> HHH-18754 Improve HQLParser's error listener usage

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/SqmTranslatorFactory.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/StandardSqmTranslatorFactory.java
confusing naming. seems obvious defect.
=> correct variable naming defects in SqmTranslatorFactory and StandardSqmTranslatorFactory

documentation/src/main/asciidoc/introduction/Advanced.adoc, documentation/src/main/asciidoc/introduction/Configuration.adoc, documentation/src/main/asciidoc/introduction/Entities.adoc, documentation/src/main/asciidoc/introduction/Interacting.adoc, documentation/src/main/asciidoc/introduction/Introduction.adoc
=> proofread the Short Guide

hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java, hibernate-core/src/main/java/org/hibernate/boot/registry/classloading/spi/ClassLoaderService.java, hibernate-core/src/main/java/org/hibernate/engine/internal/UnsavedValueFactory.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java, hibernate-core/src/main/java/org/hibernate/mapping/KeyValue.java, hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java
=> Cleanup to unsaved-value stuff

hibernate-core/src/main/java/org/hibernate/annotations/ListIndexBase.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/internal/util/collections/ArrayHelper.java, hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java, hibernate-core/src/main/java/org/hibernate/persister/collection/OneToManyPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/cfg/persister/GoofyPersisterClassProvider.java, hibernate-core/src/test/java/org/hibernate/orm/test/cid/CompositeIdTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/orderby/Book.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/orderby/OrderByMappedByTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/ordercol/Book.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/ordercol/OrderColumnMappedByTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/tck2_2/mapkeycolumn/MapKeyColumnBiDiOneToManyFKTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ejb3configuration/PersisterClassProviderTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/legacy/CustomPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mappedBy/MappedByCompositeNonAssociationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mappedBy/MappedByNonAssociationTest.java
https://hibernate.atlassian.net/browse/HHH-18830
=> HHH-18830 fix extraneous updates for unowned List with @OrderColumn

documentation/src/main/asciidoc/introduction/Configuration.adoc
=> add section on quoted identifiers to doc

hibernate-core/src/main/java/org/hibernate/tool/schema/internal/ColumnDefinitions.java, migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-18830
=> Two minor things

hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java, hibernate-core/src/test/java/org/hibernate/persister/entity/JoinedSubclassEntityPersisterTest.java
https://hibernate.atlassian.net/browse/HHH-18703
=> HHH-18703 Use natural order table numbers for subclass column closure

hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ListBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/MapBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/NaturalIdBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/main/java/org/hibernate/mapping/Collection.java, hibernate-core/src/main/java/org/hibernate/mapping/IndexedCollection.java, hibernate-core/src/main/java/org/hibernate/mapping/Map.java, hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/mapkey/Book.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/mapkey/MapKeyMappedByTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/mapkeycolumn/Book.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/mapkeycolumn/MapKeyColumnMappedByTest.java
remove ugly workaround for @MapKey/@MapKeyColumn, and add tests
It looks like @beikov had already run into this bug in the context of map keys, and worked around it, not realizing that the problem also affected list indexes. …
=> HHH-18830 remove workaround after fix

documentation/src/main/asciidoc/introduction/Advanced.adoc
=> clarifications in section on collection mapping

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/FakeSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/SqmToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/ExistsSubqueryForeignKeyTest.java
https://hibernate.atlassian.net/browse/HHH-18816
=> HHH-18816 Error when rendering the fk-side of an association in an exists subquery

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaMutationQueryFkValuesTest.java
https://hibernate.atlassian.net/browse/HHH-18647
=> HHH-18647 SemanticException when using createCriteriaInsertValues to insert into foreign key column

hibernate-core/src/main/java/org/hibernate/query/KeyedResultList.java, hibernate-core/src/main/java/org/hibernate/query/Order.java, hibernate-core/src/main/java/org/hibernate/query/Page.java
=> add some javadoc to KeyedResultList, Order, Page

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/ByteBuddyEnhancementContext.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/EnhancementContext.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/UnsupportedEnhancementStrategy.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/access/UnsupportedEnhancementStrategyTest.java
This method allows custom contexts to pick the behavior they want when a class contains getters/setters that do not have a matching field, making enhancement impossible.
Three behaviors are available:
* SKIP (the default), which will skip enhancement of such classes.
* FAIL, which will throw an exception upon encountering such classes.
* LEGACY, which will restore the pre-HHH-16572 behavior.
I do not think LEGACY is useful at the moment, but I wanted to have that option in case it turns out HHH-16572 does more harm than good in Quarkus 3.15. …
=> HHH-18833  Introduce EnhancementContext#getUnsupportedEnhancementStrategy

.gitattributes, .github/hibernate-github-bot.yml, .gitignore, .idea/.gitignore, .release/.gitignore, databases/.gitignore, drivers/.gitignore, hibernate-spatial/.gitignore, hibernate-spatial/.sdkmanrc
Following our discussion here about the current `.gitattributes` messing up checked-in JAR files: https://hibernate.zulipchat.com/#narrow/channel/132094-hibernate-orm-dev/topic/7.2E0.20Beta2.20.2F.206.2E6.2E2/near/481975242
I think this matches @beikov 's original intent more closely, and is safer.
I also noticed a few conflicting/incorrect `.gitignore` files, so I tried to fix what I could... …
=> Fix `.gitattributes` / `.gitignore`

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/access/InvalidPropertyNameTest.java
https://hibernate.atlassian.net/browse/HHH-18832
=> HHH-18832 Bytecode enhancement skipped for entities with "compute-only" @Transient properties

hibernate-core/src/main/java/org/hibernate/NaturalIdLoadAccess.java, hibernate-core/src/main/java/org/hibernate/NaturalIdMultiLoadAccess.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorBinder.java, hibernate-core/src/main/java/org/hibernate/internal/util/collections/CollectionHelper.java, hibernate-core/src/main/java/org/hibernate/loader/internal/NaturalIdLoadAccessImpl.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java, hibernate-core/src/main/java/org/hibernate/query/Query.java, hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/AbstractSqmSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/spi/DelegatingSqmSelectionQueryImplementor.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ejb3configuration/ConfigurationObjectSettingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/jakarta/JakartaSchemaToolingTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/NoDepthTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mutability/attribute/ImmutabilityMapAsBasicTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mutability/attribute/ImmutableMapAsBasicTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mutability/attribute/MutableMapAsBasicTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/mutability/converted/MapConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/where/WhereFragmentTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/LegacyParameterTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/tenantid/TenantIdTest.java, hibernate-testing/src/main/java/org/hibernate/testing/util/ServiceRegistryUtil.java, migration-guide.adoc
=> fix signature of Query.setOrder()

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/idClass/IdClassSyntheticAttributesTest.java
https://hibernate.atlassian.net/browse/HHH-18841
=> HHH-18841 Create `_identifierMapper` as a synthetic attribute

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/idClass/IdClassSyntheticAttributesTest.java
https://hibernate.atlassian.net/browse/HHH-18841
A backport of  https://github.com/hibernate/hibernate-orm/pull/9236 to 6.6
=> Backport of HHH-18841 to 6.6 branch - Create `_identifierMapper` as a synthetic attribute

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmOrderByClause.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQueryPart.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectStatement.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/idClass/IdClassSyntheticAttributesTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CountQueryTests.java
https://hibernate.atlassian.net/browse/HHH-18850
=> HHH-18850 fix count queries with 'distinct' and 'order by'

tooling/metamodel-generator/src/main/java/org/hibernate/processor/Context.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMeta.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/NamedQueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/SqmTypeUtils.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/namedentity/Book.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/namedentity/NamedEntityTest.java
See Jira Issue [HHH-18705](https://hibernate.atlassian.net/browse/HHH-18705)
Problem can be quickly, but ugly, solved by copy & paste (with small adjustments) methods `returnType` and `entityType` from class `org.hibernate.processor.annotation.NamedQueryMethod`.
[HHH-18705]: …
=> HHH 18705 - Hibernate processor creates bad TypedReferenceQuery when @Entity have name attribute

documentation/src/main/asciidoc/querylanguage/Expressions.adoc
=> document the syntax sugar

hibernate-core/src/main/java/org/hibernate/SessionFactory.java, hibernate-core/src/main/java/org/hibernate/cfg/JdbcSettings.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
=> more correct generic type for Consumers

hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
https://hibernate.atlassian.net/browse/HHH-18859
=> HHH-18859 fix error message for slice operator applied to non-string non-array

hibernate-core/src/main/java/org/hibernate/dialect/function/array/ArrayContainsArgumentTypeResolver.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/test/java/org/hibernate/orm/test/function/array/ArrayContainsTest.java
https://hibernate.atlassian.net/browse/HHH-18851
=> HHH-18851 Fix parameter type inference issue when IN predicate is uses array_contains()

tooling/metamodel-generator/src/main/java/org/hibernate/processor/Context.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/TypeUtils.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/ProcessorSessionFactory.java
https://hibernate.atlassian.net/browse/HHH-18863
=> HHH-18863 probably more efficient way to detect if a class is a Panache thing

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLServerLegacySqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/PostgreSQLUnnestFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/xml/DB2XmlTableFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/xml/HANAXmlTableFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/xml/SybaseASEXmlTableFunction.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/NationalizedTest.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java
=> Nightly fix

hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcCoordinatorImpl.java
Seems the two protected methods in `org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl` was copied to `org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl` when working on https://hibernate.atlassian.net/browse/HHH-9747
Furthermore, these two dangling methods are never used anywhere.
not 100% sure, though.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTIN …
=> remove unused close(Statement) and close(ResultSet) from JdbcCoordinatorImpl

Jenkinsfile, ci/jpa-3.2-tck.Jenkinsfile, ci/release/Jenkinsfile, ci/snapshot-publish.Jenkinsfile, nightly.Jenkinsfile
Upgrade to 1.18 to avoid buggy notifications.
See https://hibernate.zulipchat.com/#narrow/channel/132096-hibernate-user/topic/Jenkins.20Notifications
Full changeset:
https://github.com/hibernate/hibernate-jenkins-pipeline-helpers/compare/1.13..1.18
https://github.com/hibernate/hibernate-jenkins-pipeline-helpers/compare/1.17..1.18
Don't configure the version in Jenkinsfile so that it's easier to upgrade next time.
See https://ci.hibernate.org/manage/configure#global-untrusted-pipeline-libraries to change the (default) version globally for all projects.
and can be relicensed under the terms of the [LGPL …
=> Upgrade to hibernate-jenkins-pipeline-helpers 1.18 -- and configure the version on CI instead of in Jenkinsfile

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MariaDBLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/TiDBDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/aggregate/HANAAggregateSupport.java, hibernate-core/src/main/java/org/hibernate/dialect/aggregate/MySQLAggregateSupport.java, hibernate-core/src/main/java/org/hibernate/dialect/function/json/HANAJsonObjectAggFunction.java, hibernate-core/src/test/java/org/hibernate/orm/test/instant/InstantWithNormalizedTest.java
=> Nightly fixes

documentation/src/main/asciidoc/userguide/chapters/domain/entity.adoc, hibernate-core/src/main/java/org/hibernate/boot/model/relational/SqlStringGenerationContext.java, hibernate-core/src/main/java/org/hibernate/boot/model/relational/internal/SqlStringGenerationContextImpl.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/ExplicitSqlStringGenerationContext.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/SQLQueryParser.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/SQLQueryParserUnitTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/subselect/SubselectWithPlaceholdersUnitTests.java
Allow catalog and schema replacement in `<subselect>` and `@Subselect` mappings.
Largely a dust off of https://github.com/hibernate/hibernate-orm/pull/2543.  Thanks @OleksiiKlochko! 
https://hibernate.atlassian.net/browse/HHH-7913
=> HHH-7913 - Schema replacement in <subselect> / @Subselect

hibernate-core/src/test/java/org/hibernate/orm/test/annotations/entity/BasicHibernateAnnotationsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchOptimisticLockingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/naturalid/compound/CompoundNaturalIdTest.java
Fix test CockroachDB test failures.
https://hibernate.atlassian.net/browse/HHH-18866
=> HHH-18866 - Fix CockroachDB test failures

.github/workflows/ci.yml
https://hibernate.atlassian.net/browse/HHH-18870
=> HHH-18870 Set `HOME` to `/root` for atlas CI runners

Jenkinsfile, settings.gradle
Should have been part of a previous Bytebuddy upgrade, but it seems we forgot.
Backports: #9300
=> Don't use net.bytebuddy.experimental=true for Java 23 testing

hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentArrayHolder.java, hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java, hibernate-core/src/main/java/org/hibernate/type/CollectionType.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/orphan/onetomany/merge/MergeCascadeWithMapCollectionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/orphan/onetomany/merge/MergeOrphanRemovalArrayBidirectionalTest.java
https://hibernate.atlassian.net/browse/HHH-18842
=> HHH-18842 Regression: CollectionType.replace() breaks if target is PersistentCollection, but not instance of Collection (e.g. PersistentMap)

documentation/src/main/asciidoc/introduction/Configuration.adoc
=> add some documentation about date/time config settings

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/cid/CompositeIdTypeMismatchTest.java
https://hibernate.atlassian.net/browse/HHH-18839
=> HHH-18839 Validate property type of `@IdClass` at bind time

hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorBinder.java
=> light refactoring to GeneratorBinder

hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/NativeQueryResultBuilderTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/hand/query/EntityReturnClassTests.java
https://hibernate.atlassian.net/browse/HHH-18629
=> HHH-18629 Fix inconsistent column alias generated while result class is used for placeholder

tooling/metamodel-generator/src/main/java/org/hibernate/processor/Context.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/TypeUtils.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/ProcessorSessionFactory.java
https://hibernate.atlassian.net/browse/HHH-18863
=> HHH-18863 backport to 6.6 

documentation/src/main/asciidoc/userguide/chapters/caching/Caching.adoc
=> Fix a couple of typo's

hibernate-core/src/main/java/org/hibernate/boot/internal/BootstrapContextImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/TypeBeanInstanceProducer.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedColumn.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CopyIdentifierComponentSecondPass.java, hibernate-core/src/main/java/org/hibernate/type/spi/TypeBootstrapContext.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/models/BootstrapContextTesting.java
https://hibernate.atlassian.net/browse/HHH-14020
=> HHH-14020 add getServiceRegistry() to TypeBootstrapContext

hibernate-core/src/main/java/org/hibernate/cfg/DialectSpecificSettings.java, hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java
https://hibernate.atlassian.net/browse/HHH-13969
=> HHH-13969 query the page size on Sybase ASE

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultEvictEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/ReSaveReferencedDeletedEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/ReSaveReferencedDeletedEntityJPA.java
https://hibernate.atlassian.net/browse/HHH-14416
=> HHH-14416 resaving child entities after removal

hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/event/spi/EventEngine.java, hibernate-core/src/main/java/org/hibernate/jpa/event/internal/CallbacksFactory.java, hibernate-core/src/main/java/org/hibernate/jpa/event/spi/CallbackRegistry.java
=> light refactoring of EventEngine and CallbacksFactory

documentation/src/main/asciidoc/introduction/Configuration.adoc, documentation/src/main/asciidoc/introduction/Introduction.adoc, hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java, hibernate-core/src/main/java/org/hibernate/jpa/HibernatePersistenceConfiguration.java
This improves the aesthetics of simple examples.
=> HHH-16646 add some nice convenience methods to Configuration

documentation/src/main/asciidoc/introduction/Interacting.adoc, hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AbstractEntityIdGeneratorResolver.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AbstractPropertyHolder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedColumn.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedDiscriminatorColumn.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedJoinColumn.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedJoinColumns.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotationBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ClassPropertyHolder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionPropertyHolder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ColumnsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/DelayedParameterizedTypeBean.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/DialectOverridesAnnotationHelper.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/FilterDefBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorParameters.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ImplicitToOneJoinTableSecondPass.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/IndexColumn.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/QueryBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/QueryHintDefinition.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/SoftDeleteHelper.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/TableBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ToOneBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/XMLContext.java, hibernate-core/src/main/java/org/hibernate/boot/model/naming/Identifier.java, hibernate-core/src/main/java/org/hibernate/internal/util/StringHelper.java
Was #3853.
https://hibernate.atlassian.net/browse/HHH-14519
=> HHH-14519 avoid blowing up when annotation values are blank strings

hibernate-core/src/test/java/org/hibernate/orm/test/locking/B.java, hibernate-core/src/test/java/org/hibernate/orm/test/locking/PessimisticWriteLockWithAliasTest.java
original author of test was @jedichenbin in  https://github.com/hibernate/hibernate-orm/pull/2465
https://hibernate.atlassian.net/browse/HHH-12866
=> HHH-12866 test showing problem is fixed

hibernate-core/src/main/java/org/hibernate/boot/model/internal/ColumnsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/DelayedParameterizedTypeBean.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/DialectOverridesAnnotationHelper.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/FilterDefBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/QueryHintDefinition.java, hibernate-core/src/main/java/org/hibernate/cache/internal/CollectionCacheInvalidator.java, hibernate-core/src/main/java/org/hibernate/engine/internal/ForeignKeys.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/main/java/org/hibernate/type/OneToOneType.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/batch/HandleVersionNumbersInitializedToNegativeValueTests.java
https://hibernate.atlassian.net/browse/HHH-18883
=> HHH-18883 proposed fix

hibernate-core/src/main/java/org/hibernate/graph/internal/parse/GraphParser.java, hibernate-core/src/main/java/org/hibernate/internal/util/collections/StandardStack.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/query/results/internal/DomainResultCreationStateImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/DomainResultGraphPrinter.java, hibernate-core/src/main/java/org/hibernate/sql/results/spi/LoadContexts.java, hibernate-core/src/test/java/org/hibernate/orm/test/util/StandardStackTest.java, hibernate-graalvm/src/main/java/org/hibernate/graalvm/internal/StaticClassLists.java, hibernate-graalvm/src/test/java/org/hibernate/graalvm/internal/StaticClassListsTest.java
- https://hibernate.atlassian.net/browse/HHH-18875
Sharing as a draft as I couldn't test the impact on Quarkus native-images yet.
=> HHH-18875 Stop using `Array.newInstance` in `org.hibernate.internal.util.collections.StandardStack`

documentation/src/main/asciidoc/introduction/Advanced.adoc, hibernate-core/src/main/java/org/hibernate/boot/model/naming/CamelCaseToUnderscoresNamingStrategy.java, hibernate-core/src/main/java/org/hibernate/boot/model/naming/ImplicitNamingStrategyJpaCompliantImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/naming/PhysicalNamingStrategySnakeCaseImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/namingstrategy/CamelCaseToUnderscoresNamingStrategyTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetomany/orderby/IdClassAndOrderByTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/namingstrategy/ejb3joincolumn/PhysicalNamingStrategyImpl.java
https://hibernate.atlassian.net/browse/HHH-16516
=> HHH-16516 rework CamelCaseToUnderscoresNamingStrategy and handle quoted identifiers

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/update/SqmUpdateStatement.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/JsonMappingTests.java
https://hibernate.atlassian.net/browse/HHH-18709
=> HHH-18709 CriteriaUpdate involving JSON field containing Map<String, Object> results in SemanticException

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/HSQLLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/boot/model/naming/Identifier.java, hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/NormalizingIdentifierHelperImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/spi/IdentifierHelperBuilder.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/autoquote/SpecialCharactersTest.java
https://hibernate.atlassian.net/browse/HHH-16516
=> HHH-16516 no need to quote a $ except at the start of column/table name

gradle/databases.gradle, hibernate-c3p0/src/test/java/org/hibernate/test/c3p0/C3P0ConnectionProviderTest.java, hibernate-c3p0/src/test/java/org/hibernate/test/c3p0/C3p0TransactionIsolationConfigTest.java, hibernate-c3p0/src/test/java/org/hibernate/test/c3p0/StatementCacheTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/customsql/CustomSqlRestrictionOverridesTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/ReSaveReferencedDeletedEntity.java, hibernate-testing/hibernate-testing.gradle, hibernate-testing/src/main/java/org/hibernate/testing/transaction/TransactionUtil2.java, settings.gradle
=> attempt fix CI failures and update some deps

hibernate-core/src/main/java/org/hibernate/boot/registry/internal/StandardServiceRegistryImpl.java, hibernate-core/src/main/java/org/hibernate/service/internal/AbstractServiceRegistryImpl.java
=> minor cleanups to ServiceRegistryImpls

documentation/documentation.gradle, gradle/java-module.gradle, hibernate-core/hibernate-core.gradle, hibernate-spatial/hibernate-spatial.gradle, hibernate-testing/hibernate-testing.gradle, settings.gradle
=> more cleanups to dependencies

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/TypecheckUtil.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmBinaryArithmetic.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmUnaryOperation.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/instantiation/InstantiationWithGenericsExpressionTest.java
https://hibernate.atlassian.net/browse/HHH-18274
=> HHH-18274 generics generalized solution

documentation/src/main/asciidoc/introduction/Tuning.adoc, migration-guide.adoc
=> connection pool migration

hibernate-testing/src/main/java/org/hibernate/testing/bytecode/enhancement/BytecodeEnhancerRunner.java, hibernate-testing/src/main/java/org/hibernate/testing/bytecode/enhancement/EnhancementOptions.java, hibernate-testing/src/main/java/org/hibernate/testing/bytecode/enhancement/extension/engine/BytecodeEnhancedClassUtils.java
https://hibernate.atlassian.net/browse/HHH-18906
=> HHH-18906 Allow specifying UnsupportedEnhancementStrategy for Hibernate testing

hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HANADialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
https://hibernate.atlassian.net/browse/HHH-18892
=> HHH-18892 add portable sha() and md5() functions to HQL

documentation/src/main/asciidoc/querylanguage/Expressions.adoc, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
https://hibernate.atlassian.net/browse/HHH-18892
=> HHH-18892 add test for md5() function

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/embeddedid/OneToOneJoinColumnsEmbeddedIdTest.java
https://hibernate.atlassian.net/browse/HHH-17838 
=> HHH-17838 @OneToOne relationship + @Embeddable keys + FetchType.LAZY fail in most recent version

hibernate-core/src/main/java/org/hibernate/cache/spi/SecondLevelCacheLogger.java, hibernate-core/src/main/java/org/hibernate/cache/spi/support/EntityReadOnlyAccess.java, hibernate-core/src/main/java/org/hibernate/cache/spi/support/NaturalIdReadOnlyAccess.java, hibernate-core/src/main/java/org/hibernate/resource/beans/internal/BeansMessageLogger.java, hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/MissingCacheStrategyTest.java
=> improve format of second-level cache log messages

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/MetaAttributeGenerationVisitor.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/hhh18858/ArrayTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/hhh18858/Competitor.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/hhh18858/Contest.java
Jira issue [HHH-18858](https://hibernate.atlassian.net/browse/HHH-18858)
When array property is annotated with one of `@ManyToMany`, `@OneToMany`, or `@ElementCollection`, field in generated meta model class should be of type `jakarta.persistence.metamodel.ListAttribute`, currently is `jakarta.persistence.metamodel.SingularAttribute`.  …
=> HHH-18858 array fields and static metamodel

hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/BatchImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcCoordinatorImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/group/PreparedStatementDetails.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/internal/AbstractPreparedStatementGroup.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/internal/PreparedStatementDetailsStandard.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/internal/PreparedStatementGroupSingleTable.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/internal/PreparedStatementGroupStandard.java, hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchReleaseStatementDebugMessageTest.java
https://hibernate.atlassian.net/browse/HHH-18692
=> HHH-18692 Hibernate attempts to close batched statements multiple times 

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/InheritanceState.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/models/hbm/joinformula/JoinColumnAndFormulaTests.java
See Jira issue [HHH-18384](https://hibernate.atlassian.net/browse/HHH-18384)
In `org.hibernate.boot.model.internal.PropertyBinder#addProperty`element annotated with `@Id` should be added before not annotated elements, but after previously added annotated elements
Additionally, preserving hierarchy order. …
=> HHH-18384 @JoinColumnsOrFormulas broken

build.gradle, hibernate-core/src/main/java/org/hibernate/hql/internal/ast/HqlParser.java, hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/paths/PluralAttributeExpressionsTest.java, hibernate-core/src/test/java/org/hibernate/query/IsEmptyJQLTest.java
Backport of https://github.com/hibernate/hibernate-orm/pull/3183.
https://hibernate.atlassian.net/browse/HHH-6686
=> HHH-6686 Fix JQL exception in face of 'is (not) empty' - 5.3

hibernate-core/src/test/java/org/hibernate/orm/test/collection/bag/PersistentBagContainsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/event/entity/MergeListPreAndPostPersistTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/QuotedIdentifierTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/SchemaUpdateWithUseJdbcMetadataDefaultsSettingToFalseAndQuotedNameTest.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/innerclass/Dummy.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/innerclass/InnerClassTest.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/innerclass/Person.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/ClassWriter.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/Context.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaPackage.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/DefaultConstructor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/InnerClassMetaAttribute.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/NonManagedMetamodel.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/RepositoryConstructor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/model/Metamodel.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/StringUtil.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/TypeUtils.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/ProcessorSessionFactory.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/xml/XmlMetaEntity.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/innerclass/Dummy.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/innerclass/InnerClassTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/innerclass/Person.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/separatecompilationunits/SeparateCompilationUnitsTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/util/CompilationStatement.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/util/TestUtil.java
See Jira Issue [HHH-18693](https://hibernate.atlassian.net/browse/HHH-18693)
This is still work in progress, not to be merged with main branch, at least not immediately.
For each (static) inner non-private class one meta-model class will be generated. 
Naming is as follows. If we have:
```
class A {
...
@Entity
static class B {
...
}
...
}
```
Generated class will be named `A_B_` …
=> HHH-18693 Hibernate Processor does not handle inner types

build.gradle, documentation/documentation.gradle
Older versions cannot correctly resolve dependencies
=> Update and migrate to asciidoc gradle plugin `3.3.2`

tooling/metamodel-generator/src/main/java/org/hibernate/processor/Context.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMeta.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/ProcessorSessionFactory.java
also cache enum results read from index
https://hibernate.atlassian.net/browse/HHH-18863
=> HHH-18863 allow index creation to be disabled in processor

.github/workflows/contributor-build.yml, build.gradle, documentation/documentation.gradle
@dreab8 I think we should also keep `5.6` dependencies updated so that if we eventually need a release we have a working build on the branch
=> Port forward missing dependency updates from `5.3`

hibernate-core/src/test/java/org/hibernate/orm/test/idclass/NestedIdClassTest.java
https://hibernate.atlassian.net/browse/HHH-14340
HHH-14340; `NestedIdClassTest` fails, duplicate column in the generated SQL
=> HHH-14340 - Add test

tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/selectenumproperty/Topic.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/selectenumproperty/TopicData.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/selectenumproperty/TopicRepository.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/selectenumproperty/TopicStatus.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/selectenumproperty/TopicTypeEnumTest.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
Jira issue [HHH-18920](https://hibernate.atlassian.net/browse/HHH-18920)
Properly resolving parameter type name when matching selection with constructor parameters.
[HHH-18920]: https://hibernate.atlassian.net/browse/HHH-18920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
=> HHH-18920 Enum parameters in Jakarta Data repository method return type constructor are not properly matched

hibernate-core/src/main/java/org/hibernate/boot/model/TypeContributions.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/hhh18787/CustomData.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/hhh18787/CustomDataType.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/hhh18787/SomeEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/hhh18787/TypesContributor.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/usertype/hhh18787/UserTypeNotRecognisedTestCase.java
See Jira issue [HHH-18787](https://hibernate.atlassian.net/browse/HHH-18787)
When registering custom type, use `type.returnedClass().getTypeName()` instead of `type.returnedClass().getName()`. This is key that is later used. Possible alternative may be to register under both if different. …
=> HHH-18787 Custom UserType not recognised for array properties

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/NamedQueryMethod.java
Minor change. Creating named query as `TypedQuery` is avoiding (irritating) compilation warnings
=> Use returnClass parameter in call to EntityManager.createNamedQuery in generated methods

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractAnnotatedMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractCriteriaMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/IdFinderMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/LifecycleMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/Constants.java
instead of directly throwing IllegalArgumentException
=> use Objects.requireNonNull in generated code for repositories

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/LazyAttributeLoadingInterceptor.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultRefreshEventListener.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/refresh/RefreshEntityWithLazyPropertyTest.java
https://hibernate.atlassian.net/browse/HHH-13377
=> HHH-13377 Lazy loaded properties of bytecode enhanced entity are left stale after refresh of entity

hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemavalidation/MariaDbJsonColumnValidationTest.java
Jira issue [HHH-18869](https://hibernate.atlassian.net/browse/HHH-18869)
JSON is an alias for LONGTEXT (see [JSON Data Type](https://mariadb.com/kb/en/json-data-type/) in MariaDB Knowledge Base)
Simple fix is to override `org.hibernate.dialect.Dialect#equivalentTypes` for `MariaDBDialect` to return true when comparing those two types. …
=> HHH-18869 Schema validation fails with MariaDB when entity field is of type BigDecimal[]

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/access/UnsupportedEnhancementStrategyTest.java
https://hibernate.atlassian.net/browse/HHH-18904
https://hibernate.atlassian.net/browse/HHH-18903
=> HHH-18904 Improve check for unsupported property access properties during bytecode-enhancement

hibernate-core/src/main/java/org/hibernate/cfg/Environment.java, hibernate-core/src/main/java/org/hibernate/cfg/JdbcSettings.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DriverManagerConnectionProviderImpl.java
=> improve jdoc for some JdbcSettings and deprecate one of them

documentation/src/main/asciidoc/introduction/Tuning.adoc
=> links to settings from doc

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
the spec doesn't say it can't be empty, and so I think this is the most natural interpretation
=> treat empty/blank @DiscriminatorValue literally

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/SelectUnknownEnumLiteralTest.java
See Jira issue [HHH-18894](https://hibernate.atlassian.net/browse/HHH-18894) and [original post](https://discourse.hibernate.org/t/hibernate-6-6-enum-literal-is-considered-field-literal-instead/10672)
Exception is thrown when enum constant is used as column in select if enum class is not referenced by any managed class. 
Proposed solution is to treat non-managed class in equivalent way as are treated managed enum classes.
For more …
=> HHH-18894  Hibernate 6.6 enum literal is considered field literal instead

hibernate-core/src/main/java/org/hibernate/SessionFactory.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappingMetamodelImpl.java
=> minor things

hibernate-core/src/test/java/org/hibernate/orm/test/querycache/QueryCacheTest.java
Test demonstrating the issue has been fixed.
https://hibernate.atlassian.net/browse/HHH-18371
=> HHH-18371 JDBC connection acquisition failure can lead to query cache corruption 

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/ReSaveReferencedDeletedEntity.java
=> Only cast LONG32 to text on PG to avoid type comparison related issues

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/test/java/org/hibernate/dialect/DialectTest.java
In case of query with left join, the existing QUERY_PATTERN of Dialect class doesn't permits to correctly append query hint (aka use index) to the query. The result is an invalid SQL query
Example of code that not works
```
myEntity.join(MyEntity_.other, JoinType.LEFT)
[...]
final TypedQuery<MyEntity> query = em.createQuery(cq);
if (query instanceof final org.hibernate.query.Query<CommandeStock> hibernateQuery) {
hibernateQuery.addQueryHint("MY_INDEX");
}
```
Those changes aimed to improve QUERY_PATTERN. Now the regex handles queries with usuals join keywords like natural, left/right, inner/outer join.
Unit tests was appended to check existing behavior and new one.
By submitting this pull request, I confirm that my …
=> HHH-18916 - Extends Dialect#addQueryHints support for join queries

hibernate-c3p0/hibernate-c3p0.gradle, hibernate-c3p0/src/test/resources/META-INF/validation.xml, hibernate-core/hibernate-core.gradle, hibernate-core/src/test/resources/META-INF/validation.xml, hibernate-spatial/hibernate-spatial.gradle, hibernate-spatial/src/test/resources/META-INF/validation.xml, settings.gradle
Hey @gavinking 😃 I thought you might be somewhat interested in this one. 
I'm not sure how ORM wants to test that integration with the Validation spec, since the spec itself somewhat tells that the EL is a "must", but HV can work without it too.
see also https://docs.jboss.org/hibernate/validator/9.0/reference/en-US/html_single/#non-el-message-interpolator …
=> Do not rely on Expressly for Hibernate Validator message interpolation

hibernate-core/src/main/java/org/hibernate/action/internal/BulkOperationCleanupAction.java, hibernate-core/src/main/java/org/hibernate/boot/MetadataBuilder.java, hibernate-core/src/main/java/org/hibernate/cfg/MappingSettings.java, hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
=> add missing jdoc for hibernate.discriminator.force_in_select setting

documentation/src/main/asciidoc/integrationguide/chapters/services/Services.adoc, documentation/src/main/asciidoc/integrationguide/chapters/services/extras/extend/EventPublishingService.java, documentation/src/main/asciidoc/integrationguide/chapters/services/extras/extend/EventPublishingServiceContributor.java, documentation/src/main/asciidoc/integrationguide/chapters/services/extras/extend/EventPublishingServiceImpl.java, documentation/src/main/asciidoc/integrationguide/chapters/services/extras/extend/EventPublishingServiceInitiator.java, documentation/src/main/asciidoc/integrationguide/chapters/services/extras/override/LatestAndGreatestConnectionProviderImpl.java, documentation/src/main/asciidoc/integrationguide/chapters/services/extras/override/ex2-contributor.java, documentation/src/main/asciidoc/integrationguide/chapters/services/extras/override/ex2-meta-inf, documentation/src/main/asciidoc/integrationguide/chapters/services/extras/override/ex3-contributor.java, documentation/src/main/asciidoc/integrationguide/chapters/services/extras/override/ex3-meta-inf, documentation/src/main/asciidoc/integrationguide/preface.adoc
Recently working on Hibernate Integration stuff in MongoDB. After carefully reading the excellent Integration doc, it seems there are some minor defects that could be fixed.
As normal, many might be false positives. I'll leave some comments to explain the reasons behind some changes.
=> improve integration doc

hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/DdlTransactionIsolatorJtaImpl.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaTransactionCoordinatorImpl.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/synchronization/SynchronizationCallbackCoordinatorTrackingImpl.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/synchronization/SynchronizationCallbackTarget.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/spi/TransactionCoordinatorBuilder.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/spi/TransactionCoordinatorOwner.java
Recently worked on transaction stuff in mongoDB and found some obvious defects in the javadoc for `resource/transaction` package.
=> fix some obvious defect in javadoc for resource/transaction package

hibernate-core/src/main/java/org/hibernate/event/internal/EmptyEventManager.java, hibernate-core/src/main/java/org/hibernate/event/spi/EventManager.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderHelper.java, hibernate-jfr/src/main/java/org/hibernate/event/jfr/internal/EntityLockEvent.java, hibernate-jfr/src/main/java/org/hibernate/event/jfr/internal/JfrEventManager.java
https://hibernate.atlassian.net/browse/HHH-18942
=>  HHH-18942 JFR lock entity event

hibernate-core/src/main/java/org/hibernate/SharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/Transaction.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/test/java/org/hibernate/orm/test/resource/transaction/jta/JpaComplianceAlreadyStartedTransactionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/resource/transaction/jta/NonJpaComplianceAlreadyStartedTransactionTest.java
and clarify its semantics in the jdoc
=> HHH-18867 correctly implement the documented semantics of beginTransaction()

documentation/src/main/asciidoc/introduction/Configuration.adoc, documentation/src/main/asciidoc/introduction/Tuning.adoc
=> mention Hibernate JFR in the Short Guide

hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java, hibernate-core/src/main/java/org/hibernate/cfg/Environment.java, hibernate-core/src/main/java/org/hibernate/jpa/HibernatePersistenceConfiguration.java
=> Javadoc for Configuration properties

hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
=> Improve msgs

documentation/src/main/style/asciidoctor/css/hibernate-layout.css
=> tune the documentation CSS

documentation/documentation.gradle, hibernate-core/src/main/java/org/hibernate/query/MutationQuery.java
These modules don't contain APIs which are called by users or implemented by integrators. Including them in the generated Javadoc results in confusion for users and makes the Javadoc much more difficult to navigate and consume.
In particular, we definitely don't want packages like these included in the main Javadoc distribution for Hibernate ORM:
-  `org.hibernate.testing.orm.domain.gambit`
-  `org.hibernate.testing.orm.domain.helpdesk`
"Good documentation" isn't about having the maximum possible quantity of documentation; it's about having documentation where people actually have a hope of finding what they're looking for. In general, generated Javadoc is entirely useless except when we've actually taken time to actually write meaningful and readable prose. If all I need is a list of …
=> remove modules which don't contain APIs from aggregated Javadoc

hibernate-core/src/main/java/org/hibernate/id/uuid/UuidVersion7Strategy.java
Jira issue [HHH-18947](https://hibernate.atlassian.net/browse/HHH-18947)
Changes suggested here are using randomly created 62 bytes counter (instead of current 14 bits counter, and  48 bits random bytes) that is incrementing by random value for each new generated UUID. This is improving entropy, and it is now comparable to that of UUID v6. …
=> HHH-18947 Changed UUID v 7 implementation for better entropy

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java, hibernate-community-dialects/src/test/java/org/hibernate/community/dialect/InformixFunctionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/ASTParserLoadingTest.java
Port forward the changes from https://github.com/hibernate/hibernate-orm/pull/8652. Also see the 6.6 variant for this PR: https://github.com/hibernate/hibernate-orm/pull/9343
https://hibernate.atlassian.net/browse/HHH-18168
https://hibernate.atlassian.net/browse/HHH-18369 …
=> Port forward some Informix fixes

hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HANADialect.java, hibernate-core/src/main/java/org/hibernate/dialect/aggregate/DB2AggregateSupport.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/NationalizedTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
https://hibernate.atlassian.net/browse/HHH-18803
https://hibernate.atlassian.net/browse/HHH-18806
https://hibernate.atlassian.net/browse/HHH-18892
=> Various nightly fixes

tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/multivaluebinding/Post.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/multivaluebinding/PostRepository.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/multivaluebinding/TopicPostTest.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/NamedQueryMethod.java
Jira issue [HHH-18960](https://hibernate.atlassian.net/browse/HHH-18960)
Currently when named query parameter allows multiple value binding (like parameters for `in`), in generated query it is represented as raw type instead of `List` (or, possibly, `Collection`). Same problem is present when generating meta model class for Jakarta Data repository. …
=> HHH-18960 Hibernate Processor - when query parameter allows multiple value binding parameter in generated query should be collection

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMeta.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/NamedQueryMethod.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/resultclass/NameValue.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/resultclass/Post.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/resultclass/ResultClassTest.java
Jira issue [HHH-18958](https://hibernate.atlassian.net/browse/HHH-18958)
This has been marked as TODO in `org.hibernate.processor.annotation.AnnotationMeta` some time ago
[HHH-18958]: https://hibernate.atlassian.net/browse/HHH-18958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …
=> HHH-18958 Hibernate Processor - respect @NamedQuery(resultClass)

tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/reactive/Library2.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/IdFinderMethod.java
https://hibernate.atlassian.net/browse/HHH-18953
=> HHH-18953 correctly handle Optional in reactive repos

hibernate-core/src/main/java/org/hibernate/Transaction.java, hibernate-core/src/main/java/org/hibernate/cfg/TransactionSettings.java, hibernate-core/src/main/java/org/hibernate/collection/spi/AbstractPersistentCollection.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CollectionEntry.java, hibernate-core/src/main/java/org/hibernate/engine/transaction/internal/TransactionImpl.java, hibernate-core/src/main/java/org/hibernate/engine/transaction/spi/TransactionImplementor.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/resource/jdbc/internal/AbstractLogicalConnectionImplementor.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jdbc/internal/JdbcResourceLocalTransactionCoordinatorImpl.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaTransactionAdapterTransactionManagerImpl.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaTransactionAdapterUserTransactionImpl.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaTransactionCoordinatorImpl.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/StatusTranslator.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/spi/TransactionCoordinator.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/spi/TransactionStatus.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/NamedQueryTransactionFailureTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/transactions/TransactionLifecycleTest.java
also clean up some stuff in AbstractPersistentCollection
Unfortunately TransactionStatus is an SPI type, which makes its use in the API of Transaction a bit wrong. Also, it's weird to see dependence on an interface defined by JPA. (However these are relatively harmless aesthetic points, so I decided not to deprecate anything.) Instead I've added alternative "convenience" operations.
Note on terminology: a transaction which has been "marked for rollback only" is still an active transaction! You can still do work in it, and that work will still be atomically rolled back when the transaction completes. Apparently there was some confusion on this at some point, which was later fixed, but some evidence of the confusion was left behind in code. …
=> HHH-18965 give some love to org.hibernate.Transaction

hibernate-core/src/main/java/org/hibernate/Transaction.java
=> add missing @Override annotations

build.gradle, ci/release/Jenkinsfile, gradle/published-java-module.gradle, tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
https://hibernate.atlassian.net/browse/HHH-18912
Backport to 6.2
See https://github.com/hibernate/hibernate-orm/pull/9413
=> HHH-18912 - ORM release process

ci/release/Jenkinsfile
https://hibernate.atlassian.net/browse/HHH-18963
=> HHH-18963 Switch to scheduled releases instead of release on push

hibernate-core/src/main/java/org/hibernate/dialect/SybaseASESqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/AnsiNullTest.java
https://hibernate.atlassian.net/browse/HHH-16216
=> HHH-16216 Add Sybase ASE test for ansinull=off and fix some issues

databases/mariadb/matrix.gradle, docker_db.sh, hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java, hibernate-core/src/main/java/org/hibernate/type/SqlTypes.java, hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchOptimisticLockingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchUpdateAndVersionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/lock/RepeatableReadTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/locking/OptimisticAndPessimisticLockTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/locking/OptimisticLockTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/optlock/OptimisticLockTest.java, hibernate-vector/src/main/java/org/hibernate/vector/BinaryVectorJdbcType.java, hibernate-vector/src/main/java/org/hibernate/vector/MariaDBFunctionContributor.java, hibernate-vector/src/main/java/org/hibernate/vector/MariaDBTypeContributor.java, hibernate-vector/src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor, hibernate-vector/src/main/resources/META-INF/services/org.hibernate.boot.model.TypeContributor, hibernate-vector/src/test/java/org/hibernate/vector/MariaDBTest.java
Since 11.7 MariaDB support Vector fields. 
This was in preview since some time, and now released since 11.7.1. see https://mariadb.org/projects/mariadb-vector/ 
https://hibernate.atlassian.net/browse/HHH-18900
=> HHH-18900 MariaDB Vector support

hibernate-core/src/main/java/org/hibernate/boot/internal/StandardEntityNotFoundDelegate.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/usertype/EnhancedUserTypeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/usertype/MyEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/usertype/MyId.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/usertype/MyType.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/basic/BookAuthorRepository.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/reactive/Library.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/ClassWriter.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/Context.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractAnnotatedMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/EventField.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/LifecycleMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/QueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/model/Metamodel.java
=> support for Jakarta Data events

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractAnnotatedMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaAttribute.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaCollection.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaType.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/DataAnnotationMetaAttribute.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/DefaultConstructor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/EventField.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/LifecycleMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/NameMetaAttribute.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/NamedQueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/NaturalIdFinderMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/QueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/RepositoryConstructor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/model/Metamodel.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/Constants.java
=> preserve order of members in metamodel/repo impl

hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
=> add @implNotes to SessionImpls

documentation/src/main/asciidoc/introduction/Configuration.adoc, documentation/src/main/asciidoc/introduction/Introduction.adoc
=> fix a mistake in the documentation

documentation/src/main/asciidoc/introduction/Configuration.adoc, documentation/src/main/asciidoc/introduction/Tuning.adoc, hibernate-agroal/src/main/java/org/hibernate/agroal/internal/AgroalConnectionProvider.java, hibernate-agroal/src/main/java/org/hibernate/agroal/internal/package-info.java, hibernate-c3p0/src/main/java/org/hibernate/c3p0/internal/C3P0ConnectionProvider.java, hibernate-c3p0/src/main/java/org/hibernate/c3p0/internal/C3P0MessageLogger.java, hibernate-c3p0/src/main/java/org/hibernate/c3p0/internal/StrategyRegistrationProviderImpl.java, hibernate-c3p0/src/test/java/org/hibernate/test/c3p0/C3P0ProxyConnectionProvider.java, hibernate-core/src/main/java/org/hibernate/cfg/JdbcSettings.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/ConnectionProviderInitiator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DatasourceConnectionProviderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DriverManagerConnectionProviderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/spi/ConnectionProviderConfigurationException.java, hibernate-core/src/main/java/org/hibernate/internal/log/ConnectionInfoLogger.java, hibernate-hikaricp/src/main/java/org/hibernate/hikaricp/internal/HikariCPConnectionProvider.java, hibernate-hikaricp/src/main/java/org/hibernate/hikaricp/internal/HikariConfigurationUtil.java, hibernate-hikaricp/src/main/java/org/hibernate/hikaricp/internal/StrategyRegistrationProviderImpl.java, hibernate-ucp/src/main/java/org/hibernate/oracleucp/internal/StrategyRegistrationProviderImpl.java, hibernate-ucp/src/main/java/org/hibernate/oracleucp/internal/UCPConnectionProvider.java
note that the "garbage cast" in the TODO actually
resulted in a bad user experience
=> convert properties passed to Agroal to strings

documentation/src/main/asciidoc/introduction/Introduction.adoc, documentation/src/main/asciidoc/introduction/Tuning.adoc, hibernate-agroal/src/main/java/org/hibernate/agroal/internal/AgroalConnectionProvider.java, hibernate-c3p0/src/main/java/org/hibernate/c3p0/internal/C3P0ConnectionProvider.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DatabaseConnectionInfoImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DatasourceConnectionProviderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DriverManagerConnectionProviderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/spi/DataSourceBasedMultiTenantConnectionProviderImpl.java, hibernate-core/src/main/java/org/hibernate/jpa/HibernatePersistenceConfiguration.java, hibernate-hikaricp/src/main/java/org/hibernate/hikaricp/internal/HikariCPConnectionProvider.java, hibernate-ucp/src/main/java/org/hibernate/oracleucp/internal/UCPConnectionProvider.java
=> report the name of the ConnectionProvider along with the other info

hibernate-core/src/main/java/org/hibernate/cfg/JdbcSettings.java, hibernate-core/src/main/java/org/hibernate/jpa/HibernatePersistenceConfiguration.java
=> add two additional convenience methods to HibernatePersistenceConfiguration

documentation/src/main/asciidoc/introduction/Tuning.adoc, hibernate-core/src/main/java/org/hibernate/cfg/CacheSettings.java, hibernate-core/src/main/java/org/hibernate/cfg/JdbcSettings.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/spi/ConnectionProvider.java
=> big improvements to docs surrounding ConnectionProvider

documentation/src/main/asciidoc/introduction/Entities.adoc
=> more info about @Version in the doc

hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AbstractEntityIdGeneratorResolver.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorAnnotationHelper.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorParameters.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/IdBagIdGeneratorResolverSecondPass.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/IdGeneratorResolverSecondPass.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/StrictIdGeneratorResolverSecondPass.java, hibernate-core/src/main/java/org/hibernate/cfg/ManagedBeanSettings.java, hibernate-core/src/main/java/org/hibernate/generator/Generator.java, hibernate-core/src/main/java/org/hibernate/id/NativeGenerator.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tuple/internal/AnonymousTupleType.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/spi/BeanContainer.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/ExportableValueGeneratorTest.java
This PR allows regular "value" (i.e. non-`@Id`) generators to implement `Configurable` and `ExportableProducer`, finally putting them on equal footing with id generators.
See https://hibernate.atlassian.net/browse/HHH-18983.
=> HHH-18983 work on Generators

documentation/src/main/asciidoc/introduction/Entities.adoc
I don't think that's how Postgres arrays actually work
=> fix assertion that I believe to be incorrect at least on Postgres

hibernate-core/src/main/java/org/hibernate/boot/registry/selector/internal/StrategySelectorImpl.java, hibernate-core/src/main/java/org/hibernate/boot/registry/selector/spi/NamedStrategyContributions.java, hibernate-core/src/main/java/org/hibernate/boot/registry/selector/spi/NamedStrategyContributor.java, hibernate-core/src/main/java/org/hibernate/boot/registry/selector/spi/StrategySelector.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/registry/strategy/NamedStrategyContributorBaselineTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/registry/strategy/NamedStrategyContributorImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/registry/strategy/NamedStrategyContributorTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/registry/strategy/StrategyContract.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/registry/strategy/StrategyContractImpl.java
HHH-18937 - Introduce a JavaServiceLoadable extension to contribute "strategy selectors"
https://hibernate.atlassian.net/browse/HHH-18937
=> HHH-18937 - Introduce a JavaServiceLoadable extension to contribute "strategy selectors"

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ManyToManyCollectionPart.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/manytoone/ManyToOneWithAnyAndSameEntityTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/manytoone/ManyToOneWithAnyAndSecondaryTable.java
He mistakenly assumes, at first glance, that the mappedBy attribut is not a @ManyToOne or @Any because the mappedBy attribut is mapped in a secondary table and therefore has a join.
The problem appears later during a cast where the instance of type DiscriminatedAssociationAttributeMapping is cast to PluralAttributeMapping.
https://hibernate.atlassian.net/browse/HHH-18750 …
=> HHH-18750 : @OneToMany with @Any mapped in secondary table KO (ClassCastException

documentation/src/main/asciidoc/userguide/chapters/query/spatial/Spatial.adoc
This PR updates the documentation to reflect the availability of several MySQL Spatial Functions based on both the official documentation ([MySQL Spatial Relation Functions](https://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions.html) and [MySQL Spatial Operator Functions](https://dev.mysql.com/doc/refman/8.4/en/spatial-operator-functions.html)) and personal testing. Specifically, the following functions are confirmed to be available:
ST_Distance
ST_Buffer
ST_ConvexHull
ST_Intersection
ST_Difference
ST_SymDifference …
=> HHH-18966 update user guide mysql spatial function support

documentation/src/main/asciidoc/introduction/Interacting.adoc, hibernate-core/src/main/java/org/hibernate/query/NamedAttributeRange.java, hibernate-core/src/main/java/org/hibernate/query/NamedPathElement.java, hibernate-core/src/main/java/org/hibernate/query/Path.java, hibernate-core/src/main/java/org/hibernate/query/PathElement.java, hibernate-core/src/main/java/org/hibernate/query/PathRange.java, hibernate-core/src/main/java/org/hibernate/query/PathRoot.java, hibernate-core/src/main/java/org/hibernate/query/Restriction.java, hibernate-core/src/main/java/org/hibernate/query/criteria/internal/NamedCriteriaQueryMementoImpl.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/NamedHqlQueryMementoImpl.java, hibernate-core/src/main/java/org/hibernate/query/range/CaseInsensitiveValue.java, hibernate-core/src/main/java/org/hibernate/query/range/FullRange.java, hibernate-core/src/main/java/org/hibernate/query/range/Interval.java, hibernate-core/src/main/java/org/hibernate/query/range/LowerBound.java, hibernate-core/src/main/java/org/hibernate/query/range/NotNull.java, hibernate-core/src/main/java/org/hibernate/query/range/Pattern.java, hibernate-core/src/main/java/org/hibernate/query/range/Range.java, hibernate-core/src/main/java/org/hibernate/query/range/UpperBound.java, hibernate-core/src/main/java/org/hibernate/query/range/Value.java, hibernate-core/src/main/java/org/hibernate/query/range/ValueList.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/restriction/RestrictionTest.java
https://hibernate.atlassian.net/browse/HHH-18990
=> HHH-18990 refinements to Path, add NotNull range

documentation/src/main/asciidoc/introduction/Interacting.adoc, hibernate-core/src/main/java/org/hibernate/query/criteria/CriteriaDefinition.java, hibernate-core/src/main/java/org/hibernate/query/criteria/JpaCriteriaQuery.java, hibernate-core/src/main/java/org/hibernate/query/criteria/JpaQueryStructure.java, hibernate-core/src/main/java/org/hibernate/query/restriction/Restriction.java, hibernate-core/src/main/java/org/hibernate/query/sqm/NodeBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/AbstractSqmSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/KeyBasedPagination.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/from/SqmFromClause.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/AbstractSqmSelectQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmJpaCompoundSelection.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQuerySpec.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectStatement.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/query/CriteriaDefinitionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/restriction/RestrictionTest.java
https://hibernate.atlassian.net/browse/HHH-18979
=> HHH-18979 Add Restriction.apply and JpaCriteriaQuery.getRoot()

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderArrayParam.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderStandard.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoaderArrayParam.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoaderInPredicate.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoadingBatcher.java, hibernate-core/src/main/java/org/hibernate/sql/ForUpdateFragment.java
https://hibernate.atlassian.net/browse/HHH-18992
=> HHH-18992 pass LockOptions correctly to multiple id loaders

tooling/hibernate-gradle-plugin/src/main/java/org/hibernate/orm/tooling/gradle/HibernateOrmPlugin.java
There was a report that the build.gradle file contained in the project stubs generated by start.spring.io did not compile (see spring-io/start.spring.io#1078) that identified [HHH-15557](https://hibernate.atlassian.net/browse/HHH-15557) as the underlying issue.
Here is my attempt to fix it following the approach suggested in the [Gradle docs](https://docs.gradle.org/7.6.2/userguide/implementing_gradle_plugins.html#reacting_to_plugins).
For …
=> HHH-15557 fix problem when orm plugin is applied before Java plugin

hibernate-core/src/main/java/org/hibernate/annotations/Check.java, hibernate-core/src/main/java/org/hibernate/annotations/Comment.java, hibernate-core/src/main/java/org/hibernate/annotations/Parameter.java, hibernate-core/src/main/java/org/hibernate/usertype/ParameterizedType.java, migration-guide.adoc
=> Migration guide and a deprecation

documentation/src/main/asciidoc/introduction/Tuning.adoc, documentation/src/main/asciidoc/userguide/chapters/batch/Batching.adoc
=> update docs for StatelessSession to reflect new capabilities

migration-guide.adoc
=> migration guide for StatelessSession and second-level cache

hibernate-core/src/main/java/org/hibernate/engine/spi/CollectionEntry.java, hibernate-core/src/test/java/org/hibernate/orm/test/interceptor/CollectionRecreateInterceptorTest.java
https://hibernate.atlassian.net/browse/HHH-3129
=> HHH-3129 Set CollectionEntry role whenever possible

hibernate-core/src/test/java/org/hibernate/orm/test/flush/AutoFlushRemoveTest.java
https://hibernate.atlassian.net/browse/HHH-3354
=> HHH-3354 Test auto flush remove previously added entity from collection

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddableMappingTypeImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/columndiscriminator/Author.java, hibernate-core/src/test/java/org/hibernate/orm/test/columndiscriminator/Book.java, hibernate-core/src/test/java/org/hibernate/orm/test/columndiscriminator/BookDetails.java, hibernate-core/src/test/java/org/hibernate/orm/test/columndiscriminator/BoringBookDetails.java, hibernate-core/src/test/java/org/hibernate/orm/test/columndiscriminator/ColumnDiscrimnatorWithSchemaTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/columndiscriminator/SpecialBookDetails.java, hibernate-core/src/test/resources/org/hibernate/orm/test/columndiscriminator/orm.xml
Jira issue [HHH-18988](https://hibernate.atlassian.net/browse/HHH-18988)
Parameter `tableExpression` in `org.hibernate.metamodel.mapping.internal.ExplicitColumnDiscriminatorMappingImpl` constructor should be qualified. At the moment only table name was used, ignoring schema (and/or catalog) name.
Change has been tested in `6.6` branch, so it can be safely backported. …
=> HHH-18988 Embeddable inheritance + default_schema results in NPE at startup

hibernate-core/src/main/java/org/hibernate/graph/AttributeNode.java, hibernate-core/src/main/java/org/hibernate/graph/Graph.java, hibernate-core/src/main/java/org/hibernate/graph/internal/AbstractGraph.java, hibernate-core/src/main/java/org/hibernate/graph/internal/AttributeNodeImpl.java, hibernate-core/src/main/java/org/hibernate/graph/spi/GraphImplementor.java
- add Javadoc, which has been missing for many years
- add a missing operation
=> javadoc for graph package

Jenkinsfile
We were incorrectly skipping these reports for runs that didn't have a specific CI node set (like JDK version runs for PRs to the 6.6 branch).
=> Produce develocity reports on all Jenkins CI runs for PRs

Jenkinsfile
We were incorrectly skipping these reports for runs that didn't have a specific CI node set (like JDK version runs for PRs to the 6.6 branch).
=> [6.6] Produce develocity reports on all Jenkins CI runs for PRs

hibernate-core/src/main/java/org/hibernate/graph/EntityGraphs.java, hibernate-core/src/main/java/org/hibernate/graph/GraphParser.java
=> modernize EntityGraphs utility class

hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/instantiation/DynamicInstantiationTemporalTest.java
https://hibernate.atlassian.net/browse/HHH-4179
=> HHH-4179 Test constructor syntax with temporal types

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/EntityGraphWithInheritanceTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/named/multiple/NamedEntityGraphsWithInheritanceTest.java
This MR is the continuation of this one https://github.com/hibernate/hibernate-orm/pull/9088 .
The aim is to make inheritance work on Entity graphs, as described in the NamedEntityGraph annotation. …
=> HHH-18714 add support for inheritance in NamedEntityGraph annotation

hibernate-core/src/main/java/org/hibernate/graph/AttributeNode.java, hibernate-core/src/main/java/org/hibernate/graph/EntityGraphs.java, hibernate-core/src/main/java/org/hibernate/graph/Graph.java, hibernate-core/src/main/java/org/hibernate/graph/RootGraph.java, hibernate-core/src/main/java/org/hibernate/graph/internal/AbstractGraph.java, hibernate-core/src/main/java/org/hibernate/graph/internal/AttributeNodeImpl.java, hibernate-core/src/main/java/org/hibernate/graph/spi/AttributeNodeImplementor.java, hibernate-core/src/main/java/org/hibernate/graph/spi/GraphImplementor.java
All of these methods now exist in the JPA supertype,  without the funky naming. We need to guide users away from the non-standard ones, especially in light of the ugliness.
=>  Graphpocalypse: deprecated funkily-named methods of Graph

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java
https://hibernate.atlassian.net/browse/HHH-18714
=>  HHH-18714 add an explicit type check instead of the cast to raw

hibernate-core/src/test/java/org/hibernate/orm/test/deletedetached/DeleteDetachedJpaComplianceTest.java
https://hibernate.atlassian.net/browse/HHH-4160
=> HHH-4160 Add test to check JPA compliance for deleting detached entities

hibernate-core/src/test/java/org/hibernate/orm/test/deletedetached/DeleteDetachedOptionalityViolationTest.java
https://hibernate.atlassian.net/browse/HHH-2792
=> HHH-2792 Test remove detached with null values and detached proxy

hibernate-core/src/main/java/org/hibernate/annotations/AttributeAccessor.java, hibernate-core/src/main/java/org/hibernate/annotations/Cascade.java, hibernate-core/src/main/java/org/hibernate/annotations/CascadeType.java, hibernate-core/src/main/java/org/hibernate/annotations/Checks.java, hibernate-core/src/main/java/org/hibernate/annotations/FlushModeType.java, hibernate-core/src/main/java/org/hibernate/annotations/GenericGenerator.java, hibernate-core/src/main/java/org/hibernate/annotations/GenericGenerators.java, hibernate-core/src/main/java/org/hibernate/annotations/NamedNativeQuery.java, hibernate-core/src/main/java/org/hibernate/annotations/NamedQuery.java, hibernate-core/src/main/java/org/hibernate/annotations/ResultCheckStyle.java, hibernate-core/src/main/java/org/hibernate/annotations/SQLDelete.java, hibernate-core/src/main/java/org/hibernate/annotations/SQLDeleteAll.java, hibernate-core/src/main/java/org/hibernate/annotations/SQLInsert.java, hibernate-core/src/main/java/org/hibernate/annotations/SQLUpdate.java
especially the enums which names collide with JPA
=> escalate some annotation deprecations to forRemoval=true

Jenkinsfile, settings.gradle
https://hibernate.atlassian.net/browse/HHH-18972
Backport of #9477 to branch 6.6.
Potentially more impacting here, as we're upgrading from Bytebuddy 1.14 (on `main` we were already on Bytebuddy 1.15). Creating as draft so we can see the impact.
See also https://github.com/wildfly/wildfly/pull/18588
=> Backport HHH-18972 to branch 6.6 - Upgrade to ByteBuddy 1.15.11

hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/RuntimeMetamodelsImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/spi/RuntimeMetamodelsImplementor.java, hibernate-core/src/main/java/org/hibernate/query/internal/NamedObjectRepositoryImpl.java, hibernate-core/src/main/java/org/hibernate/query/named/NamedObjectRepository.java
=> SessionFactoryImpl doesn't need to implement BindingContext

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AggregateComponentSecondPass.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/mapping/Column.java, hibernate-core/src/main/java/org/hibernate/mapping/Formula.java, hibernate-core/src/main/java/org/hibernate/mapping/IdentifierCollection.java, hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java, hibernate-core/src/main/java/org/hibernate/mapping/Selectable.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractEmbeddableMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddableMappingTypeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SelectableMappingImpl.java, hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java
=> a minor cleanup

hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/SessionFactory.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionFactoryDelegatingImpl.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/RepresentationMode.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractManagedType.java, hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/dynamic/DynamicJoinedInheritanceTests.java
https://hibernate.atlassian.net/browse/HHH-19016
=> HHH-19016 add SessionFactory.createGraphForDynamicEntity()

hibernate-core/src/main/java/org/hibernate/graph/Graph.java, hibernate-core/src/main/java/org/hibernate/graph/GraphParser.java, hibernate-core/src/main/java/org/hibernate/graph/internal/parse/GraphParser.java
=> GraphParser warnings

hibernate-core/src/main/java/org/hibernate/binder/internal/CommentBinder.java
This annotation is deprecated in 7, but I guess this is a candidate for backport
https://hibernate.atlassian.net/browse/HHH-19011
=> HHH-19011 fix incorrect placement of table comment with @Comment

hibernate-core/src/test/java/org/hibernate/orm/test/annotations/comment/CommentElementCollectionTest.java
Test to reproduce the https://hibernate.atlassian.net/browse/HHH-19011
=> HHH-19011 Reproducing test

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedColumn.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedJoinColumn.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/comment/jpa/CommentTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/comment/jpa/CommentsTest.java
and add tests for JPA comments based on older tests for @Comment
=> fix 'comment' and 'options' for @JoinColumn

hibernate-core/src/main/java/org/hibernate/query/range/Range.java
=> fix two instances of the same typo

hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/EmbeddableMetaModelTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/Weight.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/WeightClass.java
https://hibernate.atlassian.net/browse/HHH-18819
Backport of https://github.com/hibernate/hibernate-orm/pull/9584
=> [6.6] HHH-18819 Error resolving persistent property of @MapperSuperclass if subtype @Embeddable used as @IdClass

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BasicProxyFactoryImpl.java, hibernate-core/src/test/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyBasicProxyFactoryTest.java
Basic proxies were being created with a shared interceptor.  As the interceptor is stateful, this lead to cross-thread data leakage and thus intermittently broken persistence. This mod creates an interceptor per proxy, preventing leaking of state.
(Originally submitted by [@bighenry](https://github.com/bighenry) for 5.6)
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.m …
=> HHH-13915 : Prevent state sharing in basic proxies.

hibernate-core/src/main/java/org/hibernate/cache/internal/CollectionCacheInvalidator.java, hibernate-core/src/main/java/org/hibernate/event/internal/ProxyVisitor.java, hibernate-core/src/test/java/org/hibernate/orm/test/cache/CollectionCacheEvictionComplexIdTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/array/PrimitiveByteArrayIdCollectionTest.java
https://hibernate.atlassian.net/browse/HHH-7180
=> HHH-7180 Test and fix wrong collection key equality comparisons

documentation/src/main/asciidoc/introduction/Entities.adoc, hibernate-core/src/main/java/org/hibernate/type/descriptor/WrapperOptions.java
=> add big WARNING to doc

ci/release/Jenkinsfile
This should be safer as these nodes are only used once.
Backport of https://github.com/hibernate/hibernate-orm/pull/9613.
=> [6.2] Use specific Jenkins nodes for releases

ci/release/Jenkinsfile, ci/snapshot-publish.Jenkinsfile
This should be safer as these nodes are only used once.
=> Use specific Jenkins nodes for releases

ci/release/Jenkinsfile, ci/snapshot-publish.Jenkinsfile
This should be safer as these nodes are only used once.
Backport of #9613.
=> [6.4] Use specific Jenkins nodes for releases

ci/release/Jenkinsfile, ci/snapshot-publish.Jenkinsfile
This should be safer as these nodes are only used once.
Backport of #9613.
=> [6.6] Use specific Jenkins nodes for releases

ci/release/Jenkinsfile
Backport of #9571 to 6.6
@beikov I was thinking we could merge this to 6.6 first, because on 6.6 it wouldn't be a complete disaster if my build conditions don't work and a release was triggered by mistake. Works for you?
=> [6.6] Allow Jenkins to parse the release Jenkinsfile before cancelling non-release triggers

hibernate-core/src/main/java/org/hibernate/dialect/H2DurationIntervalSecondJdbcType.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLIntervalSecondJdbcType.java, hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/ArgumentTypesValidator.java, hibernate-core/src/main/java/org/hibernate/type/CustomType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/DurationJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JdbcType.java, hibernate-core/src/main/java/org/hibernate/type/internal/UserTypeJavaTypeWrapper.java, hibernate-core/src/main/java/org/hibernate/type/internal/UserTypeJdbcTypeAdapter.java, hibernate-core/src/main/java/org/hibernate/usertype/UserType.java
https://hibernate.atlassian.net/browse/HHH-19035
=> HHH-19035 UserType.isComparable()

ci/release/Jenkinsfile
This reverts commit ffecd7d6ca9987533249703bb023bd72af902c5b.
This reverts PR #9617
See https://github.com/hibernate/hibernate-orm/pull/9571#issuecomment-2592706563
=> Revert "Allow Jenkins to parse the release Jenkinsfile before cancelling non-release triggers"

hibernate-core/src/main/java/org/hibernate/ScrollableResults.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentImpl.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractScrollableResults.java, hibernate-core/src/main/java/org/hibernate/internal/EmptyScrollableResults.java, hibernate-core/src/main/java/org/hibernate/internal/FetchingScrollableResultsImpl.java, hibernate-core/src/main/java/org/hibernate/internal/ScrollableResultsImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/ScrollableResultsIterator.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/ScrollableResultsImplementor.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeNonSelectQueryPlanImpl.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeSelectQueryPlanImpl.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/ResultSetMappingProcessor.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/AggregatedSelectQueryPlanImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/Initializer.java
=> Code cleanups

hibernate-core/src/main/java/org/hibernate/internal/util/collections/StandardStack.java
https://hibernate.atlassian.net/browse/HHH-19047
=> HHH-19047 Prevent GC nepotism from affecting data structures not explicitly cleaning up old elements

hibernate-core/src/main/java/org/hibernate/annotations/SQLSelect.java, hibernate-core/src/main/java/org/hibernate/annotations/Subselect.java, hibernate-core/src/main/java/org/hibernate/annotations/Synchronize.java, hibernate-core/src/main/java/org/hibernate/annotations/View.java
=> improve javadoc for @View, @Subselect, and @SQLSelect

docker_db.sh, hibernate-vector/src/main/java/org/hibernate/vector/PGVectorFunctionContributor.java, hibernate-vector/src/main/java/org/hibernate/vector/PGVectorTypeContributor.java, hibernate-vector/src/test/java/org/hibernate/vector/PGVectorTest.java
Extended the support for pgvector to work with the CockroachDB dialect. 
https://hibernate.atlassian.net/browse/HHH-19054
=> HHH-19054 - pgvector support for CockroachDB

docker_db.sh
Set TTL and retention times more aggressively to
minimize spurious test failures
This should help with the flaky tests  in CI
=> Tune CockroachDB configuration

.github/hibernate-github-bot.yml
This should add another check to PRs to verify that a user hasn't removed the "license text" part from the PR. 
I tested this a bit with Search and my bot-playground repositories. It should be working ok now, but if anyone notices some false-failures -- please let me know. 
=> Enable the check to verify that the license agreement is present in a PR description

documentation/src/main/asciidoc/repositories/Hibernate_Data_Repositories.adoc, documentation/src/main/asciidoc/repositories/Reactive.adoc
=> document reactive repositories

documentation/src/main/asciidoc/introduction/Tuning.adoc
=> mention Oracle defaultRowPrefetch in WARNING

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/sql/Template.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/DateTimeUtils.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/spi/DdlTypeRegistry.java
=> misc minor code changes

ci/quarkus.Jenkinsfile, hibernate-core/src/main/java/org/hibernate/cfg/Compatibility.java, hibernate-core/src/main/java/org/hibernate/cfg/Unsafe.java
https://hibernate.atlassian.net/browse/HHH-18545
=> Fix Quarkus CI not picking up the snapshot hibernate version

hibernate-core/src/main/java/org/hibernate/engine/internal/PersistenceContexts.java, hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/spi/PersistenceContext.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultEvictEventListener.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
=> fix a couple of warnings by making StatefulPersistenceContext package-private

hibernate-core/src/main/java/org/hibernate/boot/MetadataBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ToOneBinder.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingMetadataBuilderImplementor.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingMetadataBuildingOptions.java, hibernate-core/src/main/java/org/hibernate/boot/spi/InFlightMetadataCollector.java, hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataBuildingOptions.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/derivedidentities/e1/b/specjmapid/CustomerInventory.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/derivedidentities/e1/b/specjmapid/IdMapManyToOneSpecjTest.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java
https://hibernate.atlassian.net/browse/HHH-19018
=> HHH-19018 remove support for inferred @MapsId

hibernate-core/src/main/java/org/hibernate/annotations/OptimisticLock.java, hibernate-core/src/main/java/org/hibernate/annotations/OptimisticLocking.java
=> minor improvement to javadoc for @OptimisticLock

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java
https://hibernate.atlassian.net/browse/HHH-19069
=> HHH-19069 Call startLoading on entity sub-initializers only once

hibernate-core/src/main/java/org/hibernate/id/uuid/UuidVersion6Strategy.java, hibernate-core/src/main/java/org/hibernate/id/uuid/UuidVersion7Strategy.java, hibernate-graalvm/src/main/java/org/hibernate/graalvm/internal/GraalVMStaticFeature.java, hibernate-graalvm/src/main/java/org/hibernate/graalvm/internal/StaticClassLists.java, hibernate-graalvm/src/test/java/org/hibernate/graalvm/internal/StaticClassListsTest.java
inside the UuidVersion7Strategy constructor
https://hibernate.atlassian.net/browse/HHH-18974
=> HHH-18974 - initialize SecureRandom at runtime

migration-guide.adoc
=> migration guide updates for 7

hibernate-core/src/main/java/org/hibernate/boot/internal/TypeBeanInstanceProducer.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorBinder.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/ConnectionProviderInitiator.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/CdiBeanContainerBuilder.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/CdiBeanContainerDelayedAccessImpl.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/CdiBeanContainerExtendedAccessImpl.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/CdiBeanContainerImmediateAccessImpl.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/ContainerManagedLifecycleStrategy.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/JpaCompliantLifecycleStrategy.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/spi/AbstractCdiBeanContainer.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/spi/BeanContainer.java, hibernate-core/src/main/java/org/hibernate/resource/beans/internal/BeansMessageLogger.java, hibernate-core/src/main/java/org/hibernate/resource/beans/internal/FallbackBeanInstanceProducer.java, hibernate-core/src/main/java/org/hibernate/resource/beans/internal/Helper.java, hibernate-core/src/main/java/org/hibernate/resource/beans/internal/ManagedBeanRegistryImpl.java, hibernate-core/src/main/java/org/hibernate/resource/beans/spi/ManagedBeanRegistryInitiator.java, hibernate-core/src/main/java/org/hibernate/service/spi/ServiceException.java
also remove unnecessary use of reflection for creation of the CDI `BeanContainer`
https://hibernate.atlassian.net/browse/HHH-18982
=> HHH-18982 make BeanContainer loadable as a Java service

hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/CdiBeanContainerDelayedAccessImpl.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/CdiBeanContainerExtendedAccessImpl.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/ContainerManagedLifecycleStrategy.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/JpaCompliantLifecycleStrategy.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/spi/ContainedBean.java, hibernate-core/src/main/java/org/hibernate/resource/beans/container/spi/ContainedBeanImplementor.java, hibernate-core/src/main/java/org/hibernate/resource/beans/internal/ManagedBeanRegistryImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/connections/ConnectionProviderFromBeanContainerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/SimpleBeanContainer.java, hibernate-core/src/test/java/org/hibernate/orm/test/idgen/userdefined/UserDefinedGeneratorsTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/multitenancy/beancontainer/MultiTenantConnectionProviderFromBeanContainerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/multitenancy/beancontainer/TestBeanContainer.java
=> as suggested by TODO in code, make ContainedBean extend ManagedBean

hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/spi/PersistenceContext.java
In Hibernate Reactive, [ReactivePersistenceContextAdapter](https://github.com/hibernate/hibernate-reactive/blob/89f7cf20df9778fc4f1ced298ebead22d7c4ae00/hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/impl/ReactivePersistenceContextAdapter.java#L34) extends `StatefulPersistenceContext`.
But, [this change](https://github.com/hibernate/hibernate-orm/commit/1f87e47dfc429b662e0f7a06a575b90aa3d3b023?diff=unified#diff-b1b37f6d0ff0e2632cdd8194a9db6155e75b29cec62ffd03368e569868aea8feL92) makes the class package-private.
I've fixed the build in Hibernate Reactive buy moving the class to the same package, but is it possible to make it `protected` instead?
By the way, the current build using the ORM snapshots is here: [wip/3.0](https://github.com/hibernate/hibernate-reactive/tree/ …
=> Allow Hibernate Reactive to implement PersistenceContext

hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaIsolationDelegate.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/txn/JtaObtainConnectionExceptionTest.java
https://hibernate.atlassian.net/browse/HHH-18961
=> HHH-18961 JtaIsolationDelegate, obtaining connection : NPE when SQLExceptionConversionDelegate#convert returns null

hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/EmbeddableInheritanceHierarchyOrderTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/HierarchyOrderTest.java
Jira issue [HHH-18933](https://hibernate.atlassian.net/browse/HHH-18933)
Test classes used in PR [#9548](https://github.com/hibernate/hibernate-orm/pull/9548) showing that the isse has been resolved in 7.0
[HHH-18933]: https://hibernate.atlassian.net/browse/HHH-18933?atlOrigin=eyJpIjoiNWRk …
=> HHH-18933 showing the issue has been resolved

hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/annotations/AnnotationMetadataSourceProcessorImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/EmbeddableInheritanceHierarchyOrderTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/HierarchyOrderTest.java
Jira issue [HHH-18933](https://hibernate.atlassian.net/browse/HHH-18933)
Method `org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl#orderAndFillHierarchy` has not been properly ordering classes.
Fixing problem by adding method `org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl#orderHierarchy` and ordering classes before returning from `orderAndFillHierarchy`. Added method is equivalent to one that is (properly) ordering classes in main branch. …
=> HHH-18933 the ordering of the class declaration in persistence.xml seems to affect the metamodel

hibernate-core/src/main/java/org/hibernate/type/ComponentType.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/EmbeddableInheritanceReplaceTest.java
Jira issue [HHH-19079](https://hibernate.atlassian.net/browse/HHH-19079)
When method `org.hibernate.type.ComponentType#getPropertyValues(java.lang.Object)` is invoked with `null` parameter, number of discriminator columns should be added to number of properties
[HHH-19079]: …
=> HHH-19079 ComponentType.replace can cause ArrayIndexOutOfBoundsException when used with embeddable inheritance

hibernate-core/src/main/java/org/hibernate/type/ComponentType.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/EmbeddableInheritanceReplaceTest.java
Jira issue [HHH-19079](https://hibernate.atlassian.net/browse/HHH-19079)
Backport to 6.6
[HHH-19079]: https://hibernate.atlassian.net/browse/HHH-19079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Hhh 19079 backport 6.6

.mailmap
Mainly to help with the relicensing effort (identifying authors).
This data was extracted from publicly available information exposed by GitHub through its APIs. GitHub only exposes this data if users opt in.
=> Add more entries to .mailmap

hibernate-core/src/main/java/org/hibernate/internal/SessionFactorySettings.java, hibernate-core/src/test/java/org/hibernate/orm/test/internal/SessionFactoryNameSettingTest.java
https://hibernate.atlassian.net/browse/HHH-19072
=> HHH-19072 The hibernate.session_factory_name configuration property no longer works in Hibernate 7.0.0

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/CoreCacheProvider.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/CorePrefixFilter.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/CoreTypePool.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/ModelTypePool.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/OverridingClassFileLocator.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/SafeCacheProvider.java, hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/PersistenceUnitInfoDescriptor.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/enhance/EnhancingClassTransformerImpl.java
Draft solution for https://hibernate.atlassian.net/browse/HHH-18901
We don't have a good test for this, and I didn't yet link the commits to appropriate Jiras... but I'd consider it now stable enough for others to have a look.
Specifically targeting branch 6.6 for now as that's where we can reproduce it: I'll "forward port" this if you all like it. 
Thanks!
=> HHH-18901 AnnotationFormatError: Duplicate annotation for class: interface org.hibernate.bytecode.enhance.spi.EnhancementInfo 

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/set/UnionOfPartitionResultsTest.java
Backporting patch for Jira issue [HHH-18069](https://hibernate.atlassian.net/browse/HHH-18069) to `6.6`
This patch is also fixing Jira issue [HHH-18985](https://hibernate.atlassian.net/browse/HHH-18985)
[HHH-18069]: …
=> HHH-18069 NullPointerException when unioning partition results (backport to 6.6)

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/EnhancementContext.java, hibernate-core/src/main/java/org/hibernate/cfg/BytecodeSettings.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/enhance/EnhancingClassTransformerImpl.java
Version of https://hibernate.atlassian.net/browse/HHH-19050 targeting `main` branch
=> HHH-19050 Allow configuration of EntityManagerFactoryBuilderImpl to override the BytecodeProvider instance

.idea/.gitignore, .idea/icon.svg
it seems nice to have the hibernate icon displayed in IntelliJ toolbar
=> Add Hibernate project icon to IntelliJ

tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/embeddedid/EmbeddedIdTest.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/embeddedid/Thing.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/embeddedid/ThingRepo.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
https://hibernate.atlassian.net/browse/HHH-19107
=> HHH-19107 fix @EmbeddedId with CrudRepository

hibernate-core/src/main/java/org/hibernate/internal/NaturalIdMultiLoadAccessStandard.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/ExecutionContextWithSubselectFetchHandler.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderArrayParam.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderStandard.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoadingBatcher.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdExecutionContext.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiLoadLockingTest.java
https://hibernate.atlassian.net/browse/HHH-18992
=> HHH-18992 - Locking does not work with multiLoad

hibernate-envers/src/main/java/org/hibernate/envers/boot/internal/EnversIntegrator.java, hibernate-envers/src/main/java/org/hibernate/envers/internal/tools/ReflectionTools.java
Backport of https://github.com/hibernate/hibernate-orm/pull/9699 to 6.6.
https://hibernate.atlassian.net/browse/HHH-19104
=> HHH-19104 backport to 6.6; Envers - Reset ReflectionTools cache on disintegration

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java, hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessEnhancedImpl.java, hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyEnhancedImpl.java, hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyResolverStandardImpl.java, hibernate-core/src/main/java/org/hibernate/property/access/spi/EnhancedGetterFieldImpl.java, hibernate-core/src/main/java/org/hibernate/property/access/spi/GetterFieldImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/access/PropertyAccessMemberTest.java
https://hibernate.atlassian.net/browse/HHH-18928
When defaulting to `PROPERTY` access at the class-level by deducing it from annotations, we still need to access properties via fields: if we try to use the instrumented getter/setter methods of bytecode-enhanced entities in Hibernate internal code, we would trigger unnecessary/unwanted lazy property initializations, resulting in test failures. Note that this was the case even before https://github.com/hibernate/hibernate-orm/commit/90227d94bdda269bda5d91409045485f125ab778. 
I've implemented a workaround for this in the last commit, where we still report the correct `Member` for class-level `PROPERTY` access while actually using the field under the hood.
By submitting this pull request, I confirm that my contribution …
=> HHH-18928 Consider the default Access Type as per Spec section 2.3.1 and skip enhancement of properties accessor

hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/SharedSessionCreationOptions.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
remove unnecessary internal use of TransactionImplementor
=> minor refactoring

ci/jpa-3.2-tck.Jenkinsfile
And move Jenkins "input" steps outside of nodes/agents, so that we don't keep a node reserved while we're waiting for input. See best practice 6 in https://www.cloudbees.com/blog/top-10-best-practices-jenkins-pipeline-plugin
=> Add approval for TCK run

hibernate-core/src/main/java/org/hibernate/internal/NaturalIdMultiLoadAccessStandard.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiLoadLockingTest.java
- revert change made by commit 7292aacf5dfd2b43775fb1a9846a6ae4748732a4
- disable the MultiLoadLockTest for now (until https://hibernate.atlassian.net/browse/HHH-19115 is implemented)
https://hibernate.atlassian.net/browse/HHH-18992
=> HHH-18992 Revert a change

gradle/published-java-module.gradle, hibernate-platform/hibernate-platform.gradle, tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
Reverts changes from [this commit](https://github.com/hibernate/hibernate-orm/commit/57b9191c8c669fe278bb1ce69b338fccfe33d6cc) to the `release` task dependencies.
=> Revert publish task dependency on release changes

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/CodeTemplates.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImplConstants.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/EnhancerConstants.java, hibernate-core/src/main/java/org/hibernate/collection/spi/AbstractPersistentCollection.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentCollection.java, hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryContext.java, hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/spi/InstanceIdentity.java, hibernate-core/src/main/java/org/hibernate/engine/spi/ManagedEntity.java, hibernate-core/src/main/java/org/hibernate/event/internal/AbstractFlushingEventListener.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/util/collections/AbstractPagedArray.java, hibernate-core/src/main/java/org/hibernate/internal/util/collections/InstanceIdentityMap.java, hibernate-core/src/main/java/org/hibernate/internal/util/collections/InstanceIdentityStore.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/version/SimpleEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/basic/BasicSessionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/cache/ByteCodeEnhancedImmutableReferenceCacheTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/pc/InstanceIdentityTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/util/InstanceIdentityMapTest.java
https://hibernate.atlassian.net/browse/HHH-18326
This PR tries to address the performance impact of relying on identity hashes to track persistent instances. See the initial benchmark results for the current state here: https://github.com/hibernate/hibernate-orm-benchmark/pull/15.
This strategy is using a unique `int` (but could be `long` too) **instance id** that is assigned once an entity/collection is made persistent, and through that maps instances to a new collection (`InstanceIdentityMap`) that simply stores information in an array using the unique id as index. This allows us to avoid relying on identity hash code for:
- **immutable** bytecode-enhanced entities
- persistent collections
I will add more details on the proposed change along with benchmarks results of using the new …
=> HHH-18326 Inefficient identity hash code computation tracking persistent instances

hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java, hibernate-core/src/test/java/org/hibernate/orm/test/lazyonetoone/LazyOneToOneWithEntityGraphTest.java
A `ClassCastException` is thrown when trying to resolve instances without bytecode enhancement enabled under these preconditions:
- @OneToOne property on a model
- @JoinColumn to a unique key (other than @Id)
- @EntityGraph being applied with attributes that are not the one-to-one
**Related Change in Hibernate 6.6**
- https://github.com/hibernate/hibernate-orm/pull/8812
**Reproducer**
- https://github.com/hibernate/hibernate-orm/pull/9560 …
=> HHH-19017: Address ClassCastException for PersistentAttributeInterceptable

.github/dependabot.yml, .github/workflows/ci-report.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml
To match what we are doing for other projects.
Two actions that won't match the rules: 
- graalvm/setup-graalvm
- github/codeql-action
=> Use SHA instead of versions in GH actions / Limit which github actions are considered for updates

hibernate-core/src/main/java/org/hibernate/cfg/SchemaToolingSettings.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaCreatorImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/tool/schema/SkipDefaultImportFileExecutionTest.java
https://hibernate.atlassian.net/browse/HHH-19098
https://github.com/hibernate/hibernate-orm/pull/9692 backport for 6.6
=> HHH-19098 Disable implicit loading of the default import script

changelog.txt
Automation was buggy and closed the issue before the fix was even merged.
=> Remove incorrect mention of HHH-19098 in changelog

tooling/hibernate-maven-plugin/hibernate-maven-plugin.gradle
HHH-19122 - Leverage org.gradlex.maven-plugin-development for hibernate-maven-plugin
Fixes the ability to publish artifacts to maven-local.  
Does remove functional/integration testing of the plugin, however.  See https://hibernate.atlassian.net/browse/HHH-19123
=> HHH-19122 - Leverage org.gradlex.maven-plugin-development for hibernate-maven-plugin

ci/release/Jenkinsfile
getopts requires that options are the first arguments
cc @sebersole 
I'll backport to relevant branches as well, but won't open PRs for that if I can avoid it.
=> Fix passing of options to release scripts

hibernate-core/src/main/java/org/hibernate/annotations/ColumnDefault.java, hibernate-core/src/main/java/org/hibernate/annotations/Formula.java, hibernate-core/src/main/java/org/hibernate/annotations/Generated.java
=> add an example of @Generated @ColumnDefault to the javadoc

tooling/metamodel-generator/src/main/java/org/hibernate/processor/ClassWriter.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractCriteriaMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/TypeUtils.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/innerclass/InnerInterfaceTest.java
Jira issue [HHH-19091](https://hibernate.atlassian.net/browse/HHH-19091)
Changed implementation to generate metamodel classes from interfaces in a similar way as earlier from classes and records
[HHH-19091]: https://hibernate.atlassian.net/browse/HHH-19091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
=> HHH-19091Metamodel classes are not generated from inner interfaces

tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/fqcninquery/FqcnInQueryTest.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/fqcninquery/MyEntity.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/fqcninquery/MyRepository.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/ProcessorSessionFactory.java
Jira issue [HHH-19130](https://hibernate.atlassian.net/browse/HHH-19130)
Method `org.hibernate.processor.validation.ProcessorSessionFactory#isMatchingEntity` should accept either entity name or fully qualified class name when annotated with `@Entity` annotation
[HHH-19130]: …
=> HHH-19130 Metamodel generation failes when FQCN is used instead of entity name

hibernate-core/src/test/java/org/hibernate/orm/test/locking/JoinedInheritancePessimisticLockingTest.java
https://hibernate.atlassian.net/browse/HHH-7315
=> HHH-7315 Add test for locking with joined inheritance

gradle/published-java-module.gradle
=> Artifact signing (6.2)

hibernate-core/src/main/java/org/hibernate/boot/beanvalidation/TypeSafeActivator.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/beanvalidation/Address.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/beanvalidation/CustomNotNull.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/beanvalidation/CustomNotNullAndNotBlank.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/beanvalidation/CustomNotNullOrNotBlank.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/beanvalidation/CustomNull.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/beanvalidation/CustomNullAndNotBlank.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/beanvalidation/CustomNullOrNotBlank.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/beanvalidation/CustomNullOrPattern.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/beanvalidation/DDLTest.java
https://hibernate.atlassian.net/browse/HHH-18724
=> HHH-18724 Take constraint composition type into account when determining nullable state of a Column

hibernate-core/src/main/java/org/hibernate/type/descriptor/java/AbstractJavaType.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/idclass/CompositeIdClassTest.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/idclass/MyEntity.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/idclass/MyRepository.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockEntityPersister.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/ProcessorSessionFactory.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/idclass/CompositeIdClassTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/idclass/MyEntity.java
Jira issue [HHH-19134](https://hibernate.atlassian.net/browse/HHH-19134)
When entity class is annotated with `@IdClass`, property named `id` should be represented by composite containing all properties annotated with `@Id`
[HHH-19134]: …
=> HHH-19134 Hibernate processor - find by id fails for entity with composite identifier with @IdClass

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AbstractPluralAttribute.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmPluralValuedSimplePath.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmMemberOfPredicate.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/paths/PluralAttributeExpressionsTest.java
https://hibernate.atlassian.net/browse/HHH-19126
Backport of https://github.com/hibernate/hibernate-orm/pull/9730
=> HHH-19126 Plural valued paths should be collection-typed instead of element typed

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
and remove a hack that I believe is now obsolete
=> improve message for validation of Restriction parameter of repo method

hibernate-core/src/main/java/org/hibernate/NonUniqueObjectException.java, hibernate-core/src/main/java/org/hibernate/PropertyValueException.java, hibernate-core/src/main/java/org/hibernate/StaleObjectStateException.java, hibernate-core/src/main/java/org/hibernate/TransientPropertyValueException.java, hibernate-core/src/main/java/org/hibernate/UnresolvableObjectException.java, hibernate-core/src/main/java/org/hibernate/generator/internal/NaturalIdHelper.java, hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/naturalid/ValidationTests.java
=> Error messages

documentation/src/main/asciidoc/repositories/Repositories.adoc
Renaming AuthorBookRecord to AuthorBookSummary
The documentation uses a class name as example, called AuthorBookSummary, but later on there is a new class called AuthorBookRecord
I wonder if AuthorBookSummary should be the class name used in the record declaration and in the implementation. …
=> Changing Repository class name in example

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MySQLLegacyDialect.java
This fixes [HHH-19097](https://hibernate.atlassian.net/browse/HHH-19097) by implementing `stripsTrailingSpacesFromChar -> true` on `MySQLLegacyDialect`  just like it had been implemented on `MySQLDialect` in commit 633f1012e196e3adb25a2f9c637a422d54ab8fbe and as I commented here: https://github.com/hibernate/hibernate-orm/commit/633f1012e196e3adb25a2f9c637a422d54ab8fbe#r151987775
[HHH-19097]: https://hibernate.atlassian.net/browse/HHH-19097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> HHH-19097 Implemented MySQLLegacyDialect#stripsTrailingSpacesFromChar

hibernate-core/src/main/java/org/hibernate/type/EntityType.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/cid/NestedCompositeIdWithOrderedUpdatesTest.java
https://hibernate.atlassian.net/browse/HHH-19110
=> HHH-19110 - Update ordering with nested composite Ids

hibernate-core/src/main/java/org/hibernate/dialect/HANAServerConfiguration.java
This PR fixes [HHH-18946](https://hibernate.atlassian.net/browse/HHH-18946) (Startup issues with HANA in failover situations)
[HHH-18946]: https://hibernate.atlassian.net/browse/HHH-18946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HHH-18946 Fix startup issues with HANA in failover situations

hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/GetMultipleFromCacheTest.java
https://hibernate.atlassian.net/browse/HHH-19142
=> HHH-19142 StatelessSession.getMultiple() and second-level cache

hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiLoadLockingTest.java
Just as for Postgresql, the test should be skipped for CockroachDB. See the class comments.
=> Skip MultiLoadLockingTest for CockroachDB

hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/BasicFormatterImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/jdbc/util/BasicFormatterTest.java
During SQL formatting, it was discovered that the newline character was missing after a single-line comment (-- comment). This causes the formatted SQL to be incorrect .
```sql
CREATE TRIGGER before_employee_delete
BEFORE DELETE ON employees
FOR EACH ROW
BEGIN
-- abcd
IF EXISTS (SELECT 1 FROM orders WHERE employee_id = OLD.id) THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'Cannot delete employee because they have related orders';
END IF;
END;
```
Formatted Result Before the Fix:
Formatted Result After the Fix: …
=> Fix SQL formatting bug where a newline is missing after a single-line comment

documentation/src/main/asciidoc/userguide/chapters/domain/associations.adoc, hibernate-core/src/main/java/org/hibernate/query/hql/internal/QualifiedJoinPathConsumer.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmTreePrinter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmAttributeJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmFkExpression.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmSingularJoin.java, hibernate-core/src/test/java/org/hibernate/orm/test/associations/NotFoundTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/LeftJoinNullnessPredicateQueryTest.java
https://hibernate.atlassian.net/browse/HHH-19116
=> HHH-19116 Error when using fk() function on left joined many-to-one association and is null predicate

hibernate-core/src/main/java/org/hibernate/collection/spi/AbstractPersistentCollection.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentArrayHolder.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentCollection.java
for the benefit of Hibernate Reactive, which currently casts to AbstractPersistentCollection
=> promote getSession() up to PersistentCollection

hibernate-core/src/main/java/org/hibernate/engine/internal/VersionLogger.java, hibernate-core/src/main/java/org/hibernate/engine/internal/Versioning.java
=> introduce VersionLogger

hibernate-core/src/main/java/org/hibernate/SharedSessionContract.java
https://hibernate.atlassian.net/browse/HHH-19171
=> HHH-19171 add SharedSessionContract.inTransaction

hibernate-core/src/main/java/org/hibernate/jpa/internal/PersistenceUnitUtilImpl.java
These messages were added in HHH-7454 and HHH-11426.
- I'm pretty sure that the claim made in HHH-7454 is simply incorrect, whereas the message added in
- On the other hand, HHH-11426 is warning about an error that might, but probably won't occur. …
=> get rid of extremely useless log messages

hibernate-core/src/main/java/org/hibernate/Hibernate.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/util/PersistenceUtilHelper.java
=> improvements to Hibernate class, cleanups in PersistenceUtilHelper

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/customsql/CustomSqlRestrictionOverridesTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/where/annotations/MappedSuperclassTest.java
I have several entities with common super class SoftDeleteSupport marked with @MappedSuperclass annotation. It have boolean rmv; field.
Currently I have to put @SQLRestriction in each entity.
I propose to support @SQLRestriction on classes marked with @MappedSuperclass t reduce code duplication.
This PR is intends to fix HHH-18723
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONT …
=> HHH-18723 Support @SQLRestriction in class marked as @MappedSuperclass

hibernate-core/src/main/java/org/hibernate/MultiIdentifierLoadAccess.java, hibernate-core/src/main/java/org/hibernate/NaturalIdMultiLoadAccess.java
=> Very minor javadoc change

hibernate-core/src/test/java/org/hibernate/orm/test/jpa/orphan/onetoone/OneToOneLazyOrphanRemovalEmbeddedTest.java
Hey @mbladel 
I was looking at some tests that failed in the other PR and noticed that this one fails on sybase with:
```
OneToOneLazyOrphanRemovalEmbeddedTest > initializationError FAILED
org.hibernate.exception.GenericJDBCException: could not execute statement [Incorrect syntax near the keyword 'count'.
] [insert into OwnerEntity (child_id,count,id) values (?,?,?)]
at app//org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:61)
```
https://github.com/hibernate/hibernate-orm/actions/runs/13576066171/job/37952476819?pr=9822
IDK if the tests should just quote the keywords or what the general approach is, but since... I suppose this test wasn't really about keywords, maybe let's just rename the property/column and make the build happier …
=> HHH-19185 Follow up on test update from 44918d69228f1ac8dd77f512d099d859276e1286

hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/EntityGraphUsingFetchGraphTest.java
HHH-19181 - Remove LGPL-only contributions - Batch 3
(HHH-13233) Remove commit d8faee0d2c156e48a5d160385adeb51e49255c22 by David Steinkopff <david.steinkopff@x-root.de>
=> HHH-19181 - Remove LGPL-only contributions - Batch 3

gradle/published-java-module.gradle, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/InlineDirtyCheckingHandler.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/dirty/DirtyTrackingIdTest.java
https://hibernate.atlassian.net/browse/HHH-19206
=> HHH-19206 Skip dirty tracking for embedded id fields 

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/database/qualfiedTableNaming/DefaultCatalogAndSchemaTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/secondarytable/SecondaryTableTest.java
https://hibernate.atlassian.net/browse/HHH-19219
=> HHH-19219 Fix for Informix Catalog and schema support

hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
https://hibernate.atlassian.net/browse/HHH-18638
=> HHH-18638 remove support for old crockroachDB dialect older than 23.1

docker_db.sh, edb/edb17.Dockerfile, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/PostgreSQLUnnestFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/json/JsonTableFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/json/PostgreSQLJsonValueFunction.java
https://hibernate.atlassian.net/browse/HHH-18886
=> HHH-18886 Upgrade PostgreSQL and EDB testing to version 17

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/embeddable/InheritedPropertyTest.java
Jira issue [HHH-19195](https://hibernate.atlassian.net/browse/HHH-19195)
To preserve hierarchical ordering of discriminator values `LinkedHashMap` should be used instead of `TreeMap`
[HHH-19195]: https://hibernate.atlassian.net/browse/HHH-19195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
=> HHH-19195 Embeddable inheritance: discriminator values are not hierarchically ordered

hibernate-core/src/main/java/org/hibernate/query/internal/BindingTypeHelper.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/TemporalJavaType.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/DateTimeParameterTest.java
https://hibernate.atlassian.net/browse/HHH-17151
Backport of https://github.com/hibernate/hibernate-orm/pull/9443
=> [6.2] HHH-17151 NPE when binding null parameter in native query with explicit TemporalType

hibernate-core/src/main/java/org/hibernate/SharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/cfg/BatchSettings.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
note that this feature was most likely introduced in HHH-10431 by accident!
=> provide even better documentation of the effect of JDBC batching in SS

hibernate-core/src/main/java/org/hibernate/action/internal/AbstractEntityInsertAction.java, hibernate-core/src/main/java/org/hibernate/collection/spi/AbstractPersistentCollection.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentCollection.java, hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CollectionEntry.java, hibernate-core/src/main/java/org/hibernate/event/internal/AbstractFlushingEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/WrapVisitor.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderSubSelectFetch.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/type/CollectionType.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/NonPkCompositeJoinColumnCollectionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/NonPkJoinColumnCollectionTest.java
(cherry picked from commit 1f08501d80927659b759cb42faac31ccbd9189b4)
upstream PR: https://github.com/hibernate/hibernate-orm/pull/8700
issue: https://hibernate.atlassian.net/browse/HHH-18229
[Backport HHH-18229 fix to downstream 6.2 branch]
=> HHH-18229 Handle null owner key for collections

hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetoone/JoinColumnTest.java
https://hibernate.atlassian.net/browse/HHH-17420
https://issues.redhat.com/browse/JBEAP-29294
upstream PR: https://github.com/hibernate/hibernate-orm/pull/7728
[Backport HHH-17420 fix to downstream 6.2 branch]
=> [HHH-17420][JBEAP-29294] JoinColumn throws an  AnnotationException

hibernate-core/src/main/java/org/hibernate/boot/beanvalidation/BeanValidationEventListener.java, hibernate-core/src/main/java/org/hibernate/boot/beanvalidation/TypeSafeActivator.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/beanvalidation/CollectionActionsValidationTest.java
https://hibernate.atlassian.net/browse/HHH-19232
=> HHH-19232 BeanValidationEventListener not called if only associated collection is updated via getter

hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/oracle/OracleSDOFunctionDescriptors.java, hibernate-spatial/src/test/java/org/hibernate/spatial/dialect/oracle/hhh19227/TestSDODescriptorBug.java
=> HHH-19227 - Fix OracleSDOFunctionDescriptors

tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/embeddedid/EmbeddedIdTest.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/embeddedid/Thing.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/embeddedid/ThingRepo.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
(cherry picked from commit 05677ebbc39ed45c1c0a2562bd46812f0ded80ec)
Basically a backport to 6.6 of HHH-19107
=> [6.6 Backport] HHH-19107 fix @EmbeddedId with CrudRepository

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/SelectUnknownEnumLiteralTest.java
Jira issue  [HHH-18894](https://hibernate.atlassian.net/browse/HHH-18894)
Backporting changes from PR [#9342](https://github.com/hibernate/hibernate-orm/pull/9342)
[HHH-18894]: https://hibernate.atlassian.net/browse/HHH-18894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
=> HHH-18894 [6.6 backport] Hibernate 6.6 enum literal is considered field literal instead

changelog.txt
Please don't merge, we don't want a release just for this... Let's wait until we have other, more useful things merged into 6.6.
See https://hibernate.zulipchat.com/#narrow/channel/132094-hibernate-orm-dev/topic/Release.20automation.20and.20changelog
=> Remove issues added to the changelog by mistake

tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java
presence of JTA was not detected due to misspelling of package name
https://hibernate.atlassian.net/browse/HHH-19109
=> HHH-19109 fix use of @TransactionScoped by repository

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/EntityGraphAndJoinFetchTest.java
https://hibernate.atlassian.net/browse/HHH-19246
=> HHH-19246 Traverse entity graph also for explicit join fetches

tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Bookshop.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/ClassWriter.java
(cherry-picked from commit 225d9b3b0befdf348b6089e8eb9639df06c49711)
Basically a backport to 6.6 of HHH-19106
=> [6.6 Backport] HHH-19106 deconstruct inherited annotations before printing them

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/MetaAttributeGenerationVisitor.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/hhh18858/ArrayTest.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/hhh18858/Competitor.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/hhh18858/Contest.java
Jira issue [HHH-18858](https://hibernate.atlassian.net/browse/HHH-18858)
Backporting changes from [#9360](https://github.com/hibernate/hibernate-orm/pull/9360) to 6.6
[HHH-18858]: https://hibernate.atlassian.net/browse/HHH-18858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
=> HHH-18858 [6.6] array fields and static metamodel

hibernate-core/src/main/java/org/hibernate/type/descriptor/java/JdbcTimestampJavaType.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/array/MySqlArrayOfTimestampsTest.java
Jira issue [HHH-18881](https://hibernate.atlassian.net/browse/HHH-18881)
Backporting changes from PR [#9327](https://github.com/hibernate/hibernate-orm/pull/9327)
[HHH-18881]: https://hibernate.atlassian.net/browse/HHH-18881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
=> HHH-18881 [6.6 backport] In MySQL (and MariaDB), array of dates are not converted correctly

hibernate-core/src/main/java/org/hibernate/cfg/JdbcSettings.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/StatementPreparerImpl.java
https://hibernate.atlassian.net/browse/HHH-19265
=> HHH-19265 deprecate hibernate.jdbc.use_scrollable_resultset

hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/jpa/HibernateHints.java, hibernate-core/src/main/java/org/hibernate/procedure/ProcedureCall.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java, hibernate-core/src/main/java/org/hibernate/procedure/spi/ProcedureCallImplementor.java, hibernate-core/src/main/java/org/hibernate/query/CommonQueryContract.java, hibernate-core/src/main/java/org/hibernate/query/MutationQuery.java, hibernate-core/src/main/java/org/hibernate/query/NativeQuery.java, hibernate-core/src/main/java/org/hibernate/query/Query.java, hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/hql/spi/SqmQueryImplementor.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractCommonQueryContract.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/SqmQuery.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sql/spi/NativeQueryImplementor.java, hibernate-core/src/main/java/org/hibernate/query/sqm/SqmSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/spi/DelegatingSqmSelectionQueryImplementor.java
Includes: https://hibernate.atlassian.net/browse/HHH-19271
=> various minor improvements around Query hierarchy

hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/internal/MutationExecutorStandard.java
These changes are needed by Hibernate reactive, see https://github.com/hibernate/hibernate-reactive/pull/2141
=> Add methods to MutationExecutorStandard for Hibernate reactive

hibernate-core/src/main/java/org/hibernate/internal/SessionFactorySettings.java
https://hibernate.atlassian.net/browse/HHH-19263
I'm seeing a unit test failure with WildFly Preview that disables the Hibernate ORM 2-phase bootstrap by configuring a test with `<property name="wildfly.jpa.twophasebootstrap" value="false"/>` (https://github.com/wildfly/wildfly/blob/main/testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/injection/support/jpa/persistence.xml#L18) which causes the test to deploy before the JNDI name space has been configured.  
Clearly the JNDI name space is an internal detail of WildFly but I do get a test deployment failure as a result.  If this pull request is wrong and the https://hibernate.atlassian.net/browse/HHH-19263 issue is also wrong, I'll look into other WildFly side alternatives to ensure that applications do not deploy …
=> HHH-19263 Do not bind to JNDI if hibernate.session_factory_name_is_jndi is set to false

hibernate-envers/src/main/java/org/hibernate/envers/event/spi/EnversPostUpdateEventListenerImpl.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/lazy/LazyFieldsTest.java
https://hibernate.atlassian.net/browse/HHH-19220
=> HHH-19220 ClassCastException: class org.hibernate.bytecode.enhance.spi.LazyPropertyInitializer$1 cannot be cast to class java.lang.String

hibernate-core/src/main/java/org/hibernate/boot/beanvalidation/BeanValidationEventListener.java, hibernate-core/src/main/java/org/hibernate/boot/beanvalidation/HibernateTraversableResolver.java, hibernate-core/src/main/java/org/hibernate/boot/beanvalidation/TypeSafeActivator.java
Hey @gavinking , @beikov 
Since you've been talking about the validator in the other PR 😄 it got me interested. 
The fact that we recreate the validator on each validate call feels a bit redundant, so I've started looking into it. And this PR is where I got so far.
It would be nice if we wouldn't need to have that `traversableResolver.addPersisterIfNecessary( persister, sessionFactory );` I've added. But to get rid of it, we need to have access to the built SF (not the one being built that we can get our hands on right now from the integrator). Would it make sense to add some `Integrator#postintegrate(Sf sf... )` method that is called at the very end of the SF constructor, then eagerly build the association map? 
Or am I missing something here 😄  
By submitting this …
=> HHH-19205 Do not recreate the validator on each BeanValidationEventListener#validate call

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractMultiNaturalIdLoader.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoaderArrayParam.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoaderInPredicate.java, hibernate-core/src/main/java/org/hibernate/loader/internal/LoadAccessContext.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiIdEntityLoadTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiLoadLockingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiNaturalIdLoadTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/naturalid/CompoundNaturalIdTests.java
https://hibernate.atlassian.net/browse/HHH-19115
=> HHH-19115 - implement ordered multiloading with natural ids

docker_db.sh
(to avoid fake error messages on slower machines)
=> Allow a little more timeout margin for mysql startup

hibernate-core/src/test/java/org/hibernate/orm/test/annotations/basic/ImpliciteOptionalBooleanBasicTest.java
Test for reproduce.
@Basic#optional not implicit
https://hibernate.atlassian.net/browse/HHH-19279
=> HHH-19279 : @Basic#optional not implicit

hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/basic/ImplicitOptionalBooleanBasicTest.java
as specified by Javadoc of Basic.optional()
https://hibernate.atlassian.net/browse/HHH-19279
=> HHH-19279 @Basic annotation should not mark primitive fields as optional

hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-jcache/src/test/java/org/hibernate/orm/test/caching/GetManagedEntitiesTest.java
https://hibernate.atlassian.net/browse/HHH-18008
=> HHH-18008 add Session.getManagedEntities()

hibernate-core/src/main/java/org/hibernate/engine/spi/EntityKey.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/main/java/org/hibernate/pretty/MessageHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/BatchFetchProxyTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/fetching/BatchFetchingTest.java
=> three minor things

hibernate-core/src/main/java/org/hibernate/cfg/SchemaToolingSettings.java, hibernate-core/src/main/java/org/hibernate/relational/SchemaManager.java, hibernate-core/src/main/java/org/hibernate/relational/internal/SchemaManagerImpl.java, hibernate-core/src/main/java/org/hibernate/tool/schema/Action.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/AbstractSchemaPopulator.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/HibernateSchemaManagementTool.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaCreatorImpl.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaPopulatorImpl.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaTruncatorImpl.java, hibernate-core/src/main/java/org/hibernate/tool/schema/spi/SchemaManagementTool.java, hibernate-core/src/main/java/org/hibernate/tool/schema/spi/SchemaManagementToolCoordinator.java, hibernate-core/src/main/java/org/hibernate/tool/schema/spi/SchemaPopulator.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemamanager/SchemaManagerLoadScriptTest.java, migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-19103
=> HHH-19103 add SchemaManager.populate()

hibernate-core/src/main/java/org/hibernate/query/criteria/JpaExpression.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/FullyQualifiedReflectivePathTerminal.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/AbstractSqmExpression.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmExpression.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmFieldLiteral.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSubQuery.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/main/java/org/hibernate/tool/schema/Action.java
=> three more minor things

documentation/src/main/asciidoc/introduction/Introduction.adoc, documentation/src/main/asciidoc/introduction/Preface.adoc, documentation/src/main/asciidoc/introduction/Processor.adoc
=> add more links to the Short Guide

documentation/src/main/asciidoc/introduction/Introduction.adoc
=> clarify the intention with respect to Active Record

hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentImpl.java
A minor defect in that the `Dialect#getSqlAstTranslatorFactory()` is called twice unnecessarily, even though in most of casees it is not a big deal
=> avoid duplicated SqlAstTranslatorFactory creation in JdbcEnvironmentImpl

hibernate-core/hibernate-core.gradle, hibernate-core/src/main/java/org/hibernate/annotations/processing/Find.java, hibernate-core/src/main/java/org/hibernate/annotations/processing/HQL.java, hibernate-core/src/main/java/org/hibernate/dialect/hint/package-info.java, hibernate-core/src/main/java/org/hibernate/mapping/package-info.java, hibernate-core/src/main/java/org/hibernate/query/range/package-info.java, hibernate-core/src/main/java/org/hibernate/query/restriction/package-info.java, hibernate-core/src/main/java/org/hibernate/tuple/package-info.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/package-info.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/spi/package-info.java
=> Javadoc cleanup

hibernate-core/src/main/java/org/hibernate/tool/schema/spi/SchemaManagementToolCoordinator.java
https://hibernate.atlassian.net/browse/HHH-19103
or was it maybe on purpose to let the populator run after any other action ? 🙈 
=> HHH-19103 Add missing break within truncate action

README.adoc
=> Update readme icons to match what we do in other repositories

hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureParameterMetadataImpl.java, hibernate-core/src/main/java/org/hibernate/query/CommonQueryContract.java, hibernate-core/src/main/java/org/hibernate/query/ParameterMetadata.java, hibernate-core/src/main/java/org/hibernate/query/Query.java, hibernate-core/src/main/java/org/hibernate/query/internal/ParameterMetadataImpl.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractCommonQueryContract.java
and add getParameters() to ParameterMetadata
(this is going to be useful in Hibernate Reactive)
=> pull getParameterMetadata() up to CommonQueryContract

hibernate-core/src/main/java/org/hibernate/cfg/QuerySettings.java
Adapts the javadoc of `QuerySettings.QUERY_PLAN_CACHE_ENABLED` as it doesn't reflect how it is used in `org.hibernate.query.internal.QueryEngineImpl.buildInterpretationCache`.
https://hibernate.atlassian.net/browse/HHH-19208
=> HHH-19208 Adapt javadoc of QuerySettings.QUERY_PLAN_CACHE_ENABLED

tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/selectenumproperty/Topic.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/selectenumproperty/TopicData.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/selectenumproperty/TopicRepository.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/selectenumproperty/TopicStatus.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/selectenumproperty/TopicTypeEnumTest.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
Jira issue [HHH-18920](https://hibernate.atlassian.net/browse/HHH-18920)
Backporting changes from PR[#9385](https://github.com/hibernate/hibernate-orm/pull/9385) to 6.6
[HHH-18920]: https://hibernate.atlassian.net/browse/HHH-18920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
=> HHH-18920 [6.6 backport] Enum parameters in Jakarta Data repository method return type constructor are not properly matched 

hibernate-core/src/main/java/org/hibernate/query/ParameterMetadata.java
=> some polish to the javadoc for ParameterMetadata

Jenkinsfile, nightly.Jenkinsfile
=> HIB-140 Switch to access keys for develocity.commonhaus.dev

hibernate-core/src/main/java/org/hibernate/query/spi/AbstractCommonQueryContract.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/SelectCaseWhenNullLiteralTest.java
https://hibernate.atlassian.net/browse/HHH-19291
=> Expressions.nullExpresion() in querydsl result in NPE in SqmExpressible with named parameters

hibernate-core/src/main/java/org/hibernate/StatelessSession.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/main/java/org/hibernate/query/QueryProducer.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/fetchprofile/NewGraphTest.java
…instead of a result class.
https://hibernate.atlassian.net/browse/HHH-19296
https://hibernate.atlassian.net/browse/HHH-19298
=> HHH-19296 overload createSelectionQuery() to accept an EntityGraph

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/access/HierarchyPropertyAccessTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/access/UnsupportedEnhancementStrategyTest.java
https://hibernate.atlassian.net/browse/HHH-19059
=> HHH-19059 Bytecode enhancement fails when inherited fields are mapped using property access in subclass

hibernate-core/src/main/java/org/hibernate/query/Query.java, hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/spi/DelegatingSqmSelectionQueryImplementor.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/fetchprofile/NewGraphTest.java
https://hibernate.atlassian.net/browse/HHH-19096
=> HHH-19096 Adjust `SelectionQuery#setEntityGraph(..)` to accept entity graphs of supertypes

hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java, hibernate-core/src/main/java/org/hibernate/exception/ConstraintViolationException.java, hibernate-core/src/main/java/org/hibernate/exception/internal/SQLStateConversionDelegate.java
Partly inspired by #9788 9788.
=> HHH-19300 do a better job of interpreting constraint violations

documentation/src/main/asciidoc/repositories/Repositories.adoc
=> remove unnecessary @Pattern annotation in doc code examples

hibernate-core/src/main/java/org/hibernate/dialect/HANADialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/constraint/ConstraintInterpretationTest2.java
=> HHH-19300 constraint name extraction for HANA

hibernate-core/src/main/java/org/hibernate/exception/ConstraintViolationException.java
=> nice javadoc for ConstraintViolationException

tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/innerclass/InnerRepositoryTest.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
Jira issue [HHH-19301](https://hibernate.atlassian.net/browse/HHH-19301)
Fully qualified name should be imported for inner (static) Jakarta Data repository interface
[HHH-19301]: https://hibernate.atlassian.net/browse/HHH-19301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …
=> HHH-19301 Must import FQCN when generating metamodel class for inner Jakarta Data repository interface

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacyDialect.java, hibernate-core/src/main/java/org/hibernate/AssertionFailure.java, hibernate-core/src/main/java/org/hibernate/CallbackException.java, hibernate-core/src/main/java/org/hibernate/Interceptor.java, hibernate-core/src/main/java/org/hibernate/LazyInitializationException.java, hibernate-core/src/main/java/org/hibernate/NonUniqueResultException.java, hibernate-core/src/main/java/org/hibernate/PropertySetterAccessException.java, hibernate-core/src/main/java/org/hibernate/QueryTimeoutException.java, hibernate-core/src/main/java/org/hibernate/UnknownEntityTypeException.java, hibernate-core/src/main/java/org/hibernate/boot/jaxb/internal/FileXmlSource.java, hibernate-core/src/main/java/org/hibernate/boot/jaxb/internal/InputStreamXmlSource.java, hibernate-core/src/main/java/org/hibernate/boot/jaxb/internal/UrlXmlSource.java, hibernate-core/src/main/java/org/hibernate/boot/jaxb/spi/XmlSource.java, hibernate-core/src/main/java/org/hibernate/boot/spi/XmlMappingBinderAccess.java, hibernate-core/src/main/java/org/hibernate/exception/LockTimeoutException.java
=> miscellaneous improvements

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CockroachLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/NonUniqueResultException.java, hibernate-core/src/main/java/org/hibernate/PessimisticLockException.java, hibernate-core/src/main/java/org/hibernate/QueryTimeoutException.java, hibernate-core/src/main/java/org/hibernate/StaleStateException.java, hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/lock/OptimisticEntityLockException.java, hibernate-core/src/main/java/org/hibernate/dialect/lock/PessimisticEntityLockException.java, hibernate-core/src/main/java/org/hibernate/exception/LockAcquisitionException.java, hibernate-core/src/main/java/org/hibernate/exception/LockTimeoutException.java, hibernate-core/src/main/java/org/hibernate/exception/SnapshotIsolationException.java, hibernate-core/src/main/java/org/hibernate/exception/internal/SQLStateConversionDelegate.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/internal/ExceptionConverterImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchUpdateAndVersionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/unit/CockroachDialectVersionTest.java, migration-guide.adoc
=> cleanups around QueryTimeoutException and LockTimeoutException

hibernate-core/src/main/java/org/hibernate/exception/LockAcquisitionException.java, hibernate-core/src/main/java/org/hibernate/exception/LockTimeoutException.java
=> add an @apiNote to LockAcquisitionException and LockTimeoutException

hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java
I added some tests in Hibernate Reactive and realized that I need a couple of extra changes to close 
https://hibernate.atlassian.net/browse/HHH-19288
These should be the last changes I need.
Previous PR: https://github.com/hibernate/hibernate-orm/pull/9871
Related to this Hibernate Reactive issue: https://github.com/hibernate/hibernate-reactive/issues/2129 …
=> More scope changes in JdbcEnvironmentInitiator

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
=> several extremely trivial code cleanups in AbstractEntityPersister

hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java
Backports [HHH-19267](https://hibernate.atlassian.net/browse/HHH-19267)
And [HHH-19288](https://hibernate.atlassian.net/browse/HHH-19288)
[HHH-19267]: https://hibernate.atlassian.net/browse/HHH-19267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
=> Backport changes for Reactive for 6.6: Make it possible to extends the JdbcEnvironmentInitiator

hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/boot/BootFailureTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/boot/Event.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/boot/EventId.java, hibernate-core/src/test/resources/org/hibernate/orm/test/jpa/boot/META-INF/persistence.xml
https://hibernate.atlassian.net/browse/HHH-19307
=> HHH-19307 - NPE when entity class missing from persistence.xml is id of another entity

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/hqlsql/Books.java
this would have saved my ass on Quarkus Insights
=> produce error for a Sort parameter on a repo method which returns a projection

ci/release/Jenkinsfile
=> Backport to 6.6: Test the ci-commiter before checking the release type (manual/automatic)

hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/criteria/internal/NamedCriteriaQueryMementoImpl.java, hibernate-core/src/main/java/org/hibernate/query/named/NameableQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/SimpleHqlInterpretationImpl.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/SqmSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/AbstractSqmSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/main/java/org/hibernate/query/sqm/spi/DelegatingSqmSelectionQueryImplementor.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/AbstractSqmParameter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectStatement.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
some refactoring in Query hierarchy
=> promote getTupleTransformer() and getResultListTransformer() to SelectionQuery

hibernate-core/src/main/java/org/hibernate/action/internal/EntityDeleteAction.java, hibernate-core/src/main/java/org/hibernate/generator/OnExecutionGenerator.java, hibernate-core/src/main/java/org/hibernate/generator/values/internal/GeneratedValuesHelper.java, hibernate-core/src/main/java/org/hibernate/id/IdentityGenerator.java, hibernate-core/src/main/java/org/hibernate/id/SelectGenerator.java, hibernate-core/src/main/java/org/hibernate/internal/NaturalIdHelper.java, hibernate-core/src/main/java/org/hibernate/internal/NaturalIdMultiLoadAccessStandard.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractMultiNaturalIdLoader.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoaderArrayParam.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoaderInPredicate.java, hibernate-core/src/main/java/org/hibernate/loader/internal/BaseNaturalIdLoadAccessImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiLoadLockingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiNaturalIdLoadTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/naturalid/immutableentity/ImmutableEntityNaturalIdTest.java
https://hibernate.atlassian.net/browse/HHH-19248
=> HHH-19248 Return of deleted entities doesn't work with naturalid multiloading

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractMultiIdEntityLoader.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractMultiNaturalIdLoader.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderArrayParam.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderInPredicate.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoaderArrayParam.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoaderInPredicate.java
=> reorganize code in AbstractMultiNaturalIdLoader and AbstractMultiIdEntityLoader

hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractEntityBatchLoader.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractMultiIdEntityLoader.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractMultiNaturalIdLoader.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractNaturalIdLoader.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/EntityBatchLoaderArrayParam.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/EntityBatchLoaderInPredicate.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/EntityConcreteTypeLoader.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderHelper.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderArrayParam.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdEntityLoaderInPredicate.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoaderArrayParam.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoaderInPredicate.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoadingBatcher.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderProvidedQueryImpl.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderStandardImpl.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderSupport.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdLoadPlan.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleUniqueKeyEntityLoaderStandard.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/StandardBatchLoaderFactory.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/CallbackImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/LoadPlanBuilderTest.java
=> more cleanups to code in loader.ast.internal package

hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/ArgumentTypesValidator.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
https://hibernate.atlassian.net/browse/HHH-19334
=> HHH-19334 fix CCE when tuple passed to HQL position() function

hibernate-core/src/main/java/org/hibernate/boot/model/NamedGraphCreatorJpa.java, hibernate-core/src/main/java/org/hibernate/boot/model/NamedGraphCreatorParsed.java, hibernate-core/src/main/java/org/hibernate/graph/internal/parse/GraphParsing.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/util/StringHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/named/multiple/NamedEntityGraphsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/named/parsed/PackageLevelTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/transaction/FlushAndTransactionTest.java
=> Some fixes for JPA TCK failures

hibernate-core/src/main/java/org/hibernate/query/CommonQueryContract.java, hibernate-core/src/main/java/org/hibernate/query/TypedParameterValue.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractCommonQueryContract.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/TypedValueParametersTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/procedure/StoredProcedureParameterTypeTest.java
Also add static factory methods which allow type arg inference without the silly diamond.
https://hibernate.atlassian.net/browse/HHH-19340
=> HHH-19340 Make TypedParameterValue a record

hibernate-core/src/main/java/org/hibernate/boot/model/IdentifierGeneratorDefinition.java, hibernate-core/src/main/java/org/hibernate/boot/model/TypeDefinitionRegistryStandardImpl.java, hibernate-core/src/main/java/org/hibernate/engine/config/spi/StandardConverters.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/Size.java
=> two very small things

hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuildingContextRootImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/TypeDefinitionRegistryStandardImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/NamedEntityGraphDefinition.java, hibernate-core/src/main/java/org/hibernate/boot/model/TypeDefinitionRegistryStandardImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotationBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/NamedGraphCreatorJpa.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/NamedGraphCreatorParsed.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/annotations/AnnotationMetadataSourceProcessorImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/MappingDocument.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/InjectionHelper.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java, hibernate-testing/src/main/java/org/hibernate/testing/boot/MetadataBuildingContextTestingImpl.java
some of the exposed stuff is internal-only
=> clean up the public API of org.hibernate.boot

docker_db.sh, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/identifier/NaiveEqualsHashCodeEntityTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/identifier/NaturalIdEqualsHashCodeEntityTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/identifier/SimpleEntityTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaOrderedSetAggregateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/OrderedSetAggregateTest.java, settings.gradle
The changes is about upgrading mysal testing version to 9.2
https://hibernate.atlassian.net/browse/HHH-19228
=> HHH-19228 upgrade mysql testing version to 9.2

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java
=> Avoid non-functioning TIMESTAMP_WITH_TIMEZONE type code on sybase

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/insert/AbstractSqmInsertStatement.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/insert/SqmConflictClause.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/insert/SqmInsertSelectStatement.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/insert/SqmInsertValuesStatement.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/InsertConflictWithCriteriaCopyTreeEnabledTests.java
https://hibernate.atlassian.net/browse/HHH-19314
=> HHH-19314 StackOverflowException when using onConflict with createCriteriaInsertValues and createCriteriaInsertSelect

ci/release/Jenkinsfile
=> Backport to 6.4: Test the ci-commiter before checking the release type (manual/automatic)

ci/release/Jenkinsfile
=> Backport to 6.2: Test the ci-commiter before checking the release type (manual/automatic)

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/EntityGraphAndJoinTest.java
https://hibernate.atlassian.net/browse/HHH-17629
=> HHH-17629 Criteria and Entity graph generates same join clause twice

hibernate-core/src/test/java/org/hibernate/orm/test/filter/FilterDefinitionOrderTest.java
https://hibernate.atlassian.net/browse/HHH-19036
Only a test since this already works nicely in 7.0
=> HHH-19036 Add a test for filter declaration order

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotationBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/annotations/AnnotationMetadataSourceProcessorImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/FilterDefinitionOrderTest.java
https://hibernate.atlassian.net/browse/HHH-19036
This already works fine in 7.0 since the switch to models and having this:
https://github.com/hibernate/hibernate-orm/blob/f0bfef9ce35e6ba7caf27904e503b5fceb5f81e1/hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/annotations/AnnotationMetadataSourceProcessorImpl.java#L170-L177
I did consider doing the pass over classes in the processFilterDefinitions method as well for 6.6, but it feels a bit redundant to generate the `orderedClasses = orderAndFillHierarchy( xClasses )` two times, or alternatively going through `xClasses` + their super types... so this seems like a good compromise, no ? …
=> HHH-19036 Process all filters before going through classes

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/PathSource.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AbstractAttribute.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AbstractIdentifiableType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AbstractManagedType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AbstractPluralAttribute.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EmbeddableTypeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EntityTypeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappedSuperclassTypeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/SingularAttributeImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/SqmPathSource.java, hibernate-core/src/main/java/org/hibernate/query/sqm/spi/SqmCreationHelper.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmPath.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmDomainType.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmEmbeddableDomainType.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmEntityDomainType.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmManagedDomainType.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmMappedSuperclassDomainType.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmPersistentAttribute.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmPluralPersistentAttribute.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmPolymorphicRootDescriptor.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmSingularPersistentAttribute.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmTreatableDomainType.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tuple/internal/AnonymousTupleTableGroupProducer.java, migration-guide.adoc, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java
https://hibernate.atlassian.net/browse/HHH-16972
=> HHH-16972 more fallout from big refactor

hibernate-core/src/main/java/org/hibernate/SessionBuilder.java, hibernate-core/src/main/java/org/hibernate/SharedSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/StatelessSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java, hibernate-core/src/main/java/org/hibernate/engine/spi/AbstractDelegatingSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/engine/spi/AbstractDelegatingSharedSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/BaselineSessionEventsListenerBuilder.java, hibernate-core/src/main/java/org/hibernate/internal/SessionCreationOptions.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/main/java/org/hibernate/query/spi/QueryEngineOptions.java, hibernate-core/src/main/java/org/hibernate/resource/jdbc/spi/JdbcSessionContext.java, hibernate-core/src/main/java/org/hibernate/resource/jdbc/spi/PhysicalConnectionHandlingMode.java, hibernate-core/src/test/java/org/hibernate/orm/test/events/ClearEventListenerTest.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/basic/TransactionRollbackBehaviour.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java
- An SPI operation exposed the internal class `BaselineSessionEventsListenerBuilder`.
- (Also, we can replace `BaselineSessionEventsListenerBuilder` with a package-private static Helper method, so mark it for removal.)
- I also found two API methods which exposed SPI types. I deprecated them and replaced them with better overloads. …
=> HHH-19350  deprecate layer-breaking operations

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacySqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteInsertHandler.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/BasicValuedPathInterpretation.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EmbeddableValuedPathInterpretation.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/NonAggregatedCompositeValuedPathInterpretation.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/SqmPathInterpretation.java, hibernate-core/src/main/java/org/hibernate/sql/ast/SqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/flush/AutoFlushOnUpdateQueryTest.java
https://hibernate.atlassian.net/browse/HHH-18563
=> HHH-18563 Add set clause foreign key target tables to affected tables

hibernate-core/src/main/java/org/hibernate/cfg/DialectSpecificSettings.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/ASTParserLoadingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/JsonWithArrayEmbeddableTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/formula/FormulaTests.java, migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-18896
=> HHH-18896 Use binary_float/binary_double on Oracle for Java float/double

hibernate-core/src/main/java/org/hibernate/boot/SessionFactoryBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java, hibernate-core/src/main/java/org/hibernate/internal/log/DeprecationLogger.java
We believe that this was once upon a time long ago used for JBoss integration, but it's not used by WildFly anymore. Also, the property itself has a name which is quite misleading.
https://hibernate.atlassian.net/browse/HHH-19357
=> HHH-19357 deprecate 'hibernate.discard_pc_on_close'

hibernate-core/src/main/java/org/hibernate/action/internal/EntityIncrementVersionProcess.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/EnhancementHelper.java, hibernate-core/src/main/java/org/hibernate/collection/spi/AbstractPersistentCollection.java, hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionImplementor.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/event/spi/AutoFlushEvent.java, hibernate-core/src/main/java/org/hibernate/id/IdentifierGeneratorHelper.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/main/java/org/hibernate/proxy/AbstractLazyInitializer.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/transaction/SynchronizationTypeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/transaction/TransactionJoinHandlingChecker.java, hibernate-core/src/test/java/org/hibernate/orm/test/sharedSession/SessionWithSharedConnectionTest.java, hibernate-envers/src/test/java/org/hibernate/envers/test/integration/tm/SessionFactoryInterceptorTransactionTest.java, hibernate-envers/src/test/java/org/hibernate/envers/test/integration/tm/SessionInterceptorTransactionTest.java
- remove deprecated getFlushMode()
- remove setHibernateFlushMode()
- deprecate silly methods which are much worse than safe casts
=> partially address a todo in SharedSessionContractImplementor

hibernate-vector/src/main/java/org/hibernate/vector/MariaDBFunctionContributor.java, hibernate-vector/src/main/java/org/hibernate/vector/OracleVectorFunctionContributor.java, hibernate-vector/src/main/java/org/hibernate/vector/PGVectorFunctionContributor.java
Extracted duplicated vector distance function registration code into a helper method to improve code clarity and maintenance.
https://hibernate.atlassian.net/browse/HHH-19284
=> HHH-19284 : Refactor - Extract duplicated vector distance function registration

hibernate-core/src/main/java/org/hibernate/annotations/TimeZoneStorageType.java, hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/BasicValueBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/TimeZoneStorageHelper.java, hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/VersionResolution.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingMetadataBuildingOptions.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataBuildingOptions.java, hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java, hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java, hibernate-core/src/main/java/org/hibernate/type/StandardBasicTypes.java, hibernate-core/src/main/java/org/hibernate/type/TimeZoneStorageStrategy.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/DelegatingJdbcTypeIndicators.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JdbcTypeIndicators.java, hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java
This enum is not really an API-API (it's more like an SPI), and has no usages in `org.hibernate`. Application programs are expected to use `o.h.annotations.TimeZoneStorageType`, and so putting this enum in `org.hibernate` is pretty confusing to users, who have no use for it.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING …
=> move incubating enum TimeZoneStorageStrategy to org.hibernate.type

hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/main/java/org/hibernate/loader/internal/IdentifierLoadAccessImpl.java
Fix https://hibernate.atlassian.net/browse/HHH-19348
For Hibernate Reactive
Change scopes of some private methods, and small refactoring to avoid duplication in Hibernate Reactive.
Related to https://github.com/hibernate/hibernate-reactive/issues/2181
=> Change scope of private methods for Hibernate Reactive

hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/loader/internal/IdentifierLoadAccessImpl.java
A couple of extra changes for [HHH-191384 ](https://hibernate.atlassian.net/browse/HHH-19348)
For Hibernate Reactive.
Related to https://github.com/hibernate/hibernate-reactive/issues/2181
https://hibernate.atlassian.net/browse/HHH-19384
=> Change the scope of more methods

documentation/documentation.gradle, release/release.gradle, release_notes.md, whats-new.adoc
Per discussions about information related to release series, here are the changes needed on the ORM side -
* added a What's New guide to list new features and new capabilities
* updated release_notes.md, which is used as part of the GitHub release notes to link to both the Migration Guide and the What's New guide (note that this part is temporary as @yrodiere wants to handle this differently moving forward)
* stage this new What's New guide for upload to the doc server
A follow-up task is to change the website series notes to not include the What's New information.  I just recently added it there anyway, so not a big deal. …
=> HHH-19358 - Add a "What's New" document for series

hibernate-core/src/main/java/org/hibernate/boot/jaxb/Origin.java, hibernate-core/src/main/java/org/hibernate/boot/jaxb/SourceType.java, hibernate-core/src/main/java/org/hibernate/query/criteria/HibernateCriteriaBuilder.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/JdbcTypeNameMapper.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/XmlArrayJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/XmlAsStringArrayJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/XmlAsStringJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/XmlJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/spi/JdbcTypeRegistry.java
=> hit some stuff in o.h.t.d.jdbc with Extract Method

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/FetchGraphCollectionOrderByAndCriteriaJoinTest.java
Test cases and possible fix for https://hibernate.atlassian.net/browse/HHH-19207
=> HHH-19207 fix missing order by

hibernate-core/src/main/java/org/hibernate/query/range/CaseInsensitiveValue.java, hibernate-core/src/main/java/org/hibernate/query/range/LowerBound.java, hibernate-core/src/main/java/org/hibernate/query/range/UpperBound.java, hibernate-core/src/main/java/org/hibernate/query/range/Value.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/AbstractSqmSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/jpa/ParameterCollector.java
the test failures demonstrate the problem
https://hibernate.atlassian.net/browse/HHH-17002
=> HHH-18991 enable use of parameters in Restrictions

documentation/src/main/asciidoc/introduction/Interacting.adoc, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/query/QueryProducer.java, hibernate-core/src/main/java/org/hibernate/query/criteria/CriteriaDefinition.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/MutationSpecification.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/QuerySpecification.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/SelectionSpecification.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/internal/MutationSpecificationImpl.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/internal/SelectionSpecificationImpl.java, hibernate-core/src/main/java/org/hibernate/query/restriction/NamedPathElement.java, hibernate-core/src/main/java/org/hibernate/query/restriction/Path.java, hibernate-core/src/main/java/org/hibernate/query/restriction/PathElement.java, hibernate-core/src/main/java/org/hibernate/query/restriction/PathRoot.java, hibernate-core/src/main/java/org/hibernate/query/restriction/Restriction.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/dynamic/OtherEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/dynamic/SimpleQuerySpecificationTests.java
Usage looks like:
```java
var books = 
SelectionSpecification.create(Book.class)
.addRestriction(Restriction.like(Book_.title, "%Hibernate%", false))
.addRestriction(Restriction.greaterThan(Book_.pages, 100))
.addFetching(Path.from(Book.class).to(Book_.authors))
.setOrder(Order.desc(Book_.title))
.createQuery(session)
.getResultList();
```
Looks just like ye olde Hibernate criteria, but perfectly type safe!
Also now allowed:
```java
var books = 
SelectionSpecification.create(Book.class)
.addAugmentation((builder, query, book) -> 
query.where(builder.like(book.get(Book_.title), "%Hibernate%")))
.addFetching(Path.from(Book.class).to(Book_.authors))
.addOrdering(Order.asc(Book_.title))
.createQuery(session)
.getResultList();
```
That is .... actually really nice.
By …
=> HHH-19364 fully-detached version

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmInterpretationsKey.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmSelectionQueryImpl.java
=> some cleanup to SqmInterpretationsKey

tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java
so we don't need to go locating and instantiating unnecessary services
=> avoid use of BootstrapServiceRegistryBuilder in MockSessionFactory

documentation/src/main/asciidoc/introduction/Processor.adoc, documentation/src/main/asciidoc/repositories/Reactive.adoc
=> clarify some stuff about session mgt with reactive repositories

hibernate-core/src/main/java/org/hibernate/IdentifierLoadAccess.java, hibernate-core/src/main/java/org/hibernate/MultiIdentifierLoadAccess.java, hibernate-core/src/main/java/org/hibernate/NaturalIdLoadAccess.java, hibernate-core/src/main/java/org/hibernate/NaturalIdMultiLoadAccess.java, hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/SimpleNaturalIdLoadAccess.java, hibernate-core/src/main/java/org/hibernate/StatelessSession.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java, hibernate-core/src/main/java/org/hibernate/internal/MultiIdentifierLoadAccessImpl.java, hibernate-core/src/main/java/org/hibernate/internal/NaturalIdMultiLoadAccessStandard.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/main/java/org/hibernate/loader/internal/BaseNaturalIdLoadAccessImpl.java, hibernate-core/src/main/java/org/hibernate/loader/internal/IdentifierLoadAccessImpl.java, hibernate-core/src/main/java/org/hibernate/loader/internal/NaturalIdLoadAccessImpl.java, hibernate-core/src/main/java/org/hibernate/loader/internal/SimpleNaturalIdLoadAccessImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/FindMultipleEntityGraphTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/GetMultipleEntityGraphTest.java
=> HHH-19378 findMultiple() and getMultiple() with EntityGraph

documentation/src/main/asciidoc/introduction/Interacting.adoc
=> document new overload of findMultiple()

documentation/src/main/asciidoc/introduction/Interacting.adoc, hibernate-core/src/main/java/org/hibernate/query/programmatic/MutationSpecification.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/QuerySpecification.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/SelectionSpecification.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/internal/MutationSpecificationImpl.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/internal/SelectionSpecificationImpl.java, hibernate-core/src/main/java/org/hibernate/query/restriction/Path.java, hibernate-core/src/main/java/org/hibernate/query/restriction/Restriction.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/dynamic/SimpleQuerySpecificationTests.java
Submitted for consideration by @sebersole.
=> HHH-19364 snappier naming

documentation/src/main/asciidoc/userguide/chapters/query/programmatic/QuerySpecification.adoc, hibernate-core/src/main/java/org/hibernate/query/Order.java, hibernate-core/src/main/java/org/hibernate/query/programmatic/MutationSpecification.java, whats-new.adoc
=> HHH-19364 documentation updates

hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/query/specification/MutationSpecification.java, hibernate-core/src/main/java/org/hibernate/query/specification/QuerySpecification.java, hibernate-core/src/main/java/org/hibernate/query/specification/SelectionSpecification.java, hibernate-core/src/main/java/org/hibernate/query/specification/internal/MutationSpecificationImpl.java, hibernate-core/src/main/java/org/hibernate/query/specification/internal/SelectionSpecificationImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/dynamic/SimpleQuerySpecificationTests.java
=> HHH-19364 make Specification subtypes into TypedQueryReferences

whats-new.adoc
=> couple of minor improvs to What's New for completeness

hibernate-core/src/main/java/org/hibernate/query/specification/internal/MutationSpecificationImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/dynamic/SimpleQuerySpecificationTests.java
Fix https://hibernate.atlassian.net/browse/HHH-19386
=> MutationSpecificationImpl#getResultType must return null (and not Void.class)

hibernate-core/src/test/java/org/hibernate/orm/test/query/dynamic/SimpleQuerySpecificationTests.java
Follows https://github.com/hibernate/hibernate-orm/pull/10083
Because I forgot to add a test with the StatelessSession.
https://hibernate.atlassian.net/browse/HHH-19386
=> Add test with stateless session for HHH-19386

hibernate-core/src/main/java/org/hibernate/internal/util/collections/IdentityMap.java, hibernate-core/src/main/java/org/hibernate/internal/util/collections/LazySet.java, hibernate-envers/src/main/java/org/hibernate/envers/internal/tools/ConcurrentReferenceHashMap.java, hibernate-envers/src/main/java/org/hibernate/envers/internal/tools/ReflectionTools.java
=> cleanups to internal collection-related utils

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java
=> code cleanups in DefaultMergeEventListener

documentation/src/main/asciidoc/querylanguage/Expressions.adoc
and fix something which was actually wrong: the JDBC-style literals are assigned types from java.sql, not java.time.
=> update documentation of date/time literals for JPA 3.2

documentation/src/main/asciidoc/introduction/Entities.adoc
=> document deprecation of Byte[], Character[] in JPA 3.2

tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/eg/Library.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/ClassWriter.java
https://hibernate.atlassian.net/browse/HHH-19425
=> HHH-19425 fix missing '.class' when annotations copied to repo implementations

tooling/metamodel-generator/src/main/java/org/hibernate/processor/ClassWriter.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
https://hibernate.atlassian.net/browse/HHH-19425
https://hibernate.atlassian.net/browse/HHH-19374
https://hibernate.atlassian.net/browse/HHH-19375
=> HHH-19374, HHH-19375, HHH-19425 backport to 6.6

documentation/src/main/asciidoc/repositories/Pagination.adoc, documentation/src/main/asciidoc/repositories/Reactive.adoc
=> improvements to Data Repositories documentation

local-build-plugins/src/main/groovy/local.publishing.gradle
=> HHH-19341 Adjust the snapshots publishing config to use username/password env variables

hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/attr/CommonPluralAttributeProcessing.java, hibernate-core/src/test/java/org/hibernate/orm/test/boot/models/hbm/collections/list/ListTests.java, hibernate-core/src/test/resources/mappings/models/hbm/list/mapping.xml
HHH-19299 - <element-collection/> with LIST classification interpreted as BAG
https://hibernate.atlassian.net/browse/HHH-19299
=> HHH-19299 - <element-collection/> with LIST classification interpreted as BAG

build.gradle, ci/release/Jenkinsfile, ci/snapshot-publish.Jenkinsfile, gradle/published-java-module.gradle, hibernate-platform/hibernate-platform.gradle, tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
=> HHH-19341 Backport JReleaser config to 6.6

hibernate-core/src/main/java/org/hibernate/engine/internal/Nullability.java, hibernate-core/src/main/java/org/hibernate/query/QueryProducer.java
=> two minor cleanupy type things

hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/query/QueryProducer.java
=> more prominent discussion of result types

hibernate-core/src/main/java/org/hibernate/query/QueryProducer.java
=> expand the jdoc of QueryProducer

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/BasicDomainType.java, hibernate-core/src/main/java/org/hibernate/procedure/ProcedureCall.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/FunctionReturnImpl.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/PostgreSQLCallableStatementSupport.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureParameterImpl.java, hibernate-core/src/main/java/org/hibernate/procedure/spi/ProcedureCallImplementor.java, hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcCallFunctionReturnImpl.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcCallParameterExtractorImpl.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcCallParameterRegistrationImpl.java, hibernate-core/src/main/java/org/hibernate/sql/exec/spi/JdbcCallParameterRegistration.java, hibernate-core/src/main/java/org/hibernate/type/OutputableType.java, hibernate-core/src/main/java/org/hibernate/type/ProcedureParameterExtractionAware.java
we're trying to clean up org.hibernate.Query
https://hibernate.atlassian.net/browse/HHH-19438
https://hibernate.atlassian.net/browse/HHH-19442
=> HHH-19438 move OutputableType to org.hibernate.type

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AggregateComponentSecondPass.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
https://hibernate.atlassian.net/browse/HHH-19389
=> HHH-19389 proper error when @Struct is used on Dialect with no support for UDTs

hibernate-core/src/main/java/org/hibernate/cfg/JdbcSettings.java, hibernate-core/src/main/java/org/hibernate/dialect/temptable/TemporaryTableHelper.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/SQLExceptionLogging.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/SqlExceptionHelper.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/AbstractInformationExtractorImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/uniqueconstraint/UniqueConstraintBatchingTest.java
- and clean up the terrible previous impl of logExceptions()
- also slightly tidy up JdbcEnvironmentImpl
https://hibernate.atlassian.net/browse/HHH-19399
=> HHH-19399 introduce hibernate.jdbc.log.errors

hibernate-core/src/main/java/org/hibernate/jpa/HibernateHints.java, hibernate-core/src/main/java/org/hibernate/procedure/FunctionReturn.java, hibernate-core/src/main/java/org/hibernate/procedure/ProcedureCall.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/OracleCallableStatementSupport.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/SQLServerCallableStatementSupport.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/StandardCallableStatementSupport.java, hibernate-core/src/main/java/org/hibernate/procedure/spi/ProcedureCallImplementor.java, hibernate-core/src/main/java/org/hibernate/query/procedure/ProcedureParameter.java
https://hibernate.atlassian.net/browse/HHH-19445
=> HHH-19445 ProcedureCall should accept BindableType, not BasicTypeReference

hibernate-core/src/main/java/org/hibernate/query/sqm/SqmPathSource.java
https://hibernate.atlassian.net/browse/HHH-18569
=> HHH-18569 Fix missing parameter + remove unneeded deprecations

documentation/src/main/asciidoc/introduction/Interacting.adoc
should have had this from the start
=> add explanation of whole transient vs detached stuff

documentation/src/main/asciidoc/introduction/Interacting.adoc, hibernate-core/src/main/java/org/hibernate/Interceptor.java, hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/spi/PersistenceContext.java, hibernate-core/src/main/java/org/hibernate/type/OneToOneType.java
=> jdoc, comments, and doc

hibernate-core/src/main/java/org/hibernate/LockOptions.java, hibernate-core/src/main/java/org/hibernate/Timeouts.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java, hibernate-core/src/main/java/org/hibernate/query/NativeQuery.java, hibernate-core/src/main/java/org/hibernate/query/Query.java, hibernate-core/src/main/java/org/hibernate/query/SelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/hql/spi/SqmQueryImplementor.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sql/spi/NativeQueryImplementor.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/spi/DelegatingSqmSelectionQueryImplementor.java, migration-guide.adoc
and explain what's going on with it in the javadoc
https://hibernate.atlassian.net/browse/HHH-19440
=> HHH-19440 completely deprecate LockOptions

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLiteDialect.java
See https://github.com/sqlite/sqlite/commit/f9c8ce3ced8960e7c8d74b68ad420ec5f581494d
> Standardize the error messages generated by constraint failures to a format of "$TYPE constraint failed: $DETAIL".
Also in case [extended result codes](http://sqlite.org/c3ref/extended_result_codes.html) are activated, we need the `& 0xFF`.
And as there seems to be no way to tell `extractUsingTemplate` that there is no `templateEnd`, the dollar sign is used...
See [original](https://github.com/gwenn/sqlite-dialect/blob/c87223460e3335ff4f041e012bd0d22df99fa2af/src/main/java/org/sqlite/hibernate/dialect/SQLiteDialect.java#L244-L253) code and associated [test](https://github.com/gwenn/sqlite-dialect/blob/c87223460e3335ff4f041e012bd0d22df99fa2af/src/test/java/org/hibernate/tutorial/annotations/AnnotationsIll …
=> HHH-19444 SQLiteDialect - Fix ViolatedConstraintNameExtractor

gradle/published-java-module.gradle, gradle/publishing-pom.gradle
that is also used by java modules and poms (e.g. platform one)
=> HHH-19341 Move publication repositories configuration to a more common gradle file

hibernate-core/src/main/java/org/hibernate/LockOptions.java, hibernate-core/src/main/java/org/hibernate/engine/profile/DefaultFetchProfile.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java, hibernate-core/src/main/java/org/hibernate/internal/FetchProfileHelper.java, hibernate-core/src/main/java/org/hibernate/jpa/spi/NativeQueryConstructorTransformer.java, hibernate-core/src/main/java/org/hibernate/jpa/spi/NativeQueryListTransformer.java, hibernate-core/src/main/java/org/hibernate/jpa/spi/NativeQueryMapTransformer.java, hibernate-core/src/main/java/org/hibernate/metamodel/AttributeClassification.java, hibernate-core/src/main/java/org/hibernate/metamodel/CollectionClassification.java, hibernate-core/src/main/java/org/hibernate/metamodel/RuntimeMetamodels.java, hibernate-core/src/main/java/org/hibernate/metamodel/ValueClassification.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/DiscriminatedAssociationAttributeMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/DiscriminatedAssociationMapping.java, hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java, hibernate-core/src/main/java/org/hibernate/query/results/internal/Builders.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractCommonQueryContract.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/MatchingIdSelectionHelper.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteInsertHandler.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/inline/InlineDeleteHandler.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/spi/AbstractMutationHandler.java, hibernate-core/src/test/java/org/hibernate/orm/test/associations/any/AnyTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/flush/AutoFlushTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/flush/HibernateAutoFlushTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/flush/ManualFlushTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/multitenancy/DatabaseTimeZoneMultiTenancyTest.java
=> miscellaneous cleanups

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractDomainPath.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/ColumnReference.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/FunctionExpression.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/OrderingExpression.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/OrderingSpecification.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/ParseTreeVisitor.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/SelfRenderingOrderingExpression.java, hibernate-core/src/main/java/org/hibernate/query/criteria/HibernateCriteriaBuilder.java, hibernate-core/src/main/java/org/hibernate/query/criteria/JpaSearchOrder.java, hibernate-core/src/main/java/org/hibernate/query/criteria/spi/HibernateCriteriaBuilderDelegate.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/cte/SqmSearchClauseSpecification.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSortSpecification.java, hibernate-core/src/main/java/org/hibernate/sql/ast/tree/cte/SearchClauseSpecification.java, hibernate-core/src/main/java/org/hibernate/sql/ast/tree/select/SortSpecification.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetomany/DefaultNullOrderingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetomany/OrderByTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaOrderedSetAggregateTest.java
=> Remove some left-over occurrences of NullsPrecedence in incubating APIs and internal SPIs

.release/.gitignore, build.gradle, ci/release/Jenkinsfile, ci/snapshot-publish.Jenkinsfile, gradle/published-java-module.gradle, gradle/publishing-repos.gradle, hibernate-infinispan/hibernate-infinispan.gradle, release/release.gradle
=> HHH-19341 Add automated release to 5.3

hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/AbstractMultiIdEntityLoader.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderHelper.java, hibernate-core/src/main/java/org/hibernate/metamodel/MappingMetamodel.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleNaturalIdMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/JpaMetamodel.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/NavigableRole.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappingMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/spi/JpaMetamodelImplementor.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SqmPathRegistryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmBinaryArithmetic.java, hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java
https://hibernate.atlassian.net/browse/HHH-19466
=> HHH-19466 fix exposure of SPI types via JpaMetamodel

hibernate-core/src/main/java/org/hibernate/LockOptions.java, hibernate-core/src/main/java/org/hibernate/boot/SchemaAutoTooling.java, hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/NavigableRole.java, hibernate-core/src/main/java/org/hibernate/spi/NavigablePath.java
=> Tiny changes

documentation/src/main/asciidoc/introduction/Advanced.adoc, documentation/src/main/asciidoc/introduction/Mapping.adoc
=> add more links to Short Guide

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedJoinColumn.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedJoinColumns.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ColumnsBuilder.java
=> Remove some obsolete code

hibernate-core/src/main/java/org/hibernate/jpa/spi/NativeQueryArrayTransformer.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/SingleSelectionArrayResultTest.java
The fix is quite simple and obvious. I also refactored the test that was previously introduced for [HHH-18450](https://hibernate.atlassian.net/browse/HHH-18450) to cover more cases and make it easier to maintain.
My understanding is that when executing queries (any kind), we either provide a row transformer, a tuple transformer or the expected result class. Sqm-based queries are providing the row transformer directly (based on the result class) while native queries are currently implemented with providing directly the tuple transformer.
So I went with fitting in the existing code by supporting `Object[]` at the tuple transformer level for native queries.
Alternatively I looked into producing a row transformer in `NativeSelectQueryPlanImpl` or moving all the default row transformer …
=> HHH-19472: native queries can return Object[]

hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteUpdateHandler.java, hibernate-core/src/test/java/org/hibernate/orm/test/secondarytable/HHH18813Test.java
This PR fixes a bug described in HHH-18813.
The CteUpdateHandler generated an insert-query, which contained columns that do not exist in the target table.
https://hibernate.atlassian.net/browse/HHH-18813
=> HHH-18813: Fix of generated Insert-Query in CteUpdateHandler

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnyBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/OneToOneSecondPass.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ToOneBinder.java, hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java, hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CascadingAction.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CascadingActions.java, hibernate-core/src/main/java/org/hibernate/event/internal/AbstractFlushingEventListener.java, hibernate-core/src/main/java/org/hibernate/mapping/Property.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java, hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/access/HierarchyPropertyAccessTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/cfg/persister/GoofyPersisterClassProvider.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ejb3configuration/PersisterClassProviderTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/legacy/CustomPersister.java
https://hibernate.atlassian.net/browse/HHH-19394
=> HHH-19394 disable transient reference checking for read-only entities

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java
in this case it can't be intended for another provider
https://hibernate.atlassian.net/browse/HHH-19463
=> HHH-19463 when we have @Repository(provider="Hibernate") don't skip repo

hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteUpdateHandler.java, hibernate-core/src/test/java/org/hibernate/orm/test/secondarytable/HHH18813Test.java
https://hibernate.atlassian.net/browse/HHH-18813
Backport of #10173 to branch 6.6.
=> Backport HHH-18813 to branch 6.6 - DML update of secondary table column fails

hibernate-core/src/main/java/org/hibernate/query/specification/SelectionSpecification.java, hibernate-core/src/main/java/org/hibernate/query/specification/internal/SelectionSpecificationImpl.java
=> widen type of SelectionSpecification.resort()

documentation/src/main/asciidoc/introduction/Configuration.adoc, documentation/src/main/asciidoc/introduction/Introduction.adoc, documentation/src/main/asciidoc/repositories/Configuration.adoc, settings.gradle
=> update to Hibernate Validator 9

hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
=> query parser improvements

hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/NativeQueryResultCheckingTests.java
https://hibernate.atlassian.net/browse/HHH-19383
=> HHH-19383 - validation of NativeQuery result mappings

hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/NativeQueryResultCheckingTests.java
https://hibernate.atlassian.net/browse/HHH-19383
=> HHH-19383 improvements

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/BiDirectionalAssociationHandler.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/LazyLoadingAndParameterizedInheritanceTest.java
This PR includes a test and fix for the issue in https://hibernate.atlassian.net/browse/HHH-19473
=> HHH-19473: Use asDefined type when enhancing BiDirectional Associations to resolve issue with mismatched generated method signatures.

hibernate-testing/src/main/java/org/hibernate/testing/bytecode/enhancement/extension/engine/BytecodeEnhancedEngineDescriptor.java, hibernate-testing/src/main/java/org/hibernate/testing/bytecode/enhancement/extension/engine/BytecodeEnhancedTestEngine.java
=> Make bytecode test engine backwards compatible with older JUnit versions

hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/IndexBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/TableBinder.java, hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java, hibernate-core/src/main/java/org/hibernate/mapping/Table.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/refcolnames/constraints/ManyToOneRefColumnNameTest.java
this was happening for multi-column references, but not for single columns
https://hibernate.atlassian.net/browse/HHH-19479
=> HHH-19479 automatically make referenced column unique

hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/FindMultipleFromCacheTest.java
=> add additional test for findMultiple() with second-level cache

documentation/src/main/asciidoc/introduction/Advanced.adoc, hibernate-core/src/main/java/org/hibernate/EnabledFetchProfile.java
https://hibernate.atlassian.net/browse/HHH-19468
=> HHH-19468 allow an EnabledFetchProfile to be apply()d to a Session or Query

hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/EntityEntry.java, hibernate-core/src/main/java/org/hibernate/loader/internal/CacheLoadHelper.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java
https://hibernate.atlassian.net/browse/HHH-19487
=> HHH-19487 move dirty-checking related code out of AbstractEntityPersister

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
Remove reduntant LOG.isTraceEnabled() from logDirtyProperties
=> Remove reduntant LOG.isTraceEnabled() from logDirtyProperties

documentation/src/main/asciidoc/introduction/Interacting.adoc, hibernate-core/src/main/java/org/hibernate/boot/model/FunctionContributor.java, hibernate-core/src/main/java/org/hibernate/boot/model/TypeContributor.java
=> fix three occurrences of "on object"

ci/release/Jenkinsfile
Backport of https://github.com/hibernate/hibernate-orm/pull/10235
=> [6.2] Backport "Use a script to release on Jira + avoid auto-release when there are no "releasable" commits"

hibernate-core/src/main/java/org/hibernate/engine/internal/ForeignKeys.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDeleteEventListener.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/BasicEntityIdentifierMappingImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddedIdentifierMappingImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/NonAggregatedIdentifierMappingImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SimpleForeignKeyDescriptor.java, hibernate-core/src/main/java/org/hibernate/proxy/pojo/BasicLazyInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/AbstractBatchEntitySelectFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/DiscriminatedEntityInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/JpaProxyComplianceEnabledTest.java
https://hibernate.atlassian.net/browse/HHH-19476
=> HHH-19476 claimEntityHolderIfPossible Assertion Error

hibernate-core/src/test/java/org/hibernate/orm/test/records/ElementCollectionOfRecordsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/records/GenericEmbeddedIdRecordTest.java
https://hibernate.atlassian.net/browse/HHH-18957
=> HHH-18957 - Add test for issue

documentation/src/main/asciidoc/introduction/Interacting.adoc, hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/Transaction.java
=> better-document the rule for transaction rollback

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityVersionMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AbstractIdentifiableType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EntityTypeImpl.java, hibernate-core/src/main/java/org/hibernate/query/criteria/HibernateCriteriaBuilder.java, hibernate-core/src/main/java/org/hibernate/query/criteria/JpaFrom.java, hibernate-core/src/main/java/org/hibernate/query/criteria/spi/HibernateCriteriaBuilderDelegate.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/NodeBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmFrom.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaIdVersionTest.java
https://hibernate.atlassian.net/browse/HHH-19493
=> HHH-19493 add HCB.id(), HCB.version(), and JpaFrom.id()

hibernate-core/src/main/java/org/hibernate/boot/model/naming/NamingHelper.java
because the JDK version is not available in FIPS mode
https://hibernate.atlassian.net/browse/HHH-19471
=> HHH-19471 use custom implementation of MD5

hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/dirtiness/CustomDirtinessStrategyTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/dirtiness/HHH11866Test.java
Using a CustomEntityDirtinessStrategy leads to entities marked as dirty after they have been first loaded.
Consequently, calling flush immediately afterwards leads to an update, although the entity has not been changed.
The fix added a call of CustomEntityDirtinessStrategy#resetDirty in AbstractEntityPersister#afterInitialize.
The fix also needed a change of two assertions in CustomDirtinessStrategyTest, but they are ok.
For more …
=> HHH-11866 fix CustomEntityDirtinessStrategy#resetDirty is not called after entity initialization

hibernate-core/src/main/java/org/hibernate/StatelessSession.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/LazyToOnesNoProxyFactoryWithSubclassesStatelessTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/StatelessSessionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/UpsertVersionedTest.java
=> test and document behavior of SS.get() when entity not found

hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableAssembler.java, hibernate-core/src/test/java/org/hibernate/orm/test/notfound/CompositeForeignKeyNotFoundTest.java
The bug reported in HHH-18891 describes an assertion that fails because it expects the initializer state to be KEY_RESOLVED before it resolves the instance.
I added an if statement in EmbeddableAssembler to ensure that the key is resolved if the state is UNINITIALIZED.
The tests in the PR are based on https://github.com/hibernate/hibernate-test-case-templates/pull/454
as presented in https://hibernate.atlassian.net/browse/HHH-18891 but have been simplified a bit for readability.
I guess that there are other possibilities to catch the given scenario earlier or with a more specific approach.
But at least none of the other tests fail with the fix. :) …
=> HHH-18891 fix of an AssertionError when using a NotFound annotation

hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CascadingAction.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CascadingActions.java, hibernate-core/src/main/java/org/hibernate/mapping/Property.java, hibernate-core/src/main/java/org/hibernate/tuple/AbstractNonIdentifierAttribute.java, hibernate-core/src/main/java/org/hibernate/tuple/BaselineAttributeInformation.java, hibernate-core/src/main/java/org/hibernate/tuple/NonIdentifierAttribute.java, hibernate-core/src/main/java/org/hibernate/tuple/PropertyFactory.java, hibernate-core/src/main/java/org/hibernate/tuple/StandardProperty.java, hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java, hibernate-core/src/main/java/org/hibernate/type/AnyType.java, hibernate-core/src/main/java/org/hibernate/type/ComponentType.java, hibernate-core/src/main/java/org/hibernate/type/CompositeType.java, hibernate-core/src/test/java/org/hibernate/orm/test/OnDeleteTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/OnDeleteTest2.java
Supersedes #9684.
https://hibernate.atlassian.net/browse/HHH-18936
=> HHH-18936 suppress TransientObjectException when the FK is marked @OnDelete(CASCADE)

hibernate-core/src/main/java/org/hibernate/action/internal/EntityDeleteAction.java, hibernate-core/src/main/java/org/hibernate/annotations/OnDelete.java, hibernate-core/src/main/java/org/hibernate/stat/CacheRegionStatistics.java, hibernate-core/src/main/java/org/hibernate/stat/CacheableDataStatistics.java, hibernate-core/src/main/java/org/hibernate/stat/internal/AbstractCacheableDataStatistics.java, hibernate-core/src/main/java/org/hibernate/stat/internal/CacheRegionStatisticsImpl.java, hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsImpl.java, hibernate-core/src/main/java/org/hibernate/stat/spi/StatisticsImplementor.java, hibernate-core/src/test/java/org/hibernate/orm/test/ondeletecascade/OnDeleteCascadeRemoveTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/ondeletecascade/OnDeleteTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/ondeletecascade/OnDeleteTest2.java
https://hibernate.atlassian.net/browse/HHH-18936
=> HHH-18936 test for cascade REMOVE with @OnDelete(CASCADE)

hibernate-core/src/test/java/org/hibernate/orm/test/ondeletecascade/OnDeleteCascadeRemoveTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/ondeletecascade/OnDeleteTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/ondeletecascade/OnDeleteTest2.java
no support for 'on delete cascade'
=> disable test on Sybase

CONTRIBUTING.md, MAINTAINERS.md, README.adoc, release/README.adoc
=> Centralize release instructions in MAINTAINERS.md

hibernate-core/src/main/java/org/hibernate/SessionFactory.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/MappingMetamodel.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/InjectionHelper.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/JpaMetamodelPopulationSetting.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/DomainType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/JpaMetamodel.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappingMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/spi/JpaMetamodelImplementor.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/BasicDotIdentifierConsumer.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmJpaCriteriaParameterWrapper.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmNamedParameter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmPositionalParameter.java
https://hibernate.atlassian.net/browse/HHH-19466
=> HHH-19466 continue cleaning up JpaMetamodel SPI

hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/ArrayInitializer.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/collections/OrderColumnListIndexArrayInitializerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/collections/OrderColumnListIndexHHH18771ListInitializerTest.java
HHH-18876 is a follow up to HHH-18771 and describes a possible `ArrayIndexOutOfBoundsException` in the `ArrayInitializer` when using `@ListIndexBase`.
The pull request consists of a reproducer test and a fix in `ArrayInitializer` equivalent to the fix in `ListInitializer` of HHH-18771.
The provided test is based on OrderColumnListIndexHHH18771ListInitializerTest.
https://hibernate.atlassian.net/browse/HHH-18876
https://hibernate.atlassian.net/browse/HHH-18771
PR of HHH-18771: https://github.com/hibernate/hibernate-orm/pull/9169 …
=> HHH-18876 ArrayIndexOutOfBoundsException in ArrayInitializer with ListIndexBase

hibernate-core/src/test/java/org/hibernate/orm/test/mapping/access/ElementCollectionInOneToManyTest.java
I created a test case for the bug described in HHH-13721.
Hovever, as discussed in Jira, this was already resolved in the past but the Jira issue reopened for any reason.
Hence, I also could not reproduce the bug.
However, I could not find any reference to HHH-13721 in the codebase, consequently I submit this PR.
Actually I do not know if any of the existing tests matches my PR.
Therefore, if you do not want to merge this PR, please close the related Jira issue if possible or document in Jira what is expected.
https://hibernate.atlassian.net/browse/HHH-13721
and can be relicensed under the terms of the …
=> HHH-13721 Getting duplicated entities with @OneToMany and @ElementCollection

hibernate-core/src/main/java/org/hibernate/jpa/event/spi/CallbackType.java, hibernate-core/src/main/java/org/hibernate/jpa/event/spi/package-info.java
=> modernize the CallbackType enum

hibernate-core/src/main/java/org/hibernate/jpa/package-info.java
=> mention HibernatePersistenceConfiguration in package-level jdoc

hibernate-core/src/main/java/org/hibernate/id/enhanced/TableGenerator.java, hibernate-core/src/test/java/org/hibernate/orm/test/schemaupdate/idgenerator/TableGeneratorNextValNullTest.java
This bug was first reported in 2013 and is still reproducible in 7.x.
https://hibernate.atlassian.net/browse/HHH-8535
Setting next_val to null causes an infinite loop.
The bugfix introduces a HibernateException.
There was already a PR proposed in 2019 by @dyolcekaj, but closed in 2024 without any reason given.
https://github.com/hibernate/hibernate-orm/pull/3073
My PR is a simplified version of the previous one.
For more information on …
=> HHH-8535 Generating an ID with TableGenerator causes a loop if next_val is NULL

hibernate-core/src/main/java/org/hibernate/id/IdentifierGeneratorHelper.java, hibernate-core/src/main/java/org/hibernate/id/IntegralDataTypeHolder.java
=> clean up code for conversions between IntegralDataTypeHolders

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
- https://hibernate.atlassian.net/browse/HHH-19526
=> HHH-19526 Avoid generating a QueryInterpretationCache.Key when the query cache is disabled

tooling/hibernate-maven-plugin/src/main/java/org/hibernate/orm/tooling/maven/HibernateEnhancerMojo.java
https://hibernate.atlassian.net/browse/HHH-19518
=> HHH-19518 Make hibernate-maven-plugin configuration parameters non-readonly

migration-guide.adoc
Add migration guide notice for `hibernate-scan-jandex`.
https://hibernate.atlassian.net/browse/HHH-18633
https://hibernate.atlassian.net/browse/HHH-19446
=> HHH-19446 HHH-18633 `hibernate-scan-jandex` migration guide

hibernate-core/src/main/java/org/hibernate/boot/jaxb/mapping/spi/JaxbLockableAttribute.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/AttributeProcessor.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/XmlAnnotationHelper.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/attr/CommonAttributeProcessing.java, hibernate-core/src/main/resources/org/hibernate/xsd/mapping/mapping-7.0.xsd, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/xml/BaseShop.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/xml/Consumer.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/xml/ConsumerItem.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/xml/ExplicitOptimisticLockAnnotationOnCollectionXmlOnlyTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/xml/NoDefaultOptimisticLockAnnotationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/xml/Supermarket.java, hibernate-core/src/test/resources/org/hibernate/orm/test/jpa/xml/ExplicitOptimisticLockAnnotationOnCollectionXmlOnlyTest.xml, hibernate-core/src/test/resources/org/hibernate/orm/test/jpa/xml/NoDefaultOptimisticLockAnnotationTest.xml, hibernate-testing/src/main/java/org/hibernate/testing/jdbc/SQLStatementInspector.java
backport of https://github.com/hibernate/hibernate-orm/pull/10295
https://hibernate.atlassian.net/browse/HHH-19528
https://hibernate.atlassian.net/browse/HHH-19495
=> Backport of HHH-19495 Remove the default "true" from optimistic-lock in the mapping xsd / HHH-19528   Version xml mapping is ignored

changelog.txt
A few not-yet-fixed issues got caught in the process.
=> Fix changelog for 7.0.1.Final

hibernate-core/src/main/java/org/hibernate/jdbc/Expectation.java, hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/DeleteOrUpsertOperation.java, hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/MergeOperation.java, hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/OptionalTableUpdateOperation.java, hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/UpsertOperation.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/UpsertVersionedTest.java
https://hibernate.atlassian.net/browse/HHH-19522
=> HHH-19522 upsert should not fail silently instead of throwing StaleObjectStateException

tooling/hibernate-maven-plugin/src/main/java/org/hibernate/orm/tooling/maven/HibernateEnhancerMojo.java
https://hibernate.atlassian.net/browse/HHH-19518
Backport of https://github.com/hibernate/hibernate-orm/pull/10280
=> [7.0] HHH-19518 Make hibernate-maven-plugin configuration parameters non-readonly

hibernate-core/src/main/java/org/hibernate/exception/internal/SQLStateConversionDelegate.java, hibernate-core/src/main/java/org/hibernate/jpa/spi/NativeQueryConstructorTransformer.java
=> Implement equals() and hashCode() for NativeQueryConstructorTransformer

hibernate-core/src/main/java/org/hibernate/jpa/spi/NativeQueryConstructorTransformer.java
to help the query interpretation cache
back port of #10306 to 7.0.
=> implement equals() / hashCode() for NativeQueryConstructorTransformer (backport #10306)

hibernate-core/src/main/java/org/hibernate/id/CompositeNestedGeneratedValueGenerator.java
Needed to fix https://github.com/hibernate/hibernate-reactive/issues/2154
=> Add methods to CompositeNestedGeneratedValueGenerator for Hibernate reactive

hibernate-core/src/main/java/org/hibernate/jdbc/Expectation.java, hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/DeleteOrUpsertOperation.java, hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/MergeOperation.java, hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/OptionalTableUpdateOperation.java, hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/UpsertOperation.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/UpsertVersionedTest.java
https://hibernate.atlassian.net/browse/HHH-19522
Backport of https://github.com/hibernate/hibernate-orm/pull/10289.
=> [7.0] HHH-19522 upsert should not fail silently instead of throwing StaleObjectStateException

hibernate-core/src/main/java/org/hibernate/internal/util/collections/CollectionHelper.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
=> Two small things

.idea/codeStyles/Project.xml
Because I keep getting imports replaced with * ... or is it actually the intention in ORM, and are start imports acceptable?
=> code style: increase the min number of imports for them to get converted to start imports

hibernate-core/src/main/java/org/hibernate/Interceptor.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcCallImpl.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcCallRefCursorExtractorImpl.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcParameterBindingsImpl.java, hibernate-core/src/main/java/org/hibernate/type/Type.java
=> Two things

hibernate-core/src/main/java/org/hibernate/Interceptor.java, hibernate-core/src/main/java/org/hibernate/boot/registry/selector/internal/StrategySelectorImpl.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/EntityCopyNotAllowedObserver.java, hibernate-core/src/main/java/org/hibernate/event/internal/EntityCopyObserverFactoryInitiator.java, hibernate-core/src/main/java/org/hibernate/event/spi/EntityCopyObserver.java, hibernate-core/src/main/java/org/hibernate/event/spi/EntityCopyObserverFactory.java, hibernate-core/src/main/java/org/hibernate/event/spi/MergeContext.java, hibernate-core/src/main/java/org/hibernate/proxy/HibernateProxy.java, hibernate-core/src/main/java/org/hibernate/type/TypeHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/interceptor/merge/MergeAuditingInterceptor.java, hibernate-core/src/test/java/org/hibernate/orm/test/interceptor/merge/MergeAuditingInterceptorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/interceptor/merge/MergeInterceptionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/interceptor/merge/MergeInterceptor.java
https://hibernate.atlassian.net/browse/HHH-19535
=> HHH-19535 Interceptor and merge()

hibernate-core/src/main/java/org/hibernate/cache/spi/entry/CacheEntryHelper.java, hibernate-core/src/main/java/org/hibernate/sql/results/internal/ResultsHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/cache/CachedReadOnlyArrayTest.java
https://hibernate.atlassian.net/browse/HHH-18909
=> HHH-18909 fix NPE for READ_ONLY cached entity with array

design/sqm.adoc, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/query/criteria/internal/NamedCriteriaQueryMementoImpl.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/NamedHqlQueryMementoImpl.java, hibernate-core/src/main/java/org/hibernate/query/hql/spi/SqmQueryImplementor.java, hibernate-core/src/main/java/org/hibernate/query/specification/internal/MutationSpecificationImpl.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractCommonQueryContract.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQueryParameter.java, hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/spi/SimpleHqlInterpretationImpl.java, hibernate-core/src/main/java/org/hibernate/query/spi/SqlOmittingQueryOptions.java, hibernate-core/src/main/java/org/hibernate/query/spi/SqmQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/SqmSelectionQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/spi/DelegatingSqmSelectionQueryImplementor.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/CriteriaEntityGraphTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/HqlEntityGraphTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/flush/NonTransactionalDataAccessTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/ASTParserLoadingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/query/NamedQueryTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/ToHqlStringTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/sqm/exec/ParameterTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/ast/SmokeTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/ast/SqlAstHelper.java
=> various improvements to the SqmQuery hierarchy and related SPIs

hibernate-core/src/main/java/org/hibernate/internal/util/collections/ArrayHelper.java, hibernate-core/src/main/java/org/hibernate/internal/util/collections/MapBackedClassValue.java, hibernate-core/src/main/java/org/hibernate/jpa/event/internal/CallbackRegistryImpl.java
=> cleanups around CallbackRegistryImpl

hibernate-core/src/main/java/org/hibernate/UnknownEntityTypeException.java, hibernate-core/src/main/java/org/hibernate/internal/CoordinatingEntityNameResolver.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
=> improve an exception message

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/AbstractSqmStatement.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/insert/SqmInsertSelectStatement.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/insert/SqmInsertValuesStatement.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/AbstractSqmSelectQuery.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQuerySpec.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectStatement.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSubQuery.java
=> optimize AbstractSqmStatement.getParameters() and eliminate copy/paste

hibernate-core/src/main/java/org/hibernate/query/sqm/spi/SqmCreationHelper.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/AbstractSqmExpression.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmEnumLiteral.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/from/SqmRoot.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSelectStatement.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmSubQuery.java
=> some minor cleanups around SqmSubQuery

hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/function/ExtractFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/OracleExtractFunction.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
This PR fixes an error when using `epoch` with dates on Oracle.
I added an overload of `extractPattern` (which is overridden in `OracleDialect`) to handle different `TemporalType`.
This new method is only used in `ExtractFunction` in context of `OracleDialect`.
https://hibernate.atlassian.net/browse/HHH-18837 …
=> HHH-18837 Oracle epoch extraction doesn't work with dates

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/cte/SqmCteTable.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tuple/internal/AnonymousTupleType.java, hibernate-core/src/test/java/org/hibernate/orm/test/subquery/MultipleIdenticalColumnsInSubqueryTest.java
Jira issue [HHH-19396](https://hibernate.atlassian.net/browse/HHH-19396)
When creating `SqlAstQueryPartProcessingStateImpl` in method `org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter#visitQuerySpec` parameter `deduplicateSelectionItems` must be set to `false` (see comment in moved code block)
When `selectStatement` contains same column more than once in method `org.hibernate.query.sqm.tree.cte.SqmCteTable#createStatementTable`, `SqmCteTable` constructor will be unable to properly resolve aliases. To prevent this alias in select clause selection should be used if exist, one from selectable node should be used otherwise. …
=> HHH-19396 cannot select the same column twice with different aliases while using cte

Jenkinsfile, local-build-plugins/src/main/groovy/local.java-module.gradle
=> Skip jacoco instrumentation/coverage in jenkins builds

documentation/src/main/asciidoc/querylanguage/Expressions.adoc, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
https://hibernate.atlassian.net/browse/HHH-18708
=> HHH-18708 add string() function to doc

Jenkinsfile, settings.gradle
https://hibernate.atlassian.net/browse/HHH-19548
=> HHH-19548 Upgrade to ByteBuddy 1.17.5

hibernate-core/src/main/java/org/hibernate/boot/model/internal/ImplicitToOneJoinTableSecondPass.java, hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/manytoone/jointable/ManyToOneImplicitJoinTableTest.java
https://hibernate.atlassian.net/browse/HHH-19564
=> HHH-19564 fix @ManyToOne @JoinTable with implicit table name

hibernate-core/src/main/java/org/hibernate/annotations/FilterDef.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnyBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/OneToOneSecondPass.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ToOneBinder.java
=> nontrivial refactoring to ToOneBinder

hibernate-core/src/main/java/org/hibernate/dialect/function/SqlFunction.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sql/spi/SelectInterpretationsKey.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmInterpretationsKey.java
https://hibernate.atlassian.net/browse/HHH-19560
=> HHH-19560 Remove TupleTransformer and ResultListTransformer from interpretation caching

tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockEntityPersister.java
https://hibernate.atlassian.net/browse/HHH-19570
=> HHH-19570 HQL with jpamodelgen fails compilation when querying by natural id named `id`

hibernate-core/src/main/java/org/hibernate/dialect/function/SqlFunction.java, hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sql/spi/SelectInterpretationsKey.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java, hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmInterpretationsKey.java
https://hibernate.atlassian.net/browse/HHH-19560
=> [6.6] HHH-19560 Remove TupleTransformer and ResultListTransformer from interpretation caching

hibernate-core/src/main/java/org/hibernate/metamodel/internal/InjectionHelper.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java, hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/inner/InnerEntityMetamodelTest.java
https://hibernate.atlassian.net/browse/HHH-19574
=> HHH-19574 fix metamodel population for nested entity classes

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java
https://hibernate.atlassian.net/browse/HHH-19577
=> HHH-19577 Avoid duplicate stack map frames for SetPropertyValues

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java
https://hibernate.atlassian.net/browse/HHH-19577
=> [7.0] HHH-19577 Avoid duplicate stack map frames for SetPropertyValues

hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java
https://hibernate.atlassian.net/browse/HHH-19577
=> [6.2] HHH-19577 Avoid duplicate stack map frames for SetPropertyValues

tooling/metamodel-generator/hibernate-processor.gradle, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/reactive/ReactiveTest.java, tooling/metamodel-generator/src/jakartaData/java/org/hibernate/processor/test/data/reactive/RepoWithPrimary.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractCriteriaMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaDeleteMethod.java
=> Fix @Delete queries for reactive repositories

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/QueryMethod.java
=> simplifications in QueryMethod

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultRefreshEventListener.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
=> minor refactoring to DefaultRefreshEventListener

hibernate-core/src/main/java/org/hibernate/sql/Template.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/TemplateTest.java
The formula `CAST(foo AS signed)` does not work on MySQL, because `signed` gets prefixed.
As suggested by @beikov on Jira, I implemented a bugfix in `Template#renderWhereStringTemplate`.
The fix is generic for all provided cast-types.
https://hibernate.atlassian.net/browse/HHH-9812
=> HHH-9812 @Formula with SQL cast function

hibernate-core/src/main/java/org/hibernate/event/spi/AbstractCollectionEvent.java, hibernate-core/src/main/java/org/hibernate/event/spi/PostCollectionRecreateEvent.java, hibernate-core/src/main/java/org/hibernate/event/spi/PostCollectionRemoveEvent.java, hibernate-core/src/main/java/org/hibernate/event/spi/PostCollectionUpdateEvent.java, hibernate-core/src/main/java/org/hibernate/event/spi/PreCollectionRecreateEvent.java, hibernate-core/src/main/java/org/hibernate/event/spi/PreCollectionRemoveEvent.java, hibernate-core/src/main/java/org/hibernate/event/spi/PreCollectionUpdateEvent.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/events/CollectionListenerInStatelessSessionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/events/EntityA.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/events/EntityB.java
@DavideD  note that this change breaks Hibernate Reactive 
https://hibernate.atlassian.net/browse/HHH-19523
=> HHH-19523 correctly initialize Pre/PostCollectionXxxxEvents from StatelessSession

hibernate-core/src/main/java/org/hibernate/query/sqm/tree/select/SqmQueryGroup.java, hibernate-core/src/main/java/org/hibernate/sql/Template.java
=> minor cleanups to SqmQueryGroup

documentation/src/main/asciidoc/introduction/Advanced.adoc, hibernate-core/src/main/java/org/hibernate/boot/SessionFactoryBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java, hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java, hibernate-core/src/main/java/org/hibernate/cfg/MultiTenancySettings.java, hibernate-core/src/main/java/org/hibernate/context/spi/AbstractCurrentSessionContext.java, hibernate-core/src/main/java/org/hibernate/context/spi/CurrentTenantIdentifierResolver.java, hibernate-core/src/main/java/org/hibernate/context/spi/TenantSchemaMapper.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/spi/DataSourceBasedMultiTenantConnectionProviderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcCoordinatorImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java, hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionDelegatorBaseImpl.java, hibernate-core/src/main/java/org/hibernate/generator/internal/TenantIdGeneration.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/ContextualJdbcConnectionAccess.java, hibernate-core/src/main/java/org/hibernate/internal/NonContextualJdbcConnectionAccess.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/relational/SchemaManager.java, hibernate-core/src/main/java/org/hibernate/relational/internal/SchemaManagerImpl.java, hibernate-core/src/main/java/org/hibernate/resource/jdbc/internal/LogicalConnectionManagedImpl.java, hibernate-core/src/main/java/org/hibernate/resource/jdbc/spi/JdbcSessionOwner.java, hibernate-core/src/main/java/org/hibernate/tool/schema/spi/SchemaManagementToolCoordinator.java, hibernate-core/src/test/java/org/hibernate/orm/test/multitenancy/SchemaBasedMultitenancyTest.java, hibernate-jfr/src/main/java/org/hibernate/event/jfr/internal/JfrEventMonitor.java
Rebase of #10372
https://hibernate.atlassian.net/browse/HHH-19559
https://hibernate.atlassian.net/browse/HHH-19580
=> HHH-19559, HHH-19580 schema-based multitenancy

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/cursor/internal/FallbackRefCursorSupport.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/cursor/internal/StandardRefCursorSupport.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/StatementPreparerImpl.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jdbc/internal/JdbcIsolationDelegate.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/DdlTransactionIsolatorJtaImpl.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcCallParameterExtractorImpl.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcCallParameterRegistrationImpl.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/StandardJdbcMutationExecutor.java, hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/AbstractResultSetAccess.java, hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/DeferredResultSetAccess.java, hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/DirectResultSetAccess.java, hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesResultSetImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/ResultSetAccess.java, hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/ExtractionContextImpl.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/Helper.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/GenerationTargetToDatabase.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/ImprovedExtractionContextImpl.java
ideally, such calls should always pass the SQL statement as a separate argument
=> audit calls to convert()

ci/build.sh, docker_db.sh, hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java, nightly.Jenkinsfile
https://hibernate.atlassian.net/browse/HHH-19225
=> HHH-19225: remove support for mariadb version's older than 10.6

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/TimestampWithTimeZoneJdbcType.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/ParameterTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/JsonMappingTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/XmlMappingTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/CteTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/StandardFunctionTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/timestamp/JdbcTimeCustomTimeZoneTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/timezones/UTCNormalizedInstantTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/tm/CMTTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/contributor/LiteralRenderingTest.java
=> Informix duration arithmetic

hibernate-core/src/main/java/org/hibernate/internal/util/SerializationHelper.java
=> clean up SerializationHelper

hibernate-core/src/main/java/org/hibernate/query/hql/internal/SqmTreeCreationHelper.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
=> various minor refactorings to AST conversion code

hibernate-core/src/main/java/org/hibernate/type/internal/ParameterizedTypeImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/JsonMappingTests.java
https://hibernate.atlassian.net/browse/HHH-19583
=> HHH-19583 Include parameterized info of parameterized type arguments

hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmUtil.java
=> Fix potential CCE due to casting the wrong object after instanceof check

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/AltibaseDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/AltibaseSqlAstTranslator.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixSqlAstTranslator.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SybaseASELegacySqlAstTranslator.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/TimesTenDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/TimesTenSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/sql/ast/SybaseASESqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SqmTreeCreationHelper.java, hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/QueryTimeOutTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaWindowFunctionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/JpaCrossJoinTests.java
=> functional improvements to InformixSqlAstTranslator

hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/GeneratedAnnotationBatchTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/GeneratedNoOpUpdateTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaMultiselectGroupByAndOrderByTest.java, hibernate-core/src/test/resources/org/hibernate/orm/test/query/joinfetch/ItemBid.hbm.xml
=> Informix continued

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/findoptions/FindOptionsTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/lock/LockTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/lock/StatementIsClosedAfterALockExceptionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/locking/JoinedInheritancePessimisticLockingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/locking/LockModeTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/locking/LockRefreshReferencedAndCascadingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/locking/LockRefreshReferencedTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/locking/jpa/FollowOnLockingTest.java
Informix only allows FOR UPDATE with single-table SELECTs
=> fix locking-related tests for Informix + improved impl of truncate()

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/function/CastFunction.java, hibernate-core/src/main/java/org/hibernate/query/sqm/function/NamedSqmFunctionDescriptor.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/QueryLiteral.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/FilterParameterTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
=> wrapping up work on InformixDialect

hibernate-core/src/test/java/org/hibernate/orm/test/datasource/DataSourceTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/AndNationalizedTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaWindowFunctionTest.java
=> try enabling these tests on Db2 🤞

hibernate-core/src/main/java/org/hibernate/query/sql/internal/SQLQueryParser.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/SQLQueryParserUnitTests.java
https://hibernate.atlassian.net/browse/HHH-19558
=> [6.6] HHH-19558: Fixed support of JDBC Escape Syntax

hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDeleteOrUpsertOperation.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/sql/ast/MariaDBSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/sql/ast/MySQLSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/sql/ast/SqlAstTranslatorWithOnDuplicateKeyUpdate.java, hibernate-core/src/main/java/org/hibernate/sql/model/jdbc/DeleteOrUpsertOperation.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/UpsertTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/UpsertVersionedTest.java
https://hibernate.atlassian.net/browse/HHH-19498
=> HHH-19498 - improve upserts on MySQL and Maria

ci/build.sh, hibernate-core/src/main/java/org/hibernate/dialect/aggregate/MySQLAggregateSupport.java, hibernate-core/src/main/java/org/hibernate/dialect/sql/ast/MariaDBSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/AttributeFactory.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteInsertHandler.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/identifier/composite/CompositeInheritanceFailTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/identifier/composite/CompositeInheritanceWorkingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/CriteriaWindowFunctionTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/BasicListTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/BasicSortedSetTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/BooleanArrayTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/DateArrayTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/DoubleArrayTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/EnumArrayTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/EnumSetConverterTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/EnumSetTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/FloatArrayTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/IntegerArrayTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/LongArrayTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/ShortArrayTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/StringArrayTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/TimeArrayTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/TimestampArrayTest.java
https://hibernate.atlassian.net/browse/HHH-19076
=> [7.0] Various backports

ci/build.sh, docker_db.sh, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2LegacyDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/DB2iLegacySqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2iDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/DB2zDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/sql/ast/DB2SqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/sql/ast/DB2iSqlAstTranslator.java, hibernate-core/src/main/java/org/hibernate/dialect/sql/ast/DB2zSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/DB2DialectTestCase.java, local-build-plugins/src/main/groovy/local.databases.gradle, nightly.Jenkinsfile
https://hibernate.atlassian.net/browse/HHH-18639
https://hibernate.atlassian.net/browse/HHH-18641
=> HHH-18639 Remove support for DB2 versions older than 11.1 and start testing with DB2 12.1

hibernate-core/src/main/java/org/hibernate/metamodel/internal/AttributeFactory.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/identifier/composite/CompositeInheritanceFailTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/identifier/composite/CompositeInheritanceWorkingTest.java
https://hibernate.atlassian.net/browse/HHH-19076
=> HHH-19076 Resolve member of MappedSuperclass specially

documentation/src/main/asciidoc/introduction/Configuration.adoc, documentation/src/main/asciidoc/introduction/Tuning.adoc
=> document log category org.hibernate.orm.jdbc.batch in Short Guide

Jenkinsfile, ci/jpa-3.1-tck.Jenkinsfile, ci/quarkus.Jenkinsfile
hey @mbellade, 👋🏻 😃 
I've notcied a couple hanging builds that you've approved: 
* https://ci.hibernate.org/job/hibernate-orm-quarkus/job/PR-10488/4/console
* https://ci.hibernate.org/job/hibernate-orm-tck-3.1/job/PR-10488/4/console
and seems like there is a double-check in the build config. and while at it .. I've removed the use of docker registry creds
(I'll leave it to you to re-re-approve the builds 😃)
For more information on …
=> Only require pull request build approval in the check stage / Do not use docker.withRegistry

hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDirtyCheckEventListener.java, hibernate-core/src/test/java/org/hibernate/orm/test/IsDirtyImmutableTest.java
https://hibernate.atlassian.net/browse/HHH-19604
=> HHH-19604 fix Session.isDirty() with @Immutable entity

Jenkinsfile, ci/jpa-3.2-tck.Jenkinsfile, ci/quarkus.Jenkinsfile
Hey, so I was thinking we can test quarkus against the latest branched-out version (see the `def latestQuarkusVersion`), or do we do it only for the LTS versions ? 
+ there's also the cleanup of the `docker.withRegistry`, we shouldn't be using those unless we need the creds (like in that remaining quay case) …
=> Add quarkus testing to 7.0 branch / Do not use docker withregistry

hibernate-core/src/main/java/org/hibernate/internal/util/collections/AbstractPagedArray.java, hibernate-core/src/test/java/org/hibernate/orm/test/util/InstanceIdentityMapTest.java
https://hibernate.atlassian.net/browse/HHH-19582
=> HHH-19582 NullPointerException in org.hibernate.internal.util.collections.AbstractPagedArray#clear (backport from main)

tooling/metamodel-generator/src/main/java/org/hibernate/processor/ClassWriter.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/Context.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractAnnotatedMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractCriteriaMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractFinderMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/IdFinderMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/LifecycleMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/QueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/RepositoryConstructor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/Constants.java
https://hibernate.atlassian.net/browse/HHH-19606
=> HHH-19606 experimental Spring support for Jakarta Data repositories

documentation/src/main/asciidoc/repositories/Configuration.adoc
=> mention Spring-specific stuff in Hibernate Data Repositories doc

hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/Foo.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/FooType.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/NegatedInPredicateTest.java
not in is not handled correctly for multi-column joins. This pull request fixes the problem.
Compositions of not with in on lists fail for dialects not supporting record-level construction, such as DB2Dialect.
Using not with in with such dialects can lead to dangerous outcomes, such as all records being returned from a query. This is because the query condition always evaluates to either true or false (depending on the details of the query) because multi-column joins are not handled correctly. …
=> HHH-19497 Test for composition of 'not' 'in' restrictions

hibernate-core/src/main/java/org/hibernate/query/sql/internal/SQLQueryParser.java
Same fix as https://github.com/hibernate/hibernate-orm/pull/10369 for the 6.6 branch.
The unit test class does not exist on branch 6.6 and could not simply be moved over, without other changes.
https://hibernate.atlassian.net/browse/HHH-19558
=> HHH-19558: [6.6 backport] Fixed support of JDBC escape syntax 

hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/Foo.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/FooType.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/NegatedInPredicateTest.java
https://hibernate.atlassian.net/browse/HHH-19497
=> [7.0] HHH-19497 fixes incorrect implementation of 'negated in'

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/ExportableColumnHelper.java, hibernate-core/src/main/java/org/hibernate/mapping/Collection.java, hibernate-core/src/main/java/org/hibernate/mapping/OneToMany.java, hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java, hibernate-core/src/main/java/org/hibernate/mapping/Value.java
on databases where this is required
also enable support for table partitioning on MySQL and Maria
https://hibernate.atlassian.net/browse/HHH-19608
=> HHH-19608 automatically add @PartitionKey to the primary key

hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ColumnsBuilder.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DriverManagerConnectionProviderImpl.java, hibernate-core/src/main/java/org/hibernate/persister/entity/DiscriminatorType.java, hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/AbstractDeleteCoordinator.java, hibernate-core/src/main/java/org/hibernate/type/AbstractStandardBasicType.java, hibernate-core/src/main/java/org/hibernate/type/ComponentType.java, hibernate-core/src/main/java/org/hibernate/type/TypeHelper.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/AbstractArrayJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ArrayJavaType.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/ArrayJdbcType.java, hibernate-core/src/main/java/org/hibernate/type/internal/ConvertedBasicTypeImpl.java
=> Various code cleanups

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/RepositoryConstructor.java
this is a partial fix: need to consider other session types eventually
https://hibernate.atlassian.net/browse/HHH-19606
=> HHH-19606 allow resource accessor method of type StatelessSession in Spring

ci/quarkus.Jenkinsfile
=> Make sure that quarkus-version script returns the stdout in the Quarkus Jenkins job

hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/Foo.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/FooType.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/NegatedInPredicateTest.java, settings.gradle
https://hibernate.atlassian.net/browse/HHH-19497
=> [6.2] HHH-19497 fixes incorrect implementation of 'negated in'

hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/SingleTableConstraintsTest.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectContext.java
https://hibernate.atlassian.net/browse/HHH-19616
https://hibernate.atlassian.net/browse/HHH-19614
=> HHH-19616 HHH-19614 add test

hibernate-core/src/main/java/org/hibernate/action/internal/UnresolvedEntityInsertActions.java, hibernate-core/src/main/java/org/hibernate/boot/model/convert/internal/AttributeConverterManager.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/JdbcLogging.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CollectionEntry.java, hibernate-core/src/main/java/org/hibernate/generator/internal/CurrentTimestampGeneration.java, hibernate-core/src/main/java/org/hibernate/generator/internal/SourceGeneration.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/HiLoOptimizer.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/LegacyHiLoAlgorithmOptimizer.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/PooledOptimizer.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceGeneratorLogger.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStructure.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStyleGenerator.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/TableGenerator.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/TableGeneratorLogger.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/TableStructure.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jdbc/internal/JdbcIsolationDelegate.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaIsolationDelegate.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/DdlTransactionIsolatorProvidedConnectionImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/hhh12973/PostgreSQLSequenceGeneratorWithSerialTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/hhh12973/SequenceMismatchStrategyFixWithSequenceGeneratorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/hhh12973/SequenceMismatchStrategyLogTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/sequence/NegativeValueSequenceTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/schematools/TestExtraPhysicalTableTypes.java
=> More work on logging

docker_db.sh
This PR aims at removing `CREATE ANY INDEX` privilege for Oracle during tests.
https://hibernate.atlassian.net/browse/HHH-19553
=> HHH-19553 - Remove CREATE ANY INDEX privilege for Oracle

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SingleStoreDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SingleStoreSqlAstTranslator.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonArrayAggFunction.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonArrayAppendFunction.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonArrayFunction.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonArrayInsertFunction.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonExistsFunction.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonMergepatchFunction.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonObjectAggFunction.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonObjectFunction.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonQueryFunction.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonRemoveFunction.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonSetFunction.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/json/SingleStoreJsonValueFunction.java
HHH-19297
Small improvement for community SingleStoreDialect
https://hibernate.atlassian.net/browse/HHH-19297
=> HHH-19297 Register SingleStore json functions to community SingleStoreDialect

hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/InheritanceToOneSubtypeJoinGroupByTest.java
https://hibernate.atlassian.net/browse/HHH-19368
Backport of https://github.com/hibernate/hibernate-orm/pull/10533
=> [6.6] HHH-19368 Group by and single-table inheritance sub-select query error

tooling/metamodel-generator/src/main/java/org/hibernate/processor/Context.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/HibernateProcessor.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CDIAccessorMetaAttribute.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CDITypeMetaAttribute.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/NonManagedMetamodel.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/Constants.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/TypeUtils.java, tooling/metamodel-generator/src/quarkusOrmPanache/java/org/hibernate/processor/test/ormPanache/QuarkusOrmPanacheTest.java
Supports Panache2, which comes in a new package `io.quarkus.hibernate.panache` (since it supports both ORM and HR, they are not in the package name anymore). With new entity supertype, as well as repository supertypes and way of working.
Rough example entity:
```java
@Entity
public class MyEntity extends WithId.AutoLong implements PanacheEntity.Stateless {
public String name;
public interface Repo {
@Find
MyEntity findSomeone(String name);
}
}
```
This will generate the following:
```java
@StaticMetamodel(MyEntity.class)
@Generated("org.hibernate.processor.HibernateProcessor")
public abstract class MyEntity_ extends WithId_ {
/**
* Implements repository {@link org.acme.MyEntity.Repo}
**/
@Dependent
@Generated("org.hibernate.processor.HibernateProcessor")
public static class Repo_ …
```
=> Preliminary support for Panache2

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/function/GaussDBMinMaxFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/AvgFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/CountFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/GenerateSeriesArgumentTypeResolver.java, hibernate-core/src/main/java/org/hibernate/dialect/function/HypotheticalSetFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/InverseDistributionFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/ListaggFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/ListaggGroupConcatEmulation.java, hibernate-core/src/main/java/org/hibernate/dialect/function/ListaggStringAggEmulation.java, hibernate-core/src/main/java/org/hibernate/dialect/function/ModeStatsModeEmulation.java, hibernate-core/src/main/java/org/hibernate/dialect/function/PostgreSQLMinMaxFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/AbstractArrayFillFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/ArrayAggFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/ArrayAndElementArgumentTypeResolver.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/ArrayContainsArgumentTypeResolver.java, hibernate-core/src/main/java/org/hibernate/dialect/function/array/ArrayIncludesArgumentTypeResolver.java, hibernate-core/src/main/java/org/hibernate/dialect/function/json/JsonArrayAggFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/json/JsonObjectAggFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/xml/SQLServerXmlAggFunction.java, hibernate-core/src/main/java/org/hibernate/dialect/function/xml/XmlAggFunction.java, hibernate-core/src/main/java/org/hibernate/query/sqm/function/AbstractSqmSelfRenderingFunctionDescriptor.java, hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/ArgumentTypesValidator.java, hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/FunctionArgumentTypeResolver.java, hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/StandardArgumentsValidators.java, hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/StandardFunctionArgumentTypeResolvers.java, hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/StandardFunctionReturnTypeResolvers.java, hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/internal/AbstractFunctionArgumentTypeResolver.java, hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/internal/PatternRenderer.java, hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/internal/SetReturningFunctionTypeResolverBuilder.java, hibernate-vector/src/main/java/org/hibernate/vector/VectorArgumentTypeResolver.java
=> modernize some code in o.h.query.sqm.produce.function

docker_db.sh
This MR adds support for using custom EDB image for testing by providing DB_IMAGE_EDB env variable. If DB_IMAGE_EDB is not set, it will build the edb image in Hibernate, as before.
=> Add support for testing with custom EDB image

.github/dependabot.yml, documentation/documentation.gradle, hibernate-core/hibernate-core.gradle, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/type/PostgreSQLCastingIntervalSecondJdbcType.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/usertype/PostgreSQLMultipleTypesOtherContributorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/usertype/inet/PostgreSQLInetTypesOtherContributorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/usertype/inet/PostgreSQLInetTypesOtherTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/procedure/PostgreSQLFunctionProcedureTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/procedure/PostgreSQLStoredProcedureTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/PostgresIntervalSecondTest.java, hibernate-testing/src/main/java/org/hibernate/testing/jdbc/SharedDriverManagerConnectionProviderImpl.java, hibernate-testing/src/main/java/org/hibernate/testing/junit4/CustomRunner.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java, local-build-plugins/src/main/groovy/local.databases.gradle, local-build-plugins/src/main/groovy/local.java-module.gradle, settings.gradle
https://hibernate.atlassian.net/browse/HHH-19624
=> HHH-19624 Test EDB with EDB drivers

hibernate-core/src/main/java/org/hibernate/boot/archive/scan/internal/DisabledScanner.java, hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/ScanningCoordinator.java, hibernate-scan-jandex/src/main/java/org/hibernate/archive/scan/internal/ClassDescriptorImpl.java, hibernate-scan-jandex/src/main/java/org/hibernate/archive/scan/internal/MappingFileDescriptorImpl.java, hibernate-scan-jandex/src/main/java/org/hibernate/archive/scan/internal/PackageDescriptorImpl.java, hibernate-scan-jandex/src/main/java/org/hibernate/archive/scan/internal/ScanResultCollector.java, hibernate-scan-jandex/src/main/java/org/hibernate/archive/scan/internal/ScanResultImpl.java, hibernate-scan-jandex/src/main/java/org/hibernate/archive/scan/internal/StandardScannerFactory.java, hibernate-scan-jandex/src/main/java/org/hibernate/archive/scan/spi/AbstractScannerImpl.java
=> Use record types In scanner package / avoid URL.equals()

hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/inheritance/joined/JoinedDiscriminatorSameChildTableTest.java
https://hibernate.atlassian.net/browse/HHH-19457
Backport of https://github.com/hibernate/hibernate-orm/pull/10569
=> [7.0] HHH-19457 Inheritance with type JOINED not working in a related entity

docker_db.sh, documentation/documentation.gradle, gradle/databases.gradle, gradle/java-module.gradle, hibernate-core/hibernate-core.gradle, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLCastingIntervalSecondJdbcType.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/usertype/PostgreSQLMultipleTypesOtherContributorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/usertype/inet/PostgreSQLInetTypesOtherContributorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/id/usertype/inet/PostgreSQLInetTypesOtherTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/procedure/PostgreSQLFunctionProcedureTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/procedure/PostgreSQLStoredProcedureTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/type/PostgresIntervalSecondTest.java, hibernate-testing/src/main/java/org/hibernate/testing/jdbc/SharedDriverManagerConnectionProviderImpl.java, hibernate-testing/src/main/java/org/hibernate/testing/junit4/CustomRunner.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java, settings.gradle
https://hibernate.atlassian.net/browse/HHH-19624
=> [6.6] HHH-19624 Test EDB with EDB drivers

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/queryhint/OracleQueryHintTest.java
https://hibernate.atlassian.net/browse/HHH-19261
=> HHH-19261 - query hints in Oracle are not concatenated with comma's, but with spaces - do not merge yet!

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/OracleLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java, hibernate-core/src/test/java/org/hibernate/orm/test/queryhint/OracleQueryHintTest.java
https://hibernate.atlassian.net/browse/HHH-19261
=> HHH-19261 - query hints in Oracle are not concatenated with comma's, but with spaces

tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/TypeUtils.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/embeddable/ForcedAccessTypeTest.java
Jira issue [HHH-19549](https://hibernate.atlassian.net/browse/HHH-19549)
Always use access type specified when `@Access` annotation is present on embeddable.
[HHH-19549]: https://hibernate.atlassian.net/browse/HHH-19549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …
=> HHH-19549 Hibernate Processor: When embeddable is annotated by @Access enclosing element must not change access type

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/TeradataDialect.java
HHH-19619: Fix support for Truncate Table in Teradata dialect (and add extra keyword found in testing)
https://hibernate.atlassian.net/browse/HHH-19619
=> HHH-19619: Fix support for Truncate Table in Teradata dialect

ci/build.sh, local-build-plugins/src/main/groovy/local.databases.gradle, local-build-plugins/src/main/groovy/local.java-module.gradle, settings.gradle
Allows the test suite to be run locally against the Teradata dialect.  Needs a user named "hibernate_orm_test" to be created, along with a database of the same name. The `dbHost` variable must be passed as part of the build designating the hostname or IP address of the database server.
Not all tests pass cleanly with the dialect, but this PR at least gives developers the option of running them against a local Teradata DB.
For more …
=> HHH-19619: Allow test suite to be run locally against Teradata dialect

hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableFetchImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableForeignKeyResultImpl.java
In Hibernate Reactive, `ReactiveEmbeddableFetchImpl#createInitializers`
needs to access the value to override the initializer created by ORM.
Allows Hibernate Reactive to upgrade to ORM 7.1
https://hibernate.atlassian.net/browse/HHH-19639
=> Add Add EmbeddableFetchImpl#getNullIndicatorResult

build.gradle, ci/release/Jenkinsfile
Change CI release script to use Java 11 to (hopefully) fix javadoc generation.
Also removed no longer used Gradle plugin.
=> fixes for 5.6 javadoc generation

changelog.txt
Looking at the tag difference:
- https://github.com/hibernate/hibernate-orm/compare/7.0.6...7.0.7
and also at the release version at JIRA: 
- https://hibernate.atlassian.net/projects/HHH/versions/34298/tab/release-report-all-issues
some of the tickets weren't actually released. It seems that anything in the version gets included in the changelog but then only the resolved ones are kept in the version ... so we probably also need to adjust the generation of the changelog to filter out the "in-progress" ones ? …
=> Adjust the changelog to match what was release

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AggregateComponentSecondPass.java, hibernate-core/src/main/java/org/hibernate/dialect/AbstractPostgreSQLStructJdbcType.java, hibernate-core/src/main/java/org/hibernate/dialect/XmlHelper.java, hibernate-core/src/main/java/org/hibernate/dialect/aggregate/DB2AggregateSupport.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AnyDiscriminatorPart.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AnyKeyPart.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/DiscriminatedAssociationMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SelectableMappingImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/SelectableMappingsImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/AggregateEmbeddableInitializerImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableExpressionResultImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableFetchImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableForeignKeyResultImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableInitializerImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableResultImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/embeddable/StructEmbeddableArrayEmptyTest.java
https://hibernate.atlassian.net/browse/HHH-19639
https://hibernate.atlassian.net/browse/HHH-19575
=> HHH-19575 Ensure null struct is fetched as null embeddable

hibernate-core/src/main/java/org/hibernate/generator/values/internal/GeneratedValuesMappingProducer.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/main/java/org/hibernate/query/results/internal/DomainResultCreationStateImpl.java, hibernate-core/src/main/java/org/hibernate/query/results/internal/ResultSetMappingImpl.java, hibernate-core/src/main/java/org/hibernate/sql/ast/spi/SqlAstCreationState.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/NativeQueryJoinTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/embeddedid/OneToOneEmbeddedIdTest.java
https://hibernate.atlassian.net/browse/HHH-19524
=> HHH-19524 @OnetoOne relationship unnecessary joins in nativeQuery

hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/lob/LargeObjectMappingTest.java
https://hibernate.atlassian.net/browse/HHH-16253
Backport of https://github.com/hibernate/hibernate-orm/pull/10593
=> [6.6] HHH-16253 - Schema Validation Failure With Audited (N)Clob Column

hibernate-core/src/main/java/org/hibernate/engine/jdbc/JdbcLogging.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/ExtractedDatabaseMetaDataImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/GlobalTemporaryTableStrategy.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/PersistentTableStrategy.java, hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jdbc/internal/JdbcIsolationDelegate.java, hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/ExtractionContextImpl.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/DdlTransactionIsolatorProvidedConnectionImpl.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/JdbcConnectionAccessConnectionProviderImpl.java, hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/JdbcConnectionAccessProvidedConnectionImpl.java
=> more improvements to JDBC-related logging

hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DatabaseConnectionInfoImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DriverManagerConnectionProviderImpl.java
=> improvements to DriverManagerConnectionProvider + SessionFactoryOptionsBuilder

hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/generator/values/internal/GeneratedValuesHelper.java, hibernate-core/src/main/java/org/hibernate/generator/values/internal/GeneratedValuesImpl.java, hibernate-core/src/main/java/org/hibernate/generator/values/internal/GeneratedValuesMappingProducer.java, hibernate-core/src/main/java/org/hibernate/generator/values/internal/TableUpdateReturningBuilder.java, hibernate-core/src/main/java/org/hibernate/id/insert/AbstractReturningDelegate.java, hibernate-core/src/main/java/org/hibernate/id/insert/AbstractSelectingDelegate.java, hibernate-core/src/main/java/org/hibernate/id/insert/BasicSelectingDelegate.java, hibernate-core/src/main/java/org/hibernate/id/insert/GetGeneratedKeysDelegate.java, hibernate-core/src/main/java/org/hibernate/id/insert/InsertReturningDelegate.java, hibernate-core/src/main/java/org/hibernate/id/insert/SybaseJConnGetGeneratedKeysDelegate.java, hibernate-core/src/main/java/org/hibernate/id/insert/UniqueKeySelectingDelegate.java, hibernate-core/src/main/java/org/hibernate/internal/OptimisticLockHelper.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/ExecuteWithTemporaryTableHelper.java, hibernate-core/src/main/java/org/hibernate/result/internal/OutputsImpl.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcSelectExecutorStandardImpl.java, hibernate-core/src/main/java/org/hibernate/sql/model/ast/builder/TableUpdateBuilderStandard.java, hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/spi/JdbcValuesSourceProcessingOptions.java
=> some cleanups (lots of 'var')

hibernate-core/src/main/java/org/hibernate/loader/internal/CacheLoadHelper.java
The change is needed for [Hibernate Reactive](https://github.com/hibernate/hibernate-reactive/pull/2371)
=> Make PersistenceContextEntry#EntityStatus public for Hibernate Reactive

gradle/java-module.gradle, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/blob/BasicBlobTest.java, hibernate-testing/src/main/java/org/hibernate/testing/bytecode/enhancement/extension/engine/BytecodeEnhancedTestEngine.java, tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
https://hibernate.atlassian.net/browse/HHH-19516
=> Ensure compatibility with JUnit 5.12+

documentation/src/main/asciidoc/introduction/Advanced.adoc, documentation/src/main/asciidoc/userguide/chapters/domain/collections.adoc, documentation/src/main/asciidoc/userguide/chapters/pc/BytecodeEnhancement.adoc, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/EnhancementContext.java, tooling/hibernate-ant/src/main/java/org/hibernate/tool/enhance/EnhancementTask.java, tooling/hibernate-gradle-plugin/src/main/java/org/hibernate/orm/tooling/gradle/enhance/EnhancementHelper.java, tooling/hibernate-maven-plugin/src/main/java/org/hibernate/orm/tooling/maven/EnhancementContext.java
https://hibernate.atlassian.net/browse/HHH-19661
=> HHH-19661 - Deprecate enhancement support for "extended" enhancement

design/fk.adoc, documentation/src/main/asciidoc/userguide/chapters/pc/BytecodeEnhancement.adoc, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/BiDirectionalAssociationHandler.java, hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/EnhancementContext.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/BiDirectionalFetch.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/list/ListMappingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/association/OneToManyAssociationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/association/OneToOneAssociationTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/basic/ExtendedAssociationManagementTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/graphs/EntityGraphTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/onetomany/OneToManyBidirectionalTest.java, hibernate-core/src/test/resources/org/hibernate/orm/test/legacy/Marelo.hbm.xml, hibernate-core/src/test/resources/org/hibernate/orm/test/mapping/schema.sql, hibernate-envers/src/main/java/org/hibernate/envers/AuditMappedBy.java, hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/CollectionMappedByResolver.java, hibernate-envers/src/main/java/org/hibernate/envers/event/spi/BaseEnversEventListener.java, hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/ToOneIdMapper.java, tooling/hibernate-ant/src/main/java/org/hibernate/tool/enhance/EnhancementTask.java, tooling/hibernate-gradle-plugin/src/main/java/org/hibernate/orm/tooling/gradle/enhance/EnhancementHelper.java, tooling/hibernate-maven-plugin/src/main/java/org/hibernate/orm/tooling/maven/EnhancementContext.java
https://hibernate.atlassian.net/browse/HHH-19660
=> HHH-19660 - Deprecate enhancement support for automatic association management

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/H2LegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/lock/internal/H2LockingSupport.java
https://hibernate.atlassian.net/browse/HHH-19667
=> HHH-19667 Support H2 2.2.220 for update clause enhancements

hibernate-integrationtest-java-modules/hibernate-integrationtest-java-modules.gradle, local-build-plugins/src/main/groovy/local.java-module.gradle, local-build-plugins/src/main/groovy/local.publishing-java-module.gradle, tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
https://hibernate.atlassian.net/browse/HHH-19673
It seems this one-liner does the trick for the bytecode version of compiled class files (obviously, since that's handled by the `java-module` plugin). I'm hoping this is all Gradle needs to accept using a module in a project using Java 17.
=> HHH-19673 hibernate-gradle-plugin 7.0.0.CR1 wrongly requires Java 21+

hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteInsertHandler.java, hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/InsertExecutionDelegate.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/JoinInheritanceInsertTest.java
https://hibernate.atlassian.net/browse/HHH-19669
=> HHH-19669 hql insert fails for entity with join inheritance on Oracle

hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/spi/JdbcTypeRegistry.java
https://hibernate.atlassian.net/browse/HHH-19675
Backport of https://github.com/hibernate/hibernate-orm/pull/10681
=> [7.0] HHH-19675 JdbcTypeRegistry#hasRegisteredDescriptor should account for constructed types

hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/spi/JdbcTypeRegistry.java
https://hibernate.atlassian.net/browse/HHH-19675
Backport of https://github.com/hibernate/hibernate-orm/pull/10681
=> [6.6] HHH-19675 JdbcTypeRegistry#hasRegisteredDescriptor should account for constructed types

hibernate-core/src/main/java/org/hibernate/jpa/event/internal/CallbackDefinitionResolver.java
https://hibernate.atlassian.net/browse/HHH-19671
=> HHH-19671 - Avoid issuing a callback warning when a class defines an IdClass and has lifecycle callbacks

hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/AbstractEntityManagerFactoryScope.java
=> Get rid of annoying warning due to the deprecated gradle CloseableResource interface

documentation/src/main/asciidoc/introduction/Advanced.adoc, migration-guide.adoc
=> Gradle plugin bytecode enhancement configuration: updated the documentaiton and migration guide

hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DomainModelExtension.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/ServiceRegistryExtension.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/SessionFactoryExtension.java
=> Remove additional uses of the deprecated gradle CloseableResource interface

hibernate-core/src/main/antlr/org/hibernate/grammars/ordering/OrderingLexer.g4, hibernate-core/src/main/antlr/org/hibernate/grammars/ordering/OrderingParser.g4, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ManyToManyCollectionPart.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/PluralAttributeMappingImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/OrderByFragmentImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/OrderByFragmentTranslator.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/CollectionPartPath.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/DomainPathContinuation.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/FkDomainPathContinuation.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/PathConsumer.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/PathResolutionException.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/PluralAttributePath.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/RootSequencePart.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/StandardHqlTranslator.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AnnotationMetaEntity.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/util/Constants.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/orderedcollection/PrintJob.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/orderedcollection/Printer.java, tooling/metamodel-generator/src/test/java/org/hibernate/processor/test/orderedcollection/SortedCollectionTest.java
https://hibernate.atlassian.net/browse/HHH-19678
https://hibernate.atlassian.net/browse/HHH-19676
=> HHH-19678, HHH-19676 validation of @OrderBy

hibernate-core/src/main/java/org/hibernate/metamodel/internal/AttributeFactory.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AbstractPluralAttribute.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/BagAttributeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/ListAttributeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MapAttributeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/PluralAttributeBuilder.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/SetAttributeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/SingularAttributeImpl.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/MockSessionFactory.java
and thereby simplify the MockSessionFactory
=> get rid of an unused parameter in constrictors of XxxxAttributeImpl

hibernate-agroal/src/main/java/org/hibernate/agroal/internal/AgroalConnectionProvider.java, hibernate-c3p0/src/main/java/org/hibernate/c3p0/internal/C3P0ConnectionProvider.java, hibernate-c3p0/src/test/java/org/hibernate/test/c3p0/C3P0DifferentIsolationLevelTest.java, hibernate-c3p0/src/test/java/org/hibernate/test/c3p0/C3P0EmptyIsolationLevelTest.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/HSQLLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/SybaseDialect.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/ConnectionCreator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/ConnectionCreatorFactory.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DatabaseConnectionInfoImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DatasourceConnectionProviderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DriverManagerConnectionProviderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/PoolState.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/PooledConnections.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/spi/DataSourceBasedMultiTenantConnectionProviderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/spi/DatabaseConnectionInfo.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/ExtractedDatabaseMetaDataImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/spi/ExtractedDatabaseMetaData.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/spi/IdentifierHelperBuilder.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/spi/SQLStateType.java, hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStyleGenerator.java, hibernate-core/src/test/java/org/hibernate/orm/test/datasource/TestDataSourceConnectionProvider.java, hibernate-core/src/test/java/org/hibernate/orm/test/jdbc/env/NoDatabaseMetaDataTest.java, hibernate-hikaricp/src/main/java/org/hibernate/hikaricp/internal/HikariCPConnectionProvider.java
https://hibernate.atlassian.net/browse/HHH-19653
=> HHH-19653 replace lost test + log more db info

hibernate-agroal/hibernate-agroal.gradle
HHH-19686 - Add implementation dependency to agroal-pool from hibernate-agroal
https://hibernate.atlassian.net/browse/HHH-19686
=> HHH-19686 - Add implementation dependency to agroal-pool from hibernate-agroal

documentation/src/main/asciidoc/introduction/Configuration.adoc, documentation/src/main/asciidoc/introduction/Introduction.adoc
the dependency is now transitive
=> document that 'io.agroal:agroal-pool' is no longer needed

documentation/src/main/asciidoc/introduction/Tuning.adoc
=> mention 'org.hibernate.orm:hibernate-hikaricp' in doc

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/lock/internal/GaussDBLockingSupport.java, hibernate-core/src/test/java/org/hibernate/orm/test/locking/options/ConnectionLockTimeoutTests.java
The current Hibernate ORM implementation lacks proper support for GaussDB's lock timeout (lockwait_timeout). The following adaptations are required:
1. ​Correctly parse lockwait_timeout return values​ (support formats like "0", "4s", "20min", etc.).
2. ​**Support setting lock timeout via set local lockwait_timeout**​ (unit: milliseconds).
3. ​**Handle special cases for SKIP_LOCKED and NO_WAIT**​ (throw explicit exceptions if GaussDB does not support them).
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the …
=> HHH-19682 - Add Support for GaussDB Lock Timeout (lockwait_timeout)

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
=> let's not abuse Objects.toString to handle null

hibernate-vector/src/test/java/org/hibernate/vector/OracleByteVectorTest.java, hibernate-vector/src/test/java/org/hibernate/vector/OracleDoubleVectorTest.java, hibernate-vector/src/test/java/org/hibernate/vector/OracleFloatVectorTest.java, hibernate-vector/src/test/java/org/hibernate/vector/OracleGenericVectorTest.java
=> Skip some vector tests on Oracle due to a bug in version 23.9

hibernate-core/src/main/java/org/hibernate/query/hql/internal/SqmPathRegistryImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/SemanticQueryWalker.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmPath.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedCteJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedDerivedJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedDerivedRoot.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedDerivedRootJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCorrelatedRoot.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmCteRoot.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmDerivedRoot.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/from/SqmCteJoin.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/from/SqmDerivedJoin.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/CorrelationCteDerivedJoinTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/CorrelationCteDerivedRootTest.java
https://hibernate.atlassian.net/browse/HHH-17522
=> HHH-17522 Test and fix correlation of CTE and derived roots and joins

hibernate-core/src/main/java/org/hibernate/sql/Template.java, hibernate-core/src/test/java/org/hibernate/orm/test/sql/TemplateTest.java
This is a bit simpler than #10724, I believe.
https://hibernate.atlassian.net/browse/HHH-19695
=> HHH-19695 alternative solution

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/test/java/x/IdClassSingleOneToOneTest.java
https://hibernate.atlassian.net/browse/HHH-19688
=> HHH-19688 @IdClass with single @Id @OneToOne field

hibernate-core/src/main/java/org/hibernate/boot/jaxb/hbm/transform/HbmXmlTransformer.java, hibernate-core/src/main/java/org/hibernate/boot/jaxb/hbm/transform/TransformationState.java, hibernate-core/src/main/java/org/hibernate/boot/jaxb/hbm/transform/XmlPreprocessor.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/InheritanceState.java
=> more use of 'var'

hibernate-core/src/main/java/org/hibernate/id/enhanced/TableStructure.java
https://hibernate.atlassian.net/browse/HHH-19707
When @GeneratedValue(strategy = GenerationType.TABLE) is used with Cloud Spanner(using google maintained dialect, the generator’s InitCommand INSERT statement fails because it does not explicitly list the target column names.
Cloud Spanner requires all INSERT statements to specify column names — even when inserting into a single-column table. Since Hibernate’s default table generator omits the column list in its InitCommand , Spanner rejects the statement, preventing the sequence table from being initialized.
and can be relicensed under the terms of the …
=> HHH-19707 - Include value column name in TableStructure InitCommand

hibernate-core/src/main/java/org/hibernate/persister/entity/mutation/AbstractMutationCoordinator.java, hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchOffOnlyForOptimisticallyLocked.java
It, particularly, enables reporting the exact entity that failed optimistic lock.
Redoing #8864 for the affected branch, v6.
v7 has an improvement that makes the setting irrelevant, but I think that backporting it is more risky.
If/when this is merged, would you like me to port just the test case to v7, so that reporting the failed versioned entity updated is not lost again? …
=> HHH-18621 Restore hibernate.jdbc.batch_versioned_data function in H6

hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/UserSuppliedConnectionProviderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/spi/AbstractDataSourceBasedMultiTenantConnectionProviderImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/spi/AbstractMultiTenantConnectionProvider.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/spi/DataSourceBasedMultiTenantConnectionProviderImpl.java
=> fix more weird implementations of unwrap()

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/NativeQueryResultBuilderColumnDeduplicationTest.java
https://hibernate.atlassian.net/browse/HHH-19712
=> [7.1] HHH-19712 Column deduplication leads to wrong alias calculation for native query alias expansion

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/sql/NativeQueryResultBuilderColumnDeduplicationTest.java
https://hibernate.atlassian.net/browse/HHH-19712
=> [6.2] HHH-19712 Column deduplication leads to wrong alias calculation for native query alias expansion

hibernate-core/src/main/java/org/hibernate/query/sqm/function/SelfRenderingSqmWindowFunction.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/sqm/SelfRenderingSqmFunctionWithoutArgumentsTest.java
Jira issue [HHH-19719](https://hibernate.atlassian.net/browse/HHH-19719)
Checking if list of arguments is non empty before checking if first argument is instance of `SqmDistinct`. If empty, condition is definitely false :-)
[HHH-19719]: …
=> HHH-19719 org.hibernate.query.sqm.function.SelfRenderingSqmWindowFunction#appendHqlString throws IndexOutOfBoundsException  when has no arguments

hibernate-core/src/test/java/org/hibernate/orm/test/locking/options/LockedRowsTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/typeoverride/TypeOverrideTest.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFilterExtension.java
=> More ci fixes

hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractEmbeddableMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableResultImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/cid/EmbeddedIdLazyOneToOneCriteriaQueryTest.java
https://hibernate.atlassian.net/browse/HHH-19687
=> HHH-19687 Correctly instantiate id for circular key-to-one fetch with in embedded id

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/HANALegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/HANADialect.java, hibernate-core/src/main/java/org/hibernate/dialect/lock/internal/HANALockingSupport.java, hibernate-core/src/main/java/org/hibernate/sql/ast/internal/StandardLockingClauseStrategy.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/unit/locktimeout/HANALockTimeoutTest.java
=> Fix lock handling for HANA

hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
The query pattern used in Dialect is case sensitive and it currently only allows lower case queries. This PR adds support to allow uppercase (`SELECT .. FROM .. WHERE`) by making the query pattern regex case insensitive.
https://hibernate.atlassian.net/browse/HHH-19697
=> HHH-19697 Use case-insensitive Dialect query pattern matching

hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/ondeletecascade/OnDeleteManyToManyTest.java
https://hibernate.atlassian.net/browse/HHH-19732
=> HHH-19732 Fix wrong resetting of owned on-delete action when processing inverse collection

hibernate-core/src/main/java/org/hibernate/internal/util/cache/InternalCache.java, hibernate-core/src/main/java/org/hibernate/query/internal/NamedObjectRepositoryImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/ParameterMetadataImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryEngineImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryInterpretationCacheDisabledImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryInterpretationCacheStandardImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingsImpl.java
=> use 'var' in query interpretation cache

hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java, hibernate-core/src/main/java/org/hibernate/cfg/Environment.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactorySettings.java, hibernate-core/src/main/java/org/hibernate/internal/util/config/ConfigurationHelper.java
https://hibernate.atlassian.net/browse/HHH-19738
=> HHH-19738 mask out 'jakarta.persistence.jdbc.password'

hibernate-core/src/main/java/org/hibernate/cfg/Environment.java, hibernate-core/src/main/java/org/hibernate/internal/util/config/ConfigurationHelper.java
https://hibernate.atlassian.net/browse/HHH-19738
=> HHH-19738 mask out 'jakarta.persistence.jdbc.password' (7.1)

hibernate-core/src/main/java/org/hibernate/cfg/Environment.java, hibernate-core/src/main/java/org/hibernate/internal/util/config/ConfigurationHelper.java
https://hibernate.atlassian.net/browse/HHH-19738
=> HHH-19738 mask out 'jakarta.persistence.jdbc.password' (6.6)

hibernate-core/src/main/java/org/hibernate/binder/internal/AttributeAccessorBinder.java, hibernate-core/src/main/java/org/hibernate/binder/internal/CollateBinder.java, hibernate-core/src/main/java/org/hibernate/binder/internal/CommentBinder.java, hibernate-core/src/main/java/org/hibernate/binder/internal/CommentsBinder.java, hibernate-core/src/main/java/org/hibernate/binder/internal/TenantIdBinder.java, hibernate-core/src/main/java/org/hibernate/engine/spi/LoadQueryInfluencers.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/internal/util/collections/CollectionHelper.java, hibernate-core/src/main/java/org/hibernate/loader/internal/BaseNaturalIdLoadAccessImpl.java, hibernate-core/src/main/java/org/hibernate/loader/internal/CacheLoadHelper.java, hibernate-core/src/main/java/org/hibernate/loader/internal/IdentifierLoadAccessImpl.java
=> cleanups to SessionFactoryImpl and Binders

hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/MutatingTableReferenceGroupWrapper.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/mutationquery/MutationQueriesCollectionTableTest.java
https://hibernate.atlassian.net/browse/HHH-19740
=> HHH-19740 Delegate table related resolving to mutating table reference

hibernate-core/src/main/java/org/hibernate/Session.java, hibernate-core/src/main/java/org/hibernate/SessionBuilder.java, hibernate-core/src/main/java/org/hibernate/SharedSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/StatelessSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java, hibernate-core/src/main/java/org/hibernate/context/spi/AbstractCurrentSessionContext.java, hibernate-core/src/main/java/org/hibernate/context/spi/MultiTenancy.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/ConnectionProviderInitiator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/spi/ConnectionProvider.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/spi/MultiTenantConnectionProvider.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentImpl.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcServicesImpl.java, hibernate-core/src/main/java/org/hibernate/engine/spi/AbstractDelegatingSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/engine/spi/AbstractDelegatingSharedSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java, hibernate-core/src/main/java/org/hibernate/internal/ContextualJdbcConnectionAccess.java, hibernate-core/src/main/java/org/hibernate/internal/NonContextualJdbcConnectionAccess.java, hibernate-core/src/main/java/org/hibernate/internal/SessionCreationOptions.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/delegation/TestDelegatingSessionBuilder.java, hibernate-core/src/test/java/org/hibernate/orm/test/readonly/ReplicasTest.java
Rebase of  #10754
https://hibernate.atlassian.net/browse/HHH-19708
=> HHH-19708 prototype support for read/write replicas

hibernate-core/src/main/java/org/hibernate/exception/ConstraintViolationException.java, hibernate-core/src/main/java/org/hibernate/exception/GenericJDBCException.java, hibernate-core/src/main/java/org/hibernate/exception/JDBCConnectionException.java, hibernate-core/src/main/java/org/hibernate/exception/SQLGrammarException.java, hibernate-core/src/main/java/org/hibernate/exception/internal/StandardSQLExceptionConverter.java, hibernate-core/src/main/java/org/hibernate/exception/spi/TemplatedViolatedConstraintNameExtractor.java
=> minor cleanups to exception SPI package

hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryImpl.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDirtyCheckEventListener.java, hibernate-core/src/test/java/org/hibernate/orm/test/dirtiness/SessionIsDirtyTests.java
https://hibernate.atlassian.net/browse/HHH-19605
=> HHH-19605 Session.isDirty might return true when batch fetching entity with CacheConcurrencyStrategy.READ_WRITE

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/embeddable/EmbeddableInheritanceRecursiveTest.java
https://hibernate.atlassian.net/browse/HHH-19648
=> HHH-19648 Recursive @Embeddable mapping leads to stack overflow

tooling/hibernate-ant/src/main/java/org/hibernate/tool/hbm2ddl/SchemaExport.java
https://hibernate.atlassian.net/browse/HHH-18686
=> HHH-18686 - align behaviour of SchemaTool and SchemaExportTask with respect to ordering columns and metadata validation

documentation/src/main/asciidoc/querylanguage/Relational.adoc, documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc
=> two improvements to doc for HQL 'order by'

hibernate-core/src/main/java/org/hibernate/action/internal/CollectionAction.java, hibernate-core/src/main/java/org/hibernate/action/internal/DelayedPostInsertIdentifier.java, hibernate-core/src/main/java/org/hibernate/action/internal/EntityDeleteAction.java, hibernate-core/src/main/java/org/hibernate/action/internal/EntityInsertAction.java, hibernate-core/src/main/java/org/hibernate/action/internal/EntityUpdateAction.java, hibernate-core/src/main/java/org/hibernate/action/internal/UnresolvedEntityInsertActions.java, hibernate-core/src/main/java/org/hibernate/cache/internal/EnabledCaching.java, hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java, hibernate-core/src/main/java/org/hibernate/engine/spi/BatchFetchQueue.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CacheInitiator.java, hibernate-core/src/main/java/org/hibernate/engine/spi/EffectiveEntityGraph.java, hibernate-core/src/main/java/org/hibernate/engine/spi/ExecutableList.java, hibernate-core/src/main/java/org/hibernate/engine/spi/LoadQueryInfluencers.java, hibernate-core/src/main/java/org/hibernate/internal/util/collections/ArrayHelper.java, hibernate-core/src/main/java/org/hibernate/internal/util/collections/CollectionHelper.java
=> various minor cleanups around Actions

hibernate-core/src/main/java/org/hibernate/action/internal/CollectionAction.java, hibernate-core/src/main/java/org/hibernate/action/internal/EntityDeleteAction.java, hibernate-core/src/main/java/org/hibernate/action/internal/EntityInsertAction.java, hibernate-core/src/main/java/org/hibernate/action/internal/EntityUpdateAction.java, hibernate-core/src/main/java/org/hibernate/cache/spi/entry/CacheEntryHelper.java, hibernate-core/src/main/java/org/hibernate/engine/internal/EntityEntryImpl.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java, hibernate-core/src/main/java/org/hibernate/event/internal/DefaultRefreshEventListener.java, hibernate-core/src/main/java/org/hibernate/internal/NaturalIdHelper.java, hibernate-core/src/main/java/org/hibernate/internal/OptimisticLockHelper.java, hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderHelper.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/sql/results/internal/ResultsHelper.java
it's conceptually wrong to do work in the constructor of an Action instead of in its execute() method
=> change handling of natural id resolutions in EntityUpdateAction

hibernate-core/src/main/java/org/hibernate/mapping/Collection.java, hibernate-core/src/main/java/org/hibernate/mapping/Join.java, hibernate-core/src/main/java/org/hibernate/mapping/PersistentClass.java
=> delete obsolete instance variables in Collection, Join, and PersistentClass

hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java, hibernate-envers/src/test/java/org/hibernate/orm/test/envers/mapping/enumeratedvalue/CharEnumerateValueTests.java
Jira issue [HHH-19747](https://hibernate.atlassian.net/browse/HHH-19747)
When entity annotated with `@Audited` contains property of enum type that contains field annotated with `@EnumeratedValue`, MappingException with message “Could not resolve named type : convertedBasicType…” is thrown.
Proposed solution is changing `org.hibernate.mapping.BasicValue#interpretExplicitlyNamedType` to handle names starting with
"convertedBasicType" in a same way as those starting with "basicType".
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in …
=> HHH-19747 Hibernate Envers can not handle @EnumeratedValue annotation

hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/stateless/events/CollectionListenerInStatelessSessionTest.java
https://hibernate.atlassian.net/browse/HHH-19716
It doesn't look like `wrap()` is called by Reactive directly, so it seems safe to update the method, no?
=> HHH-19716 Set the collection owner when wrapping a collection into a persistent one

hibernate-core/src/main/java/org/hibernate/query/sqm/function/SelfRenderingSqmAggregateFunction.java, hibernate-core/src/main/java/org/hibernate/query/sqm/function/SelfRenderingSqmFunction.java, hibernate-core/src/main/java/org/hibernate/query/sqm/function/SelfRenderingSqmOrderedSetAggregateFunction.java, hibernate-core/src/main/java/org/hibernate/query/sqm/function/SelfRenderingSqmWindowFunction.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmFunction.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/ValueBindJpaCriteriaParameter.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/CriteriaUpdateWithParametersTest.java
https://hibernate.atlassian.net/browse/HHH-19750
https://hibernate.atlassian.net/browse/HHH-19753
Backport of https://github.com/hibernate/hibernate-orm/pull/10874
=> [7.1] HHH-19750, HHH-19753 Fix criteria value-bind parameter and SqmFunction equals and hashing logic

hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-core/src/main/java/org/hibernate/loader/internal/IdentifierLoadAccessImpl.java
=> delete unnecessary branch in SessionImpl

documentation/src/main/asciidoc/querylanguage/From.adoc, hibernate-core/src/test/java/org/hibernate/orm/test/hql/MapJoinKayValueTests.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/MapJoinTests.java
=> tests for 'join key(...)' and 'join value(...)'

documentation/src/main/asciidoc/querylanguage/From.adoc
=> move new test in HQL doc, and add an additional example

hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
=> Fixup problem after #10856 encapsulate EntityMetamodel within AbstractEntityPersister

hibernate-core/src/main/java/org/hibernate/metamodel/MappingMetamodel.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/DiscriminatorConverter.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EmbeddableDiscriminatorConverter.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/SelectablePath.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/UnifiedAnyDiscriminatorConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/any/annotations/AnyImplicitDiscriminatorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/hql/HQLTest.java
this is definitely not an elegant implementation, but it seems to work
https://hibernate.atlassian.net/browse/HHH-19775
=> HHH-19775 tolerate type(:entity) as required by JPQL

hibernate-core/src/main/java/org/hibernate/SessionBuilder.java, hibernate-core/src/main/java/org/hibernate/SharedSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/SharedStatelessSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/StatelessSessionBuilder.java, hibernate-core/src/main/java/org/hibernate/engine/creation/CommonBuilder.java
=> improve javadoc for session builders

documentation/src/main/asciidoc/introduction/Tuning.adoc
=> expand doc section on pessimistic locking

hibernate-core/src/main/java/org/hibernate/context/internal/CurrentSessionLogging.java, hibernate-core/src/main/java/org/hibernate/context/internal/JTASessionContext.java, hibernate-core/src/main/java/org/hibernate/context/internal/ManagedSessionContext.java, hibernate-core/src/main/java/org/hibernate/context/internal/ThreadLocalSessionContext.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
=> typesafe logging and cleanups in the (current session) context package

hibernate-core/src/main/java/org/hibernate/boot/BootLogging.java, hibernate-core/src/main/java/org/hibernate/boot/MetadataSources.java, hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/boot/jaxb/internal/CacheableFileXmlSource.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedColumn.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotationBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionPropertyHolder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionSecondPass.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/FilterDefBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorParameters.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/QueryBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ResultSetMappingSecondPass.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ToOneBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/ManagedResourcesImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/relational/Namespace.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/annotations/AnnotationMetadataSourceProcessorImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java, hibernate-core/src/main/java/org/hibernate/boot/models/internal/GlobalRegistrationsImpl.java, hibernate-core/src/main/java/org/hibernate/boot/registry/classloading/internal/ClassLoaderServiceImpl.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/formula/JoinFormulaManyToOneNotIgnoreLazyFetchingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/annotations/formula/JoinFormulaOneToOneNotIgnoreLazyFetchingTest.java
=> migrate to BOOT_LOGGER + more cleanups in boot packages

hibernate-core/src/main/java/org/hibernate/dialect/HANAServerConfiguration.java, hibernate-core/src/main/java/org/hibernate/dialect/temptable/TemporaryTableHelper.java, hibernate-core/src/main/java/org/hibernate/engine/config/internal/ConfigurationServiceImpl.java, hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CascadingActions.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CollectionEntry.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/jpa/HibernatePersistenceProvider.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/PersistenceUnitInfoDescriptor.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/spi/PersistenceXmlParser.java, hibernate-core/src/main/java/org/hibernate/jpa/boot/spi/ProviderChecker.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/JpaLogger.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/util/FlushModeTypeHelper.java, hibernate-core/src/main/java/org/hibernate/jpa/internal/util/LogHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/jpa/persistenceunit/DuplicatePersistenceUnitNameTest.java
=> introduce JpaLogger

ci/release/Jenkinsfile
=> Lock around clone-commit-push in Jenkins release script

hibernate-agroal/src/main/java/org/hibernate/agroal/internal/AgroalConnectionProvider.java, hibernate-c3p0/src/main/java/org/hibernate/c3p0/internal/C3P0ConnectionProvider.java, hibernate-core/src/main/java/org/hibernate/boot/archive/scan/internal/ScannerLogger.java, hibernate-core/src/main/java/org/hibernate/boot/registry/selector/spi/StrategySelector.java, hibernate-core/src/main/java/org/hibernate/cache/internal/RegionFactoryInitiator.java, hibernate-core/src/main/java/org/hibernate/cache/spi/SecondLevelCacheLogger.java, hibernate-core/src/main/java/org/hibernate/cfg/Environment.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DataSourceConnectionProvider.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DriverManagerConnectionProvider.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/PoolState.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/PooledConnections.java, hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java, hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java, hibernate-core/src/main/java/org/hibernate/internal/log/ConnectionInfoLogger.java, hibernate-core/src/test/java/org/hibernate/orm/test/datasource/DataSourceTest.java, hibernate-hikaricp/src/main/java/org/hibernate/hikaricp/internal/HikariCPConnectionProvider.java
=> Yet more logging

hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java, hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/ForeignPackageSuperclassAccessorTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/SuperclassEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/AncestorEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/ChildEntity3.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/ChildEntity4.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/ChildEntity5.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/ChildEntity6.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/ChildEntity7.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/ChildEntity8.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/ChildEntity9.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/HierarchyBytecodeOptimizerMethodVisibilityTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/HierarchyBytecodeOptimizerOrderingTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/HierarchyBytecodeOptimizerTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/ParentEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/child/ChildEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/child/ChildEntity10.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/parent/Ancestor.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/optimizer/parent/ChildEntity2.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/foreignpackage/ConcreteEntity.java
Fixes https://hibernate.atlassian.net/browse/HHH-19784 in the first commit. 
The rest of the commits are a backport of https://github.com/hibernate/hibernate-orm/pull/10192, which are required to make access optimizers work in similar cases (package-private fields in the same hierarchy but with different classloaders).
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md# …
=> [6.2] Package-private members access fixes for bytecode enhancement

docker_db.sh, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/lock/FollowOnLockingAction.java
=> Mac and locking fixes

hibernate-core/src/main/java/org/hibernate/stat/internal/AbstractCacheableDataStatistics.java, hibernate-core/src/main/java/org/hibernate/stat/internal/CollectionStatisticsImpl.java, hibernate-core/src/main/java/org/hibernate/stat/internal/EntityStatisticsImpl.java, hibernate-core/src/main/java/org/hibernate/stat/internal/NaturalIdStatisticsImpl.java, hibernate-core/src/main/java/org/hibernate/stat/internal/QueryStatisticsImpl.java, hibernate-core/src/main/java/org/hibernate/stat/internal/SessionStatisticsImpl.java, hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsImpl.java, hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsInitiator.java, hibernate-core/src/main/java/org/hibernate/stat/internal/StatsHelper.java, hibernate-core/src/main/java/org/hibernate/stat/internal/StatsNamedContainer.java
=> misc cleanups in statistics package

tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractCriteriaMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/AbstractQueryMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaDeleteMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/CriteriaFinderMethod.java, tooling/metamodel-generator/src/main/java/org/hibernate/processor/annotation/QueryMethod.java
https://hibernate.atlassian.net/browse/HHH-19713
This is what the repository method looks like now:
```java
long _totalResults =
pageRequest.requestTotal()
? _spec.createQuery(session)
.getResultCount()
: -1;
var _results = _spec.createQuery(session)
.setFirstResult((int) (pageRequest.page()-1) * pageRequest.size())
.setMaxResults(pageRequest.size())
.getResultList();
return new PageRecord<>( pageRequest, _results, _totalResults);
```
And this is after this patch:
```java
var _select = _spec.createQuery(session);
long _totalResults =
pageRequest.requestTotal()
? _select
.getResultCount()
: -1;
var _results = _select
.setFirstResult((int) (pageRequest.page()-1) * pageRequest.size())
.setMaxResults(pageRequest.size())
.getResultList();
return new PageRecord<>( pageRequest, _results, …
```
=> HHH-19713 Hibernate creates invalid SQLServer query when using pagination with Jakarta Data

hibernate-core/src/main/java/org/hibernate/boot/model/relational/Sequence.java
=> improve readability of an error message

hibernate-core/src/main/java/org/hibernate/boot/BootLogging.java, hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotationBinder.java, hibernate-core/src/main/java/org/hibernate/query/internal/FetchMementoHbmStandard.java, hibernate-core/src/main/java/org/hibernate/query/internal/NamedObjectRepositoryImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/NamedResultSetMappingMementoImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/NullPrecedenceHelper.java, hibernate-core/src/main/java/org/hibernate/query/internal/ParameterMetadataImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryEngineImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryInterpretationCacheDisabledImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryInterpretationCacheStandardImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingsImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterNamedImpl.java, hibernate-core/src/main/java/org/hibernate/query/internal/ResultMementoBasicStandard.java, hibernate-core/src/main/java/org/hibernate/query/internal/ResultMementoEntityJpa.java, hibernate-core/src/main/java/org/hibernate/query/internal/ResultMementoEntityStandard.java, hibernate-core/src/main/java/org/hibernate/query/internal/ResultMementoInstantiationStandard.java, hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcSelectExecutorStandardImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/querycache/QueryEngineImplConfigValidationTest.java
=> misc cleanups to the query.internal package

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedColumns.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotatedJoinColumns.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotationBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/BasicValueBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/GeneratorBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/IdBagBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/IdGeneratorResolverSecondPass.java
=> misc cleanups in Binders

hibernate-core/src/main/java/org/hibernate/id/uuid/CustomVersionOneStrategy.java, hibernate-core/src/main/java/org/hibernate/id/uuid/Helper.java, hibernate-core/src/main/java/org/hibernate/id/uuid/UuidGenerator.java, hibernate-core/src/main/java/org/hibernate/id/uuid/UuidVersion6Strategy.java, hibernate-core/src/main/java/org/hibernate/id/uuid/UuidVersion7Strategy.java
=> light code improvements to id.uuid package

hibernate-core/src/main/java/org/hibernate/query/specification/internal/MutationSpecificationImpl.java, hibernate-core/src/main/java/org/hibernate/query/specification/internal/SelectionSpecificationImpl.java
=> use 'var' in XxxxxSpecificationImpl

hibernate-core/src/main/java/org/hibernate/collection/spi/InitializerProducerBuilder.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/PluralAttributeMetadataImpl.java, hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/DomainResultAssembler.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/AbstractCollectionInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/AbstractImmediateCollectionInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/AbstractNonJoinCollectionInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/ArrayInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/BagInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/DelayedCollectionInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/ListInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/MapInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/SelectEagerCollectionInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/SetInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/AggregateEmbeddableInitializerImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableInitializerImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/NonAggregatedIdentifierMappingInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/AbstractBatchEntitySelectFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntityInsideEmbeddableSelectFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchEntitySelectFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/BatchInitializeEntitySelectFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/DiscriminatedEntityInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchByUniqueKeyInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntitySelectFetchInitializer.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/internal/AbstractInitializer.java
mostly just use of 'var'
also extracted a couple of reusable methods
=> superficial code cleanups in initializers

hibernate-core/src/main/java/org/hibernate/cfg/SchemaToolingSettings.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/MySQLServerConfiguration.java, hibernate-core/src/test/java/org/hibernate/orm/test/dialect/unit/lockhint/MySQLStorageEngineTest.java
https://hibernate.atlassian.net/browse/HHH-19752
=> HHH-19752 Allow setting MariaDB/MySQL storage engine not only using System properties but also configuration properties

hibernate-core/src/main/java/org/hibernate/metamodel/internal/AbstractCompositeIdentifierMapping.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/AbstractDynamicMapInstantiator.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/AbstractEntityInstantiatorPojo.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/BaseAttributeMetadata.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableInstantiatorDynamicMap.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableInstantiatorPojoIndirecting.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableInstantiatorPojoOptimized.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableInstantiatorPojoStandard.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableInstantiatorProxied.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableInstantiatorRecordIndirecting.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableInstantiatorRecordStandard.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/EmbeddableRepresentationStrategyPojo.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/EntityInstantiatorDynamicMap.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/EntityRepresentationStrategyMap.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/EntityRepresentationStrategyPojoStandard.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/FullNameImplicitDiscriminatorStrategy.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/InjectionHelper.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/JpaMetamodelPopulationSetting.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/JpaStaticMetamodelPopulationSetting.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/ManagedTypeRepresentationResolverStandard.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/PluralAttributeMetadataImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/PropertyAccessHelper.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/ShortNameImplicitDiscriminatorStrategy.java
=> superficial cleanups in metamodel.internal package

hibernate-core/src/main/java/org/hibernate/proxy/pojo/BasicLazyInitializer.java, hibernate-core/src/main/java/org/hibernate/query/assignment/Assignment.java, hibernate-core/src/main/java/org/hibernate/query/assignment/AttributeAssignment.java, hibernate-core/src/main/java/org/hibernate/query/assignment/PathAssignment.java, hibernate-core/src/main/java/org/hibernate/query/assignment/PathToAttributeAssignment.java, hibernate-core/src/main/java/org/hibernate/query/assignment/PathToPathAssignment.java, hibernate-core/src/main/java/org/hibernate/query/assignment/package-info.java, hibernate-core/src/main/java/org/hibernate/query/specification/DeleteSpecification.java, hibernate-core/src/main/java/org/hibernate/query/specification/MutationSpecification.java, hibernate-core/src/main/java/org/hibernate/query/specification/ProjectionSpecification.java, hibernate-core/src/main/java/org/hibernate/query/specification/SelectionSpecification.java, hibernate-core/src/main/java/org/hibernate/query/specification/SimpleProjectionSpecification.java, hibernate-core/src/main/java/org/hibernate/query/specification/UpdateSpecification.java, hibernate-core/src/main/java/org/hibernate/query/specification/internal/DeleteSpecificationImpl.java, hibernate-core/src/main/java/org/hibernate/query/specification/internal/MutationSpecificationImpl.java, hibernate-core/src/main/java/org/hibernate/query/specification/internal/ProjectionSpecificationImpl.java, hibernate-core/src/main/java/org/hibernate/query/specification/internal/SelectionSpecificationImpl.java, hibernate-core/src/main/java/org/hibernate/query/specification/internal/SimpleProjectionSpecificationImpl.java, hibernate-core/src/main/java/org/hibernate/query/specification/internal/UpdateSpecificationImpl.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/update/SqmSetClause.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/assignment/AssignmentTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/dynamic/OtherEntity.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/dynamic/ProjectionSpecificationTest.java
This is just what I came up with on the flight MEL->SIN.
Need to let it brew a bit more.
See: 
- https://hibernate.atlassian.net/browse/HHH-19822
- https://hibernate.atlassian.net/browse/HHH-19823
=> prototype for Assignments and ProjectionSpecifications

hibernate-core/src/test/java/org/hibernate/orm/test/graph/EntityGraphsTest.java
Correction of the inheritance syntax used with GraphParser
Some test in the file EntityGraphsTest not use the good syntax for representing inheritance with GraphParser. 
For example, it represents inheritance like this: 
`linkToOne:MockSubentity(description)`
instead of the syntax provided by GraphLanguageParser : 
`linkToOne(MockSubentity:description)`
MockSubentity also does not exist and must be replaced by GraphParsingTestSubentity
https://hibernate.atlassian.net/browse/HHH-19009 …
=> HHH-19009 correction of the inheritance syntax used with GraphParser

docker_db.sh, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/PostgreSQLLegacyDialect.java, hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
=> Update PostgreSQL testing to version 18

hibernate-core/src/main/java/org/hibernate/generator/values/internal/GeneratedValuesHelper.java, hibernate-core/src/test/java/org/hibernate/orm/test/batch/LeakingStatementCachingTest.java
This is the rebased version of  https://github.com/hibernate/hibernate-orm/pull/8678 and shows that the issue has been resolved in recent versions of Hibernate.
https://hibernate.atlassian.net/browse/HHH-18325
=> HHH-18325: Prevent comparison between proxied and non-proxied statements

hibernate-core/src/test/java/org/hibernate/orm/test/mapping/enumeratedvalue/EnumAndColumnDefinitionTest.java
The test shows that using `@JdbcTypeCode(SqlTypes.VARCHAR)` fixes the issue;
https://hibernate.atlassian.net/browse/HHH-17017
=> HHH-17017 Hibernate 6 cannot read VARCHAR column as INT

release/release.gradle
https://hibernate.atlassian.net/browse/HHH-19388
backport for 5.6
https://hibernate.atlassian.net/browse/HHH-19800
=> HHH-19800 Migrate to release scripts for documentation publishing

hibernate-core/src/main/java/org/hibernate/collection/spi/AbstractPersistentCollection.java, hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentMap.java, hibernate-core/src/test/java/org/hibernate/orm/test/extralazy/ExtraLazyMapQueuedPersistTest.java
Test reproducing the issue: https://hibernate.atlassian.net/browse/HHH-18885
Putting a entity in an extra lazy map and committing the transaction results in a ClassCastException
=> HHH-18885 Introduce DelayedOperation.getAddedEntry() for maps

build.gradle, hibernate-core/hibernate-core.gradle, tooling/metamodel-generator/hibernate-processor.gradle, tooling/metamodel-generator/src/main/java/org/hibernate/processor/Version.java
https://hibernate.atlassian.net/browse/HHH-14082
- supersede https://github.com/hibernate/hibernate-orm/pull/10726
=> HHH-14082 Apply version injection plugin

tooling/hibernate-gradle-plugin/README.adoc
JPA model generation was removed from the hibernate-gradle-plugin in #6632 . This removes said section in the README.
=> Remove outdated documentation from hibernate-gradle-plugin README

hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/internal/util/ImmutableBitSet.java, hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/PluralAttributeMappingImpl.java, hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java, hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityInitializerImpl.java, hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/FetchGraphTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/collection/set/PersistentSetRemoveTest.java
This is expanding on https://github.com/hibernate/hibernate-orm/pull/11008 to set/initialize unfetched attributes with available data, even when the entity is already initialized.
https://hibernate.atlassian.net/browse/HHH-19805
=> HHH-19805 Allow nested entity initializers to claim entity holder

hibernate-core/src/main/java/org/hibernate/query/hql/internal/QualifiedJoinPathConsumer.java, hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
https://hibernate.atlassian.net/browse/HHH-19759
=> HHH-19759 - Avoid a ClassCastException when joining on a basic value type

local-build-plugins/src/main/groovy/local.java-module.gradle
https://hibernate.atlassian.net/browse/HHH-19767
Backport of https://github.com/hibernate/hibernate-orm/pull/10917
since we need it in all supported versions with ASL 2
=> HHH-19767 Include license file in the META-INF of published artifacts

hibernate-core/src/main/java/org/hibernate/metamodel/internal/AttributeFactory.java, hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generics/compositeid/CompositeIdWithGenericPartInMappedSuperclassTest.java
Jira issue [HHH-19706](https://hibernate.atlassian.net/browse/HHH-19706)
When declaring entity does not have attribute mapping for property, and property is identifier property then it should be handled as "normal" property, not as virtual identifier.
[HHH-19706]: …
=> HHH-19706 Composite @Id with a generic part in @MappedSuperclass

hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixDialect.java, hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/InformixSqlAstTranslator.java, hibernate-core/src/test/java/org/hibernate/orm/test/filter/DynamicFilterTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/QueryTimeOutTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/mutationquery/MutationQueriesFilterTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/mutationquery/MutationQueriesWhereAndFilterTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/query/mutationquery/MutationQueriesWhereTest.java, hibernate-testing/src/main/java/org/hibernate/testing/DialectChecks.java, hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectFeatureChecks.java
https://hibernate.atlassian.net/browse/HHH-19694
=> HHH-19694 Enhanced support for older Informix

hibernate-core/src/test/java/org/hibernate/orm/test/jpa/graphs/LoadEntityGraphWithCompositeKeyCollectionsTest.java
test showing the issue has been fixed https://hibernate.atlassian.net/browse/HHH-19137
=> HHH-19137 - @NamedEntityGraph entity loading fails with AssertionError on entity model with multiple collections and composite keys

hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/AnnotationBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/spi/InFlightMetadataCollector.java
1. code formatting
2. don't leak an annotation type onto InFlightMetadataCollector SPI
3. use a record
=> minor cleanups to AnnotationBinder

changelog.txt
=> Update the changelog to match the released tasks

tooling/hibernate-gradle-plugin/hibernate-gradle-plugin.gradle
https://github.com/hibernate/hibernate-orm/pull/11080 backport to 6.6
=> Fix check Gradle task graph contains task
