hibernate/hibernate-orm

- documentation/src/main/docbook/manual/en-US/content/tutorial.xml
The example does not compile for obvious reason :)
> [HHH-9645] buildSessionFactory() should return a sessionFactory

- hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java
- hibernate-core/src/main/java/org/hibernate/event/internal/AbstractFlushingEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDeleteEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultEvictEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLockEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultRefreshEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultReplicateEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultSaveOrUpdateEventListener.java
For details see the issue https://hibernate.atlassian.net/browse/HHH-9328
> HHH-9328 Avoid creation of Cascade objects at all

- hibernate-infinispan/src/main/resources/org/hibernate/cache/infinispan/builder/infinispan-configs.xml
* fixed default configuration path
* set schema to 7.1
> HHH-9632 Upgrade to Infinispan 7.1.0.Final

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/Enhancer.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/EnhancerTest.java
Fix for bytecode enhancement dirty tracking not working when PersistentAttributeInterceptor is not injected
> HHH-9806 Backport for 4.3 branch

- hibernate-infinispan/src/main/java/org/hibernate/cache/infinispan/query/QueryResultsRegionImpl.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/query/QueryRegionImplTestCase.java
https://hibernate.atlassian.net/browse/HHH-10005
Fixes a failure in Wildfly's testsuite.
> HHH-10005 Query in context needs precedence over query in cache

- hibernate-infinispan/src/main/java/org/hibernate/cache/infinispan/InfinispanRegionFactory.java
- hibernate-infinispan/src/main/java/org/hibernate/cache/infinispan/access/PutFromLoadValidator.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/access/PutFromLoadValidatorUnitTestCase.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/functional/cluster/DualNodeJtaTransactionImpl.java
> HHH-9928 Pending put leaks when the entity is not found in DB

- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/SelectClause.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
- hibernate-core/src/test/java/org/hibernate/test/criteria/limitexpression/Country.java
- hibernate-core/src/test/java/org/hibernate/test/criteria/limitexpression/LimitExpressionTest.java
- hibernate-core/src/test/java/org/hibernate/test/criteria/limitexpression/Person.java
- hibernate-core/src/test/java/org/hibernate/test/criteria/limitexpression/UsState.java
- hibernate-core/src/test/java/org/hibernate/test/criteria/limitexpression/domain.hbm.xml
- hibernate-core/src/test/java/org/hibernate/test/pagination/DataMetaPoint.java
- hibernate-core/src/test/java/org/hibernate/test/pagination/DataPoint.hbm.xml
- hibernate-core/src/test/java/org/hibernate/test/pagination/PaginationTest.java
https://hibernate.atlassian.net/browse/HHH-951
> https://hibernate.atlassian.net/browse/HHH-951

- hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyResolverStandardImpl.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/EnhancerTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/pk/EmbeddedPKTestTask.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/pk/WorkOrder.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/pk/WorkOrderPK.java
> HHH-10079 - Restrict enhanced getter/setter usage

- hibernate-entitymanager/src/main/java/org/hibernate/jpa/criteria/expression/CaseLiteralExpression.java
- hibernate-entitymanager/src/main/java/org/hibernate/jpa/criteria/expression/SearchedCaseExpression.java
- hibernate-entitymanager/src/main/java/org/hibernate/jpa/criteria/expression/SimpleCaseExpression.java
- hibernate-entitymanager/src/test/java/org/hibernate/jpa/test/criteria/selectcase/SelectCaseTest.java
https://hibernate.atlassian.net/browse/HHH-9731
A different solution based on https://github.com/hibernate/hibernate-orm/pull/1070 comments
> HHH-9731 : Potential bug in SearchedCaseExpression type handling

- hibernate-core/src/main/java/org/hibernate/dialect/Oracle12cDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/identity/Oracle12cGetGeneratedKeysDelegate.java
- hibernate-core/src/main/java/org/hibernate/dialect/identity/Oracle12cIdentityColumnSupport.java
- hibernate-core/src/test/java/org/hibernate/test/idgen/identity/hhh9983/SaveEntityTest.java
https://hibernate.atlassian.net/browse/HHH-9983
> HHH-9983 - Error saving entity with identity id on Oracle 12c

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DriverManagerConnectionProviderImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/PooledConnections.java
- hibernate-entitymanager/src/test/java/org/hibernate/jpa/test/schemagen/Document.java
- hibernate-entitymanager/src/test/java/org/hibernate/jpa/test/schemagen/SchemaCreateDropTest.java
https://hibernate.atlassian.net/browse/HHH-10104
> HHH-10104 Using JPA 2.1 schema generation together with hbm2ddl runs into deadlock with MySQL

- hibernate-infinispan/src/main/java/org/hibernate/cache/infinispan/query/QueryResultsRegionImpl.java
- hibernate-infinispan/src/main/java/org/hibernate/cache/infinispan/util/Caches.java
- hibernate-infinispan/src/main/resources/org/hibernate/cache/infinispan/builder/infinispan-configs.xml
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/AbstractGeneralDataRegionTestCase.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/query/QueryRegionImplTestCase.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/util/CacheTestUtil.java
* this fix works only for JTA transactions! (JDBC transactions behavior was not altered)
* removed cluster loader from default configuration
> HHH-10182 Backport HHH-7898 for JTA environment only

- hibernate-core/src/main/java/org/hibernate/hql/internal/QuerySplitter.java
- hibernate-core/src/test/java/org/hibernate/test/hql/QuerySplitterTest.java
https://hibernate.atlassian.net/browse/HHH-7973
> HHH-7973 - String literals in an HQL query can get mangled

- documentation/src/main/asciidoc/userguide/chapters/domain/mapping_types.adoc
- documentation/src/main/asciidoc/userguide/chapters/domain/naming.adoc
@vladmihalcea just little typos
> Fix Documentation typos

- documentation/documentation.gradle
- documentation/src/main/style/asciidoctor/css/hibernate.css
@sebersole I created this PR to validate the design look and feel.
> DESIGN-737 - Asciidoctor styling for Hibernate outputs.

- hibernate-entitymanager/src/main/java/org/hibernate/jpa/internal/TransactionImpl.java
- hibernate-entitymanager/src/test/java/org/hibernate/jpa/test/transaction/TransactionCommitFailureTest.java
The PR contains:
- the fix for [HHH-10510](https://hibernate.atlassian.net/browse/HHH-10510) submitted by andrei-ivanon
- a test case to replicate the issue
> Fix for HHH-10510

- hibernate-core/src/main/java/org/hibernate/dialect/identity/GetGeneratedKeysDelegate.java
- hibernate-core/src/main/java/org/hibernate/id/IdentifierGeneratorHelper.java
- hibernate-core/src/main/java/org/hibernate/id/IdentityGenerator.java
- hibernate-core/src/main/java/org/hibernate/id/SequenceIdentityGenerator.java
Use dialect for verifying quoting
> HHH-9271 - IdentityGenerator broken with quoted identifiers

- hibernate-core/src/main/java/org/hibernate/Query.java
- hibernate-core/src/main/java/org/hibernate/ejb/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/ejb/HibernateEntityManager.java
- hibernate-core/src/main/java/org/hibernate/ejb/HibernateEntityManagerFactory.java
- hibernate-core/src/main/java/org/hibernate/ejb/HibernateQuery.java
- hibernate-core/src/main/java/org/hibernate/query/Query.java
https://hibernate.atlassian.net/browse/HHH-10839
> HHH-10839 Restore some lost backwards compatibility

- hibernate-envers/src/main/java/org/hibernate/envers/event/spi/BaseEnversEventListener.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/inheritance/single/relation/PolymorphicRemovalTest.java
https://hibernate.atlassian.net/browse/HHH-7249
> HHH-7249 - Fix saving proper discriminator value at deletion time between related entities.

- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQL82Dialect.java
https://hibernate.atlassian.net/browse/HHH-11016
> HHH-11016 - Added 'if exists' for sequence drop statements for PostgreSQL82 and derivatives.

- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
- hibernate-core/hibernate-core.gradle
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/tool/hbm2ddl/SchemaExport.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/Helper.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaCreatorImpl.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/GenerationTargetToScript.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/ScriptSourceInputFromFile.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/ScriptSourceInputFromUrl.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/ScriptTargetOutputToFile.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/ScriptTargetOutputToUrl.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/spi/SchemaManagementToolCoordinator.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/schemagen/JpaFileSchemaGeneratorTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/schemagen/JpaSchemaGeneratorTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/schemagen/SchemaCreateDropUtf8WithoutHbm2DdlCharsetNameTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/schemagen/iso8859/JpaFileSchemaGeneratorWithHbm2DdlCharsetNameTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/schemagen/iso8859/JpaSchemaGeneratorWithHbm2DdlCharsetNameTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/schemagen/iso8859/JpaSchemaGeneratorWithoutHbm2DdlCharsetNameTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/schemagen/iso8859/SchemaCreateDropWithHbm2DdlCharsetNameTest.java
- hibernate-core/src/test/resources/org/hibernate/jpa/test/schemagen/create-script-source.sql
- hibernate-core/src/test/resources/org/hibernate/jpa/test/schemagen/iso8859/create-script-source.sql
- hibernate-core/src/test/resources/org/hibernate/jpa/test/schemagen/iso8859/drop-script-source.sql
- hibernate-core/src/test/resources/org/hibernate/jpa/test/schemagen/iso8859/load-script-source.sql
- hibernate-core/src/test/resources/org/hibernate/jpa/test/schemagen/load-script-source.sql
https://hibernate.atlassian.net/browse/HHH-10972
> HHH-10972 - Use UTF-8 charset for reading files for initializing the database (javax.persistence.sql-load-script-source scripts)

- hibernate-core/src/main/java/org/hibernate/bytecode/internal/javassist/ProxyFactoryFactoryImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/BlobProxy.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/ClobProxy.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/ResultSetWrapperProxy.java
- hibernate-core/src/main/java/org/hibernate/exception/spi/SQLExceptionConverterFactory.java
- hibernate-core/src/main/java/org/hibernate/internal/util/ReflectHelper.java
- hibernate-core/src/main/java/org/hibernate/proxy/pojo/javassist/JavassistProxyFactory.java
- hibernate-core/src/main/java/org/hibernate/service/internal/AbstractServiceRegistryImpl.java
- hibernate-ehcache/src/main/java/org/hibernate/cache/ehcache/management/impl/BeanUtils.java
- hibernate-testing/src/main/java/org/hibernate/testing/junit4/CustomParameterized.java
- hibernate-testing/src/main/java/org/hibernate/testing/junit4/TestClassMetadata.java
Fixes https://hibernate.atlassian.net/browse/HHH-11136
> HHH-11136 - Reduce memory consumption caused by Method.getParameterTypes()

- hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/JoinedSubclassEntitySourceImpl.java
- hibernate-core/src/main/resources/org/hibernate/xsd/mapping/legacy-mapping-4.0.xsd
- hibernate-core/src/test/java/org/hibernate/test/discriminator/joined/ChildEntity.java
- hibernate-core/src/test/java/org/hibernate/test/discriminator/joined/JoinedSubclassInheritance.hbm.xml
- hibernate-core/src/test/java/org/hibernate/test/discriminator/joined/JoinedSubclassInheritanceTest.java
- hibernate-core/src/test/java/org/hibernate/test/discriminator/joined/ParentEntity.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/inheritance/joined/DiscriminatorJoinedInheritanceTest.java
https://hibernate.atlassian.net/browse/HHH-11133
> HHH-11133 - Add support for discriminator-value on joined-subclass hbm element types.

- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
- documentation/src/test/java/org/hibernate/userguide/schema/SchemaGenerationTest.java
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/spi/SchemaManagementToolCoordinator.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/SchemaUpdateHaltOnErrorTest.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/SchemaUpdateProceedOnErrorTest.java
https://hibernate.atlassian.net/browse/HHH-3674
> HHH-3674 - Expose SchemaUpdate#haltOnError as a configuration property

- hibernate-envers/src/main/java/org/hibernate/envers/internal/synchronization/AuditProcess.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/jta/JtaSessionClosedBeforeCommitTest.java
https://hibernate.atlassian.net/browse/HHH-11232
> HHH-11232 - Session closed exception when using Envers in a JTA transaction

- hibernate-core/src/main/antlr/hql.g
- hibernate-core/src/test/java/org/hibernate/test/sql/function/JpaFunctionTest.java
https://hibernate.atlassian.net/browse/HHH-11233
> HHH-11233 - JPA SQL function with no arguments can only be called if we provide a comma

- hibernate-core/src/main/java/org/hibernate/cfg/IndexOrUniqueKeySecondPass.java
- hibernate-core/src/test/java/org/hibernate/test/naturalid/composite/CompositeNaturalIdMappingTest.java
- hibernate-core/src/test/java/org/hibernate/test/naturalid/composite/EmbeddedNaturalIdTest.java
- hibernate-core/src/test/java/org/hibernate/test/naturalid/composite/PostalCarrier.java
https://hibernate.atlassian.net/browse/HHH-11255
> HHH-11255  - NaturalId mapping fails when using a composite natural identifier

- hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
- hibernate-core/src/main/java/org/hibernate/cfg/ClassPropertyHolder.java
- hibernate-core/src/main/java/org/hibernate/cfg/CollectionPropertyHolder.java
- hibernate-core/src/main/java/org/hibernate/cfg/ComponentPropertyHolder.java
- hibernate-core/src/main/java/org/hibernate/cfg/PropertyHolder.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/embeddables/collection/EmbeddableWithManyToMany_HHH_11302_Test.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/embeddables/collection/EmbeddableWithOneToMany_HHH_11302_Test.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/embeddables/collection/EmbeddableWithOneToMany_HHH_8564_Test.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/embeddables/collection/EmbeddableWithOneToMany_HHH_8860_Test.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/embeddables/collection/xml/ContactInformation.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/embeddables/collection/xml/ContactType.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/embeddables/collection/xml/EmbeddableWithOneToMany_HHH_11302_xml_Test.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/embeddables/collection/xml/Person.java
- hibernate-core/src/test/resources/org/hibernate/test/annotations/embeddables/collection/orm.xml
https://hibernate.atlassian.net/browse/HHH-4313
> HHH-4313 - ConcurrentModificationException when collection of embeddable contains a collection

- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/connection/TestConnectionPool.java
https://hibernate.atlassian.net/browse/HHH-11257
> HHH-11257 - Connection leak when SQLGrammarException is thrown

- tooling/hibernate-enhance-maven-plugin/hibernate-enhance-maven-plugin.gradle
- tooling/hibernate-enhance-maven-plugin/src/main/java/org/hibernate/orm/tooling/maven/MavenEnhancePlugin.java
- tooling/hibernate-enhance-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
- tooling/hibernate-enhance-maven-plugin/src/main/resources/META-INF/maven/plugin.xml
https://hibernate.atlassian.net/browse/HHH-11282
> HHH-11282 - Support m2e/Eclipse integration in hibernate-enhance-maven-plugin

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/BasicFormatterImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/DDLFormatterImpl.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/AbstractScriptTargetOutput.java
- hibernate-core/src/test/java/org/hibernate/jdbc/util/DdlFormatterTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/functional/ConcurrentWriteTest.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/ImportContextImpl.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/util/TestUtil.java
https://hibernate.atlassian.net/browse/HHH-11183
> HHH-11183 - Mixed line endings in schema creation script

- hibernate-core/src/main/java/org/hibernate/dialect/pagination/SQLServer2005LimitHandler.java
- hibernate-core/src/test/java/org/hibernate/dialect/SQLServer2005DialectTestCase.java
https://hibernate.atlassian.net/browse/HHH-11324
This PR also includes test case fixes for HHH-11084 which included invalid SQL which were identified as a part of this code fix.
> HHH-11324 - Fix LimitHandler parsing of select-clause subqueries for SQLServer2005Dialect.

- hibernate-core/src/main/java/org/hibernate/internal/CriteriaImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/EmptyScrollableResults.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java
- hibernate-core/src/main/java/org/hibernate/query/internal/AbstractProducedQuery.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/limitExpression/LimitExpressionTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/query/LimitExpressionTest.java
- hibernate-core/src/test/java/org/hibernate/test/criteria/limitexpression/LimitExpressionTest.java
- hibernate-core/src/test/java/org/hibernate/test/criteria/limitexpression/domain.hbm.xml
- hibernate-core/src/test/java/org/hibernate/test/legacy/LimitExpressionTest.java
https://hibernate.atlassian.net/browse/HHH-11278
> HHH-11278 - setMaxResult(0) should return an empty List

- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/CollectionMetadataGenerator.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/AuditedPropertiesReader.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/component/MiddleMapElementNotKeyComponentMapper.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/collection/StringMapLobTest.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/collection/StringMapNationalizedLobTest.java
https://hibernate.atlassian.net/browse/HHH-9834
> HHH-9834: Fix Audit table creation fails for ElementCollection Map with CLOB/NCLOB element column

- hibernate-core/src/main/java/org/hibernate/pretty/MessageHelper.java
- hibernate-infinispan/src/main/java/org/hibernate/cache/infinispan/access/PutFromLoadValidator.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/AbstractExtraAPITest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/AbstractGeneralDataRegionTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/AbstractNonFunctionalTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/AbstractRegionAccessStrategyTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/InfinispanRegionFactoryTestCase.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/access/PutFromLoadValidatorUnitTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/collection/CollectionRegionAccessStrategyTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/collection/CollectionRegionImplTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/entity/EntityRegionAccessStrategyTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/functional/AbstractFunctionalTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/functional/AbstractNonInvalidationTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/functional/ConcurrentWriteTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/functional/ReadOnlyTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/functional/ReadWriteTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/functional/cluster/DualNodeTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/functional/cluster/EntityCollectionInvalidationTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/functional/cluster/NaturalIdInvalidationTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/stress/CorrectnessTestCase.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/timestamp/TimestampsRegionImplTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/util/CacheTestSupport.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/util/CacheTestUtil.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/util/ExpectingInterceptor.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/util/TestInfinispanRegionFactory.java
On my machine it's 2 minutes with trace level on, so it's quite substantial.
Depends on #1701
> Hibernate-infinispan testsuite speedup

- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/ClassesAuditingData.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/ClassAuditingData.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/ComponentAuditingData.java
- hibernate-envers/src/main/java/org/hibernate/envers/event/spi/BaseEnversCollectionEventListener.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/components/EmbeddableWithCollectionTest.java
https://hibernate.atlassian.net/browse/HHH-9108
> HHH-9108: Fix PropertyAccessException when auditing an Embeddable that contains a collection.

- hibernate-core/src/main/java/org/hibernate/service/NullServiceException.java
- hibernate-core/src/main/java/org/hibernate/service/ServiceRegistry.java
- hibernate-core/src/main/java/org/hibernate/service/internal/AbstractServiceRegistryImpl.java
- hibernate-core/src/test/java/org/hibernate/service/ServiceRegistryTest.java
https://hibernate.atlassian.net/browse/HHH-11395
> HHH-11395 - ServiceRegistry#getService(...) throws NPE when service initiator returns null

- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
Missing trailing backtick after org.hibernate.core
> Update Configurations.adoc - Typo org.hibernate.core

- hibernate-core/src/main/java/org/hibernate/event/internal/MergeContext.java
mergeEntity the *merge* entity
> Fix Typo in MergeContext.java

- documentation/src/main/asciidoc/userguide/chapters/envers/Envers.adoc
https://hibernate.atlassian.net/browse/HHH-11461
> HHH-11461: Remove reference to the EnversSchemaGenerator tool in documentation.

- databases.gradle
- documentation/src/main/asciidoc/userguide/chapters/query/spatial/Spatial.adoc
- etc/hibernate.properties.template
- hibernate-core/src/main/java/org/hibernate/boot/registry/selector/internal/StrategySelectorBuilder.java
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/InnoDBStorageEngine.java
- hibernate-core/src/main/java/org/hibernate/dialect/MyISAMStorageEngine.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQL55Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQL57Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQL5Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQL5InnoDBDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLInnoDBDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLMyISAMDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLStorageEngine.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/EntityTest.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/uniqueconstraint/MySQLDropConstraintThrowsExceptionTest.java
- hibernate-core/src/test/java/org/hibernate/test/dialect/unit/lockhint/MySQLStorageEngineTest.java
- hibernate-core/src/test/java/org/hibernate/test/temporal/MySQL57TimestampFspFunctionTest.java
- hibernate-core/src/test/java/org/hibernate/test/temporal/MySQL57TimestampPropertyTest.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/strategy/ValidityAuditStrategyRevEndTsTest.java
- hibernate-envers/src/test/resources/hibernate.test.session-cfg.xml
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/mysql/MySQL56InnoDBSpatialDialect.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/mysql/MySQL56SpatialDialect.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/mysql/MySQL5InnoDBSpatialDialect.java
https://hibernate.atlassian.net/browse/HHH-11473
> HHH-11473 - Refactor MySQL Dialects

- hibernate-infinispan/src/main/java/org/hibernate/cache/infinispan/access/LockingInterceptor.java
- hibernate-infinispan/src/main/java/org/hibernate/cache/infinispan/access/NonStrictAccessDelegate.java
- hibernate-infinispan/src/main/java/org/hibernate/cache/infinispan/access/TombstoneCallInterceptor.java
- hibernate-infinispan/src/main/java/org/hibernate/cache/infinispan/access/VersionedCallInterceptor.java
- hibernate-infinispan/src/main/java/org/hibernate/cache/infinispan/impl/BaseTransactionalDataRegion.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/functional/VersionedTest.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/stress/CorrectnessTestCase.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/stress/entities/Address.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/stress/entities/Person.java
- hibernate-infinispan/src/test/java/org/hibernate/test/cache/infinispan/util/ExpectingInterceptor.java
@gbadner Review if you like, I'll merge this next week if I don't find out further trouble.
> HHH-11372, HHH-11373, HHH-11381 Performance fixes in 2LC

- hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/model/naming/ImplicitConstraintNameSource.java
- hibernate-core/src/main/java/org/hibernate/boot/model/naming/ImplicitNamingStrategyJpaCompliantImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/namingstrategy/LongIdentifierNamingStrategy.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/namingstrategy/LongKeyNamingStrategyTest.java
https://hibernate.atlassian.net/browse/HHH-11089
> HHH-11089 - Naming Strategy Does not affect the user-specified index/foreign-key names

- documentation/src/main/asciidoc/topical/bootstrap/JpaBootstrapping.adoc
- documentation/src/main/asciidoc/topical/generated/GeneratedValues.adoc
- documentation/src/main/asciidoc/topical/logging/Logging.adoc
- documentation/src/main/asciidoc/userguide/chapters/domain/basic_types.adoc
- documentation/src/main/asciidoc/userguide/chapters/query/hql/HQL.adoc
- documentation/src/main/docbook/manual-old/en-US/content/portability.xml
- documentation/src/main/docbook/userGuide/en-US/chapters/portability/Portability.xml
- migration-guide.adoc
see https://hibernate.atlassian.net/projects/HHH/issues/HHH-11547
> HHH-11547 fix some typos in documentation

- hibernate-core/src/main/antlr/hql-sql.g
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/HqlSqlWalker.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/AbstractMapComponentNode.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/DotNode.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/FromReferenceNode.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/IdentNode.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/IndexNode.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/MapEntryNode.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/ResolvableNode.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/SelectExpressionImpl.java
- hibernate-core/src/test/java/org/hibernate/test/hql/EntityJoinTest.java
https://hibernate.atlassian.net/browse/HHH-11538
> HHH 11538 - Skip unnecessary joins for equality and nullness checks of entities

- hibernate-core/src/main/java/org/hibernate/internal/util/ReflectHelper.java
- hibernate-core/src/test/java/org/hibernate/internal/util/ReflectHelperTest.java
- hibernate-core/src/test/java/org/hibernate/test/inheritance/discriminator/joinedsubclass/Common.java
- hibernate-core/src/test/java/org/hibernate/test/inheritance/discriminator/joinedsubclass/JoinedSubclassWithRootInterfaceTest.java
- hibernate-core/src/test/java/org/hibernate/test/inheritance/discriminator/joinedsubclass/TestEntity.hbm.xml
- hibernate-core/src/test/java/org/hibernate/test/inheritance/discriminator/joinedsubclass/TestEntity.java
- hibernate-core/src/test/java/org/hibernate/test/inheritance/discriminator/joinedsubclass/TestEntityImpl.java
- hibernate-core/src/test/java/org/hibernate/test/inheritance/discriminator/joinedsubclass/TestEntityInterface.java
https://hibernate.atlassian.net/browse/HHH-11554
> HHH-11554 - Allow super interface traversal for getter/setter methods.

- hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java
- hibernate-core/src/test/java/org/hibernate/test/jpa/orphan/one2one/OneToOneEagerNonOptionalOrphanRemovalTest.java
- hibernate-core/src/test/java/org/hibernate/test/jpa/orphan/one2one/OneToOneEagerOrphanRemovalTest.java
- hibernate-core/src/test/java/org/hibernate/test/jpa/orphan/one2one/OneToOneLazyNonOptionalOrphanRemovalTest.java
- hibernate-core/src/test/java/org/hibernate/test/jpa/orphan/one2one/OneToOneLazyOrphanRemovalTest.java
- hibernate-core/src/test/java/org/hibernate/test/orphan/one2one/OneToOneEagerNonOptionalOrphanRemovalTest.java
- hibernate-core/src/test/java/org/hibernate/test/orphan/one2one/OneToOneEagerOrphanRemovalTest.java
- hibernate-core/src/test/java/org/hibernate/test/orphan/one2one/OneToOneLazyNonOptionalOrphanRemovalTest.java
- hibernate-core/src/test/java/org/hibernate/test/orphan/one2one/OneToOneLazyOrphanRemovalTest.java
https://hibernate.atlassian.net/browse/HHH-9663
Supercedes https://github.com/hibernate/hibernate-orm/pull/1873.
> HHH-9663 - Fix orphan removal for one to one mappings.

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/ResultSetReturnImpl.java
- hibernate-core/src/main/java/org/hibernate/loader/Loader.java
https://hibernate.atlassian.net/browse/HHH-11600
> HHH-11600 - Sap HANA PreparedStatement implements CallableStatement and is treated as such by Hibernate

- hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/loader/LoaderWithInvalidQueryTest.java
https://hibernate.atlassian.net/browse/HHH-11500
> HHH-11500 - Provide the cause of the error when validating @Loader named queries

- documentation/src/main/asciidoc/userguide/chapters/domain/basic_types.adoc
- documentation/src/test/java/org/hibernate/userguide/naming/AcmeCorpPhysicalNamingStrategy.java
Fixed some minor typos in Hibernate 5.2 User Guide
> HHH-11750 Fixed typos in Hibernate 5.2 User Guide

- documentation/src/main/asciidoc/userguide/chapters/domain/extras/embeddable/Address.java
https://hibernate.atlassian.net/browse/HHH-11804
> HHH-11804 - Make embeddable class' name consistent

- hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jdbc/internal/JdbcResourceLocalTransactionCoordinatorImpl.java
- hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaTransactionCoordinatorImpl.java
- hibernate-core/src/test/java/org/hibernate/sharedSession/SessionWithSharedConnectionTest.java
https://hibernate.atlassian.net/browse/HHH-11830
> HHH-11830 - Shared Session memory leak via TransactionObserver reference

- hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
- hibernate-core/src/main/java/org/hibernate/jpa/spi/CriteriaQueryTupleTransformer.java
- hibernate-core/src/main/java/org/hibernate/jpa/spi/NativeQueryTupleTransformer.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/query/TupleNativeQueryTest.java
https://hibernate.atlassian.net/browse/HHH-11176
> HHH-11176: Add support for Tuple results for native queries

- hibernate-core/src/main/java/org/hibernate/query/Query.java
- hibernate-core/src/test/java/org/hibernate/test/stream/basic/JpaStreamTest.java
https://hibernate.atlassian.net/browse/HHH-11907
> HHH-11907 - Add the getResultStream() default method in org.hibernate.query.Query

- hibernate-core/src/main/java/org/hibernate/hql/internal/HolderInstantiator.java
- hibernate-core/src/main/java/org/hibernate/jpa/spi/NativeQueryTupleTransformer.java
- hibernate-core/src/main/java/org/hibernate/loader/custom/CustomLoader.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/query/TupleNativeQueryTest.java
https://hibernate.atlassian.net/browse/HHH-11897
> HHH-11897: Fix support for Tuple results for native queries

- hibernate-core/src/main/java/org/hibernate/resource/transaction/spi/TransactionStatus.java
* https://hibernate.atlassian.net/browse/HHH-11951
> HHH-11951 Improve TransactionStatus javadoc

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/spi/AbstractDataSourceBasedMultiTenantConnectionProviderImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/spi/AbstractMultiTenantConnectionProvider.java
- hibernate-core/src/test/java/org/hibernate/test/multitenancy/schema/AbstractSchemaBasedMultiTenancyTest.java
- hibernate-core/src/test/java/org/hibernate/test/multitenancy/schema/CurrentTenantResolverMultiTenancyTest.java
- hibernate-core/src/test/java/org/hibernate/test/multitenancy/schema/SchemaBasedDataSourceMultiTenancyTest.java
- hibernate-testing/src/main/java/org/hibernate/testing/env/ConnectionProviderBuilder.java
- hibernate-testing/src/main/java/org/hibernate/testing/transaction/TransactionUtil.java
https://hibernate.atlassian.net/browse/HHH-11651
> HHH-11651 - unwrapping error in AbstractMultiTenantConnectionProvider

- hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/ByteBuddyProxyFactory.java
- hibernate-core/src/main/java/org/hibernate/proxy/pojo/javassist/JavassistProxyFactory.java
https://hibernate.atlassian.net/browse/HHH-3870
> HHH-3870 - Hibernate proxies Groovy's getMetaClass method breaking proxies when used with Groovy

- hibernate-core/src/main/java/org/hibernate/internal/util/ReflectHelper.java
- hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessMixedImpl.java
- hibernate-core/src/main/java/org/hibernate/property/access/spi/GetterFieldImpl.java
- hibernate-core/src/main/java/org/hibernate/property/access/spi/SetterFieldImpl.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/ops/GetLoadTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/ops/Workload.java
- hibernate-core/src/test/java/org/hibernate/property/DirectPropertyAccessorTest.java
- hibernate-core/src/test/java/org/hibernate/property/Order.java
- hibernate-core/src/test/java/org/hibernate/serialization/GetterSetterSerializationTest.java
- hibernate-core/src/test/java/org/hibernate/test/lazyload/LazyLoadingTest.java
https://hibernate.atlassian.net/browse/HHH-11838
> HHH-11838 - Id retrieving from proxy with FK leads to query execution

- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsState.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/LiteralHandlingMode.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/compile/CriteriaCompiler.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/compile/RenderingContext.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/LiteralExpression.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/literal/AbstractCriteriaLiteralHandlingModeTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/literal/CriteriaLiteralHandlingModeAutoTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/literal/CriteriaLiteralHandlingModeBindTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/literal/CriteriaLiteralHandlingModeInlineTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/literal/MySQLCriteriaLiteralHandlingModeInlineTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/nulliteral/CriteriaLiteralsTest.java
https://hibernate.atlassian.net/browse/HHH-9576
> HHH-9576 - Use JDBC bind variables for handling JPA Criteria query numeric literals

- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQL5Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/Oracle8iDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SQLServer2012Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/hint/IndexQueryHintHandler.java
- hibernate-core/src/main/java/org/hibernate/dialect/hint/QueryHintHandler.java
- hibernate-core/src/main/java/org/hibernate/engine/query/spi/NativeSQLQueryPlan.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/exec/BasicExecutor.java
- hibernate-core/src/main/java/org/hibernate/loader/Loader.java
- hibernate-core/src/main/java/org/hibernate/loader/plan/exec/internal/AbstractLoadPlanBasedLoader.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/query/NamedQueryCommentTest.java
- hibernate-core/src/test/java/org/hibernate/test/legacy/FooBarTest.java
- hibernate-core/src/test/java/org/hibernate/test/legacy/MultiTableTest.java
- hibernate-core/src/test/java/org/hibernate/test/legacy/ParentChildTest.java
- libraries.gradle
https://hibernate.atlassian.net/browse/HHH-11640
> HHH-11640 - NamedQuery doesn't log comment when UPDATE/DELETE

- hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java
- hibernate-core/src/test/java/org/hibernate/test/orphan/one2one/OneToOneProxyOrphanRemovalTest.java
https://hibernate.atlassian.net/browse/HHH-11965
> HHH-11965 - Fix cascade of orphan-removal on one-to-one associations with proxies.

- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/id/AbstractIdMapper.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/component/MiddleEmbeddableComponentMapper.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/tools/query/Parameters.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/entities/collection/EmbeddableListEntity3.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/collection/embeddable/EmbeddableList3.java
Backport to 5.0: https://hibernate.atlassian.net/browse/HHH-11364
> Hhh 11364 5.0

- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/LazyBasicFieldMergeTest.java
https://hibernate.atlassian.net/browse/HHH-11117
> HHH-11117 - LazyPropertyInitializer$1 cannot be cast to [B when calling Session.merge() on compile time enhanced composed entities

- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/cfg/annotations/reflection/JPAMetadataProvider.java
- hibernate-core/src/main/java/org/hibernate/cfg/annotations/reflection/JPAOverriddenAnnotationReader.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/mapping/DefaultCascadeTest.java
- hibernate-core/src/test/resources/org/hibernate/jpa/test/mapping/orm.xml
https://hibernate.atlassian.net/browse/HHH-9158
> HHH-9158 cascade-persist in orm.xml does not apply to annotation-based relationships

- hibernate-core/src/main/java/org/hibernate/action/internal/EntityAction.java
- hibernate-core/src/main/java/org/hibernate/action/internal/EntityActionVetoException.java
- hibernate-core/src/main/java/org/hibernate/action/internal/EntityIdentityInsertAction.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
- hibernate-core/src/test/java/org/hibernate/event/PreInsertEventListenerVetoBidirectionalTest.java
- hibernate-core/src/test/java/org/hibernate/event/PreInsertEventListenerVetoUnidirectionalTest.java
https://hibernate.atlassian.net/browse/HHH-11721
> HHH-11721 - PreInsertEventListener that just vetoed ends up throwing NullPointerException because the entity is still managed

- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardIndexExporter.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/index/IndexesCreationTest.java
https://hibernate.atlassian.net/browse/HHH-11913
> HHH-11913 - Schema generation ignores index DESC/ASC order

- hibernate-core/src/main/java/org/hibernate/jpa/event/spi/jpa/ExtendedBeanManager.java
https://hibernate.atlassian.net//browse/HHH-12173
> HHH-12173 Restore backward compatibility in ExtendedBeanManager

- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsState.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/QueryTranslatorImpl.java
- hibernate-core/src/test/java/org/hibernate/test/pagination/hhh9965/HHH9965Test.java
- hibernate-core/src/test/java/org/hibernate/test/pagination/hhh9965/Product.java
- hibernate-core/src/test/java/org/hibernate/test/pagination/hhh9965/Shop.java
Fix https://hibernate.atlassian.net/browse/HHH-9965
> HHH-9965 Pagination ignored on collection fetch join: Add the ability to throw an exception instead of logging a warn

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/BatchingBatch.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/StatementPreparerImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/BasicCollectionPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/test/batch/NonBatchingBatchFailureTest.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithJoinedTableInheritance.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithJoinedTableMultiLevelInheritance.java
- hibernate-core/src/test/java/org/hibernate/test/joinedsubclassbatch/IdentityJoinedSubclassBatchingTest.java
- hibernate-core/src/test/java/org/hibernate/test/joinedsubclassbatch/JoinedSubclassBatchingTest.java
https://hibernate.atlassian.net/browse/HHH-2558
https://hibernate.atlassian.net/browse/HHH-5797
> HHH-2558 - Allow batching inserts for multi-table entities and HHH-5797 - Improve batching for entity updates or deletes that use secondary tables

- hibernate-core/src/main/java/org/hibernate/cfg/CopyIdentifierComponentSecondPass.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/derivedid/ColumnLengthTest.java
https://hibernate.atlassian.net/browse/HHH-12212
> HHH-12212 - Derived Identifiers component column size not applied

- release/release.gradle
https://hibernate.atlassian.net/browse/HHH-12266
> HHH-12266 - The release task does not upload the documentation

- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/jpa/JpaCompliance.java
- hibernate-core/src/main/java/org/hibernate/jpa/spi/JpaComplianceImpl.java
- hibernate-core/src/main/java/org/hibernate/proxy/AbstractLazyInitializer.java
- hibernate-core/src/main/java/org/hibernate/proxy/pojo/javassist/JavassistLazyInitializer.java
- hibernate-core/src/test/java/org/hibernate/jpa/JpaComplianceTestingImpl.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/ops/GetLoadJpaComplianceTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/ops/GetLoadTest.java
https://hibernate.atlassian.net/browse/HHH-12034
> HHH-12034 - According to JPA, a Proxy should be loaded even when accessing the identifier

- hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentSet.java
- hibernate-core/src/test/java/org/hibernate/test/extralazy/ExtraLazyCollectionConsistencyTest.java
- hibernate-core/src/test/java/org/hibernate/test/extralazy/ExtraLazyTest.java
https://hibernate.atlassian.net/browse/HHH-9933
> HHH-9933 - Uninitialized PersistentSet with lazy="extra" doesn't respect added elements

- hibernate-core/src/main/java/org/hibernate/cache/spi/entry/StandardCacheEntryImpl.java
- hibernate-core/src/main/java/org/hibernate/cache/spi/entry/StructuredCacheEntry.java
- hibernate-core/src/test/java/org/hibernate/test/querycache/StructuredQueryCacheTest.java
https://hibernate.atlassian.net/browse/HHH-12107
> HHH-12107 - ClassCastException when using L2Cache with "structured_cache"=true

- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/BasicMetadataGenerator.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/customtype/ExtendedEnumTypeTest.java
https://hibernate.atlassian.net/browse/HHH-12304
> HHH-12304 - Fix MappingException when audited property uses a custom EnumType

- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/AbstractCollectionMapper.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/BasicCollectionMapper.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/ListCollectionMapper.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/MapCollectionMapper.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/lazy/initializor/ListCollectionInitializor.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/collection/CollectionNullValueTest.java
https://hibernate.atlassian.net/browse/HHH-11901
> HHH-11901 - Fix auditing collections that contain null values.

- hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/EntitiesModifiedAtRevisionQuery.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/query/AssociationEntitiesModifiedQueryTest.java
https://hibernate.atlassian.net/browse/HHH-11981
> HHH-11981 - Fix QueryException thrown for association queries using EntitiesModifiedAtRevision queries.

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultEvictEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultRefreshEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/EvictVisitor.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/LazyCollectionDetachTest.java
https://hibernate.atlassian.net/browse/HHH-12260
> HHH-12260: refactor org.hibernate.event.internal.EvictVisitor#evictCollection

- hibernate-core/src/main/java/org/hibernate/proxy/AbstractLazyInitializer.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/ops/GetLoadJpaComplianceDifferentSessionsTest.java
https://hibernate.atlassian.net/browse/HHH-12273
> HHH-12273 - Load Proxy by its identifier should consider the Session UUID

- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/CriteriaSubqueryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/QueryStructure.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/Renderable.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/compile/RenderingContext.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/BinaryArithmeticOperation.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/CoalesceExpression.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/CompoundSelectionImpl.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/ConcatExpression.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/EntityTypeExpression.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/ListIndexExpression.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/LiteralExpression.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/NullifExpression.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/ParameterExpressionImpl.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/PathTypeExpression.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/SearchedCaseExpression.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/SimpleCaseExpression.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/SizeOfPluralAttributeExpression.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/SubqueryComparisonModifierExpression.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/UnaryArithmeticOperation.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/function/BasicFunctionExpression.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/path/AbstractFromImpl.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/path/AbstractPathImpl.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/path/RootImpl.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/predicate/AbstractSimplePredicate.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/predicate/CompoundPredicate.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/predicate/NegatedPredicateWrapper.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/selectcase/GroupBySelectCaseTest.java
https://hibernate.atlassian.net/browse/HHH-12230
> HHH-12230 - SelectCase does not work when simultaneously exists in select and group by sections

- hibernate-core/src/main/java/org/hibernate/cfg/OneToOneSecondPass.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/derivedidentities/e4/b/MedicalHistory.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/onetoone/OneToOneMapsIdJoinColumnTest.java
- hibernate-core/src/test/java/org/hibernate/test/onetoone/optional/BidirectionalOptionalOneToOneTest.java
https://hibernate.atlassian.net/browse/HHH-9460
> HHH-9460 - Removing non-optional bidirectional @OneToOne association with cascade

- hibernate-core/src/main/java/org/hibernate/engine/internal/TwoPhaseLoad.java
- hibernate-core/src/main/java/org/hibernate/type/CollectionType.java
- hibernate-core/src/main/java/org/hibernate/type/EntityType.java
- hibernate-core/src/main/java/org/hibernate/type/Type.java
- hibernate-core/src/test/java/org/hibernate/test/fetchprofiles/CollectionLoadedInTwoPhaseLoadTest.java
- hibernate-core/src/test/java/org/hibernate/test/fetchprofiles/EntityLoadedInTwoPhaseLoadTest.java
- hibernate-core/src/test/java/org/hibernate/test/fetchprofiles/join/JoinFetchProfileTest.java
https://hibernate.atlassian.net/browse/HHH-12297
> HHH-12297 - Relations are not loaded when using Fetch Profiles

- hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithCompositeTypeAssociation.java
https://hibernate.atlassian.net/browse/HHH-12355
> HHH-12355 - Fix ordered insert failures with composite types having associations

- documentation/src/main/asciidoc/userguide/chapters/envers/Envers.adoc
- hibernate-envers/src/main/java/org/hibernate/envers/query/AuditQueryCreator.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/AbstractAuditQuery.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/RevisionsOfEntityQuery.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/auditReader/AuditReaderAPITest.java
https://hibernate.atlassian.net/browse/HHH-7555
> HHH-7555 - Introduce ability to query revision objects without entity instantiation.

- hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingHasParentTest.java
https://hibernate.atlassian.net/browse/HHH-12380
> HHH-12380 - Stackoverflow when order_inserts=true

- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/test/java/org/hibernate/test/queryhint/QueryHintTest.java
https://hibernate.atlassian.net/browse/HHH-12362
> HHH-12362 - Allow both SQL query hints and comments

- hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/model/naming/ImplicitNamingStrategyJpaCompliantImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/model/naming/NamingHelper.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataBuildingOptions.java
- hibernate-core/src/test/java/org/hibernate/boot/model/naming/NamingHelperTest.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/namingstrategy/charset/AbstractCharsetNamingStrategyTest.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/namingstrategy/charset/Iso88591CharsetNamingStrategyTest.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/namingstrategy/charset/Utf8CharsetNamingStrategyTest.java
https://hibernate.atlassian.net/browse/HHH-12357
> HHH-12357 - NamingHelper uses system default encoding

- hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/InFlightMetadataCollector.java
- hibernate-core/src/main/java/org/hibernate/cfg/annotations/EntityBinder.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/secondarytable/SecondaryTableSchemaTest.java
https://hibernate.atlassian.net/browse/HHH-12423
> HHH-12423 - SecondaryTable is not taking into account the schema while mapping the entity

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/MetaAttributeGenerationVisitor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/Constants.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/CollectionAsBasicTypeTest.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/CommaDelimitedStringMapJavaTypeDescriptor.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/CommaDelimitedStringsJavaTypeDescriptor.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/CommaDelimitedStringsMapType.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/CommaDelimitedStringsType.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/Goods.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/Person.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/PersonPhone.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/PhoneBook.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/Product.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/StringToListConverter.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/extras/Phone.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/util/TestUtil.java
https://hibernate.atlassian.net/browse/HHH-12338
> HHH-12338 - Incorrect metamodel for basic collections

- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/engine/query/spi/HQLQueryPlan.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/QueryTranslatorImpl.java
- hibernate-core/src/main/java/org/hibernate/hql/spi/QueryTranslator.java
- hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/query/ImmutableEntityUpdateQueryHandlingMode.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/immutable/ImmutableEntityUpdateQueryHandlingModeExceptionTest.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/immutable/ImmutableEntityUpdateQueryHandlingModeWarningTest.java
https://hibernate.atlassian.net/browse/HHH-12387
> HHH-12387 - Immutable entities can be updated via bulk update queries

- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
- hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataBuildingOptions.java
- hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/cfg/annotations/IdBagBinder.java
- hibernate-core/src/test/java/org/hibernate/test/idgen/namescope/IdGeneratorNamesGlobalScopeTest.java
- hibernate-core/src/test/java/org/hibernate/test/idgen/namescope/IdGeneratorNamesLocalScopeTest.java
- hibernate-core/src/test/java/org/hibernate/test/jpa/idgenerator/TableGeneratorMultipleDefinitionTest.java
- hibernate-core/src/test/java/org/hibernate/test/jpa/idgenerator/TableGeneratorVisibilityTest.java
- migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-12454
> HHH-12454 - Offer flag to consider id generator with local scope (legacy non JPA behavior)

- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/util/SessionFactoryHelper.java
https://hibernate.atlassian.net/browse/HHH-12486
> HHH-12486 - Avoid unnecessary exceptions during entity persister lookup during query compilation

- hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetamodelImpl.java
https://hibernate.atlassian.net/browse/HHH-12485
> HHH-12485 - Avoid unnecessary exceptions during import class name lookup of metamodel

- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/internal/util/MathHelper.java
- hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingsImpl.java
- hibernate-core/src/test/java/org/hibernate/internal/util/MathHelperTest.java
- hibernate-core/src/test/java/org/hibernate/query/InClauseParameterPaddingTest.java
- hibernate-core/src/test/java/org/hibernate/query/MaxInExpressionParameterPaddingTest.java
https://hibernate.atlassian.net/browse/HHH-12469
> HHH-12469 - Add support for IN clause parameter padding to better reuse cached statements

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractPropertyMapping.java
- hibernate-core/src/test/java/org/hibernate/test/dynamicmap/DynamicMapTest.java
- hibernate-core/src/test/java/org/hibernate/test/dynamicmap/Test.hbm.xml
https://hibernate.atlassian.net/browse/HHH-12539
> HHH-12539 - NPE in AbstractPropertyMapping.getCommonPersistentClass when creating UnionSubclassEntityPersister for dynamic-map

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/MetaAttributeGenerationVisitor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/TypeUtils.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/arraytype/ArrayTestWithTypeUseTest.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/arraytype/TestEntity.java
https://hibernate.atlassian.net/browse/HHH-12011
> HHH-12011 - Fix static metamodel generation with TYPE_USE targetted annotations.

- hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaTransactionCoordinatorImpl.java
- hibernate-core/src/main/java/org/hibernate/resource/transaction/spi/TransactionCoordinator.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/transaction/JtaReusingEntityTransactionTest.java
https://hibernate.atlassian.net/browse/HHH-12540
> HHH-12540 - Reusing same EntityTransaction with JTA enabled

- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
- documentation/src/main/asciidoc/userguide/chapters/bootstrap/Bootstrap.adoc
- documentation/src/test/java/org/hibernate/userguide/bootstrap/BootstrapTest.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataBuilderContributor.java
- hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java
- hibernate-core/src/test/java/org/hibernate/boot/spi/metadatabuildercontributor/AbstractSqlFunctionMetadataBuilderContributorTest.java
- hibernate-core/src/test/java/org/hibernate/boot/spi/metadatabuildercontributor/SqlFunctionMetadataBuilderContributor.java
- hibernate-core/src/test/java/org/hibernate/boot/spi/metadatabuildercontributor/SqlFunctionMetadataBuilderContributorClassNameTest.java
- hibernate-core/src/test/java/org/hibernate/boot/spi/metadatabuildercontributor/SqlFunctionMetadataBuilderContributorClassTest.java
- hibernate-core/src/test/java/org/hibernate/boot/spi/metadatabuildercontributor/SqlFunctionMetadataBuilderContributorIllegalArgumentTest.java
- hibernate-core/src/test/java/org/hibernate/boot/spi/metadatabuildercontributor/SqlFunctionMetadataBuilderContributorIllegalClassArgumentTest.java
- hibernate-core/src/test/java/org/hibernate/boot/spi/metadatabuildercontributor/SqlFunctionMetadataBuilderContributorInstanceTest.java
- hibernate-core/src/test/java/org/hibernate/boot/spi/metadatabuildercontributor/SqlFunctionMissingTest.java
https://hibernate.atlassian.net/browse/HHH-12589
> HHH-12589 - Add support for registering custom SQL functions when bootstrapping via JPA

- gradle/databases.gradle
- gradle/libraries.gradle
- hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQL8Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/Oracle8iDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/Oracle9Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQL81Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SQLServer2005Dialect.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/EntityTest.java
- hibernate-core/src/test/java/org/hibernate/test/extralazy/UserGroup.hbm.xml
- hibernate-core/src/test/java/org/hibernate/test/jpa/lock/LockExceptionTests.java
- hibernate-core/src/test/java/org/hibernate/test/locking/AbstractSkipLockedTest.java
- hibernate-core/src/test/java/org/hibernate/test/map/UserGroup.hbm.xml
- hibernate-core/src/test/java/org/hibernate/test/mapelemformula/UserGroup.hbm.xml
- hibernate-core/src/test/java/org/hibernate/test/propertyref/basic/Person.hbm.xml
- hibernate-core/src/test/java/org/hibernate/test/resource/transaction/jdbc/autocommit/MySQLSkipAutoCommitTest.java
- hibernate-core/src/test/java/org/hibernate/test/temporal/MySQL57TimestampPropertyTest.java
- hibernate-core/src/test/java/org/hibernate/test/timestamp/JdbcTimeCustomTimeZoneTest.java
- hibernate-core/src/test/java/org/hibernate/test/timestamp/JdbcTimestampCustomSessionLevelTimeZoneTest.java
- hibernate-core/src/test/java/org/hibernate/test/timestamp/JdbcTimestampCustomTimeZoneTest.java
- hibernate-core/src/test/java/org/hibernate/test/timestamp/LocalDateCustomSessionLevelTimeZoneTest.java
- hibernate-core/src/test/java/org/hibernate/test/type/TimeAndTimestampTest.java
- hibernate-testing/src/main/java/org/hibernate/testing/DialectChecks.java
- hibernate-testing/src/main/java/org/hibernate/testing/util/ExceptionUtil.java
https://hibernate.atlassian.net/browse/HHH-12559
> HHH-12559 - Add support for MySQL 8 SKIP LOCKED and NOWAIT

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/FieldReaderAppender.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/FieldWriterAppender.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/basic/GenericReturnValueMappedSuperclassEnhancementTest.java
* https://hibernate.atlassian.net/browse/HHH-12579
>  HHH-12579 Use the field description with type variables resolved to cast the return value of the $$_hibernate_read_entity() method

- hibernate-core/src/main/java/org/hibernate/query/internal/NativeQueryImpl.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/query/NamedQueryTest.java
This could ultimately lead to ConcurrentModificationException.
* https://hibernate.atlassian.net/browse/HHH-12621
> HHH-12621 Copy the query spaces when initializing a new NativeQueryImpl

- hibernate-core/src/main/java/org/hibernate/cache/spi/support/AbstractReadWriteAccess.java
* https://hibernate.atlassian.net/browse/HHH-12627
> HHH-12627 Fix a debug level message

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultResolveNaturalIdEventListener.java
* https://hibernate.atlassian.net/browse/HHH-12631
> HHH-12631 Fix invalid tracev calls in DefaultResolveNaturalIdEventListener

- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
- documentation/src/main/asciidoc/userguide/chapters/bootstrap/Bootstrap.adoc
- documentation/src/test/java/org/hibernate/userguide/bootstrap/BootstrapTest.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataBuilderContributor.java
- hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java
- hibernate-core/src/test/java/org/hibernate/boot/spi/metadatabuildercontributor/AbstractSqlFunctionMetadataBuilderContributorTest.java
- hibernate-core/src/test/java/org/hibernate/boot/spi/metadatabuildercontributor/SqlFunctionMetadataBuilderContributor.java
- hibernate-core/src/test/java/org/hibernate/boot/spi/metadatabuildercontributor/SqlFunctionMetadataBuilderContributorClassNameTest.java
- hibernate-core/src/test/java/org/hibernate/boot/spi/metadatabuildercontributor/SqlFunctionMetadataBuilderContributorClassTest.java
- hibernate-core/src/test/java/org/hibernate/boot/spi/metadatabuildercontributor/SqlFunctionMetadataBuilderContributorIllegalArgumentTest.java
- hibernate-core/src/test/java/org/hibernate/boot/spi/metadatabuildercontributor/SqlFunctionMetadataBuilderContributorIllegalClassArgumentTest.java
- hibernate-core/src/test/java/org/hibernate/boot/spi/metadatabuildercontributor/SqlFunctionMetadataBuilderContributorInstanceTest.java
- hibernate-core/src/test/java/org/hibernate/boot/spi/metadatabuildercontributor/SqlFunctionMissingTest.java
https://hibernate.atlassian.net/browse/HHH-12589
> [5.2 - backport] HHH-12589 - Add support for registering custom SQL functions when bootstrapping via JPA

- hibernate-core/src/main/java/org/hibernate/procedure/internal/ParameterBindImpl.java
- hibernate-core/src/test/java/org/hibernate/test/procedure/HANAStoredProcedureTest.java
- hibernate-core/src/test/java/org/hibernate/test/procedure/MySQLStoredProcedureTest.java
- hibernate-core/src/test/java/org/hibernate/test/procedure/OracleStoredProcedureTest.java
- hibernate-core/src/test/java/org/hibernate/test/procedure/Phone.java
- hibernate-core/src/test/java/org/hibernate/test/procedure/PostgreSQLStoredProcedureTest.java
- hibernate-core/src/test/java/org/hibernate/test/procedure/SQLServerStoredProcedureTest.java
- hibernate-core/src/test/java/org/hibernate/test/procedure/StoredProcedureParameterTypeTest.java
- hibernate-core/src/test/java/org/hibernate/test/procedure/Vote.java
https://hibernate.atlassian.net/browse/HHH-12661
> HHH-12661 - Hibernate types (e.g. NumericBooleanType, YesNoType and a…ny implementations of UserType) cannot bind value in StoredProcedureQuery

- hibernate-core/src/main/java/org/hibernate/hql/spi/id/AbstractIdsBulkIdHandler.java
- hibernate-core/src/main/java/org/hibernate/hql/spi/id/cte/AbstractCteValuesListBulkIdHandler.java
- hibernate-core/src/test/java/org/hibernate/test/bulkid/GlobalQuotedIdentifiersBulkIdTest.java
https://hibernate.atlassian.net/browse/HHH-12561
> HHH-12561 - bulk_id_strategy does not work with globally_quoted_identifiers

- documentation/src/main/asciidoc/userguide/chapters/domain/basic_types.adoc
- hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingImpl.java
- hibernate-core/src/test/java/org/hibernate/test/converter/ConverterTest.java
https://hibernate.atlassian.net/browse/HHH-12662
> HHH-12662 - JPQL queries fail when using the Java attribute type which has an associated AttributeConverter (only the DB column type works)

- hibernate-core/src/main/java/org/hibernate/query/internal/NativeQueryImpl.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/graphs/EntityGraphNativeQueryTest.java
https://hibernate.atlassian.net/browse/HHH-12476
> HHH-12476 - NativeQuery with EntityGraphs assumes a HQL query

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/SqlExceptionHelper.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/immutable/ImmutableEntityUpdateQueryHandlingModeWarningTest.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/uniqueconstraint/UniqueConstraintBatchingTest.java
- hibernate-core/src/test/java/org/hibernate/test/locking/warning/LockNoneWarmingTest.java
- hibernate-testing/src/main/java/org/hibernate/testing/logger/TriggerOnPrefixLogListener.java
- hibernate-testing/src/main/java/org/hibernate/testing/logger/Triggerable.java
https://hibernate.atlassian.net/browse/HHH-12688
> HHH-12688 - Duplicated Error Information Displayed in the Log

- hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/AbstractPluralAttributeSourceImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/PluralAttributeKeySourceImpl.java
- hibernate-core/src/test/java/org/hibernate/test/nonpkassociation/NonPkManyToOneAssociationHbmTest.hbm.xml
- hibernate-core/src/test/java/org/hibernate/test/nonpkassociation/NonPkManyToOneAssociationHbmTest.java
- hibernate-core/src/test/java/org/hibernate/test/nonpkassociation/NonPkManyToOneAssociationTest.java
https://hibernate.atlassian.net/browse/HHH-12684
> HHH-12684 - Hibernate fails when mapping one-to-many collections by non-primary key

- hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java
- hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetamodelImpl.java
- hibernate-core/src/test/java/org/hibernate/test/metamodel/Address.java
- hibernate-core/src/test/java/org/hibernate/test/metamodel/Company.java
- hibernate-core/src/test/java/org/hibernate/test/metamodel/EmbeddableMetaModelTest.java
- hibernate-core/src/test/java/org/hibernate/test/metamodel/Person.java
https://hibernate.atlassian.net/browse/HHH-12124
> HHH-12124 - The JPA Metamodel does not allow to retrieve the actual EmbeddableType since all instances are registered by the associated Java type

- hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/query/ScalarResultNativeQueryTest.java
https://hibernate.atlassian.net/browse/HHH-12670
> HHH-12670 - Allows native SQL queries that take a given result Class to map the result set to the required type

- hibernate-core/src/main/java/org/hibernate/engine/transaction/jta/platform/internal/JBossStandAloneJtaPlatform.java
- hibernate-core/src/main/java/org/hibernate/engine/transaction/jta/platform/internal/StandardJtaPlatformResolver.java
- hibernate-core/src/main/java/org/hibernate/engine/transaction/jta/platform/internal/WildFlyStandAloneJtaPlatform.java
@scottmarlow re-worked your PR a bit as a follow up of our other chat. You like this approach?
> HHH-12640 2nd ed

- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/test/java/org/hibernate/test/idgen/foreign/ForeignGeneratorJtaTest.java
- hibernate-core/src/test/java/org/hibernate/test/idgen/foreign/ForeignGeneratorResourceLocalTest.java
https://hibernate.atlassian.net/browse/HHH-12738
> HHH-12738 - Session/EntityManager is closed in ForeignGenerator (JTA setup)

- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/compile/CriteriaQueryTypeQueryAdapter.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/CriteriaQueryTypeQueryAdapterTest.java
- hibernate-core/src/test/java/org/hibernate/test/criteria/hhh12685/CriteriaQueryIsBoundManualParameterTest.java
https://hibernate.atlassian.net/browse/HHH-12685
> HHH-12685 ClassCastException when checking if parameter isBound in criteria query

- hibernate-c3p0/hibernate-c3p0.gradle
- hibernate-c3p0/src/main/java/org/hibernate/c3p0/internal/C3P0ConnectionProvider.java
- hibernate-c3p0/src/test/java/org/hibernate/test/c3p0/C3P0DefaultIsolationLevelTest.java
- hibernate-c3p0/src/test/java/org/hibernate/test/c3p0/C3P0DifferentIsolationLevelTest.java
- hibernate-c3p0/src/test/java/org/hibernate/test/c3p0/C3P0ProxyConnectionProvider.java
- hibernate-c3p0/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- hibernate-core/src/test/java/org/hibernate/boot/model/naming/NamingHelperTest.java
- hibernate-core/src/test/java/org/hibernate/test/dialect/functional/OracleFollowOnLockingTest.java
- hibernate-core/src/test/java/org/hibernate/test/distinct/SelectDistinctHqlTest.java
- hibernate-core/src/test/java/org/hibernate/test/id/SequenceGeneratorTest.java
- hibernate-core/src/test/java/org/hibernate/test/locking/PessimisticWriteLockTimeoutTest.java
- hibernate-core/src/test/java/org/hibernate/test/resource/transaction/jdbc/autocommit/H2SkipAutoCommitTest.java
- hibernate-core/src/test/java/org/hibernate/test/resource/transaction/jdbc/autocommit/MySQLSkipAutoCommitTest.java
- hibernate-core/src/test/java/org/hibernate/test/resource/transaction/jdbc/autocommit/OracleSkipAutoCommitTest.java
- hibernate-core/src/test/java/org/hibernate/test/resource/transaction/jdbc/autocommit/PostgreSQLSkipAutoCommitTest.java
- hibernate-core/src/test/java/org/hibernate/test/resource/transaction/jdbc/autocommit/SQLServerSkipAutoCommitTest.java
- hibernate-testing/src/main/java/org/hibernate/testing/jdbc/SQLStatementInterceptor.java
- hibernate-testing/src/main/java/org/hibernate/testing/util/ReflectionUtil.java
https://hibernate.atlassian.net/browse/HHH-12749
> HHH-12749 - Avoid setting the isolation level to the same value in C3P0ConnectionProvider

- documentation/src/main/asciidoc/userguide/appendices/Annotations.adoc
- documentation/src/main/asciidoc/userguide/appendices/BestPractices.adoc
- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
- documentation/src/main/asciidoc/userguide/chapters/domain/entity.adoc
- documentation/src/main/asciidoc/userguide/chapters/pc/PersistenceContext.adoc
- documentation/src/main/asciidoc/userguide/chapters/query/native/Native.adoc
- documentation/src/test/java/org/hibernate/userguide/proxy/ProxyInterfaceTest.java
https://hibernate.atlassian.net/browse/HHH-12353
> HHH-12353 - Document that Session.getReference not always returns a T

- hibernate-core/src/main/java/org/hibernate/cfg/annotations/EntityBinder.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/SchemaUpdateJoinColumnNoConstraintSecondaryTableTest.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/SchemaUpdateJoinColumnNoConstraintSecondaryTablesTest.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/SchemaUpdateJoinColumnNoConstraintTest.java
https://hibernate.atlassian.net/browse/HHH-8805
> HHH-8805 - [SchemaUpdate] javax.persistence.ForeignKey doesn't respect ConstraintMode.NO_CONSTRAINT

- release/release.gradle
* https://hibernate.atlassian.net/browse/HHH-12774
> HHH-12774 Add missing jars to the distribution archives

- documentation/src/main/asciidoc/userguide/chapters/domain/basic_types.adoc
- documentation/src/main/asciidoc/userguide/chapters/domain/extras/basic/mapping-filter-entity-example.sql
- documentation/src/main/asciidoc/userguide/chapters/domain/extras/basic/mapping-filter-entity-query-example.sql
- documentation/src/main/asciidoc/userguide/chapters/domain/extras/basic/mapping-filter-join-table-persistence-example.sql
- documentation/src/main/asciidoc/userguide/chapters/domain/extras/basic/mapping-filter-persistence-example.sql
- documentation/src/main/asciidoc/userguide/chapters/domain/extras/basic/mapping-no-filter-collection-query-example.sql
- documentation/src/main/asciidoc/userguide/chapters/domain/extras/basic/mapping-no-filter-entity-query-example.sql
- documentation/src/main/asciidoc/userguide/chapters/domain/extras/basic/mapping-no-filter-join-table-collection-query-example.sql
- documentation/src/test/java/org/hibernate/userguide/mapping/basic/FilterJoinTableTest.java
- documentation/src/test/java/org/hibernate/userguide/mapping/basic/FilterTest.java
https://hibernate.atlassian.net/browse/HHH-12349
> HHH-12349 - User Guide documentation for @Filter is too verbose

- hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/selectcase/GroupBySelectCaseTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/selectcase/SelectCaseTest.java
- hibernate-core/src/test/java/org/hibernate/query/criteria/internal/expression/SearchedCaseExpressionTest.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/SchemaMigratorHaltOnErrorTest.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/SchemaUpdateHaltOnErrorTest.java
- hibernate-core/src/test/java/org/hibernate/test/timestamp/LocalDateCustomSessionLevelTimeZoneTest.java
* https://hibernate.atlassian.net/browse/HHH-12815
* https://hibernate.atlassian.net/browse/HHH-12822
* https://hibernate.atlassian.net/browse/HHH-12827
> Database compatibility fixes

- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/DotNode.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractPropertyMapping.java
- hibernate-core/src/main/java/org/hibernate/type/EntityType.java
- hibernate-core/src/main/java/org/hibernate/type/ManyToOneType.java
- hibernate-core/src/main/java/org/hibernate/type/OneToOneType.java
- hibernate-core/src/test/java/org/hibernate/test/hql/NaturalIdDereferenceTest.java
Implements: https://hibernate.atlassian.net/browse/HHH-12775
> HHH-12775 - Avoid join on natural id property access

- hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BasicProxyFactoryImpl.java
- hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java
- hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/ByteBuddyProxyHelper.java
This commit should reduce the garbage collection pressure as reported at
https://github.com/raphw/byte-buddy/issues/515.
* https://hibernate.atlassian.net/browse/HHH-12907
> HHH-12907 Avoid creating too many ByteBuddy objects

- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/db2/DB2SpatialDialect.java
- hibernate-spatial/src/test/java/org/hibernate/spatial/testing/dialects/db2/DB2ExpectationsFactory.java
https://hibernate.atlassian.net/browse/HHH-12608 for 5.3.
> HHH-12608 Support for ST_Dwithin() in DB2

- hibernate-core/src/main/java/org/hibernate/procedure/internal/ParameterBindImpl.java
- hibernate-core/src/test/java/org/hibernate/test/procedure/MySQLStoredProcedureTest.java
- hibernate-core/src/test/java/org/hibernate/test/procedure/PostgreSQLStoredProcedureTest.java
- hibernate-core/src/test/java/org/hibernate/test/procedure/StoredProcedureParameterTypeTest.java
https://hibernate.atlassian.net/browse/HHH-12905
> HHH-12905 - Bind value [null] was not of specified type in StoredProcedureQuery

- hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
https://hibernate.atlassian.net/browse/HHH-12915
> HHH-12915 - Concurrency issue within org.hibernate.internal.SessionFactoryImpl

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DriverManagerConnectionProviderImpl.java
- hibernate-core/src/test/java/org/hibernate/connection/DriverManagerConnectionProviderValidationConfigTest.java
https://hibernate.atlassian.net/browse/HHH-12921
https://hibernate.atlassian.net/browse/HHH-12922
> HHH-12921 - Hibernate Connection Pool Validation Thread should be defined as a daemon Thread

- hibernate-core/src/main/java/org/hibernate/boot/cfgxml/internal/ConfigLoader.java
- hibernate-core/src/main/java/org/hibernate/boot/jaxb/internal/AbstractBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/registry/classloading/internal/ClassLoaderServiceImpl.java
- hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java
- hibernate-core/src/main/java/org/hibernate/internal/util/ConfigHelper.java
- hibernate-core/src/main/java/org/hibernate/internal/util/ReflectHelper.java
- hibernate-core/src/main/java/org/hibernate/jpa/event/internal/CallbackBuilderLegacyImpl.java
- hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java
- hibernate-core/src/main/java/org/hibernate/tuple/entity/PojoEntityTuplizer.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/AuditedPropertiesReader.java
* https://hibernate.atlassian.net/browse/HHH-12931
* https://hibernate.atlassian.net/browse/HHH-12932
> Fixing security manager issues (5.3)

- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/QueryTranslatorImpl.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/FromElement.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/classic/QueryTranslatorImpl.java
- hibernate-core/src/main/java/org/hibernate/hql/spi/QueryTranslator.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/immutable/ImmutableEntityUpdateQueryHandlingModeExceptionTest.java
https://hibernate.atlassian.net/browse/HHH-12927
> HHH-12927 - Immutable warning issued if immutable entities are referenced but not changed during update

- documentation/src/main/asciidoc/userguide/chapters/transactions/Transactions.adoc
- gradle/libraries.gradle
- hibernate-core/hibernate-core.gradle
- hibernate-core/src/main/java/org/hibernate/boot/registry/selector/internal/StrategySelectorBuilder.java
- hibernate-core/src/main/java/org/hibernate/engine/transaction/jta/platform/internal/AtomikosJtaPlatform.java
- hibernate-core/src/main/java/org/hibernate/engine/transaction/jta/platform/internal/StandardJtaPlatformResolver.java
- hibernate-core/src/test/java/org/hibernate/test/lazyload/AtomikosJtaLazyLoadingTest.java
https://hibernate.atlassian.net/browse/HHH-12929
> HHH-12929 - Add AtomikosJtaPlatform implementation

- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/stat/Statistics.java
- hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsImpl.java
- hibernate-core/src/test/java/org/hibernate/test/stats/ExplicitQueryStatsMaxSizeTest.java
- hibernate-core/src/test/java/org/hibernate/test/stats/QueryStatsMaxSizeTest.java
https://hibernate.atlassian.net/browse/HHH-12933
> HHH-12933 - Generate_statistics grows QueryStatistics ConcurrentHashMap indefinitely

- documentation/src/main/asciidoc/userguide/Hibernate_User_Guide.adoc
- documentation/src/main/asciidoc/userguide/chapters/portability/Portability.adoc
- documentation/src/main/asciidoc/userguide/chapters/statistics/Statistics.adoc
- hibernate-core/src/main/java/org/hibernate/stat/Statistics.java
https://hibernate.atlassian.net/browse/HHH-12952
> HHH-12952 - Document the hibernate.statistics.query_max_size behavior and explain its implications

- documentation/src/main/asciidoc/userguide/chapters/statistics/Statistics.adoc
- hibernate-core/src/main/java/org/hibernate/engine/query/spi/QueryPlanCache.java
- hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
- hibernate-core/src/main/java/org/hibernate/stat/QueryStatistics.java
- hibernate-core/src/main/java/org/hibernate/stat/Statistics.java
- hibernate-core/src/main/java/org/hibernate/stat/internal/QueryStatisticsImpl.java
- hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsImpl.java
- hibernate-core/src/main/java/org/hibernate/stat/spi/StatisticsImplementor.java
- hibernate-core/src/test/java/org/hibernate/stat/internal/ConcurrentQueryStatisticsTest.java
- hibernate-core/src/test/java/org/hibernate/stat/internal/QueryPlanCacheStatisticsTest.java
https://hibernate.atlassian.net/browse/HHH-12855
> HHH-12855 - Add query plan compilation statistics

- documentation/src/main/asciidoc/userguide/chapters/query/hql/HQL.adoc
- documentation/src/test/java/org/hibernate/userguide/hql/PostgreSQLFunctionSelectClauseTest.java
- documentation/src/test/java/org/hibernate/userguide/hql/PostgreSQLFunctionWhereClauseTest.java
https://hibernate.atlassian.net/browse/HHH-12957
> HHH-12957 - Calling custom functions in JPQL with the function() is missing in the documentation

- hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/inheritance/joined/JoinedSubclassAndSecondaryTable.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/inheritance/joined/Pool.java
See: https://hibernate.atlassian.net/browse/HHH-12675
> HHH-12675 - Respect inverse property for JoinedSubclassEntityPersister

- hibernate-core/src/main/java/org/hibernate/Hibernate.java
- hibernate-core/src/test/java/org/hibernate/test/proxy/HibernateUnproxyTest.java
https://hibernate.atlassian.net/browse/HHH-12982
> HHH-12982 - Generify Hibernate#unproxy

- documentation/src/main/asciidoc/userguide/chapters/pc/PersistenceContext.adoc
- documentation/src/main/asciidoc/userguide/chapters/transactions/Transactions.adoc
https://hibernate.atlassian.net/browse/HHH-12934
> HHH-12934 - Exception handling documentation does not apply only to "Session-per-application anti-pattern"

- hibernate-core/src/main/java/org/hibernate/boot/registry/selector/internal/StrategySelectorBuilder.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/EntityCopyAllowedLoggedObserver.java
- hibernate-core/src/main/java/org/hibernate/event/internal/EntityCopyAllowedObserver.java
- hibernate-core/src/main/java/org/hibernate/event/internal/EntityCopyNotAllowedObserver.java
- hibernate-core/src/main/java/org/hibernate/event/internal/EntityCopyObserverFactoryInitiator.java
- hibernate-core/src/main/java/org/hibernate/event/spi/EntityCopyObserverFactory.java
- hibernate-core/src/main/java/org/hibernate/service/StandardServiceInitiators.java
Probably for @johnaohara , or anyone else interested? ;)
> HHH-13015 Optimise loading of EntityCopyObserver implementation

- documentation/src/main/asciidoc/userguide/chapters/caching/Caching.adoc
https://hibernate.atlassian.net/browse/HHH-13009
> HHH-13009 - No documentation for "hibernate.javax.cache.cache_manager"

- gradle/libraries.gradle
- hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQL81Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SAPDBDialect.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/LobCreatorBuilderImpl.java
- hibernate-core/src/test/java/org/hibernate/engine/jdbc/env/internal/LobCreationCheckSkipTest.java
https://hibernate.atlassian.net/browse/HHH-12368
> HHH-12368 - java.sql.SQLFeatureNotSupportedException in LobCreatorBuilderImpl

- hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java
- hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetamodelImpl.java
https://hibernate.atlassian.net/browse/HHH-13025
> HHH-13025 - Rename MetadataContext#getEmbeddableTypeMap to getEmbeddableTypeSet

- README.md
Hi team!
Hibernate ORM was one of the early adopters of LGTM.com, and your code quality has improved steadily over time. Here's a badge to show that off to users and contributors :slightly_smiling_face: — keep up the good work!
> Add LGTM.com code quality badge

- hibernate-core/src/main/java/org/hibernate/metamodel/model/convert/internal/NamedEnumValueConverter.java
- hibernate-core/src/main/java/org/hibernate/metamodel/model/convert/internal/OrdinalEnumValueConverter.java
- hibernate-core/src/main/java/org/hibernate/metamodel/model/convert/spi/EnumValueConverter.java
- hibernate-core/src/main/java/org/hibernate/type/EnumType.java
- hibernate-core/src/test/java/org/hibernate/test/enums/OrdinalEnumTypeTest.java
https://hibernate.atlassian.net/browse/HHH-12978
> HHH-12978 - Enum value binding is not logged by BasicBinder

- hibernate-core/src/main/java/org/hibernate/boot/registry/StandardServiceRegistryBuilder.java
- hibernate-core/src/main/java/org/hibernate/cfg/Environment.java
- hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
- hibernate-core/src/main/java/org/hibernate/tool/hbm2ddl/ManagedProviderConnectionHelper.java
- hibernate-core/src/test/java/org/hibernate/test/exceptionhandling/BaseJpaOrNativeBootstrapFunctionalTestCase.java
- hibernate-testing/src/main/java/org/hibernate/testing/junit4/BaseCoreFunctionalTestCase.java
- https://hibernate.atlassian.net/browse/HHH-13047
> HHH-13047 Deprecate Environment#verifyProperties

- documentation/src/main/asciidoc/userguide/chapters/domain/entity.adoc
- documentation/src/main/asciidoc/userguide/chapters/envers/Envers.adoc
- documentation/src/test/java/org/hibernate/userguide/envers/EntityTypeChangeAuditTest.java
- documentation/src/test/java/org/hibernate/userguide/mapping/identifier/Book.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/access/BaseFurniture.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/access/Closet.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/access/Furniture.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/duplicatedgenerator/DuplicateTest.java
- hibernate-core/src/test/java/org/hibernate/test/entityname/DuplicateEntityNameTest.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/foreignkeys/JoinedInheritanceForeignKeyTest.java
https://hibernate.atlassian.net/browse/HHH-13060
> HHH-13060 - Throw an exception when two entities are declared with the same name

- documentation/src/main/asciidoc/userguide/chapters/pc/PersistenceContext.adoc
- documentation/src/main/asciidoc/userguide/chapters/pc/extras/pc-by-multiple-ids-example.sql
- documentation/src/test/java/org/hibernate/userguide/pc/MultiLoadIdTest.java
- hibernate-core/src/main/java/org/hibernate/MultiIdentifierLoadAccess.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/loader/entity/CacheEntityLoaderHelper.java
- hibernate-core/src/main/java/org/hibernate/loader/entity/DynamicBatchingEntityLoaderBuilder.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/MultiLoadOptions.java
- hibernate-core/src/test/java/org/hibernate/test/ops/multiLoad/MultiLoadTest.java
https://hibernate.atlassian.net/browse/HHH-12944
> HHH-12944 - MultiIdentifierLoadAccess ignores the 2nd level cache

- hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/query/Query.java
- hibernate-core/src/main/java/org/hibernate/query/internal/AbstractProducedQuery.java
- hibernate-core/src/main/java/org/hibernate/query/internal/QueryImpl.java
- hibernate-core/src/test/java/org/hibernate/stat/internal/QueryPlanCacheStatisticsTest.java
https://hibernate.atlassian.net/browse/HHH-13077
> HHH-13077 - Optimize query plan call count

- hibernate-core/src/main/java/org/hibernate/boot/model/process/spi/MetadataBuildingProcess.java
- hibernate-core/src/main/java/org/hibernate/loader/custom/JdbcResultMetadata.java
- hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java
- hibernate-core/src/test/java/org/hibernate/test/id/usertype/PostgreSQLMultipleTypesOtherContributorTest.java
- hibernate-core/src/test/java/org/hibernate/test/id/usertype/inet/Event.java
- hibernate-core/src/test/java/org/hibernate/test/id/usertype/inet/Inet.java
- hibernate-core/src/test/java/org/hibernate/test/id/usertype/inet/InetJavaTypeDescriptor.java
- hibernate-core/src/test/java/org/hibernate/test/id/usertype/inet/InetSqlTypeDescriptor.java
- hibernate-core/src/test/java/org/hibernate/test/id/usertype/inet/InetType.java
- hibernate-core/src/test/java/org/hibernate/test/id/usertype/inet/PostgreSQLInetTypesOtherContributorTest.java
- hibernate-core/src/test/java/org/hibernate/test/id/usertype/inet/PostgreSQLInetTypesOtherTest.java
- hibernate-core/src/test/java/org/hibernate/test/id/usertype/json/Json.java
- hibernate-core/src/test/java/org/hibernate/test/id/usertype/json/JsonJavaTypeDescriptor.java
- hibernate-core/src/test/java/org/hibernate/test/id/usertype/json/JsonSqlTypeDescriptor.java
- hibernate-core/src/test/java/org/hibernate/test/id/usertype/json/JsonType.java
- hibernate-core/src/test/java/org/hibernate/test/id/uuid/PostgreSQLUUIDGeneratedValueTest.java
- hibernate-core/src/test/java/org/hibernate/test/type/contributor/ArrayTypeContributorTest.java
https://hibernate.atlassian.net/browse/HHH-12925
> HHH-12925 - The JDBC Type to Hibernate matching is limited to the Dialect only instead of considering the Type contributions as well

- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
- documentation/src/main/asciidoc/userguide/chapters/domain/identifiers.adoc
- migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-13101
> HHH-13101 - Document `hibernate.id.disable_delayed_identity_inserts`

- hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingHasParentTest.java
https://hibernate.atlassian.net/browse/HHH-12374
https://hibernate.atlassian.net/browse/HHH-12380
> HHH-12374 HHH-12380

- hibernate-core/src/main/java/org/hibernate/type/TypeFactory.java
- hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java
- hibernate-core/src/test/java/org/hibernate/test/type/contributor/ArraySpyType.java
- hibernate-core/src/test/java/org/hibernate/test/type/contributor/CustomTypeInstanceCountTest.java
https://hibernate.atlassian.net/browse/HHH-13105
> HHH-13105 - Add registries for user-defined Types as currently a custom Type is instantiated and configured 9 times

- hibernate-core/src/main/java/org/hibernate/boot/model/relational/NamedAuxiliaryDatabaseObject.java
- hibernate-core/src/main/java/org/hibernate/boot/model/relational/SimpleAuxiliaryDatabaseObject.java
- hibernate-core/src/main/java/org/hibernate/mapping/ForeignKey.java
- hibernate-core/src/main/java/org/hibernate/mapping/Index.java
- hibernate-core/src/main/java/org/hibernate/mapping/PrimaryKey.java
- hibernate-core/src/main/java/org/hibernate/mapping/UniqueKey.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/ExportIdentifierTest.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/various/ExportIdentifierTest.java
https://hibernate.atlassian.net/browse/HHH-12935
> HHH-12935 (5.1)

- gradle/libraries.gradle
- hibernate-core/src/test/java/AnnotationMappedNoPackageEntity.java
- hibernate-core/src/test/java/NoPackageTest.java
https://hibernate.atlassian.net//browse/HHH-13112
Note the bug only occurs with JDK9 and above (11 in particular).
> HHH-13112 Proxies on entity types in the default package lead to MappingException with JDK9+

- hibernate-core/src/main/java/org/hibernate/dialect/SQLServer2012Dialect.java
- hibernate-core/src/test/java/org/hibernate/test/dialect/functional/SQLServerDialectSequenceInformationTest.java
https://hibernate.atlassian.net/browse/HHH-13141
> HHH-13141 - Could not fetch the SequenceInformation from the database when using SQL Server with a case-sensitive collation

- documentation/src/main/asciidoc/userguide/chapters/query/hql/HQL.adoc
- documentation/src/test/java/org/hibernate/userguide/hql/HQLTest.java
- hibernate-core/src/test/java/org/hibernate/test/hql/CaseStatementTest.java
https://hibernate.atlassian.net/browse/HHH-13095
> HHH-13095 - Document how to use arithmetic expressions in CASE statements

- hibernate-core/src/main/java/org/hibernate/cfg/AttributeConverterDefinition.java
- hibernate-core/src/main/java/org/hibernate/resource/beans/internal/FallbackBeanInstanceProducer.java
- hibernate-core/src/test/java/org/hibernate/boot/model/process/internal/IntegerToVarcharConverter.java
- hibernate-core/src/test/java/org/hibernate/boot/model/process/internal/ScanningCoordinatorTest.java
- hibernate-core/src/test/java/org/hibernate/test/converter/AttributeConverterTest.java
- hibernate-core/src/test/java/org/hibernate/test/converter/PackagePrivateAttributeConverterEntityManagerFactoryTest.java
- hibernate-core/src/test/java/org/hibernate/test/converter/PackagePrivateAttributeConverterSessionFactoryTest.java
https://hibernate.atlassian.net/browse/HHH-10778
> HHH-10778 - Add support for non-public AttributeConverter implementations

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-ehcache/src/test/java/org/hibernate/cache/ehcache/test/IdentityIdentifierDelayedInsertTest.java
https://hibernate.atlassian.net/browse/HHH-13147
> HHH-13147 - Fix DelayedPostIdentifierInsert when using second-level cache.

- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/path/AbstractPathImpl.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/alias/CriteriaMultiselectAliasTest.java
https://hibernate.atlassian.net/browse/HHH-13140
> HHH-13140 - Criteria API multiselect aliases are not passed through to the JPQL query and they are not available in ResultTransformer

- documentation/src/main/asciidoc/userguide/chapters/query/hql/HQL.adoc
https://hibernate.atlassian.net/browse/HHH-13153
> HHH-13153 - No content in 15.1. Query API of User Guide

- hibernate-core/src/main/java/org/hibernate/dialect/MySQL5Dialect.java
https://hibernate.atlassian.net/browse/HHH-13162
> HHH-13162 - Upgrade MySQL and MariaDB Dialects as they support UNION ALL

- documentation/src/main/asciidoc/userguide/chapters/domain/inheritance.adoc
https://hibernate.atlassian.net/browse/HHH-13160
> HHH-13160 - Polymorphic query for InheritanceType.TABLE_PER_CLASS is not using UNION ALL

- hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/SingularAttributeSourceAnyImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/model/source/spi/AnyMappingSource.java
- hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
- hibernate-core/src/main/java/org/hibernate/cfg/BinderHelper.java
- hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java
- hibernate-core/src/main/java/org/hibernate/mapping/Any.java
- hibernate-core/src/main/java/org/hibernate/type/AnyType.java
- hibernate-core/src/main/java/org/hibernate/type/TypeFactory.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/any/AnyTest.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/any/LazyPropertySet.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/any/PropertyList.java
- hibernate-core/src/test/java/org/hibernate/test/any/AnyEagerHbmTest.java
- hibernate-core/src/test/java/org/hibernate/test/any/AnyLazyHbmTest.java
- hibernate-core/src/test/resources/org/hibernate/test/any/AnyTestEagerPropertySet.hbm.xml
- hibernate-core/src/test/resources/org/hibernate/test/any/AnyTestLazyPropertySet.hbm.xml
https://hibernate.atlassian.net/browse/HHH-13094
> HHH-13094 - Respect @Any.fetch setting to FetchType.EAGER

- hibernate-core/src/main/java/org/hibernate/proxy/AbstractLazyInitializer.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/jta/IdentifierProxyJtaSessionClosedBeforeCommitTest.java
https://hibernate.atlassian.net/browse/HHH-13191
> HHH-13191 - - Fix LazyInitializationException with auto-close session and JPA_PROXY_COMPLIANCE enabled.

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/javassist/EnhancerImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
* https://hibernate.atlassian.net/browse/HHH-13197
> HHH-13197 Reduce bootstrap log verbosity

- hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingSelfReferenceSingleTableInheritance.java
https://hibernate.atlassian.net/browse/HHH-13068
> HHH-13068 - "order_inserts = true" causes FK Violation when inserting Self Referential Entity with Single_Table Inherited Entities

- hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java
- hibernate-core/src/test/java/org/hibernate/dialect/HANADialectTestCase.java
https://hibernate.atlassian.net/browse/HHH-13239
> HHH-13239 - The query hint javax.persistence.lock.timeout doesn't work correctly on HANA

- gradle/databases.gradle
- hibernate-core/src/main/java/org/hibernate/dialect/MariaDB103Dialect.java
- hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStyleGenerator.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/SequenceInformationExtractorMariaDBDatabaseImpl.java
- hibernate-core/src/test/java/org/hibernate/id/SequenceValueExtractor.java
- hibernate-core/src/test/java/org/hibernate/test/dialect/functional/SequenceInformationMariaDBTest.java
https://hibernate.atlassian.net/browse/HHH-13229
> HHH-13229 - Sequences in MariaDB doesnt work on existing sequence

- documentation/src/test/java/org/hibernate/userguide/jmx/JmxTest.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/BatchBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/jmx/internal/JmxServiceImpl.java
- hibernate-core/src/main/java/org/hibernate/service/spi/Manageable.java
- hibernate-core/src/main/java/org/hibernate/service/spi/OptionallyManageable.java
- hibernate-core/src/main/java/org/hibernate/stat/Statistics.java
- hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsImpl.java
https://hibernate.atlassian.net/browse/HHH-6190
> HHH-6190 - Leverage JmxService to expose management and monitoring capabilities.

- hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java
- hibernate-core/src/test/java/org/hibernate/cfg/CfgFilePropertyTest.java
https://hibernate.atlassian.net/browse/HHH-13227
> HHH-13227 - UnsupportedOperationException when programmatically overriding hibernate.ejb.cfgfile

- hibernate-core/src/main/java/org/hibernate/tool/schema/spi/SchemaManagementToolCoordinator.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/schemagen/SchemaScriptFileGenerationFailureTest.java
https://hibernate.atlassian.net/browse/HHH-13230
> HHH-13230 - The AvailableSettings.HBM2DDL_HALT_ON_ERROR setting does not accept String values

- hibernate-core/src/main/java/org/hibernate/internal/util/collections/ArrayHelper.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/type/TypeHelper.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/InMemoryCreationTimestampNullableColumnTest.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/InMemoryUpdateTimestampTest.java
https://hibernate.atlassian.net/browse/HHH-13256
> HHH-13256 - Fix the fieldsPreUpdateNeeded property index allocation in AbstractEntityPersister#update

- hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
- hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
- hibernate-core/src/test/java/org/hibernate/test/inheritance/MappedSuperclassInheritanceTest.java
https://hibernate.atlassian.net/browse/HHH-13217
> HHH-13217 - Don't throw exception if both @MappedSuperclass and @Inheritance are used

- hibernate-core/src/main/java/org/hibernate/loader/plan/exec/internal/AbstractLoadQueryDetails.java
- hibernate-core/src/main/java/org/hibernate/loader/plan/exec/internal/EntityLoadQueryDetails.java
- hibernate-core/src/main/java/org/hibernate/loader/plan/exec/internal/LoadQueryJoinAndFetchProcessor.java
- hibernate-core/src/test/java/org/hibernate/test/batchfetch/BatchFetchReferencedColumnNameTest.java
https://hibernate.atlassian.net/browse/HHH-13059
> HHH-13059 (5.3) OneToMany with referencedColumnName returns too many entities

- hibernate-core/src/main/java/org/hibernate/hql/internal/QueryTranslatorFactoryInitiator.java
* https://hibernate.atlassian.net/browse/HHH-13238
The value of the change, considering it causes issues, is not obvious, let's go back to the common pattern.
> HHH-13238 Reuse a static logger in QueryTranslatorFactoryInitiator

- gradle/libraries.gradle
* https://hibernate.atlassian.net/browse/HHH-13254
> HHH-13254 Upgrade Agroal to 1.4

- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/DotNode.java
- hibernate-core/src/main/java/org/hibernate/loader/plan/exec/internal/LoadQueryJoinAndFetchProcessor.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/mapping/NestedEmbeddableTest.java
https://hibernate.atlassian.net/browse/HHH-13269
> HHH-13269 - Embeddable collection regression due to HHH-11544

- gradle/libraries.gradle
- hibernate-core/src/test/java/AnnotationMappedNoPackageEntity.java
- hibernate-core/src/test/java/NoPackageTest.java
https://hibernate.atlassian.net//browse/HHH-13283
> HHH-13283: Backport HHH-13112 to branch 5.3 - Proxies on entity types in the default package lead to MappingException with JDK9+

- hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java
- hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java
- hibernate-core/src/main/java/org/hibernate/query/internal/AbstractProducedQuery.java
- hibernate-core/src/test/java/org/hibernate/test/flush/NonTransactionalDataAccessTest.java
https://hibernate.atlassian.net/browse/HHH-13262
> HHH-13262 - javax.persistence.TransactionRequiredException: Executing an update/delete query

- hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/HibernateMethodLookupDispatcher.java
And less dependent of the JVM.
* https://hibernate.atlassian.net/browse/HHH-13277
> HHH-13277 Make HibernateMethodLookupDispatcher less fragile

- hibernate-core/src/main/java/org/hibernate/jpa/event/spi/jpa/ExtendedBeanManager.java
- hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/CdiBeanContainerBuilder.java
- hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/CdiBeanContainerExtendedAccessImpl.java
- hibernate-core/src/test/java/org/hibernate/test/cdi/events/extended/InvalidExtendedCdiSupportTest.java
- hibernate-core/src/test/java/org/hibernate/test/cdi/events/extended/ValidExtendedCdiSupportTest.java
- hibernate-core/src/test/java/org/hibernate/test/cdi/general/mixed/ExtendedMixedAccessTest.java
- hibernate-core/src/test/java/org/hibernate/test/cdi/general/mixed/Helper.java
- hibernate-core/src/test/java/org/hibernate/test/cdi/general/nonregistrymanaged/extended/NonRegistryManagedExtendedCdiSupportTest.java
- hibernate-core/src/test/java/org/hibernate/test/cdi/testsupport/TestingExtendedBeanManager.java
- hibernate-core/src/test/java/org/hibernate/test/cdi/testsupport/TestingExtendedBeanManagerImpl.java
- hibernate-core/src/test/java/org/hibernate/test/cdi/testsupport/TestingLegacyExtendedBeanManagerImpl.java
https://hibernate.atlassian.net//browse/HHH-13309
> HHH-13309 Extended bean managers implementing the new interface are not correctly detected

- hibernate-core/src/main/java/org/hibernate/action/internal/AbstractEntityInsertAction.java
- hibernate-core/src/main/java/org/hibernate/engine/internal/ForeignKeys.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDeleteEventListener.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/BidirectionalLazyTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/group/BidirectionalLazyGroupsInEmbeddableTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/group/BidirectionalLazyGroupsTest.java
https://hibernate.atlassian.net/browse/HHH-13241
> HHH-13241 Constraint violation when deleting entites in bi-directional, lazy OneToMany association with bytecode enhancement

- hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
- hibernate-core/src/test/java/org/hibernate/test/collection/nonInsertable/NonInsertableColumnTest.java
https://hibernate.atlassian.net/browse/HHH-13236
> HHH-13236 Honour @Column/insertable on element collections

- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/graphs/FetchWithRootGraphTest.java
@pro100leo so here is the final PR with your commit and a test case.
I had to tweak your test case a bit and I don't think we support entity graphs in multiload yet so I had to drop this part.
>  HHH-13312 Fix an invalid condition in new entity graph code

- hibernate-core/src/main/java/org/hibernate/resource/beans/spi/ManagedBeanRegistryInitiator.java
Rename method `resoveBeanContainer` to `resolveBeanContainer`
> HHH-13330: Fix a minor typo in ManagedBeanRegistryInitiator

- hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java
If the security manager is defined later, the checks won't be installed.
The security manager should be defined when starting the JVM.
> HHH-13324 Install the security manager check layer once and for all

- hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/test/java/org/hibernate/test/exceptionhandling/BaseJpaOrNativeBootstrapFunctionalTestCase.java
- hibernate-core/src/test/java/org/hibernate/test/interceptor/InterceptorNonNullTransactionTest.java
- hibernate-core/src/test/java/org/hibernate/test/tm/InterceptorTransactionTest.java
https://hibernate.atlassian.net/browse/HHH-13326
> HHH-13326 : Transaction passed to Hibernate Interceptor methods is null when JTA is used

- hibernate-core/src/main/java/org/hibernate/engine/internal/ForeignKeys.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/BidirectionalLazyTest.java
https://hibernate.atlassian.net/browse/HHH-13241
> HHH-13241 : Fix regression with an uninitialized null many-to-one association

- gradle/libraries.gradle
- hibernate-core/src/main/java/org/hibernate/mapping/Table.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/AbstractSchemaMigrator.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/AbstractAlterTableQuoteSchemaTest.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/AlterTableQuoteDefaultSchemaTest.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/AlterTableQuoteSpecifiedSchemaTest.java
https://hibernate.atlassian.net/browse/HHH-12939
> HHH-12939 (5.3)

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
- hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/HibernateMethodLookupDispatcher.java
- hibernate-core/src/test/java/org/hibernate/bytecode/internal/bytebuddy/EnhanceByteCodeNotInProvidedClassLoaderTest.java
https://hibernate.atlassian.net/browse/HHH-13343
https://hibernate.atlassian.net/browse/HHH-13277
> HHH-13343 HHH-13277 (5.3)

- hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/test/java/org/hibernate/test/exceptionhandling/BaseJpaOrNativeBootstrapFunctionalTestCase.java
- hibernate-core/src/test/java/org/hibernate/test/interceptor/InterceptorNonNullTransactionTest.java
- hibernate-core/src/test/java/org/hibernate/test/tm/InterceptorTransactionTest.java
https://hibernate.atlassian.net/browse/HHH-13326
> HHH-13326 (5.3)

- gradle/libraries.gradle
https://hibernate.atlassian.net/browse/HHH-13376
> HHH-13376 : Upgrade Javassist to 3.23.2-GA (5.3)

- documentation/documentation.gradle
- gradle/published-java-module.gradle
- hibernate-osgi/hibernate-osgi.gradle
I'll merge once CI is green to hopefully fix the JDK 11 build issues before the release.
> Fix building with JDK 11.0.3+

- hibernate-orm-modules/hibernate-orm-modules.gradle
- https://hibernate.atlassian.net/browse/HHH-13429
> HHH-13429 Upgrade WildFly provisioning plugin to version 0.0.11

- hibernate-core/src/main/java/org/hibernate/type/CollectionType.java
https://hibernate.atlassian.net/browse/HHH-13442
Changes to the `CollectionType#getCollection() `
- The `CollectionKey` is now created only once
- Moved the `LOG.tracef( "Created collection wrapper: ...)` inside the block where the collection wrapper is created
> HHH-13442 - CollectionType#getCollection() method improvements

- hibernate-core/src/main/java/org/hibernate/engine/loading/internal/CollectionLoadContext.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/CollectionKey.java
- hibernate-core/src/main/java/org/hibernate/type/CollectionType.java
https://hibernate.atlassian.net/browse/HHH-13444
> HHH-13444 Remove ignored EntityMode field from CollectionKey

- hibernate-core/src/main/java/org/hibernate/engine/internal/TwoPhaseLoad.java
- hibernate-core/src/main/java/org/hibernate/engine/loading/internal/CollectionLoadContext.java
- hibernate-core/src/main/java/org/hibernate/engine/loading/internal/LoadContexts.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/CascadingActions.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/CollectionKey.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultPersistEventListener.java
- hibernate-core/src/main/java/org/hibernate/loader/AbstractEntityJoinWalker.java
- hibernate-core/src/main/java/org/hibernate/persister/walking/internal/FetchStrategyHelper.java
- hibernate-core/src/main/java/org/hibernate/type/CollectionType.java
- https://hibernate.atlassian.net/browse/HHH-13442
- https://hibernate.atlassian.net/browse/HHH-13444
- https://hibernate.atlassian.net/browse/HHH-13450
- https://hibernate.atlassian.net/browse/HHH-13451
- https://hibernate.atlassian.net/browse/HHH-13452
- https://hibernate.atlassian.net/browse/HHH-13453
> Backport candidates

- hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsImpl.java
https://hibernate.atlassian.net/browse/HHH-13505
> HHH-13505 : NullPointerException thrown by StatisticsImpl#getCacheRegionStatistics

- documentation/src/main/asciidoc/userguide/chapters/envers/Envers.adoc
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/EnversSettings.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/GlobalConfiguration.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/EntitiesAtRevisionQuery.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/auditReader/FindByRevisionExactMatchOptionTest.java
https://hibernate.atlassian.net/browse/HHH-13500
> HHH-13500 Fix audit strategy sub-query return incorrect results

- hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/secondarytable/AbstractNonOptionalSecondaryTableTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/secondarytable/JoinedTableNullNonOptionalSecondaryTableTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/secondarytable/SingleTableNullNonOptionalSecondaryTableTest.java
https://hibernate.atlassian.net/browse/HHH-13424
> HHH-13424 (5.3)

- gradle/libraries.gradle
https://hibernate.atlassian.net/browse/HHH-13504
> HHH-13504 : Upgrade ByteBuddy to 1.9.11

- hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentBag.java
- hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentIdentifierBag.java
- hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentCollection.java
- hibernate-core/src/main/java/org/hibernate/type/CollectionType.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/callbacks/PreUpdateNewBidirectionalBagTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/callbacks/PreUpdateNewUnidirectionalBagTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/callbacks/PreUpdateNewUnidirectionalIdBagTest.java
https://hibernate.atlassian.net/browse/HHH-13466
Supersedes: https://github.com/hibernate/hibernate-orm/pull/2956
> HHH-13466 2

- hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentBag.java
https://hibernate.atlassian.net/browse/HHH-11032
> HHH-11032 (5.3)

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/AbstractBatchImpl.java
- hibernate-core/src/main/java/org/hibernate/loader/plan/exec/internal/AbstractLoadPlanBasedLoader.java
- hibernate-core/src/main/java/org/hibernate/resource/jdbc/internal/ResourceRegistryStandardImpl.java
- https://hibernate.atlassian.net/browse/HHH-13526
- https://hibernate.atlassian.net/browse/HHH-13528
> two optimisations for Statements handling

- hibernate-core/src/main/java/org/hibernate/engine/spi/SessionFactoryImplementor.java
- hibernate-core/src/main/java/org/hibernate/loader/DefaultEntityAliases.java
- https://hibernate.atlassian.net/browse/HHH-13529
> HHH-13529 Performance regression in org.hibernate.engine.spi.SessionFactoryImplementor#getDialect

- hibernate-core/src/main/java/org/hibernate/engine/loading/internal/CollectionLoadContext.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultInitializeCollectionEventListener.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
- hibernate-core/src/main/java/org/hibernate/query/internal/AbstractProducedQuery.java
https://hibernate.atlassian.net/browse/HHH-13521
> HHH-13521 Avoid excessive validation of enabled filters

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/AbstractBatchImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcCoordinatorImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/StatementPreparerImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/SqlStatementLogger.java
- hibernate-core/src/main/java/org/hibernate/engine/loading/internal/CollectionLoadContext.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/LoadQueryInfluencers.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SessionFactoryImplementor.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultInitializeCollectionEventListener.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/loader/DefaultEntityAliases.java
- hibernate-core/src/main/java/org/hibernate/loader/plan/exec/internal/AbstractLoadPlanBasedLoader.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
- hibernate-core/src/main/java/org/hibernate/query/internal/AbstractProducedQuery.java
- hibernate-core/src/main/java/org/hibernate/resource/jdbc/internal/ResourceRegistryStandardImpl.java
@gbadner @dreab8 @stuartwdouglas FYI these are the commits I'd suggest we backport from master.
Might look large and scary, but if you check individual commits out you'll see they are trivial, so should be a no brainer.
List of JIRAs:
- https://hibernate.atlassian.net/browse/HHH-13520
- https://hibernate.atlassian.net/browse/HHH-13521
- https://hibernate.atlassian.net/browse/HHH-13522
- https://hibernate.atlassian.net/browse/HHH-13523
- https://hibernate.atlassian.net/browse/HHH-13524
- https://hibernate.atlassian.net/browse/HHH-13526
- https://hibernate.atlassian.net/browse/HHH-13528
- https://hibernate.atlassian.net/browse/HHH-13529
> Performance work: candidates for backporting to 5.3

- hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentBag.java
- hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentIdentifierBag.java
- hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentCollection.java
- hibernate-core/src/main/java/org/hibernate/type/CollectionType.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/callbacks/PreUpdateNewBidirectionalBagTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/callbacks/PreUpdateNewUnidirectionalBagTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/callbacks/PreUpdateNewUnidirectionalIdBagTest.java
https://hibernate.atlassian.net/browse/HHH-13466
> HHH-13466 (5.3)

- hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsImpl.java
https://hibernate.atlassian.net/browse/HHH-13505
This fix needs to happen in 5.3.11.
> HHH-13505 (5.3)

- hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java
- hibernate-core/src/test/java/org/hibernate/engine/spi/delegation/SessionDelegatorBaseImplTest.java
https://hibernate.atlassian.net/browse/HHH-13514
https://hibernate.atlassian.net/browse/HHH-13525
> HHH-13514 HHH-13525 (5.3)

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java
- hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsImpl.java
- hibernate-core/src/main/java/org/hibernate/stat/internal/StatsNamedContainer.java
backported version of https://github.com/hibernate/hibernate-orm/pull/2975
> 5.3 - HHH-13527 Remove contention from StatisticsImpl

- documentation/src/main/asciidoc/userguide/chapters/caching/Caching.adoc
https://hibernate.atlassian.net/browse/HHH-13026
> HHH-13026 (5.3)

- hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/FromElementType.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/classic/QueryTranslatorImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/util/StringHelper.java
- hibernate-core/src/main/java/org/hibernate/loader/plan/exec/internal/AbstractLoadPlanBasedLoader.java
- hibernate-core/src/main/java/org/hibernate/loader/plan/exec/internal/AliasResolutionContextImpl.java
- hibernate-core/src/main/java/org/hibernate/mapping/Column.java
- hibernate-core/src/main/java/org/hibernate/mapping/Formula.java
- hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/LobTypeMappings.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/NationalizedTypeMappings.java
- hibernate-core/src/test/java/org/hibernate/test/util/StringHelperTest.java
- https://hibernate.atlassian.net/browse/HHH-13494
- https://hibernate.atlassian.net/browse/HHH-13495
- https://hibernate.atlassian.net/browse/HHH-13527
- https://hibernate.atlassian.net/browse/HHH-13531
- https://hibernate.atlassian.net/browse/HHH-13534
- https://hibernate.atlassian.net/browse/HHH-13544
- https://hibernate.atlassian.net/browse/HHH-13512
> Performance related backports

- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/StatelessQueryScrollingTest.java
- hibernate-core/src/test/java/org/hibernate/test/stateless/fetching/StatelessSessionFetchingTest.java
https://hibernate.atlassian.net/browse/HHH-13556
> HHH-13556 Tests doing dynamic fetch scrolling a collection fail on DB2

- hibernate-core/src/main/java/org/hibernate/dialect/SybaseASE15Dialect.java
https://hibernate.atlassian.net/browse/HHH-13574
> HHH-13574 SybaseASE does not support PARTITION BY

- hibernate-core/src/main/java/org/hibernate/dialect/MySQL57Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQL8Dialect.java
https://hibernate.atlassian.net/browse/HHH-13588 
weight_string, to_base64, from_base64, regexp_replace, regexp_instr, regexp_substr
> HHH-13588 Add missed functions to MySQL Dialect

- hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java
- hibernate-core/src/main/java/org/hibernate/engine/internal/ForeignKeys.java
- hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/PersistenceContext.java
- hibernate-core/src/main/java/org/hibernate/event/internal/AbstractFlushingEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultAutoFlushEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultDeleteEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/EvictVisitor.java
- hibernate-core/src/main/java/org/hibernate/internal/util/collections/IdentityMap.java
- hibernate-core/src/main/java/org/hibernate/stat/internal/SessionStatisticsImpl.java
- hibernate-core/src/test/java/org/hibernate/test/collection/multisession/MultipleSessionCollectionWarningTest.java
- hibernate-core/src/test/java/org/hibernate/test/flush/TestAutoFlushBeforeQueryExecution.java
- https://hibernate.atlassian.net/browse/HHH-13587
This saves quite a bit of memory when using a Session for very simple use cases.
> HHH-13587 Initialize selected collections of StatefulPersistenceContext lazily

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultAutoFlushEventListener.java
- hibernate-core/src/test/java/org/hibernate/test/events/AutoFlushEventListenerTest.java
https://hibernate.atlassian.net/browse/HHH-13592
> HHH-13592 AutoFlushEvent#isFlushRequired is always false

- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/id/EmbeddedIdMapper.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/ids/embeddedid/EmbeddedIdGenericsTest.java
https://hibernate.atlassian.net/browse/HHH-13564
> HHH-13564 - Fix NullPointerException for audited entity with embedded-id in superclass that makes use of generics.

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/NaturalIdInUninitializedAssociationTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/NaturalIdInUninitializedProxyTest.java
- hibernate-core/src/test/java/org/hibernate/test/naturalid/lazy/NaturalIdInUninitializedAssociationTest.java
- hibernate-core/src/test/java/org/hibernate/test/naturalid/lazy/NaturalIdInUninitializedProxyTest.java
Fix on top of https://github.com/hibernate/hibernate-orm/pull/3014
> HHH-13607 - Exception thrown while flushing uninitialized enhanced proxy with immutable natural ID

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/EnhancementHelper.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/LazyAttributesMetadata.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/tuple/PropertyFactory.java
- hibernate-core/src/main/java/org/hibernate/tuple/entity/BytecodeEnhancementMetadataPojoImpl.java
- hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java
- hibernate-core/src/test/java/org/hibernate/test/legacy/CustomPersister.java
https://hibernate.atlassian.net/browse/HHH-13611
> HHH-13661 Restore EntityMetamodel constructor to take SessionFactoryImplementor argument instead of PersisterCreationContext

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/EnhancementHelper.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/LazyAttributesMetadata.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/tuple/PropertyFactory.java
- hibernate-core/src/main/java/org/hibernate/tuple/entity/BytecodeEnhancementMetadataPojoImpl.java
- hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java
- hibernate-core/src/test/java/org/hibernate/test/legacy/CustomPersister.java
https://hibernate.atlassian.net/browse/HHH-13611
PR for 5.3 branch
> HHH-13611 Restore EntityMetamodel constructor to take SessionFactoryImplementor argument instead of PersisterCreationContext.

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/NaturalIdInUninitializedAssociationTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/NaturalIdInUninitializedProxyTest.java
- hibernate-core/src/test/java/org/hibernate/test/naturalid/lazy/NaturalIdInUninitializedAssociationTest.java
- hibernate-core/src/test/java/org/hibernate/test/naturalid/lazy/NaturalIdInUninitializedProxyTest.java
https://hibernate.atlassian.net/browse/HHH-13607
> HHH-13607 (5.3) Exception thrown while flushing uninitialized enhanced proxy with immutable natural ID

- databases/mariadb/matrix.gradle
- hibernate-core/src/test/java/org/hibernate/test/type/LocalTimeTest.java
- hibernate-core/src/test/java/org/hibernate/test/type/OffsetTimeTest.java
https://hibernate.atlassian.net/browse/HHH-13605
https://hibernate.atlassian.net/browse/HHH-13581
> HHH-13581 HHH-13605 (5.3)

- hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/H2DialectDataBaseToUpperTest.java
https://hibernate.atlassian.net/browse/HHH-13597
> HHH-13597 Building DatabaseInformation fails on H2 without DATABASE_TO_UPPER

- documentation/src/main/asciidoc/userguide/chapters/envers/Envers.adoc
- hibernate-envers/src/main/java/org/hibernate/envers/boot/internal/ImprovedModifiedColumnNamingStrategy.java
- hibernate-envers/src/main/java/org/hibernate/envers/boot/internal/LegacyModifiedColumnNamingStrategy.java
- hibernate-envers/src/main/java/org/hibernate/envers/boot/internal/ModifiedColumnNamingStrategyRegistrationProvider.java
- hibernate-envers/src/main/java/org/hibernate/envers/boot/spi/ModifiedColumnNamingStrategy.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/EnversSettings.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/GlobalConfiguration.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/AuditMetadataGenerator.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/MetadataTools.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/AuditedPropertiesReader.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/ComponentAuditedPropertiesReader.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/PropertyAuditingData.java
- hibernate-envers/src/main/resources/META-INF/services/org.hibernate.boot.registry.selector.StrategyRegistrationProvider
- hibernate-envers/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/modifiedflags/naming/ImprovedColumnNamingStrategyTest.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/modifiedflags/naming/LegacyColumnNamingStrategyTest.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/modifiedflags/naming/OtherEntity.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/modifiedflags/naming/OtherEntityId.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/modifiedflags/naming/SingleIdEntity.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/modifiedflags/naming/TestEmbeddable.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/modifiedflags/naming/TestEntity.java
https://hibernate.atlassian.net/browse/HHH-10398
> HHH-10398 Allow MOD column naming by strategy

- hibernate-core/src/main/java/org/hibernate/cache/internal/EnabledCaching.java
- hibernate-core/src/main/java/org/hibernate/cache/spi/CacheImplementor.java
- hibernate-core/src/test/java/org/hibernate/test/cache/SharedDomainDataAndQueryResultsTest.java
https://hibernate.atlassian.net/browse/HHH-13586
> HHH-13586 (5.3)

- hibernate-core/src/main/java/org/hibernate/loader/Loader.java
- hibernate-core/src/test/java/org/hibernate/test/cfg/cache/DirectReferenceCacheEntriesTest.java
https://hibernate.atlassian.net/browse/HHH-13665
> HHH-13665 selecting an Entity annotated with @Immutalbe but not with @Cachable causes a NPE when use_reference_entries is enabled

- hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/QueryScrollinWithInheritanceTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/QueryScrollingWithInheritanceTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/LazyToOnesNoProxyFactoryWithSubclassesStatelessTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/LazyToOnesProxyWithSubclassesStatelessTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/QueryScrollingWithInheritanceProxyTest.java
- hibernate-core/src/test/java/org/hibernate/test/hqlfetchscroll/QueryScrollingWithInheritanceTest.java
https://hibernate.atlassian.net/browse/HHH-13633
> HHH-13633 : Bugs join-fetching a collection when scrolling with a stateless session using enhancement as proxy

- hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/QueryScrollingWithInheritanceEagerManyToOneTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/QueryScrollingWithInheritanceProxyEagerManyToOneTest.java
https://hibernate.atlassian.net/browse/HHH-13634
> HHH-13634 : PersistenceContext can get cleared before load completes using StatelessSessionImpl

- hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentBag.java
https://hibernate.atlassian.net/browse/HHH-13675
> HHH-13675 : Optimize PersistentBag.groupByEqualityHash()

- gradle/libraries.gradle
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/BiDirectionalAssociationHandler.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
* [HHH-13680](https://hibernate.atlassian.net/browse/HHH-13680): Upgrade to Byte Buddy 1.10.2
* [HHH-13681](https://hibernate.atlassian.net/browse/HHH-13681): Upgrade to Byteman 4.0.8
Not tested locally, let's wait for CI results...
Please note that, because of [HHH-13682](https://hibernate.atlassian.net/browse/HHH-13682), we don't actually test JDK13/14 bytecode right now. I'll send another PR to address that.
> HHH-13680 + HHH-13681 Upgrade to Byte Buddy 1.10.2 and Byteman 4.0.8

- hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
- hibernate-core/src/test/java/org/hibernate/test/stateless/StatelessSessionPersistentContextTest.java
- hibernate-core/src/test/java/org/hibernate/test/stateless/StatelessSessionTest.java
https://hibernate.atlassian.net/browse/HHH-13672
> HHH-13672 The temporary PersistenceContext of a StatelessSession is not cleared after a refresh operation 

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/AbstractBatchImpl.java
- hibernate-core/src/test/java/org/hibernate/test/connections/JdbcBatchingAgressiveReleaseTest.java
https://hibernate.atlassian.net/browse/HHH-13307
> HHH-13307 : On release of batch it still contained JDBC statements using JTA

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/EnhancementAsProxyLazinessInterceptor.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/spi/LoadEvent.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
- hibernate-core/src/main/java/org/hibernate/type/EntityType.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/QueryScrollinWithInheritanceTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/QueryScrollingWithInheritanceEagerManyToOneTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/QueryScrollingWithInheritanceTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/LazyToOnesNoProxyFactoryWithSubclassesStatefulTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/LazyToOnesNoProxyFactoryWithSubclassesStatelessTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/LazyToOnesProxyMergeWithSubclassesTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/LazyToOnesProxyWithSubclassesStatelessTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/LazyToOnesProxyWithSubclassesTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/ProxyInitializeAndUpdateInlineDirtyTrackingDynamicUpdateTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/ProxyInitializeAndUpdateInlineDirtyTrackingTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/ProxyInitializeAndUpdateTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/QueryScrollingWithInheritanceProxyEagerManyToOneTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/QueryScrollingWithInheritanceProxyTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/SimpleUpdateTestWithLazyLoading.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/SimpleUpdateTestWithLazyLoadingAndInlineDirtyTracking.java
- hibernate-core/src/test/java/org/hibernate/test/hqlfetchscroll/QueryScrollingWithInheritanceTest.java
https://hibernate.atlassian.net/browse/HHH-13640
https://hibernate.atlassian.net/browse/HHH-13653
https://hibernate.atlassian.net/browse/HHH-13633
https://hibernate.atlassian.net/browse/HHH-13633
> HHH-13640 HHH-13653 HHH-13633 HHH-13634 (5.3)

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/AbstractBatchImpl.java
- hibernate-core/src/test/java/org/hibernate/test/connections/JdbcBatchingAgressiveReleaseTest.java
https://hibernate.atlassian.net/browse/HHH-13307 (5.3)
> HHH-13307 (5.3)

- gradle/libraries.gradle
HHH-10541 updating vibur-dbcp dependency to 25.0
> updating vibur-dbcp dependency to 25.0

- gradle/libraries.gradle
- hibernate-core/hibernate-core.gradle
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/DirtyCheckingWithEmbeddedOnGetterTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhance/internal/bytebuddy/DirtyCheckingWithEmbeddedTest.java
https://hibernate.atlassian.net/browse/HHH-13764
> HHH-13764 During enhancement, annotations on the getter are ignored

- documentation/src/main/asciidoc/userguide/chapters/pc/extras/gradle-example.gradle
[HHH-13755](https://hibernate.atlassian.net/browse/HHH-13755)
A small update to the example in the documentation to make it clearer what you need and which options you can set when using the plugin
> HHH-13755 Update Hibernate Gradle plugin in the documentation

- hibernate-core/src/main/java/org/hibernate/event/service/internal/EventListenerGroupImpl.java
- hibernate-core/src/test/java/org/hibernate/event/service/internal/EventListenerDuplicationStrategyTest.java
- hibernate-core/src/test/java/org/hibernate/event/service/internal/EventListenerReplacementStrategyTest.java
Follows: https://github.com/hibernate/hibernate-orm/pull/3192
https://hibernate.atlassian.net/browse/HHH-13831
I've added some tests, fixed the existing ones and fix added the misisng placeholder in the log message.
> HHH-13831 Fix EventListenerGroup implementation + Tests for replacement strategies

- hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/PersistenceXmlParser.java
hi @sebersole , would you be ok with these changes? Opening up visibility a little bit.
https://hibernate.atlassian.net/browse/HHH-13838
> HHH-13838 Allow extension of PersistenceXmlParser

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
> Fix typos in AbstractEntityPersister's generateSQLDeletStrings() method

- hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/BaseEntityManagerFunctionalTestCase.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/integrationprovider/IntegrationProviderSettingByClassUsingPropertiesTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/schemagen/JpaSchemaGeneratorTest.java
https://hibernate.atlassian.net/browse/HHH-13853
> HHH-13853 - Pass the merged Integration settings and Persistence Unit properties to buildBootstrapServiceRegistry

- hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/mapping/collections/MapOperationTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/mapping/collections/PluralAttributeMappingTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/SelectClauseTests.java
- hibernate-testing/src/main/java/org/hibernate/testing/orm/domain/gambit/EntityOfMaps.java
https://hibernate.atlassian.net/browse/HHH-13720
https://trello.com/c/OiKMCChU/14-verify-complete-sorted-map-support
Adding some tests, it seems that everything already works.
> HHH-13720 Test sorted-map support

- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/StrictJpaComplianceViolation.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/JpaComplianceDisallowFQNTests.java
> Wip/6.0 Disallow FQN entity name in JPA compliance mode

- tooling/hibernate-gradle-plugin/src/main/groovy/org/hibernate/orm/tooling/gradle/HibernatePlugin.java
See https://hibernate.atlassian.net/browse/HHH-13870
> HHH-13870 - Extract task action in Gradle plugin to fix up-to-date check

- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/connections/internal/DriverManagerConnectionProviderImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/dialect/internal/DialectFactoryImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
- hibernate-core/src/main/java/org/hibernate/internal/log/ConnectionPoolingLogger.java
- Move logging out of `Dialect` and into `DialectFactoryImpl`
- Move some connection-pool-related logging onto `ConnectionPoolingLogger`
> Minor changes to logging

- documentation/src/main/asciidoc/userguide/chapters/query/hql/HQL.adoc
- documentation/src/test/java/org/hibernate/userguide/hql/HQLTest.java
- hibernate-core/src/main/java/org/hibernate/internal/util/ReflectHelper.java
- hibernate-core/src/main/java/org/hibernate/query/internal/AbstractProducedQuery.java
- hibernate-core/src/main/java/org/hibernate/query/spi/DoubleStreamDecorator.java
- hibernate-core/src/main/java/org/hibernate/query/spi/IntStreamDecorator.java
- hibernate-core/src/main/java/org/hibernate/query/spi/LongStreamDecorator.java
- hibernate-core/src/main/java/org/hibernate/query/spi/StreamDecorator.java
- hibernate-core/src/test/java/org/hibernate/test/stream/basic/BasicStreamTest.java
- hibernate-core/src/test/java/org/hibernate/test/stream/basic/JpaStreamTest.java
https://hibernate.atlassian.net/browse/HHH-13872
> HHH-13872 - Make the Java Stream close the underlying ScrollableResultsIterator upon calling a terminal operation

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/ResultSetReturnImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/SqlStatementLogger.java
https://hibernate.atlassian.net/browse/HHH-13879
> HHH-13879 - Slow query log should use System#nanoTime not System#currentTimeMillis

- hibernate-core/src/main/java/org/hibernate/dialect/pagination/AbstractLimitHandler.java
An obvious bug introduced recently.
> Wip/6.0 Fix an obvious bug in AbstractLimitHandler

- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/loader/Loader.java
If possible, I woud like to relax some of the scopes of some methods so that I can reuse them or override them in Hibernate ORM. Let me know if I need to create a JIRA for this.
Thanks
> Changes for Rx

- hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/mapping/quote/ColumnQuoteTest.java
https://trello.com/c/3o4BJuo8/102-verify-support-for-quoted-columns
> Wip/6.0 Verify 'column quoting'

- hibernate-core/src/main/java/org/hibernate/annotations/CascadeType.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderDynamicBatch.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdLoadPlan.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/spi/SingleIdEntityLoader.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/internal/JdbcSelectExecutorStandardImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/spi/ExecutionContext.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cascade/RefreshTest.java
Part of https://trello.com/c/OVdBw7qD/27-verify-cascading
Other types of cascade testing has been taken over by Andrea.
Fix a generic issue when loading entity by id providing existing entity (like in cascade refresh case).
> Wip/6.0 Port 'refresh' cascade testing case

- hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
- hibernate-core/src/main/java/org/hibernate/proxy/pojo/ProxyFactoryHelper.java
- hibernate-core/src/main/java/org/hibernate/tuple/entity/PojoEntityTuplizer.java
- hibernate-core/src/test/java/org/hibernate/test/proxy/FinalGetterSetterTest.java
https://hibernate.atlassian.net/browse/HHH-13891
> HHH-13891 : ProxyFactory should not be built if any ID or property getter/setter methods are final

- hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
- hibernate-core/src/main/java/org/hibernate/proxy/pojo/ProxyFactoryHelper.java
- hibernate-core/src/main/java/org/hibernate/tuple/entity/PojoEntityTuplizer.java
- hibernate-core/src/test/java/org/hibernate/test/proxy/FinalGetterSetterTest.java
https://hibernate.atlassian.net/browse/HHH-13851
https://hibernate.atlassian.net/browse/HHH-13891
> HHH-13851 HHH-13891 (5.3)

- hibernate-core/src/main/java/org/hibernate/boot/registry/selector/internal/StrategySelectorBuilder.java
- hibernate-core/src/main/java/org/hibernate/dialect/Database.java
- hibernate-core/src/test/java/org/hibernate/dialect/resolver/DialectFactoryTest.java
- hibernate-core/src/test/java/org/hibernate/engine/jdbc/dialect/internal/StandardDialectResolverTest.java
https://hibernate.atlassian.net/browse/HHH-12977
https://hibernate.atlassian.net/browse/HHH-13910
> HHH-12977 HHH-13910 (5.3)

- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/AuditMetadataGenerator.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/BasicMetadataGenerator.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/IdMetadataGenerator.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/MetadataTools.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/basic/BasicTypeColumnDefinitionTest.java
https://hibernate.atlassian.net/browse/HHH-13886
> HHH-13886 Revert behavior changes introduced by HHH-10844

- hibernate-core/hibernate-core.gradle
- hibernate-orm-modules/src/test/java/org/hibernate/wildfly/integrationtest/HibernateEnversOnWildflyTest.java
- hibernate-testing/hibernate-testing.gradle
https://hibernate.atlassian.net/browse/HHH-13937
> HHH-13937 Get rid of junit5 compile-time dependencies

- gradle/libraries.gradle
https://hibernate.atlassian.net/browse/HHH-13953
> HHH-13953 (5.4)

- hibernate-core/src/main/java/org/hibernate/dialect/hint/IndexQueryHintHandler.java
Seems an obvious coding sloppiness
> wip/6.0 Fix a regular expression sloppiness in IndexQueryHintHandler

- hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java
- hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
https://hibernate.atlassian.net/browse/HHH-13916
> HHH-13916 : Add a unique Session "token"

- hibernate-core/src/main/java/org/hibernate/action/internal/BulkOperationCleanupAction.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BasicProxyFactoryImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentImpl.java
- hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/ByteBuddyProxyHelper.java
- hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
I remember there used to be a similar PR but I failed to find it any more. I thought that is a pity for it is a safe performance improvement without any compromise.
> wip/6.0 Improve performance via Collections.addAll

- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/GenerationTargetToDatabase.java
https://hibernate.atlassian.net/browse/HHH-13695
> HHH-13695 DDL export forgets to close a Statement (5.3)

- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/query/spi/HQLQueryPlan.java
- hibernate-core/src/main/java/org/hibernate/engine/query/spi/QueryPlanCache.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/QueryTranslatorImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/loader/Loader.java
- hibernate-core/src/main/java/org/hibernate/loader/hql/QueryLoader.java
I haven't created the JIRAs yet, but could you let me know if these changes are viable first? Thanks
> Required for Hibernate Reactive for queries support

- gradle.properties
https://hibernate.atlassian.net/browse/HHH-14030
Split from #3405 as requested by @Sanne: https://github.com/hibernate/hibernate-orm/pull/3405#issuecomment-630444658
> HHH-14030 Gradle: user.language=en to avoid errors on German Win10

- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/CriteriaQueryImpl.java
needed to support Criteria queries
> expose a private field to Hibernate Reactive

- hibernate-core/src/main/java/org/hibernate/loader/plan/build/internal/AbstractEntityGraphVisitationStrategy.java
https://hibernate.atlassian.net/browse/HHH-13980
> HHH-13980 NullPointerException in AbstractEntityGraphVisitationStrategy.startingCollectionIndex

- gradle/libraries.gradle
Upgrade to Hibernate Validator 6.0.20.Final fix for HHH-14013
> FIX for HHH-14013

- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/LiteralExpression.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/literal/CriteriaLiteralWithSingleQuoteTest.java
https://hibernate.atlassian.net/browse/HHH-14077
> HHH-14077 : CVE-2019-14900 SQL injection issue using JPA Criteria API

- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java
The motivation of this PR is to remove the `todo` comment in `JpaMetamodelImpl`:
The gist of this PR is to store loaded class to avoid duplicated loading later.
> wip/6.0 Remove potential duplicated class loading in JpaMetamodelImpl

- hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/internal/JdbcLiteralFormatterCharacterData.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/literal/CriteriaLiteralWithSingleQuoteTest.java
https://hibernate.atlassian.net/browse/HHH-14077
> HHH-14077  CVE-2019-14900 SQL injection issue using JPA Criteria API

- hibernate-core/src/main/java/org/hibernate/hql/spi/id/inline/AbstractInlineIdsDeleteHandlerImpl.java
- hibernate-core/src/main/java/org/hibernate/hql/spi/id/inline/AbstractInlineIdsUpdateHandlerImpl.java
- hibernate-core/src/test/java/org/hibernate/test/inheritance/InheritanceDeleteBatchTest.java
https://hibernate.atlassian.net/browse/HHH-13214
this is an alternative solution of https://github.com/hibernate/hibernate-orm/pull/3348
> HHH 13214 DML batch delete re-firing SQL from previous calls

- hibernate-core/src/main/java/org/hibernate/loader/Loader.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/batch/AbstractBatchingTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/batch/DynamicBatchingTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/batch/PaddedBatchingTest.java
https://hibernate.atlassian.net/browse/HHH-14108
> HHH-14108 - PADDED and DYNAMIC Batch loading strategies not compatible with the Enhanced Proxy feature

- hibernate-core/src/main/java/org/hibernate/loader/entity/plan/AbstractLoadPlanBasedEntityLoader.java
- hibernate-core/src/main/java/org/hibernate/loader/plan/exec/process/internal/AbstractRowReader.java
- hibernate-core/src/main/java/org/hibernate/loader/plan/exec/process/internal/EntityReferenceInitializerImpl.java
- hibernate-core/src/test/java/org/hibernate/test/batchfetch/BatchFetchRefreshTest.java
https://hibernate.atlassian.net/browse/HHH-12268
> HHH-12268 : LazyInitializationException thrown from lazy collection when batch fetching enabled

- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/util/JoinProcessor.java
- hibernate-core/src/test/java/org/hibernate/query/hhh14112/HHH14112Test.java
https://hibernate.atlassian.net/browse/HHH-14112
This is the new PR after @beikov authorized my creating a new PR after his (https://github.com/hibernate/hibernate-orm/pull/3479). Testing cases are added cloned from the bug reporter's repo.
Thanks for @beikov 's bug fixing!
> HHH-14112 Invalid count SQL for JOINED inheritance and WHERE clause

- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/SelectClause.java
- hibernate-core/src/test/java/org/hibernate/query/hhh14116/HHH14116Test.java
https://hibernate.atlassian.net/browse/HHH-14116
Thanks for @beikov 's code change.
I only included the broken testing case in the PR from the ticket attachment for the other testing cases seem pretty normal and are working even without the code changes in this PR.
> HHH-14116 Exception when fetch joining a non-collection when selecting non-root

- hibernate-core/src/main/java/org/hibernate/loader/entity/plan/AbstractLoadPlanBasedEntityLoader.java
- hibernate-core/src/main/java/org/hibernate/loader/plan/exec/process/internal/EntityReferenceInitializerImpl.java
- hibernate-core/src/test/java/org/hibernate/test/batchfetch/BatchFetchRefreshTest.java
https://hibernate.atlassian.net/browse/HHH-12268
> HHH-12268 (5.3)

- hibernate-core/src/test/java/org/hibernate/test/inheritance/TransientOverrideAsPersistentJoined.java
- hibernate-core/src/test/java/org/hibernate/test/inheritance/TransientOverrideAsPersistentMappedSuperclass.java
- hibernate-core/src/test/java/org/hibernate/test/inheritance/TransientOverrideAsPersistentSingleTable.java
- hibernate-core/src/test/java/org/hibernate/test/inheritance/TransientOverrideAsPersistentTablePerClass.java
https://hibernate.atlassian.net/browse/HHH-14103
> HHH-14103 (5.3)

- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/LiteralExpression.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/literal/CriteriaLiteralWithSingleQuoteTest.java
https://hibernate.atlassian.net/browse/HHH-14077
> HHH-14077 : CVE-2019-14900 SQL injection issue in Hibernate ORM (5.3)

- hibernate-core/src/main/java/org/hibernate/cfg/Ejb3Column.java
- hibernate-core/src/main/java/org/hibernate/cfg/Ejb3JoinColumn.java
- hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java
- hibernate-core/src/main/java/org/hibernate/dialect/CockroachDB192Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQL81Dialect.java
- hibernate-core/src/main/java/org/hibernate/engine/internal/JoinSequence.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/MethodNode.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/util/SyntheticAndFactory.java
- hibernate-core/src/main/java/org/hibernate/loader/OuterJoinableAssociation.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/SchemaCreatorImpl.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/CollectionMetadataGenerator.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/tools/StringTools.java
https://hibernate.atlassian.net/browse/HHH-14137
> HHH-14137 Empty String check performance improvements

- hibernate-core/src/main/java/org/hibernate/cfg/beanvalidation/TypeSafeActivator.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/manytoone/NotNullManyToOneTest.java
https://hibernate.atlassian.net/browse/HHH-14129
> HHH-14129 Bidirectional relationship with @NotNull fails to save

- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
- hibernate-core/src/main/java/org/hibernate/hql/spi/id/AbstractMultiTableBulkIdStrategyImpl.java
- hibernate-core/src/test/java/org/hibernate/test/dialect/functional/SQLServerDialectTempTableCollationTest.java
https://hibernate.atlassian.net/browse/HHH-3326
An ancient ticket to solve!
Implementation was copied from the code by the bug reporter, i.e. David Good, whose fixing was based on the stackoverflow page: https://stackoverflow.com/questions/21332105/temp-table-collation-conflict-error-cannot-resolve-the-collation-conflict-be
> HHH-3326 Fix temp table collation issue for SQLServer dialect

- hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/IdentNode.java
- hibernate-core/src/test/java/org/hibernate/query/hhh14156/HHH14156Test.java
https://hibernate.atlassian.net/browse/HHH-14156
> HHH-14156 IN subquery predicate with entity aliases issue for composite id

- hibernate-core/src/main/java/org/hibernate/cfg/beanvalidation/BeanValidationIntegrator.java
https://hibernate.atlassian.net/browse/HHH-14160
I don't know the exact process but this should also be backported to 5.4.
Thanks!
> HHH-14160 Use a runtime used class for testing Bean Validation presence

- hibernate-core/src/test/java/org/hibernate/test/fileimport/MultiLineImportExtractorTest.java
Fixes https://hibernate.atlassian.net/browse/HHH-14179
> HHH-14179 fix MultiLineImportExtractorTest on Windows

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/EnhancementAsProxyLazinessInterceptor.java
- hibernate-core/src/main/java/org/hibernate/loader/plan/exec/process/internal/EntityReferenceInitializerImpl.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/SharingReferenceTest.java
https://hibernate.atlassian.net/browse/HHH-14187
> HHH-14187 - Lazy loading fails if an entity appears twice in the object graph when enhancement as proxy is enabled

- gradle/java-module.gradle
https://hibernate.atlassian.net/browse/HHH-14199
> HHH-14199 fix gradle 'setDataBase' task failure

- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/FromElementFactory.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/SelectClause.java
- hibernate-core/src/test/java/org/hibernate/test/hql/FetchNonRootRelativeElementCollectionAndAssociationTest.java
> HHH-13201 - do not set empty text on collection join parent without queryable collection

- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/FromElementFactory.java
- hibernate-core/src/test/java/org/hibernate/query/criteria/internal/hhh14197/AbstractPersistent.java
- hibernate-core/src/test/java/org/hibernate/query/criteria/internal/hhh14197/Department.java
- hibernate-core/src/test/java/org/hibernate/query/criteria/internal/hhh14197/Employee.java
- hibernate-core/src/test/java/org/hibernate/query/criteria/internal/hhh14197/HHH14197Test.java
https://hibernate.atlassian.net/browse/HHH-14197
The root cause is we didn't test non-root correlated parent and some fix to FromElementFactory is needed to avoid setting text to emptiness aggressively.
> HHH-14197 Fix correlated subquery empty 'from' SQL issue

- hibernate-core/src/main/java/org/hibernate/cfg/DefaultComponentSafeNamingStrategy.java
- hibernate-core/src/main/java/org/hibernate/cfg/DefaultNamingStrategy.java
- hibernate-core/src/main/java/org/hibernate/cfg/EJB3NamingStrategy.java
- hibernate-core/src/main/java/org/hibernate/cfg/ImprovedNamingStrategy.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/classic/QueryTranslatorImpl.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/idclass/WidgetId.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/pack/defaultpar/Version.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/pack/defaultpar_1_0/Version1.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/pack/war/Version.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/AlternativeNamingStrategy.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/oracle/GetDimensionFunction.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/oracle/GetGeometryTypeFunction.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/oracle/OracleSDOSupport.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/oracle/OracleSpatialFunctions.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/oracle/SDOObjectMethod.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/oracle/SDOObjectProperty.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/oracle/criterion/OracleSpatialProjection.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/sqlserver/SqlServerMethod.java
avoid unnecessary synchronization
> HHH-14205 Replace StringBuffer with StringBuilder

- documentation/src/test/java/org/hibernate/userguide/naming/AcmeCorpPhysicalNamingStrategy.java
https://hibernate.atlassian.net/browse/HHH-14208
The gist of the PR is to improve the example naming strategy code in user guide. The resulting code snippet becomes much more concise and condense, serving better to convey the key idea of naming strategy usage.
The previous code snippet has 87 LOC; after the simplification, only 46 LOC remains. Also, it makes the code easier to understand without irrelevant and distracting content.
> HHH-14208 simplify example naming strategy code in user guide

- hibernate-core/src/main/java/org/hibernate/boot/model/convert/internal/AutoApplicableConverterDescriptorStandardImpl.java
- hibernate-core/src/test/java/org/hibernate/test/converter/AttributeConverterTest.java
https://hibernate.atlassian.net/browse/HHH-14206
Straightforward implementation.
> HHH-14206 Fix issue auto-apply converter not applied to primitives

- hibernate-core/src/main/java/org/hibernate/id/enhanced/TableStructure.java
- hibernate-core/src/test/java/org/hibernate/id/enhanced/HHH14219.java
if generator is shared by multiple entities
> HHH-14219 Fix duplicated rows of sequence table

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractPropertyMapping.java
- hibernate-core/src/test/java/org/hibernate/persister/entity/JoinFormulaImplicitJoinTest.java
Fix for #3564. See also my comment regarding the implementation: https://github.com/hibernate/hibernate-orm/pull/3564#discussion_r495819555
> HHH-14223 - nullpointer exception on @JoinFormula with implicit join

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/inlinedirtychecking/DirtyCheckEnhancementContext.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/inlinedirtychecking/DirtyCheckPrivateUnMappedCollectionTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/inlinedirtychecking/NoDirtyCheckEnhancementContext.java
https://hibernate.atlassian.net/browse/HHH-14220
> HHH-14220 EnhancementException failure with MappedSuperclass with a un-mapped collection

- hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/BaseInsertOrderingTest.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/BatchSortingTest.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/ElementCollectionTest.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingDuplicateTest.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingHasParentTest.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingReferenceDifferentSubclassTest.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingSelfReferenceSingleTableInheritance.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingSelfReferenceTest.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithBaseClassReferencingSubclass.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithBidirectionalManyToMany.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithBidirectionalMapsIdOneToOne.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithBidirectionalOneToMany.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithBidirectionalOneToManyFlushProblem.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithBidirectionalOneToOne.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithBidirectionalOneToOneFlushProblem.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithJoinedTableInheritance.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithJoinedTableMultiLevelInheritance.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithManyToOne.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithMultipleManyToOne.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithSecondaryTable.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithSingleTableInheritance.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithTablePerClassInheritance.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithUnidirectionalOneToOne.java
- hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithUnidirectionalOneToOneJoinColumn.java
- hibernate-core/src/test/java/org/hibernate/test/util/jdbc/PreparedStatementSpyConnectionProvider.java
Replaces #3580 , just reorganized the changest a bit. All credit to @NathanQingyangXu 
- https://hibernate.atlassian.net/browse/HHH-14227
> HHH-14227 fix some ActionQueue insert ordering regression issues

- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
- hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingMetadataBuildingOptions.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataBuildingOptions.java
- hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/cfg/OneToOneSecondPass.java
- hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java
- hibernate-core/src/main/java/org/hibernate/cfg/annotations/EntityBinder.java
- hibernate-core/src/main/java/org/hibernate/cfg/annotations/MapBinder.java
- hibernate-core/src/test/java/org/hibernate/test/foreignkeys/disabled/DefaultConstraintModeTest.java
Provide an option to skip foreign key creation for ConstraintMode.PROVIDER_DEFAULT
> HHH-14253 support ConstraintMode.PROVIDER_DEFAULT

- hibernate-core/src/main/java/org/hibernate/graph/internal/RootGraphImpl.java
- hibernate-core/src/test/java/org/hibernate/graph/EntityGraphsTest.java
https://hibernate.atlassian.net/browse/HHH-14264
Obvious bug and obvious fix.
> HHH-14264 fix bug that entity graph cannot be applied to child entity

- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/CollectionSizeNode.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/size/CriteriaSelectSizeCollectionTest.java
https://hibernate.atlassian.net/browse/HHH-14245
> HHH-14245 ClassCastException for Criteria Collection size selection

- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
- documentation/src/main/asciidoc/userguide/chapters/caching/Caching.adoc
> HHH-14275 Broken link to Infinispan User Guide in Hibernate 5.3 User Guide

- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/FromClause.java
- hibernate-core/src/test/java/org/hibernate/test/jpa/MapContent.java
- hibernate-core/src/test/java/org/hibernate/test/jpa/MapOwner.java
- hibernate-core/src/test/java/org/hibernate/test/jpa/Relationship.java
- hibernate-core/src/test/java/org/hibernate/test/jpa/ql/MapIssueTest.java
https://hibernate.atlassian.net/browse/HHH-14279
> HHH-14279 Test and fix for join ordering issue when entity key joins are involved

- hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/query/FetchDescriptor.java
- hibernate-core/src/main/java/org/hibernate/boot/query/NamedResultSetMappingDescriptor.java
- hibernate-core/src/main/java/org/hibernate/boot/query/ResultDescriptor.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingMetadata.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataImplementor.java
- hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderProvidedQueryImpl.java
- hibernate-core/src/main/java/org/hibernate/procedure/internal/Util.java
- hibernate-core/src/main/java/org/hibernate/query/internal/NamedObjectRepositoryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/named/NameableQuery.java
- hibernate-core/src/main/java/org/hibernate/query/named/NamedObjectRepository.java
- hibernate-core/src/main/java/org/hibernate/query/named/NamedQueryMemento.java
- hibernate-core/src/main/java/org/hibernate/query/spi/QueryEngine.java
- hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/intg/sqm/HqlTranslationNoFactoryTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/named/simple/SimpleNamedQueryTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/resultmapping/AbstractUsageTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/resultmapping/BasicResultTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/resultmapping/EntityResultTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/resultmapping/InstantiationResultTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/resultmapping/NamedRepoTests.java
> renamed `NamedQueryRepository` to `NamedObjectRepository`

- hibernate-core/src/main/antlr/sql-gen.g
https://hibernate.atlassian.net/browse/HHH-14214
> HHH-14214 Remove unnecessary rule for token type SQL_NODE

- hibernate-core/src/main/java/org/hibernate/boot/jaxb/internal/stax/LocalXmlResourceResolver.java
- hibernate-core/src/main/java/org/hibernate/boot/xsd/ConfigXsdSupport.java
- hibernate-core/src/main/java/org/hibernate/boot/xsd/LocalXsdResolver.java
- hibernate-core/src/main/java/org/hibernate/boot/xsd/MappingXsdSupport.java
- hibernate-core/src/main/java/org/hibernate/cfg/EJB3DTDEntityResolver.java
- hibernate-core/src/main/resources/org/hibernate/jpa/orm_3_0.xsd
- hibernate-core/src/main/resources/org/hibernate/jpa/persistence_3_0.xsd
- hibernate-core/src/test/resources/org/hibernate/test/annotations/xml/ejb3/orm5.xml
https://hibernate.atlassian.net/browse/HHH-14196
> HHH-14196 backport for 5.3

- gradle/libraries.gradle
https://hibernate.atlassian.net/browse/HHH-14158
> HHH-14158 Update Javassist to 3.27.0-GA

- hibernate-core/src/main/java/org/hibernate/loader/plan/build/internal/AbstractLoadPlanBuildingAssociationVisitationStrategy.java
- hibernate-core/src/test/java/org/hibernate/test/collection/map/EmbeddableIndexTest.java
https://hibernate.atlassian.net/browse/HHH-14257
> HHH-14257  An Entity A with a map collection having as index an Embeddable with a an association to the Entity A fails with a NPE

- .gitignore
https://hibernate.atlassian.net/browse/HHH-14324
> HHH-14324 Add .gradletasknamecache to .gitignore

- .gitignore
https://hibernate.atlassian.net/browse/HHH-14324
Backport of #3638
> Backport HHH-14324 to branch 5.4 - Add .gradletasknamecache to .gitignore

- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
https://hibernate.atlassian.net/browse/HHH-14310
> HHH-14310 Document hibernate.query.in_clause_parameter_padding and some other missing config properties

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/EnhancerImpl.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/javassist/EntityEnhancer.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/DefaultEnhancementContext.java
- hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/EntityPersister.java
- hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/dirty/DirtyTrackingTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/mutable/MapStringConverter.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/mutable/MutableTypeEnhancementTestCase.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/mutable/TestEntity.java
https://hibernate.atlassian.net/browse/HHH-14329
> HHH-14329 Test and fix for DirtinessTracker usage for enhanced entities doesn't respect mutable types

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- https://hibernate.atlassian.net/browse/HHH-14333
> HHH-14333 Pessimistic Lock causes FOR UPDATE on outer join statements

- hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java
https://hibernate.atlassian.net/browse/HHH-14335
> HHH-14335 Remember the resolved type in SimpleValue#getType instead of resolving multiple times

- hibernate-core/src/main/java/org/hibernate/cfg/CopyIdentifierComponentSecondPass.java
- hibernate-core/src/main/java/org/hibernate/cfg/annotations/TableBinder.java
- hibernate-core/src/test/java/org/hibernate/test/mapping/hhh14343/NestedIdClassTest.java
- hibernate-core/src/test/java/org/hibernate/test/mapping/hhh14343/entity/NestedPlayerStat.java
- hibernate-core/src/test/java/org/hibernate/test/mapping/hhh14343/entity/NestedPlayerStatId.java
- hibernate-core/src/test/java/org/hibernate/test/mapping/hhh14343/entity/NestedScore.java
- hibernate-core/src/test/java/org/hibernate/test/mapping/hhh14343/entity/NestedScoreId.java
- hibernate-core/src/test/java/org/hibernate/test/mapping/hhh14343/entity/NestedStat.java
- hibernate-core/src/test/java/org/hibernate/test/mapping/hhh14343/entity/NestedStatId.java
https://hibernate.atlassian.net/browse/HHH-14343
> HHH-14343 Test and fix quoting of column names when globally quoted identifiers is active

- hibernate-core/src/main/java/org/hibernate/event/spi/InitializeCollectionEventListener.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityAssociationMapping.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/PluralAttributeMapping.java
- hibernate-core/src/main/java/org/hibernate/query/results/FromClauseAccessImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/FromClauseIndex.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/StandardSqmSelectTranslator.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/SimpleFromClauseAccessImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/Fetchable.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/AbstractImmediateCollectionInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/AbstractEmbeddableInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/embeddable/internal/EmbeddableAssembler.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/binding/annotations/embedded/EmbeddedCircularFetchTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cid/CompositeIdTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cid/Customer.hbm.xml
- hibernate-core/src/test/java/org/hibernate/orm/test/cid/Customer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cid/LineItem.hbm.xml
- hibernate-core/src/test/java/org/hibernate/orm/test/cid/LineItem.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cid/Order.hbm.xml
- hibernate-core/src/test/java/org/hibernate/orm/test/cid/Order.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cid/Product.hbm.xml
- hibernate-core/src/test/java/org/hibernate/orm/test/cid/Product.java
- hibernate-core/src/test/java/org/hibernate/test/cid/CompositeIdTest.java
- hibernate-core/src/test/java/org/hibernate/test/hql/ASTParserLoadingTest.java
- hibernate-testing/src/main/java/org/hibernate/testing/jdbc/SQLStatementInspector.java
The PR fixes the following issues:
* chained join fetch for hql queries
* auto flush for hql queries
* add sync tables to SqlAstTranslator to affect auto flush determination
* EmbeddedId initialization
* Fetch deep determination (exclude EmbeddedAttributeMapping and BasicValuedSingularAttributeMapping)
* Fix EmbeddedId lazy collection initialization
> IdClass, EmbeddedId and other fixes

- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/FromClause.java
- hibernate-core/src/test/java/org/hibernate/test/join/OuterJoinTest.java
https://hibernate.atlassian.net/browse/HHH-14380
> HHH-14380 Join ordering logic wrongly pushes cross joins from subqueries to parent

- hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java
- hibernate-core/src/test/java/org/hibernate/test/foreignkeys/disabled/OneToManyBidirectionalForeignKeyTest.java
before this commit, foreign key is created even ConstraintMode.NO_CONSTRAINT present on the @ManyToOne side
> HHH-14229 Fix unexpected foreign key creation

- CONTRIBUTING.md
https://hibernate.atlassian.net/browse/HHH-14400
Minor improvements, but little details matter to encourage a hesitating contributor, :).
> HHH-14400 improve CONTRIBUTING.md

- hibernate-core/src/main/java/org/hibernate/query/Query.java
https://hibernate.atlassian.net/browse/HHH-14421
> HHH-14421 Fix javadoc for Query.stream() method

- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/event/spi/EventEngine.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
- hibernate-core/src/test/java/org/hibernate/test/usertype/IntegratorProvidedUserTypeTest.java
- hibernate-core/src/test/java/org/hibernate/test/usertype/StringWrapper.java
- hibernate-core/src/test/java/org/hibernate/test/usertype/StringWrapperUserType.java
- hibernate-core/src/test/java/org/hibernate/test/usertype/StringWrapperUserTypeIntegrator.java
- hibernate-core/src/test/resources/org/hibernate/test/service/org.hibernate.integrator.spi.Integrator
https://hibernate.atlassian.net/browse/HHH-14408
> HHH-14408 Fix wrong property type for integrator provided user types applied

- hibernate-core/src/main/antlr/sql-gen.g
- hibernate-core/src/test/java/org/hibernate/test/orderby/OrderByTest.java
https://hibernate.atlassian.net/browse/HHH-14351
> HHH-14351 Test and fix order by type discriminator rendering issue

- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
Use a proper bullet list in the Javadoc for `Dialect`.
> use proper bullet list in Dialect javadoc (H6)

- hibernate-core/src/main/java/org/hibernate/query/QueryProducer.java
https://hibernate.atlassian.net/browse/HHH-14384
Minor doc PR, but I think the complaint is valid.
> HHH-14384 Fix QueryProducer.createNativeQuery documentation

- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/event/service/internal/EventListenerRegistryImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
- hibernate-core/src/test/java/org/hibernate/test/usertype/IntegratorProvidedUserTypeTest.java
- hibernate-core/src/test/java/org/hibernate/test/usertype/StringWrapper.java
- hibernate-core/src/test/java/org/hibernate/test/usertype/StringWrapperUserType.java
- hibernate-core/src/test/java/org/hibernate/test/usertype/StringWrapperUserTypeIntegrator.java
- hibernate-core/src/test/resources/org/hibernate/test/service/org.hibernate.integrator.spi.Integrator
Backport of https://github.com/hibernate/hibernate-orm/pull/3712 for 5.4
> HHH-14408 Fix wrong property type for integrator provided user types applied 5.4

- hibernate-core/src/main/java/org/hibernate/boot/registry/selector/internal/DefaultDialectSelector.java
- hibernate-core/src/main/java/org/hibernate/dialect/Database.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgresPlusDialect.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/dialect/internal/DialectFactoryImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/dialect/spi/DatabaseMetaDataDialectResolutionInfoAdapter.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/dialect/spi/DialectResolutionInfo.java
https://hibernate.atlassian.net/browse/HHH-14456
> HHH-14456 Add DialectResolutionInfo#unwrap to be able to detect Cockroach

- hibernate-testing/src/main/java/org/hibernate/testing/orm/jpa/NonStringValueSettingProvider.java
- hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/EntityManagerFactoryExtension.java
- hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/Jpa.java
> Enable non-String value Settings in @Jpa 

- docker_db.sh
See
https://stackoverflow.com/questions/62574379/su-permission-denied-despite-being-root-in-oracle-container
Signed-off-by: Yoann Rodière <yoann@hibernate.org>
> Fix ulimit when starting Oracle Express

- hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/EntityManagerFactoryExtension.java
- hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/Jpa.java
> Spelling correction in @Jpa

- hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessMixedImpl.java
- hibernate-core/src/test/java/org/hibernate/test/proxy/MissingSetterWithEnhancementTest.java
https://hibernate.atlassian.net/browse/HHH-14460
> HHH-14460 Fix NPE when setter is missing for persistent property

- hibernate-core/src/main/java/org/hibernate/collection/internal/AbstractPersistentCollection.java
- hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentBag.java
- hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentIdentifierBag.java
- hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentList.java
- hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentMap.java
- hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentSet.java
- hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentSortedMap.java
- hibernate-core/src/main/java/org/hibernate/collection/internal/PersistentSortedSet.java
- hibernate-core/src/main/java/org/hibernate/collection/spi/PersistentCollection.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
I've made a good start on adding proper use of generics to the `PersistentCollection` hierarchy.
I was doing this work on the 6.0 branch, but I just noticed that it actually applies cleanly to master as well.
> PersistentCollection generics

- gradle/java-module.gradle
- gradle/libraries.gradle
Meant for both master and `5.4`
- https://hibernate.atlassian.net/browse/HHH-14463
> HHH-14463 Upgrade to ByteBuddy 1.10.21: OOB support for JDK17

- hibernate-core/src/main/java/org/hibernate/cfg/ToOneFkSecondPass.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/derivedidentities/e4/c/DerivedIdentitySimpleParentSimpleDepSecondPassOrderingTest.java
- hibernate-core/src/test/java/org/hibernate/test/util/SchemaUtil.java
https://hibernate.atlassian.net/browse/HHH-14467
An alternative to https://github.com/hibernate/hibernate-orm/pull/3755
> HHH-14467 :  AnnotationException: A Foreign key refering <SomeEntity> from <SomeOtherEntity> has the wrong number of column. should be 0 #3755

- hibernate-core/src/main/java/org/hibernate/loader/entity/plan/DynamicBatchingEntityLoader.java
https://hibernate.atlassian.net/browse/HHH-14471
> HHH-14471 Fix concurrency issue due to builder sharing in DynamicBatchingEntityLoader

- hibernate-core/src/main/antlr/hql.g
- hibernate-core/src/test/java/org/hibernate/test/hql/CountExpressionTest.java
https://hibernate.atlassian.net/browse/HHH-9182
> HHH-9182 Test and fix HQL rules to allow more expression types in aggregate functions

- hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingsImpl.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/query/QueryListParametersWithFetchSubSelectTest.java
https://hibernate.atlassian.net/browse/HHH-14439
I will backport to 5.4 once this gets merged.
> HHH-14439 QueryException: Unrecognized parameter label when executing the same query with subselects twice with different list parameters

- hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/InferredBasicValueResolver.java
- hibernate-core/src/main/java/org/hibernate/boot/model/process/internal/VersionResolution.java
- hibernate-core/src/main/java/org/hibernate/cfg/annotations/BasicValueBinder.java
- hibernate-core/src/main/java/org/hibernate/internal/util/ReflectHelper.java
- hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java
- hibernate-core/src/main/java/org/hibernate/mapping/Property.java
- hibernate-core/src/main/java/org/hibernate/metamodel/internal/StandardPojoEmbeddableRepresentationStrategy.java
- hibernate-core/src/main/java/org/hibernate/metamodel/internal/StandardPojoEntityRepresentationStrategy.java
- hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessEmbeddedImpl.java
- hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessMapImpl.java
- hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyBackRefImpl.java
- hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyIndexBackRefImpl.java
- hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyNoopImpl.java
- hibernate-core/src/main/java/org/hibernate/property/access/spi/EnhancedGetterMethodImpl.java
- hibernate-core/src/main/java/org/hibernate/property/access/spi/Getter.java
- hibernate-core/src/main/java/org/hibernate/property/access/spi/GetterFieldImpl.java
- hibernate-core/src/main/java/org/hibernate/property/access/spi/GetterMethodImpl.java
- hibernate-core/src/main/java/org/hibernate/query/internal/AbstractProducedQuery.java
- hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/instantiation/internal/DynamicInstantiationResultImpl.java
- hibernate-core/src/main/java/org/hibernate/tuple/component/PojoComponentTuplizer.java
- hibernate-core/src/main/java/org/hibernate/tuple/entity/PojoEntityTuplizer.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/JavaTypeDescriptor.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/JavaTypeDescriptorBaseline.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/JavaTypeDescriptorRegistry.java
- hibernate-core/src/test/java/org/hibernate/property/BasicPropertyAccessorTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/BeanReflectionHelper.java
> Switch from java.lang.Class to java.lang.reflect.Type in the metamodel to support parameterized types

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/PluralAttributeMappingImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/DelayedCollectionAssembler.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/DelayedCollectionFetch.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/DelayedCollectionInitializer.java
> Implement support for delayed collections with FKs based on non-primary keys

- hibernate-core/src/main/java/org/hibernate/action/internal/BulkOperationCleanupAction.java
- hibernate-core/src/main/java/org/hibernate/query/results/DomainResultCreationStateImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeNonSelectQueryPlanImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeSelectQueryPlanImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/spi/NativeJdbcMutation.java
> Non-select native query support and fix parameter binding ordering issues for select native queries

- hibernate-core/src/main/java/org/hibernate/query/hql/internal/DomainPathPart.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/sqm/exec/SubQueryImplicitJoinReferenceTest.java
This PR fixes the following envers tests:
- AssociationToOneLeftJoinQueryTest
- AssociationEntitiesModifiedQueryTest
- JoinedInheritancePropertyJoinTest
> envers test failures

- hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java
- hibernate-core/src/test/java/org/hibernate/test/jpa/orphan/one2one/embedded/OneToOneLazyOrphanRemovalInEmbeddedEntityTest.java
- hibernate-core/src/test/java/org/hibernate/test/querycache/QueryCacheTest.java
https://hibernate.atlassian.net/browse/HHH-9663
> HHH-9663 Test and implement orphan removal of assocations within embeddables

- docker_db.sh
- hibernate-core/src/main/java/org/hibernate/engine/internal/JoinSequence.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/HqlSqlWalker.java
- hibernate-core/src/test/java/org/hibernate/query/hhh12076/HbmMappingJoinClassTest.java
https://hibernate.atlassian.net/browse/HHH-12076
> HHH-12076 Enable table group joins for collection joins

- docker_db.sh
- enable experimental settings for cockroachdb
- reduce shmni setting for Hana
> Docker_db improvements

- hibernate-core/src/main/java/org/hibernate/query/hql/internal/BasicDotIdentifierConsumer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/EmbeddedIdTest.java
Fix Cannot resolve path exception with EmbeddedId and hql queries not using aliases, this fixes another bunch of envers tests
> Wip/6.0 Cannot resolve path

- hibernate-core/src/main/java/org/hibernate/hql/spi/id/local/LocalTemporaryTableBulkIdStrategy.java
Test to see if this fixes the testsuite issues.
> Try dropping local tables in same connection

- hibernate-core/src/main/java/org/hibernate/annotations/AttributeAccessor.java
- hibernate-core/src/main/java/org/hibernate/cfg/annotations/PropertyBinder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/binding/annotations/access/AttributeAccessorTest.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/accesstype/AttributeAccessorTest.java
See discussion here:
https://github.com/hibernate/hibernate-orm/discussions/3780#discussioncomment-423468
> make @AttributeAccessor annotation typesafe

- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/BooleanTypeDescriptor.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/EnumJavaTypeDescriptor.java
cc @beikov this is what I meant.
I think that's cleaner, and potentially more flexible, even if perhaps not entirely necessary.
> move the code for generating check constraints to Dialect

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcCoordinatorImpl.java
- hibernate-core/src/main/java/org/hibernate/resource/jdbc/internal/LogicalConnectionManagedImpl.java
- hibernate-core/src/test/java/org/hibernate/test/connections/BeforeCompletionReleaseTest.java
https://hibernate.atlassian.net/browse/HHH-14557
Backport of #3917; let's merge that one first.
> Backport HHH-14557 to branch 5.4 - Connection leaked on rollback with mode DELAYED_ACQUISITION_AND_RELEASE_BEFORE_TRANSACTION_COMPLETION

- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/query/NonSelectCriteriaTest.java
Follows up on https://github.com/hibernate/hibernate-orm/pull/3922
> Added test for non-select criteria queries

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/FlushVisitor.java
- hibernate-core/src/main/java/org/hibernate/event/internal/WrapVisitor.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/inlinedirtychecking/LoadUninitializedCollectionTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/inlinedirtychecking/LoadingLazyCollectionAfterQueryExecutionWithFlushModeAlwaysTest.java
https://hibernate.atlassian.net/browse/HHH-14549
> HHH-14549 Collection with default field initializer will always be empty

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/FlushVisitor.java
- hibernate-core/src/main/java/org/hibernate/event/internal/WrapVisitor.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/inlinedirtychecking/LoadUninitializedCollectionTest.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/inlinedirtychecking/LoadingLazyCollectionAfterQueryExecutionWithFlushModeAlwaysTest.java
https://hibernate.atlassian.net/browse/HHH-14549
Backport of #3916
> Backport HHH-14549 to branch 5.4 - Collection with default field initializer will always be empty

- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/postgis/PGGeometryTypeDescriptor.java
* HHH-11490 Fix for UUID mapping conflict
* HHH-11490 Custom ValueBinder implementation
> HHH-11490 Fix for UUID mapping conflict

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultLoadEventListener.java
- hibernate-core/src/test/java/org/hibernate/test/notfound/EagerProxyNotFoundTest.java
Do not merge. This PR follows a different process.
https://hibernate.atlassian.net/browse/HHH-14537
> HHH-14537 : ENFE when non-existing association with @NotFound(IGNORE)  has proxy in PC (5.3)

- hibernate-core/src/main/java/org/hibernate/Hibernate.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/IdInUninitializedProxyTest.java
https://hibernate.atlassian.net/browse/HHH-14571
> HHH-14571 Hibernate.isPropertyInitialized( someEntity, "id" ) returns false

- hibernate-core/src/main/java/org/hibernate/Hibernate.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/IdInUninitializedProxyTest.java
https://hibernate.atlassian.net/browse/HHH-14571
Backport of #3941
> Backport HHH-14571 to branch 5.4 - Hibernate.isPropertyInitialized( someEntity, "id" ) returns false

- hibernate-core/src/main/java/org/hibernate/engine/internal/AbstractEntityEntry.java
- hibernate-core/src/main/java/org/hibernate/event/internal/WrapVisitor.java
https://hibernate.atlassian.net/browse/HHH-14573
> HHH-14573 Remove useless call to EnhancementAsProxyLazinessInterceptor#isInitialized()

- documentation/src/test/java/org/hibernate/userguide/inheritance/DiscriminatorNotNullSingleTableTest.java
- hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
- hibernate-core/src/main/java/org/hibernate/cfg/annotations/EntityBinder.java
- hibernate-core/src/main/java/org/hibernate/cfg/internal/NullableDiscriminatorColumnSecondPass.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/test/inheritance/discriminator/SingleTableNullNotNullDiscriminatorTest.java
- hibernate-core/src/test/java/org/hibernate/test/inheritance/discriminator/joinedsubclass/JoinedNullNotNullDiscriminatorTest.java
https://hibernate.atlassian.net/browse/HHH-12445
> HHH-12445 Discriminator column should be nullable when using @DiscriminatorValue( "null" )

- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/CollectionSizeNode.java
- hibernate-core/src/test/java/org/hibernate/test/hql/size/WhereClauseOrderBySizeTest.java
- hibernate-core/src/test/java/org/hibernate/test/hql/size/filter/City.java
- hibernate-core/src/test/java/org/hibernate/test/hql/size/filter/Region.java
- hibernate-core/src/test/java/org/hibernate/test/hql/size/filter/WhereAnnotatedOneToManySizeTest.java
https://hibernate.atlassian.net/browse/HHH-14585
> HHH-14585 size() HQL function discards '@Where' clause

- hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
- hibernate-core/src/test/java/org/hibernate/test/events/CallbackTest.java
https://hibernate.atlassian.net/browse/HHH-14541
> HHH-14541 SessionFactoryObserver#sessionFactoryClosing() gets called after the session factory is marked as closed

- hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/PersistenceXmlParser.java
> Fix in one of the PersistenceXmlParser.parse() methods used in tests

- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSqlAstCreationState.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/DomainResultCreationState.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/AbstractCollectionInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/AbstractImmediateCollectionInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/DelayedCollectionInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/AbstractEntityInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/onetomany/OneToManyBidirectionalTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/bidirectional/BiDirectionalOneToOneFetchTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/joined/Address.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/joined/Entity.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/joined/JoinedSubclassOneToOneTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/joined/Org.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/joined/Person.hbm.xml
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/joined/Person.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/singletable/Address.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/singletable/DiscrimSubclassOneToOneTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/singletable/Entity.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/singletable/Org.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/singletable/Person.hbm.xml
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/singletable/Person.java
- hibernate-core/src/test/java/org/hibernate/test/onetoone/joined/JoinedSubclassOneToOneTest.java
- hibernate-core/src/test/java/org/hibernate/test/onetoone/singletable/DiscrimSubclassOneToOneTest.java
- hibernate-core/src/test_legacy/org/hibernate/test/hql/HQLTest.java
- fix hql queries not detecting circularity
- Collection Intializer fix creation of persistence set instance for the wrong subclass
> Wip/6.0 Re-enabled additional tests

- hibernate-core/src/main/java/org/hibernate/event/service/internal/EventListenerGroupImpl.java
- hibernate-core/src/main/java/org/hibernate/event/service/spi/EventListenerGroup.java
…ernate Reactive to fire events more efficiently
- https://hibernate.atlassian.net/browse/HHH-14621
> HHH-14621 Introduce new methods on EventListenerGroup for HR

- hibernate-core/src/main/java/org/hibernate/engine/internal/TwoPhaseLoad.java
- hibernate-core/src/main/java/org/hibernate/loader/Loader.java
- hibernate-core/src/main/java/org/hibernate/loader/plan/exec/process/internal/AbstractRowReader.java
To be followed up by matching changes in Hibernate Reactive:
- https://github.com/hibernate/hibernate-reactive/commit/d13012d1b23a374a827b4f02d696269cbb1777a3
Lots of code deletions :)
> HHH-14622 Improved iteration of PreLoadEventListener

- hibernate-core/src/main/java/org/hibernate/event/internal/AbstractFlushingEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DirtyCollectionSearchVisitor.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/LazyProxyWithCollectionTest.java
https://hibernate.atlassian.net/browse/HHH-14619
> HHH-14619 Test and fix ClassCastException because collection of uninitialized proxy is dirty checked

- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/Helper.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/exec/ScriptSourceInputAggregate.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/schemagen/JpaFileSchemaGeneratorTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/schemagen/JpaSchemaGeneratorTest.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/schemagen/iso8859/JpaFileSchemaGeneratorWithHbm2DdlCharsetNameTest.java
- hibernate-core/src/test/resources/org/hibernate/jpa/test/schemagen/create-script-source2.sql
- hibernate-core/src/test/resources/org/hibernate/jpa/test/schemagen/drop-script-source2.sql
- hibernate-core/src/test/resources/org/hibernate/jpa/test/schemagen/iso8859/create-script-source2.sql
- hibernate-core/src/test/resources/org/hibernate/jpa/test/schemagen/iso8859/drop-script-source2.sql
- hibernate-core/src/test/resources/org/hibernate/jpa/test/schemagen/iso8859/load-script-source2.sql
- hibernate-core/src/test/resources/org/hibernate/jpa/test/schemagen/load-script-source2.sql
https://hibernate.atlassian.net/browse/HHH-14618
> HHH-14618 Allow passing multiple script source files separated by comma

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/test/optlock/OptimisticLockWithGloballyQuotedIdentifierTest.java
- hibernate-core/src/test/java/org/hibernate/test/optlock/OptimisticLockWithQuotedVersionTest.java
https://hibernate.atlassian.net/browse/HHH-14616
> HHH-14616 Optimistic Lock throws org.hibernate.exception.SQLGrammarException: could not retrieve version

- hibernate-core/src/main/java/org/hibernate/engine/loading/internal/LoadContexts.java
See https://hibernate.atlassian.net/browse/HHH-14574
> HHH-14574 Avoid NPEs from LoadContexts.cleanup(ResultSet)

- hibernate-core/src/main/java/org/hibernate/engine/query/spi/QueryPlanCache.java
- hibernate-core/src/main/java/org/hibernate/stat/internal/QueryStatisticsImpl.java
- hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsImpl.java
- hibernate-core/src/main/java/org/hibernate/stat/spi/StatisticsImplementor.java
- hibernate-core/src/test/java/org/hibernate/stat/internal/QueryPlanCacheStatisticsTest.java
https://hibernate.atlassian.net/browse/HHH-14632
> HHH-14632 - Call statistics.queryPlanCacheHit and statistics.queryPlanCacheMiss for FilterQueryPlan and NativeSQLQueryPlan

- hibernate-core/src/main/java/org/hibernate/dialect/Oracle12cDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/pagination/LimitHandler.java
- hibernate-core/src/main/java/org/hibernate/dialect/pagination/Oracle12LimitHandler.java
- hibernate-core/src/main/java/org/hibernate/loader/Loader.java
- hibernate-core/src/main/java/org/hibernate/loader/plan/exec/internal/AbstractLoadPlanBasedLoader.java
- hibernate-core/src/test/java/org/hibernate/test/pagination/OraclePaginationTest.java
- hibernate-core/src/test/java/org/hibernate/test/pagination/OraclePaginationWithLocksTest.java
https://hibernate.atlassian.net/browse/HHH-14624
> HHH-14624 HHH-14624 Oracle from version 12 started supporting the offset ? rows fetch next ? rows onlysyntax for pagination

- CONTRIBUTING.md
- README.md
- documentation/documentation.gradle
- documentation/src/main/asciidoc/integrationguide/Preface.adoc
- documentation/src/main/asciidoc/quickstart/guides/obtaining.adoc
- documentation/src/main/asciidoc/quickstart/guides/preface.adoc
- documentation/src/main/asciidoc/quickstart/guides/tutorial_annotations.adoc
- documentation/src/main/asciidoc/topical/metamodelgen/MetamodelGenerator.adoc
- documentation/src/main/asciidoc/topical/registries/ServiceRegistries.adoc
- documentation/src/main/asciidoc/topical/wildfly/Wildfly.adoc
- documentation/src/main/asciidoc/userguide/Preface.adoc
- documentation/src/main/asciidoc/userguide/appendices/Annotations.adoc
- documentation/src/main/asciidoc/userguide/appendices/BestPractices.adoc
- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
- documentation/src/main/asciidoc/userguide/chapters/batch/Batching.adoc
- documentation/src/main/asciidoc/userguide/chapters/caching/Caching.adoc
- documentation/src/main/asciidoc/userguide/chapters/domain/basic_types.adoc
- documentation/src/main/asciidoc/userguide/chapters/domain/entity.adoc
- documentation/src/main/asciidoc/userguide/chapters/envers/Envers.adoc
- documentation/src/main/asciidoc/userguide/chapters/jdbc/Database_Access.adoc
- documentation/src/main/asciidoc/userguide/chapters/locking/Locking.adoc
- documentation/src/main/asciidoc/userguide/chapters/portability/Portability.adoc
- documentation/src/main/asciidoc/userguide/chapters/query/hql/HQL.adoc
- documentation/src/main/asciidoc/userguide/chapters/query/spatial/Spatial.adoc
- documentation/src/main/asciidoc/userguide/chapters/transactions/Transactions.adoc
- gradle/published-java-module.gradle
- gradle/publishing-pom.gradle
https://hibernate.atlassian.net/browse/HHH-14641
The following folders or files are processed:
- gradle/
- documentation/
- README.md
- CONTRIBUTE.md (some outdated links are also updated)
> HHH-14641 replace 'http://' reference with 'https://'

- hibernate-core/src/main/java/org/hibernate/internal/ScrollableResultsImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/internal/RowProcessingStateStandardImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesCacheHit.java
- hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesResultSetImpl.java
- hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/spi/JdbcValues.java
https://hibernate.atlassian.net/browse/HHH-14642
straightforward implementation and self-contained refactoring. created a separate PR to make the verifying piecemeal and digestible. The associated testing class cannot be migrated for it relies on the completion of https://github.com/hibernate/hibernate-orm/pull/4018
> wip/6.0 HHH-14642 verify Criteria - finish scrollableResultsImpl

- hibernate-core/src/main/java/org/hibernate/dialect/AbstractTransactSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/DerbyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/InformixDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/CaseLeastGreatestEmulation.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/DerbyLpadEmulation.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/DerbyRpadEmulation.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/SQLServerFormatEmulation.java
> Rename some classes for consistency

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/test/optlock/OptimisticLockWithGloballyQuotedIdentifierTest.java
- hibernate-core/src/test/java/org/hibernate/test/optlock/OptimisticLockWithQuotedVersionTest.java
https://hibernate.atlassian.net/browse/HHH-14616
> HHH-14616 (5.3)

- hibernate-core/src/main/java/org/hibernate/dialect/SQLServer2012Dialect.java
https://hibernate.atlassian.net/browse/HHH-14655
> HHH-14655 Upper case the information schema sequence identifier again to fix issues with case sensitive databases

- hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsImpl.java
https://hibernate.atlassian.net/browse/HHH-14662
> HHH-14662 Remove unnecessary statefull lambda instances from StatisticsImpl

- hibernate-graalvm/src/main/java/org/hibernate/graalvm/internal/QueryParsingSupport.java
- hibernate-graalvm/src/main/java/org/hibernate/graalvm/internal/StaticClassLists.java
- https://hibernate.atlassian.net/browse/HHH-14661
> HHH-14661 GraalVM support should not register ANTLR parser nodes when the Parser isn't reacheable

- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/HibernateSchemaManagementTool.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/PostgreSQLMultipleSchemaSequenceTest.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/idgenerator/SequenceGenerationTest.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/idgenerator/SequenceGeneratorsTest.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/idgenerator/TableGeneratorTest.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/idgenerator/TableGeneratorsTest.java
- hibernate-core/src/test/java/org/hibernate/test/schemaupdate/uniqueconstraint/UniqueConstraintGenerationTest.java
- hibernate-graalvm/src/main/java/org/hibernate/graalvm/internal/QueryParsingSupport.java
https://hibernate.atlassian.net/browse/HHH-14665
> HHH-14665 Use semi-colon as the default statement delimiter for scripts

- hibernate-core/src/main/java/org/hibernate/internal/log/DeprecationLogger.java
- hibernate-core/src/main/java/org/hibernate/metamodel/internal/AttributeFactory.java
- hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java
https://hibernate.atlassian.net/browse/HHH-14660
> HHH-14660 Deprecate component mappings with different attributes for the same class

- hibernate-core/src/main/java/org/hibernate/dialect/pagination/Oracle12LimitHandler.java
- hibernate-core/src/test/java/org/hibernate/dialect/Oracle12LimitHandlerTest.java
- hibernate-core/src/test/java/org/hibernate/test/pagination/OraclePaginationWithLocksTest.java
https://hibernate.atlassian.net/browse/HHH-14649
> HHH-14649 Oracle limit handler create wrong sql query when multiple spaces are present in the query

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/spi/JdbcEnvironment.java
Some additional improvements for HHH-14667, to restore backwards compatibility with Hibernate Reactive / main
> HHH-14667 Maintain backwards compatibility for Hibernate Reactive

- hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java
- hibernate-core/src/test/java/org/hibernate/test/orphan/elementcollection/ElementCollectionOrphanTest.java
- hibernate-core/src/test/java/org/hibernate/test/orphan/elementcollection/EnrollableClass.java
- hibernate-core/src/test/java/org/hibernate/test/orphan/elementcollection/EnrolledClassSeat.java
- hibernate-core/src/test/java/org/hibernate/test/orphan/elementcollection/Student.java
- hibernate-core/src/test/java/org/hibernate/test/orphan/elementcollection/StudentEnrolledClass.java
- hibernate-core/src/test/java/org/hibernate/test/orphan/elementcollection/student.hbm.xml
https://hibernate.atlassian.net/browse/HHH-14597
> HHH-14597 Test and fix for NPE while trying to delete cascade to-one association within element collection

- hibernate-core/src/main/java/org/hibernate/collection/internal/AbstractPersistentCollection.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/proxy/AbstractLazyInitializer.java
- hibernate-core/src/test/java/org/hibernate/test/connections/LazyLoadingConnectionCloseTest.java
https://hibernate.atlassian.net/browse/HHH-4808
> HHH-4808 - SessionImpl.initializeCollection() does not release JDBC connection (if outside of a transaction)

- hibernate-core/src/main/java/org/hibernate/stat/internal/StatisticsImpl.java
- hibernate-core/src/main/java/org/hibernate/stat/internal/StatsNamedContainer.java
- hibernate-core/src/test/java/org/hibernate/stat/internal/StatsNamedContainerNullComputedValueTest.java
- https://hibernate.atlassian.net/browse/HHH-14690
- https://hibernate.atlassian.net/browse/HHH-14691
> Stats improvements

- docker_db.sh
- hibernate-core-jakarta/hibernate-core-jakarta.gradle
- hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/internal/EntityValuedPathInterpretation.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/GroupByTest.java
https://hibernate.atlassian.net/browse/HHH-1615
> HHH-1615 Test and fix for group by entity

- hibernate-core/src/main/java/org/hibernate/id/factory/internal/DefaultIdentifierGeneratorFactory.java
- hibernate-core/src/test/java/org/hibernate/test/idgen/userdefined/UserDefinedGeneratorsTests.java
https://hibernate.atlassian.net/browse/HHH-14688
> HHHH-14688 Get IdentifierGenerator from BeanContainer if not registered

- hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
- https://hibernate.atlassian.net/browse/HHH-14706
> HHH-14706 Improve error message on incompatible types due to mismatched classloader

- hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlLexer.g4
- hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
- hibernate-core/src/main/java/org/hibernate/dialect/function/CaseWhenEveryAnyEmulation.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/EveryAnyEmulation.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/SQLServerEveryAnyEmulation.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/function/AbstractSqmFunctionDescriptor.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/function/AbstractSqmSelfRenderingFunctionDescriptor.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/function/NamedSqmFunctionDescriptor.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/AggregateFilterClauseTest.java
> Filter clause for aggregate functions in HQL

- hibernate-core/src/test/java/org/hibernate/orm/test/cid/CompositeIdWithGeneratorTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cid/PurchaseRecord.java
> Fix for CompositeIdWithGeneratorTest failures in sybase

- hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
- hibernate-core/src/main/java/org/hibernate/cfg/OneToOneSecondPass.java
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/DotNode.java
- hibernate-core/src/main/java/org/hibernate/mapping/OneToOne.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractPropertyMapping.java
- hibernate-core/src/main/java/org/hibernate/type/EntityType.java
- hibernate-core/src/main/java/org/hibernate/type/ManyToOneType.java
- hibernate-core/src/main/java/org/hibernate/type/OneToOneType.java
- hibernate-core/src/main/java/org/hibernate/type/SpecialOneToOneType.java
- hibernate-core/src/main/java/org/hibernate/type/TypeFactory.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/onetoone/OptionalOneToOneMapsIdQueryTest.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/onetoone/OptionalOneToOnePKJCQueryTest.java
- hibernate-core/src/test/java/org/hibernate/test/constraint/ForeignKeyConstraintMapsIdTest.java
- hibernate-core/src/test/java/org/hibernate/test/constraint/ForeignKeyNoConstraintTest.java
- hibernate-core/src/test/java/org/hibernate/test/notfound/OptionalEagerInEmbeddableNotFoundTest.java
- hibernate-core/src/test/java/org/hibernate/test/notfound/OptionalEagerMappedByNotFoundTest.java
- hibernate-core/src/test/java/org/hibernate/test/notfound/OptionalEagerNotFoundTest.java
- hibernate-core/src/test/java/org/hibernate/test/notfound/OptionalEagerRefNonPKNotFoundTest.java
- hibernate-core/src/test/java/org/hibernate/test/notfound/OptionalLazyNotFoundTest.java
- hibernate-core/src/test/java/org/hibernate/test/notfound/RequiredLazyNotFoundTest.java
- hibernate-core/src/test/java/org/hibernate/test/onetoone/lazy/LazyToOneTest.java
- hibernate-core/src/test/java/org/hibernate/test/ops/OneToOneMergeTest.java
https://hibernate.atlassian.net/browse/HHH-12320 
https://hibernate.atlassian.net/browse/HHH-12842
https://hibernate.atlassian.net/browse/HHH-12436
https://hibernate.atlassian.net/browse/HHH-13875
This is for 5.3 branch.
> HHH-12320 HHH-12842 HHH-12436 HHH-13875 (5.3)

- hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultEvictEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/jpa/internal/PersistenceUnitUtilImpl.java
- hibernate-core/src/main/java/org/hibernate/proxy/AbstractLazyInitializer.java
- hibernate-core/src/main/java/org/hibernate/proxy/LazyInitializer.java
- hibernate-core/src/main/java/org/hibernate/proxy/map/MapProxy.java
- hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/ByteBuddyInterceptor.java
- hibernate-core/src/main/java/org/hibernate/proxy/pojo/javassist/JavassistLazyInitializer.java
- hibernate-core/src/main/java/org/hibernate/tuple/entity/AbstractEntityTuplizer.java
- hibernate-core/src/main/java/org/hibernate/type/EntityType.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/ops/MergeJpaComplianceTest.java
- hibernate-envers/src/main/java/org/hibernate/envers/event/spi/BaseEnversEventListener.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/EntityInstantiator.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/id/SingleIdMapper.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/id/VirtualEntitySingleIdMapper.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/tools/EntityTools.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/RevisionsOfEntityQuery.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/proxy/ProxyIdentifier.java
https://hibernate.atlassian.net/browse/HHH-14608
This is a different solution than that of https://github.com/hibernate/hibernate-orm/pull/3986
> HHH-14608 Merge causes StackOverflow when JPA proxy compliance is enabled

- hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultEvictEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/jpa/internal/PersistenceUnitUtilImpl.java
- hibernate-core/src/main/java/org/hibernate/proxy/AbstractLazyInitializer.java
- hibernate-core/src/main/java/org/hibernate/proxy/LazyInitializer.java
- hibernate-core/src/main/java/org/hibernate/proxy/map/MapProxy.java
- hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/ByteBuddyInterceptor.java
- hibernate-core/src/main/java/org/hibernate/proxy/pojo/javassist/JavassistLazyInitializer.java
- hibernate-core/src/main/java/org/hibernate/tuple/entity/AbstractEntityTuplizer.java
- hibernate-core/src/main/java/org/hibernate/type/EntityType.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/ops/MergeJpaComplianceTest.java
- hibernate-envers/src/main/java/org/hibernate/envers/event/spi/BaseEnversEventListener.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/EntityInstantiator.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/id/SingleIdMapper.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/id/VirtualEntitySingleIdMapper.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/tools/EntityTools.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/RevisionsOfEntityQuery.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/proxy/ProxyIdentifier.java
https://hibernate.atlassian.net/browse/HHH-14608
This is for 5.3 branch.
> HHH-14608 : Merge causes StackOverflow when JPA proxy compliance is enabled (5.3)

- gradle/java-module.gradle
- gradle/libraries.gradle
https://hibernate.atlassian.net/browse/HHH-14707
Build against JDK18: https://ci.hibernate.org/view/Personal%20jobs/job/hibernate-orm-personal-yoann-jdk18/1/
> HHH-14707 Upgrade to Byte Buddy 1.11.8

- hibernate-core/src/main/java/org/hibernate/exception/internal/StandardSQLExceptionConverter.java
- https://hibernate.atlassian.net/browse/HHH-14727
> HHH-14727 Minor code cleanup in StandardSQLExceptionConverter

- hibernate-core/src/main/java/org/hibernate/bytecode/internal/SessionFactoryObserverForBytecodeEnhancer.java
- hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BasicProxyFactoryImpl.java
- hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java
- hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ProxyFactoryFactoryImpl.java
- hibernate-core/src/main/java/org/hibernate/bytecode/internal/javassist/ProxyFactoryFactoryImpl.java
- hibernate-core/src/main/java/org/hibernate/bytecode/internal/none/NoProxyFactoryFactory.java
- hibernate-core/src/main/java/org/hibernate/bytecode/internal/none/NoneBasicProxyFactory.java
- hibernate-core/src/main/java/org/hibernate/bytecode/spi/ProxyFactoryFactory.java
- hibernate-core/src/main/java/org/hibernate/tuple/component/PojoComponentTuplizer.java
- hibernate-core/src/test/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyBasicProxyFactoryTest.java
- hibernate-core/src/test/java/org/hibernate/bytecode/internal/bytebuddy/GenerateProxiesTest.java
I've not finished my work relating to the metadata usage proper, but these smaller pieces are probably simpler to digest and will pave the road towards the more interesting optimisations.
Also, they should improve proxy generation times a little, so I'm sending them already.
- https://hibernate.atlassian.net/browse/HHH-14731
- https://hibernate.atlassian.net/browse/HHH-14732
- https://hibernate.atlassian.net/browse/HHH-14733
- https://hibernate.atlassian.net/browse/HHH-14734
> ByteBuddy proxy generation improvements towards a more conservative use of Metadata

- hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/InformationExtractorJdbcDatabaseMetaDataImpl.java
https://hibernate.atlassian.net/browse/HHH-14722
> HHH-14772 InformationExtractorJdbcDatabaseMetaDataImpl#getCurrentSche…ma() method returns currentCatalog if schema == null

- hibernate-core/src/main/java/org/hibernate/exception/internal/StandardSQLExceptionConverter.java
- https://hibernate.atlassian.net/browse/HHH-14740
> HHH-14740 Still need the nullcheck removed in HHH-14727

- hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java
Fix https://hibernate.atlassian.net/browse/HHH-14761
> HHH-14761 Exception message String.format too many variables

- hibernate-core/src/main/java/org/hibernate/id/factory/internal/DefaultIdentifierGeneratorFactory.java
Trivial, but should allow us to delete some code from Quarkus.
- https://hibernate.atlassian.net/browse/HHH-14755
> HHH-14755 Allow configuring the DefaultIdentifierGeneratorFactory to ignore BeanContainer

- hibernate-core/src/test/java/org/hibernate/test/component/empty/EmptyInitializedNestedCompositesTest.java
https://hibernate.atlassian.net/browse/HHH-11926
Test is annotated with `@FailureExpected`.
> HHH-11926 : Add FailureExpected test

- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/TypeRenderingVisitor.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/CollectionAsBasicTypeTest.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/EnumHolder.java
https://hibernate.atlassian.net/browse/HHH-14768
> HHH-14768 Fix recursive type variable rendering

- docker_db.sh
- documentation/src/main/asciidoc/userguide/chapters/query/hql/HQL.adoc
- documentation/src/main/asciidoc/userguide/chapters/query/hql/extras/predicate_ilike_bnf.txt
- documentation/src/test/java/org/hibernate/userguide/hql/HQLTest.java
- hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlLexer.g4
- hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
- hibernate-core/src/main/java/org/hibernate/query/criteria/HibernateCriteriaBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmTreePrinter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmLikePredicate.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/predicate/LikePredicate.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/ILikeCriteriaTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/ILikeTest.java
- hibernate-testing/src/main/java/org/hibernate/testing/cleaner/SQLServerDatabaseCleaner.java
> HHH-14739 - Implement ILike support

- documentation/src/main/asciidoc/userguide/chapters/pc/PersistenceContext.adoc
- documentation/src/test/java/org/hibernate/userguide/criteria/CriteriaTest.java
- documentation/src/test/java/org/hibernate/userguide/envers/EntityTypeChangeAuditTest.java
- documentation/src/test/java/org/hibernate/userguide/pc/FilterTest.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java
https://hibernate.atlassian.net/browse/HHH-14772
> HHH-14772 and respect explicit polymorphism

- hibernate-core/src/main/java/org/hibernate/tool/hbm2ddl/SchemaExport.java
- hibernate-core/src/main/java/org/hibernate/tool/hbm2ddl/SchemaUpdate.java
- hibernate-core/src/main/java/org/hibernate/tool/hbm2ddl/SchemaValidator.java
- hibernate-core/src/main/java/org/hibernate/tool/hbm2ddl/SchemaValidatorTask.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/xml/JpaDescriptorParser.java
Fixes https://hibernate.atlassian.net/browse/HHH-14760
> HHH-14760 Close resource - potential resource leak

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcCoordinatorImpl.java
- https://hibernate.atlassian.net/browse/HHH-14773
> HHH-14773 JdbcCoordinatorImpl micro improvement: unguarded tracev pameters should be constant

- hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
- hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetamodelImpl.java
- https://hibernate.atlassian.net/browse/HHH-14770
> HHH-14770 Optimise access to EntityPersister in Metamodel via Class type

- hibernate-core/src/main/java/org/hibernate/engine/spi/SessionImplementor.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java
- hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
- hibernate-core/src/main/java/org/hibernate/loader/Loader.java
- https://hibernate.atlassian.net/browse/HHH-14776
> Optimisations in Loader

- hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaTransactionCoordinatorBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaTransactionCoordinatorImpl.java
https://hibernate.atlassian.net/browse/HHH-14625
> HHH-14625 Avoid performing a ServiceRegistryLookup at runtime in JtaTransactionCoordinatorImpl

- hibernate-core/src/main/java/org/hibernate/dialect/Database.java
- hibernate-core/src/main/java/org/hibernate/dialect/MariaDB106Dialect.java
https://hibernate.atlassian.net/browse/HHH-14777
> HHH-14777 Enabled skip locked rendering for MariaDB 10.6+

- gradle/libraries.gradle
- https://hibernate.atlassian.net/browse/HHH-14788
> HHH-14788 Upgrade to Byteman 4.0.16

- gradle/java-module.gradle
- gradle/libraries.gradle
https://hibernate.atlassian.net/browse/HHH-14771
> HHH-14771 Upgrade to Byte Buddy 1.11.12

- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/BaseFunctionalTest.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/DomainDataRegionTest.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/HibernateCacheTest.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/InsertedDataTest.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/JCacheClasspathConfigUriTest.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/JCacheConfigRelativePathTest.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/JCacheConfigUrlTest.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/JCacheTransactionalCacheConcurrencyStrategyTest.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/MissingCacheStrategyTest.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/RefreshUpdatedDataTest.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/StorageAccessTest.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/TestHelper.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/Account.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/Event.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/EventManager.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/HolidayCalendar.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/Item.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/Person.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/PhoneNumber.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/Product.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/UuidItem.java
- hibernate-jcache/src/test/java/org/hibernate/orm/test/jcache/domain/VersionedItem.java
- hibernate-jcache/src/test/resources/hibernate-config/domain/Account.hbm.xml
- hibernate-jcache/src/test/resources/hibernate-config/domain/Event.hbm.xml
- hibernate-jcache/src/test/resources/hibernate-config/domain/HolidayCalendar.hbm.xml
- hibernate-jcache/src/test/resources/hibernate-config/domain/Item.hbm.xml
- hibernate-jcache/src/test/resources/hibernate-config/domain/Person.hbm.xml
- hibernate-jcache/src/test/resources/hibernate-config/domain/PhoneNumber.hbm.xml
- hibernate-jcache/src/test/resources/hibernate-config/ehcache/jcache-ehcache-config.xml
> Fixed and reorganized tests in hibernate-jcache

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
See the comment in `generateInsertString()`
This is a very minor change but is conceptually correct.
> insert with @DynamicInsert should use generateIdentityInsertString()

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/lazy/proxy/BytecodeEnhancedLazyLoadingOnDeletedEntityTest.java
https://hibernate.atlassian.net/browse/HHH-14811
> HHH-14811 org.hibernate.AssertionFailure thrown instead of LazyInitializationException when trying to access a lazy property on a deleted entity

- hibernate-core/src/main/java/org/hibernate/type/EntityType.java
see https://github.com/hibernate/hibernate-reactive/pull/954
cc @Sanne
> expose two operations on EntityType for use by Hibernate Reactive

- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/util/ExceptionHelper.java
- hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jdbc/internal/DdlTransactionIsolatorNonJtaImpl.java
- hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaIsolationDelegate.java
https://hibernate.atlassian.net/browse/HHH-14763
> HHH-14763 Avoid suppress exceptions in try/finally

- hibernate-core/src/main/java/org/hibernate/mapping/Component.java
Add componentClassName details on  MappingException
See [the JIRA HHH-5249 issue](https://hibernate.atlassian.net/browse/HHH-5249)
> HHH-5249 Add more details on MappingException

- hibernate-core/src/main/java/org/hibernate/cfg/annotations/reflection/internal/JPAXMLOverriddenAnnotationReader.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/xml/XmlAndAnnotationAttributeOverrideTest.java
- hibernate-core/src/test/java/org/hibernate/test/util/SchemaUtil.java
- hibernate-core/src/test/resources/org/hibernate/jpa/test/xml/orm-empty.xml
https://hibernate.atlassian.net/browse/HHH-14827
Backport of #4224
> Backport HHH-14827 to branch 5.5 - @AttributeOverride at type level does not work when also using orm.xml

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/FieldAccessEnhancer.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/PersistentAttributeTransformer.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/basic/FinalFieldEnhancementTest.java
- hibernate-core/src/test/resources/log4j2.properties
https://hibernate.atlassian.net/browse/HHH-14828
> HHH-14828 Bytecode enhancement generates invalid bytecode for final fields

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/FieldAccessEnhancer.java
- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/internal/bytebuddy/PersistentAttributeTransformer.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/basic/FinalFieldEnhancementTest.java
- hibernate-core/src/test/resources/log4j2.properties
https://hibernate.atlassian.net/browse/HHH-14828
Backport of #4231
> Backport HHH-14828 to branch 5.5 - Bytecode enhancement generates invalid bytecode for final fields

- gradle/libraries.gradle
- https://hibernate.atlassian.net/browse/HHH-14833
> HHH-14833 Upgrade to Byte Buddy 1.11.16

- hibernate-core/src/main/java/org/hibernate/query/results/dynamic/DynamicFetchBuilderStandard.java
- hibernate-core/src/main/java/org/hibernate/query/sql/internal/ResultSetMappingProcessor.java
- hibernate-core/src/test/java/org/hibernate/orm/test/propertyref/basic/Account.java
- hibernate-core/src/test/java/org/hibernate/orm/test/propertyref/basic/Address.java
- hibernate-core/src/test/java/org/hibernate/orm/test/propertyref/basic/Group.java
- hibernate-core/src/test/java/org/hibernate/orm/test/propertyref/basic/Person.hbm.xml
- hibernate-core/src/test/java/org/hibernate/orm/test/propertyref/basic/Person.java
- hibernate-core/src/test/java/org/hibernate/orm/test/propertyref/basic/PropertyRefTest.java
> Fix resolving collection key when creating suffixed fetch builders

- gradle/libraries.gradle
- https://hibernate.atlassian.net/browse/HHH-14852
> HHH-14852 Upgrade GraalVM to version 21.2.0

- hibernate-core/src/main/java/org/hibernate/dialect/Oracle12cDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/pagination/LimitHandler.java
- hibernate-core/src/main/java/org/hibernate/dialect/pagination/Oracle12LimitHandler.java
- hibernate-core/src/main/java/org/hibernate/loader/Loader.java
- hibernate-core/src/main/java/org/hibernate/loader/plan/exec/internal/AbstractLoadPlanBasedLoader.java
- hibernate-core/src/test/java/org/hibernate/dialect/Oracle12LimitHandlerTest.java
- hibernate-core/src/test/java/org/hibernate/test/pagination/OraclePaginationTest.java
- hibernate-core/src/test/java/org/hibernate/test/pagination/OraclePaginationWithLocksTest.java
https://hibernate.atlassian.net/browse/HHH-14624
https://hibernate.atlassian.net/browse/HHH-14649
5.3 branch.
> HHH-14624 HHH-14649 Oracle limit handler (5.3)

- hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
I added support for Geometry to the resolveSqlTypeDescriptor() methods for consistency.
> Resolve to SqlTypes.GEOMETRY for Postgresql/CockroachDB

- hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- https://hibernate.atlassian.net/browse/HHH-14903
> HHH-14903 The new getConfiguredJdbcBatchSize method optimisation should apply to StatelessSession as well

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/AbstractDomainPath.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/DomainPathContinuation.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/FkDomainPathContinuation.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/ordering/ast/PluralAttributePath.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/OrderByEmbeddableToOneTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/embeddable/OrderByEmbeddableX2Test.java
With this pull request I tried to address the case of the test I added here: OrderByEmbeddableToOneTest
> Order-by nested embedded + to-one fk

- hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java
- hibernate-core/src/main/java/org/hibernate/cfg/CopyIdentifierComponentSecondPass.java
- hibernate-core/src/test/java/org/hibernate/test/idclass/IdClassForNestedIdWithAssociationTest.java
https://hibernate.atlassian.net/browse/HHH-14918
The most obvious solution seems to fix the problem; let's see if it doesn't break another test...
> HHH-14918 Key-to-one to id-class entity with key-to-one doesn't work anymore

- hibernate-core/src/main/java/org/hibernate/query/spi/QueryEngine.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/NodeBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/AbstractSqmExpression.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/AbstractNegatableSqmPredicate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/AbstractSqmPredicate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmBetweenPredicate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmBooleanExpressionPredicate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmComparisonPredicate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmEmptinessPredicate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmExistsPredicate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmInListPredicate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmInSubQueryPredicate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmLikePredicate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmMemberOfPredicate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmNegatedPredicate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmNullnessPredicate.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/LocateTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/MultiSelectTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/criteria/NegationTests.java
The JPA TCK tests expect very specific things regarding a negated predicate node
> The JPA TCK tests expect very specific things regarding a negated predicate node

- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/QueryStructure.java
- hibernate-core/src/test/java/org/hibernate/query/criteria/internal/hhh14916/Author.java
- hibernate-core/src/test/java/org/hibernate/query/criteria/internal/hhh14916/Book.java
- hibernate-core/src/test/java/org/hibernate/query/criteria/internal/hhh14916/Chapter.java
- hibernate-core/src/test/java/org/hibernate/query/criteria/internal/hhh14916/HHH14916Test.java
- Created a jira issue [HHH-14916](https://hibernate.atlassian.net/browse/HHH-14916).
- Created a [post ](https://discourse.hibernate.org/t/hibernate-orm-joins-on-fetch-not-working/5820) in dicsourse hibernate.
- Written regenerating [test case in **hibernate-test-case-templates**](https://github.com/ratulSharker/hibernate-test-case-templates).
- Inside `QueryStructure.renderFetches` if the fetch implements `Form` interface, then called `renderJoins` function.
- Written test cases for the Fix mentioned in [HHH-14916](https://hibernate.atlassian.net/browse/HHH-14916).
> Hhh 14916 join on fetch not working issue

- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
- hibernate-core/src/main/java/org/hibernate/boot/SessionFactoryBuilder.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/JdbcCoordinatorImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/spi/JdbcCoordinator.java
- hibernate-core/src/main/java/org/hibernate/id/enhanced/OptimizerFactory.java
- hibernate-core/src/main/java/org/hibernate/internal/JdbcSessionContextImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/log/DeprecationLogger.java
- hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java
- hibernate-core/src/main/java/org/hibernate/resource/jdbc/spi/JdbcSessionContext.java
- hibernate-core/src/main/java/org/hibernate/resource/transaction/spi/TransactionCoordinatorBuilder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/connections/AggressiveReleaseTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/connections/BasicConnectionProviderTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/connections/SuppliedConnectionTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/id/enhanced/SequenceStyleConfigUnitTest.java
- hibernate-core/src/test/java/org/hibernate/test/multitenancy/ConfigurationValidationTest.java
- hibernate-core/src/test/java/org/hibernate/test/tm/CMTTest.java
> Remove deprecated properties from AvailableSettings

- documentation/src/main/asciidoc/userguide/Bibliography.adoc
- documentation/src/main/asciidoc/userguide/chapters/domain/basic_types.adoc
- documentation/src/main/asciidoc/userguide/chapters/domain/naming.adoc
- documentation/src/main/asciidoc/userguide/chapters/osgi/OSGi.adoc
- documentation/src/main/style/asciidoctor/js/toc.js
- documentation/src/test/java/org/hibernate/userguide/mapping/basic/BitSetUserType.java
https://hibernate.atlassian.net/browse/HHH-14927
Fixed some obvious defects I've found in user guide along the way. See self-comments for details.
> HHH-14927 bump current hibernate version from 5.5 to 5.6 in user guide

- hibernate-spatial/src/test/java/org/hibernate/spatial/integration/StoreAndRetrieveTests.java
- hibernate-spatial/src/test/java/org/hibernate/spatial/integration/functions/TestGeometryConstructionWithParameter.java
- hibernate-spatial/src/test/java/org/hibernate/spatial/integration/predicates/PredicateSmokeTest.java
- hibernate-spatial/src/test/java/org/hibernate/spatial/integration/predicates/SpatialPredicatesTest.java
- hibernate-spatial/src/test/java/org/hibernate/spatial/testing/SpatialSessionFactoryAware.java
- hibernate-spatial/src/test/java/org/hibernate/spatial/testing/SpatialTestBase.java
- hibernate-spatial/src/test/java/org/hibernate/spatial/testing/dialects/PredicateRegexes.java
- Fixes flaky PredicateSmokeTest
- adds test for  intersects predicate
> HHH-14808 Fix PredicateSmokeTest

- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/temporals/ProposedGeneratedTests.java
This one was failing for me.. fixing.
> Improve reliability of ProposedGeneratedTests

- hibernate-core/src/main/java/org/hibernate/query/internal/QueryInterpretationCacheStandardImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/DomainParameterXref.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/sqm/ConcurrentQueriesByIdsTest.java
> Wip/6.0 Support concurrent queries having the same query text

- hibernate-core/src/main/java/org/hibernate/query/criteria/HibernateCriteriaBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/CriteriaBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/CriteriaQueryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/OrderImpl.java
- hibernate-core/src/test/java/org/hibernate/query/criteria/internal/NullPrecedenceTest.java
https://hibernate.atlassian.net/browse/HHH-14897
> HHH-14897 Allow ordering with nulls first/last in JPA Criteria

- build.gradle
two very minor improvements to the build
> Build cleanup

- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
- Under Appendix > Configurations > Bootstrap properties
- hibernate.metadata_builder_contributor
> HHH-14956 Fix link to MetadataBuilderContributor javadocs

- docker_db.sh
- gradle/libraries.gradle
- https://hibernate.atlassian.net/browse/HHH-14938
> HHH-14938 Upgrade to MySQL Connector/J 8.0.27

- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
- hibernate-core/src/test/java/org/hibernate/orm/test/lob/PostgreSqlLobStringTest.java
https://hibernate.atlassian.net/browse/HHH-14211
> HHH-14211 Switch to using oid for CLOB in PostgreSQL to avoid losing data after vacuumlo

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
changed the wrong variable name. Modify `inserBatchKey` to `insertBatchKey`
> Polishing: fix wrong variable name

- hibernate-core/src/main/java/org/hibernate/annotations/AttributeBinderType.java
- hibernate-core/src/main/java/org/hibernate/tuple/AttributeBinder.java
> improve the javadoc for AttributeBinder+AttributedBinderType

- hibernate-core/src/main/java/org/hibernate/Session.java
- hibernate-core/src/main/java/org/hibernate/StatelessSession.java
- hibernate-core/src/main/java/org/hibernate/context/internal/ThreadLocalSessionContext.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/connections/ConnectionManagementTestCase.java
- hibernate-core/src/test/java/org/hibernate/orm/test/connections/SuppliedConnectionTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ejb3configuration/EntityManagerFactorySerializationTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ejb3configuration/EntityManagerSerializationTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/proxy/ProxyTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/unionsubclass/UnionSubclassTest.java
This nasty stuff has stuck around for far too long.
> finally get rid of Session.connection()/disconnect()/reconnect()

- hibernate-core/src/main/java/org/hibernate/Session.java
- hibernate-core/src/main/java/org/hibernate/SharedSessionContract.java
- hibernate-core/src/main/java/org/hibernate/StatelessSession.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SessionImplementor.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SharedSessionContractImplementor.java
- hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
- hibernate-core/src/main/java/org/hibernate/query/NativeQuery.java
- hibernate-core/src/main/java/org/hibernate/query/Query.java
- hibernate-core/src/main/java/org/hibernate/query/QueryProducer.java
- hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQuery.java
- hibernate-core/src/main/java/org/hibernate/query/spi/QueryProducerImplementor.java
- hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sql/spi/NativeQueryImplementor.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
This is a general cleanup of the Session + Query hierarchies, focussing on stuff the IDE was complaining about..
> fix some warnings and clean up some typing issues

- databases/cockroachdb/resources/hibernate.properties
- databases/derby/resources/hibernate.properties
- databases/mariadb/resources/hibernate.properties
- databases/mssqlserver/resources/hibernate.properties
- databases/mysql/matrix.gradle
- databases/mysql/resources/hibernate.properties
- databases/oracle/resources/hibernate.properties
- databases/pgsql/resources/hibernate.properties
- hibernate-testing/src/main/java/org/hibernate/testing/cleaner/PostgreSQLDatabaseCleaner.java
- hibernate-testing/src/main/java/org/hibernate/testing/junit4/BaseUnitTestCase.java
- hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/DialectContext.java
This fixes some problems that prevented the test suite from running locally.
> Fix test matrix

- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/Discount.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/onetomany/embeddedid/OneToManyCompositeKeyTest.java
it is not the case that ln(10) = log_2(10)
@beikov
> fix broken float type precision conversion

- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/entity/BasicHibernateAnnotationsTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/binding/annotations/attributeOverrides/PluralEmbeddedOverrideTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bootstrap/binding/annotations/attributeOverrides/TablePerClassOverrideTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/entitygraph/ast/LoadPlanBuilderTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/basic/BasicCriteriaUsageTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/CachedQueryTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiLoadTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/size/ManyToManySizeTest2.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/sqm/exec/DiscriminatorTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/sql/exec/manytoone/EntityWithLazyManyToOneSelfReferenceTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/sql/exec/manytoone/EntityWithManyToOneSelfReferenceTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/sql/hand/custom/db2/DB2CustomSQLTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/sql/hand/custom/derby/DerbyCustomSQLTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/sql/hand/custom/mysql/MySQLCustomSQLTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/sql/hand/custom/oracle/OracleCustomSQLTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/sql/hand/custom/sqlserver/SQLServerCustomSQLTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/sql/hand/custom/sybase/SybaseCustomSQLTest.java
to make easier to retrieve them
> @FailureExpected annotation added to tests in orm 6 substituted with @NotImplementedYet

- gradle/libraries.gradle
- https://hibernate.atlassian.net/browse/HHH-14979
-  https://logging.apache.org/log4j/2.x/changes-report.html#a2.16.0
> HHH-14979 Upgrade to Log4J 2 2.16.0

- gradle/libraries.gradle
> 54 log4jupdate

- gradle/libraries.gradle
> 55 log4jupdate

- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdLoaderStandard.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoaderStandard.java
- hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiLoadSecondLlvCacheTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/loading/multiLoad/MultiLoadSingleEventTest.java
Actually this is my attempt to support the case.
I don't know if it is correct, since I don't know too many details of Hibernate ORM 6 code base.
I'm here to fix it!
> Support multiloading of single item

- documentation/src/main/asciidoc/userguide/chapters/envers/Envers.adoc
- hibernate-envers/src/main/java/org/hibernate/envers/Audited.java
- hibernate-envers/src/main/java/org/hibernate/envers/RelationTargetNotFoundAction.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/Configuration.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/EnversSettings.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/ClassesAuditingData.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/ToOneRelationMetadataGenerator.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/AuditedPropertiesReader.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/PropertyAuditingData.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/relation/ToOneIdMapper.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/basic/RelationTargetNotFoundConfigTest.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/basic/RelationTargetNotFoundLegacyTest.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/basic/RelationTargetNotFoundTest.java
https://hibernate.atlassian.net/browse/HHH-8051
This PR supersedes PR #3245 to target `main` with ORM 6.  All review comments in prior PR has been included.
> HHH-8051 Gracefully handle not-found to-one associations

- hibernate-envers/src/main/java/org/hibernate/envers/internal/tools/query/Parameters.java
- hibernate-envers/src/main/java/org/hibernate/envers/internal/tools/query/QueryBuilder.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/AuditEntity.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/AuditFunction.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/AuditProperty.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/internal/FunctionFunctionAuditExpression.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/internal/FunctionPropertyAuditExpression.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/internal/PropertyFunctionAuditExpression.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/internal/SimpleFunctionAuditExpression.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/AbstractAuditQuery.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/AuditAssociationQueryImpl.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/projection/AuditProjection.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/projection/internal/EntityAuditProjection.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/projection/internal/PropertyAuditProjection.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/query/AuditFunctionQueryTest.java
https://hibernate.atlassian.net/browse/HHH-11452
This PR supersedes PR #1849 as the code has been rebased against ORM 6 on the `main` branch.
> HHH-11452 Extended audit query API to specify the use of scalar functions

- hibernate-envers/src/main/java/org/hibernate/envers/internal/tools/query/QueryBuilder.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/AbstractAuditQuery.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/AuditAssociationQueryImpl.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/internal/impl/RevisionsOfEntityQuery.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/order/AuditOrder.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/order/NullPrecedence.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/order/internal/PropertyAuditOrder.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/query/NullPrecedenceTest.java
https://hibernate.atlassian.net/browse/HHH-14981
> HHH-14981 Support null precedence with Envers Query API

- hibernate-envers/src/main/java/org/hibernate/envers/internal/tools/query/Parameters.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/AuditEntity.java
- hibernate-envers/src/main/java/org/hibernate/envers/query/criteria/internal/EntityTypeAuditExpression.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/query/EntityTypeQueryTest.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/query/EntityTypeQueryTest.java
https://hibernate.atlassian.net/browse/HHH-11573
This PR supersedes #1850 and is based on `main` branch for ORM 6.
> HHH-11573 Support restricting an alias to specified type

- hibernate-envers/src/main/java/org/hibernate/envers/internal/entities/mapper/id/VirtualEntitySingleIdMapper.java
- hibernate-envers/src/test/java/org/hibernate/envers/test/integration/ids/idclass/ManyToOneNotAuditedMulIdTest.java
- hibernate-envers/src/test/java/org/hibernate/orm/test/envers/integration/ids/idclass/ManyToOneNotAuditedMulIdTest.java
https://hibernate.atlassian.net/browse/HHH-14280
This PR supersedes PR #3612 and targets the `main` branch.
> HHH-14280 Fix queries using @IdClass and a non-audited entity relation

- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/EnumJavaTypeDescriptor.java
> treat integral types as equivalent for purposes of schema validation

- documentation/src/main/asciidoc/userguide/chapters/envers/Envers.adoc
- hibernate-envers/src/main/java/org/hibernate/envers/CollectionAuditTable.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/AbstractMetadataGenerator.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/MiddleTableCollectionMetadataGenerator.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/AuditedPropertiesReader.java
- hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/PropertyAuditingData.java
https://hibernate.atlassian.net/browse/HHH-11595
> HHH-11595 Introduce `CollectionAuditTable` support

- Jenkinsfile
- databases/db2/matrix.gradle
- docker_db.sh
- gradle/libraries.gradle
Also setting environment variable `PERSISTENT_HOME=false` as it helps a little with startup times.
> Upgrade to DB2 container image ibmcom/db2:11.5.7.0

- gradle/libraries.gradle
- https://hibernate.atlassian.net/browse/HHH-14995
- https://hibernate.atlassian.net/browse/HHH-14996
- https://hibernate.atlassian.net/browse/HHH-14997
- https://hibernate.atlassian.net/browse/HHH-14998
- https://hibernate.atlassian.net/browse/HHH-14999
> Upgrade interesting dependencies

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddableMappingTypeImpl.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/IdClassEmbeddable.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationProcess.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/VirtualIdEmbeddable.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
the aim is to make a little easier to spot what went wrong when the `MappingModelCreationProcess` does not complete
> Log first Exception when MappingModelCreationProcess cannot complete

- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/ConfigurationTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/MappedSuperclassInheritanceTest.java
> Fixed and moved MappedSuperclassInheritanceTest to orm.test

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/entity/internal/EntityDelayedFetchInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/uniquekey/NaturalIdCachingTest.java
wip/6.0 remaining tests: Try to fix stuff for `NaturalIdCachingTest.java`
> Set correct key type if !referenceToPrimaryKey

- hibernate-core/src/main/java/org/hibernate/Session.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SessionDelegatorBaseImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/proxy/ProxyTest.java
This is a useful little method that Hibernate Reactive already has.
> add Session.getReference()

- hibernate-core/src/main/java/org/hibernate/SessionFactory.java
- hibernate-core/src/main/java/org/hibernate/engine/spi/SessionFactoryDelegatingImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java
- hibernate-core/src/main/java/org/hibernate/stat/SessionStatistics.java
- hibernate-core/src/main/java/org/hibernate/stat/internal/SessionStatisticsImpl.java
Cleanups to Session-associated interfaces.
> Miscellaneous cleanups

- hibernate-core/src/main/java/org/hibernate/StatelessSession.java
- hibernate-core/src/main/java/org/hibernate/boot/SessionFactoryBuilder.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryBuilder.java
- hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/fetch/EnhancedFetchTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/fetch/FetchTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/proxy/LazyToOnesProxyWithSubclassesStatelessTest.java
Draft of a `fetch()` operation for `StatelessSession` (https://hibernate.atlassian.net/browse/HHH-15001)
> StatelessSession.fetch()

- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AllowableParameterType.java
- hibernate-core/src/main/java/org/hibernate/query/Query.java
mainly the `setParameter()` and `setParemeterList()` methods
> more cleanups to the Javadoc for Query

- hibernate-core/src/main/java/org/hibernate/procedure/spi/ProcedureCallImplementor.java
- hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterBindingImpl.java
- hibernate-core/src/main/java/org/hibernate/query/spi/QueryParameterBinding.java
> minor fixes to generic types in QueryParameterBinding

- hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
This code was resulting in warnings in IntelliJ.
> remove some obsolete code from AnnotationBinder

- hibernate-core/src/main/java/org/hibernate/Session.java
Javac doesn't mind, but IntelliJ seems to get confused.
> add some overrides that should not be necessary

- hibernate-core/src/main/java/org/hibernate/annotations/ColumnDefault.java
- hibernate-core/src/main/java/org/hibernate/annotations/GeneratedColumn.java
- hibernate-core/src/main/java/org/hibernate/cfg/Ejb3Column.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/generated/always/GeneratedAlwaysTest.java
after all that, we decided it wasn't necessary :-D
> remove name() from @ColumnDefault + @GeneratedColumn

- hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- simplify two rules that were unnecessarily flexible
- remove useless parens
- rename some rules for readability
> minor cleanups to the grammar

- documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc
- documentation/src/main/java/org/hibernate/userguide/model/Account.java
- documentation/src/main/java/org/hibernate/userguide/model/Call.java
- documentation/src/main/java/org/hibernate/userguide/model/CreditCardPayment.java
- documentation/src/main/java/org/hibernate/userguide/model/Payment.java
- documentation/src/test/java/org/hibernate/userguide/batch/BatchTest.java
- documentation/src/test/java/org/hibernate/userguide/criteria/CriteriaTest.java
- documentation/src/test/java/org/hibernate/userguide/hql/HQLTest.java
- documentation/src/test/java/org/hibernate/userguide/sql/SQLTest.java
> add examples with treat()

- documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc
- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
and add some missing functions to docs
> promote log10() to standard function status

- documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc
- documentation/src/test/java/org/hibernate/userguide/hql/HQLTest.java
> enum + Java constant examples

- documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc
> undocument a fixed limitation

- documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc
- documentation/src/main/style/asciidoctor/css/hibernate-layout.css
- documentation/src/test/java/org/hibernate/userguide/hql/HQLTest.java
and a bit of a cleaner-looking css
> better explanation of query language concepts

- hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/ILikeTest.java
> allow parameter in like escape

- documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc
- documentation/src/test/java/org/hibernate/userguide/hql/HQLTest.java
> better documentation for limit and friends

- hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
> rename some grammar rules

- documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc
- documentation/src/main/asciidoc/userguide/chapters/query/hql/extras/group_by_item_bnf.txt
- documentation/src/main/asciidoc/userguide/chapters/query/hql/extras/limit_offset_bnf.txt
- documentation/src/main/asciidoc/userguide/chapters/query/hql/extras/order_by_item_bnf.txt
- documentation/src/main/asciidoc/userguide/chapters/query/hql/extras/predicate_in_bnf.txt
- documentation/src/main/asciidoc/userguide/chapters/query/hql/extras/predicate_like_bnf.txt
- documentation/src/main/asciidoc/userguide/chapters/query/hql/extras/searched_case_bnf.txt
- documentation/src/main/asciidoc/userguide/chapters/query/hql/extras/select_item_bnf.txt
- documentation/src/main/asciidoc/userguide/chapters/query/hql/extras/simple_case_bnf.txt
- documentation/src/main/asciidoc/userguide/chapters/query/hql/extras/statement_delete_bnf.txt
- documentation/src/main/asciidoc/userguide/chapters/query/hql/extras/statement_insert_bnf.txt
- documentation/src/main/asciidoc/userguide/chapters/query/hql/extras/statement_select_bnf.txt
- documentation/src/main/asciidoc/userguide/chapters/query/hql/extras/statement_update_bnf.txt
- documentation/src/test/java/org/hibernate/userguide/hql/HQLTest.java
And a new example for `insert`
> More readable BNF

- hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
Cherry picked from 1706141ffc154c1b61e304445a603ebf9a3e0a2e
> HHH-15002 H2 supports 'true' and 'false' boolean literals

- documentation/src/main/asciidoc/userguide/chapters/query/hql/QueryLanguage.adoc
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/query/spi/QueryEngine.java
- hibernate-core/src/test/resources/log4j2.properties
...and just make it a log category.
Really unclear why I didn't do it that way in the first place.
> remove hibernate.dialect.show_hql_functions 

- hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/DerbyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/NormalizingIdentifierHelperImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/spi/IdentifierHelperBuilder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/quote/QuoteTest.java
> Automatically quote initial _ identifiers on the dbs which require it

- hibernate-core/src/main/java/org/hibernate/query/hql/internal/BasicDotIdentifierConsumer.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/AbstractSqmPath.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/domain/SqmBasicValuedSimplePath.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/loader/LoaderWithInvalidQueryTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/hql/JoinOnClauseTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/MappedSuperclassInheritanceTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/criteria/paths/AbstractPathImplTest.java
Make the messages and exception types a bit more consistent.
> cosmetic improvements to HQL error reporting

- hibernate-core/src/main/java/org/hibernate/query/hql/internal/QualifiedJoinPathConsumer.java
- hibernate-core/src/main/java/org/hibernate/query/hql/internal/SemanticQueryBuilder.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/UnknownEntityException.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/ConfigurationTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/loader/LoaderWithInvalidQueryTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/MappedSuperclassInheritanceTest.java
> more cosmetic improvements to HQL error reporting

- hibernate-core/src/main/java/org/hibernate/IdentifierLoadAccess.java
- hibernate-core/src/main/java/org/hibernate/LockOptions.java
- hibernate-core/src/main/java/org/hibernate/loader/access/IdentifierLoadAccessImpl.java
Adding this to the other `XxxxLoadAccess` interfaces is much harder, but this one is easy.
> add IdentifierLoadAccess.withReadOnly()

- hibernate-core/src/main/java/org/hibernate/annotations/Comment.java
- hibernate-core/src/main/java/org/hibernate/annotations/Table.java
- hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
- hibernate-core/src/main/java/org/hibernate/cfg/ColumnsBuilder.java
- hibernate-core/src/main/java/org/hibernate/cfg/annotations/EntityBinder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/comment/CommentTest.java
Yes, you can do it with the `@Table` annotation but this is nicer, no good reason to not allow it.
> allow @Comment to apply at the class level

- gradle/libraries.gradle
- hibernate-core/src/main/java/org/hibernate/dialect/OracleTypesHelper.java
- https://hibernate.atlassian.net/browse/HHH-14998
- https://hibernate.atlassian.net/browse/HHH-15018
> Backporting two GraalVM related micro improvements

- gradle/libraries.gradle
- https://hibernate.atlassian.net/browse/HHH-15000
> HHH-15000 Upgrade to Hibernate Commons Annotations 6.0.0.Beta1

- gradle/libraries.gradle
https://hibernate.atlassian.net/browse/HHH-15024
> HHH-15024 Upgrade to Jandex 2.4.2.Final

- gradle/base-information.gradle
- gradle/java-module.gradle
- gradle/libraries.gradle
- https://hibernate.atlassian.net/browse/HHH-15026
> HHH-15026 Upgrade to Log4J 2.17.1

- gradle/libraries.gradle
https://hibernate.atlassian.net/browse/HHH-15028
> HHH-15028 Upgrade to JBoss Logging 3.4.3.Final

- hibernate-core/src/main/java/org/hibernate/engine/jndi/JndiException.java
- hibernate-core/src/main/java/org/hibernate/engine/jndi/internal/JndiServiceImpl.java
- hibernate-core/src/main/java/org/hibernate/engine/jndi/internal/JndiServiceInitiator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/service/internal/JndiServiceImplTest.java
https://hibernate.atlassian.net/browse/HHH-15033
> JNDI hardening

- hibernate-core/src/main/java/org/hibernate/engine/jndi/JndiException.java
- hibernate-core/src/main/java/org/hibernate/engine/jndi/internal/JndiServiceImpl.java
it's missing the test, otherwise the same as HHH-15033 on `main`.
> Backport of HHH-15033 to 5.6

- hibernate-core/src/main/java/org/hibernate/hql/spi/id/MultiTableBulkIdStrategy.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/spi/Exporter.java
https://hibernate.atlassian.net/browse/HHH-15032
> HHH-15032 Fix backwards incompatible SPI change that happened in 5.6.2 due to introducing SqlStringGenerationContext

- gradle/libraries.gradle
- https://hibernate.atlassian.net/browse/HHH-15040
As requested by @gavinking , I triggered a release of HCANN and labelled it `6.0.0.CR1` to make this improvement available to ORM core:
- https://hibernate.atlassian.net/browse/HCANN-120
> HHH-15040 Upgrade to Hibernate Commons Annotations 6.0.0.CR1

- hibernate-core/src/main/java/org/hibernate/type/OneToOneType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/onetoone/cache/OneToOneCacheEnableSelectingTest.java
https://hibernate.atlassian.net/browse/HHH-15044
> HHH-15044 Revert HHH-14826 fix because the provided test was wrong

- hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/DB2Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/DerbyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/HSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MariaDBDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SpannerDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/TiDBDialect.java
and squash a couple of warnings
> clean up very old Dialect javadoc

- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
- documentation/src/main/asciidoc/userguide/chapters/pc/PersistenceContext.adoc
- etc/hibernate.properties
- etc/hibernate.properties.template
- hibernate-core/src/main/java/org/hibernate/boot/SessionFactoryBuilder.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/BootstrapContextImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryBuilder.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/cfg/ExternalSessionFactoryConfig.java
- hibernate-core/src/main/java/org/hibernate/cfg/Settings.java
- hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
- hibernate-core/src/main/java/org/hibernate/internal/ExceptionConverterImpl.java
- hibernate-core/src/main/java/org/hibernate/internal/log/DeprecationLogger.java
- hibernate-core/src/test/java/org/hibernate/orm/test/exceptionhandling/BaseExceptionHandlingTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/exceptionhandling/ConstraintViolationExceptionHandlingTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/exceptionhandling/IdentifierGenerationExceptionHandlingTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/exceptionhandling/QueryExceptionHandlingTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/exceptionhandling/StaleObjectStateExceptionHandlingTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/exceptionhandling/TransactionExceptionHandlingTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/exceptionhandling/TransientObjectExceptionHandlingTest.java
the following are gone:
```
hibernate.ejb.resource_scanner
hibernate.query.substitutions
hibernate.jdbc.sql_exception_converter
hibernate.native_exception_handling_51_compliance
hibernate.legacy_limit_handler
hibernate.jdbc.wrap_result_sets
```
> remove some legacy config properties

- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cache/CollectionCacheEvictionTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cache/CollectionCacheEvictionWithoutMappedByTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cache/LockModeTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cache/ManyToManyCollectionCacheEvictionTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cache/RefreshUpdatedDataTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/ondemandload/cache/CacheLazyLoadNoTransTest.java
> remove hibernate.cache.provider_configuration_file_resource_path

- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
- etc/hibernate.properties
- etc/hibernate.properties.template
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/CUBRIDDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/MimerSQLDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/TeradataDialect.java
- hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/TimesTenDialect.java
- hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BasicProxyFactoryImpl.java
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/cfg/Environment.java
- hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
- hibernate-core/src/main/java/org/hibernate/internal/CoreMessageLogger.java
- hibernate-core/src/main/java/org/hibernate/internal/FastSessionServices.java
- hibernate-core/src/main/java/org/hibernate/internal/log/UnsupportedLogger.java
- hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/ByteBuddyProxyHelper.java
- hibernate-core/src/test/bundles/templates/cfgxmlpar/org/hibernate/orm/test/jpa/pack/cfgxmlpar/hibernate.cfg.xml
- hibernate-core/src/test/bundles/templates/explicitpar/META-INF/persistence.xml
- hibernate-core/src/test/bundles/templates/explicitpar2/META-INF/persistence.xml
- hibernate-core/src/test/java/org/hibernate/orm/test/lob/JpaLargeBlobTest.java
- hibernate-core/src/test/resources/org/hibernate/jpa/test/hibernate.cfg.xml
This should be handled by the `Dialect`s.
> remove hibernate.jdbc.use_streams_for_binary config property

- hibernate-core/src/main/java/org/hibernate/engine/spi/SessionFactoryDelegatingImpl.java
> remove some operations of SessionFactoryDelegatingImpl

- hibernate-core/src/main/java/org/hibernate/boot/MetadataBuilder.java
- hibernate-core/src/main/java/org/hibernate/boot/SessionFactoryBuilder.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingMetadataBuilderImplementor.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryBuilder.java
- hibernate-core/src/main/java/org/hibernate/dialect/Database.java
- hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SybaseASEDialect.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/dialect/spi/DatabaseMetaDataDialectResolutionInfoAdapter.java
- hibernate-core/src/main/java/org/hibernate/engine/jdbc/dialect/spi/DialectResolutionInfo.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EmbeddedAttributeMapping.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/ColumnReference.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/Expression.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/SqlSelectionExpression.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/from/DelegatingTableGroup.java
- hibernate-core/src/test/java/org/hibernate/orm/test/id/usertype/PostgreSQLMultipleTypesOtherContributorTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/id/usertype/inet/PostgreSQLInetTypesOtherContributorTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/id/usertype/inet/PostgreSQLInetTypesOtherTest.java
it's better to do this stuff in a more typesafe way.
> remove unwrap() methods that aren't to do with proxying

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/UnionSubclassEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/join/JoinTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetoone/OneToOneTest.java
This is a potential performance gain.
> cleanup obsolete code and data structures in EntityPersisters

- hibernate-core/src/main/java/org/hibernate/internal/util/collections/ArrayHelper.java
- hibernate-core/src/main/java/org/hibernate/metadata/ClassMetadata.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/AbstractCollectionPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/collection/CompositeElementPropertyMapping.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractPropertyMapping.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/Queryable.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/UnionSubclassEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardTableExporter.java
- hibernate-core/src/main/java/org/hibernate/type/BasicType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/inheritance/singletable/DuplicatedDiscriminatorValueTest.java
use `Metadata` instead of deprecated `Mapping` (I'm not sure that's really an improvement)
> clean up some warnings

- hibernate-core/src/main/java/org/hibernate/boot/model/TypeDefinition.java
- hibernate-core/src/main/java/org/hibernate/id/factory/internal/StandardIdentifierGeneratorFactory.java
- hibernate-core/src/main/java/org/hibernate/resource/beans/internal/Helper.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cdi/lifecycle/ExtendedBeanManagerNotAvailableDuringTypeResolutionTest.java
https://hibernate.atlassian.net/browse/HHH-15068
> HHH-15068 "CDI BeanManager not (yet) ready to use" when refferring to a user type by name and using an ExtendedBeanManager

- Jenkinsfile
See https://issues.jenkins.io/browse/JENKINS-43353?focusedCommentId=414847&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-414847
> Use a simpler solution to limit concurrent Jenkins builds

- hibernate-core/src/main/java/org/hibernate/boot/model/relational/internal/SqlStringGenerationContextImpl.java
- hibernate-core/src/main/java/org/hibernate/dialect/unique/UniqueDelegate.java
- hibernate-core/src/main/java/org/hibernate/id/BulkInsertionCapableIdentifierGenerator.java
- hibernate-core/src/main/java/org/hibernate/id/CompositeNestedGeneratedValueGenerator.java
- hibernate-core/src/main/java/org/hibernate/id/MultipleHiLoPerTableGenerator.java
- hibernate-core/src/main/java/org/hibernate/id/PersistentIdentifierGenerator.java
- hibernate-core/src/main/java/org/hibernate/id/SequenceGenerator.java
- hibernate-core/src/main/java/org/hibernate/id/enhanced/DatabaseStructure.java
- hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStructure.java
- hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStyleGenerator.java
- hibernate-core/src/main/java/org/hibernate/id/enhanced/TableGenerator.java
- hibernate-core/src/main/java/org/hibernate/id/enhanced/TableStructure.java
- hibernate-core/src/main/java/org/hibernate/id/insert/InsertGeneratedIdentifierDelegate.java
- hibernate-core/src/main/java/org/hibernate/mapping/RelationalModel.java
https://hibernate.atlassian.net/browse/HHH-15069
I checked locally and this seems to fix https://github.com/liquibase/liquibase/issues/2456. I don't know if *all* these changes are necessary, but they don't hurt.
> HHH-15069 Backwards-incompatible changes in SequenceStyleGenerator (and others) following default_schema changes

- hibernate-core/src/main/java/org/hibernate/dialect/DerbyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/FunctionTests.java
Fixes round() function on Postgres.
> test for round()ing double

- documentation/src/test/java/org/hibernate/userguide/hql/HQLTest.java
- hibernate-core/src/main/java/org/hibernate/dialect/H2SqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/UnionSubclassEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/function/SelfRenderingSqmAggregateFunction.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/FakeSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/SqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/ColumnReference.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/ql/TreatKeywordTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/treat/HqlTreatTest.java
This test demonstrates the problem.
> test showing 'join treat' broken for @OneToMany

- hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/ArrayInitializer.java
- hibernate-core/src/main/java/org/hibernate/sql/results/graph/collection/internal/ListInitializer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/ops/OneToManyMappedByCascadeDeleteTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/ops/OneToManyMappedByOrderColumnTest.java
See https://hibernate.atlassian.net/browse/HHH-15054
> HHH-15054 Reproducer for cascade-delete NPE on entity with @OneToMany(mappedBy = ...)

- hibernate-core/src/main/java/org/hibernate/engine/spi/SubselectFetch.java
- hibernate-core/src/main/java/org/hibernate/internal/AbstractSharedSessionContract.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderBatchKey.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderSingleKey.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/CollectionLoaderSubSelectFetch.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiIdLoaderStandard.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/MultiNaturalIdLoadingBatcher.java
- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/SingleIdEntityLoaderDynamicBatch.java
- hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java
- hibernate-core/src/main/java/org/hibernate/mapping/ToOne.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EntityCollectionPart.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/MappingModelCreationHelper.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
- hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterNamedImpl.java
- hibernate-core/src/main/java/org/hibernate/query/internal/QueryParameterPositionalImpl.java
- hibernate-core/src/main/java/org/hibernate/query/results/implicit/ImplicitFetchBuilderEntity.java
- hibernate-core/src/main/java/org/hibernate/query/spi/AbstractCommonQueryContract.java
- hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/ConcreteSqmSelectQueryPlan.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/subselect/SubselectFetchCollectionFromBatchTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/propertyref/partial/Mapping.hbm.xml
- hibernate-core/src/test/java/org/hibernate/orm/test/propertyref/partial/PartialComponentPropertyRefTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/NativeQueryScrollableResultsTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/resulttransformer/ResultTransformerTest.java
* Make sure subselect fetch registrations are per navigable path
* Consider the result class for native queries
* Fix issues with nested property references
* Fix list expansion issues for native queries
> Re-enable more tests.

- hibernate-core/src/main/java/org/hibernate/resource/beans/container/internal/JpaCompliantLifecycleStrategy.java
Issue: https://hibernate.atlassian.net/browse/HHH-15084
> HHH-15084 Remove use of BeanManager.createInjectionTarget(AnnotatedType)

- documentation/src/main/asciidoc/userguide/chapters/domain/collections.adoc
- hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuilderImpl.java
- hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/collections/ImplicitListAsListSemanticsTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/collections/ImplicitListDefaultSemanticsTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/collections/semantics/CustomSemanticsTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/onetomany/OneToManyBidirectionalTest.java
- hibernate-envers/src/test/resources/hibernate.properties
- hibernate-testing/src/main/java/org/hibernate/testing/orm/junit/ImplicitListAsListProvider.java
- migration-guide.adoc
https://github.com/hibernate/hibernate-orm/discussions/4539
> Switch back to bag by default for list semantics

- hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/ByteBuddyState.java
- hibernate-core/src/main/java/org/hibernate/proxy/pojo/bytebuddy/ByteBuddyProxyHelper.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/lazy/LazyLoadingAndInheritanceTest.java
https://hibernate.atlassian.net/browse/HHH-15090
> HHH-15090 Access to public field with extended bytecode enhancement returns null for entity lazy-loaded from polymorphic toOne association

- hibernate-core/src/main/antlr/hql-sql.g
- hibernate-core/src/main/antlr/hql.g
- hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/DotNode.java
- hibernate-core/src/test/java/org/hibernate/orm/test/notfound/FkRefTests.java
- add new `{fk}` token for HQL (probably should be a new issue)
> HHH-15060 - Fix handling of associations with @NotFound

- hibernate-core/src/main/java/org/hibernate/id/enhanced/SequenceStyleGenerator.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/SequenceInformationExtractorLegacyImpl.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/SequenceInformationExtractorOracleDatabaseImpl.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/SequenceInformationExtractorTiDBDatabaseImpl.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/extract/internal/SequenceInformationImpl.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/extract/spi/SequenceInformation.java
- hibernate-core/src/main/java/org/hibernate/tool/schema/internal/AbstractSchemaValidator.java
- hibernate-core/src/test/java/org/hibernate/orm/test/dialect/functional/OracleDialectSequenceInformationTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/dialect/functional/OracleSequenceInfoTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/dialect/functional/SequenceInformationTest.java
https://hibernate.atlassian.net/browse/HHH-13694
6.0 version of https://github.com/hibernate/hibernate-orm/pull/3169
> HHH-13694 fix numeric overflow exception for large sequence min values

- hibernate-core/src/main/java/org/hibernate/query/spi/AbstractQueryParameter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/expression/SqmExpression.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmLikePredicate.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/tree/predicate/SqmMemberOfPredicate.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/hql/ParameterTests.java
https://hibernate.atlassian.net/browse/HHH-15071
> HHH-15071 Apply type inference in SQM for like predicate and avoid NPE in query parameters

- hibernate-core-jakarta/hibernate-core-jakarta.gradle
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/UUIDTypeDescriptor.java
- hibernate-core/src/test/java/org/hibernate/test/jpa/convert/UUIDConverterTest.java
- hibernate-envers-jakarta/hibernate-envers-jakarta.gradle
- hibernate-testing-jakarta/hibernate-testing-jakarta.gradle
- tooling/metamodel-generator-jakarta/hibernate-jpamodelgen-jakarta.gradle
https://hibernate.atlassian.net/browse/HHH-14817
https://hibernate.atlassian.net/browse/HHH-15097
> UUID and Jakarta fixes

- hibernate-core/src/main/java/org/hibernate/cache/internal/EnabledCaching.java
- hibernate-core/src/test/java/org/hibernate/test/cache/CacheRegionStatisticsTest.java
https://hibernate.atlassian.net/browse/HHH-15105
> HHH-15105 Fix NPE when access default query cache region statistics

- hibernate-core/src/main/java/org/hibernate/cache/internal/EnabledCaching.java
- hibernate-core/src/test/java/org/hibernate/orm/test/cache/CacheRegionStatisticsTest.java
https://hibernate.atlassian.net/browse/HHH-15105
> HHH-15105 Test and fix for NPE when access default query cache region statistics

- hibernate-core/src/main/java/org/hibernate/hql/spi/id/cte/AbstractCteValuesListBulkIdHandler.java
- hibernate-core/src/main/java/org/hibernate/hql/spi/id/global/GlobalTemporaryTableBulkIdStrategy.java
- hibernate-core/src/main/java/org/hibernate/hql/spi/id/local/LocalTemporaryTableBulkIdStrategy.java
- hibernate-core/src/main/java/org/hibernate/hql/spi/id/persistent/PersistentTableBulkIdStrategy.java
- hibernate-core/src/test/java/org/hibernate/test/inheritance/JoinedInheritanceDeletionTest.java
https://hibernate.atlassian.net/browse/HHH-15115
> HHH-15115 Deleting an entity with Joined inheritance and default schema set is throwing and error

- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/CriteriaUpdateImpl.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/compile/CriteriaCompiler.java
- hibernate-core/src/main/java/org/hibernate/query/criteria/internal/expression/ParameterExpressionImpl.java
- hibernate-core/src/test/java/org/hibernate/jpa/test/query/CriteriaUpdateWithParametersTest.java
https://hibernate.atlassian.net/browse/HHH-15113
> HHH-15113 Exception setting ParameterExpressions on Update Queries

- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/SqmCriteriaNodeBuilder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/query/CriteriaUpdateWithParametersTest.java
https://hibernate.atlassian.net/browse/HHH-15113
> HHH-15113 - Exception setting ParameterExpressions on Update Queries

- gradle/libraries.gradle
https://hibernate.atlassian.net/browse/HHH-15119
- https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.12.8
> HHH-15119 Upgrade to ByteBuddy 1.12.8

- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractPropertyMapping.java
- hibernate-core/src/test/java/org/hibernate/query/GroupByAliasTest.java
- hibernate-core/src/test/java/org/hibernate/test/hql/VirtualKeyManyToOnePropertyPathTest.java
https://hibernate.atlassian.net/browse/HHH-15051
> HHH-15051 Add property mapping for target FK attributes for associations with id classes

- hibernate-core/src/main/java/org/hibernate/loader/ast/internal/LoaderSelectBuilder.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EntityCollectionPart.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/PluralAttributeMappingImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/NoDepthTests.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/SysModule.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/fetch/depth/SysModule2.java
- hibernate-core/src/test/resources/units/many2many/fetch-depth.xml
HHH-14993 - EAGER non-inverse collection throws StackOverflowError if `max_fetch_depth` not set
> HHH-14993 - EAGER non-inverse collection throws StackOverflowError if `max_fetch_depth` not set

- hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteDeleteHandler.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteInsertHandler.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteUpdateHandler.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/JoinedInheritanceDeletionTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/inheritance/JoinedInheritanceWithDefaultSchemaDeletionTest.java
https://hibernate.atlassian.net/browse/HHH-15115
> HHH-15115 Fix PostgreSQL SqmMultiTableMutationStrategy

- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultMergeEventListener.java
- hibernate-core/src/test/java/org/hibernate/orm/test/compositefk/OneToManyEmbeddedIdFKWithOrphanRemovalTest.java
https://hibernate.atlassian.net/browse/HHH-15098
The PR tries to fix the incorrect behaviour when merge is used.
> HHH-15098 - incorrect behavior when updating managed oneToMany collection on entity with naturalId

- hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/onetomany/OneToManyJoinColumnsUniquenessTest.java
https://hibernate.atlassian.net/browse/HHH-15091
> HHH-15091 - EntityManager.persist does not verify the existence of the one side of a many-to-one relationship

- hibernate-core/src/main/java/org/hibernate/internal/util/collections/ArrayHelper.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/JoinedSubclassEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/SingleTableEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/UnionSubclassEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteDeleteHandler.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteInsertHandler.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/cte/CteUpdateHandler.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/mutation/internal/temptable/InsertExecutionDelegate.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/secondarytable/ParentChildWithSameSecondaryTableTest.java
https://hibernate.atlassian.net/browse/HHH-15117
> HHH-15117 ConstraintViolationException is thrown using same @SecondaryTable on two entities

- documentation/src/test/java/org/hibernate/userguide/envers/EntityTypeChangeAuditTest.java
- hibernate-core/src/main/java/org/hibernate/id/enhanced/PooledOptimizer.java
- hibernate-core/src/test/java/org/hibernate/orm/test/id/enhanced/OptimizerUnitTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/idgen/enhanced/forcedtable/PooledForcedTableSequenceTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/idgen/enhanced/sequence/PooledSequenceTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/idgen/enhanced/table/PooledTableTest.java
https://hibernate.atlassian.net/browse/HHH-15118
> HHH-15118 Fix duplicate ids with PooledOptimizer when sequence value is initialValue

- hibernate-core/src/main/java/org/hibernate/property/access/internal/PropertyAccessStrategyMapImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/property/PropertyAccessStrategyMapTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/sql/hand/query/NativeSQLQueriesTest.java
https://hibernate.atlassian.net/browse/HHH-14487
> HHH-14487 Fix usage of wrong Map in PropertyAccessStrategyMapImpl

- hibernate-core/src/main/java/org/hibernate/engine/internal/UnsavedValueFactory.java
- hibernate-core/src/main/java/org/hibernate/engine/internal/Versioning.java
- hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java
- hibernate-core/src/main/java/org/hibernate/event/internal/DefaultFlushEntityEventListener.java
- hibernate-core/src/main/java/org/hibernate/internal/StatelessSessionImpl.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityVersionMapping.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/EntityVersionMappingImpl.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/internal/VersionTypeSeedParameterSpecification.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ByteJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/CalendarJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ClockHelper.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/DateJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/DbTimestampJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/InstantJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/IntegerJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/JdbcTimestampJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/LocalDateTimeJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/LongJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/OffsetDateTimeJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/PrimitiveByteArrayJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/RowVersionJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ShortJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/VersionJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ZonedDateTimeJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/internal/UserTypeVersionJavaTypeWrapper.java
https://hibernate.atlassian.net/browse/HHH-15135
> HHH-15135 Respect precision in temporal version types when generating timestamps

- gradle/libraries.gradle
- hibernate-core/src/main/java/org/hibernate/dialect/H2Dialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/H2DurationIntervalSecondJdbcType.java
Requires the changes from https://github.com/hibernate/hibernate-orm/pull/4901 to pass the H2 tests
> Update H2 to 2.1.210 and HSQLDB to 2.6.1

- documentation/src/main/asciidoc/userguide/appendices/Configurations.adoc
- documentation/src/test/java/org/hibernate/userguide/mapping/basic/DurationMappingLegacyTests.java
- hibernate-core/src/main/java/org/hibernate/boot/internal/SessionFactoryOptionsBuilder.java
- hibernate-core/src/main/java/org/hibernate/boot/model/process/spi/MetadataBuildingProcess.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingSessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataBuildingContext.java
- hibernate-core/src/main/java/org/hibernate/boot/spi/SessionFactoryOptions.java
- hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
- hibernate-core/src/main/java/org/hibernate/cfg/annotations/BasicValueBinder.java
- hibernate-core/src/main/java/org/hibernate/internal/util/config/ConfigurationHelper.java
- hibernate-core/src/main/java/org/hibernate/mapping/BasicValue.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/UUIDJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/JdbcTypeIndicators.java
- hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java
- hibernate-core/src/test/java/org/hibernate/orm/test/id/uuid/sqlrep/sqlchar/UuidAsCharAnnotationTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/id/uuid/sqlrep/sqlchar/UuidAsCharSettingTest.java
- migration-guide.adoc
https://hibernate.atlassian.net/browse/HHH-14672
> HHH-14672 - Allow specifying CHAR-based storage for UUID mappings

- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/DurationJavaType.java
> roll back breakage to DurationJavaType

- hibernate-core/src/main/java/org/hibernate/query/spi/AbstractSelectionQuery.java
https://hibernate.atlassian.net/browse/HHH-15157
> HHH-15157 Add HQL query to NoResultException

- tooling/metamodel-generator/hibernate-jpamodelgen.gradle
https://hibernate.atlassian.net/browse/HHH-15163
> HHH-15163 Switch from Java EE to Jakarta XML Binding dependency for jpamodelgen

- hibernate-core/src/main/java/org/hibernate/dialect/AbstractHANADialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/DerbyDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/OracleDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SybaseDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/ConcatPipeFunction.java
- hibernate-core/src/main/java/org/hibernate/dialect/function/LengthFunction.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/ArgumentTypesValidator.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/FunctionParameterType.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/produce/function/StandardFunctionArgumentTypeResolvers.java
- hibernate-core/src/main/java/org/hibernate/type/SqlTypes.java
- hibernate-core/src/test/java/org/hibernate/orm/test/lob/LobStringFunctionsTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/lob/LobStringTest.java
https://hibernate.atlassian.net/browse/HHH-15162
> HHH-15162 Add STRING_OR_CLOB FunctionParameterType and use that for various length functions

- hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeQueryImpl.java
https://hibernate.atlassian.net/browse/HHH-15168
> HHH-15168 Fix NPE in NativeQueryImpl.ParameterInterpretationImpl#toString

- hibernate-core/src/main/java/org/hibernate/mapping/Component.java
- https://hibernate.atlassian.net/browse/HHH-15184
> HHH-15184: Component optimisations

- documentation/src/test/java/org/hibernate/userguide/mapping/basic/TimeZoneStorageMappingTests.java
- hibernate-core/src/main/java/org/hibernate/cfg/annotations/BasicValueBinder.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/OffsetDateTimeJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ZonedDateTimeJavaType.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/InstantAsTimestampWithTimeZoneJdbcType.java
https://hibernate.atlassian.net/browse/HHH-15174
> HHH-15174 Move annotation handling code to common method for element collection and basic values

- hibernate-core/src/main/java/org/hibernate/dialect/Oracle12cDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/pagination/LimitHandler.java
- hibernate-core/src/main/java/org/hibernate/dialect/pagination/Oracle12LimitHandler.java
- hibernate-core/src/main/java/org/hibernate/loader/Loader.java
- hibernate-core/src/main/java/org/hibernate/loader/plan/exec/internal/AbstractLoadPlanBasedLoader.java
- hibernate-core/src/test/java/org/hibernate/dialect/Oracle12LimitHandlerTest.java
- hibernate-core/src/test/java/org/hibernate/test/limit/Oracle12LimitTest.java
- hibernate-core/src/test/java/org/hibernate/test/pagination/OraclePaginationTest.java
- hibernate-core/src/test/java/org/hibernate/test/pagination/OraclePaginationWithLocksTest.java
https://hibernate.atlassian.net/browse/HHH-14624
https://hibernate.atlassian.net/browse/HHH-14649
https://hibernate.atlassian.net/browse/HHH-14819
> HHH-14624 + HHH-14649 backport + test for HHH-14819

- hibernate-core/src/main/java/org/hibernate/jpa/internal/LegacySpecHelper.java
https://hibernate.atlassian.net/browse/HHH-15189
> HHH-15189 Print deprecation warning for lock timeout only when a value is passed

- gradle/libraries.gradle
- https://hibernate.atlassian.net/browse/HHH-15187
- https://hibernate.atlassian.net/browse/HHH-15188
> Micro upgrades for HCANN and Validator

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/ToOneAttributeMapping.java
- hibernate-core/src/main/java/org/hibernate/sql/exec/spi/ExecutionContext.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/association/toone/CriteriaQueryTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/CriteriaQueryTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/polymorphic/PolymorphicAssociationTest2.java
https://hibernate.atlassian.net/browse/HHH-15167
> HHH-15167  IllegalArgumentException occurred while calling setter for property 

- hibernate-core/src/main/java/org/hibernate/engine/spi/SubselectFetch.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batchfetch/SubselectFetchTest.java
https://hibernate.atlassian.net/browse/HHH-15202
> HHH-15202 Only create SubselectFetch if entity contains subselect fetch config

- gradle/libraries.gradle
- hibernate-core/hibernate-core.gradle
- https://hibernate.atlassian.net/browse/HHH-15204
> HHH-15204 Remove dependency to jakarta.activation:jakarta.activation-api

- gradle/libraries.gradle
https://hibernate.atlassian.net/browse/HHH-15208
> HHH-15208 Upgrade to Micrometer 1.8.4

- gradle/libraries.gradle
https://hibernate.atlassian.net/browse/HHH-15207
> HHH-15207 Upgrade GraalVM SDK to 22.0.0.2

- hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java
Rationale better described on JIRA:
- https://hibernate.atlassian.net/browse/HHH-15222
Also related to Quarkus integration.
> HHH-15222 Introduce a SessionLazyDelegator SPI

- hibernate-core/src/main/java/org/hibernate/resource/transaction/backend/jta/internal/JtaTransactionCoordinatorImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/IllegalArgumentExceptionTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/jpa/compliance/JtaIllegalArgumentExceptionTest.java
https://hibernate.atlassian.net/browse/HHH-15225
> HHH-15225 - Jta transactions,  name queries with errors throw IllegalStateException instead of IllegalArgumentException when transaction is not active

- hibernate-core/src/main/java/org/hibernate/sql/results/jdbc/internal/JdbcValuesCacheHit.java
https://hibernate.atlassian.net/browse/HHH-15221
> HHH-15221 fix a logging error in JdbcValuesCacheHit.java

- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/EntityIdentifierMapping.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/InverseNonAggregatedIdentifierMapping.java
- hibernate-core/src/main/java/org/hibernate/metamodel/mapping/internal/NonAggregatedIdentifierMappingImpl.java
- hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
- hibernate-core/src/test/java/org/hibernate/orm/test/entitymode/map/compositeId/CompId.hbm.xml
- hibernate-core/src/test/java/org/hibernate/orm/test/entitymode/map/compositeId/CompositeIdTest.java
https://hibernate.atlassian.net/browse/HHH-15201
> HHH 15201 Composite ID with dynamic-map entities fails with an exception 

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/EntityAsParamValueTest.java
https://hibernate.atlassian.net/browse/HHH-15233
> HHH-15233 Query NPE when using ":param IS NULL" and the parameter is an Entity 

- hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/sqm/param/EmptyEntityCollectionParameterTests.java
https://hibernate.atlassian.net/browse/HHH-15232
> HHH-15232 exception thrown when empty entity collection is provided for a query param

- documentation/src/main/asciidoc/userguide/appendices/BestPractices.adoc
https://hibernate.atlassian.net/browse/HHH-15238
Correct an appender setting and separate them into the bind and the extract settings.
> HHH-15238 - Documentation: update JDBC logging configuration for 6.0

- documentation/src/main/asciidoc/userguide/chapters/fetching/Fetching.adoc
https://hibernate.atlassian.net/browse/HHH-15154
> HHH-15154 tweak verbiage in user guide on FetchMode.SUBSELECT

- documentation/src/main/asciidoc/quickstart/guides/obtaining.adoc
https://hibernate.atlassian.net/browse/HHH-15224
> HHH-15224 update the module list in "getting started guide"

- hibernate-core/src/main/java/org/hibernate/boot/model/process/spi/MetadataBuildingProcess.java
- hibernate-core/src/main/java/org/hibernate/dialect/CockroachDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQLDialect.java
- hibernate-core/src/main/java/org/hibernate/dialect/SQLServerDialect.java
- hibernate-core/src/main/java/org/hibernate/type/SqlTypes.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/cockroachdb/CockroachDbContributor.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/postgis/AbstractPostGISJdbcType.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/postgis/PGGeographyJdbcType.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/postgis/PGGeometryJdbcType.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/postgis/PostgisDialectContributor.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/sqlserver/AbstractSqlServerGISType.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/sqlserver/SqlServerDialectContributor.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/sqlserver/SqlServerGeographyType.java
- hibernate-spatial/src/main/java/org/hibernate/spatial/dialect/sqlserver/SqlServerGeometryType.java
- hibernate-spatial/src/test/java/org/hibernate/spatial/mapping/GeographyMappingTest.java
https://hibernate.atlassian.net/browse/HHH-15165
> HHH-15165 Add support for SQL geography type

- hibernate-core/src/main/java/org/hibernate/sql/ast/tree/expression/QueryLiteral.java
- hibernate-core/src/test/java/org/hibernate/orm/test/mapping/converted/converter/literal/ConvertibleNullLiteralTest.java
https://hibernate.atlassian.net/browse/HHH-15246
Just another ticket about our old friend: NPE!
> HHH-15246 fix NPE when null value is set to Enum in query

- tooling/metamodel-generator/hibernate-jpamodelgen.gradle
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/annotation/MetaAttributeGenerationVisitor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/TypeRenderingVisitor.java
- tooling/metamodel-generator/src/main/java/org/hibernate/jpamodelgen/util/TypeUtils.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/CollectionAsBasicTypeTest.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/ConcreteLike.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/EnumHolder.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/Goods.java
- tooling/metamodel-generator/src/test/java/org/hibernate/jpamodelgen/test/collectionbasictype/Like.java
Since HHH-12338 caused some further issues, we need to also backport the fixes for these issues:
* https://hibernate.atlassian.net/browse/HHH-12338
* https://hibernate.atlassian.net/browse/HHH-14724
* https://hibernate.atlassian.net/browse/HHH-14768
> Backport of HHH-12338 to 5.3

- hibernate-core/src/main/java/org/hibernate/dialect/function/CommonFunctionFactory.java
- hibernate-core/src/main/java/org/hibernate/query/sqm/function/SqmFunctionRegistry.java
https://hibernate.atlassian.net/browse/HHH-15266
> HHH-15266 Fix NPE during function logging due to wrong character_length alternative key registration

- hibernate-core/src/main/java/org/hibernate/query/sqm/internal/QuerySqmImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/annotations/query/NamedQueryTest.java
https://hibernate.atlassian.net/browse/HHH-15263
Not sure my code changes are totally correct. Feel free to work on top of it or even close it.
> HHH-15263 - @NamedQuery is not supported with UPDATE statement

- hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java
- hibernate-core/src/test/java/org/hibernate/test/annotations/onetomany/OneToManyJoinColumnsUniquenessTest.java
https://hibernate.atlassian.net/browse/HHH-15091
> HHH-15091 EntityManager.persist does not verify the existence of the one side of a many-to-one relationship

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/LazyAttributeLoadingInterceptor.java
- hibernate-core/src/main/java/org/hibernate/internal/util/collections/CollectionHelper.java
Trivial.  I'll follow up with the PR for main soon, but only if necessary: I still need to check if this is actually a problem in 6 as well.
> HHH-15274 for branch 5.6

- hibernate-core/src/main/java/org/hibernate/engine/spi/SessionLazyDelegator.java
It would be really useful to have this SPI backported so that we can use the same integration in Quarkus while migrating to ORM 6.
It doesn't breack nor change any existing SPI so I see no problems with it.
> HHH-15222 backported

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/EnhancementAsProxyLazinessInterceptor.java
- hibernate-core/src/test/java/org/hibernate/test/bytecode/enhancement/version/VersionedEntityTest.java
https://hibernate.atlassian.net/browse/HHH-15134
> HHH-15134  Update a bytecode enanchhed Entity with a Version attribute causes OptimisticLockException

- hibernate-core/src/main/java/org/hibernate/bytecode/enhance/spi/interceptor/EnhancementAsProxyLazinessInterceptor.java
- hibernate-core/src/test/java/org/hibernate/orm/test/bytecode/enhancement/version/VersionedEntityTest.java
https://hibernate.atlassian.net/browse/HHH-15134
> HHH-15134 Update a bytecode enanchhed Entity with a Version attribute causes OptimisticLockException

- hibernate-core/src/main/java/org/hibernate/query/sql/internal/NativeNonSelectQueryPlanImpl.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/NativeQuerySchemaPlaceholderTest.java
https://hibernate.atlassian.net/browse/HHH-15269
> HHH-15269 Update NativeQuery unable to use h-schema placeholder, just emits placeholder contents into SQL

- hibernate-core/src/main/java/org/hibernate/engine/jdbc/batch/internal/BatchingBatch.java
- hibernate-core/src/test/java/org/hibernate/orm/test/batch/BatchTest.java
https://hibernate.atlassian.net/browse/HHH-15255
> HHH-15255 fix org.hibernate.orm.test.batch.BatchTest

- hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
- hibernate-core/src/main/java/org/hibernate/sql/ast/spi/AbstractSqlAstTranslator.java
- hibernate-core/src/main/java/org/hibernate/type/NullType.java
- hibernate-core/src/main/java/org/hibernate/type/StandardBasicTypes.java
- hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/NullJdbcType.java
- hibernate-core/src/test/java/org/hibernate/orm/test/query/SelectNullQueryTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/temporal/MySQL57TimestampFspFunctionTest.java
https://hibernate.atlassian.net/browse/HHH-15278
> HHH-15278 NPE when NULL is used in a query projection

- hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AbstractPluralAttribute.java
- hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/MetamodelJavaTypeTest.java
- hibernate-core/src/test/java/org/hibernate/orm/test/metamodel/TestEntity.java
https://hibernate.atlassian.net/browse/HHH-15285
> HHH-15285 Calling getJavaType() of @ElementCollection with basic types returns wrong type
